### PR TITLE
Notifications: Fixing blavatar image

### LINKED ISSUE #8190: Site Icon Does not Appear in Notifications
I came across this problem in this helpshift issue https://automattic.helpshift.com/admin/issue/239158/
The user had noticed that when they were looking at the notifications for their site that the icon for their site did not appear.  I have only been able to find one section of the notifications where this happens, and that is in list of new followers, but I checked Android and the problem seems to be limited to iOS.

screen shot 2017-11-17 at 15 29 55

(in the image all of the user gravatar images appear but the site icon does not)

### Steps to reproduce the behavior
1. In iOS go to the notifications with a set site icon
2. In the notifications find a notification about new followers and tap on it
3. In the expanded view of the notification there wont be a site icon for the site.

WordPress 8.7
iOS 11.1
Editor 2.0

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR fixes an issue that caused Blavatar images not to be properly downloaded / displayed.

Fixes #8190

Needs Review: @koke 

Sir, may i bug you with a quick patch?. I've got ~50 WPcom users, please, let me know if i can help you triggering a New Follower notification!

### To test:
1. Open WordPress.com and log into a sample site
2. Open the site's settings (thru the calypso admin) and upload a new Blavatar
3. Receive a New Follower notification
4. Open the Follower notification in iOS and expand it's details

Verify that the Top Header icon (in the Notification Details) properly displays a blavatar image.
It would appear that, now, Blavatars may be stored not just in gravatar.com.

### CODE REVIEW

**Comment by koke** [comment]
Have you checked out the helpers at `UIImageView+Gravatar`: `-[UIImageView setImageWithSiteIcon:placeholderImage:]`? It will deal with photon, blavatar, or plain site icon URLs

**Comment by jleandroperez** [comment]
@koke thanks for bringing that up!!. We **really** should merge all of those helpers into a single tool (and implemented in Swift).

Ready for another look!

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift [hunk 1]
```diff
@@ -32,14 +45,14 @@ class NoteBlockHeaderTableViewCell: NoteBlockTableViewCell {
 
 
     // MARK: - Public Methods
-    func downloadGravatarWithURL(_ url: URL?) {
-        if url == gravatarURL {
+    @objc func downloadGravatar(with url: URL?) {
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: 🤦‍♂️ I forgot to mention this on the previous review, but the `with` is not very Swifty IMO. I'd do `downloadGravatar(url:)` instead

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift [hunk 2]
```diff
@@ -32,14 +45,14 @@ class NoteBlockHeaderTableViewCell: NoteBlockTableViewCell {
...
+        guard url != gravatarURL else {
             return
         }
 
-        let placeholderImage = Style.gravatarPlaceholderImage
-        let gravatar = url.flatMap { Gravatar($0) }
-        gravatarImageView.downloadGravatar(gravatar, placeholder: placeholderImage, animate: true)
+        if let siteIconUrl = url?.absoluteString {
+            gravatarImageView.setImageWithSiteIcon(siteIconUrl, placeholderImage: Style.gravatarPlaceholderImage)
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: This works, but when the url is a gravatar URL instead of a site icon (e.g. comment notification), it will fetch the original unresized URL instead of the resized gravatar URL.

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift (hunk 1 above)
Comment (jleandroperez) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: According to the API Design Guidelines:

```
Strive for Fluent Usage
Prefer method and function names that make use sites form grammatical English phrases.
```

And the example there says:

```
AudioUnit.instantiate(
  with: description, 
  options: [.inProcess], completionHandler: stopProgressBar)
```

This one is actually swifty 😄 

[Ref. here!](https://swift.org/documentation/api-design-guidelines/)

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift (hunk 2 above)
Comment (jleandroperez) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: Let's address this in another PR, since it's a limitation of UIImageView+Gravatar.{h, m}, and may be affecting many other spots of the app.

Merging `UIImageView+Gravatar.swift` with `UIImageView+Gravatar.{h, m}` sounds like a fun project!

Comment (jleandroperez) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: [Filed here!](https://github.com/wordpress-mobile/WordPress-iOS/issues/8235)

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift (hunk 1 above)
Comment (koke) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: 😮 that's pretty clear, I don't know why I had interiorized the opposite. It still feels odd to me, but I'll take it.
However, I'd rename the Obj-C export `@objc(downloadGravatarWithURL:)`, it seems Swift isn't doing the conversion right here.

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift (hunk 2 above)
Comment (koke) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockHeaderTableViewCell.swift]: I don't think it's a problem with the helper (although 👍 to merging in Swift). The problem here is that `authorAvatarURL` is sometimes a gravatar and sometimes a site icon/blavatar. My take on it:

- Rename `downloadGravatar(with:)` to `downloadAuthorAvatar(with:)` (and other instances of `gravatar` with `authorAvatar`)
- Check if the url can be turned into a `Gravatar` and use `downloadGravatar`. Otherwise, treat it as a site icon, and use `setImageWithSiteIcon`

```swift
@objc(downloadAuthorAvatarWithURL:)
func downloadAuthorAvatar(with url: URL?) {
    guard url != authorAvatarURL else {
        return
    }

    authorAvatarURL = url

    guard let url = url else {
        authorAvatarImageView.image = Style.gravatarPlaceholderImage
        return
    }

    if let gravatar = Gravatar(url) {
        authorAvatarImageView.downloadGravatar(gravatar, placeholder: Style.gravatarPlaceholderImage, animate: true)
    } else {
        authorAvatarImageView.setImageWithSiteIcon(url.absoluteString)
    }
}
```

**Comment by jleandroperez** [comment]
@koke ready for another look! thanks for the feedback sir!

**Comment by jleandroperez** [comment]
Thanks for the review sir!
