### PR TITLE
Fix an issue with wrong cover images appearing in Reader

### LINKED ISSUE #13317: Wrong thumbnail in the reader on iOS 14.0 app
### Expected behavior
To see an image from the post as the thumbnail image as showing in the reader on https://wordpress.com/read/feeds/101350369

### Actual behavior
The latest post of this user’s site in the reader feed is showing an image from their media library and not linked to the post. The user deleted this image and the reader started showing a different unrelated image from the media library.

##### Tested on [device], iOS [version], WPiOS [version]
iOS app 14.0

#p1580316222001700-apps-slack

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/13317 by removing the questionable logic in https://github.com/wordpress-mobile/WordPressKit-iOS/pull/825. The app will no longer show random images as post covers – only actual featured images. 

**Note**: I opened a discussion about business logic. Web supports other display types for posts via `display_type`, which is something we'll likely need to also support in the future. Once we add support for featured media (different from "cover"), we can think about showing it there.

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>Modules/Package.swift</code> was changed without updating its corresponding <code>Package.resolved</code>. Please resolve the Swift packages as appropriate to your project setup (e.g. in Xcode or by running <code>swift package resolve</code>).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: Modules/Package.swift [hunk 1]
```diff
@@ -44,7 +44,7 @@ let package = Package(
         .package(url: "https://github.com/wordpress-mobile/MediaEditor-iOS", branch: "task/spm-support"),
         .package(url: "https://github.com/wordpress-mobile/NSObject-SafeExpectations", from: "0.0.6"),
         .package(url: "https://github.com/wordpress-mobile/NSURL-IDN", branch: "trunk"),
-        .package(url: "https://github.com/wordpress-mobile/WordPressKit-iOS", branch: "wpios-edition"),
+        .package(url: "https://github.com/wordpress-mobile/WordPressKit-iOS", branch: "fix/featured-images-reader-posts"),
```
Comment (kean) [inline Modules/Package.swift:47]: I added this PR for review too https://github.com/wordpress-mobile/WordPressKit-iOS/pull/825
