### PR TITLE
Fix screenshot date and time

### LINKED ISSUE #10449: Screenshots don't show the correct date / time / carrier info
### Expected behavior
The app should show the time as 9:41am in screenshots

### Actual behavior
It shows the time that the screenshots were built

### Suggested fix:
Use https://github.com/shinydevelopment/SimulatorStatusMagic to ensure consistency.

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes #10449 

**To test:**
Do a screenshot run. It should show the time as 9:41 am, with full bars for all the status icons (cellular strength, battery, etc)

### CODE REVIEW

File: Podfile [hunk 1]
```diff
@@ -104,6 +104,10 @@ target 'WordPress' do
     pod 'Starscream', '3.0.6'
     pod 'ZendeskSDK', '2.2.0'
 
+    ## Screenshot Generation Helper
+    ## ====================
+    ##
+    pod 'SimulatorStatusMagic', :configurations => ['Debug']
```
Comment (jtreanor) [inline Podfile]: Is it possible for the pod to be added to the `XCUITest` target itself? I know the target doesn't have access o the app, but perhaps it can still modify the simulator. If at all possible it would be nice to avoid adding code to the app purely for the purpose of testing.

**Comment by loremattei** [comment]
Hey! I'm moving this to 11.5 since 11.4 has been cut. If you want it to be into 11.4, please feel free to target the release branch and to ping me to build a new beta.

File: Podfile (hunk 1 above)
Comment (jtreanor) [reply Podfile]: Did you investigate adding this to the `XCUITest` target?

File: WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift [hunk 2]
```diff
@@ -8,6 +9,7 @@ class WordPressScreenshotGeneration: XCTestCase {
         super.setUp()
 
         // Put setup code here. This method is called before the invocation of each test method in the class.
+        SDStatusBarManager.sharedInstance()?.enableOverrides()
```
Comment (jtreanor) [inline WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift]: Why is this needed in addition to `IS_GENERATING_SCREENSHOTS=1` in the `Snapfile`?

File: Scripts/fastlane/Snapfile [hunk 3]
```diff
@@ -18,7 +18,12 @@ scheme "WordPressScreenshotGeneration"
 # clear_previous_screenshots true # remove the '#'' to clear all previously generated screenshots before creating new ones
 
 # Where is your project (or workspace)? Provide the full path here
-workspace "../../WordPress.xcworkspace"
+workspace File.expand_path File.dirname(__FILE__) + "../../WordPress.xcworkspace"
+
+# We use an xcarg, which attaches to an LLVM preprocessor directive.
+# This makes it possible to use a simple `#if IS_GENERATING_SCREENSHOTS`
+# in the code
+xcargs "IS_GENERATING_SCREENSHOTS=1"
```
Comment (jtreanor) [inline Scripts/fastlane/Snapfile]: It looks like this might not be used. Is this needed?
