### PR TITLE
Fix AutoLayout warnings in Blog Header and Posts

### LINKED ISSUE #14689: Bug: Warning about a tableView performing cell layout before its added to the view hierarchy.
When restoring state to the post list screen the following warning is logged to the console: 

> 2020-08-19 21:27:25.307107-0500 WordPress[75669:1495127] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x7fa72f01d200; frame = (0 0; 375 557); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7fa72e63e7a0>; layer = <CALayer: 0x7fa72e63a320>; contentOffset: {0, 0}; contentSize: {375, 106}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <UITableViewController: 0x7fa6ee45e570>>

It seems likely that during state restoration, somewhere tableView.reloadData is being called before a tableView is added to the view hierarchy.  It's not immediately clear if this is the post list's tableView or something else.  The error does not appear when restoring state to the site details screen, or the list of sites.  Nothing seems obviously broken but it's something we should probably address.

### Steps to reproduce the behavior
- Browse to a site's post list. 
- Background the app. 
- If you're in the simulator cancel the debugger at this point. If you're on a device you'll need to wait for the OS to terminate the app (do not force close). You can also restart your device.
- Launch the app again and look closely at what is logged to the console to find the warning.

### LINKED ISSUE #14690: Bug: Warnings about breaking constraints on the site details screen.
In the simulator, browse to any site details screen and observe the output to the console.  Currently there are numerous warnings about breaking constraints. 

### Examples: 
```
2020-08-19 21:27:25.397770-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ac7e0 UIView:0x7fa7185abd30.width == 326   (active)>",
    "<NSLayoutConstraint:0x7fa7185add30 H:[UIView:0x7fa7185abd30]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185ad1a0 H:|-(0)-[UIView:0x7fa7185abd30]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185ac7e0 UIView:0x7fa7185abd30.width == 326   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.400991-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa718597b50 UIButton:0x7fa718597820'More'.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7185ada00 V:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adc80 V:|-(16)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aefe0 V:|-(16)-[UIView:0x7fa6ee4c15d0]   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa7185af090 V:[UIView:0x7fa6ee4c15d0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa6ee536c20 'UISV-alignment' UIButton:0x7fa71858b0d0'Edit'.bottom == UIButton:0x7fa718597820'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538480 'UISV-alignment' UIButton:0x7fa71858b0d0'Edit'.top == UIButton:0x7fa718597820'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529240 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.top == UIView:0x7fa718586ec0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529330 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa718586ec0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee5351f0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa71858b0d0'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee534180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa71858b0d0'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa72e7e4e10 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.top == UIStackView:0x7fa718586d20.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee52b370 'UISV-canvas-connection' V:[UIStackView:0x7fa71858af10]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa72e7de900 'UISV-spacing' V:[UIStackView:0x7fa718586d20]-(8)-[UIStackView:0x7fa71858af10]   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528900 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee531a90 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa71858af10 )>",
    "<NSLayoutConstraint:0x7fa6ee543160 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa6ee4c13c0.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528630 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee5317c0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa71858af10 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa718597b50 UIButton:0x7fa718597820'More'.height == 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.427971-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ad950 H:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adb00 H:|-(0)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee53cec0 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.leading == UIStackView:0x7fa718586d20.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee523010 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.trailing == UIStackView:0x7fa718586d20.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529ad0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.leading == UIView:0x7fa718586ec0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee5295a0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.trailing == UIView:0x7fa718586ec0.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee516280 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.leading == UIStackView:0x7fa6ee4c1de0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538b50 'UISV-canvas-connection' H:[UIStackView:0x7fa6ee4c1de0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528800 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee528a00 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':UIStackView:0x7fa718586d20 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee5295a0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.trailing == UIView:0x7fa718586ec0.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.430865-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ad950 H:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adb00 H:|-(0)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51a6e0 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.leading == UIStackView:0x7fa6ee4c33c0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee53d120 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.trailing == UIStackView:0x7fa6ee4c33c0.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51b450 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee51bde0'UIViewLayoutMarginsGuide'.leading == UILabel:0x7fa6ee4c3770'Post Title'.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51d910 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee51bde0'UIViewLayoutMarginsGuide'.trailing == UILabel:0x7fa6ee4c3770'Post Title'.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee516280 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.leading == UIStackView:0x7fa6ee4c1de0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538b50 'UISV-canvas-connection' H:[UIStackView:0x7fa6ee4c1de0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51c0e0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x7fa6ee51bde0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x7fa6ee4c33c0 )>",
    "<NSLayoutConstraint:0x7fa6ee51c2e0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x7fa6ee51bde0'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':UIStackView:0x7fa6ee4c33c0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee51d910 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee51bde0'UIViewLayoutMarginsGuide'.trailing == UILabel:0x7fa6ee4c3770'Post Title'.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.433074-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ad950 H:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adb00 H:|-(0)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51a180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee518df0'UIViewLayoutMarginsGuide'.leading == WordPress.CachedAnimatedImageView:0x7fa6ee4c1f80.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51a540 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee518df0'UIViewLayoutMarginsGuide'.trailing == WordPress.CachedAnimatedImageView:0x7fa6ee4c1f80.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee516280 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.leading == UIStackView:0x7fa6ee4c1de0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538b50 'UISV-canvas-connection' H:[UIStackView:0x7fa6ee4c1de0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>",
    "<NSLayoutConstraint:0x7fa6ee519490 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x7fa6ee518df0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x7fa6ee4c1de0 )>",
    "<NSLayoutConstraint:0x7fa6ee519690 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x7fa6ee518df0'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':UIStackView:0x7fa6ee4c1de0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee51a540 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee518df0'UIViewLayoutMarginsGuide'.trailing == WordPress.CachedAnimatedImageView:0x7fa6ee4c1f80.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.435579-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ad950 H:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adb00 H:|-(0)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee53aa60 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.leading == UIStackView:0x7fa6ee4c5e30.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee51ed00 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.trailing == UIStackView:0x7fa6ee4c5e30.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee520e50 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee520170'UIViewLayoutMarginsGuide'.leading == UIView:0x7fa6ee4c5ff0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee520f90 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee520170'UIViewLayoutMarginsGuide'.trailing == UIView:0x7fa6ee4c5ff0.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee516280 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.leading == UIStackView:0x7fa6ee4c1de0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538b50 'UISV-canvas-connection' H:[UIStackView:0x7fa6ee4c1de0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>",
    "<NSLayoutConstraint:0x7fa6ee520430 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x7fa6ee520170'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x7fa6ee4c5e30 )>",
    "<NSLayoutConstraint:0x7fa6ee520630 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x7fa6ee520170'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':UIStackView:0x7fa6ee4c5e30 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee520f90 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee520170'UIViewLayoutMarginsGuide'.trailing == UIView:0x7fa6ee4c5ff0.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.438003-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ad950 H:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adb00 H:|-(0)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee53bdc0 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.leading == UIStackView:0x7fa738605bd0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee521090 'UISV-alignment' UIStackView:0x7fa6ee4c1de0.trailing == UIStackView:0x7fa738605bd0.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee522ce0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee521f60'UIViewLayoutMarginsGuide'.leading == UILabel:0x7fa718585710'Status'.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee522ec0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee521f60'UIViewLayoutMarginsGuide'.trailing == UILabel:0x7fa718585710'Status'.trailing   (active)>",
    "<NSLayoutConstraint:0x7fa6ee516280 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.leading == UIStackView:0x7fa6ee4c1de0.leading   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538b50 'UISV-canvas-connection' H:[UIStackView:0x7fa6ee4c1de0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 0   (active)>",
    "<NSLayoutConstraint:0x7fa6ee522260 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x7fa6ee521f60'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':UIStackView:0x7fa738605bd0 )>",
    "<NSLayoutConstraint:0x7fa6ee522460 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x7fa6ee521f60'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':UIStackView:0x7fa738605bd0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee522ec0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee521f60'UIViewLayoutMarginsGuide'.trailing == UILabel:0x7fa718585710'Status'.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.441109-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ada00 V:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adc80 V:|-(16)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aefe0 V:|-(16)-[UIView:0x7fa6ee4c15d0]   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa7185af090 V:[UIView:0x7fa6ee4c15d0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa6ee536c20 'UISV-alignment' UIButton:0x7fa71858b0d0'Edit'.bottom == UIButton:0x7fa718597820'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee538480 'UISV-alignment' UIButton:0x7fa71858b0d0'Edit'.top == UIButton:0x7fa718597820'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529240 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.top == UIView:0x7fa718586ec0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529330 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa718586ec0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee5351f0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa71858b0d0'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee534180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa71858b0d0'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa72e7e4e10 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.top == UIStackView:0x7fa718586d20.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee52b370 'UISV-canvas-connection' V:[UIStackView:0x7fa71858af10]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa72e7de900 'UISV-spacing' V:[UIStackView:0x7fa718586d20]-(8)-[UIStackView:0x7fa71858af10]   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528900 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee531a90 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa71858af10 )>",
    "<NSLayoutConstraint:0x7fa6ee543160 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa6ee4c13c0.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528630 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee5317c0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa71858af10 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ee534180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee5316d0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa71858b0d0'Edit'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.444236-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa718589870 V:|-(0)-[UILabel:0x7fa71857e870' ']   (active, names: '|':UIView:0x7fa718586ec0 )>",
    "<NSLayoutConstraint:0x7fa718587110 V:[UILabel:0x7fa71857e870' ']-(16)-[UILabel:0x7fa718587860' ']   (active)>",
    "<NSLayoutConstraint:0x7fa718589f80 V:[UILabel:0x7fa718587860' ']-(8)-[UILabel:0x7fa7185885c0' ']   (active)>",
    "<NSLayoutConstraint:0x7fa71858a080 V:[UILabel:0x7fa7185885c0' ']-(0)-|   (active, names: '|':UIView:0x7fa718586ec0 )>",
    "<NSLayoutConstraint:0x7fa7185ada00 V:[UIStackView:0x7fa6ee4c1c40]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185adc80 V:|-(16)-[UIStackView:0x7fa6ee4c1c40]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aefe0 V:|-(16)-[UIView:0x7fa6ee4c15d0]   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa7185af090 V:[UIView:0x7fa6ee4c15d0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa6ee4c13c0 )>",
    "<NSLayoutConstraint:0x7fa6ee529240 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.top == UIView:0x7fa718586ec0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee529330 'UISV-canvas-connection' UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa718586ec0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa72e7e4e10 'UISV-canvas-connection' UIStackView:0x7fa6ee4c1c40.top == UIStackView:0x7fa718586d20.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ee52b370 'UISV-canvas-connection' V:[UIStackView:0x7fa71858af10]-(0)-|   (active, names: '|':UIStackView:0x7fa6ee4c1c40 )>",
    "<NSLayoutConstraint:0x7fa72e7de900 'UISV-spacing' V:[UIStackView:0x7fa718586d20]-(8)-[UIStackView:0x7fa71858af10]   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528900 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa718586d20 )>",
    "<NSLayoutConstraint:0x7fa6ee543160 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa6ee4c13c0.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ee528630 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ee528540'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa718586d20 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa718587110 V:[UILabel:0x7fa71857e870' ']-(16)-[UILabel:0x7fa718587860' ']   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.734519-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185ac7e0 UIView:0x7fa7185abd30.width == 326   (active)>",
    "<NSLayoutConstraint:0x7fa7185add30 H:[UIView:0x7fa7185abd30]-(0)-|   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185ad1a0 H:|-(0)-[UIView:0x7fa7185abd30]   (active, names: '|':UIView:0x7fa6ee4c15d0 )>",
    "<NSLayoutConstraint:0x7fa7185aeee0 UIView:0x7fa6ee4c15d0.width == UITableViewCellContentView:0x7fa6ee4c13c0.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ee5430b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ee4c13c0.width == 375   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185ac7e0 UIView:0x7fa7185abd30.width == 326   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.795383-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7384f6470 UIView:0x7fa7384f59e0.width == 326   (active)>",
    "<NSLayoutConstraint:0x7fa7384f7990 H:[UIView:0x7fa7384f59e0]-(0)-|   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f6e60 H:|-(0)-[UIView:0x7fa7384f59e0]   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f8bd0 UIView:0x7fa7384d3150.width == UITableViewCellContentView:0x7fa7384d2d40.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ce83f800 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa7384d2d40.width == 375   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7384f6470 UIView:0x7fa7384f59e0.width == 326   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.798482-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7384e8ec0 UIButton:0x7fa7384e8b90'More'.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7384f7660 V:[UIStackView:0x7fa7384d38f0]-(0)-|   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f78e0 V:|-(16)-[UIStackView:0x7fa7384d38f0]   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f8cd0 V:|-(16)-[UIView:0x7fa7384d3150]   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa7384f8d80 V:[UIView:0x7fa7384d3150]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa6ce833610 'UISV-alignment' UIButton:0x7fa7384e12d0'Edit'.bottom == UIButton:0x7fa7384e8b90'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce834e70 'UISV-alignment' UIButton:0x7fa7384e12d0'Edit'.top == UIButton:0x7fa7384e8b90'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce826180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7384dcbf0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce826270 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7384dcbf0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8176b0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa7384e12d0'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce830c30 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7384e12d0'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce823c00 'UISV-canvas-connection' UIStackView:0x7fa7384d38f0.top == UIStackView:0x7fa7384dca30.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce835030 'UISV-canvas-connection' V:[UIStackView:0x7fa7384e1110]-(0)-|   (active, names: '|':UIStackView:0x7fa7384d38f0 )>",
    "<NSLayoutConstraint:0x7fa7384eb080 'UISV-spacing' V:[UIStackView:0x7fa7384dca30]-(8)-[UIStackView:0x7fa7384e1110]   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8258b0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7384dca30 )>",
    "<NSLayoutConstraint:0x7fa6ce82e5e0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7384e1110 )>",
    "<NSLayoutConstraint:0x7fa6ce83f8b0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa7384d2d40.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8255e0 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7384dca30 )>",
    "<NSLayoutConstraint:0x7fa6ce82e310 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7384e1110 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7384e8ec0 UIButton:0x7fa7384e8b90'More'.height == 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.801999-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7384f7660 V:[UIStackView:0x7fa7384d38f0]-(0)-|   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f78e0 V:|-(16)-[UIStackView:0x7fa7384d38f0]   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f8cd0 V:|-(16)-[UIView:0x7fa7384d3150]   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa7384f8d80 V:[UIView:0x7fa7384d3150]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa6ce833610 'UISV-alignment' UIButton:0x7fa7384e12d0'Edit'.bottom == UIButton:0x7fa7384e8b90'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce834e70 'UISV-alignment' UIButton:0x7fa7384e12d0'Edit'.top == UIButton:0x7fa7384e8b90'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce826180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7384dcbf0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce826270 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7384dcbf0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8176b0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa7384e12d0'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce830c30 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7384e12d0'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce823c00 'UISV-canvas-connection' UIStackView:0x7fa7384d38f0.top == UIStackView:0x7fa7384dca30.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce835030 'UISV-canvas-connection' V:[UIStackView:0x7fa7384e1110]-(0)-|   (active, names: '|':UIStackView:0x7fa7384d38f0 )>",
    "<NSLayoutConstraint:0x7fa7384eb080 'UISV-spacing' V:[UIStackView:0x7fa7384dca30]-(8)-[UIStackView:0x7fa7384e1110]   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8258b0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7384dca30 )>",
    "<NSLayoutConstraint:0x7fa6ce82e5e0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7384e1110 )>",
    "<NSLayoutConstraint:0x7fa6ce83f8b0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa7384d2d40.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8255e0 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7384dca30 )>",
    "<NSLayoutConstraint:0x7fa6ce82e310 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7384e1110 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ce830c30 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce82e220'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7384e12d0'Edit'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.805046-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7384dfa70 V:|-(0)-[UILabel:0x7fa7384dcdc0' ']   (active, names: '|':UIView:0x7fa7384dcbf0 )>",
    "<NSLayoutConstraint:0x7fa7384dd130 V:[UILabel:0x7fa7384dcdc0' ']-(16)-[UILabel:0x7fa7384ddac0' ']   (active)>",
    "<NSLayoutConstraint:0x7fa7384e0180 V:[UILabel:0x7fa7384ddac0' ']-(8)-[UILabel:0x7fa7384de7c0' ']   (active)>",
    "<NSLayoutConstraint:0x7fa7384e0280 V:[UILabel:0x7fa7384de7c0' ']-(0)-|   (active, names: '|':UIView:0x7fa7384dcbf0 )>",
    "<NSLayoutConstraint:0x7fa7384f7660 V:[UIStackView:0x7fa7384d38f0]-(0)-|   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f78e0 V:|-(16)-[UIStackView:0x7fa7384d38f0]   (active, names: '|':UIView:0x7fa7384d3150 )>",
    "<NSLayoutConstraint:0x7fa7384f8cd0 V:|-(16)-[UIView:0x7fa7384d3150]   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa7384f8d80 V:[UIView:0x7fa7384d3150]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa7384d2d40 )>",
    "<NSLayoutConstraint:0x7fa6ce826180 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7384dcbf0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce826270 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7384dcbf0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce823c00 'UISV-canvas-connection' UIStackView:0x7fa7384d38f0.top == UIStackView:0x7fa7384dca30.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce835030 'UISV-canvas-connection' V:[UIStackView:0x7fa7384e1110]-(0)-|   (active, names: '|':UIStackView:0x7fa7384d38f0 )>",
    "<NSLayoutConstraint:0x7fa7384eb080 'UISV-spacing' V:[UIStackView:0x7fa7384dca30]-(8)-[UIStackView:0x7fa7384e1110]   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8258b0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7384dca30 )>",
    "<NSLayoutConstraint:0x7fa6ce83f8b0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa7384d2d40.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce8255e0 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ce8254f0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7384dca30 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7384dd130 V:[UILabel:0x7fa7384dcdc0' ']-(16)-[UILabel:0x7fa7384ddac0' ']   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.862763-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185c8860 UIView:0x7fa7185c7f10.width == 326   (active)>",
    "<NSLayoutConstraint:0x7fa7185c9d50 H:[UIView:0x7fa7185c7f10]-(0)-|   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185c9220 H:|-(0)-[UIView:0x7fa7185c7f10]   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185caf90 UIView:0x7fa7185acbf0.width == UITableViewCellContentView:0x7fa718570e30.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ce911730 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa718570e30.width == 375   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185c8860 UIView:0x7fa7185c7f10.width == 326   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.865789-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185bb5c0 UIButton:0x7fa7185bb290'More'.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7185c9a20 V:[UIStackView:0x7fa72e53a840]-(0)-|   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185c9ca0 V:|-(16)-[UIStackView:0x7fa72e53a840]   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185cb090 V:|-(16)-[UIView:0x7fa7185acbf0]   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa7185cb140 V:[UIView:0x7fa7185acbf0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa6ce905500 'UISV-alignment' UIButton:0x7fa7185b3650'Edit'.bottom == UIButton:0x7fa7185bb290'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185fae20 'UISV-alignment' UIButton:0x7fa7185b3650'Edit'.top == UIButton:0x7fa7185bb290'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f4010 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7185a9b40.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f4100 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7185a9b40.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185e5600 'UISV-canvas-connection' UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa7185b3650'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185feac0 'UISV-canvas-connection' UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7185b3650'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185f26d0 'UISV-canvas-connection' UIStackView:0x7fa72e53a840.top == UIStackView:0x7fa7185a99a0.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f8b30 'UISV-canvas-connection' V:[UIStackView:0x7fa7185b3490]-(0)-|   (active, names: '|':UIStackView:0x7fa72e53a840 )>",
    "<NSLayoutConstraint:0x7fa7185d8360 'UISV-spacing' V:[UIStackView:0x7fa7185a99a0]-(8)-[UIStackView:0x7fa7185b3490]   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3740 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7185a99a0 )>",
    "<NSLayoutConstraint:0x7fa7185fc470 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7185b3490 )>",
    "<NSLayoutConstraint:0x7fa6ce9117e0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa718570e30.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3470 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7185a99a0 )>",
    "<NSLayoutConstraint:0x7fa7185fc1a0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7185b3490 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185bb5c0 UIButton:0x7fa7185bb290'More'.height == 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.885808-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185c9a20 V:[UIStackView:0x7fa72e53a840]-(0)-|   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185c9ca0 V:|-(16)-[UIStackView:0x7fa72e53a840]   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185cb090 V:|-(16)-[UIView:0x7fa7185acbf0]   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa7185cb140 V:[UIView:0x7fa7185acbf0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa6ce905500 'UISV-alignment' UIButton:0x7fa7185b3650'Edit'.bottom == UIButton:0x7fa7185bb290'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185fae20 'UISV-alignment' UIButton:0x7fa7185b3650'Edit'.top == UIButton:0x7fa7185bb290'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f4010 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7185a9b40.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f4100 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7185a9b40.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185e5600 'UISV-canvas-connection' UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa7185b3650'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185feac0 'UISV-canvas-connection' UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7185b3650'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185f26d0 'UISV-canvas-connection' UIStackView:0x7fa72e53a840.top == UIStackView:0x7fa7185a99a0.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f8b30 'UISV-canvas-connection' V:[UIStackView:0x7fa7185b3490]-(0)-|   (active, names: '|':UIStackView:0x7fa72e53a840 )>",
    "<NSLayoutConstraint:0x7fa7185d8360 'UISV-spacing' V:[UIStackView:0x7fa7185a99a0]-(8)-[UIStackView:0x7fa7185b3490]   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3740 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7185a99a0 )>",
    "<NSLayoutConstraint:0x7fa7185fc470 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7185b3490 )>",
    "<NSLayoutConstraint:0x7fa6ce9117e0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa718570e30.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3470 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7185a99a0 )>",
    "<NSLayoutConstraint:0x7fa7185fc1a0 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7185b3490 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185feac0 'UISV-canvas-connection' UILayoutGuide:0x7fa7185fc0b0'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa7185b3650'Edit'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.889001-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa7185abca0 V:|-(0)-[UILabel:0x7fa7185a89f0' ']   (active, names: '|':UIView:0x7fa7185a9b40 )>",
    "<NSLayoutConstraint:0x7fa7185a9d00 V:[UILabel:0x7fa7185a89f0' ']-(16)-[UILabel:0x7fa7185a9f30' ']   (active)>",
    "<NSLayoutConstraint:0x7fa7185b1650 V:[UILabel:0x7fa7185a9f30' ']-(8)-[UILabel:0x7fa7185aa9f0' ']   (active)>",
    "<NSLayoutConstraint:0x7fa7185b1750 V:[UILabel:0x7fa7185aa9f0' ']-(0)-|   (active, names: '|':UIView:0x7fa7185a9b40 )>",
    "<NSLayoutConstraint:0x7fa7185c9a20 V:[UIStackView:0x7fa72e53a840]-(0)-|   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185c9ca0 V:|-(16)-[UIStackView:0x7fa72e53a840]   (active, names: '|':UIView:0x7fa7185acbf0 )>",
    "<NSLayoutConstraint:0x7fa7185cb090 V:|-(16)-[UIView:0x7fa7185acbf0]   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa7185cb140 V:[UIView:0x7fa7185acbf0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa718570e30 )>",
    "<NSLayoutConstraint:0x7fa7185f4010 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.top == UIView:0x7fa7185a9b40.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f4100 'UISV-canvas-connection' UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa7185a9b40.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa7185f26d0 'UISV-canvas-connection' UIStackView:0x7fa72e53a840.top == UIStackView:0x7fa7185a99a0.top   (active)>",
    "<NSLayoutConstraint:0x7fa7185f8b30 'UISV-canvas-connection' V:[UIStackView:0x7fa7185b3490]-(0)-|   (active, names: '|':UIStackView:0x7fa72e53a840 )>",
    "<NSLayoutConstraint:0x7fa7185d8360 'UISV-spacing' V:[UIStackView:0x7fa7185a99a0]-(8)-[UIStackView:0x7fa7185b3490]   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3740 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa7185a99a0 )>",
    "<NSLayoutConstraint:0x7fa6ce9117e0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa718570e30.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa7185f3470 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa7185f3380'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa7185a99a0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa7185a9d00 V:[UILabel:0x7fa7185a89f0' ']-(16)-[UILabel:0x7fa7185a9f30' ']   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.948786-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa6ce7a0b00 UIView:0x7fa6ce7a01b0.width == 326   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7a1ff0 H:[UIView:0x7fa6ce7a01b0]-(0)-|   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a14c0 H:|-(0)-[UIView:0x7fa6ce7a01b0]   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a3230 UIView:0x7fa6ce77dde0.width == UITableViewCellContentView:0x7fa6ce77dc30.width   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7e5940 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x7fa6ce77dc30.width == 375   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ce7a0b00 UIView:0x7fa6ce7a01b0.width == 326   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.951822-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa6ce793860 UIButton:0x7fa6ce793530'More'.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7a1cc0 V:[UIStackView:0x7fa6ce77e4a0]-(0)-|   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a1f40 V:|-(16)-[UIStackView:0x7fa6ce77e4a0]   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a3330 V:|-(16)-[UIView:0x7fa6ce77dde0]   (active, names: '|':UITableViewCellContentView:0x7fa6ce77dc30 )>",
    "<NSLayoutConstraint:0x7fa6ce7a33e0 V:[UIView:0x7fa6ce77dde0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa6ce77dc30 )>",
    "<NSLayoutConstraint:0x7fa6ce7d9750 'UISV-alignment' UIButton:0x7fa6ce78be80'Edit'.bottom == UIButton:0x7fa6ce793530'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7dafb0 'UISV-alignment' UIButton:0x7fa6ce78be80'Edit'.top == UIButton:0x7fa6ce793530'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cc2c0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide'.top == UIView:0x7fa6ce7877a0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cc3b0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa6ce7877a0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7bd8a0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa6ce78be80'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7d6d70 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa6ce78be80'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee565540 'UISV-canvas-connection' UIStackView:0x7fa6ce77e4a0.top == UIStackView:0x7fa6ce7875e0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7db170 'UISV-canvas-connection' V:[UIStackView:0x7fa6ce78bcc0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ce77e4a0 )>",
    "<NSLayoutConstraint:0x7fa6ee55f000 'UISV-spacing' V:[UIStackView:0x7fa6ce7875e0]-(8)-[UIStackView:0x7fa6ce78bcc0]   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cb9f0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa6ce7875e0 )>",
    "<NSLayoutConstraint:0x7fa6ce7d4720 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa6ce78bcc0 )>",
    "<NSLayoutConstraint:0x7fa6ce7e59f0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa6ce77dc30.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cb720 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa6ce7875e0 )>",
    "<NSLayoutConstraint:0x7fa6ce7d4450 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa6ce78bcc0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ce793860 UIButton:0x7fa6ce793530'More'.height == 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-19 21:27:25.955263-0500 WordPress[75669:1495127] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7fa6ce7a1cc0 V:[UIStackView:0x7fa6ce77e4a0]-(0)-|   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a1f40 V:|-(16)-[UIStackView:0x7fa6ce77e4a0]   (active, names: '|':UIView:0x7fa6ce77dde0 )>",
    "<NSLayoutConstraint:0x7fa6ce7a3330 V:|-(16)-[UIView:0x7fa6ce77dde0]   (active, names: '|':UITableViewCellContentView:0x7fa6ce77dc30 )>",
    "<NSLayoutConstraint:0x7fa6ce7a33e0 V:[UIView:0x7fa6ce77dde0]-(0)-|   (active, names: '|':UITableViewCellContentView:0x7fa6ce77dc30 )>",
    "<NSLayoutConstraint:0x7fa6ce7d9750 'UISV-alignment' UIButton:0x7fa6ce78be80'Edit'.bottom == UIButton:0x7fa6ce793530'More'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7dafb0 'UISV-alignment' UIButton:0x7fa6ce78be80'Edit'.top == UIButton:0x7fa6ce793530'More'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cc2c0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide'.top == UIView:0x7fa6ce7877a0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cc3b0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide'.bottom == UIView:0x7fa6ce7877a0.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7bd8a0 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide'.top == UIButton:0x7fa6ce78be80'Edit'.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7d6d70 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa6ce78be80'Edit'.bottom   (active)>",
    "<NSLayoutConstraint:0x7fa6ee565540 'UISV-canvas-connection' UIStackView:0x7fa6ce77e4a0.top == UIStackView:0x7fa6ce7875e0.top   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7db170 'UISV-canvas-connection' V:[UIStackView:0x7fa6ce78bcc0]-(0)-|   (active, names: '|':UIStackView:0x7fa6ce77e4a0 )>",
    "<NSLayoutConstraint:0x7fa6ee55f000 'UISV-spacing' V:[UIStackView:0x7fa6ce7875e0]-(8)-[UIStackView:0x7fa6ce78bcc0]   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cb9f0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa6ce7875e0 )>",
    "<NSLayoutConstraint:0x7fa6ce7d4720 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':UIStackView:0x7fa6ce78bcc0 )>",
    "<NSLayoutConstraint:0x7fa6ce7e59f0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa6ce77dc30.height == 44   (active)>",
    "<NSLayoutConstraint:0x7fa6ce7cb720 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x7fa6ce7cb630'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa6ce7875e0 )>",
    "<NSLayoutConstraint:0x7fa6ce7d4450 'UIView-topMargin-guide-constraint' V:|-(8)-[UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa6ce78bcc0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fa6ce7d6d70 'UISV-canvas-connection' UILayoutGuide:0x7fa6ce7d4360'UIViewLayoutMarginsGuide'.bottom == UIButton:0x7fa6ce78be80'Edit'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #14690
Fixes #14689

This PR fixes warnings in:

* `BlogDetailHeaderView`
* `PostCardCell`
* `PostListViewController`
* Some debug code was removed

#### No warnings when running the app

1. Run the app
1. Check that no Autolayout warnings are shown
1. Check that no "[TableView] Warning once only: UITableView was told to layout its visible cells and other (...)" warnings are shown

#### No warnings when showing posts

1. Run the app
1. Tap "Blog Posts" on any site
1. Check that no Autolayout warnings are shown
1. Check that no "[TableView] Warning once only: UITableView was told to layout its visible cells and other (...)" warnings are shown

#### No visual changes in Blog Header

1. Run the app
1. Tap any blog
1. Check the site header, there shouldn't be any changes or regressions

#### No visual changes in Blog Posts

1. Run the app
1. Tap any blog
1. Tap Blog Posts
1. Check the large post cells (not the compact one), there shouldn't be any changes or regressions

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/System/WordPressAppDelegate.swift [hunk 1]
```diff
@@ -107,17 +107,6 @@ class WordPressAppDelegate: UIResponder, UIApplicationDelegate {
     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
         DDLogInfo("didFinishLaunchingWithOptions state: \(application.applicationState)")
 
-        let queue = DispatchQueue(label: "asd", qos: .background)
```
Comment (frosty) [inline WordPress/Classes/System/WordPressAppDelegate.swift:110]: Huh, I wonder why this was even there...

**Review by Gio2018 — CHANGES_REQUESTED** [review]
Hi @leandroalonso , the first step works fine on iPhone, but when running it on iPad Air 2 with iPadOS 13.7, I got both the `[TableView]...` error and constraint breaking warnings. Here's the console log I got

[console.log](https://github.com/wordpress-mobile/WordPress-iOS/files/5234811/console.log)

**Comment by leandroalonso** [comment]
@Gio2018 I fixed some warnings happening in iPad under the Post List, however, they're not the same as the ones in the log you shared.

This PR fixes warnings only for the blog header and the post list. Probably some other places have those warnings too, but they're out of scope for this PR. Based on your logs I think that they come from notifications or stats, not sure though.

Would you mind testing again and checking there are no warnings for Post List?

**Review by Gio2018 — COMMENTED** [review]
Hi @leandroalonso ! If I force the state restoration to open on "Blog Posts" (should this condition be added to the test steps?), then I don't see the constraints warning anymore. I do still see the `[TableView] Warning once only:` in the console log.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 2]
```diff
@@ -298,6 +303,10 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
     }
 
     func showCompactOrDefault() {
+        guard isViewOnScreen() else {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: How come this is necessary now? Is it because of the call for this method being moved to viewWillAppear?

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 3]
```diff
@@ -213,7 +218,7 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
 
     /// Update the `GhostOptions` to correctly show compact or default cells
     private func updateGhostableTableViewOptions() {
-        let ghostOptions = GhostOptions(displaysSectionHeader: false, reuseIdentifier: postCellIdentifier, rowsPerSection: [10])
+        let ghostOptions = GhostOptions(displaysSectionHeader: false, reuseIdentifier: postCellIdentifier, rowsPerSection: [50])
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift:221]: Curious: why do we need to add more rows here?

**Review by frosty — COMMENTED** [review]
Thanks for working on these! I can confirm on iPhone I'm not seeing layout warnings any more. I am still seeing quite a few warnings on iPad, but it's hard to tell if those are coming from other parts of the app or not (I think they probably are). Just left a few small questions!

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 3 above)
Comment (Gio2018) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift:221]: +1

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 2 above)
Comment (Gio2018) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Should we just move it to `viewDidAppear`?

**Review by Gio2018 — APPROVED** [review]
Hi @leandroalonso , thanks for pointing me in the right direction: the `[Tableview]..` warning was indeed related to Notifications. Just left a couple more comments, otherwise it's good to go for me!

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 3 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift:221]: One image can explain:



50 is a lot, but given that rows are rendered only when they appear on screen I just added more so we can be better prepared even for an upcoming Apple device with a huge screen. :P

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 2 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: This method is called when `isCompact` is changed (and it's changed in a few different places).

Moving it to `viewDidAppear` doesn't fix the issue, it will require a bigger refactor. However, after testing again I saw that this was causing some problems with icons and labels not being properly set.

I changed this method in 38c10d0768f9dd4351f7f799a951f54149fbfefe

Now, it will be executed, but it will only reload the tableView if the view is on screen.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 3 above)
Comment (frosty) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift:221]: 😬

**Comment by aerych** [comment]
🎉 Yay!
