### PR TITLE
Account Creation: Fix broken flow after signing up from the WordPress app

### LINKED ISSUE #21746: WordPress: Migration phase incorrect for first time users
### Expected behavior
After a new user creates an account, they should be presented with the final migration flow UI.

### Actual behavior
New users see different phases of the migration depending on when the remote feature flags are fetched.

### Steps to reproduce the behavior

1. Delete both WordPress and Jetpack to prevent any shared or cached data
2. Install WordPress
3. Create a new account
4. Background the app, do not close it
5. Confirm your new account's email on the same device
6. After navigating back to the WordPress app, observe Jetpack features

### Video

https://github.com/wordpress-mobile/WordPress-iOS/assets/2454408/b09238bd-4d1e-45e3-ba2f-bc3cf41670c9

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #21746
## Description
This PR fixes an issue where users signing up on the WordPress app land on the Reader while it should not be accessible. 

The PR also introduces logic for synchronizing calls to fetch the remote feature flags, making sure that the latest network call is always respected regardless of when the response comes. This is to avoid the following scenario:
1. Unauthenticated request to fetch feature flags made (Request A)
2. User logs in
3. Authenticated request to fetch feature flags made (Request B)
4. Response for request B returned and values updated
5. ❌  Response for request a returned and values overridden

## Testing Instructions

1. Delete both WordPress and Jetpack apps
2. Install WordPress
3. Create a new account via email
4. Background the app, do not close it
5. Confirm your new account's email on the same device
6. You should be navigated back to the WordPress app automatically
7. Tap "Done"
8. Tap "Not right now"
9. ✅ Make sure that you land on My Site with the tab bar & Jetpack features hidden 

## Regression Notes
1. Potential unintended areas of impact
Sign up flow on Jetpack

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/System/RootViewCoordinator.swift [hunk 1]
```diff
@@ -87,6 +87,18 @@ class RootViewCoordinator {
         self.rootViewPresenter = nil
     }
 
+    func showPostSignUpTabForNotSites() {
```
Comment (wargcm) [inline WordPress/Classes/System/RootViewCoordinator.swift]: There might be a minor typo here with the name. Is it supposed to be this?
```suggestion
    func showPostSignUpTabForNoSites() {
```

**Review by wargcm — APPROVED** [review]
LGTM! There was just a minor typo with a function name, but everything works 🎉

File: WordPress/Classes/System/RootViewCoordinator.swift (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/System/RootViewCoordinator.swift]: Nice catch! Fixed in e5b010b298bba6530a35ee92ebb39acc664c2ef1

File: WordPress/Classes/Stores/RemoteFeatureFlagStore.swift [hunk 2]
```diff
@@ -85,3 +92,43 @@ extension RemoteFeatureFlagStore {
...
+            }
+            switch result {
+                case .success(let flags):
+                    DDLogInfo("🚩 Successfully updated local feature flags: \(flags.dictionaryValue)")
+                    self?.completion(.success(flags.dictionaryValue))
+                case .failure(let error):
+                    DDLogError("🚩 Unable to update Feature Flag Store: \(error.localizedDescription)")
+                    self?.completion(.failure(error))
+            }
+            self?.state = .isFinished
```
Comment (mokagio) [inline WordPress/Classes/Stores/RemoteFeatureFlagStore.swift:131]: Unless I'm reading the code wrong, if `self` is `nil`, nothing will happen other than console logs.

Have you considered returning early with `guard let self else { return }`?

File: WordPress/WordPressTest/JetpackFeaturesRemovalCoordinatorTests.swift [hunk 3]
```diff
@@ -346,3 +346,13 @@ private extension Date {
...
+
+internal extension RemoteFeatureFlagStore {
+    func update(using remote: FeatureFlagRemote, waitOn test: XCTestCase) {
+        let exp = test.expectation(description: "Store finishes update")
+        update(using: remote) {
+            exp.fulfill()
+        }
+        test.wait(for: [exp], timeout: 1)
+    }
+}
```
Comment (mokagio) [inline WordPress/WordPressTest/JetpackFeaturesRemovalCoordinatorTests.swift:358]: Interesting approach. For a moment I got worried because it looked like the test was no longer testing application code, but then I looked at the implementation and realized it called the app code internally.

This has definitely value because it DRYes what would otherwise be a lot of repeated async expectations.

I wonder if the DRY could be pushed even further. Most tests have a similar arrange structure:

```swift
        let store = ...
        let flags = ...
        let remote = ...
        store.update(using: remote, waitOn: self)
```

**Review by mokagio — COMMENTED** [review]
I landed on this PR while checking the editorialized release notes.
