### PR TITLE
Fix/site header layout fixes

### LINKED ISSUE #14617: Site header has too much spacing inside
### Expected behavior
I'm not sure if this assumption is correct but if the site bio doesn't exist, the site header has too much additional spacing inside. Haven't been able to reproduce this visual bug when there's a site bio. Description of actual/expected behavior:

Screen Shot 2020-08-11 at 2 49 40 PM

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xs, iOS 13.6

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #14617 and #14618 
To test:

Site name trailing 
1. Go to reader
2. Tap on a site name in the post card (a site with a long name like theinquisitivebee.co.uk)
3. See that the site name doesn't get cut and has a 16 trailing to superview.

Empty site description 
1. Go to reader
2. Tap on a site name in the post card (a site that doesn't have description like aerych.blog)
3. See that the header bottom is 16 to image bottom .

Make sure the header looks as expected with 1 liner and long description

Simulator Screen Shot - iPhone 11 Pro - 2020-08-11 at 17 52 07
Simulator Screen Shot - iPhone 11 Pro - 2020-08-11 at 18 19 02

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by emilylaguna — CHANGES_REQUESTED** [review]
Heya! 👋 The wrapping of the site header is working well, but I noticed a few issues:

When I tap the follow button on a site that does not have a description, the application crashes:
```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/emilylaguna/Desktop/Work/WordPress-iOS/WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift, line 88
2020-08-12 12:27:41.702938-0400 WordPress[23883:194151] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/emilylaguna/Desktop/Work/WordPress-iOS/WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift, line 88
```


---

I am not seeing the 16px right margin as indicated here: https://github.com/wordpress-mobile/WordPress-iOS/issues/14618 when the site title is just long enough

Screen Shot 2020-08-12 at 12 10 26 PM

---

The gap between the site icon / followers label seems pretty large, is this intended?

Screen Shot 2020-08-12 at 12 17 21 PM

---

When in a RTL language the follow title overlaps the follow icon:

Screen Shot 2020-08-12 at 12 24 21 PM

---

If I tap and hold on the follow button the title text disappears

**Review by emilylaguna — CHANGES_REQUESTED** [review]
I did some further testing with a small screen device and encountered a overlap issue:

Screen Shot 2020-08-12 at 1 06 12 PM

**Comment by yaelirub** [comment]
>I did some further testing with a small screen device and encountered a overlap issue:

Not sure how you get to this screen but I see:
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-12 at 10 21 09

It's weird because you don't even have the back title in the navigation?

**Comment by yaelirub** [comment]
Hey @emilylaguna , thanks for the through review 🙏 
>When I tap the follow button on a site that does not have a description, the application crashes:

I couldn't reproduce. Maybe because I removed the deactivation of the constraint. 

>I am not seeing the 16px right margin as indicated here: #14618 when the site title is just long enough

Couldn't reproduce. 

>The gap between the site icon / followers label seems pretty large, is this intended?

Its20px by design:
Screen Shot 2020-08-12 at 12 19 33 PM

>I did some further testing with a small screen device and encountered a overlap issue:

Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14622/commits/e7d5c9c3f85bb7520a360b79ac7731384f27a2eb

Ready for another look

File: WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift [hunk 1]
```diff
@@ -85,8 +85,7 @@ fileprivate func > <T: Comparable>(lhs: T?, rhs: T?) -> Bool {
         WPStyleGuide.applyReaderFollowButtonStyle(followButton)
 
         if siteTopic.siteDescription.isEmpty {
-            descriptionLableTopConstraint.isActive = false
-            descriptionLabel.topAnchor.constraint(equalTo: avatarImageView.bottomAnchor, constant: 0.0).isActive = true
+            descriptionLableTopConstraint.constant = 0.0
```
Comment (emilylaguna) [inline WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift:88]:
```suggestion
            descriptionLabelTopConstraint.constant = 0.0
```

**Review by emilylaguna — CHANGES_REQUESTED** [review]
This is working for me now, 1 final typo fix and we'll be ready to :shipit:

File: WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift (hunk 1 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift]: updated here 75ca4e7

**Review by emilylaguna — APPROVED** [review]
:shipit:
