### PR TITLE
Use frame-nonce to authenticate Jetpack previews

### LINKED ISSUE #5693: Blog Posts: Preview for self-hosted site without Jetpack returns a 404 error
### Expected behavior

I expect to be able to preview blog posts on self-hosted sites without Jetpack.
### Actual behavior

If I try to preview a post (using the Preview link in the Blog Posts list, or the preview eye icon in the editor), I end up on the WP Admin login screen with an authentication error:

> ERROR: The password you entered for the username [self-hosted username] is incorrect. Lost your password?
### Steps to reproduce the behavior
1. Add a self-hosted site without Jetpack to the app
2. Create a draft post in the site
3. Save the draft to the site's server (not a local draft)
4. Tap the "Preview" link in the Blog Posts list. Result: Instead of a preview you see the site's login screen
5. Open the draft in the editor again and tap the preview icon. Result: Instead of a preview you see the site's login screen
### Screenshots

self-hosted post preview
##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.4.0.20160707.1

I also tested this in the latest stable version 6.3, and the same bug occurs there so this is not a new issue in 6.4.

### PR DESCRIPTION
**Pull request by koke**
This uses the same `frame-nonce` system that calypso uses to load previews that would otherwise require authentication on Jetpack sites where we don't have credentials to log in.

There's a lot more background in the comments in #5693, only I found out that a `frame-nonce` is only useful for Jetpack sites. WordPress.com will return a 404 if signed out for a preview that needs auth, even if the `frame-nonce` is present. For the purposes of this issue though, that's OK, as we only needed to fix it for Jetpack sites for now.

Fixes #5693 

What I tested:

✅ Real preview used
❌ Fake preview used

| wp.com                            | wp.com             | Jetpack            | Self Hosted        |
|-----------------------------------|--------------------|--------------------|--------------------|
| New draft                         | :x:                | :x:                | :x:                |
| Saved draft                       | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Saved draft with local changes    | :x:                | :x:                | :x:                |
| Published post                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Published post with local changes | :x:                | :x:                | :x:                |
| Scheduled post                    | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Saved draft on private blog       | :white_check_mark: | :woman_shrugging:  | :woman_shrugging:  |

Needs review: @aerych

### CODE REVIEW

**Comment by koke** [comment]
> Not sure why this branch is still showing so many changes after its dependent PR was merged.

Because I hadn't merged develop in yet.

File: WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift [hunk 1]
```diff
@@ -16,27 +16,20 @@ class PostPreviewGenerator: NSObject {
     }
 
     func generate() {
-        guard let link = post.permaLink,
-            let url = URL(string: link),
+        guard let url = post.permaLink.flatMap(URL.init(string:)),
             !post.hasLocalChanges() else {
-                showFakePreview()
-                return
+                return showFakePreview()
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift]: Agreed. I found it a bit annoying to have the two lines everywhere, but I see how it can be way more confusing to `return Void`

**Comment by koke** [comment]
Ready for another look

**Comment by aerych** [comment]
:shipit: with great 🚢 ing sir!
