### PR TITLE
[VoiceOver] Add accessibility to Post List buttons

### LINKED ISSUE #12870: Pages: add button is read wrongly as "Button. Possibly add." with VoiceOver
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. In the WordPress app, go to My Site > Site Pages.
1. Swipe right until you reach the add button and observe how it is read out.

**Result:** the add button is read wrongly as "Button. Possibly add." and should be something like. "Add page. Button." ([2s](https://cloudup.com/cM_A3uh0zmw))

pages-add-button
<sup>Tested with WPiOS 13.5.0.3 (App Store version) on iPhone 6S iOS 13.2.</sup>

<p style="clear:both;"><sub>/hat tip @etoledom for the report, internal reference: p77Llu-bQ6-p2</sub></p>

### LINKED ISSUE #12872: Posts List: list view and add buttons are read incorrectly with VoiceOver
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. In the WordPress app, go to My Site > Blog Posts.
1. Swipe right to reach the buttons in the header for toggling compact and expanded view modes and for adding a new post.

**Result:** the compact list view button is read as "Button. Possibly menu." and should be something like "Switch to compact list view. Button." the expanded list view button is read as "Button." and should be something like "Switch to expanded list view. Button." and the add buton is read as "Button. Possibly add." and should be something like "Add new post. Button." ([5s](https://cloudup.com/cD6_Yuu34pZ))

posts-list-add-button
<sup>Tested with WPiOS 13.5.0.3 (App Store version) on iPhone 6S iOS 13.2.</sup>

<p style="clear:both;"><sub>/hat tip @etoledom for the report, internal reference: p77Llu-bQ6-p2</sub></p>

### PR DESCRIPTION
**Pull request by vphong**
Fixes #12872, Fixes #12870 with issues addressed in #13038. I apologize @shiki, I was having issues building and didn't realize deleting the remote branch would close the other pull request. The issues you brought up have been taken care of, though!

To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
Hi @vphong! No worries. 

It looks like there are some unrelated commits in this PR: 

image

Would you mind removing those first? You'd probably need to `rebase` on `develop`. Or a new branch based off of `develop` would probably be easier.

**Comment by vphong** [comment]
@shiki Sorry about that, taken care of now.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 1]
```diff
@@ -296,6 +296,8 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
         updateGhostableTableViewOptions()
         ghostableTableView.reloadSections([0], with: .automatic)
 
+        postsViewButtonItem.accessibilityLabel = NSLocalizedString("List style", comment: "List display style")
```
Comment (shiki) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Usually, the `comment` would also describe where it can be found and how it is used. My suggestion would be something along the lines of:

```
The accessibility label for the list style button in the Post List.
```

It gives some context for the translator and also helps them find that button in the app. 

Feel free to improve the other `NSLocalizedString` you created in this PR too. 🙂

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 2]
```diff
@@ -296,6 +296,8 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+        postsViewButtonItem.accessibilityValue = isCompact ? NSLocalizedString("Expanded", comment: "Expanded style") : NSLocalizedString("Compact", comment: "Compact style")
```
Comment (shiki) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: When the button is selected and the list is in compact view, the `accessibilityValue` is “Expanded”. I think we should describe **what the current list style is**. 



I think it makes more sense since after you tap on the button, VoiceOver would speak it again with the current `accessibilityValue`. 

```suggestion
postsViewButtonItem.accessibilityValue = isCompact ? NSLocalizedString("Compact", comment: "...") : NSLocalizedString("Expanded", comment: "...")
```

What do you think? 🙂

Comment (vphong) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Makes sense! Will do :)

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 1 above)
Comment (vphong) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Alright, I've re-written the 4 `NSLocalizedString`s. What do you think of them?

Comment (shiki) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: They look great! 👍 Thank you!

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 2 above)
Comment (vphong) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: This has been taken care of!
