### PR TITLE
Show media error if a post has permanent failed media

### LINKED ISSUE #12802: [Offline Posting] Self-hosted sites: Failed uploads with media errors do not show an error label
### Expected behavior

~The Post List says  “We couldn't complete this action, but we'll try again later.”~
The Post List says “We couldn't upload this media”.

### Actual behavior

The Post List says “Local changes“.

### Steps to reproduce the behavior

1. Use a self-hosted site
2. Go offline
3. Edit an existing draft
4. Add an image to it
5. Tap X → Update Draft
6. Tap "Cancel"
7. Go online and immediately go back offline at least 3 times

## Notes

WPCom sites show the correct label.

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #12802

To test:

1. Use a self-hosted site (or WPCom, the output is the same for both)
2. Go offline
3. Edit an existing draft
4. Add an image to it
5. Tap X → Update Draft
6. Tap "Cancel"
7. Go online and immediately go back offline as soon as you see the media being uploaded
8. Do the above step 3 times
9. Check the "Retry" button is appearing with a _We couldn't upload this media._ message

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

File: WordPress/Classes/Models/AbstractPost.swift [hunk 1]
```diff
@@ -136,4 +136,10 @@ extension AbstractPost {
     @objc override open func featuredImageURLForDisplay() -> URL? {
         return featuredImageURL
     }
+
+    /// Returns true if the post has any media that needs manual intervention to be uploaded
```
Comment (shiki) [inline WordPress/Classes/Models/AbstractPost.swift]: 👌 Thank you for adding a comment!
