### PR TITLE
Fix flaky Blogging Prompts Tests

### LINKED ISSUE #22323: `test_fetchPrompts_passesTheDateCorrectly` fails semi-consistently
See messages at https://github.com/wordpress-mobile/WordPress-iOS/pull/21921#issuecomment-1823996486

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes #22323 

The tests here were more complex than they needed to be – this PR:

- Simplifies the test suite
- Simplifies the logic by not using a `Date` as a Dictionary key

To test:
- Ensure tests pass – I ran the `BloggingPromptsServiceTests` 100 times in a row without failure, then tested them twice in CI. Feel free to re-run them as many times as you'd like in CI to be confident that the issue is addressed!

## Regression Notes
1. Potential unintended areas of impact
Could cause issues with downloading Blogging Prompts from the server

2. What I did to test those areas of impact (or what existing automated tests I relied on)
The existing test suite should cover this.

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jkmassel** [comment]
Rebased to see if the tests pass – if they do, I'll rebase once again after #23466 lands, then open the PR for real

File: WordPress/WordPressTest/BloggingPromptsServiceTests.swift [hunk 1]
```diff
@@ -138,49 +133,28 @@ final class BloggingPromptsServiceTests: CoreDataTestCase {
     }
 
     func test_fetchPrompts_givenNoParameters_assignsDefaultValue() throws {
```
Comment (jkmassel) [inline WordPress/WordPressTest/BloggingPromptsServiceTests.swift:135]: This test only needs to assert that the default date matches the URL parameter – no need for `differenceInDays`

File: WordPress/WordPressTest/BloggingPromptsServiceTests.swift [hunk 2]
```diff
@@ -138,49 +133,28 @@ final class BloggingPromptsServiceTests: CoreDataTestCase {
...
-        XCTAssertEqual(differenceInDays, expectedDifferenceInDays)
+        let expectedDate = dateFormatter.string(from: service.defaultStartDate)
+        XCTAssertEqual(expectedDate, try passedDate())
 
         // ensure that the passed number parameter is correct.
         let numberParameter = try XCTUnwrap(passedNumber())
         XCTAssertEqual(numberParameter, expectedNumber)
     }
 
     func test_fetchPrompts_passesTheDateCorrectly() throws {
```
Comment (jkmassel) [inline WordPress/WordPressTest/BloggingPromptsServiceTests.swift:150]: This test only needs to assert that the given date matches the URL parameter – no need for any specific date math here

File: WordPress/WordPressTest/BloggingPromptsServiceTests.swift [hunk 3]
```diff
@@ -196,8 +170,7 @@ final class BloggingPromptsServiceTests: CoreDataTestCase {
         let expectedPromptIDs = Set(testPrompts.map(\.promptID))
 
         // insert existing prompts.
-        let date = try XCTUnwrap(Self.dateFormatter.date(from: "2022-05-03"))
-        makeBloggingPrompt(siteID: siteID, promptID: 1000, date: date)
+        try makeBloggingPrompt(siteID: siteID, promptID: 1000, date: testPrompts.last!.dateString)
```
Comment (jkmassel) [inline WordPress/WordPressTest/BloggingPromptsServiceTests.swift:173]: This test needs to assert that there are never two blogging prompts created for the same calendar day.

It previously used dates for this, but we can simplify it – by comparing something like `2022-05-03` instead of `2022-05-03T12:34:56.000Z`, there's much less opportunity for errors to sneak in. By adjusting the codebase to use a `dateString` for comparison, the logic is quite a bit more robust against issues.

Tiny improvement – we care that the date of the last prompt matches the one in the test data – by referencing it directly we can ensure they don't get out of sync.

File: WordPress/WordPressTest/BloggingPromptsServiceTests.swift [hunk 4]
```diff
@@ -403,31 +373,27 @@ private extension BloggingPromptsServiceTests {
         return try XCTUnwrap(passedParameters[key], "Param not found for \(key)")
     }
 
-    func passedNumber() throws -> Int? {
-        return try passedParameter("per_page") as? Int
+    func passedNumber() throws -> Int {
```
Comment (jkmassel) [inline WordPress/WordPressTest/BloggingPromptsServiceTests.swift:376]: Just a nit – if we're `throw`-ing anyway, we can ensure that the test data will always be present

File: WordPress/WordPressTest/BloggingPromptsServiceTests.swift [hunk 5]
```diff
@@ -403,31 +373,27 @@ private extension BloggingPromptsServiceTests {
...
+        return try XCTUnwrap(passedParameter("per_page") as? Int)
     }
 
-    func passedDate() throws -> Date {
+    func passedDate() throws -> String {
```
Comment (jkmassel) [inline WordPress/WordPressTest/BloggingPromptsServiceTests.swift:380]: We were previously converting the passed parameter from a string into a date, but we start with a stringified date to do the comparison. By using stringified dates for both sides, it's way easier to do comparison

**Review by crazytonyli — APPROVED** [review]
