### PR TITLE
Show an alert when trying to preview while uploading media 

### LINKED ISSUE #13929: Images broken if previewing a Post without updating it first
**Describe the bug**
While we were working on [this](https://github.com/wordpress-mobile/WordPress-iOS/issues/13803), we had noticed an issue where previewing in the Block Editor while images being uploaded: Ref https://github.com/wordpress-mobile/WordPress-iOS/pull/13910#pullrequestreview-394229097

**To Reproduce**
1. From WordPress app, Go to **Site -> Posts** then select a Post to edit. Switch to Block Editor if you're on the classic editor.
2. Add an Image block, then tap **ADD IMAGE** and choose **Free Photo Library**
3. Search and select an image of your choice
4. While the image being uploaded, Tap the ... menu at the top-right corner, select Preview, you will the image being broken.

**Expected behavior**
In my opinion, since the image has not been uploaded yet so the preview won't be able to show the image. However, the Preview button is there, and it user would expect to see images when previewing a Post.

**Screenshots**
image

**Smartphone (please complete the following information):**
 - Device: [iPhone, iPad]
 - OS: [iOS]
 - Version [13.4]

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #13929 

To test (Classic and block editors - *Please test on device*):
1. Go to My Site -> Posts then select a Post to edit.
2. Add an Image / gallery block or classic
3. While the image being uploaded, Tap the ... menu at the top-right corner, select Preview
4. See the alert if image still uploading 
5. When Image done uploading, tap preview again
6. See preview with the image 

IMG_5993

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@yaelirub it worked smoothly in Gutenberg. However, I had a problem with Aztec: https://d.pr/v/98bx05

For some reason, the "local path" remains (something that was not introduced by your PR — it's there for some time).

Do you want to check that or shall we merge this one?

**Comment by yaelirub** [comment]
I saw it and I think there's an issue for it.
AFAIK, out of scope for this PR

File: WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift [hunk 1]
```diff
@@ -65,6 +65,10 @@ extension PostEditor where Self: UIViewController {
     }
 
     func displayPreview() {
+        if isUploadingMedia {
+            displayMediaIsUploadingAlert()
+            return
+        }
```
Comment (leandroalonso) [inline WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift:71]:
```suggestion
        guard !isUploadingMedia else {
            displayMediaIsUploadingAlert()
            return
        }

```
