### PR TITLE
RichText: Better handling for optionals relating to embeds.

### LINKED ISSUE #6772: WPRichContentView: crash on embedForAttachment(WPTextAttachment) -> WPRichTextEmbed
Not sure about this one.

### Version 

WPiOS 6.9+

### Log
```
Crashed: com.apple.main-thread
0  WordPress                      0x1002d0e90 WPRichContentView.embedForAttachment(WPTextAttachment) -> WPRichTextEmbed (WPRichContentView.swift:227)
1  WordPress                      0x1002d0ec0 @objc WPRichContentView.embedForAttachment(WPTextAttachment) -> WPRichTextEmbed (WPRichContentView.swift)
2  WordPress                      0x1002d0788 @objc WPRichContentView.attachmentManager(WPTextAttachmentManager, viewForAttachment : WPTextAttachment) -> UIView? (WPRichContentView.swift:207)
3  WordPress                      0x1002cd770 specialized WPTextAttachmentManager.(enumerateAttachments() -> ()).(closure #1) (WPTextAttachmentManager.swift:123)
4  WordPress                      0x1002c9de4 WPTextAttachmentManager.(enumerateAttachments() -> ()).(closure #1) (WPTextAttachmentManager.swift)
5  WordPress                      0x1002c9b08 thunk (WPTextAttachmentManager.swift)
6  Foundation                     0x18f7a2b80 -[NSAttributedString enumerateAttribute:inRange:options:usingBlock:] + 264
7  WordPress                      0x1002d2324 specialized WPRichContentView.content.setter (WPRichContentView.swift)
8  WordPress                      0x1002a28dc ReaderDetailViewController.configureRichText() -> () (ReaderDetailViewController.swift)
9  WordPress                      0x1002a0cd4 ReaderDetailViewController.configureView() -> () (ReaderDetailViewController.swift:417)
10 WordPress                      0x10029f334 ReaderDetailViewController.viewDidLoad() -> () (ReaderDetailViewController.swift:200)
11 WordPress                      0x10029f374 @objc ReaderDetailViewController.viewDidLoad() -> () (ReaderDetailViewController.swift)
12 UIKit                          0x194c32924 -[UIViewController loadViewIfRequired] + 1056
13 UIKit                          0x194c4a4b4 -[UIViewController __viewWillAppear:] + 132
14 UIKit                          0x194dd25b4 -[UINavigationController _startCustomTransition:] + 1136
15 UIKit                          0x194ceae74 -[UINavigationController _startDeferredTransitionIfNeeded:] + 676
16 UIKit                          0x194ceaadc -[UINavigationController __viewWillLayoutSubviews] + 64
17 UIKit                          0x194ceaa40 -[UILayoutContainerView layoutSubviews] + 188
18 UIKit                          0x194c2fa80 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1196
19 QuartzCore                     0x1920dd9d8 -[CALayer layoutSublayers] + 148
20 QuartzCore                     0x1920d24cc CA::Layer::layout_if_needed(CA::Transaction*) + 292
21 QuartzCore                     0x1920d238c CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
22 QuartzCore                     0x19204f3e0 CA::Context::commit_transaction(CA::Transaction*) + 252
23 QuartzCore                     0x192076a68 CA::Transaction::commit() + 512
24 UIKit                          0x194c25150 _afterCACommitHandler + 324
25 CoreFoundation                 0x18ed2a0c0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
26 CoreFoundation                 0x18ed27cf0 __CFRunLoopDoObservers + 372
27 CoreFoundation                 0x18ed28180 __CFRunLoopRun + 1024
28 CoreFoundation                 0x18ec562b8 CFRunLoopRunSpecific + 444
29 GraphicsServices               0x19070a198 GSEventRunModal + 180
30 UIKit                          0x194c9d7fc -[UIApplication _run] + 684
31 UIKit                          0x194c98534 UIApplicationMain + 208
32 WordPress                      0x1000d72c0 main (main.m:5)
33 libdispatch.dylib              0x18dc395b8 (Missing)
```

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6772 
This PR improves some optional handling which *should* resolve the crash reported in 6722. 

To test:
- Create a post on a blog you follow, where the post contains an iframe with an empty string for its `src` tag. For example: ```<iframe src="" width="300" height"200"></iframe>```
- Confirm the crash by viewing the post in the reader detail.
- Switch to this branch.
- View the post in the reader detail again and confirm there is no longer a crash. 

While this will prevent a crash, the exact markup involved remains unknown. Since the embed's HTML will be passed in its expected that we'll receive some reports of embedded content looking wrong in the reader.  We can use these reports to zero in on the exact circumstances and improve the fix once the exact mark up is known. 

Needs review: @kurzee would you mind another sir?

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 1]
```diff
@@ -227,10 +227,11 @@ extension WPRichContentView: WPTextAttachmentManagerDelegate {
 
         attachment.maxSize = CGSize(width: width, height: height)
 
-        if attachment.tagName == "iframe" {
-            embed.loadContentURL(URL(string: attachment.src.stringByDecodingXMLCharacters())!)
+        if let url = URL(string: attachment.src.stringByDecodingXMLCharacters()), attachment.tagName == "iframe" {
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Would it be more performant to check `attachment.tagName == "iframe"` first, before running `URL(string: attachment.src.stringByDecodingXMLCharacters())`?

**Comment by kurzee** [comment]
And posterity, I was only able to get this to crash (sans fix) by using a self-hosted site, which did not strip out the empty iframe.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Indeed it would, tho I was getting a Swift error trying to reverse the statements when I first tried.
Naturally everything works correctly now. 😬 🙄

**Comment by aerych** [comment]
I reordered the statements. Thanks for the nudge there. :)

Thanks as always @kurzee !!
