### PR TITLE
Stats Revamp: Text in the card not responding to changes between Dark and Light mode

### LINKED ISSUE #19015: [iOS] Stats Revamp cards not responding to changes between Dark and Light mode
### Expected behavior

The Stats' Insights screen should adapt instantly to changes in the device's Dark/Light mode settings.

### Actual behavior

The Stats' Insights screen doesn't immediately reflect changes.

### Steps to reproduce the behavior

1. Open the Stats screen
2. Ensure you're on the Insights screen
3. Change the device appearance mode between Light and Dark
4. Notice that the text color does not adapt correctly
5. Refresh the screen, to the previous screen, and return to the Stats' Insight screen
6. Notice that the text colors have now adapted

### Screenshots

|   |
| - |

### PR DESCRIPTION
**Pull request by staskus**
Fixes #19015

## Description

Text in the card not responding to changes between Dark and Light mode. Is is noticeable on `Likes Total` and `Comments Total` cards "guide" area.

The issue happens because we use `NSAttributedString` which is built together with `foregroundColor` attributes and passed to the cell. It does not automatically update color when Light/Dark mode changes. 

## Solution

Currently we build `guideText` inside `StatsTotalInsightsData` and then pass to `StatsTotalInsightsCell`. Instead, building `guideText` directly in `StatsTotalInsightsCell` and rebuilding it when `traitCollectionDidChange` is triggered. It requires passing some additional dependencies to `StatsTotalInsightsCell`.

### Before all:
1. Enable showsStatsRevampV2 feature flag
3. Launch the application and open Stats

### Case 1:
1. Add Likes total and Comments Total cards
2. Ensure you're on the Insights screen
4. Change the device appearance mode between Light and Dark
5. Notice that the guide text color changes when the appearance mode changes

## Regression Notes

1. Potential unintended areas of impact

Building of `Likes Total` and `Cards Total` cards

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manually testing that the cards continue working

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Images & Videos

https://user-images.githubusercontent.com/4062343/192844286-2aa74577-b259-4fd4-8593-59c8e5e377d7.mp4

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift [hunk 1]
```diff
@@ -336,7 +336,7 @@ struct TotalInsightStatsRow: ImmuTableRow {
             return
         }
 
-        cell.configure(count: dataRow.count, difference: dataRow.difference, percentage: dataRow.percentage, sparklineData: dataRow.sparklineData, guideText: dataRow.guideText, guideURL: dataRow.guideURL, statSection: statSection, siteStatsInsightsDelegate: siteStatsInsightsDelegate)
+        cell.configure(dataRow: dataRow, guideURL: dataRow.guideURL, statSection: statSection, siteStatsInsightsDelegate: siteStatsInsightsDelegate)
```
Comment (sla8c) [inline WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift]: It seems to me like the 2nd parameter here is not necessary since you are passing dataRow in the first parameter.  I removed the 2nd parameter myself and only used the dataRow object and it worked fine.

**Review by sla8c — CHANGES_REQUESTED** [review]

File: WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift (hunk 1 above)
Comment (staskus) [reply WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift]: Goood observation 👍.  I somehow managed to miss it. 

drawing

**Review by sla8c — APPROVED** [review]
