### PR TITLE
Use objects in the right context in callback blocks

### LINKED ISSUE #2372: Services callbacks should check if the object was deleted before updating it
We have a crash in https://github.com/wordpress-mobile/WordPress-iOS/blob/4.3/WordPress/Classes/Services/CommentService.m#L194 because we're trying to change a comment that's already deleted.

Store only object IDs when doing network requests and fetch the objects if needed when the request is finished

### PR DESCRIPTION
**Pull request by koke**
I've seen recently a few more cases when removing a site would crash if a sync was in progress.

I went through all the Service classes and made sure we only pass object IDs to callback blocks.

Fixes #2372

Needs Review: @astralbodies

### CODE REVIEW

**Comment by koke** [comment]
Submitted too fast, it breaks a lot :open_mouth:

**Comment by koke** [comment]
Never mind, app was in a bad state from switching branches. @astralbodies ready for review

File: WordPress/Classes/Services/BlogService.m [hunk 1]
```diff
@@ -159,9 +159,14 @@ - (void)syncBlogsForAccount:(WPAccount *)account
 {
     DDLogMethod();
 
+    NSManagedObjectID *accountID = account.objectID;
     id<AccountServiceRemote> remote = [self remoteForAccount:account];
     [remote getBlogsWithSuccess:^(NSArray *blogs) {
         [self.managedObjectContext performBlock:^{
+            WPAccount *account = (WPAccount *)[self.managedObjectContext existingObjectWithID:accountID error:nil];
+            if (!account) {
+                return;
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/BlogService.m]: If no account is found shouldn't we invoke the failure callback here?

File: WordPress/Classes/Services/BlogService.m [hunk 2]
```diff
@@ -159,9 +159,14 @@ - (void)syncBlogsForAccount:(WPAccount *)account
 {
     DDLogMethod();
 
+    NSManagedObjectID *accountID = account.objectID;
     id<AccountServiceRemote> remote = [self remoteForAccount:account];
     [remote getBlogsWithSuccess:^(NSArray *blogs) {
         [self.managedObjectContext performBlock:^{
+            WPAccount *account = (WPAccount *)[self.managedObjectContext existingObjectWithID:accountID error:nil];
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/BlogService.m]: Ignoring a possible error returned error here. We should at least log it.

File: WordPress/Classes/Services/BlogService.m [hunk 3]
```diff
@@ -305,40 +310,74 @@ - (void)syncBlogStaggeringRequests:(Blog *)blog
 - (void)staggerSyncPostsForBlog:(Blog *)blog
 {
     PostService *postService = [[PostService alloc] initWithManagedObjectContext:self.managedObjectContext];
-    [postService syncPostsOfType:PostServiceTypePost forBlog:blog success:^{
+    NSManagedObjectID *blogID = blog.objectID;
+    void(^next)() = ^ {
+        Blog *blog = (Blog *)[self.managedObjectContext existingObjectWithID:blogID error:nil];
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/BlogService.m]: Again we are ignoring the possible error returned we should at least log it. This happens on other calls bellow, so I will not state it again but I think we should change them all to track a possible error and log it.

File: WordPress/Classes/Services/CommentService.m [hunk 4]
```diff
@@ -208,6 +208,10 @@ - (void)loadMoreCommentsForBlog:(Blog *)blog
         options:options
         success:^(NSArray *comments) {
            [self.managedObjectContext performBlock:^{
+               Blog *blog = (Blog *)[self.managedObjectContext existingObjectWithID:blogID error:nil];
+               if (!blog) {
+                   return;
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/CommentService.m]: Invoke failure callback here.

File: WordPress/Classes/Services/CommentService.m [hunk 5]
```diff
@@ -291,10 +295,12 @@ - (void)spamComment:(Comment *)comment
             success:(void (^)())success
             failure:(void (^)(NSError *error))failure
 {
+    NSManagedObjectID *commentID = comment.objectID;
     [self moderateComment:comment
                withStatus:@"spam"
                   success:^{
-                      [self.managedObjectContext deleteObject:comment];
+                      Comment *commentInContext = (Comment *)[self.managedObjectContext existingObjectWithID:commentID error:nil];
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/CommentService.m]: Detect if comment is not nil? Invoke failure if comment is nil.

File: WordPress/Classes/Services/PostCategoryService.m [hunk 6]
```diff
@@ -107,9 +107,14 @@ - (void)syncCategoriesForBlog:(Blog *)blog
                       failure:(void (^)(NSError *error))failure
 {
     id<PostCategoryServiceRemote> remote = [self remoteForBlog:blog];
+    NSManagedObjectID *blogID = blog.objectID;
     [remote getCategoriesForBlog:blog
                          success:^(NSArray *categories) {
                              [self.managedObjectContext performBlock:^{
+                                 Blog *blog = (Blog *)[self.managedObjectContext existingObjectWithID:blogID error:nil];
+                                 if (!blog) {
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/PostCategoryService.m]: Invoke failure callback?

File: WordPress/Classes/Services/PostService.m [hunk 7]
```diff
@@ -248,7 +263,7 @@ - (void)syncPostsOfType:(NSString *)postType
                               purgeExisting:YES
                           completionHandler:^{
                               // Update the Last Sync Date, accordingly
-                              Blog *blogInContext = (Blog *)[self.managedObjectContext existingObjectWithID:blog.objectID error:nil];
+                              Blog *blogInContext = (Blog *)[self.managedObjectContext existingObjectWithID:blogID error:nil];
```
Comment (SergioEstevao) [inline WordPress/Classes/Services/PostService.m]: What happens if blog is nil at this moment?

File: WordPress/Classes/Services/BlogService.m (hunk 1 above)
Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: I don't know. The sync didn't really fail, it's just not relevant anymore since the account is gone. Calling `failure` could end up in showing an error to the user that's not really a problem. Calling `success` feels misleading since nothing really synced. Not calling anything could lead to something waiting for the sync to finish, at least in theory.

No good solution here. I went for the simplest change possible, since the alternative right now is crashing.

Comment (SergioEstevao) [inline WordPress/Classes/Services/BlogService.m]: During my tests I got in a situation where the login screen stayed forever there, because the account was returning nil.

File: WordPress/Classes/Services/BlogService.m (hunk 2 above)
Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: The error provides more details in case the object isn't found. IMO, we don't care about the details, only if we can get an object.

File: WordPress/Classes/Services/BlogService.m (hunk 1 above)
Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: That's another bug then. I could reproduce and it was caused because the account wasn't saved yet. Calling `obtainPermanentIDsForObjects:error:` fixes it

Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: @astralbodies since I don't see many uses of `obtainPermanentIDForObject:` in the code, I'm guessing it's best to save the context before calling sync blogs, and assume service classes are passed objects that are already saved in the context?

We could refactor this further and update all the service classes to only take IDs, but again this PR was meant to just fix the crashes.

Comment (astralbodies) [inline WordPress/Classes/Services/BlogService.m]: @koke I'm beginning to think passing any parameters by `NSManagedObjectID` is going to have to be the requirement. It feels less elegant but it provides a level of safety we don't have. Passing around temporary IDs can also add a level of unexpected behavior. Calling `obtainPermanentIDForObject` is expensive from what I know since it has to go all the way down to the store to obtain the ID. 

We're also not calling refreshObject in many places which feels like a potential source of problems especially if an object is deleted in another context.

Comment (SergioEstevao) [inline WordPress/Classes/Services/BlogService.m]: I see two possible solutions here:

 * Always use NSManageObjectID for the parameters, because we are unsure what thread/context they are going to be use.
 * Always assume that the calls to services need to be done on the main context, then internally we decide if we need to get the object ID or not depending of what kind of context we are using.

We just need to be consistent about it or else is very hard to reason about the code.

Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: > Always assume that the calls to services need to be done on the main context

Main/derived context has nothing to do with this issue. The problem here was that the caller just created/inserted the account object and hadn't saved the context yet, so the ID wasn't permanent and `existingObjectWithID` returned `nil`. It all happened on the main thread.

Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: >  I'm beginning to think passing any parameters by NSManagedObjectID is going to have to be the requirement.

@astralbodies I think that's probably for the best, but I think we should do a second PR for that and try to get this into 5.4, since my goal was to stop crashing when a site is deleted and a call was in progress

Comment (koke) [inline WordPress/Classes/Services/BlogService.m]: db960ba should fix the login issue, which brings another problem to the table: I think all service methods that create new managed objects should call `saveContextAndWait:` before returning them, but I'm not sure about the side effects

Comment (astralbodies) [inline WordPress/Classes/Services/BlogService.m]: Agreed - if a method expects immediate return then it should use the callback paradigm to asynchronously wait for results.

**Comment by astralbodies** [comment]
@koke Is this ready for another review?

**Comment by koke** [comment]
@astralbodies I think I wanted to implement something else but I can't remember. Let's go for another review :grimacing:

**Comment by astralbodies** [comment]
@koke I think we're good to move forward on this once you merge in develop :smile: 

:shipit:
