### PR TITLE
[Jetpack] Update Jetpack banner visibility algorithm

### LINKED ISSUE #19097: Reader > Search: Jetpack banner is visible and animated in 'No posts found' screen.
Jetpack banner is responding to scroll up/down gestures in `Reader` > `Search` > `'No posts found' screen`. 
The same thing happens for the `Unable to load this content right now` screen.

|  |  |
| :-: | :-: |
| <video width="300" src="https://user-images.githubusercontent.com/42008628/180320519-782eb7dd-d00e-4ca9-9b0f-1348e2e14fee.mov"> | <video width="300" src="https://user-images.githubusercontent.com/42008628/180321015-c7c1b92d-5479-4ffd-96ed-a614e6e74730.mov"> |

### Steps to reproduce the behavior
1. Open the app.
2. Go to `Reader`.
3. Tap `Search` button.
4. Type several letters in the search field to the result is the `No posts found` screen.
5. Swipe the screen up and down.
6. ❌ Notice the Jetpack banner is responding to scrolling up/down gestures.
7. Turn the Airplane mode ON.
8. Search for something.
9. Notice the `Unable to load this content right now` screen is displayed.
10. Swipe the screen up and down.
11. ❌  Notice the Jetpack banner is responding to scrolling up/down gestures.

### PR DESCRIPTION
**Pull request by twstokes**
## Description

**This PR:**
- Fixes #19097
  - Bouncing `UIScrollView`s should no longer affect banner visibility
- Hides the banner when a scroll view is scrolled past the height of the banner, otherwise shows it
- No longer hides the `ReaderStreamViewController` Jetpack banner when the keyboard is shown on the `ReaderSearchViewController`
    - This keeps us from having to add logic to show / hide banners depending on the keyboard visibility

### Bouncing scroll view behavior

The banner should always be shown on scroll views that bounce.

1. Go to Reader
2. Tap the magnifying glass to start a search
3. Search for gibberish to ensure no results will be found (see https://github.com/wordpress-mobile/WordPress-iOS/issues/19097)
4. Bounce the scroll view by moving it up and down
5. **Expect** that the banner is always shown

This applies to any scroll view without enough content to exceed its frame's height.

### Banner visibility behavior

The banner should be hidden if a scrolling (non-bouncing) scroll view is scrolled below the height of a banner. Otherwise it should be shown.

1. Go to Reader
2. Tap the magnifying glass to start a search
3. Search for a generic term that results in many results
4. Scroll down
5. **Expect** the banner to hide once scrolled past the minimum of a banner, [currently defined as 50 pts](https://github.com/wordpress-mobile/WordPress-iOS/blob/9dc27140b2023ba046876917cc890d1b61eb6e6c/WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerView.swift#L42)
6. **Expect** the banner not to reappear until the top offset is less than or equal to the 50 pt minimum defined above

### Banners to test:
- Jetpack activity log
- Notifications
- Reader
- Reader searching (there should be a banner above the keyboard)
- Reader search results - Posts and Sites tab

### Items to consider testing:
- a11y / VoiceOver / Dynamic Type
- Dark / Light mode
- Portrait / Landscape
- Jetpack / WordPress app

## Regression Notes
1. Potential unintended areas of impact
    - All Jetpack banner views in the app
    - Presenting the Jetpack overlay when a banner is tapped

7. What I did to test those areas of impact (or what existing automated tests I relied on)
    - Manually tested steps above

8. What automated tests I added (or what prevented me from doing so)
    - Added `JetpackBannerScrollVisibilityTests`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JPScrollViewDelegate.swift [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import Combine
 import CoreGraphics
+import UIKit
 
 /// Conform to this protocol to send scrollview translations to a `JetpackBannerView` instance
 protocol JPScrollViewDelegate: UIScrollViewDelegate {
 
-    var scrollViewTranslationPublisher: PassthroughSubject<CGFloat, Never> { get }
+    var scrollViewTranslationPublisher: PassthroughSubject<Bool, Never> { get }
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JPScrollViewDelegate.swift:8]: We should probably update these names to better fit their purpose:
- `scrollViewTranslationPublisher`
- `addTranslationObserver`

But I'll wait until after the first review pass.

**Review by Gio2018 — APPROVED** [review]
Awesome @twstokes , works as a charm!
