### PR TITLE
Reader: Fixes anchor links not responding to taps

### LINKED ISSUE #15017: Reader doesn't open anchor links correctly, or doesn't scroll to anchor
### Expected behavior
Tapping on a link that points to an anchor in a different webpage should open that link and scroll to the anchor position.

### Actual behavior
Couple of different behaviors observed:
a. Post is opened but content doesn't scroll to the anchor. That's what folks encounter in this ZD ticket: 3345628
b. Post is not opened. That's what I observed on my iPhone 6s, iOS v13.5.1, WPiOS 15.8 (and 15.6 Internal)

### Steps to reproduce the behavior
1. In the Reader, use the search box and put the URL of a post you know it includes an anchor link
2. Open the post
3. Tap on the anchor link
4. Either nothing happens, or the post is opened but content not scrolled to the anchor position

Example:
[Click here](https://makyo0117.wordpress.com/2019/11/18/shbdt-chuong-1/) and scroll to the bottom of the article.
Click Mục lục  to be taken to an anchor link and a list of chapter/article numbers

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s, iOS v13.5.1, WPiOS v15.8 (link not opening case)
iPad Air (3rd gen), iOS 13.6.1 (17G80) (scroll not happening case)

### PR DESCRIPTION
**Pull request by emilylaguna**
Fixes #15017

#### Loading of posts with anchors
1. Open a post with a link to a post with an anchor in the reader, example URL: https://emilylaguna.wordpress.com/2020/09/30/anchor-1/
2. Tap on the link
3. If it's a WP.com post you should be directed to the post in the app, and sent to the anchor once the post loads

#### Loading of a post with internal anchors
1. Open a post that has anchors to other areas in the same post, example: https://emilylaguna.wordpress.com/2020/09/30/anchor-2/
2. Scroll to the anchor
3. Tap on it
4. You should be brought to the location in the post for that anchor

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift [hunk 1]
```diff
@@ -221,16 +229,32 @@ class ReaderDetailCoordinator {
         })
     }
 
-    private func renderPostAndBumpStats() {
+    private func renderPostAndBumpStats(with url: URL? = nil) {
```
Comment (leandroalonso) [inline WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift]: I was a little bit confused by the `url` as a param here.

I had to check the code to see that `bumpStats` does not rely on this URL, and was wondering why that was set in one of the places that is called but not on the other.

What do you thinnk about instead of having this logic here you just call `self?.scrollToHashIfNeeded(with: url)` in `service.fetchPost`? I guess it will avoid this confusion.

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift [hunk 2]
```diff
@@ -72,6 +72,13 @@ class ReaderDetailViewController: UIViewController, ReaderDetailView {
         }
     }
 
+    /// Tracks whether the webview has called -didFinish:navigation
+    private var isLoadingWebView = true
+
+    /// If the scroll(to:) has been called before the webview content has been loaded
+    /// the hash will be stored in this variable, and scrolled to once the content is loaded
+    private var pendingHashString: String? = nil
```
Comment (leandroalonso) [inline WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift]: I know this is such a simple logic (and the scroll) but I wonder if that shouldn't be in the coordinator (which is responsible for all the logic) — while the view simple do what the coordinator commands.

Something like: webView load -> tell coordinator -> coordinator tell VC to scroll if needed.

**Review by leandroalonso — CHANGES_REQUESTED** [review]
It works as described.

Just two small suggestions though.

**Comment by hypest** [comment]
👋 @emilylaguna , I removed myself from the reviewers list as I'm not currently planning to dive in, especially since I see Leandro has made a pass already. That said, let me know if you'd still want me to make some pass, although I won't be too productive on the iOS side of things :)

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift (hunk 2 above)
Comment (emilylaguna) [reply WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift]: Done in ee35f5cc93eecd4588b5b6ba05e35a474526e9e0

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift (hunk 1 above)
Comment (emilylaguna) [reply WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift]: This was changed in ee35f5cc93eecd4588b5b6ba05e35a474526e9e0

**Comment by emilylaguna** [comment]
@leandroalonso back to you!

**Review by leandroalonso — APPROVED** [review]
