### PR TITLE
No tags with duplicate names

### LINKED ISSUE #8475: Tags: Warn if creating a new tag and the tag title is empty when exiting
If I try to add a new tag to my site, but I leave the Tag title field empty and return to the settings, the tag isn’t created. That makes sense because I didn’t actually give it a name, but should we handle that better? Either show some kind of warning that you’re going to lose the description text or (maybe a bit excessive) save the abandoned text for the next time the user clicks the + icon to prefill?

### Expected behavior
I expected to get some kind of warning that I was about to lose some of my work.

### Actual behavior
I exit the new tag screen silently without any kind of indicator.

### Steps to reproduce the behavior
1. Within the app, navigate to Settings -> Tags.
2. Click + to create a new tag.
3. Type a description, but leave the tag title empty.
4. Click "< Tags" to navigate back to the main list.

No tag will be created, and you won't receive any kind of indicator that you'll lose the description.

### PR DESCRIPTION
**Pull request by elibud**
Fixes #8475 and #8470 

**To test:**
1. Check that you can create a new tag with a name that's not currently being used.
2. Check that you can edit a tag to a name that's not currently being used.
3. Check that you can't create a new tag with a name that's currently being used.
4. Check that you can't edit a new tag to a name that's currently being used.

cc: @diegoreymendez

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift [hunk 1]
```diff
@@ -313,32 +313,73 @@ extension SiteTagsViewController {
...
+        }
+
+        tag.name = updatedData.title
+        tag.tagDescription = updatedData.subtitle
+
+        save(tag)
+    }
+
+    private func existingTagForData(_ data: SettingsTitleSubtitleController.Content) -> PostTag? {
+        if let title = data.title {
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift]: A big `if let…` like this is a perfect place to use a `guard` instead.

File: WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift [hunk 2]
```diff
@@ -313,32 +313,73 @@ extension SiteTagsViewController {
...
         newTag.name = data.title
         newTag.tagDescription = data.subtitle
 
-        self.save(newTag)
+        save(newTag)
+    }
+
+    private func updateTag(_ tag: PostTag, updatedData: SettingsTitleSubtitleController.Content) {
+        // Lets check that we are not updating a tag to a name that already exists
+        if let existingTag = existingTagForData(updatedData),
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift]: I think this would work better as a `guard`

File: WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift [hunk 3]
```diff
@@ -313,32 +313,73 @@ extension SiteTagsViewController {
...
+                return nil
+            }
+            return results.first
+        } else {
+            return nil
+        }
+    }
+
+    fileprivate func displayAlertForExistingTag(_ tag: PostTag) {
+        let title =  NSLocalizedString("Name already exists",
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift]: We way want to consult someone else on this, but imo "Tag already exists" would be a more direct error title.

I also think "A tag with that name already exists, please choose a different one." might be a bit confusing, because to a user the title *is* the tag. I'd suggest "A tag called {tag.title} already exists.", so they can see what the existing tag is called, and hopefully understand what happened.

Comment (elibud) [reply WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift]: yeah I was copying Calypso, but I really prefer your suggestions. I will update this.

**Comment by elibud** [comment]
@nheagy thanks for the suggestions, both fixed, would you mind taking another look and doing another round of testing?
