### PR TITLE
Menus: Readability fixes

### LINKED ISSUE #5683: Menus: Add length cutoff for long menus when dropdown expanded
### Expected behavior

I setup a really long menu name for one of my menus. When the menu is active, it has an ellipses that cuts off the length at a certain point and everything looks great. I expected the same thing to be applied when I expanded the menu list.
### Actual behavior

When I expand the menu list though, the really long menu name is not cutoff and it overlaps with the checkmark if it's the currently selected menu.

The "uses" separator is also truncated to "us..." which looks weird.
### Steps to reproduce the behavior
1. Create a menu with a really long menu title. I used "This is a really long menu name that I happen to have because I like it"
2. Save the menu title and select that menu as the active menu for your site.
3. Open the menu dropdown in both landscape and portrait. In landscape, you'll notice the "us..." cutoff.

Menu list collapsed:

screen shot 2016-07-08 at 16 00 03

Menu list expanded:

screen shot 2016-07-08 at 16 01 28

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #5683

Readability fixes for the labels in the header. This was a bit of tech debt, but also more troublesome with our new split-view on iPad and iPhone Pluses.

In the Menus header, refactored to use a `UIStackView` and allow for properly resizing/truncating the selection labels when it's super long. Also updated the storyboards for Xcode 8.2 and fixed the compression issue for the "USES" label.

To test:
1. Open Menus on an iPhone Plus simulator or device, for a test site that has at least one Menu set up on it.
2. Rotate to landscape, this will bring in the split-view and compress the layout.
3. Type in a new, long name for the Menu currently selected (may be the "Default Menu").
4. Check that the "USES" label doesn't compress in width when you reach the truncated limit.
5. Tap on the Menu selection dropdown at the top-right.
6. Check that the new Menu name truncates correctly before the checkmark or edge of the view.

Needs review: @bummytime can you take a peak at this one?

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m [hunk 1]
```diff
@@ -26,22 +30,9 @@ - (id)init
...
-        _label = label;
-
-        UIEdgeInsets insets = [Menu viewDefaultDesignInsets];
-        insets.left = MenusDesignDefaultContentSpacing;
-        insets.right = MenusDesignDefaultContentSpacing;
-
-        [label.leadingAnchor constraintEqualToAnchor:self.leadingAnchor constant:insets.left].active = YES;
-        [label.trailingAnchor constraintEqualToAnchor:self.trailingAnchor constant:insets.right].active = YES;
-        [label.topAnchor constraintEqualToAnchor:self.topAnchor constant:0].active = YES;
-        [label.bottomAnchor constraintEqualToAnchor:self.bottomAnchor constant:0].active = YES;
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m]: Love all the red here!

File: WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m [hunk 2]
```diff
@@ -54,12 +45,72 @@ - (id)init
...
+    UILabel *label = [[UILabel alloc] init];
+    label.backgroundColor = [UIColor clearColor];
+    label.font = [[WPStyleGuide regularTextFont] fontWithSize:14];
+    label.textColor = [WPStyleGuide darkGrey];
+    [self addSubview:label];
+    _label = label;
+
+    NSAssert(_stackView != nil, @"stackView is nil");
+    [self.stackView addArrangedSubview:label];
+    _label = label;
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m]: Is this redundant with the assignment above on Line 80?

File: WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m [hunk 3]
```diff
@@ -116,24 +167,6 @@ - (void)drawRect:(CGRect)rect
...
-        checkOrigin.y += checkStepLength / 2.0;
-
-        CGContextSetLineWidth(context, 1.0);
-        CGContextMoveToPoint(context, checkOrigin.x, checkOrigin.y);
-        CGContextAddLineToPoint(context, checkOrigin.x + checkStepLength, checkOrigin.y - checkStepLength);
-        CGContextMoveToPoint(context, checkOrigin.x - (checkStepLength / 2.0), checkOrigin.y - (checkStepLength / 2.0));
-        CGContextAddLineToPoint(context, checkOrigin.x, checkOrigin.y);
-        CGContextSetStrokeColorWithColor(context, [[WPStyleGuide greyDarken10] CGColor]);
-        CGContextStrokePath(context);
-    }
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m]: Love this going away too! Much improved.

**Comment by kurzee** [comment]
@bummytime thanks for the review! Good catch on the extra `_label` set, must have snuck in there when I was refactoring that. One last peak/approval?

**Comment by kurzee** [comment]
Thanks @bummytime!
