### PR TITLE
Fix scroll to comment issue

### LINKED ISSUE #16897: App not always scrolling to correct comment in notifications
### Expected behavior

When tapping a notification about a comment, tapping on the comment should make the app should scroll all the way to the comment, even if it is in a long thread of comments.

### Actual behavior

When tapping a notification, the app _doesn’t always_ scroll all the way to the comment if it’s a long way down (e.g. near the end of a comment thread or project thread). I have seen it fail to scroll all the way, sometimes stopping midway down the thread. Other times it does scroll to the correct comment.

This scrolling issue was a known bug but was addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/16802 which has the 17.8 milestone. So I’m bringing it up here in case there’s a lingering bug.

### Steps to reproduce the behavior

1. Locate a notification about a comment (e.g. another user liked your comment)
2. Tap the notification in the app's Notifications tab and be taken to the "Likes" screen
3. Tap the comment itself and be taken to the "Comments" screen
4. Notice that the app doesn't scroll you down to the comment in question, sometimes it scrolls half-way, for example

I was able to reproduce this 2 out of 2 times; however, when I went back to try it again and could only reproduce 1 out of 5 times.

### PR DESCRIPTION
**Pull request by justtwago**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/16897

It's an improvement for the original fix from https://github.com/wordpress-mobile/WordPress-iOS/pull/23255
In addition to that workaround, I've added a small delay to let the TableView calculate cells' height and render them properly before scrolling to a highlighted comment.

Please let me know if you have any ideas on how to improve it. 
More context: p1709841569628759-slack-C06BWNSR02K

To test:
- [ ] Run the original app from `trunk` and find a comment notification that leads to a post with a big number of comments.
- [ ] Go to the comment details and then to the original comment with the full comments tree.
- [ ] Notice that the list scrolled to a wrong comment instead of the highlighted one.
- [ ] Run the app from this PR and make the same steps with the same comments.
- [ ] Confirm that the list is scrolled to the proper highlighted comment after a few attempts.

## Regression Notes
1. Potential unintended areas of impact
Reader Comments screen `ReaderCommentsViewController`

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tests

3. What automated tests I added (or what prevented me from doing so)
Legacy code

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/290">25.1</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m [hunk 1]
```diff
@@ -848,33 +852,40 @@ - (NSAttributedString *)cacheContentForComment:(Comment *)comment
...
-        {
-            [self.tableView scrollToRowAtIndexPath:indexPath atScrollPosition:UITableViewScrollPositionTop animated:YES];
-            self.highlightedIndexPath = indexPath;
-        }
+    if (!comment) {
+        return;
+    }
 
-        // Reset the commentID so we don't do this again.
-        self.navigateToCommentID = nil;
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m:877]: [Question] Was this removed by design? You mentioned a regression related to scrolling more than once to the comment. Could this be the cause of the regression?

**Review by hassaanelgarem — APPROVED** [review]
Thanks for working on this stubborn issue! 
It works as expected! 🚀 
Left one question that might affect the changes, but the code looks good otherwise.

File: WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m (hunk 1 above)
Comment (justtwago) [reply WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m:877]: Yes, this change was intentional. Basically, it was the initial fix for my previous PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/23255
It occurs that the issue is complex, and `self.navigateToCommentID = nil;` breaks proper scrolling to the comment in case there are more pages to load.

Comment (justtwago) [reply WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m:877]: > Could this be the cause of the regression?

Exactly, that was the cause of the regression. We refresh the list (which triggers auto-scroll) when replying to a comment or a post. I've added an argument to the `refreshTableViewAndNoResultsView` method to manually control the auto-scroll.
