### PR TITLE
Fixing Notifications Header

### LINKED ISSUE #5913: Notifications: Section header can appear too wide
To reproduce: 
- Be signed into a wpcom account and be showing a section header in the Notifications screen. 
- Confirm the header is the correct width. 
- Switch to the Me tab and sign out of the app. 
- Sign back into the app with the same account. 
- Switch to the Notifications tab. 
- Notice the section header is full width.

cc @jleandroperez 

img_0025

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #5913

#### To test:
1. Be signed into a wpcom account and be showing a section header in the Notifications screen.
2. Confirm the header is the correct width.
3. Switch to the Me tab and sign out of the app.
4. Sign back into the app with the same account.
5. Switch to the Notifications tab.

As a result, the Section Header should have the expected width.

Needs review: @aerych 
Eric, may i bug you with a quick review?

Thanks in advance!!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift [hunk 1]
```diff
@@ -634,6 +640,10 @@ private extension NotificationsViewController
             DDLogSwift.logError("Error refreshing Notification Row \(error)")
         }
     }
+
+    func setNeedsReloadResults() {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Why this method instead of just setting the property?

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Inspired by `setNeedsDisplay` + this way the ivar is only accessed directly within the `WPTableViewHandler Helpers` extension.

Comment (aerych) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Yet the variable could still be accessed directly throughout the class and other extensions being defined on the class. The setter seems unnecessary and not too swifty to me.  Not a huge deal if you prefer to keep it.

**Comment by aerych** [comment]
Retested everything and the patch seems to do the trick. 
I have a slight concern that a reload could be masking an underlying cause of the wide header but I never saw other issues like breaking constraints.  Probably fine for now and something we can revisit later if needed.   
One super nitpicky comment that you're welcome to ignore.  Otherwise :shipit:

**Comment by jleandroperez** [comment]
@aerych  `setNeedsReloadResults` gone.

Thanks for the review sir!
