### PR TITLE
Zendesk Mobile: create identity when it's actually needed.

### LINKED ISSUE #9220: Zendesk Mobile: Zendesk Identity is not always created
### Expected behavior
- Fresh Install of the app.
- Log into a Self hosted site
- Open Me > Support
- Attempting any of the three Support options should work.

### Actual behavior
- Fresh Install of the app.
- Log into a Self hosted site
- Open Me > Support
- Attempt any of the three Support options.
- Nothing happens.

### Steps to reproduce the behavior
See above.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #9220 

To test:
- Fresh Install of the app.
- Log into a Self hosted site.
  - Open Me > Support.
  - Verify the three Support options work.
  - Find the `Zendesk identity created` log and verify the email and name match the site.
- Log into a WP account.
  - Open Me > Support.
  - Select one of the Support options.
  - Find the `Zendesk identity created` log and verify the email and name match the WP site.
- Log out of the WP account.
  - Open Me > Support.
  - Select one of the Support options.
  - Find the `Zendesk identity created` log and verify the email and name match the self hosted site.

To note: In the absence of a WP account, the app will use the _first_ self hosted site for Zendesk, regardless of additional self hosted sites added. Since this is written to User Defaults, a re-install is needed to clear it.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@jleandroperez - I know you provided several options when we discussed this issue. However, they all depended on external factors. As I'm trying to keep Zendesk logic contained to `ZendeskUtils` as much as possible, I decided to let Zendesk create the identity when it needs it. Plus, that ensures the identity is created, instead of depending on it being triggered external.

As always, let me know what you think!

File: WordPress/Classes/Utility/ZendeskUtils.swift [hunk 1]
```diff
@@ -37,78 +36,38 @@ import CoreTelephony
...
-        helpCenterContentModel.labels = [Constants.articleLabel]
+            helpCenterContentModel.groupType = .category
+            helpCenterContentModel.groupIds = [Constants.mobileCategoryID]
+            helpCenterContentModel.labels = [Constants.articleLabel]
 
-        let presentInController = ZendeskUtils.configureViewController(controller)
-        ZDKHelpCenter.presentOverview(presentInController, with: helpCenterContentModel)
+            let presentInController = ZendeskUtils.configureViewController(controller)
+            ZDKHelpCenter.presentOverview(presentInController, with: helpCenterContentModel)
+        }, failure: nil)
```
Comment (jleandroperez) [inline WordPress/Classes/Utility/ZendeskUtils.swift]: Few thoughts on alternatives!!

```
func showHelpCenterIfPossible(from controller:  UIViewController) {
    ZendeskUtils.createIdentity { success in {
          guard success else { 
              showFailureAlert(from: controller)
              return
          }

          showHelpCenter(from: controller)
    }
}

private func showHelpCenter(from controller: UIViewController) {
     // All of the `showHelpCenter` method's code, minus the Identity creation
}
```

- The main idea is to let the caller know that the method **may fail** (instead of silently failing).
- By updating the `createIdentify` signature to `private func createIdentity(completion: (Bool) -> Void)` you can *slightly* simplify the syntax. (Arguable point, definitely!!)
- This applies to the other public methods as well!

File: WordPress/Classes/Utility/ZendeskUtils.swift [hunk 2]
```diff
@@ -279,7 +279,7 @@ private extension ZendeskUtils {
             let logFileInformation = fileLogger.logFileManager.sortedLogFileInfos.first,
             let logData = try? Data(contentsOf: URL(fileURLWithPath: logFileInformation.filePath)),
             let logText = String.init(data: logData, encoding: .utf8) else {
-            return ""
+                return ""
```
Comment (jleandroperez) [inline WordPress/Classes/Utility/ZendeskUtils.swift]: Nipticky: Extra tab

File: WordPress/Classes/Utility/ZendeskUtils.swift (hunk 1 above)
Comment (ScoutHarris) [reply WordPress/Classes/Utility/ZendeskUtils.swift]: Thanks @jleandroperez . I'll look at changing it. I hadn't quite figured out how I wanted to handle failures, but I can at least structure it well so it'll be easy to do/change in the future.

**Comment by ScoutHarris** [comment]
@jleandroperez I liked your feedback. It looks much better now, thank you! 

I did the following:
- Added `IfPossible` to the public methods names.
- Changed `createIdentify` to only have a `completion` block.
- I added TODOs for showing errors. I have an item on my todo list to add error handling, so I'd like to address this later.

If you wouldn't mind another review, I'd greatly appreciate it!

File: WordPress/Classes/Utility/ZendeskUtils.swift (hunk 2 above)
Comment (jleandroperez) [reply WordPress/Classes/Utility/ZendeskUtils.swift]: Ahhhhhhh sorry about that!!

File: WordPress/Classes/Utility/ZendeskUtils.swift [hunk 3]
```diff
@@ -279,7 +293,7 @@ private extension ZendeskUtils {
             let logFileInformation = fileLogger.logFileManager.sortedLogFileInfos.first,
             let logData = try? Data(contentsOf: URL(fileURLWithPath: logFileInformation.filePath)),
             let logText = String.init(data: logData, encoding: .utf8) else {
```
[the remark this answers is not in the document]
Comment (ScoutHarris) [reply WordPress/Classes/Utility/ZendeskUtils.swift]: Thanks @jleandroperez . I have two outstanding PRs branched off of this one - I'll fix those last two items in one of those since they're so minor. I'm merging this thing! 😄

**Comment by ScoutHarris** [comment]
Thanks @jleandroperez . I have two outstanding PRs branched off of this one - I'll fix those last two items in one of those since they're so minor. I'm merging this thing! 😄
