### PR TITLE
Fix crash in Comment moderation

### LINKED ISSUE #16431: Crash when marking a comment as spam, then approving or unapproving it
### Expected behavior
No crash, marking a comment as spam moves it to the Spam tab immediately

### Actual behavior

https://user-images.githubusercontent.com/66104034/116929050-17e65e80-ac1b-11eb-814c-2697a77dddff.MP4

### Steps to reproduce the behavior
1. Go to Comments and open the detail view of a comment
2. Mark as Spam
3. Notice it does not move to the Spam tab
4. Tap on Approve/Unapprove 
5. Crash

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #16431 

This fixes an issue that would cause the app to crash after marking a Comment as Spam, then attempting to Approve/Unapprove it.
- `CommentAnalytics` now checks for the existence of `comment.blog` and `comment.postID`.
- Besides the aforementioned crash, multiple moderation actions on a Comment resulted in some weird states. So now the Comment details view is dismissed after any Comment moderation action (approve, unapprove, trash, spam).
- The [previously added](https://github.com/wordpress-mobile/WordPress-iOS/pull/16639) toast message when deleting Comment has been removed as it's now unnecessary.

To test:
- Go to My Site > Comments.
- Select any Comment.
- Perform a moderation action (approve, unapprove, spam, trash).
- Verify the Comment detail view is dismissed.
- Verify the Comment appears in the correct filter.
- Verify these Comment events are logged correctly:
  - comment_viewed
  - comment_replied_to
  - comment_editor_opened
  - comment_edited
  - comment_unliked
  - comment_liked
  - comment_unapproved
  - comment_approved
  - comment_spammed
  - comment_trashed

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Approved, unapproved, trashed, spammed Comments. Verified views were dismissed as expected, and Comment states were updated as expected (i.e. they appeared in the correct filters).

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Comments/CommentViewController.m [hunk 1]
```diff
@@ -546,30 +548,38 @@ - (void)spamComment
     
     UIAlertAction *cancelAction = [UIAlertAction actionWithTitle:NSLocalizedString(@"Cancel", @"Cancel")
                                                            style:UIAlertActionStyleCancel
-                                                         handler:^(UIAlertAction *action){}];
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Comments/CommentViewController.m:549]: Nice.

File: WordPress/Classes/ViewRelated/Comments/CommentViewController.m [hunk 2]
```diff
@@ -504,30 +513,23 @@ - (void)trashComment
...
-    
-    if (error) {
-        DDLogError(@"Comment was deleted while awaiting for alertView confirmation");
-        return;
-    }
-    
     [CommentAnalytics trackCommentTrashedWithComment:[self comment]];
     
-    [commentService deleteComment:reloadedComment success:^{
+    [commentService deleteComment:self.comment success:^{
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Comments/CommentViewController.m:524]: Huh. I wonder why we were doing this.

File: WordPress/Classes/ViewRelated/Comments/CommentAnalytics.swift [hunk 3]
```diff
@@ -27,59 +27,60 @@ import Foundation
...
-        let properties = defaultProperties(comment: comment)
-        WPAnalytics.track(.commentUnliked, properties: properties, blog: comment.blog)
+        trackCommentEvent(comment: comment, event: .commentUnliked)
     }
 
     @objc static func trackCommentRepliedTo(comment: Comment) {
+        trackCommentEvent(comment: comment, event: .commentRepliedTo)
+    }
+
+    private static func trackCommentEvent(comment: Comment, event: WPAnalyticsEvent) {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Comments/CommentAnalytics.swift:75]: Nice consolidation. :)

**Review by aerych — APPROVED** [review]
Hola @ScoutHarris 👋 
Changes look good to me. Nice bit of clean up as well. :) 
:shipit:

File: WordPress/Classes/ViewRelated/Comments/CommentViewController.m (hunk 2 above)
Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/Comments/CommentViewController.m:524]: I finally figured out (after this PR) the weirdness I was seeing is because if you Trash a Spam comment, the comment is _permanently_ deleted. Our alerts don't clarify that (which I'll be fixing). So the Spam and Trash actions were reloading the comment to make sure it existed. But the other actions weren't. And even if they did, because we continued to display the comment details, it appeared to still existed and thus weirdness.

**Comment by ScoutHarris** [comment]
Thanks @aerych !
