### PR TITLE
Issues/3709 non ascii tags

### LINKED ISSUE #3709: Non-ascii character tags cannot be followed in the Reader
With the iOS app, you can't follow tags such as "日本" and "América".

Steps to reproduce:

1. Navigate to the "followed tag" page where you can add tags.
2. In the text field, enter "América".
3. You get "Amrica" tag (missing "é").
4. Then, enter "日本".
5. You get an error saying you couldn't follow the topic & "Request failed: not found (404)" This error message should be translatable too.
6. You also get a tag ":(" instead of the intended phrase. You are unable to unfollow this tag. If you try to remove this tag, you get the same 404 error message.

### PR DESCRIPTION
**Pull request by aerych**
Closes #3709 

Steps to test and confirm the patch are listed in the issue description.

Needs Review: @oguzkocer, would you be game to review this one?

### CODE REVIEW

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m [hunk 1]
```diff
@@ -174,9 +168,24 @@ - (NSString *)sanitizeTopicNameForAPI:(NSString *)topicName
...
+
     return topicName;
 }
 
+- (NSArray *)normalizeMenuTopicsList:(NSArray *)rawTopics subscribed:(BOOL)subscribed recommended:(BOOL)recommended
+{
+    NSMutableArray *topics = [NSMutableArray array];
+    for (NSDictionary *topicDict in rawTopics) {
+        // Failsafe
+        if (![topicDict isKindOfClass:[NSDictionary class]]) {
```
Comment (oguzkocer) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: I wonder if it'd be better to check for this within `normalizeTopicDictionary` so it's future proof. I am not sure about this, so feel free to ignore me :)

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m [hunk 2]
```diff
@@ -174,9 +168,24 @@ - (NSString *)sanitizeTopicNameForAPI:(NSString *)topicName
...
+            continue;
+        }
+        [topics addObject:[self normalizeMenuTopicDictionary:topicDict subscribed:subscribed recommended:recommended]];
+    }
+    return [topics copy]; // Return immutable array.
```
Comment (oguzkocer) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: I am not absolutely sure how this works internally, but if we use `copy` here, wouldn't it create copies for the objects inside the array as well? If so, and if this is what we want, should we implement `NSCopying` protocol for the `RemoteReaderTopic`. If we don't want to actually copy them, can we just return the `topics` directly, since we can't mutate it without casting to `NSMutableArray` by default anyway.

File: WordPress/Classes/Services/ReaderTopicService.m [hunk 3]
```diff
@@ -279,11 +279,10 @@ - (void)followTopicNamed:(NSString *)topicName withSuccess:(void (^)())success f
         }
         return;
     }
-
     ReaderTopicServiceRemote *remoteService = [[ReaderTopicServiceRemote alloc] initWithRemoteApi:[self apiForRequest]];
-    [remoteService followTopicNamed:topicName withSuccess:^{
+    [remoteService followTopicNamed:topicName withSuccess:^(NSNumber *topicID){
         [self fetchReaderMenuWithSuccess:^{
```
Comment (oguzkocer) [inline WordPress/Classes/Services/ReaderTopicService.m]: I know this was already here, but I *think* there is a possible [retain cycle](http://stackoverflow.com/questions/20030873/always-pass-weak-reference-of-self-into-block-in-arc) here.

File: WordPress/Classes/Services/ReaderTopicService.m [hunk 4]
```diff
@@ -430,6 +439,32 @@ - (ReaderTopic *)findTopicNamed:(NSString *)topicName
...
+    NSArray *topics = [self.managedObjectContext executeFetchRequest:request error:&error];
+    if (error) {
+        DDLogError(@"%@ error fetching topic: %@", NSStringFromSelector(_cmd), error);
+        return nil;
+    }
+
+    if ([topics count] == 0) {
+        return nil;
+    }
+    return [topics objectAtIndex:0];
```
Comment (oguzkocer) [inline WordPress/Classes/Services/ReaderTopicService.m]: Maybe we can use objective-c literals here -> `topics[0]`

**Comment by oguzkocer** [comment]
@aerych: I have tested the changes by adding "日本" tag and it's working great! I've left a couple of tiny comments (more like questions), otherwise looks good! Let me know when it's ready for another pass!

/cc @astralbodies for the Core Data changes and migration.

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m (hunk 2 above)
Comment (aerych) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: > wouldn't it create copies for the objects inside the array as well?

Nah. `copy` is a convenience method for `copyWithZone:` and performs a shallow copy of the array.  We could also call `[[NSArray alloc] initWithArray:]` but I prefer this as its shorter.

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: I think its pretty safe. We control the endpoint and would coordinate any changes with an API version bump.  Tho, fwiw I want to change many things about how we retrieve and parse tag topics so this will probably change in the near future anyway.

File: WordPress/Classes/Services/ReaderTopicService.m (hunk 3 above)
Comment (aerych) [inline WordPress/Classes/Services/ReaderTopicService.m]: Let's fix it!

File: WordPress/Classes/Services/ReaderTopicService.m (hunk 4 above)
Comment (aerych) [inline WordPress/Classes/Services/ReaderTopicService.m]: Totes!

Comment (astralbodies) [inline WordPress/Classes/Services/ReaderTopicService.m]: Actually use firstObject - it's safer to use because no error is thrown when index zero doesn't exist. :smile:

Comment (aerych) [inline WordPress/Classes/Services/ReaderTopicService.m]: lol. I had just edited my comment to say the same thing :D

**Comment by aerych** [comment]
@oguzkocer Ready for round two :)

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m (hunk 2 above)
Comment (oguzkocer) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: Good to know, thanks for explaining! :)

File: WordPress/Classes/Networking/ReaderTopicServiceRemote.m (hunk 1 above)
Comment (oguzkocer) [inline WordPress/Classes/Networking/ReaderTopicServiceRemote.m]: Sounds good!

File: WordPress/Classes/Services/ReaderTopicService.m (hunk 3 above)
Comment (oguzkocer) [inline WordPress/Classes/Services/ReaderTopicService.m]: I think you fixed(?) a different one in [#b86841e](https://github.com/wordpress-mobile/WordPress-iOS/commit/b86841e380103eaac8d36da5fe1be14fad66d0e8). I am not even sure if we even need that one, since `self` is not the one performing the action and I don't think that'd create a retain cycle.

I was talking about [this one](https://github.com/wordpress-mobile/WordPress-iOS/blob/issues/3709-non-ascii-tags/WordPress/Classes/Services/ReaderTopicService.m#L285-L286).

**Comment by oguzkocer** [comment]
@aerych I mentioned one more thing and then we're good to go :+1:

File: WordPress/Classes/Services/ReaderTopicService.m (hunk 3 above)
Comment (aerych) [inline WordPress/Classes/Services/ReaderTopicService.m]: doH!  I beg that I had not yet had my coffee when I wrote that patch. Fixing

Comment (oguzkocer) [inline WordPress/Classes/Services/ReaderTopicService.m]: haha :) coffee sounds good!

**Comment by aerych** [comment]
Thanks @oguzkocer.  I rolled back the errant commit and patched the correct block in 431a365b5e55cc6daa15cdd56fb23e8139375437.  Round three?

**Comment by oguzkocer** [comment]
All good @aerych :shipit:

**Comment by aerych** [comment]
Thank ya sir!

**Comment by oguzkocer** [comment]
Happy to be able to help! :)
