### PR TITLE
Move the awful layout code into the right lifecycle method

### LINKED ISSUE #1914: Install Jetpack screen crops icon, doesn't scroll.
On an iPhone in landscape orientation, the Install Jetpack screen crops the Jetpack logo. This would be fine if the view could scroll.

ios simulator screen shot jul 8 2014 2 00 30 pm

### LINKED ISSUE #4665: Stats: Install Jetpack prompt has an odd jump after animating in.
To reproduce: 

- Login to the app with a self-hosted site. 
- Go to My Sites tab > Site Details  > Stats
- Watch the controller transition closely.  When the new controller is finished animating in its content will abruptly jump upward. 

Video demo: https://cloudup.com/c0cEexqrUiX

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #4665 

Corrects a problem with layout being called at the wrong point in the view controller lifecycle. This fixes a glitch with the UI jumping upwards after a remote request has completed.

The ultimate solution is to replace the UI with something with autolayout and not all manual layout code. This would resolve #1914 as well.

**Testing:**
1. Start with a fresh app install.
2. Add self-hosted site that does not have Jetpack installed.
3. Attempt to view settings.
4. View (you should install Jetpack notice) should not jump after a couple seconds.

Also -
1. Start with a fresh app install.
2. Add self-hosted site that has Jetpack installed (and connected).
3. Attempt to view settings.
4. View (log into your Jetpack) should not jump after a couple seconds.

Needs Review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
> Move the awful layout code into the right lifecycle method

The title for this issue has me laughing :D

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m [hunk 1]
```diff
@@ -130,13 +146,6 @@ - (void)viewDidLoad
     [self addSkipButtonIfNeeded];
 }
 
-// This resolves a crash due to JetpackSettingsViewController previously using a .xib.
-// Source: http://stackoverflow.com/questions/17708292/not-key-value-coding-compliant-error-from-deleted-xib
-- (void)loadView
-{
-    [super loadView];
-}
-
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: O.O 
Yay for nuking this bit.

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m [hunk 2]
```diff
@@ -75,7 +75,7 @@ @implementation JetpackSettingsViewController
 
 - (instancetype)initWithBlog:(Blog *)blog
 {
-    self = [super init];
+    self = [super initWithNibName:nil bundle:nil];
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: Curious about this change. I wouldn't think it calling `initWithNibName:bundle:` would make any practical difference.

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m [hunk 3]
```diff
@@ -95,6 +95,8 @@ - (BOOL)hidesBottomBarWhenPushed
 
 - (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
 {
+    [super willAnimateRotationToInterfaceOrientation:toInterfaceOrientation duration:duration];
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: Just a though, `willAnimateRotationToInterfaceOrientation:duration:` is deprecated in iOS8.  Would it make sense to replace it with `viewWillTransitionToSize:withTransitionCoordinator:` as a part of this change?

**Comment by aerych** [comment]
Hiya @astralbodies.  Tested both scenarios and the jump is no longer there.  I had a question and a suggestion but neither are blockers for shipping this patch.  Happy to take a second peek if you choose to switch away from the orientation method.  Otherwise, :shipit: when ready.  :)

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m (hunk 2 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: I just realized this is calling `super`, but if we treat it like a convenience initializer it should probably be calling `self`.

Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: From the Apple Docs:

```
  The designated initializer. If you subclass UIViewController, you must call the super implementation of this
  method, even if you aren't using a NIB.  (As a convenience, the default init method will do this for you,
  and specify nil for both of this methods arguments.) In the specified NIB, the File's Owner proxy should
  have its class set to your view controller subclass, with the view outlet connected to the main view. If you
  invoke this method with a nil nib name, then this class' -loadView method will attempt to load a NIB whose
  name is the same as your view controller's class. If no such NIB in fact exists then you must either call
  -setView: before -view is invoked, or override the -loadView method to set up your views programatically.
```

I'll switch it back to `init` - for some reason I thought the default init method didn't call the same effective initWithNibName:bundle: with nils.

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m (hunk 3 above)
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: I was going to but then that's a whole other PR since all of the layout logic here is manual math.

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m (hunk 1 above)
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: I think the only reason it was here was for crashes happening with the simulator with the old XIB hanging around. The crash never would have happened with an App Store deploy or if the simulator would have just been reset.

**Comment by aerych** [comment]
:shipit:  :)

File: WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m (hunk 3 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: Cool. No worries. I think there might not need to be much of a change to the layout code if `[self layoutControls];` was called from the transition coordinator's completion method. Something to consider later on.

Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m]: It's my goal to replace this with a Storyboard or XIB since there are in fact three different UIs shoved into this view controller.

**Comment by astralbodies** [comment]
Thanks much for the review @aerych!!
