### PR TITLE
Share Extension: use first line of Markdown as title

### LINKED ISSUE #11352: Share Extension: consider making the top line become the post title when sharing from Bear into the WordPress app
### Expected behavior

I had expected the very top Heading from Bear to become the Title of the WordPress post even though logically I see that it is labeled H1.

### Actual behavior

Exporting from Bear to TXT then sharing to the WordPress app results in the title from Bear becoming a Heading in the body of the WordPress post.

### Steps to reproduce the behavior

1. Open Bear and add some content.
1. Tap the (i) icon at top right.
1. Select TXT.
1. Tap the share icon at top right.
1. Select the WordPress app (must be 12.1+).
1. Tap “Next” at top right.
1. Select a site if prompted.
1. Tap “Publish” at top right.
1. View the published post in a browser or preview it in the app.

IMG_2290 IMG_2298
<sup>Tested on WP Internal 12.1.0.20190325 on iPhone 6S iOS 12.2 sharing from Bear into `madefortesting190318.wordpress.com`.</sup>

<sup>(internal ref: p5T066-Nx-p2#comment-2643)</sup>

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #11352 

This PR improves our Markdown import by turning the first line of an MD file into the title of the created post, if that first line is formatted as a heading. 

This substantially improves the experience of sharing items from Bear, which is launching in 12.3 so I have targeted that branch instead of `develop`.

md-post-title

To test:
- Build to device
- In Bear or Ulysses, create a new note with a headline as the first line (this is default in Bear)
- Share that note as either MD file or a TextBundle, open in WP
- Ensure that the first line of the file has become the post's title

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by astralbodies** [comment]
Not sure if this PR caused it or not but I'm seeing these warnings after installing CocoaPods:

```
[!] The `WordPressShareExtension [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressShareExtension/Pods-WordPressShareExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressShareExtension [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressShareExtension/Pods-WordPressShareExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressShareExtension [Release-Internal]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressShareExtension/Pods-WordPressShareExtension.release-internal.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressShareExtension [Release-Alpha]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressShareExtension/Pods-WordPressShareExtension.release-alpha.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressDraftActionExtension [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressDraftActionExtension/Pods-WordPressDraftActionExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressDraftActionExtension [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressDraftActionExtension/Pods-WordPressDraftActionExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressDraftActionExtension [Release-Internal]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressDraftActionExtension/Pods-WordPressDraftActionExtension.release-internal.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressDraftActionExtension [Release-Alpha]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressDraftActionExtension/Pods-WordPressDraftActionExtension.release-alpha.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressTodayWidget [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressTodayWidget/Pods-WordPressTodayWidget.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressTodayWidget [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressTodayWidget/Pods-WordPressTodayWidget.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressTodayWidget [Release-Internal]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressTodayWidget/Pods-WordPressTodayWidget.release-internal.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `WordPressTodayWidget [Release-Alpha]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `../Pods/Target Support Files/Pods-WordPressTodayWidget/Pods-WordPressTodayWidget.release-alpha.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by bummytime** [comment]
@astralbodies I noticed that too. Merging `develop` into this branch seems to address those warnings ☝️ .

File: WordPress/WordPressShareExtension/ShareExtractor.swift [hunk 1]
```diff
@@ -452,34 +452,35 @@ private struct URLExtractor: TypeBasedExtensionContentExtractor {
...
         } else {
             result = ExtractedItem()
         }
-        result.importedText = html
 
-        return result
-    }
+        // If the first line is formatted as a heading, use it as the title
+        var lines = md.components(separatedBy: .newlines)
+        if lines.count > 1, lines[0].first == "#" {
```
Comment (bummytime) [inline WordPress/WordPressShareExtension/ShareExtractor.swift]: Just a style nit (maybe) → any thoughts on breaking this logic out into a separate func?

**Comment by nheagy** [comment]
@astralbodies @bummytime ya, those warnings are unrelated to this PR and have only been fixed on `develop`: #11548
