### PR TITLE
Fix an issue with P2 sites and follow conversation

### LINKED ISSUE #18975: Reader: Can't enable in-app notifications on some posts
### Expected behavior

I expected to be able to enable in-app notifications on any posts in the Reader.

### Actual behavior

When I try to enable in-app notifications on some posts, the toggle immediately toggles off. I noticed it happening on a blog (internal p2) where I already follow all posts and comments via email.

The app logs show the following:

```
2022-07-01 12:57:21:712 🔵 Tracked: reader_toggle_comment_notifications <blog_id: 208157483, default_tab_experiment: dashboard, notifications_enabled: 1, source: reader_post_details_comments, subscription_count: 96>
2022-07-01 12:57:22:037 Error updating notification settings for followed conversation: Optional((extension in WordPressKit):__C.ReaderPostServiceRemote.ResponseError.decodingFailed)
2022-07-01 12:57:22:038 Reader Comments: error toggling notification status: Optional((extension in WordPressKit):__C.ReaderPostServiceRemote.ResponseError.decodingFailed))
```

### Steps to reproduce the behavior

1. Follow all posts and comments on a blog (this can be adjusted in the following settings in https://wordpress.com/following/manage)
2. Find a post from that blog in the Reader.
3. At the bottom of the post detail, tap the bell icon.
4. In the bottom sheet, toggle on "Enable in-app notifications".
5. Notice the setting immediately toggles off. When you close the bottom sheet, a notice appears with the error "Could not enable notifications"

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/18975 and .https://github.com/wordpress-mobile/WordPress-iOS/issues/20953.

The "Follow Conversation" button will now appear for P2 sites where you don't already have the global "Email me new comments" option enabled, which matches how it works on the web. I'm

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/307">25.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/Models/ReaderPost+Swift.swift [hunk 1]
```diff
@@ -3,6 +3,21 @@ import WordPressUI
...
+    /// https://github.com/wordpress-mobile/WordPress-iOS/issues/20953. This code
+    /// makes sure that you see the "Follow Conversation" button on P2s
+    /// but not if you have "Emails me all comments" option enabled, which
+    /// matches the behavior on the web.
+    var canActuallySubscribeToComments: Bool {
+        if canSubscribeComments {
+            return true
+        }
+        if isP2Type() {
+            return !((topic as? ReaderSiteTopic)?.emailSubscription?.sendComments ?? false)
```
Comment (crazytonyli) [inline WordPress/Classes/Models/ReaderPost+Swift.swift:16]: Maybe it's just me, the `!` & `?` makes it hard to read.

```suggestion
            return (topic as? ReaderSiteTopic)?.emailSubscription?.sendComments != true
```

**Review by crazytonyli — APPROVED** [review]
