### PR TITLE
Page the requests for media on XMLRPC.

### LINKED ISSUE #8932: Media: Setting featured image doesn't work due to memory error
Original report by @M1g4 in https://github.com/Automattic/wp-desktop/issues/428

#### Scenario:
We're running a blog with a high number of pictures. Trying to attach a featured image to a post in the iOS-Wordpress-App causes an error. The reason for this error is the abnormal high amount of memory the process on the server needs while trying to load the media. 

The Android-app works perfectly with the exact same blog and the same user.

#### Steps to reproduce
1. Have a blog with a high amount of media
2. Open iOS Wordpress app
3. Start new post
4. Go to options and try to set a featured image 

#### What I expected
Thumbnails of my photos to pick one for upload

#### What happened instead
An error occurs, stating that a problem occured while trying to access my media. I don't know the exact english wording since I use the german app (see screenshot below).

#### App Version / OS version
Wordpress 9.5 // iOS 11.2.2

#### Context / Source
At 128 MB of maximum allowed memory, the server logs look like this while trying to attach a featured image using the iPhone app: 
[21/Mar/2018:11:17:49 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 runtime=715792 php_memory=134217728
[21/Mar/2018:11:17:49 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 runtime=738591 php_memory=134217728
[21/Mar/2018:11:17:50 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 runtime=645105 php_memory=134217728

For comparison, here are the logs of the same process using the Android app: 
[21/Mar/2018:11:18:47 +0100] "POST /xmlrpc.php HTTP/1.1" 200 791 runtime=1158547 php_memory=23068672
[21/Mar/2018:11:19:07 +0100] "POST /xmlrpc.php HTTP/1.1" 200 483 runtime=149115 php_memory=22020096
[21/Mar/2018:11:19:07 +0100] "POST /xmlrpc.php HTTP/1.1" 200 930 runtime=200736 php_memory=22020096

As you can see, the Android app causes the xmlrpc to use less memory. So we tried to increase the max allowed memory to 256 on our server. The result, this time including user agent data for your documents:

[21/Mar/2018:11:36:26 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202 wp-iphone/9.5" runtime=944321 php_memory=268435456
[21/Mar/2018:11:36:26 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202 wp-iphone/9.5" runtime=944745 php_memory=268435456
[21/Mar/2018:11:36:27 +0100] "POST /xmlrpc.php HTTP/1.1" 500 169 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202 wp-iphone/9.5" runtime=872012 php_memory=268435456

As you can see, even 256 MB are not enough. This is a major problem for us, since the only solution without an update of the iOS app would mean archiving or deleting the main part of our images.

#### Screenshot
wordpress_fehler_app

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8932 

This PR implements the paging for the requests of the Media Library of WP.org blog using the XMLRPC Api.

Instead of requesting the library in one go we request pages with 100 elements each.

The way the XMLRPC api implements paging using offset and page could cause some minor data sync issues if media is added to the library at the exact time a sync is happening, but this should auto correct itself on the next sync and was considered a minor issue comparing to server crashes returning big media libraries.

To test:
 - Start the app
 - Add a WP.org site to the site list that **does not** use Jetpack
 - Open the Media Library
 - Check if all media items are there
 - Check with an empty media library just to be sure

### CODE REVIEW

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 1]
```diff
@@ -30,13 +30,40 @@ - (void)getMediaWithID:(NSNumber *)mediaID
...
+                             [media addObjectsFromArray: pageMedia];
+                         }
+                         // Did we got all the items we requested or it's finished?
+                         if (pageMedia.count < pageSize) {
+                             if (success) {
+                                 success(media);
+                             }
+                             return;
+                         }
+                         NSUInteger newOffset = offset + pageMedia.count;
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: I know they should be the same value, but I'd probably add `pageSize` here instead of `pageMedia.count`, just because it's a known constant value.

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 2]
```diff
@@ -30,13 +30,40 @@ - (void)getMediaWithID:(NSNumber *)mediaID
...
+                         [self getMediaLibraryStartOffset:newOffset media:media success: success failure: failure];
                      }
                  }
                  failure:^(NSError *error, NSHTTPURLResponse *httpResponse) {
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: Should we fail entirely if we managed to receive some of the data? If we received 150 / 250 items, I think it would be best to display those, even if we also display an error?

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 3]
```diff
@@ -30,13 +30,40 @@ - (void)getMediaWithID:(NSNumber *)mediaID
 - (void)getMediaLibraryWithSuccess:(void (^)(NSArray *))success
                            failure:(void (^)(NSError *))failure
 {
-    NSArray *parameters = [self defaultXMLRPCArguments];
+    NSMutableArray * mediaResult = [[NSMutableArray alloc] init];
+    [self getMediaLibraryStartOffset:0 media:mediaResult success:success failure:failure];
+}
+
+- (void)getMediaLibraryStartOffset:(NSUInteger)offset
+                             media:(NSMutableArray *)media
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: I think I'd prefer to pass an immutable array here – perhaps we could do that, and just construct a new array each time combining the existing + new items to pass on to the next iteration?

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m (hunk 2 above)
Comment (SergioEstevao) [reply WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: One of the problems here is that when we merge the data we delete anything that is not part of the result. If we are happy with that we could respond success with partial data.

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m (hunk 3 above)
Comment (SergioEstevao) [reply WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: I was just copying what we did for the REST API, but I'm happy to change that the memory implications shouldn't be too bad.

**Comment by SergioEstevao** [comment]
@frosty ready for another look

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 4]
```diff
@@ -52,18 +52,19 @@ - (void)getMediaLibraryStartOffset:(NSUInteger)offset
                      NSAssert([responseObject isKindOfClass:[NSArray class]], @"Response should be an array.");
                      if (success) {
                          NSArray *pageMedia = [self remoteMediaFromXMLRPCArray:responseObject];
+                         NSMutableArray *resultMedia = [NSMutableArray arrayWithArray:media];
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: We can still eliminate the mutable array entirely (and the `if` below), I think, if we just do:

`NSArray *resultMedia = [media arrayByAddingObjectsFromArray:pageMedia];`

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m (hunk 2 above)
Comment (frosty) [reply WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: That makes sense. We could potentially delete media that loaded successfully once but then failed the next time the library was refreshed. Seems safer just to keep it?

The alternative might be to check the local media library count for this site, and if the count is 0 or less than the amount we fetched, we'll keep whatever we managed to fetch?

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 5]
```diff
@@ -30,13 +30,41 @@ - (void)getMediaWithID:(NSNumber *)mediaID
 - (void)getMediaLibraryWithSuccess:(void (^)(NSArray *))success
                            failure:(void (^)(NSError *))failure
 {
-    NSArray *parameters = [self defaultXMLRPCArguments];
+    NSMutableArray * mediaResult = [[NSMutableArray alloc] init];
+    [self getMediaLibraryStartOffset:0 media:mediaResult success:success failure:failure];
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: We could just pass `@[]` here instead of creating `mediaResult`.

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 6]
```diff
@@ -30,13 +30,41 @@ - (void)getMediaWithID:(NSNumber *)mediaID
...
+    NSArray *parameters = [self XMLRPCArgumentsWithExtra:filter];
+
     [self.api callMethod:@"wp.getMediaLibrary"
               parameters:parameters
                  success:^(id responseObject, NSHTTPURLResponse *httpResponse) {
                      NSAssert([responseObject isKindOfClass:[NSArray class]], @"Response should be an array.");
                      if (success) {
-                         success([self remoteMediaFromXMLRPCArray:responseObject]);
+                         NSArray *pageMedia = [self remoteMediaFromXMLRPCArray:responseObject];
+                         NSMutableArray *resultMedia = [NSMutableArray arrayWithArray:media];
```
Comment (frosty) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: We could remove the mutable array entirely here (and the `if` below) and just do:

`NSArray *resultMedia = [media arrayByAddingObjectsFromArray:pageMedia];`

File: WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m [hunk 7]
```diff
@@ -30,13 +30,41 @@ - (void)getMediaWithID:(NSNumber *)mediaID
...
+                         }
+                         // Did we got all the items we requested or it's finished?
+                         if (pageMedia.count < pageSize) {
+                             if (success) {
+                                 success(resultMedia);
+                             }
+                             return;
+                         }
+                         NSUInteger newOffset = offset + pageSize;
+                         [self getMediaLibraryStartOffset:newOffset media:resultMedia success: success failure: failure];
```
Comment (elibud) [inline WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: Am I understanding this correctly and we are getting the entire Media Library for the site in one go? It looks like we are doing the same for .com sites, so performance should be tested already... I'm just surprised this works and doesn't kill the app for sites with a lot of media.

Comment (SergioEstevao) [reply WordPressKit/WordPressKit/MediaServiceRemoteXMLRPC.m]: @elibud so remember the media object it's basically an url with some extra metadata, it's doesn't include the bytes for media, so even a large media library (1000 objects) it's only going to be some kbs top. 
A single image download of a full size iPhoneX image will be a lot larger than all the size of the media library info.

I'm still surprised that the original request complained that the server went crashing when getting all the library, unless they are doing some extra processing on each media object before returning the result I don't see why it's happening.
