### PR TITLE
Use original username when reselected.

### LINKED ISSUE #8962: Signup: Can't cancel a username change after selecting a different username
### Expected behavior

I expect that when I sign up and look at my options to change a username, the username I have selected before I go back is the one I'll end up with.

### Actual behavior

If I select a different username and then select my original username again, I end up with the different username instead.

### Steps to reproduce the behavior

1. Sign up for a new account in the app.
2. On the epilogue screen, select your username to go to the Change Username screen.
3. Note that your original username is first on the list with a checkmark by it.
4. Select another username from the list. Note that it has a checkmark by it.
5. Select your original username again. Note that it has a checkmark by it.
6. Select the "Back" button to go back to the epilogue screen.

Expected: I'll see my original username on the epilogue screen.
Actual: The other username I selected is shown (and is the username I see on the Me screen after completing signup).

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.7.0.20180316

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #8962

To test:
- Follow the repro steps on #8962 
- Verify the original username is used when re-selected.

@elibud - when you have a moment to review, I'd appreciate it!

### CODE REVIEW

**Comment by ScoutHarris** [comment]
@diegoreymendez - please add to 9.7. Thank you!

File: WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift [hunk 1]
```diff
@@ -216,13 +216,14 @@ extension SignupUsernameTableViewController {
         switch indexPath.section {
         case Sections.suggestions.rawValue:
             if indexPath.row == 0 {
-                selectedUsername = ""
+                selectedUsername = currentUsername ?? ""
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift]: `""` is used on line `130` of `SignupEpilogueViewController.swift` to decide if the username change request needs to be performed. With this change, tapping a username and then tapping the original will cause a username change request—it will succeed, but it will hit the network and show the user the "changing username" HUD.

File: WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift [hunk 2]
```diff
@@ -7,7 +7,6 @@ protocol SignupUsernameViewControllerDelegate {
 class SignupUsernameViewController: NUXViewController {
     // MARK: - Properties
     open var currentUsername: String?
-    private var newUsername: String?
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift]: Nice cleanup! ✨

File: WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift (hunk 1 above)
Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift]: Thanks @nheagy . I'll address that in another PR.
