### PR TITLE
ShareExtension: Fixing Sharing from Google Photos

### LINKED ISSUE #5690: Share Extension: Image shared from Google Photos app includes link to local file
### Expected behavior

I expect images to be shared with either no link or a link to the file on a sharing service.
### Actual behavior

When I share a photo from the Google Photos app, it includes a link to the local image file on my device. (I expect either no link or a link to the file uploaded on Google Photos.)

Sharing from Google Photos to WordPress
### Steps to reproduce the behavior
1. Open the Google Photos app
2. Select a photo and tap the sharing icon
3. Select WordPress as the sharing target
4. Note that the sharing dialog includes a link to a local file (beginning `file:///`)

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR updates the `ShareExtractor` order, so that whenever the ImageExtractor can handle a request, it'll be returned **before** the Text Extractor.

Fixes #5690

### To test:
1. Open the Google Photos app
2. Select a photo and tap the sharing icon
3. Select WordPress as the sharing target

Verify that the actual picture gets shared (instead of the local URL)

Needs review: @koke 
Thanks in advance!

### CODE REVIEW

File: WordPress/WordPressShareExtension/ShareExtractor.swift [hunk 1]
```diff
@@ -51,10 +51,10 @@ struct ShareExtractor {
 private extension ShareExtractor {
     var supportedExtractors: [ExtensionContentExtractor] {
         return [
+            ImageExtractor(),
             SharePostExtractor(),
             PropertyListExtractor(),
-            URLExtractor(),
-            ImageExtractor()
+            URLExtractor()
```
Comment (koke) [inline WordPress/WordPressShareExtension/ShareExtractor.swift]: I think I'd just flip these, but otherwise leave SharePost/PropertyList at the top, as they're more specific.

**Comment by jleandroperez** [comment]
@koke updated! ready for another peak!

**Comment by koke** [comment]
Looks good to me, but buddybuild says no. It'll probably resolve itself if you merge develop though

**Comment by jleandroperez** [comment]
Thanks @koke!
