### PR TITLE
Xcode 8.3 / Swift 3.1 Compatibility fixes

### LINKED ISSUE #6936: Update project to support Xcode 8.3 / Swift 3.1
Title has it. Resolve all warnings, check for CocoaPods 1.1.1 compatibility (1.2.1 is not out yet).

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #6936 

This updates the project to Xcode 8.3 and Swift 3.1 compatibility. There were a lot of compiler warnings due to how casting is handled in Swift 3.1. A lot of the logging statements got `String(describing: )` added to prevent a compiler warning about passing an optional in. There are also some slight differences in all the places we are casting an Error to an NSError. 

There are a lot of small nuances to the casting changes I made that could affect the flow of the app. Please make sure to look carefully and discuss any issues you may think could arise.

To test:
1. Run the project.
2. Unit test the project.

Needs review: @nheagy, @SergioEstevao, @jleandroperez, @aerych, @koke, @frosty, @kurzee, @elibud

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m [hunk 1]
```diff
@@ -171,6 +171,8 @@ - (void)viewWillDisappear:(BOOL)animated
 {
     [super viewWillDisappear:animated];
 
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wunused-result"
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m]: Should we use `#pragma clang diagnostic pop`?

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m [hunk 2]
```diff
@@ -188,7 +190,8 @@ - (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIVi
         NSIndexPath *selectedIndexPath = [self.tableView indexPathForSelectedRow];
         // Make sure a selected comment is visible after rotating, and that the replyTextView is still the first responder.
         if (selectedIndexPath) {
-            [self.replyTextView becomeFirstResponder];
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wunused-result"[self.replyTextView becomeFirstResponder];
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m]: Should we use `#pragma clang diagnostic pop`?

File: WordPress/WordPressTest/PushNotificationsManagerTests.m [hunk 3]
```diff
@@ -72,7 +72,9 @@ - (void)testBadgeResetNotificationDoesntAttemptToHandleAnyNotificationKind
     NSDictionary *userInfo = @{ @"type" : @"badge-reset"};
     PushNotificationsManager *manager = [PushNotificationsManager new];
     id mockManager = OCMPartialMock(manager);
-    
+
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wunused-result"
```
Comment (kurzee) [inline WordPress/WordPressTest/PushNotificationsManagerTests.m]: Should we use `#pragma clang diagnostic pop`?

File: WordPress/Classes/ViewRelated/Post/NavBarTitleDropdownButton.m [hunk 4]
```diff
@@ -1,4 +1,4 @@
-#import "NavBarTitleDropdownButton.h"
+#import "NavbarTitleDropdownButton.h"
```
Comment (elibud) [inline WordPress/Classes/ViewRelated/Post/NavBarTitleDropdownButton.m]: Why don't we rename the .h file to be Nav**B**arTitleDropdownButton?

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m (hunk 2 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m]: Maybe also move the objc to its own line

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift [hunk 5]
```diff
@@ -1200,8 +1200,12 @@ import WordPressComAnalytics
             }
 
             let failureBlock = { (error: Error?) in
+                guard let error = error else {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift]: It might make sense / be cleaner to move the cast so its part of the assigment.  Maybe something like:
```
guard let error = error as NSError! else {
        return
    }
```

**Comment by aerych** [comment]
@astralbodies I added a couple of suggestions, but otherwise everything looks good :)

**Comment by astralbodies** [comment]
Thanks for the feedback @aerych @elibud @jleandroperez @kurzee!!

I checked in a few changes and will merge the PR when Buddybuild comes back.

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift (hunk 5 above)
Comment (koke) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift]: The `as` is not conditional so it will always succeed. Doing that will mask `error: Error` with `error: NSError`. I think it's a bit clearer as it is now, but no big deal either way

File: WordPress/Classes/Extensions/CGAffineTransform+Helpers.swift [hunk 6]
```diff
@@ -8,7 +8,7 @@ extension CGAffineTransform {
     /// parameters.
     ///
     static func makeRotation(_ angle: CGFloat, scale: CGFloat) -> CGAffineTransform {
-        let angle   = angle * CGFloat(M_PI) / 180.0
+        let angle   = angle * CGFloat(Double.pi) / 180.0
```
Comment (koke) [inline WordPress/Classes/Extensions/CGAffineTransform+Helpers.swift]: You can use `CGFloat.pi` here and avoid the conversion

File: WordPress/Classes/Models/Notifications/Notification.swift [hunk 7]
```diff
@@ -256,7 +256,7 @@ extension Notification {
         }
 
         guard let timestamp = timestamp, let timestampAsDate = Date.dateWithISO8601String(timestamp) else {
-            DDLogSwift.logError("Error: couldn't parse date [\(self.timestamp)] for notification with id [\(notificationId)]")
+            DDLogSwift.logError("Error: couldn't parse date [\(String(describing: self.timestamp))] for notification with id [\(notificationId)]")
```
Comment (koke) [inline WordPress/Classes/Models/Notifications/Notification.swift]: As an alternative, I'd prefer to use `.debugDescription` instead of `String(describing:)`

**Comment by astralbodies** [comment]
@koke It looks like debugDescription still produces a warning for an optional so you have to provide a default value. 😕

**Comment by astralbodies** [comment]
@koke Made the changes to pi 😄

**Comment by astralbodies** [comment]
Thanks everyone for the reviews!
