### PR TITLE
Issue/10115 image export gps location fix

### LINKED ISSUE #10115: Photo GPS information is not being send to server even when allowed by user
### Expected behavior

When the user has the options "Remove Location From Media" disabled, on their App Privacy Settings, Images sent to the server from the device should send GPS EXIF information if available.

### Actual behavior

Photos are sent with the EXIF information trimmed, including GPS.

### Steps to reproduce the behavior

- Start the app
- Open one of your blogs
- Go to Media
- Upload an image from the device that you know has GPS information.
- Go to the web, and open the Media Library for that blog
- Download the image
- Check on Preview if the image has GPS information.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #10115

This PR changes the MediaAssetExporter in order to export the assets data instead of an UIImage. This allows to maintain all metadata (EXIF info) of the images on the device and export it to the servers if needed.

Because we are now exporting the raw data of assets we also needed to add code to check if the HEIC format is being used, and make sure we convert it to JPG before sending it to the server.

To test:

- [ ] Start the app
- [ ] Make sure you have "Remove Location" disabled on your app settings.
- [ ] Open one of your blogs
- [ ] Go to Media
- [ ] Upload an image from the device that you know has GPS information.
- [ ] Go to the web, and open the Media Library for that blog
- [ ] Download the image
- [ ] Check on Preview if the image has GPS information.
- [ ] Do the same test but now with location removed and see if the GPS information is not set. 
- [ ] Repeat the tests but now with the option to resize images to lower resolution activated.

### CODE REVIEW

File: WordPress/Classes/Utility/Media/MediaAssetExporter.swift [hunk 1]
```diff
@@ -80,7 +81,14 @@ class MediaAssetExporter: MediaExporter {
                 return exportGIF(forAsset: asset, resource: resource, onCompletion: onCompletion, onError: onError)
             }
         }
-
+        // Sergio Estevao: If the image is of the type HEIC we make sure the exportImageType uses JPG,
+        // because WordPress doesn't accept HEIC.
+        if #available(iOS 11.0, *) {
+            if let resource = resources.first,
+                UTTypeEqual(resource.uniformTypeIdentifier as CFString, AVFileType.heic.rawValue as CFString) {
```
Comment (koke) [inline WordPress/Classes/Utility/Media/MediaAssetExporter.swift]: I see other values of `AVFileType` that could be problematic (e.g. `dng`, `tiff`, `heif`,...).
Is this required for this fix? If not, can we split into a different PR and explore an option that always ensures a supported format (jpg/png/gif)?

Comment (SergioEstevao) [reply WordPress/Classes/Utility/Media/MediaAssetExporter.swift]: It's needed because by default photos are now saved in this format on iOS 11. When you try to use the code the way it was, it tried to export them to WP servers on that format, and failed miserably. 
The other formats could also be problematic, but they are not "common" use on iOS like HEIC is at the moment.
