### PR TITLE
Fix #20298: query media observers safely

### LINKED ISSUE #20298: Crash during uploading a photo to the Media Library
**Sentry Url**: https://sentry.io/share/issue/612bebef8e0e436bafada858b6d40099/
**User Count**: 35
**Count**: 43
**First Release**: 21.5.1.0
**First Seen**: 2023-02-02T16:13:42Z
**Last Seen**: 2023-03-08T22:57:30Z
**24 Hours**: 0
**30 Days**: 41
**LogID:** 4A145768-1CD4-4439-A8A4-2D90FC6E58D8

```
EXC_BREAKPOINT: Path is satisfied
  File "MediaCoordinator.swift", line 577, in MediaCoordinator.observersForMedia
  File "<compiler-generated>", line null, in Sequence.filter
  File "<compiler-generated>", line null, in Sequence.filter
  File "MediaCoordinator.swift", line 576, in MediaCoordinator.observersForMedia
  File "MediaCoordinator.swift", line 633, in MediaCoordinator.notifyObserversForMedia
  File "<compiler-generated>", line null, in thunk for closure
...
(9 additional frame(s) were not displayed)
```

------

I experienced this exact crash during development, but couldn't reproduce it.

### PR DESCRIPTION
**Pull request by crazytonyli**
I believe the crash #20298 is related to accessing `media.posts` from an arbitrary queue rather than the context queue that the `media` instance is bound to.

## Test instructions

It's hard to verify the fix because the crash is not easy to verify. But it would be good verify the media uploading still works, i.e. from the "Media" screen, or a post editor.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
What are described in the "Test instructions" section.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/MediaCoordinator.swift [hunk 1]
```diff
@@ -543,42 +543,34 @@ class MediaCoordinator: NSObject {
...
         }
     }
 
     /// Utility method to return all observers for a specific media item,
     /// including any 'wildcard' observers that are observing _all_ media items.
     ///
-    private func observersForMedia(_ media: Media) -> [MediaObserver] {
-        let mediaObservers = self.mediaObservers.values.filter({ $0.media?.uploadID == media.uploadID })
+    private func observersForMedia(withObjectID mediaObjectID: NSManagedObjectID, originalPostIDs: [NSManagedObjectID]) -> [MediaObserver] {
+        let mediaObservers = self.mediaObservers.values.filter({ $0.mediaObjectID == mediaObjectID })
```
Comment (crazytonyli) [inline WordPress/Classes/Services/MediaCoordinator.swift]: The [`uploadID`](https://github.com/wordpress-mobile/WordPress-iOS/blob/8d84b2468e991f037f544086267ce8269930ef06/WordPress/Classes/Services/MediaCoordinator.swift#L740-L742) is `objectID` as a string, so comparing `NSManagedObjectID` should be the same as comparing `uploadID`.

File: WordPress/Classes/Services/MediaCoordinator.swift [hunk 2]
```diff
@@ -543,42 +543,34 @@ class MediaCoordinator: NSObject {
     }
 
     /// Encapsulates an observer block and an optional observed media item or post.
-    struct MediaObserver {
-        let media: Media?
-        let post: AbstractPost?
+    private struct MediaObserver {
+        let mediaObjectID: NSManagedObjectID?
+        let postObjectID: NSManagedObjectID?
```
Comment (mokagio) [inline WordPress/Classes/Services/MediaCoordinator.swift]: Out of scope but _welp_ 😱 The double optional design (which precedes this PR) leaves the door open for an instance with both element `nil`. 

Event thought this are `let` and we have two inits that set either one or the other, I'd "feel better" if the relationship was encoded in the type system. E.g.:

```swift
enum ObservedResource {
  case media(id: NSManagedObjectID)
  case post(id: NSManagedObjectID)
}

let observed: ObservedResource
```

File: WordPress/Classes/Services/MediaCoordinator.swift (hunk 1 above)
Comment (mokagio) [reply WordPress/Classes/Services/MediaCoordinator.swift]: Makes sense.

File: WordPress/Classes/Services/MediaCoordinator.swift (hunk 2 above)
Comment (mokagio) [reply WordPress/Classes/Services/MediaCoordinator.swift]: Update – Reading more of the code below I see that having both values nil is a way to represent "wildcards" and observe _all_ media items.

This could be achieved in the `enum` model I suggested, and IMHO in a more self-explanatory way, like this:

```swift
enum ObservedResource {
  case media(id: NSManagedObjectID)
  case post(id: NSManagedObjectID)
  case all
}
```

**Review by mokagio — APPROVED** [review]
I tested this on the Simulator with a breakpoint in `observersForMedia(withObjectID mediaObjectID:, originalPostIDs:)`.

I uploaded a couple of images from the Media gallery screen, and [one from the editor](https://giotestdotsite.wordpress.com/2023/03/10/post-with-freshly-uploaded-image/).

File: WordPress/Classes/Services/MediaCoordinator.swift [hunk 3]
```diff
@@ -543,42 +543,34 @@ class MediaCoordinator: NSObject {
...
-            self.media = nil
-            self.post = post
+            self.mediaObjectID = nil
+            self.postObjectID = post.objectID
             self.onUpdate = onUpdate
         }
     }
 
     /// Utility method to return all observers for a specific media item,
     /// including any 'wildcard' observers that are observing _all_ media items.
```
Comment (mokagio) [inline WordPress/Classes/Services/MediaCoordinator.swift]: This comment is out of date now 🤔 Could we update it to

```suggestion
    /// Utility method to return all observers for a `Media` item with the given `NSManagedObjectID`
    /// and part of the posts with given `NSManagedObjectID`s, including any 'wildcard' observers 
    /// that are observing _all_ media items.
```

File: WordPress/Classes/Services/MediaCoordinator.swift (hunk 2 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/MediaCoordinator.swift]: Great suggestion. Addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20299/commits/33985c7b0e238ba95eca4aae3de4e243d1da7f38.
