### PR TITLE
Show switch to block editor in empty classic post

### LINKED ISSUE #16293: Cannot switch to block editor from empty post in classic editor
### Expected behavior

With the classic editor open on an empty post, I should be able to switch to the block editor (via the three-dots menu) if the site has "Enable block editor" in the ON position.

### Actual behavior

There's no option to switch to the block editor.

### Steps to reproduce the behavior

1. Locate a site that has the "Enable block editor" switch ON
2. Locate an existing classic post
3. Open it for editing (this will open the classic editor)
4. Delete all its content (it doesn't matter if the title is empty or not)
5. Tap the three-dots menu in the editor and expect to see a "Switch to block editor" option
6. Notice there is no such option

##### Tested on iPhone 11, iOS 14.4.1, WPiOS 17.1 beta

Note: This issue exists in earlier versions (tested as far back as WPiOS 17.0). The bug isn't present in WPAndroid (tested in 17.1 beta).

### PR DESCRIPTION
**Pull request by guarani**
This brings WPiOS in-line with WPAndroid where users in the classic editor can switch to the block editor as long as the post is empty and the site defaults to Gutenberg.

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/16293

To test:
1. Locate a site that has Gutenberg enabled
2. Locate a post created using the classic editor (you might need to temporarily switch the site over to classic by turning the "Enable block editor" switch off in Site Settings, creating a classic post, and switching the site back to Gutenberg)
3. Open the post for editing and remove all content (the title can be left as-is)
4. Tap the three-dots menu and expect to see a "Switch to block editor" option

## Regression Notes
1. Potential unintended areas of impact

The changes to the app's logic only affect the rendering of the "Switch to block editor" action in the classic editor menu bottom sheet. Barring a crash, I don't think these changes could affect other parts of the app.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I smoke tested the change and added a new test.

3. What automated tests I added (or what prevented me from doing so)

I added the `AztecPostViewController+MenuTests` unit tests to help catch regressions if the behavior implemented here breaks.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 1]
```diff
@@ -1277,9 +1277,7 @@ private extension AztecPostViewController {
             }
         }
 
-        if post.blog.isGutenbergEnabled,
-            let postContent = post.content,
-            postContent.count > 0 && post.containsGutenbergBlocks() {
+        if post.blog.isGutenbergEnabled, post.isContentEmpty() || post.containsGutenbergBlocks() {
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift:1280]: `isContentEmpty` considers a post empty [if it contains an empty paragraph block](https://github.com/wordpress-mobile/WordPress-iOS/blob/edce2beb2cc01df3c66942b2b61139cee3892ccf/WordPress/Classes/Models/BasePost.m#L109-L113), but I think that's OK here.

If the user finds themself with the classic editor open on a post that only contains an empty paragraph block, I can't think of a good reason not to allow them to switch over the the block editor.

**Comment by guarani** [comment]
Test comment

**Review by illusaen — APPROVED** [review]
LGTM!
