### PR TITLE
Don't save synced blogs after signed out 

### LINKED ISSUE #20928: Core Data: Invalid parameter not satisfying: account.managedObjectContext == context
`account.managedObjectContext` is not equal to `context` in `(void)updateDefaultBlogIfNeeded:(WPAccount *)account inContext:(NSManagedObjectContext *)context`. The crash happened when logging out and then logging in. 

[The crash doesn't happen in release builds because `NS_BLOCK_ASSERTIONS` flag is defined. ](https://developer.apple.com/documentation/foundation/nsparameterassert)

Sentry Issue: [JETPACK-IOS-FXR](https://a8c.sentry.io/issues/4264408912/?referrer=github_integration)

```
NSInternalInconsistencyException: Invalid parameter not satisfying: account.managedObjectContext == context
  File "AccountService.m", line 360, in -[AccountService updateDefaultBlogIfNeeded:inContext:]
  File "BlogService.m", line 469, in -[BlogService mergeBlogs:withAccountID:inContext:]
  File "BlogService.m", line 41, in __51-[BlogService syncBlogsForAccount:success:failure:]_block_invoke_3
  File "ContextManager.swift", line 120, in ContextManager.performAndSave
  File "<compiler-generated>", in ContextManager.performAndSave
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #20928.

This crash (or the failed assertion `NSParameterAssert(account.managedObjectContext == context)`) happens because syncing blogs operation (which is kicked off from the site picker screen) continues to run even though the app has signed out. When the syncing blogs API request(s) come back, the account is deleted from the database and the assertion fails because `account` is `nil`.

## Test Instructions

See https://github.com/wordpress-mobile/WordPress-iOS/issues/20928#issuecomment-1608570438 for steps to reproduce this bug. Verify the crash is no longer reproducible. And you should see a "Can't find the account. User may have signed out." log on Xcode console output.

You can also reproduce the issue by commenting out the `BlogService` changes and running the new unit test added in this PR.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
What's described in the Test Instructions.

3. What automated tests I added (or what prevented me from doing so)
One unit test that can be used to reproduce the issue.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

File: WordPress/WordPressTest/BlogJetpackTests.swift [hunk 1]
```diff
@@ -151,6 +151,43 @@ class BlogJetpackTests: CoreDataTestCase {
...
     }
 
+    /// Verify an account's blogs won't be saved if the account is deleted during a blog sync.
+    func testSyncBlogsAndSignOut() throws {
+        let wpComAccount = try createOrUpdateAccount(username: "user", authToken: "token")
+        XCTAssertEqual(Blog.count(in: mainContext), 0)
+        var deleted = false
+
+        // Blog sync makes a series of HTTP requests: the first one fetchs all blogs, followed by a few
+        // requests to get blog capabilities (one for each blog).
```
Comment (crazytonyli) [inline WordPress/WordPressTest/BlogJetpackTests.swift:161]: IMO, it's not efficient to make individual HTTP requests to the same endpoint. I've created https://github.com/wordpress-mobile/WordPress-iOS/issues/20964 to suggest a potential improvement: creating a new API endpoint that accepts a list of site id and returns their Jetpack capablities.

File: WordPress/Classes/Services/BlogService.m [hunk 2]
```diff
@@ -424,6 +424,11 @@ - (void)mergeBlogs:(NSArray<RemoteBlog *> *)blogs withAccountID:(NSManagedObject
 {
     // Nuke dead blogs
     WPAccount *account = [context existingObjectWithID:accountID error:nil];
```
Comment (mokagio) [inline WordPress/Classes/Services/BlogService.m]: While we're at it, should we also add error handling, or at least error capturing? If nothing else, it might give more information in the logs.

File: WordPress/WordPressTest/BlogJetpackTests.swift (hunk 1 above)
Comment (mokagio) [reply WordPress/WordPressTest/BlogJetpackTests.swift:161]: Worth adding a link to the issue, in case we'll get to work on it and do a search in the codebase for its reference?
```suggestion
        // requests to get blog capabilities (one for each blog).
        //
        // See also https://github.com/wordpress-mobile/WordPress-iOS/issues/20964
```

File: WordPress/WordPressTest/BlogJetpackTests.swift [hunk 3]
```diff
@@ -151,6 +151,43 @@ class BlogJetpackTests: CoreDataTestCase {
...
+        let syncExpectation = expectation(description: "Blogs sync")
+        blogService.syncBlogs(for: wpComAccount) {
+            syncExpectation.fulfill()
+        } failure: { error in
+            XCTFail("Sync blogs shouldn't fail: \(error)")
+        }
+
+        // No blogs should be saved after the sync blogs operation finishes.
+        wait(for: [syncExpectation], timeout: 1.0)
+        XCTAssertEqual(Blog.count(in: mainContext), 0)
```
Comment (mokagio) [inline WordPress/WordPressTest/BlogJetpackTests.swift:190]: I verified that without the change in `BlogService.m` from this diff this new test fails:

Screenshot 2023-06-28 at 4 11 08 pm

Comment (mokagio) [reply WordPress/WordPressTest/BlogJetpackTests.swift:190]: Can you double check my understanding of this test?

1. Setup the stage by loading an account
2. Verify there are no blogs in the database
3. Stub network requests to return some blogs
4. Run `syncBlogs` which would proceed to save in the DB all the blogs it received from the stubbed request
5. Delete the account (as part of the stubbed networking behavior) to simulate a logout
6. Verify there are still no blogs in the DB, which confirms that the data for the account we deleted/logged out from was not stored

Is that right?

**Review by mokagio — APPROVED** [review]

File: WordPress/WordPressTest/BlogJetpackTests.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPress/WordPressTest/BlogJetpackTests.swift:190]: Yep. 100% correct. 😃

Comment (mokagio) [reply WordPress/WordPressTest/BlogJetpackTests.swift:190]: 😄
