### PR TITLE
Make sure the media is attached to post.

### LINKED ISSUE #8009: Media not properly attached to post on development and internal builds
### Expected behavior
When uploading Media into a post the resulting object should have the field `post_ID` properly configured.

### Actual behavior
The `post_ID` field is always 0.

While investigating https://github.com/wordpress-mobile/WordPress-iOS/issues/7943 I noticed that we are not setting the `post_ID` value on `Media` objects, and this seems to come back to the new `MediaService` changes.
If you compare `MediaService` vs `MediaService+Legacy` you can see that in the first one all media objects are created using the method `makeMediaWithBlog` but in the second one we use `makeMediaWithBlog` and `makeMediaWithPost` depending on the context, thus inserting the media in the post correctly. 

### Steps to reproduce the behavior
Create a new post, add local media to it and publish it. Check the media object in the console, it will not be correct.

##### Tested on Simulator, iOS 11, WPiOS 8.7

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8009 

So this PR restore the attachment of media to the posts on the new media code.
It also fix a status of the media object when the they are created.

To test:
 - Open the app
 - Start a new post
 - Insert a media object to the post
 - Publish the post
 - Go to the web and using the old WP-Admin check in the media library if your new media object is attached to the post.

### CODE REVIEW

File: WordPress/Classes/Services/MediaExportService.swift [hunk 1]
```diff
@@ -182,6 +199,7 @@ open class MediaExportService: LocalCoreDataService {
     /// Configure Media with the AssetExport.
     ///
     fileprivate func configureMedia(_ media: Media, withExport export: MediaAssetExporter.AssetExport) {
+        media.remoteStatusNumber = NSNumber(value: MediaRemoteStatus.local.rawValue)
```
Comment (frosty) [inline WordPress/Classes/Services/MediaExportService.swift]: I don't feel like this belongs in this method. Everything else in this class is just to do with exporting the media, and the remote status isn't really related.

I feel like it'd make more sense in `makeMedia(in:)` in `Media+Blog`, as a kind of default value for the status (we also set the mediaID to zero and the creation date in there).

**Comment by SergioEstevao** [comment]
@frosty ready for another look

File: WordPress/Classes/Models/Media.m [hunk 2]
```diff
@@ -162,15 +162,17 @@ - (void)setRemoteStatus:(MediaRemoteStatus)aStatus
...
-            return NSLocalizedString(@"Uploaded", @"");
-        default:
-            return NSLocalizedString(@"Pending", @"");
+            return NSLocalizedString(@"Uploaded", @"Status for Media object that is uploaded and sync with server.");
+        case MediaRemoteStatusProcessing:
+            return NSLocalizedString(@"Pending", @"Status for Media object that is being processed locally.");
+        case MediaRemoteStatusLocal:
+            return NSLocalizedString(@"Local", @"Status for Media object that is only exists locally.");
     }
 }
```
Comment (elibud) [inline WordPress/Classes/Models/Media.m]: Good job on adding those localization comments :)
