### PR TITLE
Draft post card: Prevent crash when re-opening post mid-upload

### LINKED ISSUE #20870: EXC_BREAKPOINT: frameLength > managedObjectContext > retainWeakReference
Sentry Issue: [JETPACK-IOS-1EW](https://a8c.sentry.io/issues/4145777221/?referrer=github_integration)

```
EXC_BREAKPOINT: frameLength > managedObjectContext > retainWeakReference
  File "GutenbergViewController.swift", in value
  File "GutenbergViewController.swift", line 1090, in GutenbergViewController.gutenbergDidRequestSendEventToHost
  File "RNReactNativeGutenbergBridge.swift", line 407, in RNReactNativeGutenbergBridge.sendEventToHost
  File "<compiler-generated>", line 406, in RNReactNativeGutenbergBridge.sendEventToHost
  File "RCTModuleMethod.mm", line 584, in -[RCTModuleMethod invokeWithBridge:module:arguments:]
...
(12 additional frame(s) were not displayed)
```

## How to reproduce it
* Navigate to the Home screen and scroll to the "Work on a draft post" card.
* Tap on a draft post.
* Modify the content and save it.
* While the post is being uploaded, open the post again from the "Work on a draft post" card.
* Wait a couple of seconds until the notification stating the that post has been uploaded shows up.
* Try to modify a block or create one.
* Observe the crash.

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/20870

## Description

Prevents a crash when accessing drafts that are mid-upload from the Home screen's 'Work on a Draft Post' card. 

The proposed fix takes the existing code preventing posts being edited mid-upload from the main posts lists [from the `PostListViewController.swift` file](https://github.com/wordpress-mobile/WordPress-iOS/blob/0520842897ec3f11868fef24e3f76d916f4b21c3/WordPress/Classes/ViewRelated/Post/PostListViewController.swift#L613-L616). The code is then added at the top of [the `PostListEditorPresenter.swift` file](https://github.com/wordpress-mobile/WordPress-iOS/blob/0520842897ec3f11868fef24e3f76d916f4b21c3/WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift), so that it fires no matter the screen the user is attempting to access the post from. 

## Testing

> **Note**
> It may be necessary to simulate a poor connection in order to be able to re-open a post while it's still uploading.

**Verify crash is resolved**

* Navigate to the Home screen and scroll to the "Work on a draft post" card.
* Tap on a draft post.
* Modify the content.
* Tap the X icon to the editor's upper left and choose the option to update the post.
* While the post is being uploaded, open the post again from the "Work on a draft post" card.
* Verify that a prompt prevents you from editing the post while it's uploading, as per the following screenshot.

**Verify there are no regressions via Post List screen**

* Navigate to the Post List screen.
* Tap on a draft post.
* Modify the content.
* Tap the X icon to the editor's upper left and choose the option to update the post.
* While the post is being uploaded, open the post again from the Post List screen.
* Verify that a prompt prevents you from editing the post while it's uploading.

## Regression Notes
1. Potential unintended areas of impact

Any other changes to the 'Work on a Draft Post' card's functionality would be unintended, such as any blockers to the ability to open uploaded drafts via that card.  

In addition, as we're moving code that impacts the Post List screen, it would be unintentional to introduce any issues related to editing posts via that screen. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I manually tested opening and editing posts via the card and the Post List screen.

3. What automated tests I added (or what prevented me from doing so)

As I lack native expertise, I'd like to await feedback on this proposal before investigating automated tests.

<hr />

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 1]
```diff
@@ -610,10 +610,6 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
         guard let post = apost as? Post else {
             return
         }
-        guard !PostCoordinator.shared.isUploading(post: post) else {
```
Comment (SiobhyB) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift:613]: In the first iteration of this fix I essentially duplicated this code in the `DashboardPostsListCardCell.swift` file (see: https://github.com/wordpress-mobile/WordPress-iOS/pull/20872/commits/c5dd3024a4b3473e0b56a4bbc78d992d2d585789). However, moving to the `PostListEditorPresenter.swift` file felt like the more robust solution, as this is also being done [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/0520842897ec3f11868fef24e3f76d916f4b21c3/WordPress/Classes/ViewRelated/Pages/PageEditorPresenter.swift#L16-L19) in the `PageListPresenter.swift` file. I'd be curious whether there are any blockers or downsides to this approach.

**Comment by SiobhyB** [comment]
👋 @hassaanelgarem, GitHub recommended you as someone who has edited these files a lot in the past, would you be available to take a look? If not, let me know and I'll try to find another reviewer :)

**Comment by hassaanelgarem** [comment]
@SiobhyB Yes, I can take a look for sure 👍

**Review by hassaanelgarem — APPROVED** [review]
The changes look good to me! I tested the drafts and scheduled posts cards and the posts list, they all work as expected now and the crash is irreproducible.
