### PR TITLE
Fix ampersand display in profile names and comments author

### LINKED ISSUE #8911: & character not appearing correctly in iOS app
I noticed something in the iOS app recently.  When using the & as part of your public display name there are some unexpected results.  The & symbol ends up display it's self as &amp; instead of just & You can see this problem in this image.

This ends up effecting more then just how your profile appears, if you comment on another post while your display not is showing &amp; that is how other users will see your display name on comments.  

To reproduce.
1. Change your public display name to include the & symbol
2. Check your Me page in the app, it should appear with &amp; instead of  just &

(note: I tested this by changing my public display name in the app and from calypso, same problem occurred)

iPhone 6s
WordPress 9.4
iOS 11.2.6

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #8911 

To test:

**Profile Names:**
- Put an ampersand in Display Name, First Name, and Last Name.
- Verify they display correctly on:
  - Me tab header.
  - My Profile page.

**Comment Authors:**
- Comment on a blog post.
- Verify the author displays correctly on:
  - My Sites > Comments
  - My Sites > Comments > select a comment
  - Reader > click on Comment icon

**Me tab header:**
me

**My Profile page:**
my_profile

**My Sites > Comments:**
sites comments

**Reader > Comments:**
reader comments

@koke , @jleandroperez - could I bother one of you for a review please? Thanks!!!

### CODE REVIEW

File: WordPress/Classes/Services/AccountSettingsService.swift [hunk 1]
```diff
@@ -196,7 +196,16 @@ class AccountSettingsService {
...
         }
-        return results.first
+
+        guard let account = results.first else {
+            return nil
+        }
+
+        account.displayName = account.displayName.stringByDecodingXMLCharacters()
+        account.firstName = account.firstName.stringByDecodingXMLCharacters()
+        account.lastName = account.lastName.stringByDecodingXMLCharacters()
```
Comment (jleandroperez) [inline WordPress/Classes/Services/AccountSettingsService.swift]: This one feels a bit odd, since the method is expected to *load* from CoreData, but instead, it's also modifying few properties. Although this particular scenario is okay, i've got first hand experience debugging issues related to this practise, for hoooours and hoooours.

How about if, instead:

### Alternative A
. We add properties, like the one you've used below (`authorForDisplay`): **firstNameForDisplay** / **lastNameForDisplay** ... and, oh well, **displayNameForDisplay**?

### Alternative B
Probably cleaner and easier: maybe just do the conversion in the AccountSettings initialization?

**Comment by ScoutHarris** [comment]
@jleandroperez - turns out, there was already an `AccountSettings.init` that takes `ManagedAccountSettings`, so I used that. Please review again. Thanks!
