### PR TITLE
Fix orientation of images when copy pasted to a post

### LINKED ISSUE #8613: Images that are copy pasted to Aztec can get the wrong orientation
### Expected behavior

Images that where taken upside down/inverted landscape should be copy pasted correctly to the aztec editor.

### Actual behavior

Images are being copy pasted with the wrong orientation.

### Steps to reproduce the behavior

- On a device take photo with the device upside down (home button on the top)
- Select that image on the Photos app and select copy
- Open the mobile and start a new post using Aztec
- Paste the image on the content
- See the image upside down

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8613 

This PR, changes the place were we remove the orientation info to only be done when we are resizing the images and use the `kCGImageSourceCreateThumbnailWithTransform` option. ]
When we just copying the full size image we should keep the original orientation info.

To test:
 - Check the ticket above for step on how to reproduce

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@frosty I think I need to fix the test and add the two scenarios, one for when you resize and another when you don't resize.

**Comment by SergioEstevao** [comment]
@frosty ready for another look.

**Comment by frosty** [comment]
I think there are still changes required to the tests – the one that you've modified still mentions "correcting the orientation" both in the text name and the expectation description, but the orientation is no longer changed. And then I think we need to add another test where the image is resized and the orientation is changed?

**Comment by SergioEstevao** [comment]
@frosty ready for another look.

File: WordPress/WordPressTest/MediaImageExporterTests.swift [hunk 1]
```diff
@@ -174,7 +174,8 @@ class MediaImageExporterTests: XCTestCase {
         let exporter = MediaImageExporter(image: image, filename: nil)
```
Comment (frosty) [inline WordPress/WordPressTest/MediaImageExporterTests.swift]: Sorry to nitpick – would you mind just updating the description for the expectation as well? Perhaps `image export by UIImage and not altering the orientation`? After that, let's :shipit:
