### PR TITLE
Fix Login's unwind segue breaking transitions

### LINKED ISSUE #7088: Navigation controller transitions break after login
As discovered by @frosty the transitions for the navigation controller breaks after using the new login process. Once "broken" the navigation controller no longer animates when going back.

This appears to be a problem with the unwind segue.

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #7088

To test:
- Use the new login process to login (on for debug builds)
- Ensure that the blog list navigation controller's transitions still work
- Also ensure that the tab bar can still show UIAlerts—such as when tapping "Log Out" from the Me tab

Needs review: @frosty 
_You found it you have to review it_ 😝

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m [hunk 1]
```diff
@@ -888,9 +888,11 @@ - (void)willTransitionToTraitCollection:(UITraitCollection *)newCollection withT
                                  completion:nil];
 }
 
+// this method allows this VC to be a valid unwind destination for this selector
 - (IBAction)unwindOutWithSegue:(UIStoryboardSegue *)segue
 {
-    // here so that this VC is a valid unwind destination for this selector
+    // unwind segues don't seem to always clean themselves up 😫
+    [self dismissViewControllerAnimated:NO completion:nil];
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: Do we need to double check which segue it is, or that something's being presented?

Comment (nheagy) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: We can call `-dismissViewControllerAnimated` when nothing has been presented without problems. Atm there is only one unwind targetting this selector, so we're good there too.

I'm merging this now, and trying to solve the flicker elsewhere. Need to take a break so I keep some hair 😜

Thanks @frosty
