### PR TITLE
Fix Core Data crash related to media errors

### LINKED ISSUE #17802: Retrying failed media uploads without Internet connectivity leads to Core Data exception
Fixed by #17488, #17759.

**On a self-hosted site not connected to Jetpack:**

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The Internet connection appears to be offline."
8. Tapping "Retry" crashes the app

**On a WordPress.com site:**

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The internet connection appears to be offline." (Internet is not capitalized)
8. Tapping "Retry" crashes the app

### PR DESCRIPTION
**Pull request by twstokes**
This PR aims to fix a Core Data crash when persisting Media errors due to underlying types in `UserInfo` that don't adopt `NSSecureCoding`.

The solution proposed here is to strip all but explicitly defined keys in the setter of `Media.error`.

### Overview example:

An NSError is thrown by iOS that there's no Internet connectivity. Its `UserInfo` dictionary contains an `NSUnderlyingError` which contains an object whose class doesn't conform to `NSSecureCoding`. It also contains other standard keys such as `NSLocalizedDescription`, and `NSErrorFailingURLKey`.

**Before this change:**

When saving the context, Core Data would throw an exception once it reached the object that couldn't be encoded, because it didn't adopt `NSSecureCoding`.

**After this change:**

When saving the context, Core Data only encodes `NSLocalizedDescription` with no error. The persisted error is a stripped down encodable version of the original.

Related:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/17488

**To test:**

On a self-hosted site not connected to Jetpack:

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The Internet connection appears to be offline."
8. Tapping "Retry" does not crash the app.
9. Disabling Airplane Mode, tapping the image, and tapping "Retry" successfully uploads the image.

On a WordPress.com site:

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The Internet connection appears to be offline."
8. Tapping "Retry" does not crash the app.
9. Disabling Airplane Mode, tapping the image, and tapping "Retry" successfully uploads the image.

### Other context

Exact error that would be produced:

```
CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLSaveChangesRequestContext: 0x151fc5b90> , <shared NSSecureUnarchiveFromData transformer> threw while encoding a value. with userInfo of {
    NSUnderlyingError = "Error Domain=NSCocoaErrorDomain Code=4866 \"The data couldn\U2019t be written because it isn\U2019t in the correct format.\" UserInfo={NSUnderlyingError=0x155c23f60 {Error Domain=NSCocoaErrorDomain Code=4864 \"This decoder will only decode classes that adopt NSSecureCoding. Class 'NWConcrete_nw_path' does not adopt it.\" UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class 'NWConcrete_nw_path' does not adopt it.}}}";
}
```

## Regression Notes
1. Potential unintended areas of impact
  - Different error scenarios:
    - Uploading media to a self-hosted site that's low on storage
    - Uploading media that's too large to a self-hosted site
    - Uploading media to a WP.com / Jetpack connected site in Airplane mode

Because we're only cherrypicking one field from the error now (`NSLocalizedDescription`), there's a possibility other fields were used somewhere else in the app.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
The testing steps above. I relied on the Core Data migration tests from version 103 to 104 of the data model.

3. What automated tests I added (or what prevented me from doing so)
I updated the Core Data migration tests to test that keys that aren't explicitly defined in the setter of Media.error aren't included.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ttahmouch — COMMENTED** [review]
The changes look good to me. I'm not sure if there is an easy way to test the sad path nor if it would be useful for these edge cases, but we probably should if it's not a large undertaking?

**Comment by twstokes** [comment]
> The changes look good to me. I'm not sure if there is an easy way to test the sad path nor if it would be useful for these edge cases, but we probably should if it's not a large undertaking?

Thanks @ttahmouch! I'm going to take a little more time on this PR because the scope of how this crash can be triggered is potentially larger than just what I've identified here.

File: WordPress/WordPressTest/CoreDataMigrationTests.m [hunk 1]
```diff
@@ -1322,7 +1322,7 @@ - (void)testMigrationFrom103To104CustomTransformers
     // Media has an Error transformer
     Media *media1 = (Media *)[NSEntityDescription insertNewObjectForEntityForName:[Media entityName] inManagedObjectContext:context];
     media1.blog = blog1;
-    NSError *error1 = [NSError errorWithDomain:NSURLErrorDomain code:100 userInfo:@{ @"reason": @"test" }];
+    NSError *error1 = [NSError errorWithDomain:NSURLErrorDomain code:100 userInfo:@{ NSLocalizedDescriptionKey: @"test" }];
```
Comment (ttahmouch) [inline WordPress/WordPressTest/CoreDataMigrationTests.m]: 👍

File: WordPress/Classes/Services/MediaService.m [hunk 2]
```diff
@@ -434,11 +434,13 @@ - (NSError *)customMediaUploadError:(NSError *)error remote:(id <MediaServiceRem
             }
         }
     }
+
     if (customErrorMessage) {
-        NSMutableDictionary *userInfo = [[NSMutableDictionary alloc] init];
+        NSMutableDictionary *userInfo = [error.userInfo mutableCopy];
         userInfo[NSLocalizedDescriptionKey] = customErrorMessage;
         error = [[NSError alloc] initWithDomain:error.domain code:error.code userInfo:userInfo];
```
Comment (ttahmouch) [inline WordPress/Classes/Services/MediaService.m]: **Nit:**
```
error = [NSError errorWithDomain:error.domain code:error.code userInfo:userInfo }];
```

File: WordPress/Classes/Services/MediaService.m [hunk 3]
```diff
@@ -434,11 +434,13 @@ - (NSError *)customMediaUploadError:(NSError *)error remote:(id <MediaServiceRem
             }
         }
     }
+
     if (customErrorMessage) {
-        NSMutableDictionary *userInfo = [[NSMutableDictionary alloc] init];
+        NSMutableDictionary *userInfo = [error.userInfo mutableCopy];
```
Comment (ttahmouch) [inline WordPress/Classes/Services/MediaService.m:439]: 👍

Was lacking extra fields on the dictionary causing issues?

Comment (twstokes) [inline WordPress/Classes/Services/MediaService.m:439]: This reverts the fix [introduced here](https://github.com/wordpress-mobile/WordPress-iOS/pull/17488/files#diff-24c20c98b279ad5a4856285338d0e4a1a25847f7be842379bd954844098c685dR438) in favor of passing all `UserInfo` values up to the new setter, which could cherry pick more if needed in the future.

File: WordPress/Classes/Models/Media.m [hunk 4]
```diff
@@ -261,4 +261,20 @@ - (BOOL)hasRemote {
...
+    NSError *error;
+
+    if (value != nil) {
+        // Cherry pick keys that support secure coding. NSErrors thrown from the OS can
+        // contain types that don't adopt NSSecureCoding, leading to a Core Data exception and crash.
+        NSDictionary *userInfo = @{NSLocalizedDescriptionKey: value.localizedDescription};
+        error = [[NSError alloc] initWithDomain:value.domain code:value.code userInfo:userInfo];
+    }
+
+    [self willChangeValueForKey:@"error"];
```
Comment (twstokes) [inline WordPress/Classes/Models/Media.m:273]: The setter boilerplate was generated from Xcode, so it makes me feel better about its legitimacy. 😄

**Comment by twstokes** [comment]
@frosty, would you mind giving this PR a look over since you'd [worked on the transformers part](https://github.com/wordpress-mobile/WordPress-iOS/blob/4eb29d11695ea4966094408e0100102c49b8fa19/WordPress/Classes/Models/ValueTransformers.swift#L35)? I'm totally open to a more optimal solution than the setter method if there are better ideas. 🙇

File: WordPress/Classes/Models/Media.m [hunk 5]
```diff
@@ -261,4 +261,20 @@ - (BOOL)hasRemote {
     return self.mediaID.intValue != 0;
 }
 
+- (void)setError:(NSError *)value
```
Comment (ttahmouch) [inline WordPress/Classes/Models/Media.m]: **Nit:**
```
- (void)setError:(NSError *)error
```

File: WordPress/Classes/Models/Media.m [hunk 6]
```diff
@@ -261,4 +261,20 @@ - (BOOL)hasRemote {
...
+{
+    NSError *error;
+
+    if (value != nil) {
+        // Cherry pick keys that support secure coding. NSErrors thrown from the OS can
+        // contain types that don't adopt NSSecureCoding, leading to a Core Data exception and crash.
+        NSDictionary *userInfo = @{NSLocalizedDescriptionKey: value.localizedDescription};
```
Comment (ttahmouch) [inline WordPress/Classes/Models/Media.m]: Is the `localizedDescription` the only field we'd want to cherry-pick?

Is the code that was assuming everything was conforming to the `NSSecureCoding` protocol something we built? Should that just be modified to something conditional?

e.g.,
```
if ([object respondsToSelector:@selector(supportsSecureCoding)] && [object supportsSecureCoding]) {
```
or similar.

**Review by ttahmouch — APPROVED** [review]
The changes look good to me overall.

I'm just not positive replacing the originally emitted `NSError` is the best approach because I don't know if the state that was being encoded and decoded conforming to `NSSecureCoding` was needed at all, or if it could have simply been ignored if non-conformant.

File: WordPress/Classes/Services/MediaService.m (hunk 2 above)
Comment (ttahmouch) [reply WordPress/Classes/Services/MediaService.m]: This wasn't your change, but I noticed some variations of usages between the convenience static constructors and alloc/init.

File: WordPress/Classes/Models/Media.m (hunk 5 above)
Comment (twstokes) [reply WordPress/Classes/Models/Media.m]: Good catch! The setter was created automatically via Xcode and I should've cleaned that up. Done.

File: WordPress/Classes/Models/Media.m (hunk 6 above)
Comment (twstokes) [reply WordPress/Classes/Models/Media.m]: > Is the localizedDescription the only field we'd want to cherry-pick?

This is my understanding based on how I've observed we use the errors. Typically we're only caring about the error domain, type, and the description (e.g. to display to the user in a bottom sheet when they need to retry an upload). I had added in the Regression Notes, though, that there's a chance we used another field somewhere.

> Is the code that was assuming everything was conforming to the NSSecureCoding protocol something we built? Should that just be modified to something conditional?

I'd considered checking protocol conformance but I believe it turns into a case where we need to traverse the object graph. For instance, `NSError` conforms to `NSSecureCoding` [[source](https://developer.apple.com/documentation/foundation/nserror?language=objc)], but its `UserInfo` dictionary could contain an arbitrary value that doesn't.

When looking at the overall scope of how we're using these errors, I went with the cherrypicking approach.

File: WordPress/Classes/Services/MediaService.m (hunk 3 above)
Comment (twstokes) [reply WordPress/Classes/Services/MediaService.m:439]: No, but this was a form of cherrypicking already (we only used the custom error message as the description), so I wanted to move all the filtering to the setter.

File: WordPress/Classes/Services/MediaService.m (hunk 2 above)
Comment (twstokes) [reply WordPress/Classes/Services/MediaService.m]: I'll update this and the setter, looks cleaner. 👍

File: WordPress/Classes/Models/Media.m (hunk 6 above)
Comment (ttahmouch) [reply WordPress/Classes/Models/Media.m]: Yeah, I suppose I assumed that we'd already be traversing the object graph somewhere, but it's probably not our code that would be doing that directly when we are serializing the `NSDictionary`.

The cherry-picking approach seems fine.

File: WordPress/Classes/Services/MediaService.m (hunk 3 above)
Comment (ttahmouch) [reply WordPress/Classes/Services/MediaService.m:439]: That makes sense.

**Comment by twstokes** [comment]
> I'm just not positive replacing the originally emitted `NSError` is the best approach because I don't know if the state that was being encoded and decoded conforming to `NSSecureCoding` was needed at all, or if it could have simply been ignored if non-conformant.

I'm not 100% sure on this myself but it may be a requirement to conform now. https://github.com/wordpress-mobile/WordPress-iOS/issues/15167 has some information where warnings appeared starting with Xcode 12.

**Review by frosty — APPROVED** [review]
The code changes look good to me, and I can't think of any other places we use the errors other than those you've identified.

However, when testing I followed the steps on both `trunk` and this branch, and I was unable to cause the original crash to happen on `trunk` so I can't 100% verify that these changes have made a difference there!

**Comment by twstokes** [comment]
> However, when testing I followed the steps on both `trunk` and this branch, and I was unable to cause the original crash to happen on `trunk` so I can't 100% verify that these changes have made a difference there!

Thanks @frosty! I'll double-check this to make sure nothing has changed since the PR started.

**Comment by twstokes** [comment]
I just wanted to follow up that I was still able to reproduce the crash in `trunk` on a self-hosted site that didn't have Jetpack connected. It's expected that .com sites won't crash due to the [previous fix](https://github.com/wordpress-mobile/WordPress-iOS/pull/17488).

Thanks to both of you for the reviews. 🙇
