### PR TITLE
Fix for confusing publish button and title when scheduling post

### LINKED ISSUE #9224: Posts: confusing publish confirmation for scheduled post
473825a3-9b0f-4d99-85d3-0e4a8b9b87b2
### Expected behavior

Confirmation dialog asking about post scheduling. 

### Actual behavior

Confirmation dialog asking about post publishing, which is confusing since I would like to schedule, not publish a post. 

### Steps to reproduce the behavior

1. Create new post
1. Change its publish options to scheduling
1. Tap on “Shedule” button.

### PR DESCRIPTION
**Pull request by Rhetorical**
Fixes #9224 

To test:
1. Create new post
2. Change its publish options to scheduling
3. Tap on “Schedule” button or attempt to exit
4. Alert action sheet will now display text and title for "schedule" or "publish" according to the `postEditorStatContext`

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostEditorState.swift [hunk 1]
```diff
@@ -51,6 +51,21 @@ public enum PostEditorAction {
         }
     }
 
+    fileprivate var publishingActionQuestionLabel: String {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostEditorState.swift]: So we only show the publish confirmation for 'async' publish actions (that is, publish actions that close the editor – see [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/38c13a0be0115f943677a2eba2c3f23a3e108de0/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L1201)). 

It's probably best if we don't request localisations for strings we're not going to use, so we should probably only return values for `.publish, .publishNow, .schedule, .submitForReview`. You could remove the extra cases, return an empty string in the `default` case (or we could make the return value optional), and perhaps add a comment explaining that the dialog is only shown for async publishing methods.

Comment (Rhetorical) [reply WordPress/Classes/ViewRelated/Post/PostEditorState.swift]: @frosty I think that the showing the for values with a default blank string sounds like a good idea. Nothing against optionals. I've separated out `.publish` and `.publishNow` in my switch cases just so they're not displaying the same message and button.

**Comment by Rhetorical** [comment]
Hi @frosty, this makes sense. I had it setup originally like this and then found the enum for the `PostEditorAction`. I'll make some changes on this and push them back up to pass the action into the `displayPublishConfirmationAlert` function like you've suggested.

**Comment by Rhetorical** [comment]
@frosty I have a question for you. When attempting to use the `action` passed to the `displayPublishConfirmationAlert` the `action` is "publish", even when saving as a draft. You can see in my screenshot that the `debugPrint` of the `postEditorContext.action` is showing "Worpdress.PostEditorAction.schedule", but the action passed to the function is "publish". This being the case do you think that it would be better to switch back to a full list for the `publishingActionQuestionLabel` and use whatever is in context for the UI? That way even if it was "update" it would show the correct title rather than a blank and we don't have to be concerned with the action being passed into the function. Let me know what you think or if you think this is another issue in general...possibly the async value being sent is incorrect?

image

**Comment by frosty** [comment]
@Rhetorical Sorry for the delay replying, I've been AFK for a couple of days. I may not have explained myself properly in my earlier comment, but I was thinking of something like this: https://gist.github.com/frosty/b96af2452626a9b5e1da83e535c471df

Not sure if I've missed anything there, but it seems to work in my testing. Let me know what you think!

**Comment by Rhetorical** [comment]
hi @frosty no problem at all on the brief delay. I checked out your gist and it's basically what I did, I've modified my branch to make more exactly the flow and wording you showed on the function. It works as it is now, but I was thinking that there was an error. When attempting to "x" out of the post/page it always prompts with a "publish now?" question. If I tap the "schedule" button it works as expected. Let me know what you think. Thanks!

**Comment by frosty** [comment]
Thanks for the update. Can you confirm, you only see "Are you sure you want to publish?" if you X out when you've edited an already-published post, right? I don't see it for drafts, which is fine. I think it's probably reasonable for already-published posts, to confirm the user wants to publish their changes.

**Comment by Rhetorical** [comment]
@frosty confirmed that if the page is already published if it's been updated when the user taps the "x" they're presented with the "You have unsaved Changes: Update Post / Discard" after updating post user is presented with the "Are you sure you want to publish? Publish / Keep Editing" option.

**Comment by Rhetorical** [comment]
Thank you for the feedback
