### PR TITLE
App extensions: fix for tracks errors

### LINKED ISSUE #9789: App Extensions: Large number of Tracks errors originating from ShareExtensionSessionManager
This is a little bit of a convoluted issue, but here is the crux of it— 

We are seeing a high number of `wpios_share_extension_error` events in the share extension. this event actually has twice as many occurrences than `wpios_share_extension_posted`on a consistent basis. Something seems fishy here. 

Looking at the individual `wpios_share_extension_error` events in Tracks we can see almost every single error originates from a single spot: [ShareExtensionSessionManager](https://github.com/wordpress-mobile/WordPress-iOS/blob/36785420d25be2f627a9d1055f6810be1d62ab8f/WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift#L316). The `error_description` from this event usually looks like this:

 ```
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorDomainKey=3, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorCodeKey=-9802, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://public-api.wordpress.com/rest/v1.1/tracks/record, NSErrorFailingURLStringKey=https://public-api.wordpress.com/rest/v1.1/tracks/record, NSErrorClientCertificateStateKey=0}
```

After chatting with @astralbodies a bit we have a hunch that:

1. The "lite" tracks client in the extensions is attempting to log an event immediately before the share extension is dismissed (e.g. `wpios_share_extension_posted`)
2. The share extension is dismissed
3. The "lite" tracks client's network call is invalidated by iOS (potentially never recorded in tracks) 
4. `ShareExtensionSessionManager`'s `urlSession(_ session: URLSession, didBecomeInvalidWithError error: Error?)` is executed and the WPiOS tracks client posts the share extension error from the "light" tracks client.

Assuming this is true ☝️, this suggests the app extension stats may not be accurate (potentially lower that what they should be).

### PR DESCRIPTION
**Pull request by bummytime**
This PR attempts to address the large amount of Tracks errors in the app extensions. See #9789 for more details. Things done:

1. In the `ShareExtensionSessionManager` we are only logging invalidated sessions that are _not_ tracks-specific.
2. `ShareModularViewController` is logging the `wpios_share_extension_posted` or `wpios_draft_extension_posted` events prior to actually firing the background NSURLSession which saves the media/post. We are doing this first because @astralbodies and I have a hunch the tracks network call is getting invalidated when fired in the save completion handler.

Fixes #9789 

## Testing

_Test both the draft and share extensions sharing an image and also just text._

1. Build and run on a device (no sim) and disconnect XCode
2. Share text/image
3. Verify the media/text is shared in a new post
4. In Tracks live view, search for `wpios_%_extension_%` and your username - verify you see the appropriate events - you should not see any unexpected `wpios_draft_extension_error` events
(this may take a few minutes to appear)

Ping me if you have any questions with testing! 😄

### CODE REVIEW

**Comment by bummytime** [comment]
Thank you @mindgraffiti !!

File: WordPress/WordPressShareExtension/ShareModularViewController.swift [hunk 1]
```diff
@@ -818,6 +818,12 @@ fileprivate extension ShareModularViewController {
     }
 
     fileprivate func prepareForPublishing() {
+        // We are preemptively logging the Tracks posted event here because if handled in a completion handler,
+        // there is a good chance iOS will invalidate that network call and the event is never received server-side.
+        // See https://github.com/wordpress-mobile/WordPress-iOS/issues/9789 for more details.
+        self.tracks.trackExtensionPosted(self.shareData.postStatus.rawValue)
+        ////
```
Comment (aerych) [inline WordPress/WordPressShareExtension/ShareModularViewController.swift]: ////
;)
