### PR TITLE
ReaderDetailViewController: Replacing IUO with if let

### LINKED ISSUE #7091: Crash: ReaderDetailViewController.swift:593
```
Crashed: com.apple.main-thread
0  WordPress                      0x100229c54 ReaderDetailViewController.configureByLine() -> () (ReaderDetailViewController.swift:593)
1  WordPress                      0x10022810c ReaderDetailViewController.configureView() -> () (ReaderDetailViewController.swift:400)
2  WordPress                      0x10022fa24 specialized ReaderDetailViewController.(setupWithPostID(NSNumber, siteID : NSNumber) -> ()).(closure #1) (ReaderDetailViewController.swift)
3  WordPress                      0x100226fec ReaderDetailViewController.(setupWithPostID(NSNumber, siteID : NSNumber) -> ()).(closure #1) (ReaderDetailViewController.swift)
4  WordPress                      0x10013bafc __55-[ReaderPostService fetchPost:forSite:success:failure:]_block_invoke (ReaderPostService.m:166)
5  libdispatch.dylib              0x1909b69e0 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x1909b69a0 _dispatch_client_callout + 16
7  libdispatch.dylib              0x1909bb5e8 _dispatch_main_queue_callback_4CF + 996
8  CoreFoundation                 0x191aad0c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9  CoreFoundation                 0x191aaacdc __CFRunLoopRun + 1572
10 CoreFoundation                 0x1919dad94 CFRunLoopRunSpecific + 424
11 GraphicsServices               0x193444074 GSEventRunModal + 100
12 UIKit                          0x197c93130 UIApplicationMain + 208
13 WordPress                      0x10005e804 main (main.m:5)
14 libdyld.dylib                  0x1909e959c start + 4
```

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're replacing an Implicitly Unwrapped Optional, main suspect of crash #7091, with an`if let` sequence.

Fixes #7091

### To test:
I'm afraid there are no specific repro steps. Please, try forcing `Post.authorForDisplay`  and `dateForDisplay.dateForDisplay` to return nil values, and verify nothing sets on fire.

Needs review: @aerych 
Thanks in advance sir!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift [hunk 1]
```diff
@@ -590,11 +590,16 @@ open class ReaderDetailViewController: UIViewController, UIViewControllerRestora
...
+        let author = post?.authorForDisplay()
+        let dateAsString = post?.dateForDisplay()?.mediumString()
+        let byline: String
+
+        if let author = author, let date = dateAsString {
+            byline = author + " · " + date
+        } else {
+            byline = author ?? dateAsString ?? String()
         }
+
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift]: If I were to nitpick, I'd ask if there was a way to do this that avoided the possibility of assigning nils to consts. (Call it a pet peeve.)  Something like this maybe?  
```
var byline = ""
        if let author = post?.authorForDisplay() {
            byline = author
        }
        if let dateAsString = post?.dateForDisplay()?.mediumString() {
            if byline.characters.count > 0 {
                byline += " . "
            }
            byline += dateAsString
        }
```

But what you have looks solid.

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift]: (Should we change that one anyways?, for consistency's sake?)

Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift]: Let's just :shipit: :)  
Sorry for the extra fuss

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift]: No fuzz at all sir!! thanks for the review Eric!!!
