### PR TITLE
Fix an issue with post content structure not loading in some scenarios

### LINKED ISSUE #23341: Jetpack App - Blog Post Word Count
### Expected behavior

The user reported that they used to see the word count feature immediately when clicking on three dots in a post editor. 

Screenshot 2024-06-11 at 4 34 36 PM

### 
Actual behavior

Clicking three dots does not immediately show the feature from the drop-down: 

Screenshot 2024-06-11 at 4 35 54 PM

When I tested this, the feature only showed up after I tried to add new blocks in the editor. 

### Steps to reproduce the behavior

1. Go to Jetpack app using iPhone with latest iOS version.
2. Select a site.
3. Go to Posts and select a post to edit.
4. Click the three dots at the top right of the editor. The feature will not appear.
5. Add new blocks in the editor.
6. Click the three dots again at the top right and the feature will appear. 

##### Tested on iPhone 14 Pro Max, iOS 17.5.1, Jetpack iOS 25.0

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/23341

The "More" menu now loads the actions that require the latest post content asynchronously to ensure it is up-to-date. These actions include: "Save Draft" and the "Content Structure" footer.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/cf3042b2-2144-45da-b5d1-7b26cc345b38

## To test:

**Scenario 1**

Follow the steps from https://github.com/wordpress-mobile/WordPress-iOS/issues/23341.

**Scenario 2**

- Open an existing draft
- Make an edit and _quickly_ tap "More"
- ✅ Verify that the "Save Draft" button is always enabled after an edit (might be worth using a longer post)

## Regression Notes
1. Potential unintended areas of impact: Post Editor / More Menu
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/290">25.1 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift [hunk 1]
```diff
@@ -497,6 +498,7 @@ class GutenbergViewController: UIViewController, PostEditor, FeaturedImageDelega
     }
 
     func requestHTML(for reason: RequestHTMLReason) {
+        wpAssert(requestHTMLReason == nil, "HTML request is in progress")
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: I keep hitting this assertion in the second scenario with a long post (5000 words). Two requests get called in a row before the first one completes. One for autoSave and another for custom callback. 

If I test the same case without an assertion, then `requestHTML` gets called twice, but `gutenbergDidProvideHTML` gets only called once. If it finished with reason `autosave`, then the callback() never gets called, and the more menu gets stuck in `loading..`  state.

image

Comment (kean) [reply WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: Good catch. I added a bit of Combine to resolve it. I'm not sure it's completely sound, but it should work for this use case.

Comment (staskus) [reply WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: Yes, it does do the trick.

**Review by staskus — APPROVED** [review]
