### PR TITLE
Refactor the fix for comments crash

### LINKED ISSUE #13950: Crash when rendering comments
When navigating to the list of comments for an internal p2 post, the app will crash if there are comments.

### Expected behavior
It should be possible to navigate to the list of comments for a given post

### Actual behaviour
The app crashes when rendering the list of comments.

### Steps to reproduce the behavior
1. Navigate to the Notifications tab
2. Tap a notification (for example, a notification about a new post)
3. Tap the "comments" icon at the bottom right
4. The app navigates to the list of comments, and will crash, apparently, when it is about to render the list of comments

The crash can be reproduced when initiating the navigation from the Reader.

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 11 Pro Max, iOS 13.4.1, WPiOS 14.7.0.0

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #13950

After talking to @aerych we can simplify the fix for the comments section crash while keeping Reader unaware of `BlogService`.

### To test

1. Navigate to the Notifications tab
2. Tap a notification (for example, a notification about a new post)
3. Tap the "comments" icon at the bottom right
4. The app navigates to the list of comments, and should not crash

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift [hunk 1]
```diff
@@ -205,17 +202,17 @@ class ReaderCommentCell: UITableViewCell {
...
+        guard let comment = comment, let attributedString = attributedString else {
+            return
+        }
+
+        if let blog = comment.blog {
             textView.mediaHost = MediaHost(with: blog, failure: { error in
                 // We'll log the error, so we know it's there, but we won't halt execution.
                 CrashLogging.logError(error)
             })
         }
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift:214]: Maybe add :   
```suggestion
        }  else if let post = comment.post as? ReaderPost, post.isPrivate() {
            textView.mediaHost = MediaHost(with: post, failure: { error in
                // We'll log the error, so we know it's there, but we won't halt execution.
                CrashLogging.logError(error)
            })
        }
```

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift [hunk 2]
```diff
@@ -252,6 +243,22 @@ class ReaderCommentCell: UITableViewCell {
         textView.updateLayoutForAttachments()
     }
 
+    /// Returns the media host for the current comment
+    private func mediaHost() -> MediaHost {
+        if let blog = comment?.blog {
+            textView.mediaHost = MediaHost(with: blog, failure: { error in
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift:249]:
```suggestion
            return MediaHost(with: blog, failure: { error in
```

File: WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift [hunk 3]
```diff
@@ -252,6 +243,22 @@ class ReaderCommentCell: UITableViewCell {
...
+                // We'll log the error, so we know it's there, but we won't halt execution.
+                CrashLogging.logError(error)
+            })
+        } else if let post = comment?.post as? ReaderPost, post.isPrivate() {
+            textView.mediaHost = MediaHost(with: post, failure: { error in
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift:254]:
```suggestion
            return MediaHost(with: post, failure: { error in
```
