### PR TITLE
Pages List performance improvements

### LINKED ISSUE #21813: Field Guide pages can't be loaded
### Expected behavior
The app can displays pages list in Field Guide.

### Actual behavior
The pages list keeps on loading.

### Steps to reproduce the behavior
1. Sign in using A8C account.
2. Go to site picker and choose Field Guide.
3. Go to Pages screen -> Published.
4. Wait to see if the published pages can be loaded. I've waited on this screen for 5 minutes, and it's still loading.

If the app is launched from Xcode, go to the Debug navigator and you can see the device/simulator's CPU usage is rocketed up to 100%.

Using FG might be an extreme case, because there are 5600+ pages in FG. However, we should allow Automatticians to use the app to view/edit FG pages. So I think it's best that we address this issue here.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Jetpack 23.4.

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #21813. Also, in general, this PR makes it's possible to load a site with a large number of pages (300+).

## Issue

Currently Pages List performs very poorly on a site with a large number of pages. A pretty extreme case is #21813. The app may become unresponsive in 5 minutes or so, when about 6000 pages are loaded.

If you have a test site with 300 pages, you can open that site in the app and go to Pages screen and the app will become unresponsive very quickly.

If you don't have a test site with that many pages, you can use FG as the test site, with a little bit of code change: adding another "and" condition to [this if statement](https://github.com/wordpress-mobile/WordPress-iOS/blob/23.7.0.0/WordPress/Classes/Services/PostService.m#L135): `&& loadedPosts.count < 500`. The number 500 is the max of pages you want to the app to fetch. You can tweak this number to test the Pages List's performance against certain number of pages.

## Changes

There are a few issues involved:
1. [Pages are loaded in memory](https://github.com/wordpress-mobile/WordPress-iOS/blob/23.7.0.0/WordPress/Classes/Services/PostService.m#L135) and populated into UI after all pages are fetched from API. This gives a false sense of Pages List stuck at "Fetching pages...".
2. Pages are saved using the main context. Meaning all the Core Data operations, inserting, updating, deleting, happen on the main thread.
3. Pages are displayed in hierarchical order. But the current algorithm doesn't perform well. See https://github.com/wordpress-mobile/WordPress-iOS/pull/22056.

The first two issues are addressed by [the `PostRepository.fetchAllPages` function](https://github.com/wordpress-mobile/WordPress-iOS/blob/23.7.0.0/WordPress/Classes/Services/PostRepository.swift#L393). And the last issues is addressed by the linked PR #22056. This PR basically uses those new implementations to swap out the current problematic ones.

That means, this PR should not bring any UI changes to the app, it only addresses performance issues.

> [!NOTE]
> It'd be much easier to review this PR commit by commit.

## Further considerations

In other discussions, the general consensus is it's bad to load all pages automatically, instead of page by page as user scrolls through the list (like Posts List). @kean mentioned we could change Pages List to match WP.com, where the pages are displayed in a hierarchical order if there are certain number in total (say 600), but they are displayed page by page (like Posts List) if the total amount exceed this threshold.

I agree with that idea, but did not implement it in this PR, because I don't want this PR to get too large. I'm not sure if I'd have time to implement it though, because I have other project lined up (dropping Alamofire from WordPressKit).

## Test Instructions

Verify #21813 is fixed. Use FG to test Pages List performance.

This PR also adds a cancellation mechanism to the Pages List, where the Pages List stops loading more pages when user taps the "Back" button. You can verify this behaviour by using Xcode's "Network Activity Report" in the Debug panel: You should see periodic spikes in the Network Activity when the app are on FG's pages list and see no more spikes when exits the pages list screen.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Test using FG.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

File: WordPress/Classes/Services/PostRepository.swift [hunk 1]
```diff
@@ -390,7 +390,7 @@ extension PostRepository {
     ///   - statuses: Only fetch pages whose status is included in the given statues.
     ///   - blogID: Object ID of the site.
     /// - Returns: A `Task` instance representing the fetching. The fetch pages API requests will stop if the task is cancelled.
-    func fetchAllPages(statuses: [BasePost.Status], in blogID: TaggedManagedObjectID<Blog>) -> Task<[TaggedManagedObjectID<Page>], Swift.Error> {
+    func fetchAllPages(statuses: [BasePost.Status], authorUserID: NSNumber? = nil, in blogID: TaggedManagedObjectID<Blog>) -> Task<[TaggedManagedObjectID<Page>], Swift.Error> {
```
Comment (mokagio) [inline WordPress/Classes/Services/PostRepository.swift:393]: Nitpick: The Swift API Guidelines [recommend to locate parameters with default values at the end of the list](https://swift.org/documentation/api-design-guidelines/#parameter-with-defaults-towards-the-end):

> **Prefer to locate parameters with defaults toward the end of the parameter list.** Parameters without defaults are usually more essential to the semantics of a method, and provide a stable initial pattern of use where methods are invoked.

File: WordPress/Classes/Utility/PageTree.swift [hunk 2]
```diff
@@ -2,28 +2,35 @@ final class PageTree {
 
     // A node in a tree, which of course is also a tree itself.
     private class TreeNode {
-        let page: Page
+        struct PageData {
+            var postID: NSNumber?
+            var parentID: NSNumber?
+        }
```
Comment (mokagio) [inline WordPress/Classes/Utility/PageTree.swift:8]: Always like a container type for information like this one. 

Do the properties need to be mutable?

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 3]
```diff
@@ -475,85 +475,80 @@ class AbstractPostListViewController: UIViewController,
         return .any
     }
 
-    func syncHelper(_ syncHelper: WPContentSyncHelper, syncContentWithUserInteraction userInteraction: Bool, success: ((_ hasMore: Bool) -> ())?, failure: ((_ error: NSError) -> ())?) {
+    @MainActor
+    func syncPosts(isFirstPage: Bool) async throws -> ([AbstractPost], Bool) {
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: From the function signature, I couldn't understand what that `Bool` in the returned tuple represents. I only figured it out by looking at the usage, where it's assigned to `hasMore`.

Have you considered defining a `struct` to model that information?

File: WordPress/Classes/ViewRelated/Pages/PageListViewController.swift [hunk 4]
```diff
@@ -210,17 +233,55 @@ final class PageListViewController: AbstractPostListViewController, UIViewContro
...
+            }
         } else {
             self.pages = pages
         }
+
+        tableView.reloadData()
+        refreshResults()
+    }
+
+    /// Build page hierachy in background, which should not take long (less than 2 seconds for 6000+ pages).
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Pages/PageListViewController.swift:264]: _Show off_ 😄

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 5]
```diff
@@ -475,85 +475,80 @@ class AbstractPostListViewController: UIViewController,
...
-            for: blog,
-            success: { [weak self] posts in
-                guard let self, let posts else {
-                    return
-                }
+        Task { @MainActor [weak self] in
+            do {
+                guard let (posts, hasMore) = try await self?.syncPosts(isFirstPage: false) else { return }
+
+                guard let self else { return }
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: Would it make sense to swap these? The end result would be the same, return if self is not available, but I feel it's odd to access `self?` and check `let self` afterwards. 🤷‍♂️ 

```suggestion
                guard let self else { return }

                let (posts, hasMore) = try await self.syncPosts(isFirstPage: false)
```

I didn't try this code, maybe I'm missing something and in fact it's necessary to do `guard` twice.

File: WordPress/WordPressTest/PagesListTests.swift [hunk 6]
```diff
@@ -72,9 +72,7 @@ class PagesListTests: CoreDataTestCase {
         NSLog("\(pages.count) pages used in \(#function)")
 
         measure {
-            let pageTree = PageTree()
-            pageTree.add(pages)
-            let list = pageTree.hierarchyList()
+            let list = (try? PageTree.hierarchyList(of: pages)) ?? []
```
Comment (mokagio) [inline WordPress/WordPressTest/PagesListTests.swift:75]: I was going to suggest the following, which I feel would make the point at which the test might have failed.

```suggestion
            let list = try XCTUnwrap(try? PageTree.hierarchyList(of: pages)))
```

But I checked [the docs](https://developer.apple.com/documentation/xctest/xctestcase/3194264-measure) and I guess it's not possible to `throw` from the block given to `measure` 😞

**Review by mokagio — COMMENTED** [review]
Leaving some notes before moving on with trying this on device.

**Review by mokagio — APPROVED** [review]
Worked great on my iPhone 15 Pro.

I took videos for comparison, then remembered the site to test this edge case is a private one 🥷 

Anyways, on the same device, the 23.7 beta load two pages in the list then nothing else happens in the UI. In this build, the rest of the pages appear after a second or so.

Great work 👏

File: WordPress/Classes/Services/PostRepository.swift (hunk 1 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/PostRepository.swift:393]: Good catch. I used default parameter value quite freely in a few similar functions in this class. I want to keep the blog parameter as the last parameter (or the first), and rest of the parameters (which act as post/pages filters) don't really have an sensible order. But these functions are added one by one across many PRs, it's probably worth looking into these function holistically later.

File: WordPress/Classes/Utility/PageTree.swift (hunk 2 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/PageTree.swift:8]: Maybe no? I used `var` out of habit without any extra thoughts. However, it's used as a constant though: `let pageData: PageData`.

File: WordPress/Classes/ViewRelated/Pages/PageListViewController.swift (hunk 4 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Pages/PageListViewController.swift:264]: 😅 Taking 2 seconds to sort 6000 items is not really fast though...It's much faster than what we have at the moment, but still not fast enough. I'm being lazy here by putting them into a background thread. The comment here is mainly pointing out, the sorting isn't fast enough to take place in the main thread, but is fast enough to put in the background thread without worrying it keep going forever.

File: WordPress/WordPressTest/PagesListTests.swift (hunk 6 above)
Comment (crazytonyli) [reply WordPress/WordPressTest/PagesListTests.swift:75]: Yep, that's why I added an assertion below, to make sure we are measuring success cases, not failure cases.

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: Addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/22070/commits/5981dcff18b7e203f61deb654cfb57ac2f443e82. I used a named tuple instead of a struct.

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift (hunk 5 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: This `guard let self` is similar to how we do the same check in a completion block. In reality, `self` should never be nil when calling `syncPosts`, but could be nil if user has exit the screen before the `sycnPosts` returns. I have added a comment in https://github.com/wordpress-mobile/WordPress-iOS/pull/22070/commits/19307ccad85c448547c6a84987894cdaecfd78fb

File: WordPress/Classes/Services/PostRepository.swift (hunk 1 above)
Comment (mokagio) [reply WordPress/Classes/Services/PostRepository.swift:393]: Sounds good

**Comment by mokagio** [comment]
Enabled auto-merge so this can land in `trunk` ASAP and we can move forward with the 23.8 code freeze.
