### PR TITLE
Fix split view support on large iPhones

### LINKED ISSUE #21579: Split View broken on Plus/Max iPhones
The issue appeared after the recent dashboard changes introduced in https://github.com/wordpress-mobile/WordPress-iOS/issues/21492. These changes have not shipped yet.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/9e51e313-4451-4da2-ae8a-7190157f0eb2

Before the changes the behavior was the following:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/edb0cea6-b9da-4c08-b906-cfab643a5a04

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/21579

Removing Split View from My Site on iPhone. Reasoning in https://github.com/wordpress-mobile/WordPress-iOS/issues/21579. Blessed by Chris.

### Jetpack

**Basics**

- Open the app on iPhone Plus or Pro Max
- Rotate the My Site tab to the landscape mode
- Verify that it no longer shows the split view
- Verify that the details page navigations work and take full advantage of the screen width
- Verify that the navigation under the "More" section also work
- Verify that you can open all of the details screens from the dashboard

**More Menu**

- Open More menu
- Verify that the menu use [readable content guide](https://developer.apple.com/documentation/uikit/uiview/1622644-readablecontentguide) so that they are nice and readable
- Verify that you can open all of the details screens from the dashboard

**Launch in Landscape**

- Open the app already in landscape
- Verify that on iPhone, the Home page appears (not the More menu)
- Open the More menu and verify that it doesn't display the Home button

**Readable Content Guide**

- Verify that the dashboard cards use [readable content guide](https://developer.apple.com/documentation/uikit/uiview/1622644-readablecontentguide) so that they are nice and readable

Screenshot 2023-09-15 at 4 52 48 PM

P.S. The header position is probably not ideal, but I wanted to limit the scope of the changes because the soft freeze is coming.

<hr/>

### WordPress

**Basics**

- Open the app
- Verify that the menu use [readable content guide](https://developer.apple.com/documentation/uikit/uiview/1622644-readablecontentguide) so that they are nice and readable
- Verify that you can open all of the details screens from the dashboard
- Verify that the cells have disclosure indicators in both landscape and portrait
- Verify that when you launch the app in landscape mode it doesn't restore previous selection

## Regression Notes
1. Potential unintended areas of impact: My Site
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift [hunk 1]
```diff
@@ -131,7 +131,7 @@ extension DashboardQuickActionsCardCell: BlogDetailsPresentationDelegate {
     }
 
     func presentBlogDetailsViewController(_ viewController: UIViewController) {
-        self.parentViewController?.showDetailViewController(viewController, sender: nil)
+        self.blogDetailsViewController?.show(viewController, sender: nil)
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift:134]: This cell only exists on iPhone, so blog details can push the screen by itself.

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift [hunk 2]
```diff
@@ -65,6 +71,7 @@ class MySitesCoordinator: NSObject {
         navigationController.tabBarItem.accessibilityLabel = NSLocalizedString("My Site", comment: "The accessibility value of the my site tab.")
         navigationController.tabBarItem.accessibilityIdentifier = "mySitesTabButton"
         navigationController.tabBarItem.title = NSLocalizedString("My Site", comment: "The accessibility value of the my site tab.")
+        navigationController.extendedLayoutIncludesOpaqueBars = true
```
Comment (kean) [inline WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift:78]: Without it nothing works 🤷

File: WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m [hunk 3]
```diff
@@ -409,7 +411,7 @@ - (void)viewWillAppear:(BOOL)animated
 
     [self observeWillEnterForegroundNotification];
 
-    if (self.splitViewControllerIsHorizontallyCompact) {
+    if (!self.splitViewControllerIsHorizontallyCompact) {
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m]: Doing this would mean that the selected index path won't be restored on iPad. Is this the intended behavior? I saw you added an isSplitViewDisplayed helper - maybe you can use that instead?
```suggestion
    if (self.isSplitViewDisplayed) {
```

**Review by momo-ozawa — COMMENTED** [review]
Thanks! Works as described. 

I noticed that on WPiOS, after you access the Stats screen, the static screen is displayed in portrait and the dashboard is stuck in portrait orientation thereafter. Not sure if this is due to testing via a simulator. In any case, I don't think this is a blocking issue.

File: WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m (hunk 3 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m]: Good catch, thanks! 🙇

**Review by momo-ozawa — APPROVED** [review]

**Comment by kean** [comment]
> I noticed that on WPiOS, after you access the Stats screen, the static screen is displayed in portrait 

This page is gone in phase four migration, so I think we should be good.

**Comment by momo-ozawa** [comment]
@mokagio FYI. Also, https://github.com/wordpress-mobile/WordPress-iOS/pull/21602 cherry-picks changes from this PR into trunk to unblock development
