### PR TITLE
Posts: Better calculation for action bar buttons count.

### LINKED ISSUE #5915: Post List: Cards show all buttons after rotation on iPhone
On an iPhone, post cards should show three button for a compact width (portrait) and four buttons for a regular width (landscape).   However, after rotating from portrait to landscape and back cards continue to show four buttons. 

To reproduce: 
View the post list for a blog on an iPhone. 
Rotate to landscape orientation. 
Rotate back to portrait orientation

### Expected
img_4792

### Actual
img_4791

cc @kurzee

### LINKED ISSUE #5916: Reader: Load More Posts cell shows a white background on the iPad
Example: 
img_0007

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #5915 

To test:

1. Open Blog Posts on iPad.
2. Verify four action buttons are visible in Portrait and Landscape.
3. Transition to multitasking, verify only three action buttons are visible.
4. Transition from multitasking to full-screen, verify all four buttons are visible again.

To test:

1. Open Blog Posts on iPhone.
2. Verify three action buttons are visible in portrait orientation.
3. Verify four action buttons are visible in landscape orientation.

Needs review: @frosty

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostCardActionBar.m [hunk 1]
```diff
@@ -6,7 +6,8 @@
 #import "WordPress-Swift.h"
 
 static NSInteger ActionBarMoreButtonIndex = 999;
-static CGFloat ActionBarMinButtonWidth = 90.0;
+static NSInteger const ActionBarMaxNumButtonsHorizontallyCompact = 3;
+static NSInteger const ActionBarMaxNumButtonsHorizontallyRegular = 6;
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostCardActionBar.m]: How come this is 6? Do we ever have more than 4 buttons?

**Comment by frosty** [comment]
Other than one small comment (more for curiosity than anything), this looks good!

:shipit:

**Comment by kurzee** [comment]
@frosty thanks for the review! I changed the max to 4, since that's how many we actually have. The thought previously was to have 6 as an ideal maximum, if we add more.
