### PR TITLE
[Gutenberg] Add new block type badge to block inserter list

### LINKED ISSUE #30627: Add the "New" Block Badge
## What problem does this address?
The mobile editor is a powerful tool for creating content, but many users fail to understand the extent of what they can do with it. 

## What is your proposed solution?
We will display a "new" badge on blocks that were recently added to the editor to help users discover different blocks. 

Mobile new block badge

### PR DESCRIPTION
**Pull request by dcalhoun**
* **Gutenberg:** https://github.com/WordPress/gutenberg/pull/33119
* **Gutenberg Mobile:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3720
* **WPiOS:** Self
* **WPAndroid:** https://github.com/wordpress-mobile/WordPress-Android/pull/15038

Fixes WordPress/gutenberg#30627. Add badge to showcase new block types. 

To test: See https://github.com/WordPress/gutenberg/pull/33119. 

## Regression Notes
1. Potential unintended areas of impact
  Modifications to the Gutenberg view and settings could cause disruption initializing the editor. 
2. What I did to test those areas of impact (or what existing automated tests I relied on)
  Verified the editor loaded without issue and successfully modified/saved post content. 
3. What automated tests I added (or what prevented me from doing so)
  None, as this feature is experimental at this time and any tests would be implemented in the Gutenberg editor repo.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift [hunk 1]
```diff
@@ -941,6 +941,19 @@ extension GutenbergViewController: GutenbergBridgeDelegate {
     func gutenbergDidRequestPreview() {
         displayPreview()
     }
+
+    func gutenbergDidRequestBlockTypeImpressions(_ newBlockTypes: [String]) -> [String: Int] {
+        let newImpressions = newBlockTypes.reduce(into: [:], { $0[$1] = 3 })
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: nitpick: the shorthand arguments `$0`, `$1`, etc are best avoided IMO because they reduce readability. I don't think we have any guidelines around this though.

Comment (guarani) [reply WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: I understand this line to say, give all "new blocks" a default count of 3 "impressions". If so, it might be good to bring the `3` out into a variable such as `defaultImpressionCount`.

File: WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift [hunk 2]
```diff
@@ -941,6 +941,19 @@ extension GutenbergViewController: GutenbergBridgeDelegate {
...
+        // Merge current and new impressions favoring the current
+        gutenbergSettings.blockTypeImpressions.merge(newImpressions) { (current, _) in current }
+        return gutenbergSettings.blockTypeImpressions
+    }
+
+    func gutenbergDidRequestSetBlockTypeImpressionCount(_ name: String, count: Int) -> Void {
+        let newImpressions = [name: count]
+        // Merge current and new impressions favoring the new
+        gutenbergSettings.blockTypeImpressions.merge(newImpressions) { (_, new) in new }
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: Nice work with the Swift here.

**Review by guarani — COMMENTED** [review]
👋 Great work here as usual @dcalhoun! I left some minor comments but will hold off approving since the Gutenberg side is still under review.

File: WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift (hunk 1 above)
Comment (dcalhoun) [reply WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift]: Avoiding the cryptic shorthand and unlabeled number of `3` makes total sense. However, this logic has now been moved into the JavaScript source, so the point is moot. Thank you for calling this out, though.

**Review by guarani — APPROVED** [review]
As you mentioned above most of the logic that was here has moved to JavaScript, but what's left here looks great. 

I tested iOS and left an approval on the other PRs as well: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3720#pullrequestreview-720671594
