### PR TITLE
Fix an issue with posts shown embedded in the notifications popover

### LINKED ISSUE #23883: iPad: Open posts in main navigation area when accessing them from the Notifications popover
### Expected behavior

- Opens in the main navigation area (tech note: user Reader navigation paths)

### Actual behavior

- Opens in the popover itself (not useful)

### Steps to reproduce the behavior

https://github.com/user-attachments/assets/d7481abc-75be-4991-afbf-a3e8b8efe66e

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/23883. New behavior on iPad:

https://github.com/user-attachments/assets/33da6442-d02d-4c33-ab4a-f58ea28c045b

Reader will now also no longer lose the current navigation state when opening a deep link with a post.

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/303">25.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift [hunk 1]
```diff
@@ -777,11 +777,17 @@ extension NotificationsViewController {
         if let postID = note.metaPostID,
             let siteID = note.metaSiteID,
             note.kind == .matcher || note.kind == .newPost {
-            let readerViewController = ReaderDetailViewController.controllerWithPostID(postID, siteID: siteID)
-            readerViewController.navigationItem.largeTitleDisplayMode = .never
-            readerViewController.hidesBottomBarWhenPushed = true
-            readerViewController.coordinator?.notificationID = note.notificationId
-            displayViewController(readerViewController)
+
+            if isSidebarModeEnabled && splitViewController == nil {
```
Comment (crazytonyli) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift:781]: This seems to be a roundabout way to check if the notifications view controller is displayed in a popover.

Maybe it's more intuitive to check whether `self.modalPresentationStyle` or `self.navigationController.modalPresentationStyle` is `popover`?

Comment (kean) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift:781]: Yes, but after a quick search I couldn't find a reliable way to check if something is displayed in a popover. I guess the `modalPresentationStyle` check could work in this case. I'm a bit reluctant to use it because it's only not a completely reliable indicator as on iPhone `.popover` is displayed in a sheet by default (obviously not the case here for this screen).

Btw, I'll try to remove `isSidebarModeEnabled` as well during these couple of weeks. It was added there as a temporary measure during the iPad rework and is a type of a feature flag.

**Review by crazytonyli — APPROVED** [review]
