### PR TITLE
WebKitViewController nav bar buttons color for accessibility bold text

### LINKED ISSUE #9396: The "X" and "Reload" icons on the app's internal browser aren't visible if Bold Text is enabled
A user reported in 280611-h that when accessing a page within the app's internal browser, both the "X" and "Reload" icons on the top left and right corner, respectively, are there, working, but they are not visible.

### Expected behavior

I expected the buttons to be darker or bolder, but visible.

screen shot 2018-05-17 at 5 02 23 pm

### Steps to reproduce: 

On the iPhone: 

- Go to Settings > General > Accessibility > Bold Text and turn it on. 
screen shot 2018-05-17 at 5 00 15 pm

- It will prompt to restart the phone, go ahead and tap on "Continue" to restart the phone.
- Reopen the WordPress app, go to the Reader, click on any result and then click on a link to open the page in the app's internal browser. 
- Alternatively, go to My Sites > "Pick any site" > External > and tap on "View Site" to open the site in the app's internal browser.

Result: 

screen shot 2018-05-17 at 4 59 23 pm

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #9396 

This PR fixes the UIBarButtonItem tint color on the `WebKitViewController` when `UIAccessibilityBoldText` is enabled.

img_2979

**Notes**:
- The issue is a iOS 11 bug where the `UIBarButtonItem.appearance().tintColor` conflict with the tint color of the item instance. This was fixed by re-setting the bar tint color to override the appearance setting.
- Tool bar button items also had this problem, but the color was changing to a darker one.
- There was a thread error in this class. This also was addressed.
- I took the opportunity for a small refactor to organize the code and remove a couple of (harmless) optionals and `!`s.

@koke could you please take a look? :)

To test:
 - Go to the system Settings app > General > Accessibility > Bold Text and turn it on. 
screen shot 2018-05-17 at 5 00 15 pm
- Reopen the WordPress app, go to the Reader, click on any result and then click on a link to open the page in the app's internal browser. 
- Alternatively, go to My Sites > "Pick any site" > External > and tap on "View Site" to open the site in the app's internal browser.
- Check that the navigation bar buttons and the toolbar buttons are styled as expected.

### CODE REVIEW

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 1]
```diff
@@ -104,92 +124,128 @@ class WebKitViewController: UIViewController {
         if addsWPComReferrer {
             request.setValue("https://wordpress.com", forHTTPHeaderField: "Referer")
         }
-        webView.load(request)
+        DispatchQueue.main.async { [weak self] in
+            self?.webView.load(request)
```
Comment (koke) [inline WordPress/Classes/Utility/WebKitViewController.swift]: I'm curious, when was this being called from a secondary thread?

**Comment by koke** [comment]
I noticed on Site > Sharing, the close button is missing when bold text is enabled. That one (`SharingAuthorizationWebViewController`) is still based on `WPWebViewController`

img_0110

File: WordPress/Classes/Utility/WebKitViewController.swift (hunk 1 above)
Comment (etoledom) [reply WordPress/Classes/Utility/WebKitViewController.swift]: It was happening every time when opening the `View Site` web view.

screen shot 2018-06-07 at 12 52 46 pm

It was called from `loadWebViewRequest` callback:
``` swift
authenticator.request(url: url, cookieJar: webView.configuration.websiteDataStore.httpCookieStore) { [weak self] (request) in
    self?.load(request: request)
}
```
That actually could be a better place to change thread.

**Comment by etoledom** [comment]
@koke As we agreed by PM, I moved the switch to the main thread to the CookieJar implementation.
I tested it and seems to work good too 👍

**Comment by koke** [comment]
👍 thanks, 🚢 :shipit: 🚢
