### PR TITLE
Fixing Aztec crash on Xcode9

### LINKED ISSUE #7374: Aztec editor crashing on iOS 11 beta
Aztec editor is crashing on iOS 11 beta immediately when presented. Crash is happening within `AztecPostViewController.swift` in method `editorContentWasUpdated` because `postEditorStateContext` is nil.

screen shot 2017-06-14 at 12 02 39 pm

To be clear, this seems to be an entirely different problem than #7373.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR fixes a crash "at launch" in Aztec. Please, note that this PR must be merged after #7764 is, since the CocoaLumberjack upgrade is included here (since it's required for Xcode 9).

Ref.: [lazy var's new behavior](https://bugs.swift.org/browse/SR-5172).

Fixes #7374

### To test:
- Build (this branch) with Xcode 9
- Launch Aztec
- Verify it doesn't crash anymore! 

Needs review: @nheagy 
Thanks in advance Nate!

cc @diegoreymendez

### CODE REVIEW

**Comment by jleandroperez** [comment]
CocoaLumberjack change is already in develop. Ready for review @nheagy!

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 1]
```diff
@@ -358,22 +358,8 @@ class AztecPostViewController: UIViewController, PostEditor {
...
-        }
-
-
-        // Self-hosted non-Jetpack blogs have no capabilities, so we'll default
-        // to showing Publish Now instead of Submit for Review.
-        let userCanPublish = self.post.blog.capabilities != nil ? self.post.blog.isPublishingPostsAllowed() : true
-        let context = PostEditorStateContext(originalPostStatus: originalPostStatus, userCanPublish: userCanPublish, publishDate: self.post.dateCreated, delegate: self)
-
-        return context
+    fileprivate lazy var postEditorStateContext: PostEditorStateContext = { [unowned self] in
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: I don't think we need the `[unowned self]` here? (https://twitter.com/jckarter/status/704100315587477504)

Comment (koke) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: But you're not immediately applying the closure (even if the syntax makes it look that way). Since it's a `lazy` variable, it will only initialize when it's first used.

Comment (jleandroperez) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: (What Koke said) =D. Thanks Nate!

Comment (AliSoftware) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Does https://twitter.com/jckarter/status/704100315587477504 help?

Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: @jleandroperez - I tested a few days ago and @nheagy 's comment is right.  It seems like these lazy-var initialization blocks are smart enough not to retain self at all (probably by having `[unowned self]` by default).

I basically set up a playground and tried using the lazy var, and never using it, and in both cases the object owning the variable would be released before execution ended (`deinit` was called).
