### PR TITLE
Dashboard Cards: Deduplicate activities before rendering the Activity Log card

### LINKED ISSUE #20729: App crash when logging into a particular site
### Expected behavior

The app shouldn't crash after logging in.

### Actual behavior

On a particular test site, the app crashes after logging in when it should load the dashboard.

### Steps to reproduce the behavior
1. Log into an account associated with the affected site
2. Tap through the site list after logging in
3. Notice the app crash

I couldn't reproduce on the current 22.4 beta.

### Additional info

```
Thread 1: "Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(\n    WordPressKit.Activity(activityID: \"AYXkaEbEvbhaz0TQggoq\", summary: \"Theme activated\", text: \"Switched Byrne to Twenty Fifteen\", name: \"theme__switched\", type: \"Update\", gridicon: \"themes\", status: \"\", rewindID: Optional(\"1674574310.9114\"), published: 2023-01-24 15:31:50 +0000, actor: Optional(WordPressKit.ActivityActor(displayName: \"Server\", type: \"Application\", wpcomUserID: \"\", avatarURL: \"\", role: \"\", $__lazy_storage_$_isJetpack: nil)), object: Optional(WordPressKit.ActivityObject(name: \"Twenty Fifteen\", type: \"Theme\", attributes: [\"id\": https://wordpress.org/themes/twentyfifteen/, \"object_slug\": pub/twentyfifteen, \"object_version\": 3.2-wpcom])), target: Optional(WordPressKit.ActivityObject(name: \"Server\", type: \"Application\", attributes: [:])), items: nil, content: Optional([\"text\": \"Switched Byrne to Twenty Fifteen\", \"ranges\": [[\"version\": \"3.2-wpcom\", \"type\": \"theme\", \"id\": \"11\", \"slug\": \"twentyfifteen\", \"site_slug\": \"allantr"
```

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes  #20729

## Description
- Adds a check to deduplicate activities before rendering the Activity Log card

## Background
- Crash caused by diffable data source not being able to differentiate items - duplicate activity items were being returned in the `/dashboard/cards-data` endpoint as well as the `sites/{site-id}/activity` endpoint
- Mobile investigation: p1684971925814679-slack-C0180B5PRJ4
- Jetpack crew investigation: p1685611256986159-slack-C011BCGRMBR

## How to test
1. Make sure the tests in `DashboardActivityLogViewModelTests` pass

## Regression Notes
1. Potential unintended areas of impact
Activity Log dashboard card

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Added unit tests

3. What automated tests I added (or what prevented me from doing so)
`DashboardActivityLogViewModelTests`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
~~For anyone reviewing this, see p1685719291943229/1684971925.814679-slack-C0180B5PRJ4~~

File: WordPress/Classes/Extensions/Array.swift [hunk 1]
```diff
@@ -18,6 +18,11 @@ extension Array where Element: Hashable {
     public var unique: [Element] {
         return Array(Set(self))
     }
+
+    public func deduplicated() -> [Element] {
+        var seen = Set<Element>()
+        return filter { seen.insert($0).inserted }
```
Comment (kean) [inline WordPress/Classes/Extensions/Array.swift:24]: Nice use of `inserted`. It never occurred to me it could be used this way.

**Review by guarani — APPROVED** [review]
Code looks good! [I don't have access to an affected site anymore](p1685714810004419/1684971925.814679-slack-C0180B5PRJ4), so I just regression tested this on a site with no duplicate activities and ensured that Menu > Activity Log loads correctly.

**Review by kean — APPROVED** [review]

File: WordPress/Classes/Extensions/Array.swift (hunk 1 above)
Comment (guarani) [reply WordPress/Classes/Extensions/Array.swift:24]: Same! I had to Google it to be honest, didn't know it existed 😄 I'd only seen Set used to de-dupe but it doesn't preserve the order.

Comment (kean) [reply WordPress/Classes/Extensions/Array.swift:24]: Yeah, I thought it was an extension, so my initial reaction was to search for it in the codebase 😃

**Comment by momo-ozawa** [comment]
FYI @mokagio 🙇‍♀️
