### PR TITLE
Fix off-by-one error in post likes

### LINKED ISSUE #23911: Off by one in likes
### Expected behavior
When liking a post and it has 5 likes, I should see 5 likes and 5 avatars.

### Actual behavior
I sometimes see 6 avatars and 5 likes, and sometimes see -1 likes.

### Steps to reproduce the behavior
When browsing p2s, just like - it doesn't always happen but it happens. Choose posts with 1-5 likes.

The -1 like has a consistent path to reproduce:
- Like a post with 0 likes from the list of posts
- Click the individual post to read it, you'll see no likes present
- Unlike and like
- -1 appears

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/23911.

To address it, I decided to simplify it with the following changes:

- Remove the animations as they were adding little value as you don't interact with this view or even see it when adding likes
- Use unidirectional data flow by observing a `post` object, which is the source of truth for number of likes. Remove the two properties that were storing the number of likes resulting in duplicated state.

In addition, I made a couple of other formatting and other improvements, including rewriting some of the code to use pure functions.

Screenshot 2024-12-19 at 11 45 33 AM
Screenshot 2024-12-19 at 11 45 19 AM

https://github.com/user-attachments/assets/d7b030d6-2586-4235-b177-231a1a65e85b

https://github.com/user-attachments/assets/b5fd0b48-bd7d-483f-8014-7cf32d9e5b06

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/303">25.6 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift [hunk 1]
```diff
@@ -4,132 +4,73 @@ protocol ReaderDetailLikesViewDelegate: AnyObject {
...
-
     static let maxAvatarsDisplayed = 5
-    weak var delegate: ReaderDetailLikesViewDelegate?
-
-    /// Stores the number of total likes _without_ adding the like from self.
-    private var totalLikes: Int = 0
 
-    /// Convenience property that adds up the total likes and self like for display purposes.
-    var totalLikesForDisplay: Int {
-        return displaysSelfAvatar ? totalLikes + 1 : totalLikes
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift:36]: `displaysSelfAvatar` was the root cause, as the `selfAvatarImageView` `hidden` value was being updated _after_ showing the a number of likes. So, there was an easier fix, but I opted to refactor it to make it completely reliable as there could be other issues.

**Review by crazytonyli — APPROVED** [review]
