### PR TITLE
Include year in Traffic date picker

### LINKED ISSUE #22767: Stats Traffic tab dates should include year
### Expected behavior

The date shown on the Stats Traffic tab should include the year to avoid confusion about which year is being displayed.

Discussed in:
- p1709586750284709/1709585366.152709-slack-C06BR07TJHK
- p1709042259067229/1709042158.468369-slack-C06BR07TJHK

### Actual behavior

The dates are shown without a year (e.g. "May", "May 1", "Feb 19 - Feb 25")

### Steps to reproduce the behavior
1. Open Stats
2. Go to the Traffic tab
3. Switch "By day" to different periods and notice the dates are displayed without a year.

##### Tested on iPad, iOS 17, Jetpack iOS 24.4 beta

### PR DESCRIPTION
**Pull request by guarani**
Adds the year to the date picker's display date to avoid confusion about which year is being displayed.

Fixes #22767

## Screenshots
| Before | After | 
| - | - | 
|  |  |

## To test
1. Open Stats
2. Go to the Traffic tab
3. Switch "By day" to different periods and notice the dates include the year (the exact formatting depends on the device locale):
    - By day: `January 20, 2024`
    - By week: `Jan 15 - Jan 21, 2024`
    - By year: `January 2024`

## Regression Notes
1. Potential unintended areas of impact

The Traffic tab is the only screen that might be affected

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Manual testing and existing unit tests.

3. What automated tests I added (or what prevented me from doing so)

I added unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] iPhone and iPad.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift [hunk 1]
```diff
@@ -41,7 +41,9 @@ class StatsTrafficDatePickerViewModel: ObservableObject {
     func formattedCurrentPeriod() -> String {
         let dateFormatter = period.dateFormatter
         if period == .week, let week = StatsPeriodHelper().weekIncludingDate(date) {
-            return "\(dateFormatter.string(from: week.weekStart)) - \(dateFormatter.string(from: week.weekEnd))"
+            let weekEndFormatter = DateFormatter()
+            weekEndFormatter.setLocalizedDateFormatFromTemplate("MMM d, yyyy")
+            return "\(dateFormatter.string(from: week.weekStart)) - \(weekEndFormatter.string(from: week.weekEnd))"
```
Comment (irfano) [inline WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift:46]:
```suggestion
            let yearFormatter = DateFormatter()
            yearFormatter.setLocalizedDateFormatFromTemplate("yyyy")
            return "\(dateFormatter.string(from: week.weekStart)) - \(weekEndFormatter.string(from: week.weekEnd)), \(yearFormatter.string(from: week.weekEnd))"
```

What about keeping the old return but adding year end of it? This way, we wouldn't copy `MMM d` to `weekEndFormatter`.

**Review by irfano — APPROVED** [review]
LGTM! The year is now shown with all granularities. I'm approving the PR. I have a minor comment. Feel free to merge after considering my comment. 👍🏻

File: WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift (hunk 1 above)
Comment (guarani) [reply WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift:46]: I wasn't sure if the `,` should be hard-coded. Both in your suggestion and in the current date format string, there's a hard-coded `,` so what I found below isn't specific to your suggestion but seems relevant.


| Locale | Explicit `,` in format | An alternative: use system-defined `dateFormatter.dateStyle = .medium` format |
| - | - | - |
| Turkish (tr_TR) | Mar 6, 2024 | 6 Mar 2024 |
| Spanish (es_PY) | mar. 6, 2024 | 6 mar. 2024 |

In both cases, the `,` shouldn't be used (please correct me if I'm wrong about `tr_TR`). To improve localization, I would like to try using the system-defined format in a separate issue, which I'll open to list some accessibility and localization improvements. Using the system-defined format would also remove the duplicate definitions of the format, which you raised here and is a very valid point.

Comment (guarani) [reply WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift:46]: Here's the separate issue: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/22

**Comment by guarani** [comment]
Hi @mokagio, I've merged this to the release branch to include it as a beta-fix. 
Please let me know if you have any questions 🙇

File: WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift (hunk 1 above)
Comment (irfano) [reply WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift:46]: Good point. I'm not sure if `Mar 6, 2024` is valid for Turkish, but I agree that we should use system-defined formats. Thanks for opening the issue.
