### PR TITLE
Workaround for a crashing bug with Bulgarian keyboards.

### LINKED ISSUE #15187: Crash in iOS 14 when using Bulgarian or Icelandic keyboards.
# Description

The App is crashing when focusing a text field using the Bulgarian or Icelandic keyboards.

Reference: p4a5px-2F1-p2

# Crash reproduction

## Prerequisites

- Make sure your device is running iOS 14.
- Make sure you're logged out before running this test.  It's not specific to the login flow but the steps below use the login flow.

## Steps

1. Add the Bulgarian or Icelandic language as the preferred one in your device.  Make sure the corresponding keyboard is also added.
2. Launch WPiOS
3. Tap "Continue with WordPress.com"
4. Tap on the email field to start writing.  If the Bulgarian / Icelandic keyboard is the selected one the App should crash right away.
5. If the selected keyboard is not Bulgarian / Icelandic, tap on the globe icon in your keyboard until you switch to it.

The app will crash.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #15187 

Adds a workaround to avoid the crash by replacing text field's `returnKeyType == .continue` with `returnKeyType == .next`.

# Reproducing the original issue

If you want to reproduce the original issue, comment the call to `UITextField.activateWorkaroundForBulgarianKeyboardCrash()` and following the testing steps below.

# To test the fix

Be logged out (this issue can be reproduced in any text field, but being logged out is necessary for the proposed reproduction steps below).

1. Add the Bulgarian or Icelandic keyboard in your devices settings.
2. Launch WPiOS
3. Tap "Continue with WordPress.com"
4. Tap on the email field to start writing. If the Bulgarian / Icelandic keyboard is the selected one you should be able to use it normally and the App should not crash.
5. If the selected keyboard is not Bulgarian / Icelandic, tap on the globe icon in your keyboard until you switch to it.  Make sure it works fine and doesn't crash the App.

# PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ScoutHarris** [comment]
Hey @diegoreymendez . I'm still reviewing this, but I was wondering if this should target the frozen branch (i.e. be included in the 16.0 release)?

File: WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    /// Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/15187
+    ///
+    @objc
+    class func activateWorkaroundForBulgarianKeyboardCrash() {
+        let original = class_getInstanceMethod(
+            UITextField.self,
+            #selector(UITextField.becomeFirstResponder))!
+        let new = class_getInstanceMethod(
+            UITextField.self,
+            #selector(UITextField.swizzledBecomeFirstResponder))!
```
Comment (ScoutHarris) [inline WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift]: Can these force unwraps be replaced with `guard`s?

**Review by ScoutHarris — CHANGES_REQUESTED** [review]

**Comment by diegoreymendez** [comment]
> I was wondering if this should target the frozen branch

I've run this through Eli and we agreed it's not clear that this is high impact enough to warrant a hotfix (or frozen-fix) since we've only received one report we could trace back to this.

File: WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift (hunk 1 above)
Comment (diegoreymendez) [reply WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift]: Changed.

**Comment by diegoreymendez** [comment]
Ready for another look.

**Review by ScoutHarris — APPROVED** [review]
Thanks @diegoreymendez !

Confirmed the app no longer crashes.

:shipit:

**Comment by diegoreymendez** [comment]
Thanks for the review!
