### PR TITLE
Offline Mode: Sync Engine

### LINKED ISSUE #21940: Discarding changes to a local post deletes the post
### Expected behavior

Discarding new changes to a local post should only discard the new changes, not the whole post.

### Actual behavior

In Gutenberg editor, when discard new changes to a local post, the local post is deleted.

### Steps to reproduce the behavior

1. Go to Posts list -> Draft.
2. Turn off the iOS device's WiFi.
3. Create a new post and tap Publish.
4. Go back to the draft post list. You'll see a draft post that has not been uploaded to the site yet.
5. Tap the draft post and make some changes.
6. Tap the back button in the post editor and tap discard.
7. Go back to the draft post list. The draft post is gone.

Here is a video recording:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1101828/13dc6d78-544b-48c5-ac00-0c0e6937f06c

### PR DESCRIPTION
**Pull request by kean**
This PR introduces a new sync engine for draft posts (see `PostCoordinator.setNeedsSync(for:)` and the related methods).

There are a lot of additions, but it's mostly unit tests.

The unit test target has some unrelated failures due to the WordPressKit update. I'll need to merge `trunk` in order to fix it and `trunk` needs this change to be merged https://github.com/wordpress-mobile/WordPress-iOS/pull/22900 first.

### Data

When you open an editor, it now always creates a new revision. For example:

```
// Before open
R0 → R1 (sync-needed)

// Editor opened
R0 → R1 (sync-needed) → R2
```

The editor works with `R2`. The previous revisions are immutable.

The app not longer uses the existing `remoteStatus` property. Instead, it uses a simple `isSyncNeeded` boolean to determine which revisions to sync.

This amount of data is just enough to implement nearly any sync algorithm and to also fix issues like #21940.

### Sync

`PostCoordinator` periodically syncs the revisions that have a `isSyncNeeded` flag set to `true`. It uses the new `PostRepository.sync` method introduces in the previous PRs. It creates a diff between the original and the most recent revision that needs sync, and uploads the changes using partial updates.

## Known Issues

- [ ] If media fails with a `.notConnectedToInternet`, the app doesn't display the "offline changes" label and doesn't perform quick retries

## Testing

The changes were tested **only** using REST APIs and **only** using a simplest scenarios where you edit a post and then tap "back" to save or discard changes. The remaining flows will be updated in the future PRs.

### Discard changes (new draft)

- Create a new draft
- **Verify** that if you tap back, the post is deleted without a confirmation dialog
- **Verify** that if you make any changes to the post and tap "back", it shows a confirmation dialog where you can discard or save the draft

### Discard changes (existing draft)

- Edit an existing draft
- **Verify** that if you tap back, the editor closes right away
- **Verify** that if you make any changes to the post and tap "back", it shows a confirmation dialog where you can discard or save the changes

### Discard changes (fix #21940)

Follow the steps from the issue https://github.com/wordpress-mobile/WordPress-iOS/issues/21940 and verify that it no longer reproduces.

### Create new post with image

- Create a new draft
- Add an image 
- Tap back and tap "Save Draft" before the image gets fully uploaded
- **Verify** that the image get uploaded
- **Verify** that the post is created on the server with an image
- **Verify** that no alerts or snackbars are shown at any point during sync

### Creating and updating unsynced a draft

- Set a breakpoint on `/post/new`
- Create and save a draft
- **Verify** that it hits the breakpoint
- Edit the draft (e.g. change the tilte) and save the changes
- Execute the original request
- **Verify** that the post was created
- **Verify** that app sends a follow-up request to save the changes on the server using partial updates
- **Verify** that the post got updated and these is only one post on the server

### Offline mode

Precondition: you are offline.

- Create and save a new draft
- **Verify** that the cell shows "Offline changes"
- **Verify** that you can open the post for editing and make more changes
- Enable connectivity
- **Verify** that the app uploads the post nearly instantaneously (you can look for "connection is reachable – retrying now" in the logs)

### Offline mode and restart

- Create and save a new draft
- **Verify** that the cell shows "Offline changes"
- Terminate the app
- Enable connectivity
- Re-open the app
- **Verify** that the post gets uploaded

### Sync failure and retry

Precondition: request fails for any reason other than "404"

- Create a new or update an existing draft
- Save draft
- **Verify** that the post gets synced with a progressively long delay (5, 7.5, 11.25...) until it reaches the maximum of 60 seconds

### Discarded images

- Create a new draft
- Create a revision with a new image
- Save the changes by tapping "Back" and "Save Changes"
- Create another revision and delete the image
- Save the changes
- Enable connectity
- **Verify** that the image does no get uploaded and does not block the app from uploading the changes

## Regression Notes
1. Potential unintended areas of impact: Draft Posts
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual and automated integration tests
3. What automated tests I added (or what prevented me from doing so): yes

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/Models/AbstractPost.swift [hunk 1]
```diff
@@ -146,4 +156,58 @@ extension AbstractPost {
...
+    }
+
+    var isEmpty: Bool {
+        let title = (postTitle ?? "").trimmingCharacters(in: .whitespaces)
+        let content = (content ?? "").trimmingCharacters(in: .whitespaces)
+        return title.isEmpty && content.isEmpty
+    }
+
+    // TODO: Replace with a new flag
+    @objc var isSyncNeeded: Bool {
```
Comment (kean) [inline WordPress/Classes/Models/AbstractPost.swift:186]: I'm planning to add a new flag to the database but only after we merge the changes in `trunk` and after 24.6 is cut. We'll be also removing some data.

File: WordPress/Classes/Models/Post.swift [hunk 2]
```diff
@@ -55,41 +55,12 @@ class Post: AbstractPost {
...
-            return
-        }
-
-        storedContentPreviewForDisplay = ""
-    }
-
-    // MARK: - Content Preview
-
-    fileprivate func buildContentPreview() {
-        if let excerpt = mt_excerpt, excerpt.count > 0 {
```
Comment (kean) [inline WordPress/Classes/Models/Post.swift:86]: This was buggy and not effective as it would constantly reset.

File: WordPress/Classes/Services/PostHelper.m [hunk 3]
```diff
@@ -8,6 +8,14 @@
 @implementation PostHelper
 
 + (void)updatePost:(AbstractPost *)post withRemotePost:(RemotePost *)remotePost inContext:(NSManagedObjectContext *)managedObjectContext {
+    [self updatePost:post withRemotePost:remotePost inContext:managedObjectContext overwrite:NO];
+}
+
++ (void)updatePost:(AbstractPost *)post withRemotePost:(RemotePost *)remotePost inContext:(NSManagedObjectContext *)managedObjectContext overwrite:(BOOL)overwrite {
+    if ([RemoteFeature enabled:RemoteFeatureFlagSyncPublishing] && (post.revision != nil && !overwrite)) {
```
Comment (kean) [inline WordPress/Classes/Services/PostHelper.m:15]: If there are local revision, only `sync` (and `trash` in the future) should be able to update the post with the remote changes. I'm planning to simplify this code a bit later when we remove the feature flag.

File: WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift [hunk 4]
```diff
@@ -83,15 +83,122 @@ extension PublishingEditor {
...
+        }
+
+        if presentedViewController != nil {
+            dismiss(animated: true, completion: publishPostClosure)
+        } else {
+            publishPostClosure()
+        }
+    }
+
+    func performEditorAction(_ action: PostEditorAction, analyticsStat: WPAnalyticsStat?) {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift:127]: This change should probably not be part of this PR, but it's too late too change. I suggest we roll forward and continue working on it in the future PRs. It's in the branch ,so it's safe.

File: WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift [hunk 5]
```diff
@@ -587,8 +778,34 @@ extension PublishingEditor {
...
+        guard RemoteFeatureFlag.syncPublishing.enabled() else {
+            return _createRevisionOfPost(loadAutosaveRevision: loadAutosaveRevision)
+        }
+        guard let managedObjectContext = post.managedObjectContext else {
+            return assertionFailure()
+        }
+
+        assert(post.latest() == post, "Must be opened with the latest verison of the post")
+
+        if !(post.isRevision() && !post.isSyncNeeded) {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift:769]: This check is needed only for a scenario where the app crashes during editor – it will be covered later. I plan to re-open the editor automatically to make sure the user either commits of discard the revision.

File: WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift [hunk 6]
```diff
@@ -15,11 +15,18 @@ protocol EditorAnalyticsProperties: AnyObject {
...
 
     static func handle(post: Post, in postListViewController: EditorPresenterViewController, entryPoint: PostEditorEntryPoint = .unknown) {
-
-        // Return early if a post is still uploading when the editor's requested.
-        guard !PostCoordinator.shared.isUploading(post: post) else {
-            presentAlertForPostBeingUploaded()
-            return
+        if RemoteFeatureFlag.syncPublishing.enabled() {
+            // Return early if a post is still uploading when the editor's requested.
+            guard !PostCoordinator.shared.isUpdating(post) else {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift:20]: Not great naming – will probably rework later once we start tearing the old code out.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 7]
```diff
@@ -114,7 +114,7 @@ final class PostListViewController: AbstractPostListViewController, UIViewContro
         }
         let updatedIndexPaths = (tableView.indexPathsForVisibleRows ?? []).filter {
             let post = fetchResultsController.object(at: $0)
-            return updatedObjects.contains(post)
+            return updatedObjects.contains(post) || updatedObjects.contains(post.original())
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift:117]: The height no longer changes, so we should now move the notification observer to the cell itself, which will be safer

File: WordPress/Classes/Services/PostCoordinator.swift [hunk 8]
```diff
@@ -245,6 +257,225 @@ class PostCoordinator: NSObject {
...
+        revision.isSyncNeeded = true
+        ContextManager.shared.saveContextAndWait(coreDataStack.mainContext)
+
+        let original = revision.original()
+        scheduleSync(for: original)
+    }
+
+    /// Represents an operation for syncing the post and updating it to the
+    /// revision the operation was initialized with.
+    final class SyncOperation {
```
Comment (kean) [inline WordPress/Classes/Services/PostCoordinator.swift:284]: FYI I made some large changes to make this part of sync more reliable and readable in the upcoming PRs, so I wouldn't spend too much time on review now.

**Review by momo-ozawa — COMMENTED** [review]
If you save a new draft, then reopen the editor, the "Update" button is enabled from the get go. It should only be enabled if the user makes any changes.


https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/757cb7fe-a1c0-402a-96ca-fefdefc83cd3

When testing offline mode, the app crashes when the wifi reconnects. I waited for the "Offline changes" to appear in the post list cell, then reconnected the wifi, at which point the app crashed

Screenshot 2024-03-28 at 18 42 58

**Comment by kean** [comment]
> If you save a new draft, then reopen the editor, the "Update" button is enabled from the get go. It should only be enabled if the user makes any changes.

It's been fixed in the newer PR where it now displays a "Publish" button https://github.com/wordpress-mobile/WordPress-iOS/pull/22913

> When testing offline mode, the app crashes when the wifi reconnects. I waited for the "Offline changes" to appear in the post list cell, then reconnected the wifi, at which point the app crashed

Good catch. I only tested it once on a real device and it somehow worked. I think it was because I didn't have a debugger attached, so it didn't trigger a Core Data concurrency error. Fixed.

File: WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift [hunk 9]
```diff
@@ -466,50 +651,32 @@ extension PublishingEditor {
...
+        consolidateChangesIfPostIsNew()
 
-            PostCoordinator.shared.save(post,
-                                        defaultFailureNotice: uploadFailureNotice(action: action)) { [weak self] result in
-                guard let self = self else {
-                    return
-                }
-                self.postEditorStateContext.updated(isBeingPublished: false)
-                SVProgressHUD.dismiss()
+        PostCoordinator.shared.save(post, defaultFailureNotice: uploadFailureNotice(action: action)) { [weak self] result in
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift:658]: Reverting this change as we are now handling the feature flag on a higher level – at the button tap.

**Review by momo-ozawa — APPROVED** [review]
Thanks for addressing the issues from my previous review! Reconnecting doesn't crash anymore 👍
