### PR TITLE
Publicize: Fix Facebook auth success detection

### LINKED ISSUE #17794: Publicize: Flow to connect a Facebook account never completes
### Expected behavior
Logging in with a Facebook account through the Publicize web flow should return to the app after the login, and the Facebook account should be available be made available to the user.

### Actual behavior
The web flow to connect a new Facebook account never returns to the app after successfully logging in with Facebook:

https://user-images.githubusercontent.com/830056/150392422-2c12ba2e-f200-4061-b4f1-ae50094cab3b.MP4

### Steps to reproduce the behavior

1. Open the app and select a WP.com or Jetpack site.
1. On the My Site screen, scroll down to the Configuration section.
1. Tap "Sharing".
1. Tap "Facebook".
1. Tap "Connect".
1. Login with a Facebook account that has at least one page.
1. Accept all Facebook permissions.
1. Notice how the web flow gets stuck and never returns to the app.

### Additional context

This was caused by a change to the parameters of the URL used to create a new Facebook connection (internal ref: r238579-wpcom). Assuming the implementation on iOS is similar to what we have on Android, then the end of the web flow is detected based on some URL pattern. The fix should be to update this logic to take the new URL structure into account. 

##### Tested on iPad Pro 11in, iOS 15.1, WPiOS 19.0

### PR DESCRIPTION
**Pull request by frosty**
Fixes #17794. The URL used to determine success for the Facebook Publicize connection flow has changed. This PR updates the check used to determine a Facebook success so that it matches the new URL (see final commit for those changes), as well as some slight refactoring to improve the existing code in this section.

The new URL should contain `state` and `code` values if it is a Facebook login, and `state` and `error` if it was unsuccessful. All other login types should be unaffected.

Please see the original issue for more detail about the problem.

### To test

-  Open the app and select a WP.com or Jetpack site.
-  On the My Site screen, scroll down to the Configuration section.
-  Tap "Sharing".
-  Tap "Facebook".
-  Tap "Connect".
-  Login with a Facebook account that has at least one page.
-  Accept all Facebook permissions.
-  Ensure that the webview is dismissed and you are asked which account you would like to connect.

Also ensure that you can still connect some other account types such as Twitter.

## Regression Notes
1. Potential unintended areas of impact

Other account types connecting, as I refactored some of that code slightly.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I manually tested connecting to other account types. I also ensured all tests pass, although I can't see that we have tests for publicize currently.

3. What automated tests I added (or what prevented me from doing so)

 We could add some to check these various success and failure URLs, but I wanted to merge this soon and it would be a reasonable amount of work to compile a list of all of the various URLs we're checking for.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by renanferrari** [comment]
@guarani I have some test accounts for Facebook and Twitter, so let me know if you need them 🙂

File: WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.swift [hunk 1]
```diff
@@ -145,43 +156,51 @@ class SharingAuthorizationWebViewController: WPWebViewController {
...
         // If we've made it this far and verifyRange is found then we're *probably*
         // verifying the oauth request.  There are edge cases ( :cough: tumblr :cough: )
         // where verification is declined and we get a false positive.
-        if requested.range(of: SharingAuthorizationWebViewController.verifyActionParameter) != nil {
+        if AuthorizeURLComponents.verifyActionParameter.containedIn(url) {
+            return .verify
+        }
+
+        // Facebook
+        if AuthorizeURLComponents.state.containedIn(url) && AuthorizeURLComponents.code.containedIn(url) {
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.swift:195]: This is not a blocker, just a possible improvement.

The URL format I see is:
```
https://public-api.wordpress.com/connect/?code=VERY_LONG_RANDOM_STRING&state=VERY_LONG_RANDOM_STRING#_=_
```
I'm not sure if failure cases can also include these random strings (tokens). If they can, it seems possible (though somewhat unlikely) for theses tokens to sometimes contain the characters "code" and "state", causing a false positive here.

Perhaps looking for query params with the names "code" and "state" would work more reliably:
```
        if let queryItems = URLComponents(url: url, resolvingAgainstBaseURL: true)?.queryItems {
            let containsState = queryItems.contains(where: { queryItem in
                queryItem.name == AuthorizeURLComponents.state.rawValue
            })
            let containsCode = queryItems.contains(where: { queryItem in
                queryItem.name == AuthorizeURLComponents.code.rawValue
            })
            if containsState && containsCode {
                return .verify
            }
        }
```

**Review by guarani — APPROVED** [review]
I tested Facebook, LinkedIn, and Twitter and all working great!

I left a minor code comment, but the change looks good to me :shipit:
