### PR TITLE
Fix incorrect Navigation Bar Appearance in Reader Detail screen

### LINKED ISSUE #20362: Incorrect Navigation Bar Appearance in Reader Detail screen
### Description

This is a regression bug caused by a PR targeting the upcoming v22.0:
-  https://github.com/wordpress-mobile/WordPress-iOS/pull/20278

### Expected behavior

The navigation bar appearance in the Reader Detail screen should be transparent if the post has a featured image.

### Actual behavior

The navigation bar appears white.

### Steps to reproduce the behavior
1. Enable Light Mode.
2. Navigate to any post with a featured image.
    - For example: https://lostinamberland.wordpress.com/2023/03/18/way-too-far/
3. Notice how the navigation bar appears white. It should be transparent so that the featured image is visible.  

##### Tested on iPhone 14 Pro Max, iOS 16, WPiOS 22.0

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #20362

## Description

This PR resolves a regression bug caused in this PR:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/20278

The aforementioned PR changed the Reader's navigation bar appearance from transparent to opaque. The new navigation bar appearance is inherited by all view controllers that get pushed to the same navigation controller. But one view controller should keep the transparent navigation bar appearance. And that is the `ReaderDetailViewController`. 

This PR resolves that issue by refactoring the navigation bar appearance logic in `ReaderDetailViewController`. So instead of setting `navigationBar.standardAppearance`, I used `navigationItem.standardAppearance` instead.

##  Notes 

I recommend to review each commit individually and in this order:
1. [Resolve a regression bug that was causing the nav bar appearance to appear white in posts with featured image.](https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/c6ba7364c8e3c2f57f56a667bde1b45bc855b742) 
2. [Update the navigation bar tintColor using its navigation item](https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/83c68db1f4ee6c97fe051ad918d24fa8800c5751)
3. [Reorganize methods and properties](https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/fada9c4b8d5c558309f0e61977a8426f12294602)

## Screenshots

| Before | After |
| ------- | ----- |
|  |  |

## Test Instructions
1. Install WordPress / Jetpack and login.
2. Enable Light Mode.
3. Head to a Post with a Featured Image:
    - Deep Link To: https://lostinamberland.wordpress.com/2023/03/18/way-too-far/
4. **Verify** the navigation bar appearance is transparent.

## Regression Notes
1. Potential unintended areas of impact
None.

6. What I did to test those areas of impact (or what existing automated tests I relied on)
None.

7. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
I'm about to start the 22.0 code freeze. This PR is not ready to land into `trunk`, but it seems worth leaving under the 22.0 milestone and update to point to `release/22.0` once the branch is ready given it's a UI fix.

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 1]
```diff
@@ -72,13 +73,29 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
...
+    /// This property is used to restore the navigation bar tint color to its original value.
+    private var previousNavBarTintColor: UIColor?
+
+    /// The navigation bar tint color changes depending on whether the featured image is visible or not.
+    private var navBarTintColor: UIColor? {
+        get {
+            return navigationBar?.tintColor
+        }
+        set(newValue) {
+            // Ideally, we should be setting the navigationItem's tint color, but for some reason that didn't work.
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift]: This is resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/4543fedb1a85f8e204a264e7e39fd266efe39c70

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 2]
```diff
@@ -72,13 +73,29 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
     /// Listens for contentOffset changes to track when the user scrolls
     private var scrollViewObserver: NSKeyValueObservation?
 
-    /// Stores the nav bar appearance before we change it to transparent
-    /// this allows us to reset it when the view disappears
-    private var originalNavBarAppearance: NavBarAppearance?
+    /// Flag indicating whether the navigation bar appearance needs restoration when the view disappears. Default is `false`.
+    ///
+    /// Flag changes to `true` when this view changes the navigation bar tint color. In other words, when the `navBarTintColor` setter is called.
+    private var navigationBarAppearanceNeedsRestoration = false
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift]: This is removed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/4543fedb1a85f8e204a264e7e39fd266efe39c70

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 3]
```diff
@@ -72,13 +73,29 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
...
 
-    private var navBarTintColor: UIColor = Styles.endTintColor {
-        didSet {
-            navigationBar?.setItemTintColor(useCompatibilityMode ? .textInverted : navBarTintColor)
+    /// The original navigation bar tint color.
+    ///
+    /// This property is used to restore the navigation bar tint color to its original value.
+    private var previousNavBarTintColor: UIColor?
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift]: This is removed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20363/commits/4543fedb1a85f8e204a264e7e39fd266efe39c70

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 4]
```diff
@@ -155,15 +164,22 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
...
-        navigationBar.standardAppearance.configureWithTransparentBackground()
+        // Transparent navigation bar
+        let appearance = UINavigationBarAppearance()
+        appearance.configureWithTransparentBackground()
+        navigationItem.standardAppearance = appearance
+        navigationItem.compactAppearance = appearance
+        navigationItem.scrollEdgeAppearance = appearance
+        if #available(iOS 15.0, *) {
+            navigationItem.compactScrollEdgeAppearance = appearance
+        }
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift:185]: Setting the `navigationItem`'s appearance ( instead of `navigationBar` ) is the most important change in the PR.

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 5]
```diff
@@ -102,98 +110,126 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
...
-            return
+        isLoading = true
+        isLoaded = true
+
+        var timedOut = false
+
+        let completionHandler: (CGSize) -> Void = { [weak self] size in
+            guard let self = self else {
+                return
+            }
```
Comment (alpavanoglu) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift:169]: Tidbit:
Now we can do
```Swift
guard let self else {
    return
}
```

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift [hunk 6]
```diff
@@ -102,98 +110,126 @@ class ReaderDetailFeaturedImageView: UIView, NibLoadable {
...
 
-    // MARK: - Public: Helpers
-    public func updateUI() {
-        scrollViewDidScroll()
-    }
+    // MARK: - Public: Fetching Featured Image
 
-    public func deviceDidRotate() {
-        guard !useCompatibilityMode else {
+    public func load(completion: @escaping () -> Void) {
```
Comment (alpavanoglu) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift:145]: This function handles a bit too much of action here. But no rush for fixing it since we need it in the hotfix

**Review by alpavanoglu — APPROVED** [review]
Test Succeeded ✅
