### PR TITLE
Fix Domain Dashboard Card appearing while domains information is still loading 

### LINKED ISSUE #20620: Domain Dashboard Card may appear momentarily while domains information is still loading
## Description

- Domain Dashboard Card may appear momentarily while the site information is loading and disappear once domains are loaded
- When switching sites, Domain Dashboard Card may appear and disappear only after pull-to-refresh is done

The issue will be visible after logging into the app. Once the information is loaded, the issue is no longer happening.

## Expected behavior 

Domain Dashboard Card should only appear after all the relevant information to determine its presentation is loaded.

## Video

https://user-images.githubusercontent.com/4062343/235092318-313bbf25-d920-48c7-b1c2-2731fbbe9456.mp4

### PR DESCRIPTION
**Pull request by staskus**
## ℹ️ Milestone information

 Since the issue only happens during the first load, it can be moved to 22.4 if the review doesn't pass on time.

## Description

Fixes #20620

- Don't show the domain dashboard card while domain information hasn't been loaded to avoid the card appearing momentarily and then disappearing
- Load domain information when switching sites, otherwise the domain information is not loaded for non-default domain sites

## Testing instructions

Log into an admin account with at least two sites (pc8eDl-NP-p2):
- dotCom site without a domain
- dotCom site with a domain

### Case 1: Only show the card when the domains are loaded (site without a domain)
1. Launch Jetpack
2. Log into a given account
3. Select a site **without a domain after login**
4. The card appears after a moment

### Case 2 Don't show the card before domains are loaded (site with a domain)
1. Launch Jetpack
2. Log into a given account
3. Select a site **with a domain after login**
4. The card never appears

### Case 3 Switch sites
1. Launch Jetpack
2. Log into a given account
3. Select a site **with a domain after login**
4. The card doesn't appear
5. Switch to a site **without a domain**
6. The card appears after a moment

## Regression Notes

1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

7. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### Before
https://user-images.githubusercontent.com/4062343/235092318-313bbf25-d920-48c7-b1c2-2731fbbe9456.mp4

### After
https://user-images.githubusercontent.com/4062343/235122569-d00f5f49-c0e2-4bb6-83b9-3b1ca169ea24.mp4

### CODE REVIEW

File: WordPress/WordPressTest/Dashboard/DomainsDashboardCardHelperTests.swift [hunk 1]
```diff
@@ -50,10 +54,24 @@ final class DomainsDashboardCardHelperTests: CoreDataTestCase {
...
+        let blog = BlogBuilder(mainContext)
+            .with(supportsDomains: true)
+            .with(domainCount: 0, of: .wpCom)
+            .with(domainCount: 0, of: .registered)
+            .with(hasDomainCredit: false)
+            .build()
+
+        let result = DomainsDashboardCardHelper.shouldShowCard(for: blog, isJetpack: true, featureFlagEnabled: true)
+
+        XCTAssertFalse(result, "Card should not show for blogs with domain credit")
```
Comment (guarani) [inline WordPress/WordPressTest/Dashboard/DomainsDashboardCardHelperTests.swift]:
```suggestion
        XCTAssertFalse(result, "Card should not until domain information is loaded")
```

**Review by guarani — APPROVED** [review]
Tested and this is working great! I had one minor typo fix in the testing code which I'll commit since it's the last day of the sprint (let me know if you prefer I don't do that).

> Case 2 Only show the card when the domains loaded (site with a domain)

By the way, should this testing instruction say "**Don't** show the card when the domains loaded (site with a domain)"?

**Comment by guarani** [comment]
Enabled auto-merge 🤞

**Comment by staskus** [comment]
> By the way, should this testing instruction say "**Don't** show the card when the domains loaded (site with a domain)"?

Yes, you're right! It should say "Don't show the card before domains are loaded (site with a domain)" since it tests the case that the card doesn't appear incorrectly before domain information loads and then suddenly disappears.
