### PR TITLE
Fix an issue with blogging reminders prompt not being shown after publishing a new post

### LINKED ISSUE #18696: Blogging Reminder bottom sheet not always shown after publishing 1st post on site
### Expected behavior

When publishing the first post on a site, the Blogging Reminders bottom sheet should appear.

### Actual behavior

When publishing the first post on a site, in about 1 out of 3 times, the Blogging Reminders bottom sheet does not appear.

### Steps to reproduce the behavior

1. Create a site
2. Publish a post
3. Check if Blogging Reminders bottom sheet appears
4. Repeat steps 1 to 3 until you notice the bottom sheet doesn't appear after publishing a post

##### Tested on iPhone 11, iOS 15.3.1, WPiOS 19.9 beta

h/t to @tiagomar for reporting this issue!

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/18696. I also updated the localization to no longer say "while the post is publishing..." – it's guaranteed to be published by this point. 

To test:

https://github.com/user-attachments/assets/6df0a9f0-fbf0-45db-ad9b-a523e2b0ac3c

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift [hunk 1]
```diff
@@ -204,19 +204,18 @@ extension PublishingEditor {
     }
 
     func discardUnsavedChangesAndUpdateGUI() {
-        let postDeleted = discardChanges()
-        dismissOrPopView(didSave: !postDeleted)
+        discardChanges()
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift:207]: The fact that we no longer need `didSave` simplified this quite a bit.

File: WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowIntroViewController.swift [hunk 2]
```diff
@@ -197,18 +185,10 @@ extension BloggingRemindersFlowIntroViewController: ChildDrawerPositionable {
...
-                                                    comment: "Description on the first screen of the Blogging Reminders Settings flow called aftet post publishing.")
-
-    static let siteSettingsIntroDescription = NSLocalizedString("Set up your blogging reminders on days you want to post.",
-                                                            comment: "Description on the first screen of the Blogging Reminders Settings flow called from site settings.")
-
-    static let introButtonTitle = NSLocalizedString("Set reminders",
-                                                    comment: "Title of the set goals button in the Blogging Reminders Settings flow.")
+private enum Strings {
+    static let introTitle = NSLocalizedString("bloggingRemindersPrompt.intro.title", value: "Blogging Reminders", comment: "Title of the Blogging Reminders Settings screen.")
+    static let introDescription = NSLocalizedString("bloggingRemindersPrompt.intro.details", value: "Set up your blogging reminders on days you want to post.", comment: "Description on the first screen of the Blogging Reminders Settings flow called aftet post publishing.")
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowIntroViewController.swift:190]: There was no longer need for a separate path + I adopted l10n.

File: WordPress/Classes/ViewRelated/Post/EditPostViewController.swift [hunk 3]
```diff
@@ -126,19 +126,12 @@ class EditPostViewController: UIViewController {
...
+            guard let self else {
                 editor?.dismiss(animated: true) {}
                 return
             }
-
-            // NOTE:
-            // We need to grab the latest Post Reference, since it may have changed (ie. revision / user picked a
-            // new blog).
-            if changesSaved {
-                strongSelf.post = editor?.post as? Post
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/EditPostViewController.swift:139]: This is no longer how it works starting from 23.9. After publishing `editor?.post as? Post` points to a _revision_ that gets deleted during publishing. `self.post` is sufficient now.
