### PR TITLE
Do not make another attempt if the HTTP request was cancelled

### LINKED ISSUE #20379: NSGenericException: Task created in a session that has been invalidated
Sentry Issue: [WORDPRESS-IOS-3PDR](https://a8c.sentry.io/issues/3904068976/?referrer=github_integration)

```
NSGenericException: Task created in a session that has been invalidated
  ?, in UploadRequest.Uploadable.task
  ?, in DataRequest.Requestable.task
  File "Request.swift", line 361, in DataRequest.Requestable.task
  File "SessionManager.swift", line 260, in SessionManager.request
  File "SessionManager.swift", line 239, in SessionManager.request
...
(39 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #20379, which is a crash that may happen during log out. See [this comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/20379#issuecomment-1481995663) for the potential cause of this crash.

This crash _should_ be reproducible in the app by simply tapping the log out button, if you set up a proxy and delay `/me/settings` API call's response for a few seconds. I tried to do that using mitmproxy but didn't find a "delay response" feature in it and gave up.

## Test instructions

https://github.com/wordpress-mobile/WordPress-iOS/commit/f280227989f1e429bb06d985cd858c8ff3e7db5c reproduces this crash in a unit test. Check out this commit locally and run the added unit test to verify the app indeed crashes.

If the CI passes then we should be all good. Or, you can checkout the latest commit in this PR branch and run the same test again to verify the app no longer crashes.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
None.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/WordPressTest/AccountSettingsServiceTests.swift [hunk 1]
```diff
@@ -71,4 +72,29 @@ class AccountSettingsServiceTests: CoreDataTestCase {
...
+        stub(condition: isPath("/rest/v1.1/me/settings")) { _ in
+            apiFired.fulfill()
+            sleep(2)
+            return HTTPStubsResponse(jsonObject: [:], statusCode: 500, headers: nil)
+        }
+        service.refreshSettings()
+
+        // A 5 senconds timeout is used here becuase there is a 4 seconds delay of making the HTTP API request
+        // in the `refreshSettings` call above.
+        wait(for: [apiFired], timeout: 5)
```
Comment (mokagio) [inline WordPress/WordPressTest/AccountSettingsServiceTests.swift]: The 4 seconds delay in the test because of `sleep(2)` and the retry slows down the unit tests.

This is unfortunate. Unit tests should be as fast as we can make them.

I wonder if there's a way to test that the completion with status `failed` is called when the API request fails with  `URLError.cancelled` instead?

That would remove the need to simulate a delay in the networking at this level. 🤔 

I realize it'd be troublesome to write a new test and to insert probes for this behavior, but I'd love to avoid making the unit tests sleep if possible.

Comment (crazytonyli) [reply WordPress/WordPressTest/AccountSettingsServiceTests.swift]: I had another look at the code. It turns out I misread the code. The test can call `getSettingsAttempt` straight-away. With https://github.com/wordpress-mobile/WordPress-iOS/pull/20392/commits/b29c466f7ccfff3ae8b8f05df788ce1af730dde3, this unit test passes in just a bit over 0.5 seconds.

Comment (crazytonyli) [reply WordPress/WordPressTest/AccountSettingsServiceTests.swift]: BTW, the `sleep(2)` doesn't affect the test execution—the test finishes just at the time the sleep starts.

Comment (mokagio) [reply WordPress/WordPressTest/AccountSettingsServiceTests.swift]: > With https://github.com/wordpress-mobile/WordPress-iOS/commit/b29c466f7ccfff3ae8b8f05df788ce1af730dde3, this unit test passes in just a bit over 0.5 seconds.

🎉 

image

> BTW, the `sleep(2)` doesn't affect the test execution—the test finishes just at the time the sleep starts.

Then, is the value in having it that delayed is to simulate network latency? How would you feel about adding a comment to explain that?

**Review by mokagio — APPROVED** [review]
Approving to unblock. [I need to understand the `sleep` usage better](https://github.com/wordpress-mobile/WordPress-iOS/pull/20392#discussion_r1148818142), but that's not a reason to stop this.

**Comment by mokagio** [comment]
@crazytonyli by the way, in order to merge, this branch will need to be synced with `trunk` because of the new GitHub checks rules

Screenshot 2023-03-27 at 5 00 56 pm

File: WordPress/WordPressTest/AccountSettingsServiceTests.swift (hunk 1 above)
Comment (crazytonyli) [reply WordPress/WordPressTest/AccountSettingsServiceTests.swift]: My bad, the test code sure looks quite random. I've added [some comments](https://github.com/wordpress-mobile/WordPress-iOS/pull/20392/commits/970402334c16066d92f25edfdbd0e4eb93b7deee) to explain what's happening underneath.

File: WordPress/WordPressTest/AccountSettingsServiceTests.swift [hunk 2]
```diff
@@ -71,4 +72,29 @@ class AccountSettingsServiceTests: CoreDataTestCase {
...
+
+        let apiFired = expectation(description: "Get settings API fired")
+        stub(condition: isPath("/rest/v1.1/me/settings")) { _ in
+            apiFired.fulfill()
+            sleep(2)
+            return HTTPStubsResponse(jsonObject: [:], statusCode: 500, headers: nil)
+        }
+        service.refreshSettings()
+
+        // A 5 senconds timeout is used here becuase there is a 4 seconds delay of making the HTTP API request
```
Comment (AliSoftware) [inline WordPress/WordPressTest/AccountSettingsServiceTests.swift]: Too late as the PR is already merged, but could be nice to fix typos on next occasion 🙃 
```suggestion
        // A 5 seconds timeout is used here because there is a 4 seconds delay of making the HTTP API request
```
