### PR TITLE
Issue/5890 multiple nsurl session for uploads

### LINKED ISSUE #5890: Cannot Parse Response
### Expected behaviour
 On a WP.com site while uploading multiple photo objects on a post, if the user taps on one photo and selects "Stop Upload", only that photo should be canceled and removed from the post. Other photo uploads should continue normally.

### Actual behaviour

 The photo upload that is selected is cancelled and removed but other photos on the post that are being uploaded give an error that says: "cannot parse response"

### Steps to reproduce the behavior
 - Login in the app using a WP.com account
 - Start writing  a new post in a blog
 - Tap on the add media icon
 - Add multiple images
 - Tap on one of the image while the upload is happening and select "Stop Upload"
 - You should see something like this:

screen shot 2016-08-24 at 14 14 08

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #5890 

Check the ticket description above for the symptoms.

Before I merged this in I would like for everyone that has some free time to have a look on the code and see if there is another why to fix the bug.  

Here are some of the things I checked/tried before I got to this solution
  
- ~~This only happens on WP.com hosted site, on self hosted sites it work has expected~~. It actually happens to any site that uses HTTP 2.0. I've tested this with self-hosted sites that HTTP 2.0 (Pressable test site) and it also fails with the same symptoms 
- When testing on the simulator the fact of having AutoProxxy running causes the error being more frequent.
 - I double checked the code around the editor to see if there was something wrongly implement around the Progress reporting and cancelation of tasks but all was consistent.
 - I dabbled around  the values around NSURLSessionConfiguration for HTTPMaximumConnectionsPerHost and HTTPShouldUsePipelining. Whatever values I used the end result was the same.
 - I disable all caching of the requests on NSURLSessionConfiguration and NSURLRequest level and still the error occurs.
- Thinking the issue was around AFNetworking I changed the code to AlamoFire and the result is the same.
 - I even changed the code to use vanilla NSURLSession and the result was still the same
 - My last try was to use NSURLSession but then to use a separate NSURLSession for each image upload. This finally sorted the issue, you can see the end result on this PR.

One thing that I was unable to check was the server side of this request could it be that something is strange on REST API media/new endpoint? One thing that NSURLSession does is to share the connection to a host between multiple request could the cancelation of one request causing the others to fails server side?

Needs Review: @jleandroperez the same as this PR https://github.com/wordpress-mobile/WordPress-iOS/pull/5891 but retargeting to the 6.5 release branch.

### CODE REVIEW

File: WordPress/WordPressApi/WordPressComRestApi.swift [hunk 1]
```diff
@@ -43,6 +44,20 @@ public class WordPressComRestApi: NSObject
     public var appendsPreferredLanguageLocale = true
 
     private lazy var sessionManager: AFHTTPSessionManager = {
+        let sessionManager = self.createSessionManager()
+        return sessionManager
+    }()
+
+    private var uploadSessionManager: AFHTTPSessionManager {
+        get {
+            if #available(iOS 10.0, *) {
```
Comment (jleandroperez) [inline WordPress/WordPressApi/WordPressComRestApi.swift]: *NICE!!*

**Comment by jleandroperez** [comment]
@SergioEstevao took the current branch for a ride, looks great!!

One (probably) unrelated thing. I've observed this layout constraint error in the console, right after cancelling one of the uploads:

```
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-08-31 16:28:34.587 WordPress[613:240916] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x12f0ba930 h=--& v=--& V:[UIView:0x12f54b140(13)]>",
    "<NSLayoutConstraint:0x12cf6e6b0 V:[_UIDimmingKnockoutBackdropView:0x12f09f8f0(>=44)]>",
    "<NSLayoutConstraint:0x12cdb4350 UIView:0x12f0866a0.height == UIView:0x12f000ef0.height>",
    "<NSLayoutConstraint:0x12cf6e610 _UIDimmingKnockoutBackdropView:0x12f09f8f0.top == UIView:0x12f0866a0.top>",
    "<NSLayoutConstraint:0x12ecf21d0 _UIAlertControllerView:0x12cf64380.height == UIView:0x12f000ef0.height>",
    "<NSLayoutConstraint:0x12e8b3580 _UIAlertControllerView:0x12cf64380.height == UIView:0x12f54b140.height>",
    "<NSLayoutConstraint:0x12f08c770 _UIDimmingKnockoutBackdropView:0x12f09f8f0.bottom == UICollectionView:0x12e1f2a00.bottom>",
    "<NSLayoutConstraint:0x12f08c810 UIView:0x12f0866a0.bottom == UICollectionView:0x12e1f2a00.bottom>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x12f08c810 UIView:0x12f0866a0.bottom == UICollectionView:0x12e1f2a00.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-08-31 16:28:34.588 WordPress[613:240916] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x12f0ba930 h=--& v=--& V:[UIView:0x12f54b140(13)]>",
    "<NSLayoutConstraint:0x12ec606a0 V:[UIView:0x12f0866a0(>=44)]>",
    "<NSLayoutConstraint:0x12cdb4350 UIView:0x12f0866a0.height == UIView:0x12f000ef0.height>",
    "<NSLayoutConstraint:0x12ecf21d0 _UIAlertControllerView:0x12cf64380.height == UIView:0x12f000ef0.height>",
    "<NSLayoutConstraint:0x12e8b3580 _UIAlertControllerView:0x12cf64380.height == UIView:0x12f54b140.height>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x12ec606a0 V:[UIView:0x12f0866a0(>=44)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-08-31 16:28:34.606 WordPress[613:240916] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
```

Sounds like we probably wanna address that in another PR, since it's unrelated.

:shipit: on this one!
