### PR TITLE
Reduce flickering when previewing a site

### LINKED ISSUE #16122: Site Creation flow: flicker when switching between mobile and desktop view
reported by @jd-alexander 

### Expected behavior
preview loads cleanly

### Actual behavior
When I selected a design and clicked Preview there would be a flicker from the mobile layout to the desktop layout during loading. 

https://user-images.githubusercontent.com/66104034/111557962-60bd8300-8753-11eb-90cb-43868ea2a4aa.MP4

Noticed on iPad and iPhone 12 in WPiOS 16.9 beta

### LINKED ISSUE #17864: New site creation: Flicker when previewing selected site design
### Expected behavior
No flicker or jank when initially painting the preview.

### Actual behavior
Some flickering occurs.

### Steps to reproduce the behavior
1. Create WordPress.com site
2. Select a design (the one chosen in the attached video, for example)
3. Tap Preview

https://user-images.githubusercontent.com/2092798/152187405-89e1313d-9834-40f3-821a-b00885b9a330.mp4

This view uses a different view controller than the views in https://github.com/wordpress-mobile/WordPress-iOS/pull/17861.

### PR DESCRIPTION
**Pull request by twstokes**
Fixes #16122 #17864

## Description

In my testing, flickering occurs on site previews due to:
- The blank web view being shown before the site's content is fully loaded
- The container UIStackView resizing before the web view can catch up

This PR implements the following:
- On the initial load of `PreviewWebKitViewController` and `TemplatePreviewViewController`, sets the web view's opacity to 0 (clear / not shown).
- On size changes (Mobile, Tablet, Desktop) fades the web view's opacity to 0.
- When the URL has finished loading, the `webView(_:didFinish:)` [WKNavigationDelegate method](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455629-webview)  fades the web view's opacity back to 1.

**Before**

https://user-images.githubusercontent.com/2092798/153501845-1a1e972c-b043-486b-836a-d4031a65f343.MP4

**After**

https://user-images.githubusercontent.com/2092798/153501909-db200bd3-179e-4498-b197-60c54b539f54.MP4

### Previews for existing content

1. Load a site preview by tapping the site's URL at the top of the "My Site" view.
2. Observe the site loaded in landscape and portrait orientations. The expectation is a smoother load with minimal flickering / jank.
3. At the bottom right of the preview toggle between the three different sizes: Mobile, Tablet, and Desktop.
4. Expect a smooth transition with minimal flickering / jank.
5. Tap the "Refresh" button.
6. Expect that there is no difference in refreshing as its functionality wasn't changed. Some minimal flickering may occur but it shouldn't be too distracting.

**These steps should be repeated in all areas that a preview can be shown:**

- Tapping the URL at the top of the "My Site" view.
- Tapping the "View Site" row at the bottom of the "My Site" view.
- Tapping the three dots at the top right and choosing "Preview" while editing a Post or Page.
- (any other places where a preview existing content can be shown)

### Previews of templates

1. In the "My Sites" view, tap the "+" and choose "Create WordPress.com site".
2. Select a design and tap "Preview".
3. Observe the preview in landscape and portrait orientations. The expectation is a smoother load with minimal flickering / jank.
4. At the top right of the preview toggle between the three different sizes: Mobile, Tablet, and Desktop.
5. Expect a smooth transition with minimal flickering / jank.

### Previews of page layouts

1. In the "My Site" view, tap "Pages".
2. Tap the "+" at the bottom right.
3. Select a layout and tap "Preview".
4. Observe the preview in landscape and portrait orientations. The expectation is a smoother load with minimal flickering / jank.
5. At the top right of the preview toggle between the three different sizes: Mobile, Tablet, and Desktop.
6. Expect a smooth transition with minimal flickering / jank.

## Regression Notes
1. Potential unintended areas of impact
- Any area where previews for a site can be shown (identified in testing steps above)
- Previewing a new site template

These changes should not affect anything outside of these views.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I tested with a phone in portrait and landscape, as well as a tablet.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17861-35de7ca</code>. IPA is available <a href='https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/36440efc-d762-4d19-a31a-3750af215a13/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=ahRfbuwgNqDRX6eqJpYNZUNyyAk0zCYkFdj8rU5ZCec%3D&se=2022-02-09T02%3A32%3A40Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

**Comment by jkmassel** [comment]
You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17861-35de7ca</code>. IPA is available <a href='https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/ea57ca06-ed60-4226-a563-59b2897919fd/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=8LtGcmhs0S5vHVuqAUaNmgyyxmmEAV1qtw1vNS7P0uM%3D&se=2022-02-09T02%3A33%3A27Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift [hunk 1]
```diff
@@ -287,4 +290,8 @@ extension PreviewWebKitViewController {
         setWidth(selectedDevice.width)
         webView.evaluateJavaScript(selectedDevice.viewportScript, completionHandler: nil)
     }
+
+    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
+        webView.alpha = 1
```
Comment (mkevins) [inline WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift]: I've tested this out, but I'm still experiencing a flicker for some reason (especially noticeable when switching between `Tablet` and `Desktop` preview modes).

I thought that perhaps this `webView.apha = 1` should be in the `completionHandler` for the JavaScript injection, but that did not help either. Then I tried commenting out the above line, as a "sanity check", expecting the view to be blank, and that surprisingly had no effect :thinking: . I also tried explicitly setting `webView.isOpaque = false` in `viewDidLoad()`, but that _also_ had no effect. At this point, I'm a bit confused why alpha seems to not be respected :man_shrugging: 

If we can't find a reliable way to get alpha working to smooth out the jitter on the Swift side of things, perhaps we could find a work-around with the script injection code? I also wonder if it is worth revisiting the need for the injected script, but that's probably a bit out of scope for this issue.

Tanner, I wonder, do you observe a difference when you comment out the above line? (i.e. `// webView.alpha = 1`)?

Comment (twstokes) [reply WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift]: Thanks @mkevins for giving it a look! That's odd.

> Then I tried commenting out the above line, as a "sanity check", expecting the view to be blank, and that surprisingly had no effect 🤔

I get a blank page as expected when commenting out `webView.alpha = 1`.

You probably saw this, but just in case: This fix currently doesn't apply to previewing a theme on site creation, that's going to be addressed in [a separate issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/17864). Sorry for any confusion there. This PR is only for the areas outside of that:

- Tapping the URL at the top of the "My Site" view.
- Tapping the "View Site" row at the bottom of the "My Site" view.
- Tapping the three dots at the top right and choosing "Preview" while editing a Post or Page.
- (any other non-site creation areas I may have missed)

If we're on the same page and this issue is still occurring, would you mind sharing:
- the theme you were previewing
- the device model and orientation
- the path you took in the app to load the preview

Thanks! 🙇

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift [hunk 2]
```diff
@@ -37,7 +37,18 @@ class PreviewDeviceSelectionViewController: UIViewController {
         }
 
         var viewportScript: String {
-            return String(format: "let parent = document.querySelector('meta[name=viewport]'); parent.setAttribute('content', 'width=%1$d, initial-scale=0');", NSInteger(width))
+            let js = """
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift:40]: I doubt this improves anything related to flickering, but it was an opportunity to clean things up:

- `initial-scale=0` may have been clamped to `0.1` [if I understand the spec correctly](https://www.w3.org/TR/css-device-adapt-1/#min-scale-max-scale).
- [Some themes](https://bennettdemo.wordpress.com) have two viewport meta elements, so we wipe those now before overriding as the previous code would only select one.

**Comment by twstokes** [comment]
👋 @mkevins, to simplify things I've combined the PR targeting the new site template previews with this one, as they'll most likely have the same approach.

I've added a brief fade animation when transitioning alpha states which I feel helps further smooth things over even more. However, if you think we should get a designer's take on that I'm all for it.

**Some findings regarding different approaches:**

I experimented with only updating the viewport meta value rather than doing a full reload, but found that the scroll position would drift and make things a little disorienting. For example, viewing as a Desktop scrolled to the top and then switching to Mobile would land the user somewhere down the page, rather than keep them pinned to the top as expected. `webView.reload()` doesn't appear to have this limitation (even if it does mean a little vertical jerkiness at times), and does a fairly decent job keeping the scroll position where you'd expect.

> I also wonder if it is worth revisiting the need for the injected script, but that's probably a bit out of scope for this issue.

I'm game for that if there's an idea to pursue. 👍

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift (hunk 1 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift]: I've combined the two issues in to this PR, so now it targets both template and site previews.

Comment (mkevins) [reply WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift]: > This fix currently doesn't apply to previewing a theme on site creation,

:man_facepalming: that explains it! I was trying via the Site Creation flow. Will try again with these latest updates. No wonder commenting it out had no effect :laughing: .

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift (hunk 2 above)
Comment (mkevins) [reply WordPress/Classes/ViewRelated/Post/Preview/PreviewDeviceSelectionViewController.swift:40]: Great idea! Also, I love the comments you've added! :+1:

**Comment by mkevins** [comment]
> I experimented with only updating the viewport meta value rather than doing a full reload, but found that the scroll position would drift and make things a little disorienting. For example, viewing as a Desktop scrolled to the top and then switching to Mobile would land the user somewhere down the page, rather than keep them pinned to the top as expected. `webView.reload()` doesn't appear to have this limitation (even if it does mean a little vertical jerkiness at times), and does a fairly decent job keeping the scroll position where you'd expect.

Thank you for exploring this and noting the tradeoffs. I think the closest we could get to "ideal" for this would be to override the default cache controls (not sure if this is possible or reliable, though). Then, we could reduce the delay in loading the content (which as you mentioned should be the same, since it is the same URL).

> > I also wonder if it is worth revisiting the need for the injected script, but that's probably a bit out of scope for this issue.
>
> I'm game for that if there's an idea to pursue. 👍 

I had tried removing the script, and it was still working as expected, hence my ponderings about whether this "hack" is still needed, but that was testing the site creation preview before the PRs were combined :sweat_smile: , so that is moot now. I think we have to live with the JS script after all.

**Review by mkevins — APPROVED** [review]
The code looks good. Also, I tested this (on an iPhone 11, physical device) in the various places where previews can be viewed (page creation flow, site creation flow, etc.) and confirmed that this smooths out the changing between the different viewport modes.

One trade-off that we make with these changes is that we no longer see the progress bar while the page is loading. When I was testing the site creation flow, at least for the site designs I was previewing, the pages were loading quickly. But when loading page creation flow previews (the page templates), switching between the viewport modes had a longer delay, during which the screen was blank with no progress indication.

I tried the following to help mitigate it: start the reload before the fadeout animation completes, and begin where it left off when it finishes loading.

<details>
<summary>Reload during fadeout patch</summary>

```patch
diff --git a/WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift b/WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
index b5a377bf98..c70cd45ed0 100644
--- a/WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
+++ b/WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
@@ -16,9 +16,8 @@ class PreviewWebKitViewController: WebKitViewController {
             if selectedDevice != oldValue {
                 UIView.animate(withDuration: 0.2, animations: {
                     self.webView.alpha = 0
-                }, completion: { _ in
-                    self.webView.reload()
-                })
+                }, completion: nil)
+                webView.reload()
             }
             showLabel(device: selectedDevice)
         }
@@ -295,7 +294,7 @@ extension PreviewWebKitViewController {
     }
 
     func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
-        UIView.animate(withDuration: 0.2) {
+        UIView.animate(withDuration: 0.2, delay: 0, options: .beginFromCurrentState) {
             self.webView.alpha = 1
         }
     }
diff --git a/WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift b/WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift
index cb56df2f75..75b578789c 100644
--- a/WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift	
+++ b/WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift	
@@ -28,9 +28,8 @@ class TemplatePreviewViewController: UIViewController, NoResultsViewHost, UIPopo
             if selectedPreviewDevice != oldValue {
                 UIView.animate(withDuration: 0.2, animations: {
                     self.webView.alpha = 0
-                }, completion: { _ in
-                    self.webView.reload()
-                })
+                }, completion: nil)
+                webView.reload()
             }
         }
     }
@@ -169,7 +168,7 @@ extension TemplatePreviewViewController: WKNavigationDelegate {
     }
 
     func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
-        UIView.animate(withDuration: 0.2) {
+        UIView.animate(withDuration: 0.2, delay: 0, options: .beginFromCurrentState) {
             self.webView.alpha = 1
         }
 
```
</details>

This helped slightly, but I suspect the best way to fully "fix" that would be to somehow do as you originally described and remove the need for further network calls for the same content (a bit out of scope for this PR, imo). Also, if that proves too difficult in the current implementation, another thought would be adding a progress indicator. It would be good to get some design feedback about it.

**Comment by twstokes** [comment]
> But when loading page creation flow previews (the page templates), switching between the viewport modes had a longer delay, during which the screen was blank with no progress indication.

This is a great point @mkevins, and I first learned of that view today so it went untested with these changes. I'm not satisfied with the long blank pause so I'm going to continue working on this. 🙇

**Comment by twstokes** [comment]
It looks like the previous functionality was to hide the progress bar after the initial load, so [I've made the changes here](https://github.com/wordpress-mobile/WordPress-iOS/pull/17861/commits/909c27e4fcbda98436099ece87cc17a8f0990fba) to show it again on size changes. Along with providing the user better feedback on what's happening, it matches the behavior of the "My Site" previews now, adding some consistency.

**Comment by mkevins** [comment]
Tested again, and the progress indicators are an improvement for the page template previews. Thanks for adding that!
