### PR TITLE
Ensure current site is always displayed in Sidebar List

### LINKED ISSUE #23569: The current site may not be displayed in the sidebar
### Expected behavior

We display a maximal number of `SidebarView.displayedSiteLimit` sites on the sidebar. The sites on the sidebar contains (in priority order) the current site, other recently used sites, and the rest of the user's sites.

### Actual behavior

The issue with current implementation is `SidebarView.displayedSiteLimit` is hard-coded as exactly the same as `RecentSitesService.maxSiteCount`. 

The current site may not be displayed if we change `SidebarView.displayedSiteLimit` to be a smaller number.

### Steps to reproduce the behavior

1. Change `SidebarView.displayedSiteLimit` to be a number smaller than `RecentSitesService.maxSiteCount`.
2. Make sure there are at least `RecentSitesService.maxSiteCount` sites in a WP.com account.
3. Create a site named "Zoo" (any name that comes last in alphabetical order) in the WP.com account.
4. Launch the Jetpack app and switch to a few different sites.
5. Select the "Zoo" site.
6. Open the sidebar, and check if "Zoo" is displayed in the sidebar.

### PR DESCRIPTION
**Pull request by pmusolino**
Fixes #23569 

This PR modifies the sidebar site display logic to ensure the currently selected site is always visible, regardless of its position in the recent sites list or alphabetical order.

## Changes Made
- Modified BlogListViewModel.topSites to prioritize displaying the currently selected site
- Implemented three-tier priority system for site display:
1. Current site (always shown)
2. Recent sites (up to display limit)
3. Other sites (alphabetically sorted)
- Added some unit tests

## Testing Instructions
On iPad/simulator
1. Change `SidebarView.displayedSiteLimit` to a number smaller than `RecentSitesService.maxSiteCount`
2. Log into an account with more sites than the display limit
3. Select a site that would normally be pushed out of view (e.g., alphabetically last, you can create a site named "Zoo")
5. Verify that the selected site remains visible in the sidebar

## Screenshot
Simulator Screenshot - iPad Pro 13-inch (M4) - 2025-03-20 at 17 39 04

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/308">25.9</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift [hunk 1]
```diff
@@ -221,21 +222,47 @@ private struct SidebarProfileContainerView: View {
...
+    /// Returns a list of sites to display in the sidebar, ensuring that:
+    /// 1. The current site is always included
+    /// 2. The most recent sites are included up to the display limit
+    /// 3. The sites are sorted alphabetically
     var topSites: [BlogListSiteViewModel] {
-        var topSites = recentSites.prefix(SidebarView.displayedSiteLimit)
-        var encounteredIDs = Set(topSites.map(\.id))
-        for site in allSites where !encounteredIDs.contains(site.id) {
-            if topSites.count >= SidebarView.displayedSiteLimit {
+        var displaySites = [BlogListSiteViewModel]()
```
Comment (kean) [inline WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift:231]: Have you tried the steps from https://github.com/wordpress-mobile/WordPress-iOS/issues/23569? I vaguely remember this code, but I think we opened it just in case. I doubt it's a real issue. `recentSites` always has your most recently selected site as the first item of the array. It's impossible for it to not get displayed. I might be wrong – not entirely sure about this code.

File: WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift [hunk 2]
```diff
@@ -221,21 +222,47 @@ private struct SidebarProfileContainerView: View {
...
+        var encounteredIDs = Set<TaggedManagedObjectID<Blog>>()
+
+        // Ensure the current site is included (if there is one)
+        if let currentSite {
+            displaySites.append(currentSite)
+            encounteredIDs.insert(currentSite.id)
+        }
+
+        // Add recent sites up to the limit
+        for site in recentSites {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift]: (nit) you should be able to merge these two loops in one:  `for site in recentSites + allSites`

File: WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift [hunk 3]
```diff
@@ -23,6 +23,17 @@ final class BlogListViewModel: NSObject, ObservableObject {
...
 
+    weak var sidebarViewModel: SidebarViewModel?
+
+    var currentSite: BlogListSiteViewModel? {
+        guard let sidebarViewModel,
+              case let .blog(selectedBlogID) = sidebarViewModel.selection else {
+            return nil
+        }
+
+        return allSites.first { $0.id == selectedBlogID }
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift]: (nit) I'd probably suggest using `try mainContext.existingObject(with: objectID)` instead of iterating over `allSites`.

File: WordPress/WordPressTest/BlogListViewModelTests.swift [hunk 4]
```diff
@@ -70,4 +70,120 @@ final class BlogListViewModelTests: CoreDataTestCase {
         let displayedNames = viewModel.allSites.map(\.title)
         XCTAssertEqual(displayedNames, [".Org", "51 Zone", "A", "C"])
     }
+
+    func test_topSites_includes_current_site() throws {
```
Comment (kean) [inline WordPress/WordPressTest/BlogListViewModelTests.swift]: (nit) please use camel case. Btw, for new tests (new suites), feel free to use Swift Testing.

**Review by kean — APPROVED** [review]

File: WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift (hunk 1 above)
Comment (pmusolino) [reply WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift:231]: Yes, I followed the steps from the original issue, and I confirm I was able to replicate the issue, especially if you have multiple sites and you create or select a new one that starts with `W` or `Z`.

Screenshot:
Simulator Screenshot - iPad Pro 13-inch (M4) - 2025-03-21 at 14 13 18

File: WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift (hunk 2 above)
Comment (pmusolino) [reply WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift]: Good suggestion f802776192ae2130d511772c4414232b1cca5aea

File: WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift (hunk 3 above)
Comment (pmusolino) [reply WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift]: 👍 implemented here 5bcfca312002e6c794963900ce22e260631f4225

File: WordPress/WordPressTest/BlogListViewModelTests.swift (hunk 4 above)
Comment (pmusolino) [reply WordPress/WordPressTest/BlogListViewModelTests.swift]: Updated here 8aeec842f646a7e832e43cda0cbc0e28aba46d41 👍
