### PR TITLE
Quick Start: Fix task complete event misfiring

### LINKED ISSUE #18947: Quick Start: Task completed analytics event misfiring
### Expected behavior
Task completed event to not fire if the task is already completed or if the task is not in the current list of tasks.

### Actual behavior
Task completed event gets fires for some tasks even if the task is completed or not even part of the current list of tasks

### Steps to reproduce the behavior

1. Enable Quick Start for existing sites
2. Finish all tasks
3. Tap on the site icon
4. Update site icon
5. Once completed, notice that `quick_start_task_completed` event is fired in the console with the task name `site_icon`
6. Create a new post and publish it
7. Once completed, notice that `quick_start_task_completed` event is fired in the console with the task name `publish_post`

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18947

## Description
Fixes an issue where quick start task completed event was misfiring.

### Misfiring

1. Enable Quick Start for existing sites
2. Finish all tasks
3. Tap on the site icon
4. Update site icon
5. Make sure that `quick_start_task_completed` is not fired
6. Create a new post and publish it
7. Make sure that `quick_start_task_completed` is not fired

### Regression

1. Enable Quick Start for new sites
2. Tap on the site icon
3. Update site icon
4. Make sure that `quick_start_task_completed` is fired and the quick start card is updated
5. Create a new post and publish it
6. Make sure that `quick_start_task_completed` is fired and the quick start card is updated

## Regression Notes
1. Potential unintended areas of impact
N/A
2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A
3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift [hunk 1]
```diff
@@ -403,6 +406,28 @@ private extension QuickStartTourGuide {
...
+        let uncompletedTours = allTours.filter { !completedIDs.contains($0.key) }
+        return uncompletedTours
+    }
+
+    /// Check if the provided tour have not yet been completed and is available to complete
+    /// - Parameters:
+    ///   - tour: tour to check
+    ///   - blog: blog to check
+    /// - Returns: boolean, true if the tour is not completed and is available. False otherwise
+    func isTourNotCompleted(tour: QuickStartTour, for blog: Blog) -> Bool {
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: [nit] Wdyt of inverting the method name to `isTourCompleted`? I think the double negative for `!isTourNotCompleted` can be a bit confusing

**Review by momo-ozawa — APPROVED** [review]
Works as described w 1 small nit. Thanks for catching this!

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Renamed it to `isTourAvailableToComplete` to avoid confusion and to avoid changing it's definition 👍 
Done in b3b6bc188fee7997cd1d0f83a8bd22c2a6a91d96
