### PR TITLE
Fix a Core Data concurrency issue when CrashLogging is called from a background thread

### LINKED ISSUE #20836: Calling CrashLogging.logError from a background thread crashes the app
Sentry Issue: [JETPACK-IOS-33R](https://a8c.sentry.io/issues/4198423368/?referrer=github_integration)

```
NSGenericException: *** Collection <__NSCFSet: 0x2820edce0> was mutated while being enumerated.
  File "WPAccount+Lookup.swift", line 52, in WPAccount.lookup
  File "WPAccount+Lookup.swift", line 38, in WPAccount.lookupDefaultWordPressComAccount
  File "WPCrashLoggingProvider.swift", line 53, in WPCrashLoggingDataProvider.currentUser.getter
  File "<compiler-generated>", in WPCrashLoggingDataProvider.currentUser.getter
  File "<compiler-generated>", line 50, in WPCrashLoggingDataProvider
...
(19 additional frame(s) were not displayed)
```

#### Description

The app crashes when calling `CrashLogging.logError` from a background thread. This happens because the `CrashingLogging` uses the main context to fetch a `WPAccount` instance.

```swift
    var currentUser: TracksUser? {
        let context = ContextManager.sharedInstance().mainContext

        guard let account = try? WPAccount.lookupDefaultWordPressComAccount(in: context) else {
            return nil
        }

        return TracksUser(userID: account.userID.stringValue, email: account.email, username: account.username)
    }
```
The app crashes because the main context shouldn't be called from the background thread.

#### Steps to reproduce

I couldn't reproduce this crash, but based on the crash log, it's easy to simulate the issue programmatically. All we have to do is to call `CrashLogging.logError` from a background thread.

1. First, enable `-com.apple.CoreData.ConcurrencyDebug 1` launch argument.
2. Paste the following code at the end of AppDelegate `didFinishLaunchingWithOptions` method.
```swift
UserSettings.userHasForcedCrashLoggingEnabled = true
let crashLogging = Self.crashLogging
DispatchQueue.global().async {
   crashLogging?.logMessage("Hello World")
}
```
3. Build and run the Jetpack app and ensure you are logged in.
4. Expect the app to crash.

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #20836

## Description

This PR resolves an issue causing the app to crash when `CrashLogging.logError` is called from a background thread. More details in #20836.

## Test Instructions

I couldn't find a way to reproduce this crash in production, but it's easy to trigger this issue programmatically.

1. First, enable `-com.apple.CoreData.ConcurrencyDebug 1` launch argument.
2. Paste the following code at the end of AppDelegate `didFinishLaunchingWithOptions` method.
```swift
UserSettings.userHasForcedCrashLoggingEnabled = true
let crashLogging = Self.crashLogging
DispatchQueue.global().async {
   crashLogging?.logMessage("Hello World")
}
```
3. Build and run the Jetpack app and ensure you are logged in.
4. Expect the app to crash.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
None.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift [hunk 1]
```diff
@@ -48,12 +48,11 @@ struct WPCrashLoggingDataProvider: CrashLoggingDataProvider {
     }
 
     var currentUser: TracksUser? {
-        let context = ContextManager.sharedInstance().mainContext
-
-        guard let account = try? WPAccount.lookupDefaultWordPressComAccount(in: context) else {
-            return nil
+        return ContextManager.shared.performQuery { context -> TracksUser? in
```
Comment (jkmassel) [inline WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift]: This is a good approach, though I'll preemptively suggest that we add tests to cover this for both main thread and background thread use?

File: WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+                XCTAssertEqual(user.email, Constants.defaultAccountEmail)
+            }
+        }
+
+        // Then
+        dispatchGroup.notify(queue: .main) {
+            expectation.fulfill()
+        }
+        wait(for: [expectation], timeout: 2)
+    }
```
Comment (salimbraksa) [inline WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift:35]: At first, I wanted to test `CrashLogging.logError` thread-safety instead of just `WPCrashLoggingDataProvider.currentUser`, but that method doesn't return anything to assert the correctness of the event sent.

Accomplishing that would require making changes to `CrashLogging` implementation in `Automattic-Tracks-iOS` repo, which is not the scope of this PR.

File: WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        // When
+        let user = try XCTUnwrap(dataProvider.currentUser)
+
+        // Then
+        XCTAssertEqual(user.userID, "\(Constants.defaultAccountID)")
+        XCTAssertEqual(user.username, Constants.defaultAccountUsername)
+        XCTAssertEqual(user.email, Constants.defaultAccountEmail)
+    }
+
+    func testReadingTrackUserInBackgroundThread() {
```
Comment (crazytonyli) [inline WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift]: Use the same test body as the above function but inside an `async` function probably is enough to cover the scenario where `currentUser` is called from a background thread.

However, if you do want to test concurrency calls to the `currentUser` function, using a `TaskGroup` probably would be easier than dispatch group. Something like this:

``` throws
func testReadingTrackUserInBackgroundThread() async {
    await withTaskGroup(of: Void.self) { group in
        for _ in 1...1000 {
            group.addTask {
                let user = dataProvider.currentUser
                XCTAssert(...)
            }
        }
    }
    // No assertion or waiting needed at the end.
}
```

**Review by crazytonyli — APPROVED** [review]
The app changes look good to me. Only have a suggestion around an unit test.

File: RELEASE-NOTES.txt [hunk 4]
```diff
@@ -11,6 +11,7 @@
 * [**] Block editor: [iOS] Fix dictation regression, in which typing/dictating at the same time caused content loss. [https://github.com/WordPress/gutenberg/pull/49452]
 * [*] Block editor: Display lock icon in disabled state of `Cell` component [https://github.com/wordpress-mobile/gutenberg-mobile/pull/5798]
 * [*] Block editor: Show "No title"/"No description" placeholder for not belonged videos in VideoPress block [https://github.com/wordpress-mobile/gutenberg-mobile/pull/5840]
+* [*] Resolve an issue that was causing the app crash when `CrashLogging.logError` is called from a backgroung thread. [#20846]
```
Comment (twstokes) [inline RELEASE-NOTES.txt]:
```suggestion
* [*] Resolve an issue that was causing the app crash when `CrashLogging.logError` is called from a background thread. [#20846]
```

**Comment by guarani** [comment]
👋 I restarted the failing tests, I hope that helps!
The failures were:

```
Failing tests:
--
  | StatsTests.testInsightsStatsLoadProperly()
  | EditorGutenbergTests.testAddRemoveFeaturedImage()
```

File: WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift [hunk 5]
```diff
@@ -48,12 +54,20 @@ struct WPCrashLoggingDataProvider: CrashLoggingDataProvider {
...
+            }
+            return TracksUser(userID: account.userID.stringValue, email: account.email, username: account.username)
         }
+    }
+}
+
+extension NSManagedObjectContext {
 
-        return TracksUser(userID: account.userID.stringValue, email: account.email, username: account.username)
+    func proxy_save() throws {
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift]: I believe this extension was added unintentionally?

**Review by crazytonyli — CHANGES_REQUESTED** [review]

File: WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift (hunk 5 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift]: @crazytonyli Thats correct, thanks for the catch. 🙇

Comment (salimbraksa) [reply WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift]: Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/20846/commits/119b6d148cf3a2b9b7ed5cb4b8174bac4ed7ffab

**Review by crazytonyli — APPROVED** [review]

File: WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift (hunk 2 above)
Comment (mokagio) [reply WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift:35]: Opened https://github.com/Automattic/Automattic-Tracks-iOS/issues/259 to track this

File: WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+        // Then
+        XCTAssertEqual(user.userID, "\(Constants.defaultAccountID)")
+        XCTAssertEqual(user.username, Constants.defaultAccountUsername)
+        XCTAssertEqual(user.email, Constants.defaultAccountEmail)
+    }
+
+    func testReadingTrackUserInBackgroundThread() async {
+        let dataProvider = self.makeCrashLoggingDataProvider()
+        await withThrowingTaskGroup(of: Void.self) { group in
+            for _ in 1...1000 {
```
Comment (mokagio) [inline WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift:26]: What is the rationale for adding 1,000 tasks? Is there something about the amount of tasks that affects the test behavior?

Comment (salimbraksa) [reply WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift:26]: @mokagio Running 1000 tasks concurrently in the test is an attempt to reveal potential thread safety issues. The choice of 1000 is arbitrary; it's large enough to stress the API but allows the test to be completed in a reasonable time.
