### PR TITLE
AccountSettings: Allow nil selected blog ID

### LINKED ISSUE #6956: Account Settings: Crash when editing primary site
There's a crash in `AccountSettingsController` when editing the primary site. I suspect either we don't have an `AccountSettings` or for some reason the `primarySiteID` can't be cast to an `NSNumber`.

```
Crashed: com.apple.main-thread
0  WordPress                      0x1003cc048 AccountSettingsController.(editPrimarySite(AccountSettings?, service : AccountSettingsService) -> (ImmuTableRow) -> UIViewController).(closure #1) (AccountSettingsViewController.swift:144)
1  WordPress                      0x1003ce8a8 partial apply for AccountSettingsController.(editPrimarySite(AccountSettings?, service : AccountSettingsService) -> (ImmuTableRow) -> UIViewController).(closure #1) (AccountSettingsViewController.swift)
2  WordPress                      0x100378dcc SettingsController.(insideNavigationController((ImmuTableRow) -> UIViewController) -> (ImmuTableRow) -> UIViewController).(closure #1) (SettingsCommon.swift:9)
3  WordPress                      0x1003f58b8 _TPA__TTSg5C9WordPress23ImmuTableViewControllerS0_S_18ImmuTablePresenterS____TFFe9WordPressRxCSo16UIViewControllerxS_18ImmuTablePresenterrS1_7presentFFPS_12ImmuTableRow_S0_FPS2__T_U_FPS2__T_ (ImmuTableViewController.swift:23)
4  WordPress                      0x10054f024 specialized ImmuTableViewHandler.tableView(UITableView, didSelectRowAt : IndexPath) -> () (ImmuTable.swift:301)
5  WordPress                      0x10054c428 @objc ImmuTableViewHandler.tableView(UITableView, didSelectRowAt : IndexPath) -> () (ImmuTable.swift)
6  UIKit                          0x18eb50484 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1424
7  UIKit                          0x18ec00f34 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 268
8  UIKit                          0x18ecb3fdc _runAfterCACommitDeferredBlocks + 292
9  UIKit                          0x18eca5d50 _cleanUpAfterCAFlushAndRunDeferredBlocks + 560
10 UIKit                          0x18ea150b4 _afterCACommitHandler + 168
11 CoreFoundation                 0x188b1a0c0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
12 CoreFoundation                 0x188b17cf0 __CFRunLoopDoObservers + 372
13 CoreFoundation                 0x188b18180 __CFRunLoopRun + 1024
14 CoreFoundation                 0x188a462b8 CFRunLoopRunSpecific + 444
15 GraphicsServices               0x18a4fa198 GSEventRunModal + 180
16 UIKit                          0x18ea8d7fc -[UIApplication _run] + 684
17 UIKit                          0x18ea88534 UIApplicationMain + 208
18 WordPress                      0x10005fb78 main (main.m:5)
19 libdispatch.dylib              0x187a295b8 (Missing)
```

Affecting <= WPiOS 7.2.

### PR DESCRIPTION
**Pull request by frosty**
Fixes #6956. We were getting a crash in Account Settings (see original issue) when editing the primary site. This PR just makes the optional handling around presenting and dismissing the blog selector a little more careful, by removing some force unwraps.

To test:

* Ensure you can still edit / change your primary blog correctly.
* Perhaps change the code to pass `nil` into the blog selector or to return `nil` from its success block and check that nothing breaks.

Needs review: @koke

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m [hunk 1]
```diff
@@ -45,7 +45,7 @@ - (instancetype)initWithSelectedBlogObjectID:(NSManagedObjectID *)objectID
     return self;
 }
 
-- (instancetype)initWithSelectedBlogDotComID:(NSNumber *)dotComID
+- (instancetype)initWithSelectedBlogDotComID:(nullable NSNumber *)dotComID
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m]: Do you also need the nullability in the implementation file?

**Comment by frosty** [comment]
Thanks!

File: WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m (hunk 1 above)
Comment (frosty) [inline WordPress/Classes/ViewRelated/Blog/BlogSelectorViewController.m]: Damn, missed this comment. No, I don't think it's necessary.
