### PR TITLE
Issue/6999 offline posts not saved

### LINKED ISSUE #6999: Posts are lost if published while offline
### Expected behavior

If I am offline when I publish a post (either in airplane mode or with a flaky connection) I expect the app to save the post as a local draft.

### Actual behavior

The post-post screen appears (which is confusing as the post wasn't successfully published) and I see the error "Error occurred during publishing." When I dismiss the post-post screen, I can't find the post saved anywhere in the app. It's completely lost.

### Steps to reproduce the behavior

1. Go offline (e.g. put the device in airplane mode with wifi off).
2. Start a new post with a title and content.
3. Tap Post.
4. After the post-post screen and error appear, tap "Done" to return to the post list.
5. Check each post status filter (Published, Draft, etc.).

Result: The post is completely gone.

(Tested with both the Visual and Aztec editors and confirmed the same behavior.)

##### Tested on iPhone 6, iOS 10.3, WPiOS 7.3.0.20170405

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #6999 

To test:
 - Put your device in offline mode
 - Start a new post
 - Write some content.
 - Tap on the publish button
 - Check that an error message shows up
 - The post after post screen doesn't appear.
 - The post shows up in the draft list and no content was lost.

Needs review: @koke

### CODE REVIEW

File: WordPress/Classes/Services/PostService.m [hunk 1]
```diff
@@ -210,6 +210,11 @@ - (void)uploadPost:(AbstractPost *)post
             Post *postInContext = (Post *)[self.managedObjectContext existingObjectWithID:postObjectID error:nil];
             if (postInContext) {
                 postInContext.remoteStatus = AbstractPostRemoteStatusFailed;
+                // If the post was not created on the server yet we convert the post to a local draft post with the current date.
+                if (postInContext.postID.intValue == -1 && postInContext.date_created_gmt == nil) {
```
Comment (koke) [inline WordPress/Classes/Services/PostService.m]: We have a more semantic `AbstractPost.hasRemote()` for checking if it's local.
