### PR TITLE
Issue/5726: Plan list cells not deselecting after modal dismiss

### LINKED ISSUE #5726: Plans: Cell not deselecting after modal dismiss
### Expected behavior

The cell should deselect after dismissing the modal view.

### Actual behavior

The cell stays selected.

### Steps to reproduce the behavior

1. On iPad, select a plan cell.
2. Dismiss the modal view.
3. Cell remains selected.

##### Tested on [device], iOS [version], WPiOS [version]
iPad only, does not reproduce on iPhone.

plans-selection

### PR DESCRIPTION
**Pull request by frosty**
Fixes #5726 

See original issue for description of issue. I've fixed the issue by deselecting the row when the modal is presented, as there's no simple way to tell when the modal is dismissed (`viewWill/DidAppear` doesn't get called) – we'd have to implement a delegate or somesuch which seems like overkill.

Needs review: @kurzee

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift [hunk 1]
```diff
@@ -119,6 +119,18 @@ final class PlanListViewController: UITableViewController, ImmuTablePresenter {
     func footerTapped() {
         footerTapAction?()
     }
+
+    // MARK: - ImmuTablePresenter
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift]: 🚔 🚔 🚔 🚔 Trailing white space violation 🚔 🚔 🚔 🚔

File: WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift [hunk 2]
```diff
@@ -119,6 +119,18 @@ final class PlanListViewController: UITableViewController, ImmuTablePresenter {
...
     }
+
+    // MARK: - ImmuTablePresenter 
+
+    func present(controllerGenerator: ImmuTableRowControllerGenerator) -> ImmuTableAction {
+        return {
+            [unowned self] in
+            let controller = controllerGenerator($0)
+            self.presentViewController(controller, animated: true, completion: { _ in
+                self.tableView.deselectSelectedRowWithAnimation(true)
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift]: Can we target iPad here? We lose the `clearsSelectionOnViewWillAppear` on the iPhone by forcing here.

File: WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift (hunk 1 above)
Comment (frosty) [inline WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift]: 😱

**Comment by kurzee** [comment]
@frosty all good a part from the minor comments! :shipit:

**Comment by frosty** [comment]
Thanks @kurzee! I fixed up those issues, and also added in a comment explaining why the code's there in the first place.
