### PR TITLE
Fixes Selected Row Glitch

### LINKED ISSUE #3342: Notifications: Unread Notifications Glitch
#### Steps:
1. Launch WPiOS
2. Open the Notifications tab
3. Tap over any unread notification
4. Swipe from the left corner of the screen, towards the right corner.

#### Results:
The unread cell will show up with its "unread" color, but the contents will not be visible.

[Sample video here](https://cloudup.com/cMVA3RZG95L).

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #3342

@aerych may i bother you (yet again) with a review?.

Thank you!!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m [hunk 1]
```diff
@@ -522,6 +522,7 @@ - (void)controller:(NSFetchedResultsController *)controller
         {
             [self invalidateCachedRowHeightAtIndexPath:indexPath];
             [self.tableView reloadRowsAtIndexPaths:@[indexPath] withRowAnimation:self.updateRowAnimation];
+            self.indexPathSelectedAfterUpdates = self.tableView.indexPathForSelectedRow;
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m]: Could you help me understand the reason for this line? It looks like it would conflict with the logic under the `NSFetchedResultsChangeMove` block so I'm not sure its a good change.

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m]: I've caught a couple scenarios in which an entity might get refreshed multiple times, and the selected row was getting lost.

You mean, it might conflict with the logic in `NSFetchedResultsChangeMove`, if we get multiple changes in batch right?. (Which is definitely a scenario i missed in my tests!!!!!)

Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m]: > if we get multiple changes in batch right?

Yeppers!

Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.m]: An alternative approach: https://gist.github.com/aerych/04dd5115aea42ec7ff4f

**Comment by jleandroperez** [comment]
@aerych thanks for the feedback!. Updated with the very same snippet you sent me, and it's working great (*thank you!!*).

**Comment by aerych** [comment]
I lolled when I saw your commit message :)
Looks good @jleandroperez !
:shipit:

**Comment by jleandroperez** [comment]
@aerych thank you Eric!
