### PR TITLE
Share extension: Associate Post and uploaded Media items

### LINKED ISSUE #9070: Share Extension not associating uploaded photo Media items with the post
apologies if this is the wrong place to post this - I've tried to post it on ios.forums.wordpress.org but get ngix 404 errors when submitting…

### Expected behavior

Photos uploaded using the iOS Share Extension should be uploaded as Media items (they are), added to a blog post as content (they are), and the Media item should be associated with the blog post (this is not happening). In my testing, the photo is successfully uploaded as Media, but that Media item isn't associated/linked to the blog post (as seen in the "Uploaded To" field of the Media item).

### Actual behavior

When I try to use the Share Extension to share a photo from Photos (select a photo, click the box/arrow Share icon, then select WordPress), the post gets published but the uploaded image isn't associated with the post in the Media section. If I edit the post using the web interface, remove the image, and re-add it manually, it's properly associated with the Media item.

The basic post-photo-to-blog functionality works, but without the additional metadata to associate the uploaded image and Media item with the post, plugins like YD Recent Images http://www.yann.com/en/wp-plugins/yd-recent-images can't generate the list of recently published photos because they rely on Media associations to posts.

For example - my blog has a "Photos" page (using YD Recent Images), to list the most recent 100-or-so photos.

https://darcynorman.net/photos/

Photos published by the WordPress iOS app don't show up on that page, but do show up normally on the post category page:

https://darcynorman.net/type/image/

##### Tested on [device], iOS [version], WPiOS [version]

Running the latest WordPress for iOS 9.6.1, connecting to self-hosted WordPress site running 4.9.5

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #9070 

Associate Media items with Post after a post has been successfully created from the share extension.

To test:
1. Create a post from the Share extension. Open Photos, select an image, share it to WordPress, and compose a Post
2. Navigate in a browser to the blog's media library and check that the image that was just uploaded is associated to the post that was just created.

In my case, for a self-hosted blog, it looks something like this:
screen shot 2018-06-05 at 1 33 06 pm

### CODE REVIEW

**Comment by ctarda** [comment]
Thanks @mindgraffiti for the review. I have pushed another commit that incorporates @bummytime patch, as discussed on slack. It looks like it works on my end, both when using the Share extension or when sharing as a draft, but let's see how it goes!

File: WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift [hunk 1]
```diff
@@ -226,6 +227,70 @@ import WordPressFlux
...
+    private func updateMedia(postID: Int64?, siteID: Int64, onComplete: CompletionBlock?) {
+        guard let postID = postID else {
+            return
+        }
+
+        guard let service = mediaService(siteID: siteID) else {
+            return
+        }
+
+        coreDataStack.saveContext()
```
Comment (bummytime) [inline WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift]: I think we can remove this `saveContext()` call because we are not mutating any CD objects at this point and  it's also called on Line 214 above ☝️

**Comment by ctarda** [comment]
Thanks a lot for your help @bummytime and @mindgraffiti !

I pushed one more commit to remove one extra save of the context, as pointed out in one of the comments. Merging as soon as the build completes!

**Comment by alisterscott** [comment]
I tested this as part of WPiOS 10.3.0.20180618 and I couldn't see the Uploaded To attribute in wp-admin for both a simple and Jetpack site:

screen shot 2018-06-20 at 1 36 39 pm

Am I doing something wrong?

**Comment by ctarda** [comment]
Hi @alisterscott Thanks for testing this. I'll ping you on slack
