### PR TITLE
Invite People: Private Sites

### LINKED ISSUE #5676: People: Private sites should not be able to invite followers
### Expected behavior

When sending an invitation for a private site, the roles should be:
- Viewer
- Admin
- Editor
- Author
- Contributor

On a public site, instead of "Viewer" there is the option to invite someone as a "Follower." However, to follow a private site you must first be invited as a viewer, so the only invite option is Viewer. (This is how invites work in Calypso and WP Admin.)
### Actual behavior

When sending an invitation for a private site, the available roles are:
- Viewer
- **Follower**
- Admin
- Editor
- Author
- Contributor

Follower should not be an option for invites to a private site.
### Steps to reproduce the behavior
1. Open to the app and go to My Sites > Select a private site > People.
2. Tap the plus sign in the top right to invite a new user.
3. Tap "Role" to select the role. Result: You see both Follower and Viewer as possible roles.
4. Select "Follower."
5. Enter a username or email to invite.
6. Send the invitation. Result: The user receives an invitation to become a Viewer.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR updates the list of available roles to invite people, whenever the target blog is set to Private.

Fixes #5676 

### To test:
1. Open `My Sites` tab and pick up any of your testing blogs
2. Set its visibility to Private (`Settings` > `Privacy` > `Private`)
3. Open the People Management UI (`My Sites` > `Blog` > `People`)
4. Tap the plus sign in the top right to invite a new user.

Verify that (A) the preselected role is `Viewer`, and (B) if you attempt to change the role, `Follower` doesn't show up in the list.

Needs review: @diegoreymendez 
Diego, may i bug you with a quick PR?

Thanks!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift [hunk 1]
```diff
@@ -363,6 +368,14 @@ private extension InvitePersonViewController {
         // By default, Send is disabled
         navigationItem.rightBarButtonItem?.enabled = false
     }
+
+    func setupDefaultRole() {
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift]: I was thinking that maybe we can replace this method with a property initializer.  It's pretty minor but I believe that could be a nice change.  Thoughts?

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift]: Problem is: you need the `blog` to be already set. There is no real warranty that it will be available, whenever the property initializer runs.

(That's the reasoning behind this method!)

**Comment by jleandroperez** [comment]
Thanks Diego!!
