### PR TITLE
Web previews: Abide by safe areas when a toolbar is shown

### LINKED ISSUE #16106: Reader: In-app browser preview hides/cuts important elements
When you preview a post from the Reader using the 🌏 icon, you get a preview of the site itself. However, some elements (especially fixed ones like cookie-related banners) are hidden behind the bottom bar and cannot be used.

### Expected behavior
To be able to access all the elements from the in-app preview.

### Actual behavior

The bottom overlay bar gets on top of important elements like the button to accept/deny cookies:

https://zerowastechef.com/ | https://rafaelfunchal.com.br/ | https://toddhensonphotography.com/
------------ | ------------- | -------------
 |  | 

### Steps to reproduce the behavior

1. Open the Reader
2. Open a post from a site with one of these bottom banners. Examples: https://toddhensonphotography.com/blog, https://zerowastechef.com/, or https://rafaelfunchal.com.br/
3. Tap the globe icon to preview the site
4. Check the bottom

##### Tested on iPhone 7, iOS 14.4, WPiOS 16.8.0.4

Reported also in 3826878-zen

### PR DESCRIPTION
**Pull request by kduncanwelke**
Fixes #16106 

The stack view that contains the web view has simply been pinned to the safe area on the top and bottom, and then centered, instead of pinning the stack view just to the middle of the view. 

To account for the change in presence of the toolbar, the bottom constraint for the stack view is now saved in a variable, and is deactivated when the WebKitViewController's configureToolbar() method hits the guard statement. This statement is reached when the web view is not in a secure mode, which coincides with the bottom toolbar remaining unconfigured.

This prevents the overlap that existed before that caused content at the bottom of the screen to be cut off. Visit other areas (listed below) that WebKitViewController is used, and observe that they are virtually unchanged.

### Reader
- Open reader.
- Search for a site such as [zerowastechef](https://zerowastechef.com/), then visit it, and choose a post from that site to view. 
- Hit the globe icon at the top of the view to view the post in the reader browser. 
- **See that now the cookie acceptance message is fully visible at the bottom of the page, and is not cut off by the toolbar.** 

| Before Portrait | Before Landscape |
| ------ | --------|
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 06 14 | Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 06 32 |

| After Portrait | After Landscape |
| - | - |
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 14 59 11 | Simulator Screen Shot - iPhone 11 - 2022-03-25 at 14 59 48 |

### Site Preview
- From My Site area hit site name 
- **Expect no changes**

| Before |
| - |
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 07 34 |

| After |
| - |
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 01 02 |

### Post Preview
- From My Site hit posts, then view on a post
- **Expect no changes**

| Before | After |
| - | - |
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 08 01 | Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 01 44 |

### Theme Preview
- From My Site hit themes, then choose one
- **Expect no changes**

| Before |
| - |
| Simulator Screen Shot - iPhone 11 - 2022-03-25 at 15 18 47 |

| After |
| - |
| Simulator Screen Shot - iPhone 11 - 2022-04-06 at 15 07 23 |

## Regression Notes
1. Potential unintended areas of impact
Any place the WebKitViewController is used to display a web view that is not natively displayed via an open-in-Safari link. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested portrait and landscape modes on multiple areas WebKitViewController is used, including the reader, site preview, post preview, and theme preview. 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 1]
```diff
@@ -187,7 +187,7 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
 
         NSLayoutConstraint.activate(edgeConstraints)
 
-        view.pinSubviewAtCenter(stackView)
+        view.pinSubviewToSafeArea(stackView)
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift]: This is a great idea and I think we're possibly on the right track to abide by the Safe Areas (especially the bottom), however, I've noticed a couple regressions this change may introduce.

### Reader

Visually it'd be best to retain horizontal edge-to-edge constraints so that the web's background can be shown behind Safe Areas.

|Before|After|
|------|-----|
| Reader - Before | Reader - After |

### Site Previews

Site previews appear to be affected since they also use the `WebKitViewController` class. On the My Site view, either tap the URL at the top or scroll to the bottom and tap View Site to see a preview.

|Before|After|
|------|-----|
| Site Preview - Before | Site Preview - After |

**Review by twstokes — CHANGES_REQUESTED** [review]
👋 @kduncanwelke! Thank you for contributing to WordPress for iOS!

I've done some testing and have left a comment in my review. Since this change has the potential to affect multiple areas of the app that use the `WebKitViewController` class, we should look for any other views that utilize it or its subclasses (such as `PreviewWebKitViewController`) and test them as well.

It would be great to compile those views to test and add them to the "Testing" portion of this PR. [This PR may be a good example](https://github.com/wordpress-mobile/WordPress-iOS/pull/17861).

I also think this change will deserve [a release note](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/RELEASE-NOTES.txt)!

Thank you. 😄

File: WordPress/Classes/Utility/WebKitViewController.swift (hunk 1 above)
Comment (kduncanwelke) [reply WordPress/Classes/Utility/WebKitViewController.swift]: Thank you for the review! It looks like it's not as simple as expected; I will investigate and see what I can do!

Comment (kduncanwelke) [reply WordPress/Classes/Utility/WebKitViewController.swift]: I have fixed the stretched site preview and tested and included screenshots for multiple areas of impact, and added a release note. 👏🏻

File: RELEASE-NOTES.txt [hunk 2]
```diff
@@ -14,6 +14,7 @@
 * [*] Block Editor: Add GIF badge for animated GIFs uploaded to Image blocks [https://github.com/WordPress/gutenberg/pull/38996]
 * [*] Block Editor: Small refinement to media upload errors, including centering and tweaking copy. [https://github.com/wordpress-mobile/gutenberg-mobile/pull/4597]
 * [*] Block Editor: Fix issue with list's starting index and the order [https://github.com/WordPress/gutenberg/pull/39354]
+* [*] Reader: Fixed a bug that caused cut off content in reader web view [#16106]
```
Comment (twstokes) [inline RELEASE-NOTES.txt]: We'll need to move this up to the 19.7 milestone section. If you re-sync with `trunk` you should see [this section](https://github.com/wordpress-mobile/WordPress-iOS/blob/9fd115357c3c801dc3945034a88959b668ba5621/RELEASE-NOTES.txt#L3). Thanks!

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 3]
```diff
@@ -187,7 +187,13 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
...
         NSLayoutConstraint.activate(edgeConstraints)
 
-        view.pinSubviewAtCenter(stackView)
+        // we are pinning the top and bottom of the stack view to the safe area to prevent unintentionally hidden content/overlaps (ie cookie acceptance popup) then let the rest stay centered to allow the reader website background to occupy all available space, and to allow the site preview to show a user's own site without stretching it
+        let safeArea = self.view.safeAreaLayoutGuide
+
+        stackView.topAnchor.constraint(equalTo: safeArea.topAnchor).isActive = true
+        stackView.bottomAnchor.constraint(equalTo: safeArea.bottomAnchor).isActive = true
+        stackView.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
+        stackView.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift]: 👋 @kduncanwelke - this looks really good! Thanks for your work so far.

This screenshot got me thinking:



That little gray bar at the bottom is from the UIStackView obeying the bottom safe area. In cases like these we may prefer to allow the web content to go behind the Home Indicator, so I wonder if we can:

1. Use the view's safe area bottom constraint when there's a toolbar
2. Use the view's bottom constraint when there isn't one

This will add a little bit of complexity, but may give us the best of both worlds:

1. Remove the `centerYAnchor` constraint, but keep the `centerXAnchor`. I can't think of a reason why it's needed, but I may be wrong here. It seems that if the top and bottom anchors are set at all times we don't need it. I do understand why we need the `centerXAnchor`, and that's for when the UIStackView's width gets resized.
3. Create a property that stores our safe area bottom constraint so that we can alter its priority depending on if there's a toolbar or not.
4. On `viewWillLayoutSubviews()` detect whether or not the toolbar is showing, and decided what priority to set the bottom constraint to.

[I've pushed up a branch](https://github.com/wordpress-mobile/WordPress-iOS/compare/temp/webkitvc-safe-areas) of what I'm thinking, but would love to hear your thoughts. Thanks!

File: RELEASE-NOTES.txt (hunk 2 above)
Comment (kduncanwelke) [reply RELEASE-NOTES.txt]: I'll fix this, thanks!

File: WordPress/Classes/Utility/WebKitViewController.swift (hunk 3 above)
Comment (kduncanwelke) [reply WordPress/Classes/Utility/WebKitViewController.swift]: I'll try out these changes and see if I can get that bar to disappear - I'd like to see this through to completion for the experience and because of the time invested so far. Thanks for checking it over again!

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 4]
```diff
@@ -299,6 +309,8 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
         navigationController?.isToolbarHidden = secureInteraction
 
         guard !secureInteraction else {
+            // if not a secure interaction/view, no toolbar is displayed, so deactivate constraint pinning stack view to safe area
+            stackViewBottomAnchor?.isActive = false
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift:313]: I like this method of toggling the anchor much better!

**Review by twstokes — APPROVED** [review]
This looks great to me @kduncanwelke! 🥳 🎉 

I'm running our [CI against your changes](https://github.com/wordpress-mobile/WordPress-iOS/pull/18347) in a temporary branch, and those will need to pass before we merge this PR. I do see there's a merge conflict related to the release notes. Would you mind resolving that?

Thank you! And thanks for contributing!

| Portrait After | Landscape After |
| ------------- | -----------------|
| After - Page Preview Mobile Portrait | After - Page Preview Mobile Landscape |
| After - Reader Portrait | After - Reader Landscape |
| After - Site Creation Preview Portrait | After - Site Creation Preview (rotated to) Landscape |
| After - Site Preview Desktop Portrait | After - Site Preview Desktop Landscape |
| After - Site Preview Mobile Portrait | After - Site Preview Mobile Landscape |
| After - Site Preview Tablet Portrait | After - Site Preview Tablet Landscape |
| After - Theme Preview Portrait | After - Theme Preview Landscape |

#### Constraint in action
Constraint in action

File: WordPress/Classes/Utility/WebKitViewController.swift (hunk 4 above)
Comment (kduncanwelke) [reply WordPress/Classes/Utility/WebKitViewController.swift:313]: Thanks! 😊

**Comment by twstokes** [comment]
Tests passed in the [PR to trigger CI](https://github.com/wordpress-mobile/WordPress-iOS/pull/18347) and non-required test failures appear to be unrelated to these changes. Merging PR. 🎉

**Comment by twstokes** [comment]
@tiagomar I'm writing this comment as a reminder for when we get to 19.7 testing I can create the steps. 👍

**Comment by tiagomar** [comment]
@twstokes I have just published the Call for Testing but let me know if you want to include steps for testing this. Also, the release note is pointing to #18127, do we want to point to this one instead?

**Comment by twstokes** [comment]
> @twstokes I have just published the Call for Testing but let me know if you want to include steps for testing this. Also, the release note is pointing to #18127, do we want to point to this one instead?

Great! I'll get some steps written up today.

> Also, the release note is pointing to #18127, do we want to point to this one instead?

Good catch on the release note. I can submit a PR to get that updated to point to this one. 👍

**Comment by twstokes** [comment]
> @twstokes I have just published the Call for Testing but let me know if you want to include steps for testing this. Also, the release note is pointing to #18127, do we want to point to this one instead?

@tiagomar I've done two things:
- [Created a PR for updating the release note](https://github.com/wordpress-mobile/WordPress-iOS/pull/18401)
- Updated this PR's description to aid with testing (mostly just put the images in tables)

**Comment by mokagio** [comment]
@kduncanwelke once again, thank you so much for your help with this 🙇‍♂️ 

I hope you'll be happy to know that your fix has started rolling out to the global WordPress iOS users with version 19.7. We use Apple's _Phased Release_ feature; in a few days, it will be available to everyone using the app.

Thanks! 🙌
