### PR TITLE
My Site Dashboard: show drafts and/or scheduled cards if needed

### LINKED ISSUE #18100: [MSD] First scheduled post is not shown in posts card
### Expected behavior
If the user has no posts at all, and adds a new scheduled post, it should be shown in the posts card.

### Actual behavior
Instead, this scheduled post is briefly shown, but then gets replaced with “Create your first post” again:

https://user-images.githubusercontent.com/73365754/157216923-951d0b96-059c-4938-be0c-f291bf853f09.MP4

### Steps to reproduce the behavior
1. Make sure MSD is enabled
2. Create a new account and new site
3. In this site, switch to `Home`, and make sure you see posts card in “Create your first post” mode
4. Tap it, and create a new scheduled post
5. The posts card briefly shows the scheduled post, but then gets replaced with “Create your first post” again.

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #18100 and #18122

### To test

Make sure to have the MSD flag enabled, then:

#### Scheduling a post

1. Open the dashboard for a blog with no posts at all
2. Create a new post from the FAB
3. Scheduled it
4. ✅ Check that the scheduled card appears on the dashboard

#### Creating a draft while showing only scheduled posts

1. Open the dashboard for a blog with only scheduled posts (the last one fits into this category)
2. Create a new post from the FAB
3. Tap X > Save Draft
4. ✅ Make sure the drafts card appear

#### Offline: creating a draft while showing only scheduled posts

1. Make sure to have a dashboard showing only scheduled posts
2. Go offline
3. Create a new post from the FAB
4. Tap X > Save Draft
4. ✅ Make sure the drafts card appear
5. Close the app
6. Reopen it again
7. ✅ Make sure the drafts card appear with your local post

~Ps.: for this case, if you close the app and reopen it again the drafts won't be shown. In order to fix that we need to check if drafts exist before deciding to show the card or not. Given the cost — and this being an edge case — I didn't tackle this issue here.~

An easier to solve this issue might be to *always* show the draft card in case the device is offline.

#### Offline: no posts at all

1. Make sure to have a dashboard with no posts at all
2. Go offline
3. Create a new post from the FAB
4. Tap X > Save Draft
4. ✅ Make sure the drafts card appear

## Regression Notes
1. Potential unintended areas of impact
Dashboard

3. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tested different posts flow

4. What automated tests I added (or what prevented me from doing so)
-

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@momo-ozawa @hassaanelgarem I tried displaying the scheduled card right away, given we do not necessarily need to update the Dashboard to show it. However, I had issues when displaying it:

https://user-images.githubusercontent.com/7040243/159577029-77ba8a82-8631-4233-94da-d4a9fcf81808.mp4

You can see at the very end that the scheduled cards appear, but almost at the same time the draft cards changes to the prompt, then the cell layout isn't recalculated and it looks like the scheduled posts aren't there (while they are, just outside of the view).

I feel that the fix here isn't the best from a UX perspective (you can see the screen jumping here and there), however it does solve the issue.

Let me know if you have any suggestions. :)

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift [hunk 1]
```diff
@@ -117,7 +118,12 @@ final class BlogDashboardViewController: UIViewController {
     }
 
     private func addQuickStartObserver() {
-        NotificationCenter.default.addObserver(self, selector: #selector(toggleQuickStart), name: .QuickStartTourElementChangedNotification, object: nil)    }
+        NotificationCenter.default.addObserver(self, selector: #selector(loadCardsFromCache), name: .QuickStartTourElementChangedNotification, object: nil)
+    }
+
+    private func addShowScheduledCardsObserver() {
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: What do you think of calling this `addUpdateDashboardObserver()`? Since the `.updateDashboad` notification is posted for both drafts and scheduled posts
```suggestion
    private func addUpdateDashboardObserver() {
```

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift [hunk 2]
```diff
@@ -14,13 +14,17 @@ import UIKit
 /// Eg.: The API might return that the user has no posts at all but
 /// they actually have a draft saved locally. In this case we show the drafts.
 class DashboardPostsCardCell: UICollectionViewCell, Reusable {
-    private var cardFrameView: BlogDashboardCardFrameView?
+    /// THe first card frame view on this cell
+    private var firstCardFrameView: BlogDashboardCardFrameView?
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift:18]: Do we still need this private var? Can we delete this since now the `cardFrameView` is being passed as an argument in the `PostsCardViewControllerDelegate` methods?

Slack ref: p1646221454174039/1646188721.858469-slack-C0290FLA0RM

**Review by momo-ozawa — COMMENTED** [review]
I tested the flows and it works as described. Left a couple of comments

Scheduling a post | Creating a draft while showing only scheduled posts | Offline: creating a draft while showing only scheduled posts | Offline: no posts at all
-- | -- | -- | --
Simulator Screen Shot - iPhone 13 - 2022-03-24 at 11 47 48 | Simulator Screen Shot - iPhone 13 - 2022-03-24 at 11 49 17 | Simulator Screen Shot - iPhone 13 - 2022-03-24 at 11 51 59 | Simulator Screen Shot - iPhone 13 - 2022-03-24 at 11 54 14

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift (hunk 1 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: Done in 411536c5463a17a6285c9d37649ac26b53c53e72

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift (hunk 2 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift:18]: We do! :(

It's used by the dequeuing logic. I can probably refactor that to have the VC reference instead but given that the changes on this PR are already extensive I prefer to not include more stuff. I added as a "nice to have" on our board.

File: WordPress/Classes/Services/PostCoordinator+Dashboard.swift [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+        NotificationCenter.default.post(name: .showDraftsCard, object: nil)
+    }
+}
+
+extension NSNotification.Name {
+    /// Fired when a post is scheduled
+    static let showScheduledCard = NSNotification.Name("ShowScheduledCard")
+
+    /// Fired when a draft is saved
+    static let showDraftsCard = NSNotification.Name("ShowDraftsCard")
```
Comment (hassaanelgarem) [inline WordPress/Classes/Services/PostCoordinator+Dashboard.swift]: [nit] I feel the notification name should be descriptive to what happened, not the action that should be taken after firing the notification. What do you think?
```suggestion
    static let NewPostScheduled = NSNotification.Name("NewPostScheduled")

    /// Fired when a draft is saved
    static let NewDraftPostSaved = NSNotification.Name("NewDraftPostSaved")
```

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift [hunk 4]
```diff
@@ -230,3 +236,8 @@ extension BlogDashboardViewController {
         static let cellSpacing: CGFloat = 20
     }
 }
+
+extension NSNotification.Name {
+    /// Updates the dashboard
+    static let updateDashboard = NSNotification.Name("UpdateDashboard")
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: [nit] If you agree on the previous comment then you can change this as well 😊

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+    /// drafts and/or scheduled posts, however the user might have
+    /// they locally.
+    /// This parser basically looks in the local content and fixes the data
+    /// if needed.
+    func parse(_ postsDictionary: NSDictionary, for blog: Blog) -> NSDictionary {
+        guard let posts = postsDictionary.mutableCopy() as? NSMutableDictionary else {
+            return postsDictionary
+        }
+
+        if !posts.hasDrafts {
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift:22]: [?] My understanding here that we're mssing the case where the API returns draft posts but the user has extra draft posts locally. Or am I missing something?

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift [hunk 6]
```diff
@@ -92,6 +99,7 @@ extension DashboardPostsCardCell: BlogDashboardCardConfigurable {
 
         if hidesHeader {
             frame.hideHeader()
+            childViewController.showNextPostPrompt()
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift:102]: [?] Why are we doing this? Can we maybe add a comment here to clarify this? 🙏

**Review by hassaanelgarem — COMMENTED** [review]
All scenarios work as expected! I left a few comments. Also, there's one scenario that feels a little off to me:
With one scheduled post and one draft post:

1. Go into the posts list
2. Trash the scheduled post
3. Go back to the dashboard
4. Observe the cards. (Create your first post card is shown for a few seconds then disappears)   

https://user-images.githubusercontent.com/25306722/159933106-e2646ae7-a924-498a-a0b3-0593a1da21c9.mp4

I faced another issue when going back online, but I feel it's unrelated to this PR.
1. Save a draft post while being offline
2. Go back online
3. Close and reopen the app
4. Observe that the draft post is duplicated in the dashboard
5. Go into the draft posts list, the duplicate will be removed.

https://user-images.githubusercontent.com/25306722/159934109-21212932-43a6-4ef8-8a6d-b238cad725ff.mp4

File: WordPress/Classes/Services/PostCoordinator+Dashboard.swift (hunk 3 above)
Comment (leandroalonso) [reply WordPress/Classes/Services/PostCoordinator+Dashboard.swift]: I agree!

To be honest I added those names to try to discourage others from relying on those notifications. But we don't necessarily solve a problem by creating other, changed in 1923d558f68f8e9c5864c996de506ceef4935c7d

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift (hunk 4 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: Do you have a suggestion for this one?

So far, it's used in the context of where we have a new post and should display a new card. `postsCardNewPostAvailable` maybe?

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift (hunk 5 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift:22]: Not exactly! This logic serves the purpose of knowing if there's _any_ local post to show in case the API returns that there are no posts.

If the API returns that we should show scheduled and/or cards, then we're good. It doesn't matter how many, we'll show the card and it will take care of the rest.

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift (hunk 6 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift:102]: Sure thing!

I refactored this in abb0bea75f4dd4c98c4772f02884d54230fdaaca, let me know if that gives you better context.

Basically, now we know for sure if we should show the next post prompt or not. So we do it right away.

**Comment by leandroalonso** [comment]
@hassaanelgarem 

> All scenarios work as expected! I left a few comments. Also, there's one scenario that feels a little off to me:

This is because we don't deal with removing cards. So there are a few edge cases when removing posts. We can probably deal with those but I feel that the complexity might scale. Anyway, it would be good to have this on an issue so I created #18208 to track this.

> I faced another issue when going back online, but I feel it's unrelated to this PR.

Yeah, this indeed looks like it's related to the offline support — not the cards.

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift (hunk 6 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsCardCell.swift:102]: Yes, it's much clearer now!

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift (hunk 5 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPostsParser.swift:22]: Aaah, okay got it 👍

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift (hunk 4 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: This name works!
The second direction I can think of is: `availableDashboardCardsChanged` or `availableDashboardPostsCardsChanged `

File: WordPress/WordPressTest/Dashboard/BlogDashboardPostsParserTests.swift [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+        let postsWithLocalContent = parser.parse(cardsResponseWithoutPosts["posts"] as! NSDictionary,
+                                                 for: blog)
+
+        XCTAssertEqual((postsWithLocalContent["scheduled"] as? [Any])?.count, 0)
+    }
+
+    /// When the API return scheduled posts, keep the amount returned
+    func testReturnScheduledAsItIsEvenWhenLocalScheduledExists() {
+        let blog = BlogBuilder(context).build()
+
```
Comment (hassaanelgarem) [inline WordPress/WordPressTest/Dashboard/BlogDashboardPostsParserTests.swift:87]: I think you're missing a step here of adding a local scheduled post

**Review by hassaanelgarem — APPROVED** [review]

File: WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift (hunk 4 above)
Comment (momo-ozawa) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: Thinking out loud, another candidate: `newPostAvailableForDashboard`

Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift]: Done in 64d2383a7808017b48eabd9402ad729877122727

File: WordPress/WordPressTest/Dashboard/BlogDashboardPostsParserTests.swift (hunk 7 above)
Comment (leandroalonso) [reply WordPress/WordPressTest/Dashboard/BlogDashboardPostsParserTests.swift:87]: Done in f8d5b80eb64f33f7c0e1d16a1638329a11e70cb3
