### PR TITLE
Reader post options: show message when following a site

### LINKED ISSUE #15763: Reader: Following site from post card does not produce the “Turn on notifications” toast
### Expected behavior
When I follow a site, I expect to be prompted to enable notifications

### Actual behavior
It does not appear on the post card screen

### Steps to reproduce the behavior
1. Open a Site title from the Discover screen
2. Tap on Follow and notice the toast
3. IMG_45DE45541715-1
4. Go back to the post card view and do the same on a different site from the postcard
5. Notice there is no toast

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes: https://github.com/wordpress-mobile/WordPress-iOS/issues/15763
Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/15761

This shows a following message when a site is followed from a post card or post details. This is the same message that was previously displayed in post details (before I broke it with https://github.com/wordpress-mobile/WordPress-iOS/pull/15778).

~~There is not a notification for unfollowing. Stay tuned!~~ Unfollow notifications are implemented on https://github.com/wordpress-mobile/WordPress-iOS/pull/15786.

To test:
- In the Reader, show posts you are not following (ex: Discover, filter by topic).
- On a post card or in post details, tap the options menu button.
- Select `Follow Site`.
- Verify a toast message appears.

This functionality has not changed, but if you tap `Enable` on the notification, you should see `Success turn notifications on` in the logs as confirmation.

| menu | message |
|--------|-------|

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift [hunk 1]
```diff
@@ -63,10 +63,13 @@ final class ReaderShowMenuAction {
...
                                                                                  completion: {
-                                                                                    guard let vc = vc as? ReaderStreamViewController else {
-                                                                                        return
+                                                                                    if post.isFollowing {
+                                                                                        vc.dispatchSubscribingNotificationNotice(with: post.blogNameForDisplay(), siteID: post.siteID)
+                                                                                    }
+
+                                                                                    if let vc = vc as? ReaderStreamViewController {
+                                                                                        vc.updateStreamHeaderIfNeeded()
                                                                                     }
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift]: If you like, here's  a more compact version: 
`(vc as? ReaderStreamViewController)?.updateStreamHeaderIfNeeded()`

**Review by aerych — APPROVED** [review]
Hola @ScoutHarris 👋 
Tested and it looked good to me! 
:shipit:

File: WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift (hunk 1 above)
Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift]: Ha. I considered that but thought it might be a bit too much going on. I can certainly do it though!
