### PR TITLE
Display post / comment authors at the top of the suggestions list

### LINKED ISSUE #18818: Mention UI should make parent comment's author prominent in list of suggestions
### Expected behavior

When inserting an @-mention into a reply, the app brings up a list of suggestions. It would be nice if the username of the parent comment or post was at the top of the list, for convenience.

### Actual behavior

You have to manually search for the username of the parent post or comment when inserting an @-mention.

### Steps to reproduce the behavior

1. Locate a post or comment
2. Start a reply
3. Type `@` to insert an @-mention
4. Notice that the author of the parent comment isn't shown at the top of the list

### PR DESCRIPTION
**Pull request by salimbraksa**
## Issue
Closes #18818 

## Description
This PR adds `prominentSuggestionsIds` attribute to `SuggestionsTableView`, then the view controllers that own this view populate that attribute with the post author id or comment author id if they exist.

## Solution
See "implementation" section (ref: pbMoDN-3DH-p2) for more details on how this PR is implemented.

I searched for all the view controllers that use the `SuggestionsTableView` view, and they are:
- **ReaderCommentsViewController**: This VC has access to both the post and the selected comment. So it can pass their ids to `SuggestionsTableView`.
- **FullScreenCommentReplyViewController**: This VC receives the `prominentSuggestionsIds` from the VC that presented it.
- **CommentDetailViewController**: This VC has only access to the comment author id but not the post author id. It does have access to the `postId`, which means we can fetch the whole post to access the author id. But I don't think it's a good solution.
- **NotificationDetailsViewController**: Same issue as **CommentDetailViewController**. Has access to comment author id but not the post author id.
- **GutenbergSuggestionsViewController**: I believe this VC is used when adding a post. So the post author id or comment author id is not relevant here.

## Test Instructions:

**N.B: This feature is not enabled in self-hosted sites ( wordpress.org ).**

There are different scenarios to take into consideration:

**Scenario 1 - Reader Tab**
1. Tap the "Reader" tab.
2. Click on a post.
3. Tap "Comments" icon.
4. Insert @-mention in the reply post. You should see the post author at the top of the suggestions list.
5. Insert @-mention in a comment reply. You should see both the post author and the comment author at the top of the suggestions list.
6. Expand the reply input, then insert @-mention. You should see both the post author and the comment author at the top of the suggestions list.

**Scenario 2 - My Site Tab**
1. Tap the "My Site" tab.
2. Click on "Comments" row.
3. Tap any comment.
4. Tap "Reply" button.
5. Insert @-mention. You should see the comment author at the top of the suggestions list.
6. Expand the reply input, then insert @-mention. You should see the comment author at the top of the suggestions list.

**Scenario 3 - Notifications Tab - Comment Details**
1. Tap the "Notifications" tab.
2. Tap a comment notification.
3. Tap "Reply" button.
4. Insert @-mention. You should see the comment author at the top of the suggestions list.
5. Expand the reply input, then insert @-mention. You should see the comment author at the top of the suggestions list.

**Scenario 4 - Notifications Tab - Notification Details**
First, we need to disable a feature flag to access the Notification Details screen. But this scenario can only be tested by developers.

1. "My Site" Tab > "Me" profile picture > App Settings > Debug.
2. Disable "Notification Comment Details" feature flag.
3. Close everything then navigate to "Notifications" screen.
4. Tap a comment notification.
5. Insert @-mention. You should see the comment author at the top of the suggestions list.
6. Expand the reply input, then insert @-mention. You should see the comment author at the top of the suggestions list.

## Regression Notes
1. Potential unintended areas of impact
Maybe there is a case where I forgot to setup `prominentSuggestionsIds`. But I searched everywhere `SuggestionsTableView` is mentioned and I think the VCs mentioned above are all of them.

3. What I did to test those areas of impact (or what existing automated tests I relied on)
I've manually tested all the scenarios where we access `SuggestionsTableView`.

4. What automated tests I added (or what prevented me from doing so)
Unfortunately the `SuggestionsTableView` is not unit-testable. I'll open another PR to make it unit-testable.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by salimbraksa** [comment]
@twstokes Few questions:
1. Should I update the `RELEASE-NOTES.txt`?
2. Regarding `CommentDetailViewController` and `NotificationDetailsViewController`, right now they only display the comment author id at the top of the suggestions list because those VCs don't have access to post author id. If we want to fix this efficiently, we may need the backend to send us back the `postAuthorID` under the `comment` object. Let me know if I'm missing something.

File: WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents [hunk 1]
```diff
@@ -996,6 +996,7 @@
     </entity>
     <entity name="UserSuggestion" representedClassName="UserSuggestion" syncable="YES">
         <attribute name="displayName" optional="YES" attributeType="String" syncable="YES"/>
+        <attribute name="id" optional="YES" attributeType="Integer 64" defaultValueString="0" usesScalarValueType="YES" syncable="YES"/>
```
Comment (salimbraksa) [inline WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents]: @twstokes Added a `UserSuggestion.id` attribute in the latest core data version model. Do you think I should've created a new version?

The change is very small and it didn't require migration or caused any breaking issues.

**Comment by twstokes** [comment]
> 1. Should I update the `RELEASE-NOTES.txt`?

Please do! We'll target milestone 20.3, so let's add a line under it describing the feature. For each bullet item we add a `*` that serves as a priority indicator. This particular issue fits the single `*` level IMO. <sub>ref: PCYsg-guH-p2</sub>

> 2. Regarding `CommentDetailViewController` and `NotificationDetailsViewController`, right now they only display the comment author id at the top of the suggestions list because those VCs don't have access to post author id. If we want to fix this efficiently, we may need the backend to send us back the `postAuthorID` under the `comment` object. Let me know if I'm missing something.

Thanks for the heads up on this! I'll check it out during my review to understand it better.

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift [hunk 2]
```diff
@@ -97,6 +97,39 @@ extension SuggestionType {
         }
     }
 
+    func moveProminentSuggestionsToTop() {
+        // This method only works for "mention" suggestion types
+        // And when both "searchResults" and "prominentSuggestionsIds" are not empty
+        guard
+            self.suggestionType == .mention &&
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: To make things consistent, should this be a `,` rather than `&&`?

File: WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m [hunk 3]
```diff
@@ -519,9 +519,11 @@ - (void)setIndexPathForCommentRepliedTo:(NSIndexPath *)indexPathForCommentReplie
         CommentContentTableViewCell *cell = (CommentContentTableViewCell *)[self.tableView cellForRowAtIndexPath:indexPathForCommentRepliedTo];
         cell.isReplyHighlighted = YES;
     }
-
+
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m]: Nit: A little bit of whitespace.

```suggestion

```

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift [hunk 4]
```diff
@@ -26,6 +26,7 @@ public class FullScreenCommentReplyViewController: EditCommentViewController, Su
     /// Reply Suggestions
     ///
     private var siteID: NSNumber?
+    private var prominentSuggestionsIds: [NSNumber]?
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift:29]: Is there a benefit to keeping this an array optional rather than just an array?

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift [hunk 5]
```diff
@@ -11,6 +11,15 @@ extension SuggestionType {
 
 @objc public extension SuggestionsTableView {
 
+    // MARK: - API
+
+    /// Returns the a list of prominent suggestions excluding the current user.
+    static func prominentSuggestions(fromPostAuthorId postAuthorId: NSNumber?, commentAuthorsIds: [NSNumber], defaultAccountId: NSNumber?) -> [NSNumber] {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: It looks like `commentAuthorIDs` currently never contains more than one ID at most. Should we update this to `commentAuthorId: NSNumber?`, or perhaps I'm missing something?

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift [hunk 6]
```diff
@@ -480,6 +486,12 @@ extension NotificationDetailsViewController {
         }
 
         suggestionsTableView = SuggestionsTableView(siteID: siteID, suggestionType: .mention, delegate: self)
+        suggestionsTableView?.prominentSuggestionsIds = SuggestionsTableView.prominentSuggestions(
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: Could you help me understand how this gets called? I thought I could reply to a comment on the Notifications tab to get it, but I don't think that's right. Thanks!

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift [hunk 7]
```diff
@@ -97,6 +106,41 @@ extension SuggestionType {
         }
     }
 
+    func moveProminentSuggestionsToTop() {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: Would it be possible for us to refactor this to not mutate the class properties directly? This should also help with unit testing as we'll have a simpler input and output, and we could even make it `static`.

I wonder if it could accept an array of prominent suggestion IDs as well as an array of search results and return an array of search results where the prominent results are on top and ordered. We can then set `self.searchResults` to the output.

What do you think?

File: WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents (hunk 1 above)
Comment (twstokes) [reply WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents]: Thanks for bringing this up @salimbraksa!

> Do you think I should've created a new version?
Looking at past revisions to the core data models, I think we should create a new version. We'll also need to update [MIGRATIONS.md](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/MIGRATIONS.md) with what changed.

Should we update the name from `id` to something like `userSuggestionId` or `suggestionId`? Looking at other entity types it seems we've followed that convention. Let me know your thoughts on that.

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift [hunk 8]
```diff
@@ -97,6 +106,41 @@ extension SuggestionType {
...
+            !ids.isEmpty
+        else { return }
+
+        // Finds the suggestions to move to the top of the "searchResults" array.
+        //
+        // Also, the order of the prominent suggestions in "searchResults" should be
+        // the same order as "prominentSuggestionsIds".
+        var suggestionsToInsert: [Any?] = Array(repeating: nil, count: ids.count)
+        let indexesToRemove = NSMutableIndexSet()
+        for (index, item) in (searchResults as NSArray).enumerated() {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: I might be overlooking something because I didn't do a deep dive here, but would this have the same effect?

1. Create a new array of prominent suggestions based on filtering `searchResults` by prominent IDs
2. Create a new array of `searchResults` by filtering out the prominent suggestions from array 1
3. Return [array 1 + array 2]

**Review by twstokes — COMMENTED** [review]
👋 @salimbraksa! Thanks for your work on this. 🙇 I've dropped some answers, questions, and comments in the review.

1. Can we expand on the **Test Instructions** area to cover all the scenarios for loading comments? Even if they're quite redundant, detailed and numbered steps for our testers are really valuable to ensure we have coverage.
2. Is this feature only applicable to WordPress.com sites and WordPress.org + Jetpack? In other words, will users connected to a self-hosted site (which communicates over XML-RPC) be able to use the feature when replying to comments on their blog? <sub>ref: PCYsg-g6b-p2</sub>

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift (hunk 4 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift:29]: I think there is a subtle semantic differences between the two.

`nil` array means the prominent suggestions feature is not used in some screens ( e.g GutenbergSuggestionsViewController ). I think it also saves some memory compared to empty array ( though the difference is probably negligible )

Whereas an empty array could mean that the view controller tried to find prominent suggestions but didn't find any.

That being said, the drawback of optional array is that we have to unwrap it every time we want to use the it. And this could be significant if we are using the property very frequently.

Happy to change it to empty array if that's your preference 🙏

File: WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents (hunk 1 above)
Comment (salimbraksa) [reply WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents]: Good point. The only reason I named it "ID" is because it's named "ID" in the backend API. But I agree that it should change.

As an alternative to what you suggested, what do you think of naming it just "userId" ( or "accountId") ? And the reason is because the attribute represents the same id as "WPAccount.id".

With "userSuggestionId", we don't know whether that's the same id as "WPAccount.is" or a different one. When I was working on this, I had to manually compare both ids to confirm that they're the same thing.

What do you think?

Comment (twstokes) [reply WordPress/Classes/WordPress.xcdatamodeld/WordPress 143.xcdatamodel/contents]: > what do you think of naming it just "userId"

That sounds great @salimbraksa! I was mistaken when I suggested `suggestionId`, so `userId` makes way more sense. Looking at other entities where we reference a user ID I see we've used `userID` (with the D capitalized), so I'll let you make the judgement call on what fits best with the codebase - I'm fine either way. 👍

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 7 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: I totally agree. I actually refactored that method in the perf PR to something similar to what you suggested.

I'll make the changes for this PR too 👌

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift (hunk 4 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift:29]: > nil array means the prominent suggestions feature is not used in some screens

I'm fine with this logic. 👍

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 8 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift:125]: Yes, I've considered that approach but it didn't work as expected. Let me explain: 

- Let's say `prominentSuggestionsIds` equals this array `[postAuthorId, commentAuthorId]`. Meaning the post author should appear before the comment author.
- And `searchResults` equals this array `[..., commentAuthor, ..., postAuthor]`

`array1` in this case will be `[commentAuthor, postAuthor]`. Notice how the authors order is not the same as `prominentSuggestionsIds`!

We probably want to maintain the order of authors.

Another reason is that this approach loops through `searchResults` twice, and I was looking for way to loop through the array only once.

I hope it's clear, let me know what do you think.

Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: Not really, I've considered that approach but it didn't work as expected. Let me explain: 

- Let's say `prominentSuggestionsIds` equals this array `[postAuthorId, commentAuthorId]`. Meaning the post author should appear before the comment author.
- And `searchResults` equals this array `[..., commentAuthor, ..., postAuthor]`

`array1` in this case will be `[commentAuthor, postAuthor]`. Notice how the authors order is not the same as `prominentSuggestionsIds`!

We probably want to maintain the order of authors.

Another reason is that this approach loops through `searchResults` twice, and I was looking for way to loop through the array only once.

I hope it's clear, let me know what do you think.

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift (hunk 6 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: When you click on a comment in the Notifications screen, what you get is `CommentDetailViewController`, not `NotificationDetailsViewController`!

In `NotificationsViewController` ( Notifications screen ), there is a logic that decides whether to display `CommentDetailViewController` or `NotificationDetailsViewController`. During development, I commented out some code to force the display of `NotificationDetailsViewController`.

I'll dig into this more to understand how to navigate to `NotificationDetailsViewController`.🙏

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 5 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: I've designed the API this way in case we want to cover the UX you suggested in P2 ( pulling all authors above a nested comment ). 

Maybe it's just going to be confusing for now, what do you think?

**Comment by salimbraksa** [comment]
@twstokes Thanks for taking the time to review my PR 🙏
>Can we expand on the Test Instructions area to cover all the scenarios for loading comments? Even if they're quite redundant, detailed and numbered steps for our testers are really valuable to ensure we have coverage.

Sure thing 👍

>Is this feature only applicable to WordPress.com sites and WordPress.org + Jetpack? In other words, will users connected to a self-hosted site (which communicates over XML-RPC) be able to use the feature when replying to comments on their blog?

Good catch, I haven't thought about this. I'll test with a fake site then get back to you 🙏

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift (hunk 6 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: Thanks @salimbraksa!

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 5 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: > Maybe it's just going to be confusing for now, what do you think?

I agree, perhaps this should be plural only if / when that feature is implemented. 👍

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift (hunk 6 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: @twstokes It looks like there is a feature flag called `FeatureFlag.notificationCommentDetails` that controls whether to display `CommentDetailViewController` or `NotificationDetailsViewController`. Currently, it's set to `true`.

Disable the feature flag if you want `NotificationDetailsViewController` to show up:
1. Go to `FeatureFlag.swift` file.
2. Search for `notificationCommentDetails` and change the `enabled` computed property to `false`.

I think `NotificationDetailsViewController` is deprecated but the original author didn't want to remove that class yet.

Comment (twstokes) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: Thanks for researching and following up on that @salimbraksa!

Looks like we can also toggle by going to:
1. Me (tapping profile image at top right)
2. App Settings
3. Debug
4. Toggling "Notification Comment Details"

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift [hunk 9]
```diff
@@ -97,6 +131,54 @@ extension SuggestionType {
...
+        } else {
+            searchResults = suggestions
+        }
+        if suggestionType == .mention {
+            searchResults = self.moveProminentSuggestionsToTop(searchResults: searchResults, prominentSuggestionsIds: prominentSuggestionsIds ?? [])
+        }
+        return searchResults
+    }
+
+    private func moveProminentSuggestionsToTop(searchResults: [Any], prominentSuggestionsIds ids: [NSNumber]) -> [Any] {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: I like this version with no side effects! 👏 

Is there any particular reason we're going with `searchResults: [Any]` and returning `[Any]` over enforcing the `UserSuggestion` type?

Would `private func moveProminentSuggestionsToTop(searchResults: [UserSuggestion], prominentSuggestionsIds ids: [NSNumber]) -> [UserSuggestion]` strengthen the function's purpose?

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h [hunk 10]
```diff
@@ -9,10 +9,12 @@ typedef NS_CLOSED_ENUM(NSUInteger, SuggestionType) {
 
 @interface SuggestionsTableView : UIView <UITableViewDataSource>
 
+@property (nonatomic, readonly, nonnull, strong) UITableView *tableView;
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h:12]: Out of curiosity, why did we move this and need to change the type properties?

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 8 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: This sounds logical! It definitely has better performance than something like:

```
let topSuggestions = prominentIds.compactMap { id in
    searchResults.first(where: { $0.id == id })
}

let regularSuggestions = searchResults.filter { !prominentIds.contains($0.id) }
```

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h (hunk 10 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h:12]: Properties should be declared in the `.h` file in order to access them in the Swift extension. And if you look at `showSuggestions(forWord:)` implementation, it needs to access `tableView` to reload the data:
```
@discardableResult func showSuggestions(forWord word: String) -> Bool {
       // ... Omitted for brevity
        self.tableView.reloadData()
        self.setNeedsUpdateConstraints()
        return searchResults.count > 0
}
```
And I made it `readonly` so that it doesn't get mutated after it is initialized ( similar to `let` in Swift ).

Comment (twstokes) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h:12]: Thanks! Makes sense!

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 9 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: >Is there any particular reason we're going with searchResults: [Any] and returning [Any] over enforcing the UserSuggestion type?

I think I just haven't paid attention to this. `searchResults` type from ObjC is `NSArray` ( aka `[Any]` ) so I kept using that type. But I agree it should be `[UserSuggestion]` for `moveProminentSuggestionsToTop`. Fix pushed!

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 8 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: Since `searchResults` is going to be larger than `prominentIds`. I wanted to reduce the number of times we iterate through `searchResults`.

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift (hunk 6 above)
Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift:489]: @twstokes This is neat! Thanks for sharing this 👍

File: WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift (hunk 8 above)
Comment (twstokes) [reply WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift]: Makes sense! I'll go ahead and resolve this conversation. 👍

**Comment by twstokes** [comment]
This is looking good @salimbraksa!

I tested each scenario with a WordPress.com account:
- ✅ Scenario 1 - Reader Tab
- ✅ Scenario 2 - My Site Tab
- ✅ Scenario 3 - Notifications Tab - Comment Details
- ✅ Scenario 4 - Notifications Tab - Notification Details

I have not tested with a self-hosted non-Jetpack account.

**A few outstanding items that you may be aware of:**
- RELEASE-NOTES.txt has a conflict
- MIGRATIONS.md should be updated with the Core Data model changes

**Comment by twstokes** [comment]
I've created a PR for running CI tests: https://github.com/wordpress-mobile/WordPress-iOS/pull/19009

**Review by twstokes — APPROVED** [review]

File: RELEASE-NOTES.txt [hunk 11]
```diff
@@ -1,5 +1,6 @@
 20.3
 -----
+* [*] User Mention: When replying to a post or a comment, the post author or comment author shows up at the top of the suggestions list. [#18818]
```
Comment (twstokes) [inline RELEASE-NOTES.txt]:
```suggestion
* [*] User Mention: When replying to a post or a comment, the post author or comment author shows up at the top of the suggestions list. [#18979] 
```

**Comment by twstokes** [comment]
👋 @salimbraksa - this looks good!

[CI PR passed](https://github.com/wordpress-mobile/WordPress-iOS/pull/19009) ✅ 

After updating the [release notes](https://github.com/wordpress-mobile/WordPress-iOS/pull/18979#discussion_r916352775) we should be good to merge!
