### PR TITLE
Fixes #5195 – Toggling site visibility crashed the app

### LINKED ISSUE #5195: Toggling site visibility crashes the app
Toggling the visibility of sites either applies the visibility to the wrong site, or crashes the app. This appears to be due to the addition of the separate default / primary site section in the tableview, where the switch handling code expects only one section.

### Steps to reproduce the behavior

1. Ensure you have a primary site set and visible in the My Sites list. 
2. Under My Sites, tap Edit to reveal the visibility toggles.
3. Toggle the visibility of the first site in the 'all sites' group. You should see that the changes actually affect the primary site instead.
4. Attempt to toggle the visibility of another site in the list, lower down. The app should crash.

### PR DESCRIPTION
**Pull request by frosty**
Fixes #5195. See that issue for full details, and how to test.

I've tweaked the code so that it can now use the correct index path for each cell, rather than relying on a view tag (eww!)

Needs review: @jleandroperez 
Thanks!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.h [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 @interface WPBlogTableViewCell : WPTableViewCell
 
-@property (nonatomic, weak) UISwitch *visibilitySwitch;
+@property (nonatomic, weak, nullable) UISwitch *visibilitySwitch;
+@property (nonatomic, copy, nullable) void (^visibilitySwitchToggled)(WPBlogTableViewCell * _Nonnull cell);
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Cells/WPBlogTableViewCell.h]: Thank you!!! :hug:

**Comment by jleandroperez** [comment]
Thanks so much for fixing this one!!!

:shipit:

**Comment by frosty** [comment]
Thanks for reviewing!
