### PR TITLE
Fix UserInfo Crash

### LINKED ISSUE #17802: Retrying failed media uploads without Internet connectivity leads to Core Data exception
Fixed by #17488, #17759.

**On a self-hosted site not connected to Jetpack:**

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The Internet connection appears to be offline."
8. Tapping "Retry" crashes the app

**On a WordPress.com site:**

1. Create a new Post
2. Add an Image Block
3. Put the device in Airplane Mode
4. Tap "Add Image"
5. Choose a photo from the device or the camera
6. Observe that the image is added to the post with an overlay "Failed to insert media. Please tap for options."
7. Observe that when tapping on the overlay, a bottom sheet appears that reads "The internet connection appears to be offline." (Internet is not capitalized)
8. Tapping "Retry" crashes the app

### PR DESCRIPTION
**Pull request by illusaen**
Fixes a crash where cloning the `userInfo` of an `NSError` is causing a Core Data exception when trying to save the context.

```
2021-11-17 14:10:31:827 WordPress[1434:200461] Unresolved Core Data save error: Error Domain=NSCocoaErrorDomain Code=134060 "A Core Data error occurred." UserInfo={NSUnderlyingError=0x120604370 {Error Domain=NSCocoaErrorDomain Code=4866 "The data couldn’t be written because it isn’t in the correct format." UserInfo={NSUnderlyingError=0x120618770 {Error Domain=NSCocoaErrorDomain Code=4864 "This decoder will only decode classes that adopt NSSecureCoding. Class 'NWConcrete_nw_path' does not adopt it." UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class 'NWConcrete_nw_path' does not adopt it.}}}}}
```

### To test:
**Prerequisites: iOS 15**

1. Go to a simple site.
2. Put the device into Airplane Mode.
3. Add an image block to a post.
4. Select an image from the device.
5. See that it doesn't crash and a "Failed to insert media. Please tap for options." message is displayed.

## Regression Notes
1. Potential unintended areas of impact
Error should still exist and show that there was a networking error, just without crashing.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Use the above steps to test.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/MediaService.m [hunk 1]
```diff
@@ -435,9 +435,7 @@ - (NSError *)customMediaUploadError:(NSError *)error remote:(id <MediaServiceRem
         }
     }
     if (customErrorMessage) {
-        NSMutableDictionary *userInfo = [error.userInfo mutableCopy];
-        userInfo[NSLocalizedDescriptionKey] = customErrorMessage;
-        error = [[NSError alloc] initWithDomain:error.domain code:error.code userInfo:userInfo];
+        error = [[NSError alloc] initWithDomain:error.domain code:error.code userInfo:error.key];
```
Comment (twstokes) [inline WordPress/Classes/Services/MediaService.m]: Since the issue seems to arise from the original error's `userInfo` dictionary, this prevents it from being included when committing to Core Data. 👍 

**Some thoughts:**

- I think we can still pass in a `userInfo` dictionary that includes our custom error message.
- `error.key` will prevent compiling due to it not being a property on an [NSError](https://developer.apple.com/documentation/foundation/nserror)

Example of the userInfo that breaks:

```
{
    NSErrorFailingURLKey = "https://public-api.wordpress.com/rest/v1.1/sites/199533184/media/new?locale=en";
    NSErrorFailingURLStringKey = "https://public-api.wordpress.com/rest/v1.1/sites/199533184/media/new?locale=en";
    NSLocalizedDescription = "The Internet connection appears to be offline.";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1009 \"(null)\" UserInfo={_NSURLErrorNWPathKey=unsatisfied (No network route), _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}";
    "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalUploadTask <34890537-1C31-4960-AFBA-EC6924B9B8A8>.<33>";
    "_NSURLErrorRelatedURLSessionTaskErrorKey" =     (
        "LocalUploadTask <34890537-1C31-4960-AFBA-EC6924B9B8A8>.<33>"
    );
    "_kCFStreamErrorCodeKey" = 50;
    "_kCFStreamErrorDomainKey" = 1;
}
```

Perhaps we can pluck `NSErrorFailingURLKey`, `NSErrorFailingURLStringKey`, `NSLocalizedDescription` (our custom error) and use those only?

I believe `NSUnderlyingError` is the problem key / value and if we wanted to send along a description we could with `.localizedDescription`, but I'm not sure how much value that offers since at this point we know the error domain.

**Comment by twstokes** [comment]
Interestingly the crash doesn't occur (nor the errors) if the original `NSError` is used. Comparing the "custom" error to the original, only the descriptions differ (because that's what we inject). The `NSUnderlyingError` key in the userInfo dictionary appears to be the culprit. Possibly the fact that its value is an object is a clue.

**Comment by twstokes** [comment]
I also want to note that I failed to find any spots in code where we cared about anything more than the domain, code, and description when dealing with Media errors.

**Review by ScoutHarris — APPROVED** [review]
✅ See that it doesn't crash and a "Failed to insert media. Please tap for options." message is displayed.

:shipit:
