### PR TITLE
Fixes Notifications Undelete Glitch

### LINKED ISSUE #4859: Notifications: Undelete Animation Glitch
Sample video here: https://cloudup.com/c0cZ1-JnX8v

Thanks @astralbodies for reporting this!

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #4859

To test:
1. Receive a Comment-Y Notification
2. Launch WPiOS and open the Notifications tab
3. Open the Notification details
4. Tap over the `Trash` button
5. Within 4 seconds, tap *Undo*, open the Notification Details, and tap `Trash` again

Verify that the notification gets effectively nuked *4 seconds* after tapping the Trash button. This was caused by a *GCD* dispatch_after call, not being cancelled (because there is no mechanism to do so!).

Needs review: @astralbodies 
Thanks in advance Aaron!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h [hunk 1]
```diff
@@ -20,7 +20,7 @@
 @property (nonatomic, strong) NSString                      *pushNotificationID;
 @property (nonatomic, strong) NSDate                        *pushNotificationDate;
 @property (nonatomic, strong) NSDate                        *lastReloadDate;
-@property (nonatomic, strong) NSMutableSet                  *notificationIdsMarkedForDeletion;
+@property (nonatomic, strong) NSMutableDictionary           *notificationDeletionBlocks;
```
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h]: Should this maybe be a `NSMapTable` so the deletion blocks are held weakly?

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Internal.h]: We actually need to **retain / copy** those blocks, since they come from another ViewController. Changing to MapTable should break things there (unless it's set to strong / strong, which really replicates NSDictionary's behaviour).

Thanks for checking!!

**Comment by astralbodies** [comment]
:shipit:!

**Comment by jleandroperez** [comment]
Thanks sir!
