### PR TITLE
[Pages List] Fix app freeze when loading page with GIF as its featured image

### LINKED ISSUE #19183: [Pages List] App freezes if a page has GIF as its featured image
### Expected behavior
Pages list page to load normally. 

### Actual behavior
Pages list page freezes if a page has a GIF as a featured image.

### Steps to reproduce the behavior

1. Upload a GIF to the media library
2. Create a new page and set its featured image to the GIF
3. Run the app
4. Navigate to pages
5. Observe that the app freezes

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #19183

## Description
Pages list page freezes if a page has a GIF as a featured image.

## Root Cause
The issue was a threading deadlock.
- `ImageLoader.loadImage` gets called from main thread
- Inside of it, `MediaThumbnailCoordinator.shared.fetchStubMedia` gets called
- Which fetches the media from the API and then performs an **async** block on a `NSManagedObjectContext`'s thread
- This block calls the completion handler, which in turn propagates back to `ImageLoader.loadImage`
- `ImageLoader.loadImage` calls `ImageLoader.loadImage` on the main thread (line 351) but this time it goes down a different a different path
- This path leads to `Blog.isAtomic()` being called (from `MediaHost.init()`) which runs a **sync** block on the same `NSManagedObjectContext` thread
- The two blocks form a deadlock

## Solution
Call `Blog.isAtomic()` before anything else, and pass the value directly to `MediaHost.init()`

## Testing Instructions

1. Upload a GIF to the media library
2. Create a new page and set its featured image to the GIF
3. Run the app
4. Navigate to pages
5. Make sure the app doesn't freeze and GIF is loaded normally

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
@hassaanelgarem 👋 

I can confirm that the app doesn't freeze, but the featured image renders as a grey square in the Pages list. Is this expected?

https://user-images.githubusercontent.com/6711616/184644313-71639f57-3df2-4ffb-b51c-0079da676057.mp4

**Comment by hassaanelgarem** [comment]
@momo-ozawa It loads normally for me 🤷‍♂️ 



Does the GIF load inside the editor?

**Comment by momo-ozawa** [comment]
@hassaanelgarem 

> Does the GIF load inside the editor?

It does!

I think I know what's going on. When I upload the GIF from the app it doesn't render in the Pages list. But if I upload the GIF from web, it renders as expected.

Simulator Screen Recording - iPhone 13 - 2022-08-15 at 14 46 33

File: WordPress/Classes/Utility/Media/ImageLoader.swift [hunk 1]
```diff
@@ -314,18 +314,24 @@ import AutomatticTracks
...
-    @objc(loadImageFromMedia:preferredSize:placeholder:success:error:)
+    @objc(loadImageFromMedia:preferredSize:placeholder:isBlogAtomic:success:error:)
     /// Load an image from the given Media object. If it's a gif, it will animate it.
     /// For any other type of media, this will load the corresponding static image.
     ///
     /// - Parameters:
     ///   - media: The media object
     ///   - placeholder: A placeholder to show while the image is loading.
     ///   - size: The preferred size of the image to load.
+    ///   - isBlogAtomic: Whether the blog associated to the media item is Atomic of not
```
Comment (momo-ozawa) [inline WordPress/Classes/Utility/Media/ImageLoader.swift]:
```suggestion
    ///   - isBlogAtomic: Whether the blog associated to the media item is Atomic or not
```

**Review by momo-ozawa — APPROVED** [review]
LGTM w 1 nit. Also, I think it would be good to mention this in the release notes. 

As for the issue I mentioned about the gif not rendering on the pages screen, I think that can be addressed in a separate PR

**Comment by hassaanelgarem** [comment]
> Does the GIF load inside the editor?

@momo-ozawa I'm sorry I thought you attached a screenshot not a video 🙈 

> As for the issue I mentioned about the gif not rendering on the pages screen, I think that can be addressed in a separate PR

Agreed! I opened an issue (#19192) to track this 👍
