### PR TITLE
Issue/4954 3d touch crash no blogs

### LINKED ISSUE #4954: 3D Touch shortcuts crash on an account with no blogs
To reproduce:

1. Sign in to the app with a WordPress.com account that has no blogs
2. Go back to the home screen, tap to show 3D Touch shortcuts, select anything other than Notifications
3. :bomb: 

I don't have a 3D Touch enabled phone but @diegoreymendez tested it
> New post crashes the app for me
> Same for everything except notifications

I discovered this while writing #4953, in this piece of code:

```swift
    public func loggedInShortcutArray() -> [UIApplicationShortcutItem] {
        var defaultBlogName: String?
        if blogService.blogCountForAllAccounts() > 1 {
            defaultBlogName = blogService.lastUsedOrFirstBlog()?.settings.name
        }
```

As I had to deal with the possibility of `lastUsedOrFirstBlog` being optional, I noticed that this might still be called if logged in, but with a blog count of 0. In that case, we still add blog-related shortcuts that won't work.

cc @kwonye

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4954 

To test:
1. Sign in with an account that has no blogs
2. Verify when 3D touching it does not crash and there are no shortcut icons

cc @koke. I'm going to have @diegoreymendez review it as he can actually test it.

Needs review: @diegoreymendez

### CODE REVIEW

**Comment by sendhil** [comment]
Going to merge this in as #4963 is in.

File: WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift [hunk 1]
```diff
@@ -26,15 +26,23 @@ public class WP3DTouchShortcutCreator: NSObject
         blogService = BlogService(managedObjectContext: mainContext)
     }
     
-    public func createShortcuts(loggedIn: Bool) {
+    public func createShortcutsIf3DTouchAvailable(loggedIn: Bool) {
+        if !is3DTouchAvailable() {
+            return
+        }
```
Comment (koke) [inline WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift]: It's a good practice to use `guard` for this. The resulting behavior would be the same, but `guard` shows a clearer intention, and the compiler will warn you if you forget to add a return, throw, or similar inside the `guard`

File: WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift [hunk 2]
```diff
@@ -26,15 +26,23 @@ public class WP3DTouchShortcutCreator: NSObject
...
+        
         if loggedIn {
-            createLoggedInShortcuts()
+            if hasBlog() {
+                createLoggedInShortcuts()
+            } else {
+                clearShortcuts()
+            }
```
Comment (koke) [inline WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift]: I think this is problematic for two reasons:
1. Even if you have no blogs, it still makes sense to show the notifications shortcut
2. In the `hasBlog` case, you still have to deal with the possibility of `lastUsedOrFirstBlog` being `nil` at compile time, even if you know it can never happen.

I'd revert this bit to the previous version and change `createLoggedInShortcuts` instead:

```swift
private func loggedInShortcutArray() -> [UIApplicationShortcutItem] {
    let notificationsShortcut = ...
    if let defaultBlog = blogService.lastUsedOrFirstBlog() {
        let defaultBlogName = defaultBlog.settings?.name
        // Create stats, newPhoto, and newPost shortcuts
        // Return [notifications, stats, newPhoto, newPost]
    } else {
        // Return [notificationsShortcut]
    }
```

I've split the `defaultBlog` optional check in two parts because you can have one blog with a `nil` name. In that case you'd want to show all the shortcuts even if you don't show the site name.

File: WordPress/Classes/ViewRelated/NUX/LoginViewController.m [hunk 3]
```diff
@@ -177,7 +177,7 @@ - (void)bindToViewModel
 - (void)update3DTouchForLogIn
 {
     WP3DTouchShortcutCreator *shortcutCreator = [WP3DTouchShortcutCreator new];
-    [shortcutCreator createShortcuts:self.cancellable];
+    [shortcutCreator createShortcutsIf3DTouchAvailable:self.cancellable];
```
Comment (koke) [inline WordPress/Classes/ViewRelated/NUX/LoginViewController.m]: I know it's not new code, but `LoginViewController.cancellable != loggedIn`. It is now, but if we start supporting a logged out experience, I'd guess logins would be cancellable even if logged out, and this would break. `WP3DTouchShortcutCreator` already checks if `hasWordPressComAccount`, why do we need the extra parameter?

**Comment by kwonye** [comment]
Thanks for the feedback @koke. All valid points for sure. I'm adding this as a "re-do" on my to-do list, but the priority of it is not high. It'll get done, I just can't guarantee it'll be done soon.

**Comment by kwonye** [comment]
Per @koke: "as a suggestion, I’d have `createShortcutsIf3DTouchAvailable` call a second method that returns an array of shortcuts and test that array instead of touching UIApplication" (Regarding tests)
