### PR TITLE
Handle link tap inside WPRichContentView instead of in shouldInteractWith URL

### LINKED ISSUE #12568: Reader: Swiping with finger on a link opens the link instead of scrolling
### Expected behavior

When swiping to scroll through a post in the Reader, it shouldn't matter where you place your finger to perform the swipe action.

### Actual behavior

If you happen to place your finger on a link when you perform the swipe action, it opens the link instead of scrolling the post.

This is especially troublesome because you can't immediately close the webview. While the webview says "Loading..." the "x" in the top left doesn't do anything.

### Steps to reproduce the behavior

1. Open a post in the Reader.
2. Try to swipe when placing your finger over a link. The posts from this blog are great to test with because the content is very link-heavy: https://5blogs.wordpress.com

Result: No matter how quickly you perform the swipe action, the link opens.

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #12568 

Since iOS 13, the delegate method ```textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange, interaction: UITextItemInteraction)```
gets called not only when tapping on a link but also when scrolling.

As a result of this and the way we handle things inside that delegate method, links would open on scroll which feels especially buggy in link heavy posts like the ones in this blog: https://5blogs.wordpress.com

This PR adds a gesture recognizer to `WPRichContentView` where we now handle taps on links and attachments.

It also introduces a new WPRichContentViewDelegate method `interactWith(URL: URL)` to preform customization of the link presentation in the controller if needed. 

[Reported issues on SO](https://stackoverflow.com/questions/58189447/ios-13-uitextview-delegate-method-shouldinteract-called-when-scrolling-on-attach)

To test:

In reader post:
1. Open a post in reader (preferably with a lot of links)
2. Make sure that scrolling through doesn't open links
3. Make sure that tapping on a link opens the links as expected
4. Make sure that tapping on media is handled as expected

In reader post comments 
1. Open a post in reader with comments that have links 
2. Make sure that scrolling through the comment content doesn't open links
3. Make sure that tapping on a link in comment opens the links as expected
4. Make sure that tapping on media in comment is handled as expected

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 1]
```diff
@@ -155,6 +166,27 @@ class WPRichContentView: UITextView {
...
+          let point = recognizer.location(in: self)
+          let characterIndex = self.layoutManager.characterIndex(for: point, in: self.textContainer, fractionOfDistanceBetweenInsertionPoints: nil)
+          // handle tap on link
+          if let linkAttribute = self.attributedText?.attribute(.link, at: characterIndex, effectiveRange: nil),
+              let url = linkAttribute as? URL,
+              let richDelegate = delegate as? WPRichContentViewDelegate {
+              richDelegate.interactWith?(URL: url)
+          // handle tap on attachement
+          } else if let attachmentAttribute = self.attributedText?.attribute(.attachment, at: characterIndex, effectiveRange: nil),
+              let attachment = attachmentAttribute as? WPTextAttachment {
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: This doesn't seem to be getting called. When you tap on an image in a reader post, I'm seeing a `ReaderPlaceholderAttachment` instead of `WPTextAttachment`. Opening the image is working because the attachment manager is creating a `WPRichTextImage` which is a `UIControl` and acts as a button.

Unless I missed other details, we can get rid of this case.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 2]
```diff
@@ -155,6 +166,27 @@ class WPRichContentView: UITextView {
...
     }
 
+    private func setupTouchDetection() {
+          for gesture in gestureRecognizers ?? [] {
+              gesture.require(toFail: linkTapGestureRecognizer)
+          }
+          addGestureRecognizer(linkTapGestureRecognizer)
+      }
+
+      @objc func tapRecognized(_ recognizer: UIGestureRecognizer) {
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: I haven't found an example where this goes wrong, but just in case, we should be implementing `gestureRecognizer(_:shouldReceive:)` in our delegate to make sure our recognizer only responds to taps on links.

I've been playing with it and this seems to work:

```swift
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        guard gestureRecognizer == linkTapGestureRecognizer else {
            return true
        }
        let point = touch.location(in: self)
        let characterIndex = self.layoutManager.characterIndex(for: point, in: self.textContainer, fractionOfDistanceBetweenInsertionPoints: nil)

        let linkAttribute = self.attributedText?.attribute(.link, at: characterIndex, effectiveRange: nil)
        return linkAttribute is URL
    }
```

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 3]
```diff
@@ -155,6 +166,27 @@ class WPRichContentView: UITextView {
         }
     }
 
+    private func setupTouchDetection() {
+          for gesture in gestureRecognizers ?? [] {
+              gesture.require(toFail: linkTapGestureRecognizer)
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: I thought this would be necessary but I commented it out and things still seem to work (after implementing the `shouldReceive` method). What was this trying to prevent?

Also, it seems to be interfering with the normal behavior of the text view. When I long press on a link, the share sheet pops up now ❤️ but the word I tapped also gets selected.

Simulator Screen Shot - iPhone 11 - 2019-10-03 at 09 37 57

**Comment by koke** [comment]
While testing the tapping on images, I noticed something that seems unrelated to this issue, but worth noting, not sure if you know more about it. When you long press an image, it pops out as if you would be able to drag and drop, but the content is blank, and the moment you try to drag it, it disappears:

reader-image-long-press

I think we should probably support drag and drop and the share sheet on long press for reader images.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 4]
```diff
@@ -155,6 +166,27 @@ class WPRichContentView: UITextView {
...
+          }
+          addGestureRecognizer(linkTapGestureRecognizer)
+      }
+
+      @objc func tapRecognized(_ recognizer: UIGestureRecognizer) {
+          let point = recognizer.location(in: self)
+          let characterIndex = self.layoutManager.characterIndex(for: point, in: self.textContainer, fractionOfDistanceBetweenInsertionPoints: nil)
+          // handle tap on link
+          if let linkAttribute = self.attributedText?.attribute(.link, at: characterIndex, effectiveRange: nil),
+              let url = linkAttribute as? URL,
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: This was probably an existing issue, but I wanted to test links in comments and somehow the first comment with a link I could find was an email address. `mailto:user@example.com` is a URL, but we don't want our in-app browser to handle that (and it can't)

Simulator Screen Shot - iPhone 11 - 2019-10-03 at 09 48 53

Comment (koke) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Confirmed it was the same in latest WP Internal

**Comment by koke** [comment]
> I have considered if this change warrants user-facing release notes and have added them to RELEASE-NOTES.txt if necessary.

I think this one should go in the release notes. At least definitely a mention in the call for testing, since I'm not sure what odd cases we might be missing for the gesture recognizer interactions.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 1 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Weird, it's getting called for me and if I remove this logic, tap on an image doesn't do anything.

Comment (koke) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: I was testing on the iOS 13.1 simulator

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: I'm on 13.1 device

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 2 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: And what about taps on images? I guess that's related to our comments above?

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 3 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: You're right! Removing it

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 2 above)
Comment (koke) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: That code doesn't handle the images because I thought we didn't need to, but it's possible as well, just a bit more complicated. The logic is similar to the `tapRecognized`, except it only has to return if the touch should be handled.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 4 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Right. Out of scope for this PR. I'll create a ticket for it if one doesn't exist

**Comment by yaelirub** [comment]
@koke , updated and ready for another look

**Comment by yaelirub** [comment]
@koke , you're right!
Im removing the attachment from both methods

**Comment by yaelirub** [comment]
The failing testDoNotUploadAPostWithFailedMedia was fixed for 13.4 https://github.com/wordpress-mobile/WordPress-iOS/pull/12514

**Comment by jtreanor** [comment]
@yaelirub did you mean to target 13.3 with this? I submitted the build for review this morning. Could this wait for 13.4 or should we consider delaying the release?

**Comment by yaelirub** [comment]
@jtreanor , I meant to target 13.3 and it has to be merged there since this bug is an annoying issue and have been reported by multiple users https://github.com/wordpress-mobile/WordPress-iOS/issues/12568#issuecomment-538017300 including Matt.

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift (hunk 4 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: A ticket exists: https://github.com/wordpress-mobile/WordPress-iOS/issues/11645

**Comment by aerych** [comment]
FWIW, possibly, maybe resolved in iOS 13.2.  More info linked [in this comment](https://github.com/Automattic/simplenote-ios/pull/470#issuecomment-542382370).

I haven't looked through the code here but FYI in case it would make sense to roll back with the updated OS (assuming its actually fixed)
