### PR TITLE
Fix filter change not syncing

### LINKED ISSUE #5957: Posts not syncing when toggling filter
### Expected behavior

Posts should automatically sync when toggling the filters between Published, Drafts, Trashed, Scheduled.
### Actual behavior

Toggling the filter does not initiate a fresh sync and instead only shows posts locally stored in CoreData. If posts were not previously stored, a user would see "You don't have any [posts]" which would be misinforming, relying on a pull-to-refresh up top to sync.
### Steps to reproduce the behavior
1. Launch the app from a fresh install, log in.
2. Select a site with known Drafts or Trashed posts.
3. Select Blog Posts or Pages.
4. Switch to Drafts, Trashed or Scheduled.
5. No posts will display or load.
6. Pull to refresh, posts were indeed available (if on the site).

posts-selector

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #5957

To test: See #5957 for steps to reproduce.

Needs review: @kurzee

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 1]
```diff
@@ -963,6 +963,7 @@ class AbstractPostListViewController : UIViewController, WPContentSyncHelperDele
                 let index = strongSelf.filterSettings.availablePostListFilters().indexOf(selectedValue as! PostListFilter) {
 
                 strongSelf.filterSettings.setCurrentFilterIndex(index)
+                strongSelf.syncItemsWithUserInteraction(false)
```
Comment (kurzee) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: I think it might best to call `syncItemsWithUserInteraction` after `refreshAndReload` as we would have already appropriately set up the fetch request, table, etc to be ready for any newly synced content.

Comment (nheagy) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: I put it there to be as near its original location as possible, but I think you're right. Moved and pushed. Thanks 👍

**Comment by kurzee** [comment]
@nheagy nice! :shipit:
