### PR TITLE
Change the loading indicator from a ghost view to an activity indicator

### LINKED ISSUE #14080: [GlobalStep] [iOS] Under "Menus" black empty box flashes for few seconds before "Nothing Found" message is prompted while adding new item.
Environment:
iOS: iPad Air 2(v13.3.1), iPhone 11 Pro (v13.3.1)

Steps To Reproduce:
 
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Open "My site" tab.
 5. Tap on "Menus".
 6. Select or add new menu.
 7. Tap on New item and list will open.
 8. Tap on any option from the list (eg. Page,Link, Tag, Post,Product)
 9. Observe that   black empty text box is displayed for few second and then "Nothing found" message is displayed.
  
 Actual Result:
Under "Menus" black empty box flashes for few seconds before "Nothing Found" message is prompted while adding new item

 Expected Result:
Upon adding new item in Menu from "Menus" blank empty box should not display.

[#14080.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594795/14080.zip)

### PR DESCRIPTION
**Pull request by mindgraffiti**
Closes #14080

This PR removes the ghost animation and replaces it with an activity indicator, to let the user know that their search results are loading.

### To test
I used FG pages to test this because there are many and it takes a while to load, even on a fast connection.

1. Install and launch the application.
2. Tap on "Log In".
3. Log in to the app using valid credentials.
4. Open "My site" tab.
5. Tap on "Menus".
6. Select or add new menu.
7. Tap on New item and list will open.
8. Tap on any option from the list (eg. Page,Link, Tag, Post,Product)
9. Observe the ghost view has been replaced with a spinner.
10. Try out a few searches that have no results ("Wow"). The spinner should disappear and a message for no results should appear.
11. Try a search with only a couple of results ("Show"). The spinner should show up below the cached results and eventually disappear when it doesn't find anything new.

### Screenshots
**iOS 13**
| Light mode | Dark mode |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 11 06 19 | Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 11 08 50 |

| iOS 12 |
| --- |
| <a href="https://user-images.githubusercontent.com/1062444/98146872-7f506b00-1e91-11eb-9c6a-d21c3c976dda.png"></a> |

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Menus/MenuItemSourceFooterView.m [hunk 1]
```diff
@@ -60,23 +37,26 @@ - (void)setupSourceCell
...
+    _activityIndicator.translatesAutoresizingMaskIntoConstraints = false;
+    [self addSubview: _activityIndicator];
+    [self pinSubviewAtCenter: _activityIndicator];
 }
 
 - (void)toggleMessageWithText:(NSString *)text
 {
     self.labelText = text;
-    if (!self.beginLoadingAnimationsTimer && !self.endLoadingAnimationsTimer) {
+    if (self.activityIndicator.isAnimating == NO) {
```
Comment (ScoutHarris) [inline WordPress/Classes/ViewRelated/Menus/MenuItemSourceFooterView.m]: This could just be `!self.activityIndicator.isAnimating`.

**Review by ScoutHarris — APPROVED** [review]
I have one minor comment. Otherwise, looks great!

:shipit:

**Comment by mindgraffiti** [comment]
Thanks for the review @ScoutHarris!
