### PR TITLE
fix: Improve autosave and unsaved changes detection

### LINKED ISSUE #79: Draft posts containing media are always marked as unsaved on iOS
## Description

On **iOS only**, if a **draft** post contains a **media** block, the post remains marked as "unsaved" even after saving the draft. 

## Step-by-step reproduction instructions

1. Create a new post in the editor. 
2. Add an Image block. 
3. Tap the more menu (three-horizontal dots) in the top-right corner. 
4. Tap _Save Draft_. 
5. Exit the editor after the draft saves. 

## Expected behaviour

The editor closes without prompting to save edits. 

## Actual behaviour

The editor prompts to save edits. 

## WordPress information

-   WordPress version: 
-   Gutenberg version: 
-   Are all plugins except Gutenberg deactivated? 
-   Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information

-   Device:  iPhone SE
-   Operating system:  iOS 18.2
-   WordPress app version:  25.7

### PR DESCRIPTION
**Pull request by dcalhoun**
Detecting content changes by comparing the content received from
GutenbergKit to the latest server-provided post content is problematic
as the server makes slight modifications to content markup, creating
perpetually changed content. We now rely upon GutenbergKit's `changed`
parameter as the source of truth.

Embrace the existing `Autosaver` utility so the frequency is higher, as
the utility includes both a time interval and a number of changes count
which determine whether an autosave should occur. This also further
aligns GutenbergKit's behavior with Gutenberg Mobile.

Fix https://github.com/wordpress-mobile/GutenbergKit/issues/79.

Related: 
- https://github.com/wordpress-mobile/GutenbergKit/issues/79
- https://github.com/wordpress-mobile/GutenbergKit/pull/104
- https://github.com/wordpress-mobile/WordPress-Android/pull/21698

To test: 

**1: Posts with media do not have unsaved changes after saving**
See https://github.com/wordpress-mobile/GutenbergKit/issues/79. 

**2: Posts with changes warns when closing the editor**
1. Open a post. 
2. Make changes. 
3. Close the editor. 
4. Verify the editor notifies of unsaved changes. 

**3: Editor manages Publish/Update button enabled state**
1. Open a publish/draft post. 
2. Verify the _Publish_ or _Update_ button is disabled. 
3. Make changes. 
4. Verify the _Publish_ or _Update_ button is enabled. 

**4: Local changes are persisted on quit**
1. Open a post. 
2. Make changes. 
3. Quit the app. 
4. Verify changes are persisted locally, indicated by the app opening the editor with the changes when launching the app. 

## Regression Notes
1. Potential unintended areas of impact
    Unlikely with this dependency upgrade.
6. What I did to test those areas of impact (or what existing automated tests I relied on)
    N/A.
7. What automated tests I added (or what prevented me from doing so)
    N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>Modules/Package.swift</code> was changed without updating its corresponding <code>Package.resolved</code>. Please resolve the Swift packages as appropriate to your project setup (e.g. in Xcode or by running <code>swift package resolve</code>).</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift [hunk 1]
```diff
@@ -68,10 +68,12 @@ class NewGutenbergViewController: UIViewController, PostEditor, PublishingEditor
     // MARK: - GutenbergKit
 
     private let editorViewController: GutenbergKit.EditorViewController
-    private weak var autosaveTimer: Timer?
+
+    lazy var autosaver = Autosaver() {
+        self.performAutoSave()
+    }
```
Comment (dcalhoun) [inline WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift:74]: Reinstated the use of `Autosaver` as it is a far more robust implementation, including triggering persistence if a number of changes threshold is crossed.

File: WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift [hunk 2]
```diff
@@ -266,15 +264,14 @@ class NewGutenbergViewController: UIViewController, PostEditor, PublishingEditor
...
-        // TODO: read title as well
         let startTime = CFAbsoluteTimeGetCurrent()
         let editorData = try? await editorViewController.getTitleAndContent()
         let duration = CFAbsoluteTimeGetCurrent() - startTime
         print("gutenbergkit-measure_get-latest-content:", duration)
 
         if let title = editorData?.title,
            let content = editorData?.content,
-           title != post.postTitle || content != post.content {
+           editorData?.changed == true {
```
Comment (dcalhoun) [inline WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift:274]: This allows GutenbergKit to dictate that content changed, rather than comparing Gutenberg's content against the server's content, which is problematic as the server makes subtle changes to the content markup—e.g., adding spaces.

**Comment by kean** [comment]
It makes sense, although I wish the was a way to create a normalized version of a post.

I noticed a bit of an issue with undoing the change (see video). The "Update" button is still highlighted (minor issue). The "Back" button actually closes the editor without saving. I'm not entirely sure why.

https://github.com/user-attachments/assets/04236edf-2fa4-4bf4-b9f5-c011b46ddb8d

**Review by kean — APPROVED** [review]

**Comment by dcalhoun** [comment]
> The "Update" button is still highlighted (minor issue). The "Back" button actually closes the editor without saving. I'm not entirely sure why.

This relates to the `AutosaveMonitor` not communicating an autosave to the host whenever the post is [considered "clean."](https://github.com/WordPress/gutenberg/blob/db7153125f6dcbd7135ac12af3adc6e56f96109f/packages/editor/src/components/autosave-monitor/index.js#L39-L42) 

1. Clean post. 
2. Add character to title.
3. Post is marked dirty → host is notified (Update button enabled). 
4. Remove character from title, reverting post to its original state. 
5. Post is marked clean → host is [_not_ notified](https://github.com/WordPress/gutenberg/blob/db7153125f6dcbd7135ac12af3adc6e56f96109f/packages/editor/src/components/autosave-monitor/index.js#L70-L73) (Update button remains enabled).
6. Request close editor → [request latest content](https://github.com/wordpress-mobile/WordPress-iOS/blob/fb4d598eccbfc9f5576cd7d5296dffcf668b835c/WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift#L580-L582) → post title matches original title → editor closes without notice.
