### PR TITLE
Remove the Core Data workaround in EditorMediaUtility

### LINKED ISSUE #20630: NSInvalidArgumentException: nil is not a valid object ID
Sentry Issue: [JETPACK-IOS-1B8](https://a8c.sentry.io/issues/4106973751/?referrer=github_integration)

```
NSInvalidArgumentException: nil is not a valid object ID
  File "EditorMediaUtility.swift", line 23, in AuthenticatedImageDownload.main
  File "EditorMediaUtility.swift", line 22, in AuthenticatedImageDownload.main
  File "CoreDataHelper.swift", line 189, in CoreDataStack.performQuery<T>
  File "<compiler-generated>", in CoreDataStack.performQuery<T>
  File "<compiler-generated>", in thunk for closure
...
(18 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by crazytonyli**
This is an attempt to fix #20630. The issue is the `NSManagedObjectContext.existingObject(with:)` call in `AuthenticatedImageDownload` throws an Objective-C exception.

The root cause is unknown. But this PR cleans up the code that accesses Core Data objects. Hopefully now that the Core Data objects (`Post` and `Blog` instances) are now used correctly, the issue would go away.

There are two main code changes:
1. `AuthenticatedImageDownload` no long access `NSManagedObject`. It used to have code to query `Blog`. The code is now moved to its caller.
2. The caller `EditorMediaUtilit.downloadImage` function is refactored to access the `Post` argument safely using `performAndQuery`.

> **Note**
> It might be easier to review this PR [with "Hide whitespace" option on](https://github.com/wordpress-mobile/WordPress-iOS/pull/21227/files?diff=unified&w=1).

## Test Instructions

Make sure Gutenberg editor and Aztec editor both can still load images.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
What's described in the Test Instructions.

4. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

File: WordPress/Classes/Networking/MediaHost+Blog.swift [hunk 1]
```diff
@@ -8,6 +8,13 @@ extension MediaHost {
...
     }
 
+    init(with blog: Blog) {
+        self.init(with: blog) { error in
+            // We'll log the error, so we know it's there, but we won't halt execution.
+            WordPressAppDelegate.crashLogging?.logError(error)
+        }
+    }
+
     init(with blog: Blog, failure: (BlogError) -> ()) {
```
Comment (mokagio) [inline WordPress/Classes/Networking/MediaHost+Blog.swift:18]: Have you considered using argument default for this over a dedicated init?

E.g.

```swift
init(
    with blog: Blog,
    failure: (BlogError) -> () = { error in
        // ...
    }
) {
```

Granted this approach assumes that the logging mechanism will remain a singleton shared instance, which might not be desirable in the future.

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift [hunk 2]
```diff
@@ -8,66 +8,24 @@ final class AuthenticatedImageDownload: AsyncOperation {
     }
 
     let url: URL
-    let blogObjectID: NSManagedObjectID
+    let mediaHost: MediaHost
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:11]: From the PR description:

> `AuthenticatedImageDownload` no long access `NSManagedObject`. It used to have code to query `Blog`. The code is now moved to its caller.

Just wanted to +1 this decision. Aside from the hunch that this will help with #20630, having the image download operation know about `MediaHost` over `Blog` seems like a better design because the surface of information it can access (thus that we need to be aware of when working with it) is now much smaller.

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift [hunk 3]
```diff
@@ -165,38 +123,82 @@ class EditorMediaUtility {
...
+            } catch {
+                // Send Objective-C exceptions to Sentry for further diagnosis.
+                WordPressAppDelegate.crashLogging?.logError(error)
+                throw error
+            }
+
+            return try object.get()
+        }
+
+        let post = try safeExistingObject(postObjectID) as! Post
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:180]: This is neat.

Hopefully we won't have to use it again, but just in case, I wonder how we could make it more discoverable / flexible so other people can reuse it? 🤔

**Review by mokagio — APPROVED** [review]
> Make sure Gutenberg editor and Aztec editor both can still load images.

I verified this via the Jetpack installable build.

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:180]: I really hope that this PR fixes the issue and makes the extra Objective-C exception become unnecessary. That means we can delete this ugly try catch.

I don't want to move this into a shared places because I don't think we should catch the `NSInvalidArgument` exception, which to me feels like an indication of programming error, rather than Core Data data accessing error.
