### PR TITLE
Fixes web stats for Jetpack sites

### LINKED ISSUE #3508: Stats web view fails for Jetpack sites
Since #3308, `-[StatsWebViewController authStats]` will fail for Jetpack sites.

The reason is that we're not storing passwords for wp.com accounts, so it will throw an assertion in Debug builds and probably fail to authenticate in production.

```obj-c
    NSString *username = blog.isWPcom ? blog.username : blog.jetpackUsername;
    NSString *password = blog.isWPcom ? blog.password : blog.jetpackPassword;

    //...
    
    NSURLRequest *request = [WPURLRequest requestForAuthenticationWithURL:loginURL
                                                              redirectURL:redirectURL
                                                                 username:username
                                                                 password:password
                                                              bearerToken:blog.authToken
                                                                userAgent:nil];
```

Since `blog` is the Jetpack site, `authToken` will be `nil`, and `blog.jetpackPassword` will also be `nil`.

### PR DESCRIPTION
**Pull request by koke**
Since we don't store wp.com passwords anymore, this makes
`blog.authToken` return the Jetpack account's token for Jetpack blogs.

Fixes #3508 

*Testing note:* make sure to set `WPJetpackRESTEnabled` to NO (normally enabled on Debug builds). Otherwise, Jetpack sites turn into wp.com sites and the original issue doesn't appear.

### CODE REVIEW

**Comment by koke** [comment]
@astralbodies can you take a look? :smile:

File: WordPress/Classes/Models/Blog+Jetpack.m [hunk 1]
```diff
@@ -225,6 +225,15 @@ - (NSNumber *)jetpackDotComID
     return [self jetpackBlogID];
 }
 
+- (NSString *)jetpackAuthToken
+{
+    if ([self isWPcom]) {
+        return [self jetpackAuthToken];
```
Comment (astralbodies) [inline WordPress/Classes/Models/Blog+Jetpack.m]: This always wigs me out when I see swizzling :worried: - calling the "wrong" method. :wink:

**Comment by astralbodies** [comment]
I think it looks good and simplifies things. I dislike swizzling in general but since it's worked well so far why stop. :stuck_out_tongue_closed_eyes: 

:shipit:
