### PR TITLE
Work around to correctly set the metaPublishImmediately flag.

### LINKED ISSUE #3886: Page list UI breaks when publishing new page.
There is an issue with the page list where, when a new page is created, and it is the only item in its section, an error will be thrown and the table view UI will be broken until the user exists and reenters the list. 

The error:
```
2015-06-18 10:28:57.772 WordPress[3389:34113] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /SourceCache/UIKit_Sim/UIKit-3347.44/UITableView.m:1623
2015-06-18 10:29:03.045 WordPress[3389:34113] CoreData: error: Serious application error.  An exception was caught from the delegate of NSFetchedResultsController during a call to -controllerDidChangeContent:.  Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (3) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). with userInfo (null)
```
This is triggered when the section the draft page was in is suddenly empty, thus removed, and replaced by the following section.  The framework treats this as an inconsistency in the number of rows after the update.  The cause is the newly created page is incorrectly sorted after its initial save. 

Props @koke for the discovery.

### PR DESCRIPTION
**Pull request by aerych**
Fixes an issue sorting pages.

Fixes #3886 

This is a rather hacky patch but takes advantage of an existing initialization feature. A better fix would probably be to set all of these properties as the default values in the model.   Let's follow up up with a PR doing that in the develop branch. 

To test:
- Open your page list. 
- If you have any pages already created today, move them into drafts or the trash. 
- Tap to create a new page. 
- Add a title and content and save. 
- The page should show up with the correct title under the "today" section and the UI should still be responsive. 

cc @koke, @sendhil 

Needs Review: @sendhil

### CODE REVIEW

File: WordPress/Classes/Services/PostService.m [hunk 1]
```diff
@@ -492,6 +492,10 @@ - (void)restorePost:(AbstractPost *)post
 - (void)initializeDraft:(AbstractPost *)post {
     post.remoteStatus = AbstractPostRemoteStatusLocal;
     post.status = PostStatusPublish;
+
+    // Hack: The date_create_gmt should arleady be nil for a draft but
```
Comment (sendhil) [inline WordPress/Classes/Services/PostService.m]: Could you attach your name and a date to this? e.g. `HACK(aerych, 6/18/2015):...`

Comment (aerych) [inline WordPress/Classes/Services/PostService.m]: Yes indeed.

**Comment by sendhil** [comment]
Looks good to me.
