### PR TITLE
Show standard notice for network errors on the Media Library

### LINKED ISSUE #10941: Media: Improve offline error message in media library
Reported by @sedocirp7 in beta testing:

### Expected behavior

When not connected to the internet, I expect to see a clear message about being offline, such as the one I see when I open my Blog Posts:

> Unable to Sync
> The internet connection appears to be offline.

### Actual behavior

In a site's Media Library, the offline error message is vague — it doesn't mention that you appear to be offline:

> Media Library
> There was a problem when trying to access your media. Please try again later.

image

### Steps to reproduce the behavior

1. Go offline (e.g. airplane mode).
2. Open My Sites.
3. Open the site's Media section.

### LINKED ISSUE #11320: Remove Media library alert displayed on top of empty view when no connection.
Steps:
- Be offline
- Go to media 
See alert.
IMG_3665

### PR DESCRIPTION
**Pull request by SergioEstevao**
We are also disabling the default error message displayed by the
WPMediaPicker and not showing any message and use the no view screen
when media is empty.

Fixes #11320 
Fixes #10941 

To test:
 - Start the app
 - Navigate to a post where you never synced the media library before
 - Turn off the Internet Connection for the device
 - Open the Media Library
 - Check if the custom empty view shows a no extra alert is presented
 - Exit the Media Library
 - Turn on the internet connection
 - Renter the media library
 - Check that media assets shows
 - Turn off the connection again
 - Pull to refresh
 - See if a notice shows up with an easy to understand message.
 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift [hunk 1]
```diff
@@ -595,6 +595,15 @@ extension MediaLibraryViewController: WPMediaPickerViewControllerDelegate {
 
         updateViewState(for: pickerDataSource.numberOfAssets())
     }
+
+    func mediaPickerController(_ picker: WPMediaPickerViewController, handleError error: Error) -> Bool {
+        let nserror = error as NSError
+        if let mediaLibrary = self.blog.media, !mediaLibrary.isEmpty {
+            let title = NSLocalizedString("Unable to Sync", comment: "Title of error prompt shown when a sync the user initiated fails.")
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift:602]: Totally nitpicking but I think sync should be lowercase and also could we say  "Unable to  sync media"?

Comment (SergioEstevao) [reply WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift:602]: I copied the string from other places is being used, in order to keep the translations.

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift:602]: Oh I see

**Comment by yaelirub** [comment]
@SergioEstevao , Im a bit confused by how to test this or what screen I should see and what message I should not see. Can you please share screenshots / gif ?
This is what Im seeing when Im offline and don't have any images in the media library:
Simulator Screen Shot - iPhone 11 Pro - 2020-04-16 at 12 20 00

**Comment by SergioEstevao** [comment]
> @SergioEstevao , Im a bit confused by how to test this or what screen I should see and what message I should not see. Can you please share screenshots / gif ?
This is what Im seeing when Im offline and don't have any images in the media library:

You shouldn't see any alert on this implementation, if you don't have images you should just see
the no connection background view. If you have images already cached you should see those and an "toast" saying that you have a network problem.

**Comment by yaelirub** [comment]
Tested and works as expected. Thanks for working on this and for your patience, @SergioEstevao :)
