### PR TITLE
Fix formatting issue on Reader post

### LINKED ISSUE #9564: Formatting issue on Reader post
[This post](https://wordpress.com/read/feeds/27083162/posts/1746290142) is showing up with the last lines overlapping each other. ([Non-reader url](https://href.li/?https://stephencwinter.com/2018/01/26/a-personal-reflection-on-logres-and-the-matter-of-britain-by-stephen-winter/))

Only happens on iOS. Verified to show correctly on the web/Android.

img_0616

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #9564 

This issue was a bit tricky. It was described as "Lines overlapping each other".
After a quick check, I notice that also an image was missing.

This specific issue (with this posts in particular) is related to three components: **HR**, **IMG**, **Paragraph**

```html
    ....
    <p>
        <em>David Llewellyn Dodds, Guest Editor
        </em>
    </p>
    <!-- Issue start here -->
    <hr>
    <a href="http://apilgriminnarnia.com/?attachment_id=7546">
        <img class="aligncenter wp-image-7546 " src="https://stephencwinter.files.wordpress.com/2018/01/james-archer-le-mort-arthur-e1516801625681.jpg?w=562&#038;h=343" height="343" width="562">
    </a>
    It may feel, for the inhabitants of the British Isles, that recent years have been particularly unsettled. The referendum…
```
None of those components are surrounded by `<p>` tags, but all the other components are.
I'm not sure if that is a bug by itself or how was that possible.

A fast test injecting surrounding `<p>` tags to the `img` and `paragraph` solved the issue, so it's clear that the issue is related to that.

With some debugging I pinpoint the problem to the [replaceHorizontalRuleMarkers](https://github.com/wordpress-mobile/WordPress-iOS/blob/51d6c867ea76b5b0b2adb62650ff92e4efd982ab/WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift#L94) method.

Another fast test shows that deleting the line `107` (`mParagraphStyle.maximumLineHeight = 1.0`) partially solves the problem.

With that information I assume that, when converting the html code to attributed text without the `<p>` tags, the `NSAttributedText` instance assumes that those three elements are in the same paragraph, and when adding the HR paragraph styles specifying a maximum height of `1`, the three elements in it are affected.

Finally, I noticed that a _"healthy"_ HR placeholder looks like this:
`WPHORIZONTALRULEIDENTIFIER\nSomething else`
With a `\n` after the `WPHORIZONTALRULEIDENTIFIER`

And the HR placeholder with the problem looks like this:
`WPHORIZONTALRULEIDENTIFIERIt may feel, for `

### The solution

This proposed solution is to check if the character after the placeholder is a `\n`, and if not, we insert it. This separates the HR paragraph from whatever is next, solving the issue.

before_after

To test:

- Open [this post](https://wordpress.com/read/feeds/27083162/posts/1746290142) that has the problem.
- Check that it renders correctly.
- Open [this post](https://wordpress.com/read/feeds/75463728/posts/1977737837) that has a few "normal" HR.
- Check that it renders exactly as before.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift [hunk 1]
```diff
@@ -119,12 +119,24 @@ class WPRichTextFormatter {
...
+                attachmentString.append(NSAttributedString(string: "\n"))
+            }
+
             attrString.replaceCharacters(in: range, with: attachmentString)
         }
 
         return attrString
     }
 
+    func needsAppendNewLine(to string: String, at nsRange: NSRange) -> Bool {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift]: The method name is kind of generic but its solving a specific glitch.  Since this is specific to horizontal rules, would it make sense to tweak the method name to reflect that?
