### PR TITLE
Post and Pages List: Do not present network alert when composing posts / pages

### LINKED ISSUE #9025: Can't compose offline
### Expected behavior

I should be able to compose a post while offline.

### Actual behavior

I keep getting this alert while trying to create a post while on Airplane mode.

image uploaded from ios 3

Note: This works correctly on version 9.6 of the app.

### Steps to reproduce the behavior

Start composing a post and turn airplane mode on.

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #9025 , as suggested, by:

1. AbstractPostListViewController should only display an alert if it's topmost
2. It should only attempt to display an alert if the refresh was user initiated. We should pass a parameter to the refresh method to indicate whether the refresh was caused by the user (pull to refresh) – only in that situation should we display the alert.
To test:

Navigate to the Post list
1. Start composing a post.
2. Turn on airplane mode. There should be one and only one alert.
It should be possible to compose a post and save it as draft (locally)

First discussion here: #9038

### CODE REVIEW

**Comment by ctarda** [comment]
There was some discussion about a parameter name [a parameter name](https://github.com/wordpress-mobile/WordPress-iOS/pull/9038/files/15b194817b22a323857decd1836417c64c3c4983#diff-cadb926e12a69498840fecbf9a11912a)

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 1]
```diff
@@ -603,9 +605,13 @@ class AbstractPostListViewController: UIViewController, WPContentSyncHelperDeleg
         }
     }
 
+    func shouldPresentAlert() -> Bool {
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: Is this used anywhere?

**Comment by diegoreymendez** [comment]
@frosty had reviewed this, but I took the time to re-test.  It's working fine.
