### PR TITLE
Issues/6332 preserve in use content

### LINKED ISSUE #6332: Reader: Don't delete reader posts while they are in use.
This is a follow up to the crash described in #6297.  Ideally, when syncing is completed we do not want to have deleted from core data any posts the user was currently using. 

Let's add a new boolean field to ReaderPost called "inUse" or something similar and set it to true when a post is being used by a detail vc.  When a sync completes and the new posts are merged to core data, rather than deleting posts missing from a batch that are also marked as inUse, we'll just nullify their topic relationship.   This allows the post to continue to be present in core data for the user's needs, while still removing it from the posts for the topic.  Like any other "orphan" post it will be cleaned up during the next launch of the app (assuming its not needed for state restoration.)

This will be a more robust fix for situations like #6297 and we can then remove the band-aid patch in #6305.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6332
This patch supersedes what was in #6352 for a cleaner model revision.

To test:
Repeat the steps outlined in #6297.
Confirm that the post is not deleted (watch for the NSLog or set a breakpoint), that instead its topic is set to nil, and there is no crash.

Needs review: @koke

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift [hunk 1]
```diff
@@ -84,9 +84,10 @@ import WordPressShared
             restorableSelectedIndexPath = defaultIndexPath
         }
 
-        cleanupStaleContent(removeAllTopics: false)
+        unflagInUseContent()
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift]: I'm a bit concerned that this is on the application launch execution path. I profiled on an iPad Mini 1, and it "only" added 30 ms, but I imagine it could be more if it had more posts in Core Data. I can't think of a better way to do this though. If it's a problem, core data batch updates could help a bit. I'm not sure how much of a problem this actually is though.

**Comment by aerych** [comment]
> I tried the steps in #6297 and got a different (but familiar?) crash

Try as I might, I can't reproduce this one. Any chance it could be an issue due to switching between branches or something similar?

File: WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift]: I'm not too worried about it, but if you have a strong concern we could move this call to a `UIApplicationWillTerminate` notification observer.  I think it might makes things a bit less obvious but some extra documentation would help.   Thoughts?

**Comment by koke** [comment]
> Any chance it could be an issue due to switching between branches or something similar?

Maybe? I can't reproduce it now either

**Comment by koke** [comment]
:shipit: once conflict is solved

**Comment by aerych** [comment]
Many thanks @koke !!
