### PR TITLE
Fix Activity Log and Plugins not working on Jetpack

### LINKED ISSUE #20471: Activity Log and Plugins not functional on Jetpack
### Expected behavior
Activity log and Plugin to load normally

### Actual behavior
Activity Log never loads, and Plugins shows "Error loading plugins" message.

### Steps to reproduce the behavior

1. Run the WordPress app
2. Log in to an account that has a connected self-hosted site
3. Logout
4. Run the Jetpack app
5. Log in to the same account from step 2
6. Navigate to the Menu
7. Navigate to Activity Log
8. Notice that the screen never finishes loading
9. Go back
10. Navigate to Plugins
11. Notice that the installed plugins never load and shows an error message.

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #20471
Ref: p1680581589932799/1680567166.180859-slack-C0180B5PRJ4

## Description
Fixes an issue where Activity Log and Plugins wouldn't load normally on Jetpack.

## Testing Instructions

1. Run the WordPress app
2. Log in to an account that has a connected self-hosted site
3. Logout
4. Run the Jetpack app
5. Log in to the same account from step 2
6. Navigate to the Menu
7. Navigate to Activity Log
8. Make sure the Activity Log list loads normally
9. Go back
10. Navigate to Plugins
11. Make sure the Installed Plugins section loads normally.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/CredentialsService.swift [hunk 1]
```diff
@@ -10,13 +10,12 @@ struct KeychainCredentialsProvider: CredentialsProvider {
...
     private let provider: CredentialsProvider
-    private let dotComOAuthKeychainService = "public-api.wordpress.com"
 
     init(provider: CredentialsProvider = KeychainCredentialsProvider()) {
         self.provider = provider
     }
 
     func getOAuthToken(site: JetpackSiteRef) -> String? {
-        return provider.getPassword(username: site.username, service: dotComOAuthKeychainService)
+        return provider.getPassword(username: site.username, service: AppConstants.authKeychainServiceName)
```
Comment (staskus) [inline WordPress/Classes/Services/CredentialsService.swift:19]: As I understand, this is the main place of the fix. Using correct `authKeychainServiceName` based on the app, and not a static "public-api.wordpress.com".

Then this `CredentialsService` is used in `ActivityStore` and `PluginStore`. This is the reason Activity log and plugins weren't working.

**Review by staskus — APPROVED** [review]
Thanks for the fix!

I tested on:
1. TestFlight Jetpack & WordPress 22.0.0.2 and reproduced the issue
2. This branch and didn't reproduce the issue

The code changes make sense. I haven't identified any more usage of static `public-api.wordpress.com` definitions for keychain service.

**Review by momo-ozawa — APPROVED** [review]
Thank you for fixing this!

**Review by dvdchr — APPROVED** [review]
Thank you for fixing this! I can also confirm that Activity Log now works on Jetpack when testing this branch.

**Comment by dvdchr** [comment]
CI build [failed](https://buildkite.com/automattic/wordpress-ios/builds/13535):

```
🔬 UI Tests (iPhone): 1 failure(s)
testSupportForumsCanBeLoadedDuringLogin in WordPressUITests.SupportScreenTests

🔬 Unit Tests: 1 failure(s)
testDataSourceReceivesRequestedCount in WordPressTest.TenorDataSourceTests
```

 [Rebuilding](https://buildkite.com/automattic/wordpress-ios/builds/13539).

**Comment by mokagio** [comment]
Thank you for taking a look at the builds @dvdchr 🙇‍♂️ 

Worth noting that those test failure annotations were for flaky tests and that the UI tests job was green:

image

#20378 will help make those failures clearer.

The prototype build steps legit failed, but the issue there was with the tooling not the code changes.

image

Also, for the next time, it's more resource efficient to retry individual failed steps as opposed to rerun the entire pipeline 🤓:

Screenshot 2023-04-04 at 7 16 26 pm

Thanks!

**Comment by mokagio** [comment]
Taking over merging to move on with the hotfix process. The CI failures are with installable builds and are unrelated to the code changes.

File: WordPress/Classes/Services/CredentialsService.swift (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/Services/CredentialsService.swift:19]: Yes, exactly!
