### PR TITLE
Onboarding Improvements: Fix UI tests

### LINKED ISSUE #17390: Onboarding Improvement: Update UI tests
## Description

Update the UI tests to accommodate the changes made to the Login flow

## Task

- [x] Make sure UI tests pass on CI #17561

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #17390 

## Description

This PR fixes the broken UI tests in the Login flow. 
- Added a new QuickStart prompt Screen Object
- Added a method to dismiss the QuickStart prompt if needed

### Local
1. Run `rake mocks`
2. Test the WordPressUITests target
3. ✅ Tests should succeed

### CI
1. ✅ Buildkite UI tests should be green

## Regression Notes
1. Potential unintended areas of impact
UI tests

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Ran the tests locally and confirmed they succeeded

3. What automated tests I added (or what prevented me from doing so)
UI tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift [hunk 1]
```diff
@@ -366,7 +366,13 @@ extension WordPressAuthenticationManager: WordPressAuthenticatorDelegate {
             // If the quick start prompt has already been dismissed,
             // then show the My Site screen for the specified blog
             guard !self.quickStartSettings.promptWasDismissed(for: blog) else {
-                self.windowManager.dismissFullscreenSignIn(blogToShow: blog)
+
+                if self.windowManager.isShowingFullscreenSignIn {
+                    self.windowManager.dismissFullscreenSignIn(blogToShow: blog)
+                } else {
+                    navigationController.dismiss(animated: true)
+                }
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift:374]: @leandroalonso 
This accounts for the case when we're already logged in, and we add a self-hosted site via the site switcher.
The UI test below caught this case -- phew!
https://github.com/wordpress-mobile/WordPress-iOS/blob/3675ad4ed9bc44dd374a2b2b10c1fdf6efb587d1/WordPress/WordPressUITests/Tests/LoginTests.swift#L73-L75

**Review by leandroalonso — APPROVED** [review]
