### PR TITLE
Account Settings Primary Site: show URL if site has no name

### LINKED ISSUE #5884: Empty primary site field in Account Settings
### Expected behavior

I expect "Primary Site" field to be always filled with either the blog name or the url.
### Actual behavior

If the blog name is empty for a site, "Primary Site" field would be empty.
### Steps to reproduce the behavior

Remove the name of a blog and navigate to "Account Settings" screen.
##### Tested on [device], iOS [version], WPiOS [version]

Should be the same for all device and versions (tested on a branch)

/cc @jleandroperez

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #5884

In Account Settings > Primary Site, if the site has no name, the site URL will now be displayed.

To test:

---
- Remove the primary site Title. (site > Settings > Site Title)
- Go to Account Settings > Primary Site.
- Verify the URL is displayed.

---
- Give the primary site a Title.
- Go to Account Settings > Primary Site.
- Verify the Title is displayed.

---
Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift [hunk 1]
```diff
@@ -88,6 +87,10 @@ private class AccountSettingsController: SettingsController {
             action: presenter.push(editEmailAddress(settings, service: service))
         )
 
+        // If the primary site has no name, then show the URL.
+        var primarySiteName = settings.flatMap { service.primarySiteNameForSettings($0) }
+        primarySiteName = (primarySiteName == nil || primarySiteName == "") ? settings?.webAddress : primarySiteName
+
```
Comment (danielebogo) [inline WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift]: If you prefer instead of `primarySiteName  == ""` you can do `primarySiteName.isEmpty`, or you can even simplify with `(primarySiteName?.isEmpty ?? true) ? .................`

Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift]: Hey @danielebogo . I used `primarySiteName == ""` because `primarySiteName` is an optional and I didn't want to unwrap it just for this test. However, your suggestion of `(primarySiteName?.isEmpty ?? true)` is _much_ better! It shall be changed. Thank you!

**Comment by designsimply** [comment]
I spoke too soon! Further beta testing revealed that the `Site Title` field is simply reflecting the `Web Address` field and I filed a separate issue for that at https://github.com/wordpress-mobile/WordPress-iOS/issues/11716.
