### PR TITLE
Tag Picker UI (with completion)

### LINKED ISSUE #6611: Post Options: Improve UI of the tag field
### Expected behavior
To receive feedback on the tags I'm creating

### Actual behavior
The tags field is a little confusing, and offers no feedback as to whether I have the format correct. Confusingly, it doesn’t show spaces typed at the end of the text until I type another non-space character.

### Steps to reproduce the behavior
1) Create a new post
2) Open the Options page
3) Begin typing in the Tags field, including spaces

This shows that spaces don't show up until another non-space character is typed:
ios-tag-ui

It would nice to mimic the Calypso web feature of marking tags once they're added.  It also provides auto-complete for existing tag names.  You can't see it in this animation, but the tags are transformed once you type a comma.

ios-tag-calypso

### PR DESCRIPTION
**Pull request by koke**
Tags, it's here. 

tag-picker

## What this does

This move the tag editing in the post options to it's own view. The new tag picker is a text field that suggests previously used tags as you type.

## What was left out

I couldn't get to everything I'd liked to, but I think this is solid enough for a release, and so much better than the previous implementation. For the future:

- Visually treating the tag items as items that can be tapped to be removed. I so wanted this, but I believe it might take as much work as the rest of it, so not yet.
- The text field grows automatically as you add more lines, but it does so indefinitely. If you have too many tags you might not be able to edit them. I've tried everything I could think of, but every solution had its set of drawbacks. Not super happy about this, but this seem like the least bad option until we figure it out.
- Caching. Every time the picker is presented the tags are loaded from the network. This is wasteful and less than optimal, but I think I'll wait for the network improvements. Outside of testing, I wouldn't expect that much back and forth between post options and the tag picker.

Fixes #6611

### CODE REVIEW

**Comment by elibud** [comment]
This is amazing, it feels so good to have autocomplete on tags 🎉

I didn't review the code yet because I know you want to make some changes, so here's my feedback on the functionality.

- Overall the UI is great, super fast and responsive.

- The filtering is just perfect, I love it!

- Selecting existing tags is super fast <- I imagine this is the most common use case and it works great.

Small issues:

- For some reason the sorting doesn't match Calypso. The query we are making is correct but on the web the tags order is different. They may be using some extra undocumented param?

- If the initial post tags don't fit into one line, shouldn't we display the necessary lines as soon as you enter the VC instead of waiting for you to type? But then, if we do this, what happens when you have too many tags...

- I don't think we can scroll to the last rows in the table view when the keyboard is being displayed.

- It feels a bit odd that if I come in and out of the view I get the "Loading" every time, could we cache the tags and display the cached result until we receive the newest?

- It's hard for me to know that I've created a new tag, but I know we will address this on a second iteration.

And a tiny bug:

Entering the TagsVC edits the tags field adding a space after every comma. This causes the Editor to detect changes and enable the Update button. For example this tags:
`popo,elisa,featured,flota,mouse` become `popo, elisa, featured, flota, mouse` just for entering the TagsVC.


Thanks for tackling this, it is such a great addition to the app :) I know users are going to love it.

**Comment by koke** [comment]
> For some reason the sorting doesn't match Calypso. The query we are making is correct but on the web the tags order is different

https://github.com/Automattic/wp-calypso/issues/13603

**Comment by koke** [comment]
Checklist to keep track of all the feedback:

- [ ] Similar style to mail/calendar: the list of suggestions has a gray background, and the text field is white, with a drop shadow that indicates that the list is underneath it.
- [ ] Making the padding inside the text field consistent with the padding on the items in the autocomplete list
- [ ] Making sure the text inside the text field is vertically centered
- [ ] Ensure text view adjusts its height on initial presentation
- [ ] Limit text view height to something reasonable (3-4 lines?)
- [ ] Investigate caching options. I'll probably leave it out of this PR, but at least write down the conclusions.

And a couple other wishlist items from design feedback:

- Visually treating the tag items already in the list differently, not as text but as items that can be tapped to be removed
- Highlight the part of the autocompleted text that’s matching what I typed

File: WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift [hunk 1]
```diff
@@ -0,0 +1,402 @@
...
+        title = NSLocalizedString("Tags", comment: "Title for the tag selector view")
+    }
+
+    required init?(coder aDecoder: NSCoder) {
+        fatalError("init(coder:) has not been implemented")
+    }
+
+    fileprivate let textView = UITextView()
+    private let textViewContainer = UIView()
+    private let shadow = ShadowView()
```
Comment (elibud) [inline WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift]: Is there any reason to use our own custom class instead of doing something like:

```
textViewContainer.layer.masksToBounds = false
textViewContainer.layer.shadowOffset = CGSize(width: 0, height: 2)
textViewContainer.layer.shadowRadius = 2
textViewContainer.layer.shadowOpacity = 0.5
textViewContainer.layer.shadowColor = WPStyleGuide.greyDarken30().cgColor
```
And add the tableview as a subview before the textViewContainer? I think the end result is quite good and we avoid adding an extra view to the hierarchy (with all the constraints and that I think that's a big plus)

simulator screen shot may 11 2017 10 18 04

File: WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift [hunk 2]
```diff
@@ -0,0 +1,402 @@
...
+        return 1
+    }
+
+    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
+        return 1
+    }
+
+    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
+        let cell = tableView.dequeueReusableCell(withIdentifier: FailureDataSource.cellIdentifier, for: indexPath)
+        WPStyleGuide.configureTableViewSuggestionCell(cell)
```
Comment (elibud) [inline WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift]: Do you think it makes sense to use a different color configuration for the failure cell? Maybe `cell.textLabel?.textColor = WPStyleGuide.errorRed()`?

Comment (koke) [inline WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift]: As it's not a critical/blocking error, I think the red would be too much.

Comment (elibud) [inline WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift]: I kind of missed the message when I tested on Airplane mode though, so I would like to differentiate it a bit from Loading, but yeah, red might be too much...

**Comment by koke** [comment]
> Maybe a last minutes change?

Yes, I tried too many things and forgot that one there :)

I've removed that constraint and took your code for the shadow. Ready for another look

**Comment by elibud** [comment]
I have one question and one more suggestion:

Q: What should we do when the user manually enters a tag that is already in the post? Should we delete it when they put the ',' to reflect that is already there? (the current behavior is not terrible, since they will be cleaned up upon post save, but it looks odd if I type: azul, azul, verde)

S: I think we should include an explanation of how to enter tags, something explaining that they are comma separated. It could be visible only when the TableView is not, so below the TextField, what do you think?

**Comment by koke** [comment]
> What should we do when the user manually enters a tag that is already in the post?

Calypso deletes any duplicate as soon as you type the comma, but I find that a bit jarring. If it's going to be removed when saving I guess it's just fine to leave it and keeps the code simpler.

>  I think we should include an explanation of how to enter tags, something explaining that they are comma separated. It could be visible only when the TableView is not, so below the TextField, what do you think?

In the previous implementation there was a placeholder, I'd like to bring it back but it's not trivial on a text view. Adding a footer sounds good, but the table view is visible by default. It only hides if you are already typing and there are no matching suggestions or if you have zero tags to suggest.

**Comment by elibud** [comment]
As discussed we should create a new issue with the pending enhancements, but this is a great first version, I'm approving.
