### PR TITLE
Media Detail screen improve accessibility and hints

### LINKED ISSUE #12878: Media: detail screen navigation buttons are not accessible and image and editable fields need hints
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. In the WordPress app, go to My Site > Media.
1. Select an image and double tap to open media details.
1. Swipe right to navigate through all the elements on screen.

**Result:** [32s](https://cloudup.com/cbXD05KPrh2)

* Navigation buttons are not accessible.
* Image should be marked as a button with a proper hint.
* It would be good to add hints to editable fields.

media-detail-screen
<sup>Tested with WPiOS 13.5.0.3 (App Store version) on iPhone 6S iOS 13.2.</sup>

<p style="clear:both;"><sub>/hat tip @etoledom for the report, internal reference: p77Llu-bQ6-p2</sub></p>

### PR DESCRIPTION
**Pull request by sla8c**
Fixes #12878

To test:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
2. In the WordPress app, go to My Site > Media.
3. Select an image and tap to open media details.
4. VoiceOver through all the elements on screen.
5. Image should be marked as a button with an accessibility label and hint.
6. Editable fields have accessibility labels and hints added

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I tested in Simulator using Accessibility Inspector (I currently don't have ability to test / debug on Device)

Navigation bar accessibility was already added

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift [hunk 1]
```diff
@@ -175,6 +175,9 @@ struct MediaImageRow: ImmuTableRow {
             setAspectRatioFor(cell)
             loadImageFor(cell)
             cell.isVideo = media.mediaType == .video
+            cell.accessibilityTraits = .button
+            cell.accessibilityLabel = NSLocalizedString("Preview media", comment: "Accessibility label for media item preview for user's viewing an item in their media library")
+            cell.accessibilityHint = NSLocalizedString("Click to view media in full screen", comment: "Accessibility hint for media item preview for user's viewing an item in their media library")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift]: `Click` -> `Tap` 🙂

File: WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift [hunk 2]
```diff
@@ -239,6 +242,9 @@ struct MediaDocumentRow: ImmuTableRow {
         if let cell = cell as? MediaItemDocumentTableViewCell {
             cell.customImageView.tintColor = cell.textLabel?.textColor
             cell.showIconForMedia(media)
+            cell.accessibilityTraits = .button
+            cell.accessibilityLabel = NSLocalizedString("Preview media", comment: "Accessibility label for media item preview for user's viewing an item in their media library")
+            cell.accessibilityHint = NSLocalizedString("Click to view media in full screen", comment: "Accessibility hint for media item preview for user's viewing an item in their media library")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift]: Same as above

File: WordPress/Classes/Utility/WPImmuTableRows.swift [hunk 3]
```diff
@@ -93,6 +93,8 @@ struct EditableTextRow: ImmuTableRow {
     func configureCell(_ cell: UITableViewCell) {
         cell.textLabel?.text = title
         cell.detailTextLabel?.text = value
+        cell.accessibilityLabel = title
+        cell.accessibilityHint = value
```
Comment (frosty) [inline WordPress/Classes/Utility/WPImmuTableRows.swift]: I wonder if editable rows should also say something like 'tap to edit' 🤔 Although we would also want to check if they were enabled before doing so. We should also likely use `accessibilityValue` for the row's value.

```
cell.accessibilityLabel = title
cell.accessibilityValue = value
cell.accessibilityHint = NSLocalizedString("Tap to edit", comment: "Accessibility hint prompting the user to tap a table row to edit its value.")
```

**Review by frosty — COMMENTED** [review]
The table rows are all working well for me (just left a few small comments)!

Either in this PR or as a followup, we should also address the full screen view that appears when you tap on the main image. When I tapped to view fullscreen, Voiceover proceeded to read me a very cryptic full filename very quickly. It should probably just say that it's displaying the image full screen (maybe include the title if it has one?) and hint how to dismiss the screen.

File: WordPress/Classes/Utility/WPImmuTableRows.swift (hunk 3 above)
Comment (sla8c) [reply WordPress/Classes/Utility/WPImmuTableRows.swift]: Nice suggestion! 😄 I’ve made an update for this using isUserInteractionEnabled to check state for whether enable() or disable() was called

File: WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift (hunk 1 above)
Comment (sla8c) [reply WordPress/Classes/ViewRelated/Cells/MediaItemTableViewCells.swift]: Nice catch and Tap is much more appropriate!  Thanks! 🙂

**Review by frosty — APPROVED** [review]
Changes look good!
