### PR TITLE
Fix: Use default value for nil sitenames when displaying a notice

### LINKED ISSUE #20565: Following sites in Reader crashes Jetpack
### Expected behavior
App not to crash.

### Actual behavior
App crashed.

**Note, in this video I was not able to reproduce the crash but the steps are the same.**

https://user-images.githubusercontent.com/2092798/233234103-e2dc70d2-7c1d-4197-9ade-90ffa898c332.MOV

### Steps to reproduce the behavior
1. Reader -> Search
2. Type "adafruit"
3. Followed hackaday.com and blog.adafruit.com from the top two posts

##### Tested on iPhone 12 Pro, iOS 16.4.1, Jetpack iOS 22.2.0.0

Sentry Issue: [JETPACK-IOS-1BG](https://a8c.sentry.io/issues/4108713755/?referrer=github_integration)

```
EXC_BREAKPOINT: URLWithString:relativeToURL:
  File "ReaderHelpers.swift", in value
  File "ReaderHelpers.swift", line 368, in ReaderHelpers.dispatchToggleFollowSiteMessage
  File "ReaderShowMenuAction.swift", line 123, in ReaderShowMenuAction.execute
  File "<compiler-generated>", in thunk for closure
  File "ReaderPostService.m", line 345, in __70-[ReaderPostService toggleFollowingForPost:inContext:success:failure:]_block_invoke
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #20565 

Sometimes the `post.blogNameForDisplay()` would return nil, which throws a fatal error. I haven't figured out the exact reason why that would return nil, but this adds some mitigation steps:

- Show "Following this site" instead of crashing
- Log the message to Sentry (so we can track the frequency)

## To test

Follow the reproduction steps from #20565:

1. Reader -> Search
2. Type "adafruit"
3. Followed hackaday.com and blog.adafruit.com from the top two posts

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

N/A, no UI changes impacted or introduced.

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift [hunk 1]
```diff
@@ -365,7 +365,18 @@ struct ReaderPostMenuButtonTitles {
     }
 
     class func dispatchToggleFollowSiteMessage(post: ReaderPost, follow: Bool, success: Bool) {
-        dispatchToggleFollowSiteMessage(siteTitle: post.blogNameForDisplay(), siteID: post.siteID, follow: follow, success: success)
+        let blogName = {
+            guard let blogNameForDisplay = post.blogNameForDisplay() else {
+                if let siteID = post.siteID, let postID = post.postID {
+                    WordPressAppDelegate.crashLogging?.logMessage("Expected blogNameForDisplay() to exist",
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift]: @dvdchr The optional `WordPressAppDelegate.crashLogging` gives me the impression that if, for unknown reasons, that instance is `nil`, that message won't be logged. What do you think of using the non-optional `CrashLogging.main` instance?

Comment (dvdchr) [reply WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift]: Good catch! The `main` instance provides a fallback in case the one from the app delegate is nil. This is addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20567/commits/84b32045bae812841e3136b4526cde2b1c236b90 ! Thanks.

Comment (dvdchr) [reply WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift]: Whoops, looks like I missed an import. Addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/20567/commits/9e320b70cac245870b208f3f84322f2569e42590.

**Comment by dvdchr** [comment]
👋🏼 Heads up: as I'm going to be AFK next week, I'll be enabling auto-merge.

**Comment by twstokes** [comment]
Thank you @dvdchr and @salimbraksa! 🙇

**Review by salimbraksa — APPROVED** [review]
I forced `post.blogNameForDisplay()` to return `nil`, and the app didn't crash. LGTM! 🚀
