### PR TITLE
Fix the condition for saving new drafts

### LINKED ISSUE #24051: Draft pages cannot be previewed
When drafting a new page in the editor, one cannot preview a rendering of the page. This differs from the experience for drafting posts. 

## Steps to Reproduce

1. Create a new page. 
2. Tap the more button (three horizontal dots) in the top-right corner. 
3. Tap Preview. 

## Expected Result
The draft page is saved and a WebView opens previewing the page content. 

## Actual Result
The draft page is not saved, a native view displays "Preview Unavailable." 

https://github.com/user-attachments/assets/2a00b20b-328e-4b28-aa47-66b195848ab9

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #24051.

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/308">25.9</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by dcalhoun — APPROVED** [review]
Previewing new draft pages now works from my testing. Thanks for addressing this! 🚀

File: WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift [hunk 1]
```diff
@@ -20,7 +20,7 @@ extension PostEditor {
     }
 
     private func savePostBeforePreview(completion: @escaping ((String?, Error?) -> Void)) {
-        guard !post.changes.isEmpty else {
+        guard !post.changes.isEmpty || post.original().isNewDraft else {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift:23]: That should fix it, but I'm not sure it's the correct way to do it.

When you create a new draft, it creates an empty post ("original") and a local revision ("post"). As you make changes, they are applied to the revision. As soon as you make a single change, `post.changes.isEmpty` starts returning `false` – so far so good.

The problem is when you create a post from a template, it saves the original content to the "original", so it "thinks" that there are no changes. It inadvertently affects not only the previews but some other flows. For example, when you create a new draft from a template and immediately close it, it doesn't ask you if you want to save it – it discards it automatically (and I would argue it should let you save a draft from a template you picked without editing it):

https://github.com/user-attachments/assets/8385f76f-a040-4243-849d-22e68d26aa68

I suggest making the change [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/a35a2a37f7ff590c9534286a16eb08b049c26f4f/WordPress/Classes/ViewRelated/Pages/Controllers/EditPageViewController.swift#L48) and apply the changes to the (unsaved) revision instead of the original:

```swift
let newPage = blog.createDraftPage().createRevision() as! Page
```

This way the editor will treat the changes the same way as if you typed them.

**Review by kean — CHANGES_REQUESTED** [review]

File: WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift (hunk 1 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift:23]: I can see it both ways though, so I'm going to remove the "Request Changed". Ideally, I'd rather avoid supporting a scenario where an "original" has some predefined content, but from what I understand, it should be fine – publishing, saving should work as expected. I'd check if it's covered by the unit tests. If it's not, it's problematic to continue using it.

Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift:23]: The scenario you described and the changes you suggested make sense to me. I think your changes and this PR are not mutually exclusive, though. They appear to fix two different problems, which all relate to https://github.com/wordpress-mobile/WordPress-iOS/issues/24051.

The condition in the `savePostBeforePreview` function is problematic because we need to save the post if the post does not exist on the site.

What do you think we could merge this PR and fix the issue you mentioned in a separate PR? I'm happy to look into that issue.

**Review by kean — APPROVED** [review]

File: WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift (hunk 1 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift:23]: Sure, I'm approving it – it makes sense. There is also an edge-case where the post content is empty – what will happen in that case? Will it save an empty draft? It should probably disable the preview button.

> They appear to fix two different problems

If you make the `let newPage = blog.createDraftPage().createRevision() as! Page` change, it fixes both issues.
