### PR TITLE
When Start Over action is selected, open documentation for all the WordPress app users

### LINKED ISSUE #20351: Start Over opens WordPress.com support link
### Expected behavior
With the change in focus, the app should redirect WordPress.com users who need help to the help guide but not open a support request on WordPress.com. It should link to https://wordpress.com/support/empty-site/ similar as it does for free sites.

### Actual behavior
The app opens a direct link to email WordPress.com support for paid sites.

### Steps to reproduce the behavior
1. Navigate to a WordPress.com paid site (Personal or Premium plan)
2. Click on Site Settings and under Advanced navigate to Start Over
3. Notice the paid option to contact support.

IMG_5402 (1)

### PR DESCRIPTION
**Pull request by staskus**
Fixes #20351

## Testing instructions

⚠️ Note: https://public-api.wordpress.com/wpcom/v2/mobile/feature-flags?platform=ios&marketing_version=22.0 `wordpress_support_forum_remote_field` should be set to `true` before testing

### Case 1 WordPress app 22.0:
1. Open the WordPress app
2. Navigate to a WordPress.com paid site (Personal or Premium plan)
3. Click on Site Settings and under Advanced navigate to Start Over
4. Notice `https://en.support.wordpress.com/empty-site` opening

### Case 2 Jetpack app 22.0:
1. Open the WordPress app
2. Navigate to a WordPress.com paid site (Personal or Premium plan)
3. Click on Site Settings and under Advanced navigate to Start Over
4. Notice the paid option to contact support.

## Regression Notes

1. Potential unintended areas of impact

I'm following the logic of https://github.com/wordpress-mobile/WordPress-iOS/issues/20240 which removes WP Zendesk support for all WP app users only starting from 22.0, so I used the same flags here. It could be not what's intended.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Images & Videos

https://user-images.githubusercontent.com/4062343/225849554-3b9c50a0-7a2e-4f78-a747-b622159b1b57.mp4

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift [hunk 1]
```diff
@@ -33,3 +33,9 @@ enum SupportConfiguration {
         return isJetpack && migrationState == .completed
     }
 }
+
+@objc class SupportConfigurationObjC: NSObject {
+    @objc static var isStartOverSupportEnabled: Bool {
+        return SupportConfiguration.current() == .zendesk
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift:39]: @guarani 

1. If we want this to be enabled from 21.9 and only available on WordPress app, we should check `AppConfiguration.isJetpack` here and target `release/21.9`
2. If we want this to be enabled from 22.0, together with removing other WP.com paid support features, we should leave it as it is

Comment (guarani) [reply WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift:39]: > If we want this to be enabled from 22.0, together with removing other WP.com paid support features, we should leave it as it is

I think that is what's needed, but I also think that using `AppConfiguration.isJetpack` achieves this. If we use `AppConfiguration.isJetpack` and merge this to `trunk` today, it'll get picked up in the 22.0 release. Wdyt?

**Review by guarani — COMMENTED** [review]
Hey @staskus, thanks for the PR! I left a comment because I'm unsure if I have the same understanding of what's needed as you do. Let me know if my comment doesn't make sense and I'd be happy to discuss it.

File: WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift (hunk 1 above)
Comment (staskus) [reply WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift:39]: Yes, that's correct. We'll lose the feature flag and consistency with the other forum features but the main functionality will remain the same.

Comment (guarani) [reply WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift:39]: Ok, I missed your point about keeping this change under the control of the forum remote feature flag. Makes sense to leave it as-is 👍

**Comment by guarani** [comment]
Approving this now that I understand this implementation keeps this change within the control of the forum remote feature flag. I'm going to go ahead and merge this since it's approaching the end of the week. 
Thanks @staskus!

**Review by guarani — APPROVED** [review]
Approving this now that I understand this implementation keeps this change within the control of the forum remote feature flag. I'm going to go ahead and merge this since it's approaching the end of the week. 
Thanks @staskus!
