### PR TITLE
iOS 14: Fixes CachedAnimatedImageView not loading the image

### LINKED ISSUE #14932: iOS 14: CachedAnimatedImageView does not load the image
When the app is built with Xcode 12 and ran on iOS 14 instances of `CachedAnimatedImageView` do not display the image

This only affects iOS 14, when the same build is ran on iOS 13 and below the images appear fine.

### PR DESCRIPTION
**Pull request by emilylaguna**
Fixes #14932

### To test:
1. Build the app using Xcode 12
2. Launch the app on iOS 14
3. Tap the Reader
4. Tap on following
5. Locate a post that has an image
6. You should see the image
7. Tap on the post to see the detail view
8. Tap on the image to open it full size
9. You should see the image
10. Locate a post with a gif featured image
11. Verify the gif plays

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift [hunk 1]
```diff
@@ -96,7 +96,9 @@ public class CachedAnimatedImageView: UIImageView, GIFAnimatable {
 
     // MARK: - Public methods
 
-    override public func display(_ layer: CALayer) {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift:99]: Nice catch!!

**Review by frosty — APPROVED** [review]
Thanks for fixing this! I can confirm that images are loading as expected.
