### PR TITLE
Show loader while activating theme

### LINKED ISSUE #15329: Activating a theme does not close the preview or disable the "Activate" button
### Expected behavior
I expect activation to look like something is installing and then the preview to close.

### Actual behavior
1. During activation, there is no user feedback, so I do not actually know anything is happening and I am likely to keep tapping the Activate button. (The video is a bit faster, actual time of seemingly no action is about 7 seconds). 
2. It stays open and the Activate button is still enabled, so even though I got the message thanking me for choosing the theme, I still feel like it didn't work and I need to tap the button again. 

### Steps to reproduce the behavior
https://cloudup.com/cPSa1glnLMw

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #15329 

To test: 
1. Go to themes 
2. Got to a specific theme 
3. If its active, notice the bar item tittle is "Active" , if it's not active notice title = "Activate"
4. If it's active see Customizer, if it's not active see theme
5. Tap "Activate" and notice spinner 
6.  Notice spinner is hidden once theme is active
7. Notice title turns to disabled "Active" once the theme is activated 

* Anything else I didn't think of 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
theme_loader

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift [hunk 1]
```diff
@@ -183,6 +183,15 @@ public protocol ThemePresenter: class {
         return !suspendedSearch.trim().isEmpty
     }
 
+    fileprivate var activityIndicator: UIActivityIndicatorView = {
+        let indicatorView = UIActivityIndicatorView(style: .medium)
+        indicatorView.frame = CGRect(x: 0.0, y: 0.0, width: 40.0, height: 20.0)
```
Comment (Gio2018) [inline WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift]: nit: since we already have grouped constants in this class [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/163292dcb88b606e51d5ec325be072fda7461c9f/WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift#L250), maybe we can add these numbers (or even just the `CGRect` itself) to these constants?

File: WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift [hunk 2]
```diff
@@ -780,6 +793,12 @@ public protocol ThemePresenter: class {
                 let successMessage = String(format: successFormat, theme?.name ?? "", theme?.author ?? "")
                 let manageTitle = NSLocalizedString("Manage site", comment: "Return to blog screen action when theme activation succeeds")
                 let okTitle = NSLocalizedString("OK", comment: "Alert dismissal title")
+
+                self?.activityIndicator.stopAnimating()
+                self?.activateButton?.customView = nil
+                self?.activateButton?.isEnabled = false
+                self?.activateButton?.title = ThemeAction.active.title
```
Comment (Gio2018) [inline WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift]: nit: totally not a big deal, but maybe we can group these calls in an helper method for readability? Same with the two calls to start the animation above.

**Review by Gio2018 — APPROVED** [review]
Tested on devices: iPhone 11 Pro Max - iOS 14.4 and iPad Pro 11 2nd gen, iPadOS 14.4 and it worked as described.

One thing that I noticed, not directly related to this PR, is that if I activate a theme from the "meatball menu" (see image below), there is no similar feedback for the users before the theme is actually activated. This is not a huge deal, but I can open/handle a separate issue if it's the case.

Other than that, I left a couple of minor comments that can be safely ignored.

:shipit:!

<p align=center>

</p>

File: WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift (hunk 1 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift]: Done in 3a57070fa24d7e0913ae182564a7da9e800d56fb

File: WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift (hunk 2 above)
Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift]: Done in 3a57070fa24d7e0913ae182564a7da9e800d56fb

**Comment by yaelirub** [comment]
Thank you so much for the review, @Gio2018 🙏 
Would you please open an issue to handle loading from activate in the bottom sheet. I think we need design solution there 
cc: @iamthomasbishop
