### PR TITLE
Fix crash in attributedStringWithHTML

### LINKED ISSUE #7277: Crash: NSAttributedString.attributedStringWithHTML(String, attributes : [HTMLAttributeType : [String : AnyObject]]?) -> NSAttributedString
This crash is occurring for iPad (99%) and iPhone (1%) on iOS 10 with 7.6.0.2 and 7.5.0.2.  The stack trace is below.

```
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1016c3734 _TTSfq4n_s_n_n_n___TFs17_assertionFailureFTVs12StaticStringSS4fileS_4lineSu5flagsVs6UInt32_Os5Never + 164
1  libswiftCore.dylib             0x1015c83c0 swift_unexpectedError_merged + 282
2  libswiftCore.dylib             0x1015c8288 swift_unexpectedError + 26
3  WordPress                      0x1002b1ca4 specialized static NSAttributedString.attributedStringWithHTML(String, attributes : [HTMLAttributeType : [String : AnyObject]]?) -> NSAttributedString (NSAttributedString+StyledHTML.swift:46)
4  WordPress                      0x1004b077c JetpackLoginViewController.setupSendSMSCodeButtonText() -> () (NSAttributedString+StyledHTML.swift)
5  WordPress                      0x1004b02f8 JetpackLoginViewController.setupControls() -> () (JetpackLoginViewController.swift)
6  WordPress                      0x1004af8ac JetpackLoginViewController.viewDidLoad() -> () (JetpackLoginViewController.swift:89)
7  WordPress                      0x1004af8e8 @objc JetpackLoginViewController.viewDidLoad() -> () (JetpackLoginViewController.swift)
8  UIKit                          0x18ded8ec0 -[UIViewController loadViewIfRequired] + 1036
9  UIKit                          0x18ded8a9c -[UIViewController view] + 28
10 WordPress                      0x100091304 -[StatsViewController promptForJetpackCredentials] (StatsViewController.m:164)
11 WordPress                      0x100090fe4 -[StatsViewController initStats] (StatsViewController.m:129)
12 WordPress                      0x100090604 -[StatsViewController viewDidLoad] (StatsViewController.m:74)
13 UIKit                          0x18ded8ec0 -[UIViewController loadViewIfRequired] + 1036
14 UIKit                          0x18df90ff0 -[UINavigationController _layoutViewController:] + 72
15 UIKit                          0x18df90ec8 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 416
16 UIKit                          0x18df901f8 -[UINavigationController _startTransition:fromViewController:toViewController:] + 144
17 UIKit                          0x18df8fc2c -[UINavigationController _startDeferredTransitionIfNeeded:] + 856
18 UIKit                          0x18df8f7e0 -[UINavigationController __viewWillLayoutSubviews] + 64
19 UIKit                          0x18df8f744 -[UILayoutContainerView layoutSubviews] + 188
20 UIKit                          0x18ded607c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1200
21 QuartzCore                     0x18b0c6274 -[CALayer layoutSublayers] + 148
22 QuartzCore                     0x18b0bade8 CA::Layer::layout_if_needed(CA::Transaction*) + 292
23 QuartzCore                     0x18b0baca8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
24 QuartzCore                     0x18b03634c CA::Context::commit_transaction(CA::Transaction*) + 252
25 QuartzCore                     0x18b05d3ac CA::Transaction::commit() + 504
26 QuartzCore                     0x18b05de78 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 120
27 CoreFoundation                 0x187d5c9a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
28 CoreFoundation                 0x187d5a630 __CFRunLoopDoObservers + 372
29 CoreFoundation                 0x187c8adc4 CFRunLoopRunSpecific + 456
30 UIKit                          0x18df43384 -[UIApplication _run] + 652
31 UIKit                          0x18df3e058 UIApplicationMain + 208
32 WordPress                      0x100052d48 main (main.m:11)
33 libdyld.dylib                  0x186c9959c start + 4
```

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #7277

I was unable to reproduce this crash, despite many attempts, however this eliminates the `try!` that was causing the crash. Also removes two unnecessary lines in `Login2FAViewController.swift` that I found while working on this ;)

To test:
1. ensure that attributed text build with this method still appears correctly, such as:
   - the underlined text on the 2FA verification screen
   - text on the plans screens
   - text on the delete site screen

Needs review: @frosty 
_You touched this last, it seems, want to check out my hacking?_

### CODE REVIEW

File: WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift [hunk 1]
```diff
@@ -19,22 +19,23 @@ extension NSAttributedString {
     class func attributedStringWithHTML(_ htmlString: String, attributes: StyledHTMLAttributes?) -> NSAttributedString {
         let styles = styleTagTextForAttributes(attributes)
         let styledString = styles + htmlString
-        let attributedString = try! NSMutableAttributedString(
+        guard let attributedString = try? NSMutableAttributedString(
             data: styledString.data(using: String.Encoding.utf8)!,
```
Comment (frosty) [inline WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift]: Perhaps we should `if let` this data too, to avoid another force unwrap – just to be safe?

File: WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift [hunk 2]
```diff
@@ -19,22 +19,23 @@ extension NSAttributedString {
...
         // body of the text, so we can copy it use its text alignment.
-        let paragraphStyle: NSMutableParagraphStyle
+        let paragraphStyle = NSMutableParagraphStyle()
         if let attributes = attributes,
             let bodyAttributes = attributes[.BodyAttribute],
             let pStyle = bodyAttributes[NSParagraphStyleAttributeName] as? NSParagraphStyle {
-            paragraphStyle = pStyle.mutableCopy() as! NSMutableParagraphStyle
-        } else {
-            paragraphStyle = NSMutableParagraphStyle()
+                paragraphStyle.setParagraphStyle(pStyle)
```
Comment (frosty) [inline WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift]: TIL!

**Comment by nheagy** [comment]
Thanks @frosty!
