### PR TITLE
Ignore an Objective-C exception

### LINKED ISSUE #24247: WordPressDotComAuthenticatorTests crashes when you disable StatsWidgetsStoreTests
Steps:

- Disable `StatsWidgetsStoreTests`
- Run the whole set of unit tests

Result:

- `WordPressDotComAuthenticatorTests.testSignInSuccess` starts crashing

```
<details><summary><tt>testSignInSuccess()</tt> in <tt>WordPressDotComAuthenticatorTests</tt></summary>
<pre>Crash: WordPress (3408) <external symbol></pre>
```

There is no more information. It's unclear what exactly causes it.

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #24247.

See the inline code comment for details.

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/308">25.9</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift [hunk 1]
```diff
@@ -100,8 +100,13 @@ class MySitesCoordinator: NSObject {
...
     @objc func signinDidFinish() {
-        mySiteViewController = makeMySiteViewController()
-        navigationController.viewControllers = [rootContentViewController]
+        // The code below raises an exception during unit tests. Adding a `try?` to ignore the error.
+        // The exception is Error Domain=NSRangeException Code=0 "(null)". I'm not exactly sure what code (probably
+        // deep in UIKit) throws this exception, but I don't see any reason the code below would cause crash in production.
+        try? WPException.objcTry {
+            self.mySiteViewController = self.makeMySiteViewController()
+            self.navigationController.viewControllers = [self.rootContentViewController]
+        }
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift:109]: I suppose we consider safe to blanket ignore any exception here because we are confident they would arise only when running unit tests due to the many stateful assumption in the app at the moment.

Is that safe?

How would you feel about running this only if `NSClassFromString("XCTestCase") != nil`?

**Review by mokagio — APPROVED** [review]
Alright!

Sorry it took me a while to review this, but I wanted to verify it locally (_just in case!_) using the steps from https://github.com/wordpress-mobile/WordPress-iOS/issues/24247

All good!

Approving to unblock, my question regarding the scope to which we should wrap possible exceptions is not a blocker at all.

**Review by kean — APPROVED** [review]

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift (hunk 1 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift:109]: It should be okay because I don't think there is no exception in this code in the real app.

As I shared on Slack, the actual crash site is at [this code](https://github.com/wordpress-mobile/WordPress-iOS/blob/be3f6b0b1e0b3a0c59b4d71cd71b9089044585d1/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsButtonViewModel.swift#L47), which should never happen in the real app too.

I also can't find any related issue on Sentry.
