### PR TITLE
Issue/8054 fix download of images org basic auth

### LINKED ISSUE #8054: Download of Image on .org sites with basic auth is not working
Because images are being download using direct url session the case where a site is protected with .basic auth is not being handled and this result on the following issues.

❌ When opening a post with media the image placeholder in Aztec never updated:

screen shot 2017-10-25 at 12 52 11 pmscreen shot 2017-10-25 at 12 51 58 pm

❌ Post List — Refreshing worked, but "featured" image in post list cell did not display:

screen shot 2017-10-25 at 12 49 50 pm

❌ Post Options — More or less worked, but was unable to set featured image:

screen shot 2017-10-25 at 12 57 45 pm

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8054 

To test:
 - Launch the app and add a self-hosted site with basic auth enabled
 - Go to Media Library, check that images download correctly
 - Tap an image and see if it opens correctly
 - Edit a post add an image to it, save it and reopen again and see if image loads correctly
 - Add a feature image image to the same post see if it saves and loads correctly on post settings
 - Check if in the post list the images are loaded correctly.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 1]
```diff
@@ -1384,20 +1361,20 @@ - (void)uploadFeaturedMedia:(Media *)media
...
+//    self.featuredImage = image;
+//    [self.tableView reloadData];
+//}
+//
+//- (void)tableImageSource:(WPTableImageSource *)tableImageSource
+// imageFailedforIndexPath:(NSIndexPath *)indexPath
+//                   error:(NSError *)error
+//{
+//    [self featuredImageFailedLoading:indexPath withError:error];
+//}
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: @SergioEstevao Were you intending to remove this commented block?

Comment (SergioEstevao) [reply WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: I need to delete it.

**Comment by SergioEstevao** [comment]
@bummytime removed the commented out code. Ready for another look.
