### PR TITLE
Better offline messages: full implementation

### LINKED ISSUE #5759: Improve errors when the app is offline
### Expected behavior

If the app is offline and can't sync/display the correct information on a screen, I expect to see an error explaining that.
### Actual behavior

On some screens, when the device is offline the app displays incorrect information instead of an error:
- Comments: The app says `No comments yet` even if there are comments on the site
- People: The app says `No users yet` or `No followers yet` even if there are users/followers on the site
- Reader: The reader just doesn't update, without explaining why. If there are no previously synced posts for a reader list, it incorrectly says `No recent posts / No posts have been made recently`
- Reader search: If you try to search the reader, it says `No posts found / No posts found matching [search term] in your language`
- Notifications: The notifications tab just doesn't update, without explaining why.
#### Screenshots

photo jul 20 6 09 08 pm

### PR DESCRIPTION
**Pull request by ctarda**
Fixes #5759 

This has been reviewed in pieces already, during hack week, but here is the full feature in one single PR. 

Expected behaviour in Comments, Notifications, Posts List, Pages List, Reader and People:
- If there is no cached data, we use NoResultsView to present a user-facing message informing that the network is down
- If there is cached data, we present an alert
- Content should reload when the network connection is back up

To test:
1. Put the device in flight mode
2. Navigate to the views mentioned
3. Exit flight mode and check that content reloads

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift [hunk 1]
```diff
@@ -1183,6 +1205,10 @@ private extension NotificationsViewController {
 //
 private extension NotificationsViewController {
     func syncNewNotifications() {
+        guard connectionAvailable() else {
+            handleConnectionError()
+            return
+        }
```
Comment (elibud) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Can we add an empty line here too?
