### PR TITLE
Fix issue with notification header details comment preview not showing

### LINKED ISSUE #13856: Notifications: Gutenberg comments don't show up in notifications about likes or replies to comments
### Expected behavior

When some likes or replies to a comment I made, I expect to see the beginning of my comment at the top of the notification about it.

### Actual behavior

When my comment was made using Gutenberg, the area in the notification where I expect to see the beginning of my comment is blank.

This issue is specific to WPiOS — it works as expected on the web and in WPAndroid.

### Steps to reproduce the behavior

1. On a site, enable Gutenberg for the site comments.
2. Leave a comment using Gutenberg.
3. From another account, like or reply to that comment.
4. In the app, check your notifications on the account you used to leave the Gutenberg comment.
5. Select the notification about the like/reply to your comment to view the notification detail.

Result: The notification is received, but the text of your comment isn't visible in the notification detail.

WPiOS (bug)|WPAndroid (expected)
-|-
|

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #13856 
Rendering notification details label (includes stripping new-line) instead of plain text. 

To test:
1. Go to notifications 
2. Tap on notification where someone replied or liked your comment 
3. see the comment details line 
(more information and screenshots in the issue)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/FormattableContent/Styles/SnippetsContentStyles.swift [hunk 1]
```diff
@@ -11,5 +11,5 @@ class SnippetsContentStyles: FormattableContentStyles {
 
     var linksColor: UIColor?
 
-    var key: String = "SnipetsContentStyles"
+    var key: String = "SnippetsContentStyles"
```
Comment (emilylaguna) [inline WordPress/Classes/ViewRelated/Notifications/FormattableContent/Styles/SnippetsContentStyles.swift:14]: 👏

File: WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift [hunk 2]
```diff
@@ -307,6 +314,9 @@ extension WPStyleGuide {
         fileprivate static let snippetParagraph         = NSMutableParagraphStyle(
             minLineHeight: snippetLineSize, lineBreakMode: .byWordWrapping, alignment: .natural
         )
+        fileprivate static let snippetHeaderParagraph         = NSMutableParagraphStyle(
```
Comment (emilylaguna) [inline WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift:317]: Sticking with the coding style of the file, the `=` should be balanced with the others
```suggestion
        fileprivate static let snippetHeaderParagraph   = NSMutableParagraphStyle(
```
