### PR TITLE
Always update Widgets after logout/login

### LINKED ISSUE #15833: Stats widgets not updating after signing up for new account
### Expected behavior

The new Stats widgets should detect when you change accounts and update themselves accordingly (or at least allow you to update them without having to re-add them)

### Actual behavior

When switching sites in the app, I had to re-add the Stats widgets to get them to work.

### Steps to reproduce the behavior

1. I was using the app and had added some Stats widgets and everything was working fine
2. I signed out and created a new WordPress.com account in the app (and a brand-new site)
3. I used the app for a little while (testing some new features e.g. updates to Quick Start)
4. I back-grounded the app and noticed the widgets were asking me to sign in (this was unexpected)
5. I tried to edit the widgets and update their site but it showed an empty list of sites
6. I ultimately had to re-add the widgets to get them to work

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #15833

To test:

- install one or more widgets
- logout/login with different accounts and make sure that the widgets are updated

**Note**
When logging out and in several times with more than one widget installed, in some cases, I noticed a delay in updating some widgets of about 1 minute (sometimes less, sometimes not at all). I am not sure yet why this happened but would be good to know if you see the same (see video below)

<p align=center>

</p>

cc @jkmassel 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Stores/StatsInsightsStore.swift [hunk 1]
```diff
@@ -1078,15 +1078,36 @@ private extension StatsInsightsStore {
...
+
             WidgetCenter.shared.reloadTimelines(ofKind: WPHomeWidgetTodayKind)
-            HomeWidgetAllTimeData.delete()
             WidgetCenter.shared.reloadTimelines(ofKind: WPHomeWidgetAllTimeKind)
+        }
+    }
+}
 
+extension StatsViewController {
+    @objc func initializeStatsWidgetsIfNeeded() {
```
Comment (frosty) [inline WordPress/Classes/Stores/StatsInsightsStore.swift]: I wonder if this method would be more appropriate somewhere other than the view controller? I know it's slightly complex due to the objc requirement though, otherwise I'd say perhaps on an extension on the HomeWidgetData types in the main app. Not a dealbreaker, just that this code isn't VC specific.

File: WordPress/Classes/Stores/StatsInsightsStore.swift [hunk 2]
```diff
@@ -1055,14 +1055,14 @@ private extension InsightStoreState {
                                                                   siteName: title,
                                                                   url: url,
                                                                   timeZone: timeZone,
-                                                                  date: Date(),
+                                                                  date: Date(timeIntervalSinceReferenceDate: 0),
```
Comment (frosty) [inline WordPress/Classes/Stores/StatsInsightsStore.swift]: How come this is using the reference date now?

**Review by frosty — COMMENTED** [review]
Just a few small comments / questions!

I tested by logging in and out of a couple of accounts and everything seemed to work as expected.

**Comment by guarani** [comment]
### Widgets not updating quickly

> When logging out and in several times with more than one widget installed, in some cases, I noticed a delay in updating some widgets of about 1 minute (sometimes less, sometimes not at all). I am not sure yet why this happened but would be good to know if you see the same (see video below)

I saw this too, after logging out of an account the widget would still show the old site and when I edited it it would be showing the old site there, too. 

### Switching between sites shows the "Login to WordPress..." message momentarily

I switched from one site to another from within the Today widget and noticed that the "Login to WordPress..." message flashed for a second or two.

### Users without a site are incorrectly asked to login

New users who don't have a site yet (chose "Not now" option after sign up) are shown the "Log in to WordPress..." message in the widget.
Then if I do add a site, the widget doesn't seem to update (I waited > 1 min). Only tapping on the widget made it show the site.

### All Time widget

I noticed a bug with the All Time widget, but since it looks like only the Today widget is in the App Store at the moment, this might be still in development. When the app's not logged in, the All Time widget shows the message: "Log in to WordPress to see **today's** stats" (emphasis mine). The "today" could be changed to "all time" or similar.

<details>
  <summary>See screenshot</summary>
   
</details>

**Review by guarani — COMMENTED** [review]
### Widgets not updating quickly

> When logging out and in several times with more than one widget installed, in some cases, I noticed a delay in updating some widgets of about 1 minute (sometimes less, sometimes not at all). I am not sure yet why this happened but would be good to know if you see the same (see video below)

I saw this too, after logging out of an account the widget would still show the old site and when I edited it it would be showing the old site there, too. 

### Switching between sites shows the "Login to WordPress..." message momentarily

I switched from one site to another from within the Today widget and noticed that the "Login to WordPress..." message flashed for a second or two.

### Users without a site are incorrectly asked to login

New users who don't have a site yet (chose "Not now" option after sign up) are shown the "Log in to WordPress..." message in the widget.
Then if I do add a site, the widget doesn't seem to update (I waited > 1 min). Only tapping on the widget made it show the site.

### All Time widget

I noticed a bug with the All Time widget, but since it looks like only the Today widget is in the App Store at the moment, this might be still in development. When the app's not logged in, the All Time widget shows the message: "Log in to WordPress to see **today's** stats" (emphasis mine). The "today" could be changed to "all time" or similar.

<details>
  <summary>See screenshot</summary>
   
</details>

**Comment by guarani** [comment]
@Gio2018 I retested https://github.com/wordpress-mobile/WordPress-iOS/issues/15833 and the issue seems to persist, in that case I'm signing up for a new account – not logging into another account – if that makes a difference.

File: WordPress/WordPressStatsWidgets/Supporting Files/en.lproj/Localizable.strings [hunk 3]
```diff
@@ -34,3 +34,8 @@
 /* Description of all time widget in the preview */
 "widget.alltime.preview.description" = "Stay up to date with all time activity on your WordPress site.";
 
+/*Title of the unconfigured view in all time widget */
+"widget.alltime.unconfigured.view.title" = "Log in to WordPress to see all time stats.";
+
+/* Title of the unconfigured view in this week widget */
+"widget.thisweek.unconfigured.view.title" = "Log in to WordPress to see this week stats.";
```
Comment (frosty) [inline WordPress/WordPressStatsWidgets/Supporting Files/en.lproj/Localizable.strings]: I would probably change this one to "this week's stats". The all time one is fine, though.

File: WordPress/WordPressStatsWidgets/Views/Localization/LocalizableStrings.swift [hunk 4]
```diff
@@ -36,10 +36,18 @@ enum LocalizableStrings {
...
+    static let unconfiguredViewTodayTitle = LocalizedStringKey("widget.today.unconfigured.view.title",
                                                           defaultValue: "Log in to WordPress to see today's stats.",
                                                           comment: "Title of the unconfigured view in today widget")
 
+    static let unconfiguredViewAllTimeTitle = LocalizedStringKey("widget.alltime.unconfigured.view.title",
+                                                          defaultValue: "Log in to WordPress to see all time stats.",
+                                                          comment: "Title of the unconfigured view in all time widget")
+
+    static let unconfiguredViewThisWeekTitle = LocalizedStringKey("widget.thisweek.unconfigured.view.title",
+                                                          defaultValue: "Log in to WordPress to see this week stats.",
```
Comment (frosty) [inline WordPress/WordPressStatsWidgets/Views/Localization/LocalizableStrings.swift]: I would probably change this one to "this week's stats". The all time one is fine, though.

**Review by frosty — APPROVED** [review]
I've retested these changes and it seems to be working really well for me now when switching sites. The only issue I see persisting is the one @guarani raised around being shown the 'log in' message if a user has no sites – but we can address that separately at another time.

**Comment by frosty** [comment]
Oh, I forgot one request! Could we add a brief doc comment to each main method in `StatsWidgetStore` to clarify what they're used for?

**Comment by Gio2018** [comment]
> I've retested these changes and it seems to be working really well for me now when switching sites. The only issue I see persisting is the one @guarani raised around being shown the 'log in' message if a user has no sites – but we can address that separately at another time.

Sounds good to me! @Guarani would you have some time to re-test it? Thank you!!

**Comment by Gio2018** [comment]
> Oh, I forgot one request! Could we add a brief doc comment to each main method in `StatsWidgetStore` to clarify what they're used for?

Done!

**Review by guarani — APPROVED** [review]
Re-tested and the original issue is fixed, working great! Thanks @Gio2018!

**Comment by guarani** [comment]
I created an issue for the "Users without a site are incorrectly asked to login" bug here: https://github.com/wordpress-mobile/WordPress-iOS/issues/15857

**Comment by Gio2018** [comment]
Thanks for reviewing @frosty and @guarani ! @jkmassel, should we wait until we merge `16.1.1` before merging this one, since these changes affect the same code?

**Comment by frosty** [comment]
I think that would make sense, as I think these changes should take preference over those?
