### PR TITLE
Append "+testing" to feedback form email for Automatticians

### LINKED ISSUE #23794: Append "+testing" to feedback form email for Automatticians
From Zendesk:

> Attempts to submit requests with a staff member role (admin, agent, etc.) identity will fail by design. Apologies for any confusion around this behavior.

The end result is that HEs are unable to test the feedback form. According to Zendesk, a potential workaround for this is to programmatically append "+testing" when the feedback form is submitted from an @automattic.com or @a8c.com email address.

**Update:** This change should be made for all Zendesk ticket creation, not just the support form.

[Related Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/21449)

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #23794

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/303">25.6</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/Utility/ZendeskUtils.swift [hunk 1]
```diff
@@ -1201,3 +1208,26 @@ extension ZendeskUtils {
...
+    /// - SeeAlso: https://github.com/wordpress-mobile/WordPress-iOS/issues/23794
+    static func a8cTestEmail(_ email: String) -> String {
+        guard let suffix = ZendeskUtils.automatticEmails.first(where: { email.lowercased().hasSuffix($0) }) else {
+            return email
+        }
+
+        let atSymbolIndex = email.index(email.endIndex, offsetBy: -suffix.count)
+
+        // Do nothing if the email is already an "alias email".
+        if email[email.startIndex..<atSymbolIndex].contains("+") {
```
Comment (nbradbury) [inline WordPress/Classes/Utility/ZendeskUtils.swift:1225]: 👍

**Review by kean — APPROVED** [review]
It looks OK as a workaround but the target state is update support to require you to be authorized, so it's likely a waste.
