### PR TITLE
Fix duplicate event tracking and incorrect foreground event logging for push notifications

### LINKED ISSUE #22935: Duplicated event tracking for 'push_notification_alert_tapped' when the push notification alert is tapped
### Expected behavior
- Track `push_notification_received`  when the push notification is received, whether app is in foreground or background.
- Track `push_notification_alert_tapped` only when the push alert is tapped.

### Actual behavior
- The event `push_notification_received`  is tracked when the push notification is received and the app is in background.
- Track `push_notification_alert_tapped ` when:
    - App receives a push notification in foreground.
    - User taps the push notification alert. And in this case, the event is actually tracked twice. 

### Steps to reproduce the behavior

1. Run Jetpack and login into your account.
2. Send a push notification to the device while the app is running in the background.
3. Tap the push notification alert once it appears.
4. Verify if the `push_notification_alert_tapped` event is tracked twice.

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #22935

## Description
This PR fixes an issue where the `push_notification_alert_tapped` event was being tracked multiple times. It ensures that `push_notification_received` is consistently logged upon the arrival of any notification, and `push_notification_alert_tapped` is recorded exclusively when the user taps the notification alert. These changes also shift the responsibility of event tracking to the caller level, thereby improving the precision of our analytics.

## Test Instructions
1. Run the Jetpack app and log in.
2. Send a push notification to your device. _( e.g. You can setup 2 accounts, and use the 1st account to like a post of the 2nd account. The 2nd account should receive a push notification )_
3. **Verify** that `push_notification_received` is tracked, regardless of the app's state ( foreground or background ).
4. Tap the push notification alert.
5. **Verify** that `push_notification_alert_tapped` is tracked, and is not duplicated.

## Regression Notes
1. Potential unintended areas of impact
This PR impacts only the analytics tracking when a push notification is received or tapped.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/Utility/PushNotificationsManager.swift [hunk 1]
```diff
@@ -186,9 +186,6 @@ final public class PushNotificationsManager: NSObject {
             return
         }
 
-        // Analytics
-        trackNotification(with: userInfo)
-
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/PushNotificationsManager.swift:191]: Removing this line from `PushNotificationsManager.handleNotification` resolved the issue of duplicated `push_notification_alert_tapped` analytics events. The idea is that `handleNotification` should only be concerned with handling the notification, irrespective of the context that triggered it (whether the notification was received in the background, or the notification alert was tapped). Analytics tracking has now been moved to the caller level.

File: WordPress/Classes/Utility/PushNotificationsManager.swift [hunk 2]
```diff
@@ -207,7 +204,18 @@ final public class PushNotificationsManager: NSObject {
...
     /// - Parameter userInfo: The Notification's Payload
     ///
-    func trackNotification(with userInfo: NSDictionary) {
+    func trackNotification(with userInfo: NSDictionary, response: UNNotificationResponse? = nil) {
+        let event: WPAnalyticsStat? = {
+            if let response {
+                return response.actionIdentifier == UNNotificationDefaultActionIdentifier ? .pushNotificationAlertPressed : nil
+            }
+            return .pushNotificationReceived
+        }()
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/PushNotificationsManager.swift:213]: This logic fixes the bug where the event `push_notification_alert_tapped` is tracked when the app is in foreground. So the event was tracked even though the user doesn't tap the alert, which is misleading.

This event is now only tracked when the user taps the notification alert.

**Review by antonis — APPROVED** [review]
Thank you for fixing this @salimbraksa 🙇 
I confirm that the behavior introduced with this PR aligns with how the Android `push_notification_received` and `push_notification_alert_tapped` events work.
