### PR TITLE
Issues/5350 fix backdated draft

### LINKED ISSUE #5350: Backdated drafts are published instead with the current date/time
### Expected behavior
If you change the publish date on a post and publish it that it will use that as the published date.

### Actual behavior
Instead it will use the original creation date of the draft post as the published date.

### Steps to reproduce the behavior
- Create a post
- Save it as a draft
- Change the date on the post and update
- Change the status to publish and publish post
- View post on site and see the original creation date as the published date.

##### Tested on iPhone 6, iOS 9.3.1, WPiOS 6.1

Video of this happening
https://cloudup.com/cm6ym99KQN2

### PR DESCRIPTION
**Pull request by aerych**
Fixes #5350 
This PR adds a dateModified field to our `BasePost` model and uses it in tandem with date_created_gmt to determine if a draft post should be published immediately.   A draft post will "publish immediately" when the date_created_gmt and the modified date match. This mimics the behavior in core as far as I can tell by inspecting API results but I haven't found matching code in the php. 

To test: 
Run the app after switching to the branch. 
Confirm draft posts are still correctly sorted if they are set to publish immediately. (Publish immediately should be topmost in the list)

Create a new draft post on the web and sync.
Check the post card and confirm status says "Publish Immediately"
Click the Publish button on the card. 
Confirm the post Published with the current date/time. 

Create a new draft post on the web. Backdate the post and then sync the app.
Check the post card and confirm the correct publish date is shown. 
Click the publish button on the card
Confirm the post is published with date/time that was set.

Create a new draft post on the web. Backdate the post and then sync the app.
Open post settings and choose "publish immediately" via the date picker. 
Click the update/save the post via the editor
Confirm the post is published with current date/time.

Create a new scheduled post on the web and then sync the app.
Open post settings and choose "publish immediately" via the date picker. 
Click the update/save the post via the editor
Confirm the post is published with current date/time.

Create a new scheduled post on the web and then sync the app. 
Find the card for the scheduled post and click the publish button. 
Confirm the post is published with the current date/time.

Create a new draft post and save.
In the post list, confirm the draft shows "publish immediately" in its card and not a time value.
Trash the post. 
Change the status filter to view trashed posts and confirm the trashed post shows a time value (not publish immediately) in its card.
Restore the trashed draft. 
Switch back to the draft filter and find the post.
Confirm that it is still showing a time value (not publish immediately).

Needs review: @diegoreymendez

### CODE REVIEW

File: WordPress/Classes/Models/BasePost.m [hunk 1]
```diff
@@ -181,7 +182,7 @@ - (void)setDateCreated:(NSDate *)localDate
      If the date is now or in the past, and the status is scheduled, set the status
      to published.
      */
-    if (self.date_created_gmt == nil) {
+    if (self.date_created_gmt == nil || [self.date_created_gmt isEqualToDate:self.dateModified]) {
```
Comment (diegoreymendez) [inline WordPress/Classes/Models/BasePost.m]: The conditions inside this block are almost the same as the conditions checked [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/5483/files#diff-d03640d7facc9ecd8eb48be69bf8a577R293).

If feels like these two conditions should be a new method in `BasePost` instead, in order to ease code maintenance.

**Comment by diegoreymendez** [comment]
> This PR adds a dateModified field to our BasePost model and uses it in tandem with date_created_gmt to determine if a draft post should be published immediately. A draft post will "publish immediately" when the date_created_gmt and the modified date match.

Can we add this information somewhere appropriate in the code?  Maybe as the documentation for the new method I requested [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/5483/files#diff-0a6ee1bc75d5e2a27421c3f3800a77f2R185).

File: WordPress/Classes/Models/BasePost.m (hunk 1 above)
Comment (diegoreymendez) [inline WordPress/Classes/Models/BasePost.m]: PS: by the description of the PR it sounds to me like we should be checking if the post is a draft here too?

**Comment by diegoreymendez** [comment]
@aerych - Sorry I just realized this wasn't ready for review.  Want me to remove the comments?

**Comment by aerych** [comment]
> Sorry I just realized this wasn't ready for review. Want me to remove the comments?

No worries :)  The comments are fine.

File: WordPress/Classes/Models/BasePost.m (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/Models/BasePost.m]: > If feels like these two conditions should be a new method in BasePost instead, in order to ease code maintenance.

I thought about it, but decided it wouldn't be proper for another reason.  `BasePost` should *only* contain properties and methods in common with `AbstractPost` and `ReaderPost`.  Right now its not doing a good job of that and contains things specific to `AbstractPost`.  
I'd rather see us migrate anything specific to `AbstractPost` into that class as a clean up task.

Comment (aerych) [inline WordPress/Classes/Models/BasePost.m]: > PS: by the description of the PR it sounds to me like we should be checking if the post is a draft here too?

I think the extra check for a draft status isn't necessary. From what I can tell only drafts, or perhaps  can have identical values for date created and date modified. They should be different for posts with a scheduled, published, pending, private, trashed, or future status.   Tho now that I think about it I don't believe I tested the trashed/restored use case. I'll add that to the list.

**Comment by aerych** [comment]
> Can we add this information somewhere appropriate in the code

For sure!

**Comment by aerych** [comment]
Hola @diegoreymendez :) 
I did a bit more testing and I think this is probably ready for review now.  I've added a `DO NOT MERGE` label as a separate PR also bumps the core data model version.  I think it will be simpler to merge this PR after since the change here is minor.

File: WordPress/Classes/Models/BasePost.m (hunk 1 above)
Comment (diegoreymendez) [inline WordPress/Classes/Models/BasePost.m]: Still... can we unify how we perform this check?

My concern is someone changing this condition, but not the other one because it's written twice inline.  The location of the method could be anywhere we deem appropriate for now.

Comment (diegoreymendez) [inline WordPress/Classes/Models/BasePost.m]: Also kind of related to this discussion, and maybe superseding it...

> BasePost should only contain properties and methods in common with AbstractPost and ReaderPost.

Maybe we should consider adding `dateModified` to `AbstractPost` in this PR, considering it's not used in `ReaderPost`?

**Comment by diegoreymendez** [comment]
@aerych - On test 3 the date picker doesn't seem to update the date properly... even though the final result of the test IS successful.

https://cloudup.com/cGQHBCE5E4l

File: WordPress/Classes/Models/BasePost.m (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/Models/BasePost.m]: > Maybe we should consider adding dateModified to AbstractPost in this PR, considering it's not used in ReaderPost? (to avoid changing the model twice)

I think dateModified belongs in AbstractPost, for sure.  We need to move it as part of #5523. But as long as we're having to reference the property from BasePost it needs to belong to BasePost.  I can't bring myself have parent class calling code in one of its descendants. :/

**Comment by aerych** [comment]
Thanks @diegoreymendez!  The issue with publish immediate should be fixed.  I've also moved the common part of that conditional into its own separate method that can be reused. 
Ready for another round!

File: WordPress/Classes/Models/AbstractPost.m [hunk 2]
```diff
@@ -281,6 +282,27 @@ - (Media *)featuredImage
 
 #pragma mark - Convenience methods
 
+- (BOOL)isDraft
+{
+    if ([self.status isEqualToString:PostStatusDraft]) {
```
Comment (diegoreymendez) [inline WordPress/Classes/Models/AbstractPost.m]: Really minor, but we could join both if conditions with an "or" operator (since both cases return `YES`).

Comment (aerych) [inline WordPress/Classes/Models/AbstractPost.m]: We could. I chose to be more verbose for clarity. I think its easier to read this way.

**Comment by diegoreymendez** [comment]
All tests work perfectly.  Also checked the fixed date picker.  Nice job! :shipit:

**Comment by aerych** [comment]
Thanks @diegoreymendez !
