### PR TITLE
[Fix] Author filter issues

### LINKED ISSUE #12330: Author filter issues
### Expected behavior

The author tooltip filter should have a tiny arrow on top, and be responsive.
IMG_8600

### Actual behavior

The arrow is not present on iOS 13 and the tooltip is super unresponsive.
IMG_1776

### Steps to reproduce the behavior

On an iOS 13, multi-author blog, tap on the avatar on the top left column. Notice the arrow missing and the unresponsiveness.

### PR DESCRIPTION
**Pull request by danielebogo**
Fixes #12330 

This PR wants to fix the popover tableview inset while the app is running on iOS 13.
Investigating the problem I found here ([1](https://forums.developer.apple.com/thread/121729) | [2](https://twitter.com/steipete/status/1157666057424912384)) that 
popovers in iOS 13 use safe area. This implies I had to fix the top inset and avoid the bottom safe area over the last row.

## To test:
- Run the App on iOS 13
- Open the Post list and tap on the Author filter
- Make the same test with iOS 12

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/AuthorFilterViewController.swift [hunk 1]
```diff
@@ -48,6 +48,11 @@ class AuthorFilterViewController: UITableViewController {
         tableView.separatorColor = .neutral(.shade10)
         tableView.isScrollEnabled = false
         tableView.showsVerticalScrollIndicator = false
+        if #available(iOS 13, *) {
+            tableView.contentInset = .zero
+        } else {
+            tableView.contentInset = UIEdgeInsets(top: -13.0, left: 0, bottom: 0, right: 0)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/AuthorFilterViewController.swift]: Let's use Metrics.topInset here :)

**Comment by danielebogo** [comment]
Thanks @frosty for the review! I fixed it! Ready for another quick look!

**Comment by danielebogo** [comment]
Thanks @frosty !
