### PR TITLE
Fix an issue with a missing "Mark as Unread" button in the More menu

### LINKED ISSUE #23916: Reader: Mark as Unseen
### Expected behavior

n/a

### Actual behavior

n/a

### Steps to reproduce the behavior

The "More" menu for posts no longer have the "Mark as Unseen" button.

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/23916.

Changes:

- Revert the change that removed the "Mark as Read/Unread" button from the post "More" menu
- Add an understated "Read" indicator in the list (new feature)

This change applies to P2s. I don't think regular blogs support this.

## To test:

- Verify that the post you read have a checkmark in the lsit
- Verify that after you open an unread post and return to the list, it shows the checkmark
- Verify that you can toggle the "read" status using the "more" menu and that it updates state on the web

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift [hunk 1]
```diff
@@ -360,6 +370,17 @@ private final class ReaderPostCellView: UIView {
         }
     }
 
+    private func configureSeenCheckmarkIfNeeded() {
+        guard !isSeenCheckmarkConfigured else { return }
+        isSeenCheckmarkConfigured = true
```
Comment (crazytonyli) [inline WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift:375]: Out of curiosity, why is a special flag used here? If the idea is to prevent repeated changes to `image`, maybe a lazy var is more appropriate?

Comment (kean) [reply WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift:375]: It's a bit cumbersome, but the view is created eagerly during the setup:

```
let headerView = UIStackView(alignment: .center, [buttonAuthor, dot, timeLabel, seenCheckmark])
```

Ideally, I should create it lazily and add it lazily to the stack view, but I felt it was simpler this way.

Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift:375]: I guess you could make a `lazy var seenCheckmar: UIImage` so that this configuration function can be called repeatedly. Maybe it's personal preference, but I'm not a big fan of boolean flag type of states.
