### PR TITLE
Fixes bug with changes detection for Post Tags

### LINKED ISSUE #6522: Updating a Post Tags is not always detected as a change
### Expected behavior
Changing a Post Tags should be detected as a change, enabling the Update button on the Post edition screen

### Actual behavior
When the Tags are changed to a different value that has the same number of characters as the previous one the change is not detected.

### Steps to reproduce the behavior
Create a new Post, set Tags to 'aaa', save it.
Edit the Post, change Tags to 'ooo'. 
The Update button won't be enabled.

##### Tested on [device], iOS [version], WPiOS [version]
IPhone 7, iOS 10.2.1, WPiOS 6.8

### PR DESCRIPTION
**Pull request by elibud**
Fixes #6522

To test:
- Edit a Post
- Enter a simple Tag (remember how many characters it has)
- Save the Post
- Edit the Post, changing the Tag to something that has the same number of characters as before
- The Update button on the Post edition screen should be enabled

Needs review: @kurzee @diegoreymendez 
CC: @sendhil

### CODE REVIEW

File: WordPress/Classes/Models/Post.swift [hunk 1]
```diff
@@ -195,7 +195,7 @@ class Post: AbstractPost {
 
         if let originalPost = original as? Post {
 
-            if tags?.characters.count != originalPost.tags?.characters.count && tags != originalPost.tags {
+            if tags ?? "" != originalPost.tags ?? "" {
```
Comment (diegoreymendez) [inline WordPress/Classes/Models/Post.swift]: While the logic used here is fine, readability could be improved.

Here's one example using the exact same code, but making the intent of developer clear and explicit (for any future readers):

```swift
let tagsHaveLocalChanges = tags ?? "" != originalPost.tags ?? ""

if tagsHaveLocalChanges {
```

A step further could be to abstract the details:

```swift
if tagsHaveLocalChanges() {
```

The solutions above are a step closer to something like this (which in my opinion would do this method a big favor):

```swift
override func hasLocalChanges() -> Bool {
    if super.hasLocalChanges() {
        return true
    }
     
    assert(original == nil || original is Post)

    if let originalPost = original as? Post,
        tagsHaveLocalChanges() || coordsHaveLocalChanges() {
           return true
    }

    return false
}
```

File: WordPress/WordPressTest/PostTests.swift [hunk 2]
```diff
@@ -310,9 +310,18 @@ class PostTests: XCTestCase {
 
     func testThatHasLocalChangesWorks() {
         let original = newTestPost()
-        let revision = original.createRevision() as! Post
+        var revision = original.createRevision() as! Post
 
-        XCTAssertFalse(original.hasLocalChanges())
```
Comment (diegoreymendez) [inline WordPress/WordPressTest/PostTests.swift]: Since there's nothing stopping developers from calling `hasLocalChanges()` on "original" posts, the test removed in this line still covers a valid execution path.

As long as we allow that execution path, I'd keep this test.  It can be separated if we wanted to keep things atomic, though - but I'd avoid deleting it.

File: WordPress/Classes/Models/Post.swift (hunk 1 above)
Comment (elibud) [inline WordPress/Classes/Models/Post.swift]: I see your point, the only problem is that with https://github.com/wordpress-mobile/WordPress-iOS/pull/6521 I've already added two more fields to be compared, and if you look at AbstractPost there's like 10 more there. I would like to avoid having 10+ functions to compare 10+ fields and a big || for all of them. Furthermore the functions would only be used here. I can't come up with anything smarter/more elegant though.

File: WordPress/WordPressTest/PostTests.swift (hunk 2 above)
Comment (elibud) [inline WordPress/WordPressTest/PostTests.swift]: 👍 will add it back thanks

File: WordPress/Classes/Models/Post.swift (hunk 1 above)
Comment (diegoreymendez) [inline WordPress/Classes/Models/Post.swift]: > I would like to avoid having 10+ functions to compare 10+ fields and a big || for all of them

Why so?  This code...

```swift
override func hasLocalChanges() -> Bool {
    if super.hasLocalChanges() {
        return true
    }
 
    assert(original == nil || original is Post)
        
    if let originalPost = original as? Post,
        tagsHaveLocalChanges()
        || coordsHaveLocalChanges() 
        || publicizeMessageHasLocalChanges() {

        return true
    }

    return false
}
```

...has the advantage of being self-documenting when compared to the current direction, which is:

```swift
override func hasLocalChanges() -> Bool {
    if super.hasLocalChanges() {
        return true
    }

    assert(original == nil || original is Post)

    if let originalPost = original as? Post {

        if tags ?? "" != originalPost.tags ?? "" {
            return true
        }

        if let coord1 = geolocation?.coordinate,
            let coord2 = originalPost.geolocation?.coordinate, coord1.latitude != coord2.latitude || coord1.longitude != coord2.longitude {

            return true
        }

        if publicizeMessage ?? "" != originalPost.publicizeMessage ?? "" {
            return true
        }

        if (!NSDictionary(dictionary: disabledPublicizeConnections ?? [:])
            .isEqual(to: originalPost.disabledPublicizeConnections ?? [:])) {
            return true
        }
    }

    return false
}
```

> Furthermore the functions would only be used here.

That's not the only reason to separate code in methods, though.  Abstraction from details, single responsibility and separation of concerns are also valid reasons to separate functionality (one such example is when the application starts up... most of the code there is executed only once, but it's still separated in steps).

That said, this PR doesn't need to be more than a bug fix for the time being and your changes are perfectly fine in regards to that.

I'm approving the PR.

Comment (elibud) [inline WordPress/Classes/Models/Post.swift]: You've almost convinced me ;) On top of what you said separating it in methods will also help to improve testing. One consideration about splitting it in methods is that all of them would have to have the following guard right?:

`if let originalPost = original as? Post {`

Swift definitely has a way of making easy things complicated.

Comment (diegoreymendez) [inline WordPress/Classes/Models/Post.swift]: To be completely fair @elibud, I think it'd be better for us to continue the discussion outside of this PR... I have a few thoughts on changes we could make, but they definitely fall outside of the scope of your fix.

Comment (elibud) [inline WordPress/Classes/Models/Post.swift]: most def thx

**Comment by kurzee** [comment]
I agree with @diegoreymendez's comments here, and with this being a bug fix I think it's fine to merge now. I'm going to go ahead and merge it in, nice find @elibud! Thanks @diegoreymendez!
