### PR TITLE
Removes setFrame from AppDelegate and replaces old MainWindow.xib

### LINKED ISSUE #1162: Do not set Window frame size in App Delegate
The window frame size should not need adjustment in the App Delegate.  We are most likely doing something wrong with rotation support.  Remove this code and fix the actual issue - possibly use something like Spark Inspector to determine the problem.

```
    CGRect bounds = [[UIScreen mainScreen] bounds];
    [self.window setFrame:bounds];
    [self.window setBounds:bounds]; // for good measure.
```

### PR DESCRIPTION
**Pull request by dcondrau**
Fixes #1162

### CODE REVIEW

File: WordPress/Classes/System/WordPressAppDelegate.m [hunk 1]
```diff
@@ -164,11 +164,8 @@ - (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:
         [self setMustShowWhatsNewPopup:YES];
     }
     
-    CGRect bounds = [[UIScreen mainScreen] bounds];
-    [self.window setFrame:bounds];
-    [self.window setBounds:bounds]; // for good measure.
     self.window.rootViewController = [WPTabBarController sharedInstance];
-
+    [self.window makeKeyAndVisible];
```
Comment (koke) [inline WordPress/Classes/System/WordPressAppDelegate.m]: We're already calling this later in `application:didFinishLaunchingWithOptions:`

**Comment by koke** [comment]
Other than the extra `makeKeyAndVisible`, this seems to work fine
