### PR TITLE
Reader: Wait to autosync while stream is hidden.

### LINKED ISSUE #6297: Crash when restoring deleted reader post
While debugging #6292 I found a secondary crash. To reproduce:

- Tweak `ReaderStreamViewController.refreshInterval` to something small (I used 3 seconds) or be prepared to wait 5 minutes between tests ;)
- Launch the app, not from Xcode (UI restoration is a bit weird). If you've changed the code, hit the run button on Xcode, then quit the app, then launch from the icon (not debugging).
- Open reader, Posts I Like, open a post
- Put the app in the background
- From a browser, unlike the post you were seeing
- Re-run from Xcode
- The app should restore the post detail, sync posts and notice it's removed from the list. I've seen an animation in the like button removing the like status, but then it crashes.

```
(lldb) bt
* thread #1: tid = 0x22c7052, 0x00000001179cf708 libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> () + 40, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001179cf708 libswiftCore.dylib`function signature specialization <Arg[0] = Exploded, Arg[1] = Exploded, Arg[2] = Dead, Arg[3] = Dead> of Swift._fatalErrorMessage (Swift.StaticString, Swift.StaticString, Swift.StaticString, Swift.UInt) -> () + 40
  * frame #1: 0x000000010e5b4122 WordPress`ReaderPostCardCell.(self=0x00007ff1e5893800)() -> () + 242 at ReaderPostCardCell.swift:434
    frame #2: 0x000000010e5ae8b4 WordPress`ReaderPostCardCell.configureCell(contentProvider=0x00007fff519c23f8, self=0x00007ff1e5893800) -> () + 132 at ReaderPostCardCell.swift:251
    frame #3: 0x000000010e78b1af WordPress`ReaderStreamViewController.configurePostCardCell(cell=0x00007ff1e5893800, post=0x00006000000dea00, self=0x00007ff1e18a4600) -> () + 591 at ReaderStreamViewController.swift:1321
    frame #4: 0x000000010e792b92 WordPress`ReaderStreamViewController.tableView(tableView=0x00007ff1e2094600, indexPath=0xc000000000000016, self=0x00007ff1e18a4600) -> UITableViewCell + 2706 at ReaderStreamViewController.swift:1641
    frame #5: 0x000000010e792c9f WordPress`@objc ReaderStreamViewController.tableView(UITableView, cellForRowAtIndexPath : NSIndexPath) -> UITableViewCell + 79 at ReaderStreamViewController.swift:0
    frame #6: 0x000000010e3287bd WordPress`-[WPTableViewHandler tableView:cellForRowAtIndexPath:](self=0x0000600000110f20, _cmd="tableView:cellForRowAtIndexPath:", tableView=0x00007ff1e2094600, indexPath=0xc000000000000016) + 205 at WPTableViewHandler.m:322
    frame #7: 0x00000001121a27b5 UIKit`-[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 757
    frame #8: 0x00000001121a2a13 UIKit`-[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
    frame #9: 0x000000011217647d UIKit`-[UITableView _updateVisibleCellsNow:isRecursive:] + 3295
    frame #10: 0x00000001121890c7 UIKit`-[UITableView _visibleCells] + 27
    frame #11: 0x000000010e326363 WordPress`-[WPTableViewHandler refreshTableViewPreservingOffset](self=0x0000600000110f20, _cmd="refreshTableViewPreservingOffset") + 915 at WPTableViewHandler.m:98
    frame #12: 0x000000010e78a4c9 WordPress`ReaderStreamViewController.cleanupAfterSync(refresh=true, self=0x00007ff1e18a4600) -> () + 265 at ReaderStreamViewController.swift:1262
    frame #13: 0x000000010e790029 WordPress`ReaderStreamViewController.syncContentEnded(self=0x00007ff1e18a4600) -> () + 233 at ReaderStreamViewController.swift:1440
    frame #14: 0x000000010e790052 WordPress`@objc ReaderStreamViewController.syncContentEnded() -> () + 34 at ReaderStreamViewController.swift:0
    frame #15: 0x000000010e8a2d0f WordPress`partial apply ObjC forwarder with unmangled suffix ".36" + 31
    frame #16: 0x000000010e50e931 WordPress`thunk + 17 at NotificationSyncMediator.swift:0
    frame #17: 0x000000010e8a2db1 WordPress`partial apply for thunk + 81 at WPContentSyncHelper.swift:0
    frame #18: 0x000000010e8a287b WordPress`WPContentSyncHelper.(error=false, self=0x0000600000429d40)(error : Bool) -> () + 827 at WPContentSyncHelper.swift:101
    frame #19: 0x000000010e8a1661 WordPress`WPContentSyncHelper.(hasMore=true, self=0x0000600000429d40) -> Bool).(closure #1) + 129 at WPContentSyncHelper.swift:53
    frame #20: 0x000000010e7852ca WordPress`thunk + 26 at ReaderStreamViewController.swift:0
    frame #21: 0x000000010e8a1721 WordPress`partial apply for thunk + 81 at WPContentSyncHelper.swift:0
    frame #22: 0x000000010e8a1751 WordPress`thunk + 33 at WPContentSyncHelper.swift:0
    frame #23: 0x000000010e66c05b WordPress`thunk + 59 at SwitchTableViewCell.swift:0
    frame #24: 0x000000010e66c25a WordPress`thunk + 42 at SwitchTableViewCell.swift:0
    frame #25: 0x000000010e7852ca WordPress`thunk + 26 at ReaderStreamViewController.swift:0
    frame #26: 0x000000010e78fa11 WordPress`partial apply for thunk + 81 at ReaderStreamViewController.swift:0
    frame #27: 0x000000010e784ddc WordPress`ReaderStreamViewController.(self=0x00007ff1e18a4600, objectID=0xd0000000068c0010, success=0x000000010e78f9c0 WordPress`partial apply forwarder for reabstraction thunk helper from @callee_owned (@unowned Swift.Bool) -> (@unowned ()) to @callee_owned (@in (hasMore : Swift.Bool)) -> (@out ()) with unmangled suffix ".98" at ReaderStreamViewController.swift, hasMore=true) -> ()?, failure : (error : NSError) -> ()?) -> ()).(closure #1).(closure #1).(closure #1) + 364 at ReaderStreamViewController.swift:1129
    frame #28: 0x000000010e4f4ed7 WordPress`thunk + 39 at PageListViewController.swift:0
    frame #29: 0x0000000117ef5980 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #30: 0x0000000117f1f0cd libdispatch.dylib`_dispatch_client_callout + 8
    frame #31: 0x0000000117eff8d6 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 406
    frame #32: 0x0000000116ffe4f9 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    frame #33: 0x0000000116fc3f8d CoreFoundation`__CFRunLoopRun + 2205
    frame #34: 0x0000000116fc3494 CoreFoundation`CFRunLoopRunSpecific + 420
    frame #35: 0x0000000119a6da6f GraphicsServices`GSEventRunModal + 161
    frame #36: 0x0000000112035964 UIKit`UIApplicationMain + 159
    frame #37: 0x000000010e242cfe WordPress`main(argc=1, argv=0x00007fff519c4660) + 62 at main.m:5
    frame #38: 0x0000000117f6b68d libdyld.dylib`start + 1
(lldb) po provider
<ReaderPost: 0x6000000dea00> (entity: ReaderPost; id: 0xd000000009180016 <x-coredata://F658C6DC-696A-4806-AF72-9CD93CE7B39A/ReaderPost/p582> ; data: {
    author = nil;
    authorAvatarURL = nil;
    authorDisplayName = nil;
    authorEmail = nil;
    authorID = nil;
    authorURL = nil;
    blogDescription = nil;
    blogName = nil;
    blogURL = nil;
    commentCount = nil;
    comments = "<relationship fault: 0x600000636180 'comments'>";
    commentsOpen = nil;
    content = nil;
    crossPostMeta = nil;
    dateSynced = nil;
    "date_created_gmt" = nil;
    featuredImage = nil;
    feedID = nil;
    feedItemID = nil;
    globalID = nil;
    isBlogPrivate = nil;
    isExternal = nil;
    isFollowing = nil;
    isJetpack = nil;
    isLiked = nil;
    isLikesEnabled = nil;
    isReblogged = nil;
    isSharingEnabled = nil;
    isSiteBlocked = nil;
    isWPCom = nil;
    likeCount = nil;
    "mt_excerpt" = nil;
    "mt_text_more" = nil;
    password = nil;
    pathForDisplayImage = nil;
    permaLink = nil;
    postAvatar = nil;
    postID = nil;
    postTitle = nil;
    "post_thumbnail" = nil;
    primaryTag = nil;
    primaryTagSlug = nil;
    railcar = nil;
    readingTime = nil;
    remoteStatusNumber = nil;
    score = nil;
    siteID = nil;
    siteIconURL = nil;
    sortDate = nil;
    sortRank = nil;
    sourceAttribution = nil;
    status = nil;
    summary = nil;
    tags = nil;
    topic = nil;
    wordCount = nil;
    "wp_slug" = nil;
})
```

cc @aerych

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6297 
The crash in #6297 occurs when the reader stream kicks off its auto sync while the detail is being viewed, and then the post shown in the detail is cleaned up by the sync.  This patch avoids the crash by deferring the auto sync until the stream is the visible controller.

It would be nice if at some point we could A) completely decouple syncing from the controller and B) have a nice way of making sure "active" content is not deleted while its needed. Maybe a separate persistent store.  For now this patch will avoid the crash until we can build out a more robust solution.

To test:
Follow the steps outlined in the issue.  Confirm there is no crash

Needs review: @koke

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift [hunk 1]
```diff
@@ -1043,7 +1046,13 @@ import WordPressComAnalytics
     /// are met.
     /// - The app must have a internet connection.
     /// - The current time must be greater than the last sync interval.
-    func syncIfAppropriate() {
+    /// - Autosync must not have already occurred.
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift]: I don't understand how/if this is related to the crash or just a new behavior.

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift [hunk 2]
```diff
@@ -1043,7 +1046,13 @@ import WordPressComAnalytics
...
+    ///
+    /// NOTE:  We want to avoid automatically syncing when the controller is created
+    /// via state restoration until the controller's view is in the window.
+    /// See: https://github.com/wordpress-mobile/WordPress-iOS/issues/6297
+    ///
+    func autoSyncIfAppropriate(viewWillAppear viewWillAppear: Bool) {
```
Comment (koke) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift]: I'm confused about this method and the changes. I might be getting this completely wrong, but here's my understanding so far:

- This is called on `viewWillAppear` and `configureControllerForTopic`, which in turn is called in `viewDidLoad` and when `readerTopic` is changed.
- The `viewWillAppear` argument and logic only starts to make sense once you know when it's going to be called. For that I suspect this is too tightly coupled with how it's being called, and perhaps calling for a refactor.
- Since it already has a check against `refreshInterval`, instead of a `didAutoSync` I think this needs to check if it's already syncing. `WPContentSyncHelper` already does this check internally so in theory you can call `autoSyncIfAppropriate` twice in a row and it'll only sync once.
- `didAutoSync` will prevent any further sync, even when it's necessary: go to Reader > Search, search for `food`, then search for anything else and it won't work.
- I believe the new check tries to prevent the sync from happening when invoked via `viewDidLoad` on UI restoration. I think sync should never be called from `viewDidLoad`. Can we just move `syncIfAppropriate` out of `configureControllerForTopic` and call it directly on `viewWillAppear` and `readerTopic.didSet`?

Comment (aerych) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift]: The goal of the patch is to prevent auto syncing unless the stream is the active view controller. This fixes the crash you found by avoiding any deletion or cleanup triggered by the auto sync while content is still being viewed.
You're feedback got me rethinking the approach and I believe I've been able to simplify things and still achieve the goal.
Ready for another look :)

**Comment by aerych** [comment]
Thanks @koke !
