### PR TITLE
Deleted post with local changes appears only under Trashed tab

### LINKED ISSUE #12763: Deleted post with local changes appears under Published/Drafts/Scheduled and Trashed
### Expected behavior

If a post is deleted, it should only appear under the "Trashed" tab.

### Actual behavior

When a post with "Local changes" is deleted it appears both in his original tab and "Trashed".

### Steps to reproduce the behavior

1. Publish a post
2. While offline, edit the post and tap "Update"
3. Tap "Cancel" in post list
4. Go back online, wait for the post to be auto saved
5. Tap More -> "Move to Trash"
6. Refresh the list, the post will appear under "Published" and "Trashed"

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #12763

To test:

1. Publish a post
2. While offline, edit the post and tap "Update"
3. Tap "Cancel" in the post list
4. Go back online, wait for the post to be autosaved
5. Tap More -> "Move to Trash"
6. Refresh the list, the post will appear only under "Trashed"

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

File: WordPress/WordPressTest/Services/PostServiceWPComTests.swift [hunk 1]
```diff
@@ -112,6 +112,27 @@ class PostServiceWPComTests: XCTestCase {
...
+        remoteMock.remotePostToReturnOnTrashPost = remotePost
+
+        // Act
+        waitUntil(timeout: 3) { done in
+         self.service.trashPost(post, success: {
+             done()
+         }, failure: self.impossibleFailureBlock)
+        }
+
+        // Assert
```
Comment (shiki) [inline WordPress/WordPressTest/Services/PostServiceWPComTests.swift]: Do you think it's worth it to include this too?

```swift
        expect(post.statusAfterSync).to(equal(.trash))
        expect(post.status).to(equal(.trash))
```

**Comment by shiki** [comment]
Changed the target branch to `develop` because `issue/12240-master-branch` was just merged to `develop`.

**Comment by shiki** [comment]
Please feel free to make changes (if you want to) and merge.

File: WordPress/WordPressTest/Services/PostServiceWPComTests.swift (hunk 1 above)
Comment (leandroalonso) [reply WordPress/WordPressTest/Services/PostServiceWPComTests.swift]: Done in 43b2e686a4e50b14baf0230dc1de3d3b6108c736
