### PR TITLE
Disable Crashlytics if user opts-out of tracking

### LINKED ISSUE #9764: Respect analytics opt-out setting with 3rd parties
Make sure when the user opts out of tracking (#9359) it not only disables Tracks but also make sure we're not tracking anything in Fabric or Helpshift.

### PR DESCRIPTION
**Pull request by bummytime**
This PR configures Crashlytics to respect the "Collect information" setting on the privacy screen:

screen shot 2018-07-16 at 4 16 21 pm

 If OFF, Crashlytics will not report crashes. If ON, Crashalytics will report crashes. Code-wise, this PR essentially mimics the opt-out logic found in `WPAppAnalytics` and applies it to `WPCrashlytics`. 

A couple of things to note:

1. In the [Fabric documentation](https://docs.fabric.io/apple/crashlytics/advanced-setup.html#enable-opt-in-reporting), it mentions users will need to "completely quit the app in order for the change to take effect". Instead displaying a message like that to our users, I opted call the completion handler in `crashlyticsDidDetectReportForLastExecution` with a `NO` param which causes the current report to be trashed and never sent over the wire.  

_(Note that the next launch of WPiOS will **not** startup Crashlytics all all.)_

2. It is possible that `[Fabric with:@[CrashlyticsKit]];` will get called multiple times if the user toggles the privacy setting on and off a few times. Per their docs, that is ok:

> Only the first call to this method is honored. Subsequent calls are no-ops.

You will see a warning in the console, but that is about it.

Fixes #9764 

## Testing

I am not exactly sure the best way to test this beyond setting some breakpoints in `WPCrashlytics` and verifying the appropriate code is executed.  FWIW, [Crashlytics does provide an easy way to force a crash](https://support.crashlytics.com/knowledgebase/articles/92522-is-there-a-quick-way-to-force-a-crash) by putting `[[Crashlytics sharedInstance] crash];` somewhere fun. 🎉 

### Opt-in/Opt-out configuration
1. Build and run the app - you may have to [override some settings here](https://github.com/wordpress-mobile/WordPress-iOS/blob/6f146402e97af2ed55d0f64ccd681f7a082ffeed/WordPress/Classes/System/WordPressAppDelegate%2BSwift.swift#L36-L44) to force the loading of Crashlytics in `DEBUG`
2. Goto Me→App Settings→Privacy Settings and toggle the "Collect Information"
3. Verify that `WPCrashlytics.setUserHasOptedOut` is called with the appropriate values

### Startup of Crashlytics based on opt-out setting
1. Build and run the app
2. On app launch, if opt-out setting is YES: verify [the code](https://github.com/wordpress-mobile/WordPress-iOS/blob/3b8f08e23f66791e000e9d7e0d5653c8a0c034b4/WordPress/Classes/Utility/WPCrashlytics.m#L55-L59) in `WPCrashlytics.startupCrashlyticsIfNeeded` is not executed.
3. On app launch, if opt-out setting is NO: verify [the code](https://github.com/wordpress-mobile/WordPress-iOS/blob/3b8f08e23f66791e000e9d7e0d5653c8a0c034b4/WordPress/Classes/Utility/WPCrashlytics.m#L55-L59) in `WPCrashlytics.startupCrashlyticsIfNeeded` is executed.

@frosty would you be so kind to take a peek and let me know if it makes sense to you. Thanks!! 😄 

/cc @loremattei

### CODE REVIEW

File: WordPress/Classes/Utility/WPCrashlytics.h [hunk 1]
```diff
@@ -8,6 +8,24 @@
...
 @interface WPCrashlytics : NSObject
 
+#pragma mark - Init
+
 - (instancetype)initWithAPIKey:(NSString *)apiKey;
 
+#pragma mark - User Opt Out
+
+/**
+ *  @brief      Call this method to know if the user has opted out of crashalytics tracking.
```
Comment (frosty) [inline WordPress/Classes/Utility/WPCrashlytics.h]: Suuuuper nitpicky – `crashalytics` -> `Crashlytics`

File: WordPress/Classes/Utility/WPCrashlytics.m [hunk 2]
```diff
@@ -28,15 +34,81 @@ - (instancetype)initWithAPIKey:(NSString *)apiKey
...
+#pragma mark - Tracks Opt Out
+
+- (void)initializeOptOutTracking {
+    if ([WPCrashlytics userHasOptedOutIsSet]) {
+        // We've already configured the opt out setting
+        return;
+    }
+
+    if ([[NSUserDefaults standardUserDefaults] boolForKey:WPAppAnalyticsDefaultsUserOptedOut] == YES) {
+        // If the user has already explicitly disabled tracking for analytics, let's ensure we turn off crashalytics tracking as well
```
Comment (frosty) [inline WordPress/Classes/Utility/WPCrashlytics.m]: `crashalytics` -> `Crashlytics` again :)

File: WordPress/Classes/ViewRelated/Me/PrivacySettingsViewController.swift [hunk 3]
```diff
@@ -112,6 +112,9 @@ class PrivacySettingsViewController: UITableViewController {
 
             let accountService = AccountService(managedObjectContext: ContextManager.sharedInstance().mainContext)
             AccountSettingsHelper(accountService: accountService).updateTracksOptOutSetting(!enabled)
+
+            let crashalytics = WordPressAppDelegate.sharedInstance().crashlytics
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Me/PrivacySettingsViewController.swift]: One more nitpick – `crashalytics` -> `crashlytics`

File: WordPress/Classes/Utility/WPCrashlytics.h (hunk 1 above)
Comment (bummytime) [reply WordPress/Classes/Utility/WPCrashlytics.h]: Gah!. You are still my human spellchecker @frosty !! 😆 👍

**Comment by bummytime** [comment]
Thanks @frosty !
