### PR TITLE
Blogging reminders in notification settings

### LINKED ISSUE #17152: Add Blogging Reminders toggle to Notifications Settings
### Expected behavior
I expect to be able to toggle Blogging Reminders notification in the same place I toggle other notifications 

### Actual behavior
Blogging Reminder notification is under Site Settings, the reset of the notifications are under Notifications -> Settings -> Site -> Push Notifications. 

### Steps to reproduce the behavior
Notifications Settings             |  Blogging Reminders 
:-------------------------:|:-------------------------:
IMG_9875|IMG_9876

### PR DESCRIPTION
**Pull request by frosty**
Fixes #17152.

This PR adds blogging reminders to the Push Notifications Settings section of the app. The screen was written with the intention of being driven entirely by a provided settings object, but I've added a special case to handle adding a Blogging Reminders row when necessary. There would likely be cleaner approaches to supporting multiple types of content in this screen, but as it's been so infrequently modified I figured that can be a future job if we ever need to add more things in here.

I also switched out some of the internal classes for structs and added a protocol to make it easier to support the different types.

| No reminders set | Reminders set | Doesn't show up in other settings |
|---|---|---|
| Simulator Screen Shot - iPhone 12 - 2021-09-30 at 17 02 30 | Simulator Screen Shot - iPhone 12 - 2021-09-30 at 17 17 22 | Simulator Screen Shot - iPhone 12 - 2021-09-30 at 16 44 19 |

#### Test 1

Site with no blogging reminders set up

- Go to Notifications > Notification Settings, and choose a site from the list at the top that **doesn't** already have blogging reminders set up. Then choose Push Notifications.
- You should see Blogging Reminders at the bottom of the list, with the value of None Set.
- Tap the row, and ensure you can set reminders. Also check that the row is updated after the reminders setting view is dismissed.
- Check in your console that the source for the flow start event is `notification_settings`:

```
2021-09-30 17:48:40:734 WordPress[58411:1720752] 🔵 Tracked: blogging_reminders_flow_start <blog_type: wpcom, source: notification_settings>
```

#### Test 2

Site with blogging reminders set up

- Go to Notifications > Notification Settings, and choose a site from the list at the top that **does** already have blogging reminders set up. Then choose Push Notifications.
- You should see Blogging Reminders at the bottom of the list, with a value showing your current reminder schedule.
- Tap the row, and ensure you can set reminders. Also check that the row is updated after the reminders setting view is dismissed.
- Check in your console that the source for the flow start event is `notification_settings`:

```
2021-09-30 17:48:40:734 WordPress[58411:1720752] 🔵 Tracked: blogging_reminders_flow_start <blog_type: wpcom, source: notification_settings>
```

#### Test 3

Other settings screens

- Go to Notifications > Notification Settings, and navigate into the subscreens of "Comments on other sites" and "Email from WordPress.com" (at the bottom of the list). You should not see Blogging Reminders show up there at all.

## Regression Notes
1. Potential unintended areas of impact

Other settings screens.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I conditionally added the row in one specific situation, and viewed the other settings screens to ensure the row wasn't visible.

3. What automated tests I added (or what prevented me from doing so)

None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift [hunk 1]
```diff
@@ -98,8 +98,8 @@ class NotificationSettingDetailsViewController: UITableViewController {
 
     private func setupTableView() {
         // Register the cells
-        tableView.register(SwitchTableViewCell.self, forCellReuseIdentifier: Row.Kind.Setting.rawValue)
-        tableView.register(WPTableViewCell.self, forCellReuseIdentifier: Row.Kind.Text.rawValue)
+        tableView.register(SwitchTableViewCell.self, forCellReuseIdentifier: CellKind.Setting.rawValue)
+        tableView.register(WPTableViewCellValue1.self, forCellReuseIdentifier: CellKind.Text.rawValue)
```
Comment (Gio2018) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift:102]: not really a great naming, but it's pre-existing..

**Review by Gio2018 — APPROVED** [review]
:shipit: !

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift (hunk 1 above)
Comment (frosty) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift:102]: Yeah, these things are everywhere!

Comment (frosty) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift:102]: Yeah, there a whole bunch of pre-existing cell types like this
