### PR TITLE
The Migration flow doesn't complete automatically if the user closes and re-opens the app

### LINKED ISSUE #19884: The Migration flow auto completes when the user closes and re-opens the app
### Expected behavior

If the user interrupts the migration flow by closing the app, next time they open the app, they should land on the Migration Welcome screen.

### Actual behavior

The Migration flow completes automatically when the user closes and re-open the app.

<video src="https://user-images.githubusercontent.com/9609223/211593409-d68d6a7b-fe7a-4db3-81d7-010eb90c44e2.MP4"></video>

### Steps to reproduce the behavior

1. Clean install both WordPress and Jetpack app
2. Start the Migration Flow
3. While on the Welcome step, close the and re-open the Jetpack app
4. The Migration Flow is completed automatically without the user's consent

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/19884

## Description

This PR fixes the migration auto-complete issue when the user interrupts the migration mid-flow. Previously, when the user starts the migration and lands on the Welcome screen, they could skip the whole migration flow by simply closing and re-opening the app.

This was happening because the migration was marked completed before the Welcome screen even appears. This PR fixes this issue by marking the migration as completed when the user reaches the final screen.

| Before | After |
| ------- | ----- |
| <video src="https://user-images.githubusercontent.com/9609223/211924722-6a87a39e-9c70-4664-a28c-3811f39614d8.MP4"></video> | <video src="https://user-images.githubusercontent.com/9609223/211923592-4e313c00-74d1-4770-a204-1c426a4a8470.mp4"></video> |

## Technical Details

The goal is to display the Migration UI again even if the user interrupts the migration mid flow. This PR achieves that goal by making the following changes:

1. Marks the Migration Completed when the user reaches the final migration step. [Previously, the Migration was marked as completed before the Welcome Screen shows up](https://github.com/wordpress-mobile/WordPress-iOS/blob/4de5d26cb91d5458a39894ec13b09f815bc65edd/WordPress/Jetpack/Classes/System/JetpackWindowManager.swift#L43). See the new [implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/files#diff-55f0c4dab8e830e868c7789a868e4b9cfd94d35268d32e7e13dbb4dc490bdb2eR46).
2. Refactors the Migration Trigger conditions. Previously the Migration UI appears only when [the user is not logged in and the migration wasn't completed.](https://github.com/wordpress-mobile/WordPress-iOS/blob/4de5d26cb91d5458a39894ec13b09f815bc65edd/WordPress/Jetpack/Classes/System/JetpackWindowManager.swift#L11) Now, there is case where the Migration UI should appear even if the user is logged in. See new [implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/files#diff-bbbf5bdbd178be9be3ed7ba8cea3ae4a19b0b1f28cacdd647d2704014f96b98bR63).
3. If the Migration UI should appear while the user is logged in, the app doesn't import the content again, since the user is already logged in and the Sites List needed for the Welcome screen are already available. See [implementation](https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/files#diff-bbbf5bdbd178be9be3ed7ba8cea3ae4a19b0b1f28cacdd647d2704014f96b98bR92).

#### Case 1: The Happy Case

Testing the case of a user installing the Jetpack app for the first time.

1. Clean install WordPress app and log into your account.
2. Clean install Jetpack app.
3. **Expect** the "Load WordPress" screen to show up.
4.  Start the Migration flow by tapping the "Open WordPress" button.
5. **Expect** the Welcome Screen to appear.
6. Tap "Continue".
7. **Expect** the Notification screen to appear.
8. Close and re-open the Jetpack app.
9. **Expect** the Welcome screen to appear.

#### Case 2: User already performed the migration using WP/JP 21.4+

Testing the case of users who already performed the migration flow in WPiOS / JPiOS 21.4

1. Install both WordPress and Jetpack 21.4 from AppStore.
2. On WordPress, Log in and start the Migration Flow.
3. On Jetpack, complete the Migration Flow.
10. Install this build to update the Jetpack app.
11. **Expect** the Migration Flow NOT to start.
12. Sign out on Jetpack.
13. Switch to WordPress and try to start the Migration Flow.
5. **Expect** the Migration Flow NOT to start.

#### Case 3: Different WordPress and Jetpack versions

1. Clean Install WordPress 21.4 from AppStore and log in.
2. Clean install Jetpack from this branch.
3. **Expect** the "Load WordPress" screen to show up.
4. Start the Migration Flow by tapping "Open WordPress" button.
5. Complete the Migration Flow on Jetpack.

#### Case 4: Simulating Multiple Content Imports

Previously the content import logic was only executed once, because the migration was marked as completed before the Welcome Screen appears. Now, there is a scenario where the content import can be executed multiple times.

We should test whether the Jetpack app can handle multiple content imports.

1. Clean install WordPress app and log into your account.
7. Clean install Jetpack app.
8. **Expect** the "Load WordPress" screen to show up.
9. Start the Migration flow by tapping the "Open WordPress" button.
10. **Expect** the Welcome Screen to appear.
14. Tap "Me" button.
15. Tap "Log Out".
16. Close and re-open the Jetpack app.
17. **Expect** the "Load WordPress" screen to show up. 
18. Start the Migration flow by tapping the "Open WordPress" button.
19. Complete the Migration Flow.

## Regression Notes
1. Potential unintended areas of impact
This PR impacts the conditions to trigger the migration flow on Jetpack. It's preferred to test the migration flow.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual Tests.

3. What automated tests I added (or what prevented me from doing so)
None.

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift [hunk 1]
```diff
@@ -166,12 +167,22 @@ extension UserPersistentRepositoryUtility {
...
+                // Migrate the value of the old `isJPContentImportCompleteKey` to `jetpackContentMigrationStateKey`
+                let state = MigrationState.completed
+                repository.set(state.rawValue, forKey: UPRUConstants.jetpackContentMigrationStateKey)
+                repository.set(nil, forKey: UPRUConstants.isJPContentImportCompleteKey)
+                return state
+            } else {
+                return .notStarted
+            }
+        } set {
+            UserPersistentStoreFactory.instance().set(newValue.rawValue, forKey: UPRUConstants.jetpackContentMigrationStateKey)
```
Comment (salimbraksa) [inline WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift:185]: This code replaces the old `isJPContentImportComplete` boolean with `jetpackContentMigrationState` of type `MigrationState`. 

To make sure the Migration Flow doesn't appear again for users who already went through the Migration in WPiOS / JPiOS 21.4, this code migrates the existing value of `isJPContentImportComplete` to `jetpackContentMigrationState` ( `true` -> `MigrationState.completed` ).

**Comment by salimbraksa** [comment]
**Case 3** is currently not working as expected. This will be fixed in another PR and this PR won't be merged until that issue is resolved.

File: WordPress/Jetpack/Classes/System/JetpackWindowManager.swift [hunk 2]
```diff
@@ -2,64 +2,74 @@ import Combine
...
-                self.handleMigrationFailure(error)
-            }
+    @discardableResult
+    func startMigrationFlowIfNeeded(_ blog: Blog? = nil) -> Bool {
+        guard shouldStartMigrationFlow else {
+            return false
         }
+        self.importAndShowMigrationContent(blog)
+        return true
     }
```
Comment (salimbraksa) [inline WordPress/Jetpack/Classes/System/JetpackWindowManager.swift:65]: This is just a convenient method to avoid calling the following code in [JetpackWindowManager.showUI](https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/files#diff-bbbf5bdbd178be9be3ed7ba8cea3ae4a19b0b1f28cacdd647d2704014f96b98bR20) and [AppDelegate](https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/files#diff-a0d929b4f010704e861fa3bca33fd60c2accdbeed6669393b613d9390a7b2ae5R201):

```swift
if shouldStartMigrationFlow {
    importAndShowMigrationContent(blog)
}
```

File: WordPress/Jetpack/Classes/System/JetpackWindowManager.swift [hunk 3]
```diff
@@ -2,64 +2,74 @@ import Combine
...
+    ///  2. Or, User is logged in and the migration has started but still in progress. This scenario could happen if the migration flow starts but interrupted mid flow.
+    ///
+    var shouldStartMigrationFlow: Bool {
+        guard isCompatibleWordPressAppPresent && FeatureFlag.contentMigration.enabled else {
+            return false
+        }
+        let migrationState = UserPersistentStoreFactory.instance().jetpackContentMigrationState
+        let loggedIn = AccountHelper.isLoggedIn
+        return loggedIn ? migrationState == .inProgress : migrationState != .completed
     }
```
Comment (salimbraksa) [inline WordPress/Jetpack/Classes/System/JetpackWindowManager.swift:88]: I want to mention that in the previous implementation, there was 2 flags:
- [shouldImportMigrationData](https://github.com/wordpress-mobile/WordPress-iOS/blob/4de5d26cb91d5458a39894ec13b09f815bc65edd/WordPress/Jetpack/Classes/System/JetpackWindowManager.swift#L11): This the first flag that gets called, and it checks whether the content import should be called or not. 
- [shouldShowMigrationUI](https://github.com/wordpress-mobile/WordPress-iOS/blob/4de5d26cb91d5458a39894ec13b09f815bc65edd/WordPress/Jetpack/Classes/System/JetpackWindowManager.swift#L59): This flag is called after the content import is successful, and it's used to check whether to show the Migration UI or not. I think this flag is unnecessary, because after the content import is successful, the Migration UI should appear.

In this PR, `shouldImportMigrationData` was refactored to `shouldStartMigrationFlow` and `shouldShowMigrationUI` was removed.

File: WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Common/Navigation/MigrationFlowCoordinator.swift [hunk 4]
```diff
@@ -3,16 +3,61 @@ import UserNotifications
...
+        self.migrationEmailService = migrationEmailService
+        self.userPersistentRepository = userPersistentRepository
+        self.userPersistentRepository.jetpackContentMigrationState = .inProgress
+    }
+
+    deinit {
+        if userPersistentRepository.jetpackContentMigrationState != .completed {
+            self.userPersistentRepository.jetpackContentMigrationState = .notStarted
+        }
+    }
```
Comment (salimbraksa) [inline WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Common/Navigation/MigrationFlowCoordinator.swift:32]: The `init` and the `de-init` of `MigrationFlowCoordinator` updates the content migration state. When the migration starts, we mark the state as `inProgress`, and when it ends, we mark the state back to `notStarted` if the migration didn't complete.

File: WordPress/Jetpack/Classes/System/JetpackWindowManager.swift [hunk 5]
```diff
@@ -2,64 +2,87 @@ import Combine
...
-                UserPersistentStoreFactory.instance().isJPContentImportComplete = true
-                NotificationCenter.default.post(name: .WPAccountDefaultWordPressComAccountChanged, object: self)
-                self.showMigrationUIIfNeeded(blog)
-                self.sendMigrationEmail()
-            case .failure(let error):
-                self.migrationTracker.trackContentImportFailed(reason: error.localizedDescription)
-                self.handleMigrationFailure(error)
-            }
+    @discardableResult
+    func startMigrationFlowIfNeeded(_ blog: Blog? = nil) -> Bool {
```
Comment (twstokes) [inline WordPress/Jetpack/Classes/System/JetpackWindowManager.swift]: Should we add documentation to explain the `Bool` return value? It wasn't super clear to me at first glance.

File: WordPress/Jetpack/Classes/System/JetpackWindowManager.swift [hunk 6]
```diff
@@ -2,64 +2,87 @@ import Combine
...
 }
 
-// MARK: - Private Helpers
+// MARK: Private Helpers
 
 private extension JetpackWindowManager {
 
-    var shouldShowMigrationUI: Bool {
-        return FeatureFlag.contentMigration.enabled && AccountHelper.isLoggedIn
+    /// Checks whether the migration flow should start or not.
```
Comment (twstokes) [inline WordPress/Jetpack/Classes/System/JetpackWindowManager.swift:72]: Thanks for adding this breakdown! 👏

**Review by twstokes — APPROVED** [review]
LGTM @salimbraksa! 🚀 All tests passed.

It wouldn't hurt to have another set of 👀 on this for a review, but from what I can tell it's functioning correctly.

File: WordPress/Jetpack/Classes/System/JetpackWindowManager.swift (hunk 5 above)
Comment (salimbraksa) [reply WordPress/Jetpack/Classes/System/JetpackWindowManager.swift]: Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/19888/commits/46ebbc3de675a7e4c36ed0e8b9331c248ab08076

File: WordPress/Classes/System/WordPressAppDelegate.swift [hunk 7]
```diff
@@ -646,6 +645,8 @@ extension WordPressAppDelegate {
 #if JETPACK
         case is MigrationNavigationController:
             return "Jetpack Migration View"
+        case is MigrationLoadWordPressViewController:
+            return "Jetpack Migration Load WordPress View"
```
Comment (dvdchr) [inline WordPress/Classes/System/WordPressAppDelegate.swift:649]: Perhaps for a future note, but the root cause is the premature initialization of `WPTabBarController`. While adding the switch cases for possible root view controllers would solve the issue, it is a time bomb waiting to happen when a new root view controller is added.

I think this can be solved by not calling the `RootViewCoordinator.sharedPresenter` in the default case and instead adding a specific case for `WPTabBarController`. The default case should return nil instead. This way, the analytics value would be correct when there's an unhandled root view controller (i.e., returning `nil` instead of the default tab of the `WPTabBarController`, which is not visible to the user).

However, this should probably be implemented in a separate PR to avoid scope-creeping this PR. 😅 I can look into it this week.

**Review by dvdchr — APPROVED** [review]
LGTM. I tested and verified that the crash no longer happens on my side. :shipit:
