### PR TITLE
Reader: Missing Report and Block actions from the Post Menu Sheet

### LINKED ISSUE #20706: Reader: Block and Report actions are missing from Following and Discover feeds
### Expected behavior
When on `Reader > Following` or `Reader > Discover` screens and the user taps a post's menu button, the user is presented with a list of actions. The list should include the following actions:

- Block this site
- Block this user
- Report this post
- Report this user

This is a regression bug. Caused in:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/20490

### Actual behavior
The block / report actions are not presented in the list.

### Steps to reproduce the behavior
1. While Logged In, Head to the Reader screen.
2. Head to either Following or Discover screens.
3. Tap any post's menu button ( the 3 dots icon ), as long as the post is from a WPCOM site.
4. The Report / Block actions are not visible.

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #20706

## Description

This PR fixes an issue in Reader that was causing the Report and Block actions to be missing from Post Menu actions sheet.

| Before | After |
| ------ | ------ |
|  |  |

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
None.

3. What automated tests I added (or what prevented me from doing so)
Added unit tests to verify that the Report / Block actions are present when certain conditions are fulfilled.

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## UI Changes testing checklist:
N/A

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderMenuAction.swift [hunk 1]
```diff
@@ -13,7 +13,15 @@ final class ReaderMenuAction {
...
-        self.execute(post: post, context: context, anchor: .view(anchor), vc: vc, source: source, followCommentsService: followCommentsService)
+        self.execute(
+            post: post,
+            context: context,
+            readerTopic: readerTopic,
+            anchor: .view(anchor),
+            vc: vc,
+            source: source,
+            followCommentsService: followCommentsService
+        )
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/ReaderMenuAction.swift:24]: The bug is that `readerTopic` wasn't passed to the `execute` method.

File: WordPress/WordPressTest/ReaderPostCellActionsTests.swift [hunk 2]
```diff
@@ -0,0 +1,106 @@
+import XCTest
+
+@testable import WordPress
+
+final class ReaderPostCellActionsTests: CoreDataTestCase {
```
Comment (salimbraksa) [inline WordPress/WordPressTest/ReaderPostCellActionsTests.swift:5]: I added 2 unit tests to verify the presence of the Report / Block actions when the actions sheet is presented.

**Review by alpavanoglu — APPROVED** [review]
LGTM 🚀
