### PR TITLE
Run the "null blog property sanitization" logic as the very first Core Data operation

### LINKED ISSUE #20847: Core Data: crash triggered from `NullBlogPropertySanitizer`
### Steps to reproduce the behavior

This was a crash found via Xcode's Organiser. It has a similar stack trace as https://github.com/wordpress-mobile/WordPress-iOS/issues/20840, just with `NullBlogPropertySanitizer.sanitize()` being part of the call stack.

Organiser backtrace:
Screenshot 2023-06-13 at 10 45 19

Pointing to code:
Screenshot 2023-06-13 at 10 44 12

### PR DESCRIPTION
**Pull request by crazytonyli**
The stacktrace captured in https://github.com/wordpress-mobile/WordPress-iOS/issues/20847 shows the "sanitization" work was done asynchronously from [its only call site the ContextManager initialiser](https://github.com/wordpress-mobile/WordPress-iOS/blob/e4db21b30a9fa50809d26493b670e7b39b9fabbe/WordPress/Classes/Utility/ContextManager.swift#L96).

Just by looking at the ContextManager's initialiser and [the documentation around the sanitization code's intention](https://github.com/wordpress-mobile/WordPress-iOS/blob/e4db21b30a9fa50809d26493b670e7b39b9fabbe/WordPress/Classes/Services/NullBlogPropertySanitizer.swift#L3), I think it's best to make sure the sanitization work is done before any other Core Data query, otherwise other parts of the app may (probably not likely) see an unexpected null blog property.

As I explained in https://github.com/wordpress-mobile/WordPress-iOS/issues/20847#issuecomment-1590225799, I don't think that crash was one of Matt's. So I opened this PR targeting the trunk branch, rather than the release branch.

@leandroalonso This null blog property sanitizer code was introduced in your PR https://github.com/wordpress-mobile/WordPress-iOS/pull/13021. I know it's been a while and it's okay if you forgot about the issue this code was trying to address. But I'd appreciate your review on this change. Thanks!

@mokagio @jkmassel This null blog property sanitizer code was added before my time. I don't know much about the context. Feel free to add more reviewers if needed.

## Test Instructions

Put a breakpoint inside the `entityNamesWithRequiredBlogProperties.forEach` line. Update `NullBlogPropertySanitizer.appWasUpdated` to return `true`. Run the app. The breakpoint should be triggered on the main thread with `ContextManager.init` appearing in the stacktrace as the caller.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
What's described in the test instructions.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by mokagio — APPROVED** [review]

File: WordPress/Classes/Services/NullBlogPropertySanitizer.swift [hunk 1]
```diff
@@ -58,6 +58,13 @@ import Foundation
 
             try? self.context.save()
         }
+
+        // Make sure the "sanitization" work is done before any other Core Data reads or writes.
+        if Thread.isMainThread, context.concurrencyType == .mainQueueConcurrencyType {
```
Comment (iangmaia) [inline WordPress/Classes/Services/NullBlogPropertySanitizer.swift:63]: From my understanding, this check isn't really necessary and more like a "double check", right?

Also... not knowing the codebase and standards very well, I see this class is out of the `ContextManager` scheme and I wonder if would make sense to somehow add this routine to the queues managed there (which of course would make it harder for it to be before other reads or writes).

Comment (crazytonyli) [reply WordPress/Classes/Services/NullBlogPropertySanitizer.swift:63]: > From my understanding, this check isn't really necessary and more like a "double check", right?

In most cases, probably yes. Because the `ContextManager.shared` singleton is created from a main thread which is the only place that calls this sanitizer function. But there is no guarantee that's always going to be the case. Unless we add a `precondition(Thread.isMainThread)` to say it's a programming error to call it in a background thread. BTW, I believe some unit tests call this function from a background thread.

> [...] add this routine to the queues managed there

My understanding of this sanitizer function is, it's supposed to be call as the very first Core Data operation, to ensure there is no models that have a blog property that's null. If that's indeed the case, we'll want to call this function immediately after the Core Data stack is initialized, to eliminated the race condition between this sanitizing work and other parts of app's Core Data calls. Calling it synchronously would has a better chance in achieving that than sending the function to a queue.
