### PR TITLE
PersonViewController: Updates Interface Messages

### LINKED ISSUE #5670: People: Include username or display name in messaging about the user
### Expected behavior

I expect messaging (buttons and errors) in People management to refer to the user I am working with, rather than a generic "User." For example, here are error messages from Calypso:
- User's role can't be changed: "There was an error updating @[username]"
- To remove a user: "Remove [Display Name]"
### Actual behavior

The messaging in the app refers to the user as "User" instead of by username/display name:
- User's role can't be changed: "Sorry! Something went wrong while updating the User's Role"
- To remove a user: "Remove User"

I'd suggest changing the app messaging to match Calypso.
### Steps to reproduce the behavior
1. Set up a site with two users: the site owner and a second account you are using in the app
2. Open the app (logged in to the second account)
3. Go to My Site > People
4. Select the site owner in the list of users
5. Try to change the user's role. Result: Error message appears "Sorry! Something went wrong while updating the User's Role"
6. Look for the option to remove the user from the site. The link is a generic "Remove User" instead of referring to the display name of the user being removed.

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #5670

### To test:
1. Set up a site with two users: the site owner and a second account you are using in the app
2. Open the app (logged in to the second account)
3. Go to My Site > People
4. Select the site owner in the list of users
4. Try to change the user's role. 
5. Verify that an alert shows up, with the following text: `There was an error updating @[username]`
6. Verify that the Remove User row now reads `Remove @[username]` instead of `Remove User`

Needs review: @frosty 
Sir, may i bug you with a quick review?. Thanks in advance!

Thanks @rachelmcr for spotting this one!!

### CODE REVIEW

**Comment by jleandroperez** [comment]
@frosty i've got a million testing accounts. Please, let me know if i can help you with anything!

File: WordPress/Classes/ViewRelated/People/PersonViewController.swift [hunk 1]
```diff
@@ -186,8 +186,9 @@ private extension PersonViewController {
     }
 
     func removeWasPressed() {
+        let title = NSLocalizedString("Remove", comment: "Remove Alert Title") + " " + person.username
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/People/PersonViewController.swift]: I think you might want to do this as a formatted string – `"Remote %@"`. It's possible that in other languages the order of the words might be switched around?

File: WordPress/Classes/ViewRelated/People/PersonViewController.swift [hunk 2]
```diff
@@ -302,7 +305,8 @@ private extension PersonViewController {
     }
 
     func setupRemoveCell() {
-        removeCell.textLabel?.text = NSLocalizedString("Remove User", comment: "Remove User. Verb")
+        let removeText = NSLocalizedString("Remove", comment: "Remove. Verb")
+        removeCell.textLabel?.text = removeText + " " + person.username
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/People/PersonViewController.swift]: Same comment as above, re: doing this as a formatted string.

File: WordPress/Classes/ViewRelated/People/PersonViewController.swift [hunk 3]
```diff
@@ -250,11 +251,13 @@ private extension PersonViewController {
...
-        let retryTitle      = NSLocalizedString("Retry", comment: "Retry updating User's Role")
-        let cancelTitle     = NSLocalizedString("Cancel", comment: "Cancel updating User's Role")
-        let title           = NSLocalizedString("Sorry!", comment: "Update User Failed Title")
-        let message         = NSLocalizedString("Something went wrong while updating the User's Role.", comment: "Updating Role failed error message")
-        let alertController = UIAlertController(title: title, message: message, preferredStyle: .Alert)
+        let retryTitle          = NSLocalizedString("Retry", comment: "Retry updating User's Role")
+        let cancelTitle         = NSLocalizedString("Cancel", comment: "Cancel updating User's Role")
+        let title               = NSLocalizedString("Sorry!", comment: "Update User Failed Title")
+        let localizedError      = NSLocalizedString("There was an error updating @", comment: "Updating Role failed error message")
+        let messageText         = localizedError + person.username
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/People/PersonViewController.swift]: Same comment as above, re: doing this as a formatted string.

**Comment by jleandroperez** [comment]
@frosty ready for another look!. Thank you for pointing that out!

**Comment by frosty** [comment]
Looks good! :shipit:

**Comment by jleandroperez** [comment]
Thanks sir!
