### PR TITLE
Quick Start: Fix orientation-related issues with quick start notices 

### LINKED ISSUE #18493: Quick Start: Rotating device can misalign notification of task completion
Expected behavior
Rotating the device when a notification is shown should not change the alignment of the notification.

Actual behavior
The text in the notification is no longer center aligned.

IMG_8468

Steps to reproduce the behavior
1. Rotate device so you're in landscape mode
2. From menu screen, select stats tour in Grow your audience section
3. Select (now indicated) Stats option
4. While notification is up, rotate device so it's in portrait mode
5. Note alignment of notification

Tested on iPhone XS, iOS 15.4.1, WPiOS 19.8

### LINKED ISSUE #18757: Quick Start: Notices sometimes have full width on large devices
### Expected behavior
Notices to always have 50% width on large devices.

### Actual behavior
Notices only have 50% width when the device gets rotated.

### Steps to reproduce the behavior

1. Test on a large device (13 Pro Max)
2. Enable quick start for existing sites
3. Put the device in landscape mode
4. Start notifications task
5. Notice that the notice fills the width of the whole screen
6. Rotate the device to portrait then back to landscape
7. Notice that the notice now correctly fills 50% of the screen

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #18493
Fixes #18757

## Description
- Fixes an issue where the notice was filing the whole screen width on large devices
- Fixes an issue where the notice would get misaligned after changing orientation.
    - The root cause was due to the `UIDevice.orientationDidChangeNotification` notification being posted before the tab bar has updated its height. And since we depend on the tab bar height to align the notice, this causes the misalignment.

### Notice Width

1. Test on a large device (13 Pro Max)
2. Enable quick start for existing sites
3. Put the device in landscape mode
4. Start notifications task
5. Make sure that the notice fills 50% of the whole screen
6. Rotate the device to portrait
7. Make sure that the notice fills 100% of the whole screen
8. Rotate again
9. Make sure that the notice fills 50% of the whole screen

### Notice Misalignment

1. Test on iPhone 13 Pro Max or XS
2. Enable quick start for existing sites
3. Start notifications task
4. Note the position of the notice
5. Keep changing the orientation
6. Make sure the distance between notice and tab bar is always the same

## Regression Notes
1. Potential unintended areas of impact
N/A
2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A
5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by momo-ozawa — COMMENTED** [review]
@hassaanelgarem 👋 
I'm getting a build error: 

```
❌  /usr/local/var/buildkite-agent/builds/builder/automattic/wordpress-ios/WordPress/Classes/ViewRelated/System/WPTabBarController.m:573:15: no visible @interface for 'WPTabBarController' declares the selector 'notifyOfTabBarHeightChangeIfNeeded'
```

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m [hunk 1]
```diff
@@ -558,11 +569,25 @@ - (void) hideReaderBadge:(NSNotification *)notification
 
 - (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
 {
-    if ([keyPath isEqualToString:WPApplicationIconBadgeNumberKeyPath]) {
+    if (object == self.tabBar && [keyPath isEqualToString:WPTabBarFrameKeyPath]) {
+        [self notifyOfTabBarHeightChangeIfNeeded];
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: There's a typo that's causing a build error 👀 

```suggestion
        [self notifyOfTabBarHeightChangedIfNeeded];
```

**Review by momo-ozawa — COMMENTED** [review]
If the initial screen is site menu and I rotate landscape -> portrait -> landscape, two unexpected things happen:
- The notice isn't shown any more
- The FAB is "stuck" in the adjusted position when notices are visible


https://user-images.githubusercontent.com/6711616/170685939-9180ad9d-0007-4d8c-9a73-d856ed60f63a.mp4

**Comment by hassaanelgarem** [comment]
@momo-ozawa 

> If the initial screen is site menu and I rotate landscape -> portrait -> landscape, two unexpected things happen:

That was caused by the stats appearing then disappearing. Fixed in bee31c39dd6e2c23e520ee0a6e2f68fc755fc021 👍

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/System/WPTabBarController.m]: Fixed in 2fe04939665f11d78e5a62aa89d711fe505c2d11 🙈

**Comment by mokagio** [comment]
@hassaanelgarem @momo-ozawa Notice I updated the base branch for this PR to `release/20.0`. The PR clearly looks like something valuable to have in 20.0, so I'd rather ship another beta just for it than have our users wait an additional four weeks to get this fix.

Feel free to revert to `trunk` if I misunderstood.

**Review by momo-ozawa — COMMENTED** [review]
@hassaanelgarem I'm seeing two new issues 👀 

If you don't find an immediate solution for this, what do you think of switching back to target `trunk`? AFAIK this issue has been present for a while now / it's not a regression we introduced recently. 

### Rotating to landscape when the initial screen is Home

The animation to switch to the split vc doesn't happen immediately -- you see a black screen where the detail vc should be. Then the primary pane rotates to the wrong angle. Finally, the screen switches to the intended split vc view.

https://user-images.githubusercontent.com/6711616/171132306-d5521ef6-51a9-4c36-a9ce-04bb76e10458.mp4

### Rotating to landscape when the initial screen is Menu

The segmented control is superimposed on top of the Next Steps section title before disappearing.

https://user-images.githubusercontent.com/6711616/171132331-34488241-9d5d-47d6-a8cf-de53acf1a07a.mp4

**Comment by hassaanelgarem** [comment]
@momo-ozawa 

> The animation to switch to the split vc doesn't happen immediately -- you see a black screen where the detail vc should be. Then the primary pane rotates to the wrong angle. Finally, the screen switches to the intended split vc view.

That's weird but I can't reproduce this at all. I've tested on 13 Pro Max iOS 15.4. What iOS version are you testing with?

> The segmented control is superimposed on top of the Next Steps section title before disappearing.

Nice catch! I'll look into that, but I might end up opening another PR for this.

> If you don't find an immediate solution for this, what do you think of switching back to target trunk? AFAIK this issue has been present for a while now / it's not a regression we introduced recently.

If these issues are already existent (The second one is existent on trunk), I'd prefer to ship the fixes we have now and address the new issues separately in another PR(s).

**Comment by momo-ozawa** [comment]
@hassaanelgarem 

> That's weird but I can't reproduce this at all. I've tested on 13 Pro Max iOS 15.4. What iOS version are you testing with?

I'm testing on a 13 Pro Max iOS 15.4 simulator. I'm using Xcode 13.3.0. Which Xcode version are you using?

> If these issues are already existent (The second one is existent on trunk), I'd prefer to ship the fixes we have now and address the new issues separately in another PR(s).

Sure, sounds good to me. I just tested the 19.9 tag and I was able to reproduce this behavior, which indicates that neither of the issues are regressions. So should be safe to address these in different PRs.

One last thing -- let's make sure to add an [internal] note about this 👍

**Comment by hassaanelgarem** [comment]
@momo-ozawa 

> Which Xcode version are you using?

13.3.0 as well 🤔 

> So should be safe to address these in different PRs.

Awesome!

> let's make sure to add an [internal] note about this

Sure! Done in 028e2bc0178b224775b798f123a9cc7f2e2d66f2 👍

**Review by momo-ozawa — APPROVED** [review]
LGTM! 

Tested the steps again and can confirm that [this issue](https://github.com/wordpress-mobile/WordPress-iOS/pull/18758#pullrequestreview-987349436) is fixed!

**Comment by mokagio** [comment]
@hassaanelgarem Unless there's an urgent need to ship this in a beta, I'd wait until another PR lands on the release branch. I know there's one coming with a fix, but I don't think it has been opened yet.

Let me know if that's okay. If it isn't, I'll ship a beta with this ASAP.

cc @tiagomar

**Comment by hassaanelgarem** [comment]
@mokagio I agree! This isn't urgent indeed 👍

**Comment by mokagio** [comment]
@hassaanelgarem  this has been bundled as part of [20.0 beta 1 (20.0.0.1)](https://github.com/wordpress-mobile/WordPress-iOS/pull/18825).

Thanks for your work 🙌
