### PR TITLE
Alert for deleting trashed posts

### LINKED ISSUE #6415: No alert when deleting trashed post
### Expected behavior

User is alerted when he/she deletes trashed posts in Calypso.

screen shot 2017-01-13 at 5 27 36 pm

### Actual behavior

The trashed post is immediately deleted.

### Steps to reproduce the behavior

screen shot 2017-01-13 at 5 40 07 pm

Tap on the delete button and the post is immediately deleted with no alert.

### PR DESCRIPTION
**Pull request by ablyx**
Fixes #6415 

To test:
For a post under Trashed, tap on delete.
Tap OK: The post should be deleted as usual
Tap Cancel: Alert is dismissed

Needs review: @aerych I am new to this, please let me know if I made a mistake!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 1]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
     }
 
     func cell(_ cell: UITableViewCell, handleTrashPost post: AbstractPost) {
-        deletePost(post)
+        if (post.status == "trash") {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: We have some constants for post statuses which you can use here (in `AbstractPost.m`). You can use `PostStatusTrash` instead of `"trash"`.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 2]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+            weak var weakSelf = self
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Instead of this, you can declare `weakSelf` as part of your delete action later on, like so:

`{ [weak self] action in`

Then in your action block, you can do `self?.deletePost(post)`.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 3]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+
+            let cancelText = NSLocalizedString("Cancel", comment: "Cancels an Action")
+            let deleteText = NSLocalizedString("OK", comment: "Deletes post permanently")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Ideally the title of a button like this should be a verb indicating what the button will do. So in this case, I'd go for "Delete" or "Delete Permanently".

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 4]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+            let messageText = NSLocalizedString("Delete Permanently", comment: "Deletes post permanently")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: I'd perhaps match the text used by Calypso here, to make it a bit more informative: "Delete this post permanently?"

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 5]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+            let alertController = UIAlertController(title: nil, message: messageText, preferredStyle: .alert)
+
+            alertController.addCancelActionWithTitle(cancelText)
+            alertController.addDefaultActionWithTitle(deleteText) { action in
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: For an action such as delete, you should use `addDestructiveActionWithTitle` instead of `defaultAction`. A destructive action will color the button red, to warn the user that content will be deleted / altered by this action.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 6]
```diff
@@ -494,7 +494,23 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
+                weakSelf!.deletePost(post)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: See my above comment about `weakSelf` :)

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 4 above)
Comment (ablyx) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Thanks for your comments! Really appreciate it. I think the other changes should be quite manageable, but how do I generate the Localizeable.strings for the other languages?

Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Don't worry about the Localizable.strings – as long as you use `NSLocalizedString` in your code, we'll take care of the rest :) (in short: scripts and translators!)

**Comment by ablyx** [comment]
@frosty I've made the necessary changes, can you review it?

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 7]
```diff
@@ -494,7 +494,22 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
     }
 
     func cell(_ cell: UITableViewCell, handleTrashPost post: AbstractPost) {
-        deletePost(post)
+        if (post.status == PostStatusTrash) {
+
+            let cancelText = NSLocalizedString("Cancel", comment: "Cancels an Action")
+            let deleteText = NSLocalizedString("Delete", comment: "Deletes post permanently")
+            let messageText = NSLocalizedString("Delete Trashed Post", comment: "Deletes post permanently")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Sorry, one last amend – could you change the key here from "Delete Trashed Post" to "Delete this post permanently?" so it matches the actual text that's displayed? Thank you!

**Comment by frosty** [comment]
@ablyx Thank you! Your changes look great. I just have one last minor tweak for you and then I think we're good to go. Thanks so much for adding this!

**Comment by ablyx** [comment]
@frosty No problem. Thanks so much for your kind words and guidance!

**Comment by frosty** [comment]
Awesome! I'm going to merge this in now. Thanks again, @ablyx! :tada:
