### PR TITLE
Ensure non-null Blog url before search

### LINKED ISSUE #13742: NSInvalidArgumentException: *** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument
https://sentry.io/share/issue/111f50c5f0264e6d9c587d3d4081cc0c/

```
NSInvalidArgumentException: *** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument
  File "Classes/Models/Blog.m", line 148, in -[Blog displayURL]
  File "NewBlogDetailHeaderView.swift", line 44, in NewBlogDetailHeaderView.blog.didset
  File "<compiler-generated>", in NewBlogDetailHeaderView.blog.didset
  File "NewBlogDetailHeaderView.swift", in NewBlogDetailHeaderView.blog.setter
  File "<compiler-generated>", in NewBlogDetailHeaderView.blog.setter
...
(29 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by bjtitus**
Fixes #13742

To test:
- Ensure that the display URL is shown in the list of Blogs and Blog Details screens.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by bjtitus** [comment]
I tried for a while to reproduce this, but was unable get the property value to be nil without manipulating the data myself. If you have any ideas on how to get the URL property to be `nil`, please let me know.

I tried:
* Deleting the blog from the app
* Deleting the blog from the web while still on the blog in the app and attempting to refresh various pages

I'm guessing it's either on deletion or creation of the blog object, or some faulted data somewhere.

File: WordPress/Classes/Models/Blog.m [hunk 1]
```diff
@@ -147,6 +147,10 @@ - (NSString *)icon
 // Used as a key to store passwords, if you change the algorithm, logins will break
 - (NSString *)displayURL
 {
+    if (self.url == nil) {
+        return nil;
```
Comment (ScoutHarris) [inline WordPress/Classes/Models/Blog.m]: I'm wondering if adding a `DDLogInfo` message here to log what went wrong might be helpful?

Comment (bjtitus) [reply WordPress/Classes/Models/Blog.m:152]: Good idea! Just added.
