### PR TITLE
Fix quick start not terminating on hide this issue

### LINKED ISSUE #21603: Dashboard: Quick Start on "hide this" dismiss next steps and target touch points
### Expected behavior
When you tap on the "Hide This" option within the Quick Start Card, the associated snack bars displaying quick start next steps and touch target points are still visible on screen.

### Actual behavior
When you tap on the "Hide This" option within the Quick Start Card, it will dismiss any associated snack bars displaying quick start next steps and hide the touch target points.

### Steps to reproduce the behavior
- Login to the app
- Select "Not sure, show me around" option
- Select the check your site stats option
- Tap the Get to know the app "hide this" more menu option
- Note the associated snack bars displaying quick start next steps and touch target points are still visible on screen.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Android 12, iOS 16.6, JP 23.3.0.0

### PR DESCRIPTION
**Pull request by kean**
Fixes #21603 and removes double-confirmation on "Hide this" ([before.mp4](https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/45e0b2e5-3770-4049-8719-cb72746ba75e), [after.mp4](https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/9e402cca-7ea1-43aa-8e60-1adf65f3e352)).

## To test:

> [!IMPORTANT]
> Make sure to test on both iPad and iPhone

### Test Case 1

- Install the current production version
- Start Quick Start
- Tap “Hide This” to hide Quick Start
- Upgrade the app to the version from the branch
- Verify that Quick Start cell is still not visible

### Test Case 2

- Create a new site and start one of the Quick Start tours (or enable it from the debug menu)
- Open “Personalize Home Tab” screen
- Verify that the Quick Start tour card is not present on the list

### Test Case 3

- Complete the steps from the [defect](https://github.com/wordpress-mobile/WordPress-iOS/issues/21603)

## Regression Notes
1. Potential unintended areas of impact: Personalization screen and Quick Start tours
2. What I did to test those areas of impact (or what existing automated tests I relies on): manual
3. What automated tests I added (or what prevented me from doing so): yes

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/Categories/UIViewController+RemoveQuickStart.m [hunk 1]
```diff
@@ -5,32 +5,22 @@
...
-    NSString *confirmationTitle = NSLocalizedString(@"Remove", @"Title for button that will confirm removing the next steps/quick start menus.");
     NSString *cancelTitle = NSLocalizedString(@"Cancel", @"Cancel button");
 
-    UIAlertController *removeConfirmation = [UIAlertController alertControllerWithTitle:removeTitle message:removeMessage preferredStyle:UIAlertControllerStyleAlert];
-    [removeConfirmation addCancelActionWithTitle:cancelTitle handler:^(UIAlertAction * _Nonnull __unused action) {
-        [WPAnalytics trackQuickStartStat:WPAnalyticsStatQuickStartRemoveDialogButtonCancelTapped blog: blog];
-        [NoticesDispatch unlock];
-    }];
-    [removeConfirmation addDefaultActionWithTitle:confirmationTitle handler:^(UIAlertAction * _Nonnull __unused action) {
+    UIAlertControllerStyle alertStyle = ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad) ? UIAlertControllerStyleAlert : UIAlertControllerStyleActionSheet;
```
Comment (kean) [inline WordPress/Classes/Categories/UIViewController+RemoveQuickStart.m:15]: The sourceRect logic was broken and wasn't working on iPad properly, so I decided to simply show it as an alert, which is a common thing to do for a confirmation alert.

**Review by momo-ozawa — APPROVED** [review]
Tested on iPhone and iPad, works as described!
