### PR TITLE
Only notify group observers when the media group is updated

### LINKED ISSUE #19266: Albums list keeps blinking
This issue is related to the new `ContainerContextFactory` which is a in-development feature and is turned off in https://github.com/wordpress-mobile/WordPress-iOS/pull/19265.

### Expected behavior
Albums list doesn't blink.

### Actual behavior
Albums list keeps blinking.

### Steps to reproduce the behavior
1. Use `ContainerContextFactory` in [`ContextManager.m`](https://github.com/wordpress-mobile/WordPress-iOS/blob/438ae1303e3095a71ea3c2179194c11fcd424313/WordPress/Classes/Utility/ContextManager.m#L53).
2. Build and run the app from Xcode.
3. Go to a post's "Post Settings" page.
4. Tap "Set Featured Image".
5. Observe the UI of the presented "Albums" list.

##### Tested on iPhone and iPad, iOS 15, WPiOS commit 438ae130

Note: `EditorGutenbergTests.testAddRemoveFeaturedImage` fails due to this issue.

### PR DESCRIPTION
**Pull request by crazytonyli**
Fix #19266.

## Changes

See https://github.com/wordpress-mobile/WordPress-iOS/pull/19274 for the root cause of #19266.

```mermaid
stateDiagram-v2
  [*] --> WPMediaGroupPickerViewController : 1. User taps "Set Featured Image"
  WPMediaGroupPickerViewController --> WPMediaGroupPickerViewController.loadData
  WPMediaGroupPickerViewController.loadData --> MediaCoordinator.syncMedia : 2. Fetch media library
  MediaCoordinator.syncMedia --> MediaLibraryPickerDataSource.fetchedResultController : 3. Media in database is updated, FRC delegate is notified
  MediaLibraryPickerDataSource.fetchedResultController --> WPMediaGroupPickerViewController.loadData : 4. Data changed, please reload
```

This PR breaks the reloading loop shown in the above diagram at step 4. Previously, all updates to the media library would cause a reload. This PR checks if the media group(which is basically the most recent media in the media library) has changed and calls the group observers only when the media group is changed which is the designed behaviour of "group observers".

## Test Instructions

1. Change `ContextManager` to [use `ContainerContextFactory`](https://github.com/wordpress-mobile/WordPress-iOS/blob/7f44120b43ca36401791036912e834ade49f79c9/WordPress/Classes/Utility/ContextManager.m#L53)
2. Make sure #19266 is not reproducible.
3. The added unit test should pass.

## Regression Notes
1. Potential unintended areas of impact
All places that let user to pick an image from the site's WordPress media library.

4. What I did to test those areas of impact (or what existing automated tests I relied on)
Verified #19266 is fixed.

5. What automated tests I added (or what prevented me from doing so)
Added a unit test

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m [hunk 1]
```diff
@@ -543,27 +557,38 @@ - (NSString *)name
...
+- (void)refreshImageMedia
 {
     NSString *entityName = NSStringFromClass([Media class]);
     NSFetchRequest *request = [NSFetchRequest fetchRequestWithEntityName:entityName];
     request.predicate = [MediaLibraryPickerDataSource predicateForFilter:self.filter blog:self.blog];
     NSSortDescriptor *sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending:NO];
     request.sortDescriptors = @[sortDescriptor];
+    request.fetchLimit = 1;
     NSError *error;
     NSArray *mediaAssets = [[[ContextManager sharedInstance] mainContext] executeFetchRequest:request error:&error];
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m:569]: Sad that we swallow the error, but out of scope for this PR.

I wonder whether it's worth tracking an improvement task for this, or just wait till we'll get time to convert to Swift...

File: WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m [hunk 2]
```diff
@@ -543,27 +557,38 @@ - (NSString *)name
...
+        [self refreshImageMedia];
+    }
+
+    if (self.imageMediaID != nil) {
+        media = [[[ContextManager sharedInstance] mainContext] existingObjectWithID:self.imageMediaID error:nil];
+    }
+
+    if (media == nil) {
         UIImage *placeholderImage = [UIImage imageNamed:@"WordPress-share"];
         completionHandler(placeholderImage, nil);
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m:588]: The previous version had a nullability check before calling completion handler. Would it be useful here, too?

```suggestion
        if (completionHandler != nil) {
            completionHandler(placeholderImage, nil);
        }
```

File: WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift [hunk 3]
```diff
@@ -73,6 +74,44 @@ class MediaLibraryPickerDataSourceTests: CoreDataTestCase {
...
+            changes += 1
+        }
+
+        // Adding a video does not change the album cover.
+        let video = MediaBuilder(context).build()
+        video.remoteStatus = .sync
+        video.blog = self.blog
+        video.mediaType = .video
+        contextManager.saveContextAndWait(context)
+        expect(changes).toEventually(equal(0))
```
Comment (mokagio) [inline WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift]: **I love how you always add tests for your changes 👏 💪 🎖️**

I assume the code uses `toEventually` here because the update (via `notifyGroupObservers`) to changes happens async _even though_ the call uses `saveContextAndWait`, right?

If that's the case, then there might be a chance of false positive here. Since `0` is the default value, `toEventually(equal(0))` will pass at the first iteration of the polling check, without giving the test time to wait for the observer to be called.

This can be verified by adding a delay in the test code:

image

Nimble offers two alternative async expectations methods to use in this scenario: `toNever` and `toAlways`.

**`toNever`**

image

**`toAlways`**
image

I prefer how the `toNever` option reads in this situation, but the result is the same.


```suggestion
        expect(changes).toNever(beGreaterThan(0))
```

File: WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift [hunk 4]
```diff
@@ -73,6 +74,44 @@ class MediaLibraryPickerDataSourceTests: CoreDataTestCase {
...
+        expect(changes).toEventually(equal(1))
+
+        // Added an old image does not change the album cover.
+        let oldImage = MediaBuilder(context).build()
+        oldImage.remoteStatus = .sync
+        oldImage.blog = self.blog
+        oldImage.mediaType = .image
+        oldImage.creationDate = Date().advanced(by: -60)
+        contextManager.saveContextAndWait(context)
+        expect(changes).toEventually(equal(1))
```
Comment (mokagio) [inline WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift]: Same observation about the possibility of a false positive. In this case, I think this should work:

```suggestion
        expect(changes).toNever(beGreaterThan(1))
```

File: WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift [hunk 5]
```diff
@@ -73,6 +74,44 @@ class MediaLibraryPickerDataSourceTests: CoreDataTestCase {
...
+        // Adding a newly created image changes the album cover.
+        let newImage = MediaBuilder(context).build()
+        newImage.remoteStatus = .sync
+        newImage.blog = self.blog
+        newImage.mediaType = .image
+        newImage.creationDate = Date()
+        contextManager.saveContextAndWait(context)
+        expect(changes).toEventually(equal(1))
+
+        // Added an old image does not change the album cover.
```
Comment (mokagio) [inline WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift]:
```suggestion
        // Adding an old image does not change the album cover.
```

**Review by mokagio — APPROVED** [review]
_I haven't tested on device/Simulator._

This looks good code wise. I noticed auto-merge is not enabled, so approving to unblock merging immediately or after applying my testing suggestion if they make sense.

File: WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m (hunk 2 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m:588]: I noticed that, I also noticed that the `completionHandler` is called twice when there is no media assets–this function doesn't return after the first `completionHandler` call. The first call does a nil-check, but the second doesn't. This means the `completionHandler` shouldn't be nil in reality.

I think, given this function is used to get the image of the media asset, the call site is supposed to pass an `completionHandler`, otherwise what would they call this function for? This is the main reason why I didn't do a nil-check here—passing a nil `completionHandler` is a programming error.

File: WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift]: Oh nice, TIL. I'll commit your code, thanks!

File: WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m (hunk 2 above)
Comment (mokagio) [reply WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m:588]: 👌

**Comment by mokagio** [comment]
Reiterating my previous [approval](https://github.com/wordpress-mobile/WordPress-iOS/pull/19280#pullrequestreview-1103487512). Merge at your earliest convenience 😄
