### PR TITLE
Fixes for background on featured image in post settings

### LINKED ISSUE #12597: [Dark Mode] Post Settings featured image has  white background
After setting a featured image, tapping on the featured image (e.g. to remove it) shows a white background

### PR DESCRIPTION
**Pull request by kduncanwelke**
Made dark mode compatible.

Fixes #12597 

To test: Switch device to dark mode. Select a blog post, edit it, go to post settings, then view a featured image (once it has been set). The background color should match the device's light/dark mode, and if light/dark is not available on the device, white will be shown by default.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by aerych** [comment]
@frosty since this is dark mode related, could you help out or help find the best reviewer?

File: WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m [hunk 1]
```diff
@@ -27,7 +27,13 @@ - (void)viewDidLoad
     [super viewDidLoad];
 
     self.title = NSLocalizedString(@"Featured Image", @"Title for the Featured Image view");
-    self.view.backgroundColor = [UIColor whiteColor];
+    
+    if (@available(iOS 13, *)) {
+        self.view.backgroundColor = [UIColor systemBackgroundColor];
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m]: Rather than doing the iOS 13 check here, you can just set the background color to `[UIColor basicBackground]`. We define it ourselves in UIColor+MurielColors, and it does this same switch - white in iOS 12, system background in iOS 13 :)

File: WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m [hunk 2]
```diff
@@ -94,7 +100,11 @@ - (void)hideBars:(BOOL)hide animated:(BOOL)animated
         if (hide) {
             self.view.backgroundColor = [UIColor blackColor];
         } else {
-            self.view.backgroundColor = [UIColor whiteColor];
+            if (@available(iOS 13, *)) {
+                self.view.backgroundColor = [UIColor systemBackgroundColor];
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m]: As above, we can use `basicBackground` here.

Comment (kduncanwelke) [reply WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m]: Ah, right, thank you! I will update it to use basicBackground, and eliminate those other accidental changes.

File: WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m (hunk 1 above)
Comment (kduncanwelke) [reply WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m]: Fixed this one with an update to using the muriel colors too.

File: WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m (hunk 2 above)
Comment (frosty) [reply WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m]: Great, thank you – let me know when it's ready for another look!

**Comment by kduncanwelke** [comment]
It’s ready to go now. :)
