### PR TITLE
Fix Notices showing anywhere but the bottom on iPad devices

### LINKED ISSUE #11325: iPad: Notices are not shown after rotating the device
### Expected behavior

Notices are shown on all orientations. 

### Actual behavior

Notices are only shown on the orientation that you start the app with. 
 
### Steps to reproduce the behavior

1. iPad only: Start the app on landscape
2. Go to Site → Pages
3. Turn off the internet connection
4. The offline error Notice will be shown. 
5. Rotate the device.
6. Pull to refresh the page.
7. The offline error Notice is not shown.

The same behavior happens when starting the app on portrait and going to landscape. Also, there are other weird behavior happening like the Notice being shown in the middle of the screen.

##### Tested on [device], iOS [version], WPiOS [version]

iPad simulator. iOS 12.1.

### PR DESCRIPTION
**Pull request by shiki**
Fixes #11325. 

The bug seems to consistently happen when you launch the app, show a `Notice`, and then rotate the device.

| Starting Orientation | After Rotating |
|--------|-------|
  |      develop-before-rotate | develop-after-rotate |

## The Problem

Based on my tests, the `UntouchableViewController.view` never gets automatically resized when the device is rotated. The first orientation that the app is launched in will determine the size of the `view`.

This only happens on iPad devices. For iPhone, the `view` seems to be rotated correctly. 

## The Solution

Based on @nheagy's advice, this is a regression. We hunted for the cause and found that this started happening in 4cac38f8. It looks like the auto-resizing gets disabled when the `window` is not visible after it is initialized. This PR restores that. It will still be hidden but on the next UI loop. 

The `MaskView` got affected with the fix so the `MaskView` `frame` update had to be fixed as well.

## Testing

To reproduce the bug:

1. iPad only: Start the app on landscape
2. Go to Site → Pages
3. Turn off the internet connection
4. The offline error Notice will be shown.
5. Rotate the device.
6. Pull to refresh the page.
7. The offline error Notice is not shown.

Please also play around with showing the Notice while on portrait.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift [hunk 1]
```diff
@@ -70,6 +70,14 @@ class NoticePresenter: NSObject {
 
         super.init()
 
+        // Keep the window visible but hide it on the next run loop. If we hide it immediately,
+        // the window is not automatically resized when the device is rotated. This issue
+        // only happens on iPad devices.
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift]: Can we change this comment to mention that the problem appears to be only in the simulator?

That way we can revisit it in the future if this code gets refactored.

File: WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift [hunk 2]
```diff
@@ -434,7 +442,15 @@ private extension NoticePresenter {
         }
 
         @objc func updateFrame(notification: Notification) {
-            frame = MaskView.calculateFrame(parent: parentView, untouchableVC: untouchableVC)
+            // Update the `frame` on the next run loop. When this Notification event handler is
+            // called, the `self.parentView` still has the frame from the previous orientation.
+            // Running this routine after the current run loop ensures we have the correct frame.
+            DispatchQueue.main.async { [weak self] in
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift]: This is just a suggestion but, what if we wrapped the `DispatchQueue.main.async` call in a method with a name that explained what was going on, such as
```swift
waitALoopSoRotationWorksOnSimulator() {
    self.frame = MaskView.calculateFrame(parent: self.parentView, untouchableVC: self.untouchableVC)
}
```

File: WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift (hunk 1 above)
Comment (shiki) [reply WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift]: Agreed 👍

File: WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift (hunk 2 above)
Comment (shiki) [reply WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift]: I'm not sure about this. 😬I think it's already well contained in this method. Perhaps I can add a comment in line 73 to re-evaluate this method if the iPad simulator issue ever gets fixed.

Comment (nheagy) [reply WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift]: What made me think of it is that we're calling `DispatchQueue.main.async` twice, with the only hint that they're related being the comments. I like good comments, but I fear that they're fragile, ya know?

Anyway, still up to you 👍

**Comment by shiki** [comment]
@nheagy Thank you for the thorough testing and review.

I updated just the comment for now. 🙂 Please let me know if the comment is good enough.
