### PR TITLE
Comments: Fix comment moderation bar padding in multitasking context

### LINKED ISSUE #18743: Comment moderation bar displayed incorrectly when multitasking
### Expected behavior
The moderation bar should be displayed correctly.

### Actual behavior
The moderation bar buttons appear to shrink when displayed in a multitasking context.

comments_moderation_bar

### Steps to reproduce the behavior

- Open the app on iPad.
- Activate multitasking.
- In a site that you own, navigate to Notifications > any comment notification.
- Observe that the moderation bar buttons appear shrunk.

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #18743

This fixes a layout bug affecting iPad in multitasking context. The bug affected both Split View and Slide Over mode, but **only in landscape orientation**. Here are some screenshots:

### Landscape

• | Before | After
--|--|--
Full | before_landscape | after_landscape
Split View ⚠️  | before_multi_landscape | after_multi_landscape
Slide Over ⚠️ | before_floating_landscape | after_floating_landscape

For completeness, here are screenshots for the portrait orientation — to ensure that they are unaffected by this change:

### Portrait

• | Before | After
--|--|--
Full | before_portrait | after_portrait
Split View | before_multi_portrait | after_multi_portrait
Slide Over | before_floating_portrait | after_floating_portrait

## To test:

- Run the app on iPad in landscape orientation.
- Open WordPress-iOS in Split View context.
- Navigate to any comment.
- 🔍  Verify that the moderation bar is displayed correctly.
- Open the WordPress-iOS in Slide Over context.
- 🔍  Verify that the moderation bar is displayed correctly.
- Also ensure that the moderation bar behavior in portrait orientation works well.

Pro Tip: Here's a [link](https://stackoverflow.com/a/71509093/1266558) that shows you how to multitask on iPad! 😆 

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
The changes were visual.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by alpavanoglu** [comment]
Hey @dvdchr I have tested it and I still see the issue in landscape mode when I go into split view or slide over. The issue goes away however when I go into Portrait Mode and then back to Landscape mode.

**Comment by dvdchr** [comment]
Thanks @alpavanoglu ! In https://github.com/wordpress-mobile/WordPress-iOS/pull/18764/commits/09f8d478b883ddee9a48707a0de5f25b1638debb, I've added some additional logic that ensures that the iPad padding value is only applied when the app is in full screen mode. One small issue that I noticed is that the padding is not updated properly when switching from Split View 75% to full screen. Here's a comparison:

Normal Landscape | After transitioning from Split View 75%
--|--
18764_normal | 18764_after

After the transition, the moderation bar is still using the compact padding value. While the buttons look stretched, the moderation bar is still usable compared to before; and this problem is gone after rotating to portrait and back to landscape.

This issue happens because Split View 25% and 50% both have `compact` horizontal size class, but Split View 75%'s size class is actually `regular`. The moderation bar's padding value is recalculated when a trait collection change happens, but the problem is Split View 75% and Landscape both have `regular` horizontal size class — and this results in the trait collection change not being triggered.

One way to solve this is to override `viewWillTransitionToSize` in the view controller side, and pass this information from the view controller > table view cell > the moderation bar view to have it recalculate properly, or fire an `NSNotification` whenever there `viewWillTransitionToSize` is called. However, I don't think it's worth it to pursue this any further especially as we have pc5zdG-xc-p2#comment-244 that will remove the moderation bar from comments. 😄 

Anywho, ready for your second round of review!

File: WordPress/Classes/ViewRelated/Comments/CommentModerationBar.swift [hunk 1]
```diff
@@ -67,6 +67,14 @@ class CommentModerationBar: UIView {
         NotificationCenter.default.removeObserver(self)
     }
 
+    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
+        // readjust stack view width when horizontal size class changes.
```
Comment (alpavanoglu) [inline WordPress/Classes/ViewRelated/Comments/CommentModerationBar.swift:73]: Shouldn't we calling the super here?
`super.traitCollectionDidChange(previousTrailtCollection)`

**Review by alpavanoglu — APPROVED** [review]
LGTM

File: WordPress/Classes/ViewRelated/Comments/CommentModerationBar.swift (hunk 1 above)
Comment (dvdchr) [reply WordPress/Classes/ViewRelated/Comments/CommentModerationBar.swift:73]: 🤦🏼  Good call! This should be addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/18764/commits/b8c3f64ed261e2149e26c7b48c4e5d492aa8920e, and I'm turning on auto merge. Thanks @alpavanoglu ! 🙂
