### PR TITLE
Fixes restoration issues in tab bar

### LINKED ISSUE #3723: Last open tab is not restored after termination
If you terminate the app and reopen it, it always opens up with the first tab (My Site) instead of the last open tab.

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #3723. This PR adds the restoration to `WPTabBarController` and it now opens up with the last selected tab. I've also added restoration to `MeViewController`, `SettingsViewController` and `SupportViewController`. There are a lot of pages that currently doesn't support restoration, we probably should add them in the future.

I didn't know this before, so I am sharing here just in case it's not common knowledge: "Be aware that the system automatically deletes an app’s preserved state when the user force quits the app." http://stackoverflow.com/questions/12718341/ios-6-saving-restoring-app-state-feature

@sendhil Can I bother you with a review? Thanks!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m [hunk 1]
```diff
@@ -119,6 +133,21 @@ - (void)dealloc
...
+
+- (void)encodeRestorableStateWithCoder:(NSCoder *)coder
+{
+    [coder encodeInteger:self.selectedIndex forKey:WPTabBarSelectedIndexKey];
+    [super encodeRestorableStateWithCoder:coder];
+}
+
+- (void)decodeRestorableStateWithCoder:(NSCoder *)coder
+{
+    // Set last selected tab bar item
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: Remove this comment - the line is self explanatory.

Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: ie: if more info needs to be added it should be placed in the documentation comments for property `selectedIndex`.

**Comment by diegoreymendez** [comment]
@oguzkocer - As per sendhil's [post on lean PRs](https://coreappso2.wordpress.com/2015/05/13/lean-mean-pull-requests/) please remember that all PRs should provide testing steps of some sort (even when the changes seem basic).

The reason this is a good thing is that it will allow us to speed up our reviews and spend less time figuring out the details.

File: WordPress/Classes/ViewRelated/Me/MeViewController.m [hunk 2]
```diff
@@ -44,6 +45,11 @@ @interface MeViewController () <UITableViewDataSource, UITableViewDelegate, UIAc
 
 @implementation MeViewController
 
++ (UIViewController *)viewControllerWithRestorationIdentifierPath:(NSArray *)identifierComponents coder:(NSCoder *)coder
+{
+    return [[self alloc] init];
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Me/MeViewController.m]: Is there any testing path causing this line to be executed?  I placed a breakpoint here and never got it to execute.

File: WordPress/Classes/ViewRelated/Settings/SettingsViewController.m [hunk 3]
```diff
@@ -59,11 +61,28 @@ @interface SettingsViewController ()
 
 @implementation SettingsViewController
 
++ (UIViewController *)viewControllerWithRestorationIdentifierPath:(NSArray *)identifierComponents coder:(NSCoder *)coder
+{
+    return [[self alloc] init];
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Settings/SettingsViewController.m]: Same as above I couldn't get this to trigger.

**Comment by diegoreymendez** [comment]
@oguzkocer - So to recap: I wasn't able to restore the state for the VCs in this PR.  My steps where:

1. Launch the app.
2. Open up "Me" or "Me / Support" or "Me / Settings"
3. Double tap home
4. Close the app
5. Reopen the app

Expected results: the state would be restored.
Current results: the state wasn't restored.

**The next steps would be:**

1. Provide the testing instructions in the PR details.
2. Make sure the state is being restored for the case I detailed above.

Thank you!

**Comment by diegoreymendez** [comment]
@oguzkocer - Also, the code in [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/issue/3723-restore-last-open-tab/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L173) should be fixed since state restoration was already working for those VCs (up to the post editor) but isn't working anymore.

**Comment by oguzkocer** [comment]
Thanks for the review @diegoreymendez! Here are a few notes on your comments:

* I have removed the unnecessary comment.
* I have included the [stackoverflow post](http://stackoverflow.com/questions/12718341/ios-6-saving-restoring-app-state-feature) in my original post for the testing instructions but it probably was not clear enough. I'll make sure to add them in the original post in the future.
* Here is how you can test the restoration for both Me & Settings page:

1. Run the app using simulator
2. Navigate to settings page
3. Press Cmd + Shift + H to go to the home page
4. Switch to Xcode and stop the app (don't close the app from the simulator)
5. Put a breakpoint to the Me & Settings view controller's `+ (UIViewController *)viewControllerWithRestorationIdentifierPath:(NSArray *)identifierComponents coder:(NSCoder *)coder` method
6. Run the app again

**Result:** You should get 2 breaks in the breakpoints you have set, and once you continue those, you should see the Settings page open up instead of Me.

AFAIK there is no way to test restoration with just the device. If you know any, please let me know :)

> Also, the code in [this line](https://github.com/wordpress-mobile/WordPress-iOS/blob/issue/3723-restore-last-open-tab/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L173) should be fixed since state restoration was already working for those VCs (up to the post editor) but isn't working anymore.

I am not sure I follow the issue you mentioned above. Could you explain it a little bit more? If you can give some testing instructions for me to run before & after the changes to see the difference that'd be great.

Thank you!

**Comment by diegoreymendez** [comment]
It's ok.  For some weird reason I remember testing state restoration differently - but only your directions seem to be working now.

Let's :shipit: so we can test this on release.

**Comment by oguzkocer** [comment]
Sure thing. Thanks!
