### PR TITLE
3D Touch Shortcuts: Fix stats shortcut for new nav appearance feature

### LINKED ISSUE #16225: Shortcuts: Stats Shortcut doesn't open the Stats screen
### Expected behavior
Tapping on the Stats shortcut should open the up the Stats screen

### Actual behavior
Tapping on the Stats shortcut opens up My Site (Blog Details VC) instead of the Stats screen

https://user-images.githubusercontent.com/6711616/113536205-7a464200-9610-11eb-8bcb-5a868c850d4b.mov

### Notes
This bug was introduced in 17.0. 
16.9 works as expected -- tapping on the Stats shortcut opens up the Stats screen.

### Steps to reproduce the behavior
1. Install WP Internal 17.0.0.202210401
2. 3D touch on WP Internal app icon
3. Tap on the Stats shortcut
4. 👀 Notice that we land on My Site (Blog Details VC) instead of the Stats screen

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #16225 

This PR fixes a bug where the stats shortcut was opening the My Site screen instead of the Stats screen.

## How to test:
1. Long press on the WP app icon to bring up shortcuts
2. Tap on the Stats shortcut
3. ✅ The Stats screen should be displayed

https://user-images.githubusercontent.com/6711616/113539987-05780580-961a-11eb-89ae-12bc5f812807.mov

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested for both newNavAppearance enabled and disabled, made sure that the stats shortcut opens up the stats screen as expected

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift [hunk 1]
```diff
@@ -131,9 +131,15 @@ class MySitesCoordinator: NSObject {
     func showBlogDetails(for blog: Blog, then subsection: BlogDetailsSubsection) {
         showBlogDetails(for: blog)
 
-        if let blogDetailsViewController = navigationController.topViewController as? BlogDetailsViewController {
-            blogDetailsViewController.showDetailView(for: subsection)
+        let blogDetailsViewController: BlogDetailsViewController?
+
+        if Feature.enabled(.newNavBarAppearance) {
+            blogDetailsViewController = navigationController.topViewController?.children.first as? BlogDetailsViewController
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift]: I think it might be good if we add an equivalent `showBlogDetails(for blog: Blog, then subsection: BlogDetailsSubsection)` method to `MySiteViewController`, and then we can do something like 

```
if let mySiteViewController = navigationController.topViewController as? MySiteViewController {
    mySiteViewController.showBlogDetails(for: blog, then: subsection)
}
```

This method can then tell its blog details view controller to show the correct detail view. This would mean that the MySitesCoordinator isn't relying on the MySiteViewController being structured in a particular way, with blog details as its first child. What do you think?

**Review by frosty — COMMENTED** [review]
Thanks for fixing this! I've just left a comment about pushing some of the logic down tho the MySiteViewController.

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift (hunk 1 above)
Comment (momo-ozawa) [reply WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift]: Fixed in 289d017!

File: WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift [hunk 2]
```diff
@@ -220,6 +220,20 @@ class MySiteViewController: UIViewController, NoResultsViewHost {
...
+    /// - Parameters:
+    ///         - blog: The blog to show the details of.
+    ///         - subsection: The specific subsection to show.
+    ///
+    func showBlogDetailsSubsection(_ subsection: BlogDetailsSubsection) {
+        guard let blogDetailsViewController = blogDetailsViewController else {
+            return
+        }
+
+        blogDetailsViewController.showDetailView(for: subsection)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift]: We could probably remove the guard here and just use optional chaining – `blogDetailsViewController?.showDetailView(for: subsection)`

File: WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift [hunk 3]
```diff
@@ -131,15 +131,15 @@ class MySitesCoordinator: NSObject {
     func showBlogDetails(for blog: Blog, then subsection: BlogDetailsSubsection) {
         showBlogDetails(for: blog)
 
-        let blogDetailsViewController: BlogDetailsViewController?
-
         if Feature.enabled(.newNavBarAppearance) {
-            blogDetailsViewController = navigationController.topViewController?.children.first as? BlogDetailsViewController
+            if let mySiteViewController = navigationController.topViewController as? MySiteViewController {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift]: I think we could combine these ifs so we don't have the nesting – something like:

```
if Feature.enabled(.newNavBarAppearance),
    let mySiteViewController = navigationController.topViewController as? MySiteViewController {
    mySiteViewController.showBlogDetailsSubsection(subsection)
} else if let blogDetailsViewController = navigationController.topViewController as? BlogDetailsViewController {
    blogDetailsViewController.showDetailView(for: subsection)
}

**Review by frosty — APPROVED** [review]
This is working well for me! Just two more small code-level suggestions, and then :shipit:!

**Comment by jkmassel** [comment]
👋 We're cutting the `17.1` release today, so this PR's milestone will be updated to `17.2`!

**Comment by momo-ozawa** [comment]
@frosty I'm leaning towards merging this into release/17.1 instead of develop, since this is a bug. What do you think?

**Review by frosty — APPROVED** [review]
Works for me, and yes – merging to 17.1 makes sense!
