### PR TITLE
Issue 19051 - Suggestions list disappear after expanding/collapsing the reply input

### LINKED ISSUE #19051: Suggestions list (using @-mention) disappear after expanding/collapsing the reply input
### Expected behavior
Suggestions list continue to be shown after expanding/collapsing the reply input.

### Actual behavior
Suggestions list disappear after expanding/collapsing the reply input.

### Steps to reproduce the behavior
The issue is also reproducible in the other scenarios mentioned in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/18979).

1 - Tap the "My Site" tab.
2 - Tap on "Menu"
3 - Tap on "Comments" row.
4 - Tap any comment.
5 - Tap "Reply" button.
6 - Type `"@"`. You should see the suggestions list. Tap on the chevron up button: the reply input is expanded and the suggestions list is gone.
7 - Delete the `"@"` and type it again. You should see the suggestions list. Tap on the chevron down button: the reply input is collapsed and the suggestions list is gone.

### PR DESCRIPTION
**Pull request by igoriols**
Closes https://github.com/wordpress-mobile/WordPress-iOS/issues/19051

## Description

In this PR, I'm addressing the requested change to keep the suggestions list visible when expanding/collapsing the reply text field. If the user inserts a `@` the suggestions appear. And if the user clicks on the `^` button, it should be visible when the text area is expanded. Following the same idea, if the text area is expanded and the suggestions list is visible, it should remain visible when the user clicks on the `⌄` button.

## Details

- I created `FullScreenCommentReplyViewModel` to extract business logic from `FullScreenCommentReplyViewController` and make it easy to test the visibility of the suggestions list. 

- I added a new parameter on `FullScreenCommentReplyViewController.enableSuggestions` representing the last search string provided by the user, and it is being called before `FullScreenCommentReplyViewController` is presented. 

- I changed `FullScreenCommentReplyViewController` to display the suggestions list if the search text was provided. The suggestions list is shown or not in `viewDidAppear` using the search text provided. The suggestions list remains hidden if the search text is nil or empty.

- I modified `FullScreenCommentReplyViewController.onExitFullscreen` to have one more string as the last parameter. It represents the last search text inserted by the user when the text input area is expanded. 

- When the user exits `FullScreenCommentReplyViewController`, `onExitFullscreen` completion block is called with the last search text provided. If the user press `Reply` there is no need to keep the list visible, so I'm sending nil in the completion block. 

- I created a new method in `ReplyTextViewDelegate` which is being called when `FullScreenCommentReplyViewController` is closed. The implementation receives the last search text provided by the user, and displays the suggestions list. 

- I'm calling the new delegate method on every view controller that calls `FullScreenCommentReplyViewController` enabling the suggestions list visibility. So, every view controller that conforms with `willEnterFullScreen` method is conforming with the new `didExitFullScreen` method.

## Preview

<p float="left">
  
   
</p>

## Testing Instructions

**N.B: The user-mentions suggestions feature is not enabled in self-hosted sites ( wordpress.org ).**

**Scenario 1 - Suggestions list remains visible when the text area is expanded** 

1. Tap the "My Site" tab.
2. Tap on "Menu".
3. Tap on "Comments" row.
4. Tap any comment.
5. Tap "Reply" button.
6. Type "@" and you should see the user-mentions suggestions list.
7. Click on the `^` button.
8. Check if the suggestions list remains visible. 

**Scenario 2 - Suggestions list remains visible when the text area is collapsed** 

1. Tap the "My Site" tab.
2. Tap on "Menu".
3. Tap on "Comments" row.
4. Tap any comment.
5. Tap "Reply" button.
6. Type "@" and you should see the user-mentions suggestions list.
7. Click on the `^` button.
9. Erase the text to make the suggestions list disappear. 
10. Make it appear again by typing "@".
11. Click on the `⌄` button to collapse the text area.
12. Check if the suggestions list remains visible.

There are other scenarios to display the suggestions list described in https://github.com/wordpress-mobile/WordPress-iOS/pull/18979.

## Regression Notes
1. Potential unintended areas of impact
Unfortunately I couldn't create unit tests for every view controller conforming with the new `didExitFullScreen` delegate method: `CommentDetailViewController`, `NotificationDetailsViewController` and `ReaderCommentsViewController`.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I've manually tested all the scenarios where `didExitFullScreen` is called. 

3. What automated tests I added (or what prevented me from doing so)
I added `FullScreenCommentReplyViewModelTests` and I added new tests in `FullScreenCommentReplyViewControllerTests` to check the visibility of the suggestions list.
I couldn't add new tests for `CommentDetailViewController`, `NotificationDetailsViewController` and `ReaderCommentsViewController` to ensure the suggestions list is displayed because those view controllers are not unit-testable.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hassaanelgarem** [comment]
@igoriols The first time the input field is expanded, the issue is fixed. However, if I expand the list again the list disappears.


https://user-images.githubusercontent.com/25306722/187101697-0e46ca09-93ae-4fb1-87cd-0847557dd561.mp4

**Comment by igoriols** [comment]
> @igoriols The first time the input field is expanded, the issue is fixed. However, if I expand the list again the list disappears.
> Simulator.Screen.Recording.-.iPhone.13.Pro.-.2022-08-29.at.02.26.44.mp4

Sorry, but I couldn't reproduce the behavior you identified. Here is what I found:
Simulator Screen Recording - iPhone 13 Pro - 2022-08-29 at 09 03 31

Could you please share more details about how you identified what you have found?
How did you access the screen to reply to the comment?

Thanks in advance.

**Comment by hassaanelgarem** [comment]
> Could you please share more details about how you identified what you have found?

@igoriols Sure!

1. Make sure to have a comment on a post with likes
2. Install the app
3. Go to the notifications tab
4. Tap on "Someone liked your comment" notification
5. Tap on the comment
6. This opens up the comments view
7. Type in the reply field "@" followed by any prefix
8. Expand the reply field
9. Collapse the reply field
10. Expand the reply field
11. Notice that the suggestions list is not visible

I think it's reproducible from any type of notification not just "Someone liked your comment"

**Comment by igoriols** [comment]
> > Could you please share more details about how you identified what you have found?
> 
> @igoriols Sure!
> 
>     1. Make sure to have a comment on a post with likes
> 
>     2. Install the app
> 
>     3. Go to the notifications tab
> 
>     4. Tap on "Someone liked your comment" notification
> 
>     5. Tap on the comment
> 
>     6. This opens up the comments view
> 
>     7. Type in the reply field "@" followed by any prefix
> 
>     8. Expand the reply field
> 
>     9. Collapse the reply field
> 
>     10. Expand the reply field
> 
>     11. Notice that the suggestions list is not visible
> 
> 
> I think it's reproducible from any type of notification not just "Someone liked your comment"

Thank you for the detailed steps. Sorry, but I still can't reproduce it yet. 😕 

Simulator Screen Recording - iPhone 13 Pro - 2022-08-29 at 14 30 34

I also tried to reproduce it with other types of notifications, but I couldn't reproduce it yet. The new method I created is being called every time the suggestions list visibility is enabled. So, it should work by expanding/collapsing the reply field.

One thing I noticed is that sometimes the UI hangs during the search. Maybe a possible solution is to extract the search execution to another thread. 

The behavior you found is always happening?
Could you please check it again?

File: WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift [hunk 1]
```diff
@@ -1116,13 +1116,19 @@ extension CommentDetailViewController: ReplyTextViewDelegate {
...
         suggestionsTableView?.hideSuggestions()
 
         if let siteID = siteID {
-            controller.enableSuggestions(with: siteID, prominentSuggestionsIds: suggestionsTableView?.prominentSuggestionsIds)
+            controller.enableSuggestions(with: siteID, prominentSuggestionsIds: suggestionsTableView?.prominentSuggestionsIds, searchText: lastSearchText)
         }
     }
 
+    func replyTextView(_ replyTextView: ReplyTextView, didExitFullScreen lastSearchText: String?) {
+        guard let lastSearchText = lastSearchText, !lastSearchText.isEmpty else { return }
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift]: [Nit]
```suggestion
        guard let lastSearchText = lastSearchText, !lastSearchText.isEmpty else {
            return
        }
```

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift [hunk 2]
```diff
@@ -28,10 +29,12 @@ public class FullScreenCommentReplyViewController: EditCommentViewController, Su
     private var siteID: NSNumber?
     private var prominentSuggestionsIds: [NSNumber]?
     private var suggestionsTableView: SuggestionsTableView?
+    private var searchText: String?
 
     // Static margin between the suggestions view and the text cursor position
     private let suggestionViewMargin: CGFloat = 5
 
+    var viewModel: FullScreenCommentReplyViewModelType = FullScreenCommentReplyViewModel()
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift]: [Nit] I don't think this variable should be public. How about injecting it through an initializer?

File: WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+        sut = FullScreenCommentReplyViewModel(suggestionsService: suggestionsServiceMock, context: mainContext)
+    }
+
+    func testSuggestionsTableViewIsNotNil() {
+        let tableView = sut.suggestionsTableView(with: number, useTransparentHeader: false, prominentSuggestionsIds: [number], delegate: SuggestionsTableViewDelegateMock())
+
+        XCTAssertNotNil(tableView)
+    }
+
+    func testShouldShowSuggestionsIsFalse() {
```
Comment (hassaanelgarem) [inline WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift]: This test is a bit vague. Can you either add a more verbose setup in the test or add some documentation?

**Review by hassaanelgarem — COMMENTED** [review]
> The behavior you found is always happening?
> Could you please check it again?

I tested again on a physical device and the issue is not happening. Looks like a simulator bug 🤦‍♂️

File: WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift (hunk 3 above)
Comment (igoriols) [reply WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift]: Sure. I added a more verbose setup. Is it ok like that?

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift (hunk 2 above)
Comment (igoriols) [reply WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift]: Good idea, I thought about injecting through an initializer at first, but as it was inheriting from an Objective-C class, I thought it would be more complex. After a deeper look, I realized it was easier than I thought. 
Thanks for suggesting it.

File: WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift (hunk 1 above)
Comment (igoriols) [reply WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift]: Done. Thank you!

File: WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift (hunk 3 above)
Comment (hassaanelgarem) [reply WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift]: It's still unclear to me why the expected result is false 🤔

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift [hunk 4]
```diff
@@ -25,18 +25,29 @@ public class FullScreenCommentReplyViewController: EditCommentViewController, Su
...
     private let suggestionViewMargin: CGFloat = 5
 
-    var viewModel: FullScreenCommentReplyViewModelType = FullScreenCommentReplyViewModel()
     public var placeholder = String()
 
+    init(viewModel: FullScreenCommentReplyViewModelType = FullScreenCommentReplyViewModel()) {
+        // nibName from super class
+        let nibName = String(describing: EditCommentViewController.self)
+        self.viewModel = viewModel
+        super.init(nibName: nibName, bundle: nil)
```
Comment (hassaanelgarem) [inline WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift]: [Nit]
EditCommentViewController has a static function (`+ (NSString *)nibName;`) that determines the nibName that we can leverage. If we make this public we can do something like this:

```suggestion
        self.viewModel = viewModel
        super.init(nibName: Self.nibName(), bundle: nil)
```

What do you think?

File: WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift (hunk 3 above)
Comment (igoriols) [reply WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift]: It runs on the test environment with the mocked CoreData context, so it is expected to return false. I will add some documentation and one more test to clarify.

File: WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift (hunk 4 above)
Comment (igoriols) [reply WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift]: Nice catch. I applied your suggestions. Thank you!

**Review by hassaanelgarem — APPROVED** [review]

**Comment by hassaanelgarem** [comment]
LGTM!
One last thing, please add a low-priority release note for this fix 🙏
