### PR TITLE
Fix "index 2 beyond bounds [0 .. 1]" crash

### LINKED ISSUE #14793: NSRangeException: *** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]
**Sentry Url**: https://sentry.io/share/issue/05e6665067204964aa890efcf60479c9/
**User Count**: 245
**Count**: 295
**First Release**: 14.6.0.3
**First Seen**: 2020-04-29T12:57:07Z
**Last Seen**: 2020-08-28T16:09:29Z
**24 Hours**: 6
**30 Days**: 129
**LogID:** BAC52945-B89A-4167-983D-915686314307

```
NSRangeException: *** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]
  File "Classes/Utility/WPTableViewHandler.m", line 154, in -[WPTableViewHandler refreshTableViewPreservingOffset]
  File "Classes/ViewRelated/Reader/ReaderTableContent.swift", line 52, in ReaderTableContent.refreshPreservingOffset
  File "ReaderStreamViewController.swift", line 1145, in ReaderStreamViewController.cleanupAfterSync
  File "<compiler-generated>", line null, in ReaderStreamViewController.syncContentEnded
  File "<compiler-generated>", line 1343, in ReaderStreamViewController.syncContentEnded
  File "<compiler-generated>", line null, in WPContentSyncHelper.syncContentEnded
  File "WPContentSyncHelper.swift", line 86, in WPContentSyncHelper.syncMoreContent
  File "<compiler-generated>", line null, in WPContentSyncHelper.syncMoreContent
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "ReaderStreamViewController.swift", line 1000, in ReaderStreamViewController.syncItems
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "main.swift", line 7, in main
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #14793

## To test

Unfortunately, I wasn't able to reproduce the crash. So just a code review might be enough.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by leandroalonso** [comment]
@yaelirub would you mind reviewing this one? It's very simple and it would be good to have in 15.7.

File: WordPress/Classes/Utility/WPTableViewHandler.m [hunk 1]
```diff
@@ -151,15 +151,18 @@ - (void)refreshTableViewPreservingOffset
...
 
-        CGRect originalCellFrame = [[visibleCellFrames objectAtIndex:i] CGRectValue];
-        if (newIndexPath) {
-            // Since we still have one of the originally visible objects,
-            // preserve the original cell frame's origin, relative to the original content offset.
-            originalCellOriginOffsetDelta += originalOffset.y - originalCellFrame.origin.y;
-            break;
-        } else {
-            originalCellOriginOffsetDelta -= originalCellFrame.size.height;
+        if (visibleCellFrames.count >= i) {
```
Comment (emilylaguna) [inline WordPress/Classes/Utility/WPTableViewHandler.m]: If `i` is higher than the count, shouldn't we `break` out of the loop instead of continue iterating?

Comment (leandroalonso) [reply WordPress/Classes/Utility/WPTableViewHandler.m]: I leave without it just to keep the code without too many branches (`if`, `else`, `if`, `else`). It will probably iterate there a few more times but I'm not sure if it makes any performance difference.

What do you think? With or without it?

File: WordPress/Classes/Utility/WPTableViewHandler.m [hunk 2]
```diff
@@ -151,15 +151,18 @@ - (void)refreshTableViewPreservingOffset
...
+            if (newIndexPath) {
+                // Since we still have one of the originally visible objects,
+                // preserve the original cell frame's origin, relative to the original content offset.
+                originalCellOriginOffsetDelta += originalOffset.y - originalCellFrame.origin.y;
+                break;
+            } else {
+                originalCellOriginOffsetDelta -= originalCellFrame.size.height;
+            }
         }
+
```
Comment (emilylaguna) [inline WordPress/Classes/Utility/WPTableViewHandler.m]: Doing this would solve the if/else issue no?
```suggestion
            if (i > visibleCellFrames.count) {
                break;
            }
            
            CGRect originalCellFrame = [[visibleCellFrames objectAtIndex:i] CGRectValue];
            if (newIndexPath) {
                // Since we still have one of the originally visible objects,
                // preserve the original cell frame's origin, relative to the original content offset.
                originalCellOriginOffsetDelta += originalOffset.y - originalCellFrame.origin.y;
                break;
            } else {
                originalCellOriginOffsetDelta -= originalCellFrame.size.height;
            }
```

**Review by emilylaguna — APPROVED** [review]
I wasn't able to reproduce this crash either, but this change doesn't seem to affect the existing reader at all.
