### PR TITLE
Media: Implement sync of assets

### LINKED ISSUE #9922: Media Library: 'you have no media' appears just before the media does.
### Expected behavior
After the media is loaded, the view should go from 'fetching media' to displaying the media.  

### Actual behavior
After the media is loaded, 'you have no media' displays for a split second, then the media is displayed.

### Steps to reproduce the behavior
- A slow internet connection may be required.
- Also, a fresh install may be required as the media seems to cache.
- Go to Media Library on a site with media.
- See the view go from 'fetching media' >  'you have no media' > actual media display.

This is caused by `pickerDataSource.numberOfAssets()` being 0 when `mediaPickerControllerDidEndLoadingData` is called from the `MediaPicker` pod. It does eventually updates to the correct number. However, this is resulting in the NoResultsView showing the view for no media for a split second until `numberOfAssets` is updated.

no_media_message

### PR DESCRIPTION
**Pull request by kean**
Part of #21457

- Implement sync of Media library
- Add "Media Modernization" feature flag
- Fix https://github.com/wordpress-mobile/WordPress-iOS/issues/9922

## To test:

- Fresh install
- Enable "Media Modernization" feature flag
- Open the new Media screen and verify that the assets are synced
- Upload an asset on the web, return to the app and use PTR to sync the library

This PR also covers error and empty scenarios.

## Regression Notes
1. Potential unintended areas of impact: n/a (no production code changes)
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Media/Library/MediaCollectionCell.swift [hunk 1]
```diff
@@ -47,8 +47,10 @@ final class MediaCollectionCell: UICollectionViewCell {
             viewModel.onLoadingFinished = { [weak self] image in
                 guard let self, self.viewModel?.mediaID == mediaID else { return }
                 // TODO: Display an asset-specific placeholder on error
-                UIView.animate(withDuration: 0.2) {
+                self.imageView.alpha = 0
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Media/Library/MediaCollectionCell.swift:50]: I have a separate PR coming focusing on the cells, so disregard this.

File: WordPress/Classes/ViewRelated/Media/Library/MediaViewController.swift [hunk 2]
```diff
@@ -49,10 +77,55 @@ final class MediaViewController: UIViewController, NSFetchedResultsControllerDel
...
+
+    @objc private func syncMedia() {
+        guard !isSyncing else { return }
+        isSyncing = true
+
+        coordinator.syncMedia(for: blog, success: { [weak self] in
+            // The success callback is called before the changes get merged
+            // in the main context, so the app needs to wait until the
+            // fetch controller updates. Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/9922
+            let work = DispatchWorkItem {
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Media/Library/MediaViewController.swift:92]: I'm open to suggestions. This is clearly not ideal.

File: WordPress/Classes/ViewRelated/Media/Library/MediaViewController.swift [hunk 3]
```diff
@@ -102,6 +175,12 @@ final class MediaViewController: UIViewController, NSFetchedResultsControllerDel
             }
         }
         pendingChanges = []
+
+        if let workItem = pendingRefreshWorkItem {
+            workItem.cancel()
+            didFinishRefreshing(error: nil)
+            pendingRefreshWorkItem = nil
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Media/Library/MediaViewController.swift:182]: I think you can omit this since didFinishRefreshing(error:) sets pendingRefreshWorkItem to nil

**Review by momo-ozawa — APPROVED** [review]
