### PR TITLE
Posts: Show "duplicate" action for pending posts

### LINKED ISSUE #22854: Posts list: contributor drafts missing context menu actions
### Expected behavior
Contributor drafts should have the "Duplicate" and "Publish" actions available in the context menu to match the web

Screenshot 2024-03-19 at 16 32 23

### Actual behavior
"Duplicate" and "Publish" are missing.

It's particularly inconvenient that "Publish" is missing; the only way to publish is to go in to post settings and change the status to "Published". There is no option in the editor overflow menu to publish either. I'm not sure if this is intentional, but I think the editor should also have a "Publish" option. 

### Steps to reproduce the behavior
- Create a contributor post for a site and submit for review (on the web or app, whichever is easier)
- On the app, log in via an account that has admin access and locate the above post
- Tap on the context menu for the post

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #22854 

## Description
* Fixes an issue where the "duplicate" action wasn't available for pending posts

## How to test

- Create a contributor post for a site and submit for review (on the web or app, whichever is easier)
- On the app, log in via an account that has admin access and locate the above post
- Tap on the context menu for the post
- ✅ Verify: The duplicate action is available

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
added tests

3. What automated tests I added (or what prevented me from doing so)
added a test for pending posts context menu actions

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift [hunk 1]
```diff
@@ -204,7 +204,7 @@ class PostCardStatusViewModel: NSObject, AbstractPostMenuViewModel {
             buttons.append(.moveToDraft)
         }
 
-        if post.status == .publish || post.status == .draft {
+        if post.status == .publish || post.status == .draft || post.status == .pending {
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift:207]: I only made these changes to the posts view model, because there's no such thing as pending pages - contributors can't create pages (ref: https://wordpress.com/support/invite-people/user-roles/)

**Review by kean — APPROVED** [review]
