### PR TITLE
Fix an issue where the FAB was not correctly displayed in the post screen on iPad split screen

### LINKED ISSUE #17661: Add post fab dissapearing on split screen on iPad
### Expected behavior
Fab to add new posts should always be visible on the Posts screen, it's the only way to add a new post. 

### Actual behavior
When pulling the WP app into a split screen view on iPad, the fab doesn't initially appear on the posts screen. Tapping back to My Site and then back to Posts brings it back. 

Video of the issue: 

https://user-images.githubusercontent.com/712873/145466159-dce65a34-9e7e-4d16-b1b7-560b020b3223.MP4

### Steps to reproduce the behavior
- Open the WP app on iPad
- Open another app
- Drag the WP app into view as a split-screen and resize the WP app to the smallest size.
- Sometimes the add post fab shows up, sometimes it doesn't

##### Tested on [device], iOS [version], WPiOS [version]

This issue was reported by a user and I was able to reproduce it. 

Test on iPad, iOS 15.1, WPiOS 18.8

### PR DESCRIPTION
**Pull request by Gio2018**
Fixes #17661

To test:

- checkout/build and run this branch on an iPad (device or sim)
- go to the post list
- play around with different sizes and rotations of split screen, and make sure the FAB appears correctly in each condition
- Repeat the test on iPhone and make sure the FAB in the post list screen appears correctly both in portrait and landscape

<p align=center>

</p>

## Regression Notes
1. Potential unintended areas of impact
None, this code only adds handling the FAB in the post list.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
visually test that the FAB in the post list behaves correctly, on a variety of devices and orientations.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 1]
```diff
@@ -379,6 +385,15 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
         filterSettings.setFilterWithPostStatus(initialFilterWithPostStatus)
     }
 
+    /// Listens for the app coming to foreground in order to properly set the create button
+    private func listenForAppComingToForeground() {
+        NotificationCenter.default.addObserver(forName: UIApplication.willEnterForegroundNotification,
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: 👋 @Gio2018 - I was looking at [the docs](https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver) for `addObserver(forName:object:queue:using:)` and I wonder if we should be explicitly removing the observer when the view goes away.

The `removeObserver(_:name:object:)` [docs say](https://developer.apple.com/documentation/foundation/notificationcenter/1407263-removeobserver):

> If you used [addObserver(forName:object:queue:using:)](https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver) to create your observer, you should call this method or removeObserver(_:) before the system deallocates any object that addObserver(forName:object:queue:using:) specifies.

> If your app targets iOS 9.0 and later or macOS 10.11 and later, and you used addObserver(_:selector:name:object:) to create your observer, you do not need to unregister the observer. If you forget or are unable to remove the observer, the system cleans up the next time it would have posted to it.

If we do, does the same apply for the [site title PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/18543/files#diff-84a58b7cfc66828e04468ded5b553cec2b9bea10b14d5f92549499ecf4f976d6R63)?

**Review by twstokes — COMMENTED** [review]
Looks good! I tested on both and iPad and iPhone. I left one comment in the code review.

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift (hunk 1 above)
Comment (Gio2018) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Thanks @twstokes !! Good point, we should either call `addObserver(_:selector:name:object:)` or remove the observer. I'll update it. We should indeed do the same in Site Title, but I'd do it in a separate pr since this addresses a specific issue.

Comment (twstokes) [reply WordPress/Classes/ViewRelated/Post/PostListViewController.swift]: Sounds good! Apologies for not spotting it on the other PR.

**Comment by mokagio** [comment]
I'll be starting the 19.9 code freeze soon, but I think this ought to be part of 19.9. We'll ship a new beta for this once merged 👍

**Review by twstokes — APPROVED** [review]
LGTM @Gio2018!
