### PR TITLE
Likes List: track when more Likes fetched

### LINKED ISSUE #16726: Likes: Add stat to track when more items are fetched when the list is scrolled
Add a new tracks event to bump when the likes list is scrolled and more items are fetched.
Add logic to bump the event when more items are fetched. Do not bump on a failed fetch.  
For example: `like_list_fetched_more`

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #16726 

This adds a track event when more Likes are fetched, i.e. the list is scrolled past the initially fetched Likes.

To test:

Reader:
- Go to the Reader. Select a post with more than 90 likes.
- Tap the Likes summary to display the list.
- Scroll past the first batch of Likes to fetch more.
- Verify this is logged: `🔵 Tracked: like_list_fetched_more <source: like_reader_list>`

Like Notifications:
- Go to the Notifications > Likes. Select one with more than 90 likes.
- Scroll past the first batch of Likes to fetch more.
- Verify this is logged: `🔵 Tracked: like_list_fetched_more <source: like_notification_list>`

Hack Tip:
If you don't have a lot of Likes, you can add a `count` parameter to the [fetch methods](https://github.com/wordpress-mobile/WordPress-iOS/blob/af5f627a23f74e6552c2b2a60c85a65234d9ca73/WordPress/Classes/ViewRelated/Likes/LikesListController.swift#L220) to fetch less at a time.

```
postService.getLikesFor(postID: postID,
                        siteID: siteID,
                        count: 10,

commentService.getLikesFor(commentID: commentID,
                         siteID: siteID,
                         count: 10,
```

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Likes/LikesListController.swift [hunk 1]
```diff
@@ -82,6 +82,10 @@ class LikesListController: NSObject {
         return showingNotificationLikes ? 2 : 1
     }
 
+    private var analyticsProperties: [String: Any] {
+        return showingNotificationLikes ? ["source": "like_notification_list"] : ["source": "like_reader_list"]
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Likes/LikesListController.swift]: We could just say `notifications` and `reader` for the source since the rest is implied.

File: WordPress/Classes/ViewRelated/Likes/LikesListController.swift [hunk 2]
```diff
@@ -170,17 +174,25 @@ class LikesListController: NSObject {
...
-            self?.totalLikesFetched = users.count
-            self?.lastFetchedDate = users.last?.dateLikedString
-            self?.isFirstLoad = false
-            self?.isLoadingContent = false
-            self?.trackUsersToExclude()
+            if self.isFirstLoad {
+                self.delegate?.updatedTotalLikes?(totalLikes)
+            }
+
+            if !self.isFirstLoad && !users.isEmpty {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Likes/LikesListController.swift:185]: Nice :)

**Review by aerych — APPROVED** [review]
Howdy @ScoutHarris 👋 
Code looks good :)  Just one suggestion that's a bit nitpicky. 
Tested and confirmed that the new event was being tracked as expected. 
:shipit:  from me!

File: WordPress/Classes/ViewRelated/Likes/LikesListController.swift (hunk 1 above)
Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/Likes/LikesListController.swift]: Okie dokie.
