### PR TITLE
Issue/7691 inconsistent date labels

### LINKED ISSUE #7691: Stats: Inconsistent Date Labels
### Expected behavior
All date labels show up with a consistent size.

### Actual behavior
Irregular label size!

### Steps to reproduce the behavior
Launch Stats on an iPad Device, portrait.

##### Tested on iPad, iOS 10, WPiOS 8.2
img_0041

### PR DESCRIPTION
**Pull request by jim-rhoades**
Fixes #7691 

To test:

I tested this on the iPhone 7 and iPad Pro 9.7" simulators. I am unable to test on a device due to code signing issues.

Needs review: @

### CODE REVIEW

**Comment by jim-rhoades** [comment]
Also, I wasn't sure where to put the method:

- (CGFloat)fontSizeForString: (NSString *)string inRect: (CGRect)rect

... which I added to WPStatsGraphViewController.m. If needed, I could make that more generic by adding a font parameter and move it somewhere else (maybe a new file under "WordPressComStatsiOS > Services"?

**Comment by diegoreymendez** [comment]
Adding @jleandroperez as a reviewer since he opened the original issue.

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m [hunk 1]
```diff
@@ -208,6 +217,50 @@ - (void)setVisits:(StatsVisits *)visits forSummaryType:(StatsSummaryType)summary
...
+            smallestFontSize = currentFontSize;
+        }
+    }
+
+    return smallestFontSize;
+}
+
+- (CGFloat)fontSizeForString: (NSString *)string inRect: (CGRect)rect
+{
+    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(rect), 17.0f)];
```
Comment (diegoreymendez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: @jim-rhoades - I noticed that the label may not really be necessary in this method.  Is there any specific reason to have it?

Comment (jim-rhoades) [reply WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: It's used by the rest of the method to calculate the font size... but honestly I wasn't in love with allocating temporary UILabel's just to figure out what the smallest font size should be. I was rushed and had family in town the day I was playing around with that, so didn't have time to figure out if there's a better way. I'll look at it again.

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphBarCell.h [hunk 2]
```diff
@@ -9,6 +9,7 @@
 @property (nonatomic, strong) NSArray *categoryBars;
 
 @property (nonatomic, copy) NSString *barName;
+@property CGFloat barNameFontSize;
```
Comment (jleandroperez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphBarCell.h]: Mind adding `(nonatomic)` ?. By default, properties are `atomic`, and this way we'd avoid the extra locking overhead.

[Ref. here!](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/EncapsulatingData/EncapsulatingData.html)

File: WordPress/InfoPlist-alpha.h [hunk 3]
```diff
@@ -0,0 +1 @@
+
```
Comment (jleandroperez) [inline WordPress/InfoPlist-alpha.h]: Since this isn't really related to the issue, mind reverting this one?

File: WordPress/InfoPlist-internal.h [hunk 4]
```diff
@@ -0,0 +1 @@
+
```
Comment (jleandroperez) [inline WordPress/InfoPlist-internal.h]: Since this isn't really related to the issue, mind reverting this one as well?

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m [hunk 5]
```diff
@@ -20,6 +20,7 @@ @interface WPStatsGraphViewController () <UICollectionViewDelegateFlowLayout>
 @property (nonatomic, strong) NSArray<StatsSummary *> *statsData;
 @property (nonatomic, assign) StatsSummaryType currentSummaryType;
 @property (nonatomic, strong) NSDate *selectedDate;
+@property CGFloat dateFontSize;
```
Comment (jleandroperez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: Same as above. Since properties, by default, are **atomic**, mind adding `(nonatomic)`?

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m [hunk 6]
```diff
@@ -208,6 +217,44 @@ - (void)setVisits:(StatsVisits *)visits forSummaryType:(StatsSummaryType)summary
...
+            smallestFontSize = currentFontSize;
+        } else if (currentFontSize < smallestFontSize) {
+            smallestFontSize = currentFontSize;
+        }
+    }
+
+    return smallestFontSize;
+}
+
+- (CGFloat)fontSizeForString: (NSString *)string inRect: (CGRect)rect
```
Comment (jleandroperez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: Since only the `rect.size` is ever used, would it be possible to update the signature?

```
- (CGFloat)fontSizeForString: (NSString *)string containerSize: (CGSize)size
```

Or something like that! naming isn't really important. But it'd be great to ditch the rect's origin, since it's not required here.

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m [hunk 7]
```diff
@@ -208,6 +217,44 @@ - (void)setVisits:(StatsVisits *)visits forSummaryType:(StatsSummaryType)summary
...
+{
+    UIFont *font = [WPStyleGuide axisLabelFont];
+    NSAttributedString *text = [[NSAttributedString alloc] initWithString:string attributes:@{NSFontAttributeName:font}];
+
+    NSStringDrawingContext *context = [NSStringDrawingContext new];
+    context.minimumScaleFactor = 0.5;
+    CGSize size = CGSizeMake(CGRectGetWidth(rect), CGRectGetHeight(rect));
```
Comment (jleandroperez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: This line is equivalent to `rect.size`

File: WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m [hunk 8]
```diff
@@ -208,6 +217,44 @@ - (void)setVisits:(StatsVisits *)visits forSummaryType:(StatsSummaryType)summary
...
+            smallestFontSize = currentFontSize;
+        }
+    }
+
+    return smallestFontSize;
+}
+
+- (CGFloat)fontSizeForString: (NSString *)string inRect: (CGRect)rect
+{
+    UIFont *font = [WPStyleGuide axisLabelFont];
```
Comment (jleandroperez) [inline WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsGraphViewController.m]: Just a thought! no need to change anything:

By making the UIFont a parameter, you'd be able to encapsulate this into a `NSString+FontSize` extension, which could be reused anywhere. The method signature could look like this:

```
NSString *something = @"Aloha!";
CGFloat calculatedSize = [something sizeWithFont:(UIFont *)font containerSize:(CGSize)size];
```
