### PR TITLE
Check if object id is a temporary object id

### LINKED ISSUE #20630: NSInvalidArgumentException: nil is not a valid object ID
Sentry Issue: [JETPACK-IOS-1B8](https://a8c.sentry.io/issues/4106973751/?referrer=github_integration)

```
NSInvalidArgumentException: nil is not a valid object ID
  File "EditorMediaUtility.swift", line 23, in AuthenticatedImageDownload.main
  File "EditorMediaUtility.swift", line 22, in AuthenticatedImageDownload.main
  File "CoreDataHelper.swift", line 189, in CoreDataStack.performQuery<T>
  File "<compiler-generated>", in CoreDataStack.performQuery<T>
  File "<compiler-generated>", in thunk for closure
...
(18 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by crazytonyli**
This is an attempt to fix #20630.

The crash message says "NSInvalidArgumentException: nil is not a valid object ID", but the `blogObjectID` is a non-optional object, so I'm not exactly sure what the `nil` references and what's the cause of the crash.

Considering this is an attempt to fix a crash, @mokagio do you think we should target this change to the code freeze branch?

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Viewed a post with images, and confirmed the image can be loaded and displayed.

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
N/A

### CODE REVIEW

**Review by twstokes — APPROVED** [review]
LGTM @crazytonyli! Thanks for making this change.

One thing I didn't dig into that I had a question about: When the error is thrown and the `Result` fails will it reach Sentry?

**Comment by crazytonyli** [comment]
@twstokes I don't think it will. I was thinking if the crash disappears from the release that includes this change, then we'll know that this fix works. What kind of information do you want to send to Sentry?

**Comment by twstokes** [comment]
> @twstokes I don't think it will. I was thinking if the crash disappears from the release that includes this change, then we'll know that this fix works. What kind of information do you want to send to Sentry?

True, and since it first appeared in this release + it's semi-frequent the data should be pretty clear. I'm good with keeping it as is. 👍

**Comment by crazytonyli** [comment]
@mokagio I've changed the target branch to the 22.3 release branch, considering this is an attempt to fix the 3rd top crash in 22.2.

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift [hunk 1]
```diff
@@ -3,13 +3,18 @@ import Aztec
...
+    }
+
     let url: URL
     let blogObjectID: NSManagedObjectID
     private let callbackQueue: DispatchQueue
     private let onSuccess: (UIImage) -> ()
     private let onFailure: (Error) -> ()
 
     init(url: URL, blogObjectID: NSManagedObjectID, callbackQueue: DispatchQueue, onSuccess: @escaping (UIImage) -> (), onFailure: @escaping (Error) -> ()) {
+        assert(!blogObjectID.isTemporaryID)
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:17]: For reference, since I always forget how `assert`, `fatalError`, etc behave in Release, so I checked [the docs](https://developer.apple.com/documentation/swift/assert(_:_:file:line:)) and verified this will be ignored in Release builds:

> Use this function for internal sanity checks that are active during testing but do not impact performance of shipping code. To check for invalid usage in Release builds, see `precondition(_:_:file:line:)`.

I think that's the kind of behavior we want. Fail ASAP during development to shorten the feedback cycle, but be graceful (`throw DownloadError.blogNotFound`) in Release builds.

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift [hunk 2]
```diff
@@ -20,6 +25,12 @@ final class AuthenticatedImageDownload: AsyncOperation {
     override func main() {
         let result = ContextManager.shared.performQuery { context in
             Result {
+                // Can't fetch the blog using a temporary ID. This check is added as an attempt to prevent this crash:
+                // https://github.com/wordpress-mobile/WordPress-iOS/issues/20630
+                guard !self.blogObjectID.isTemporaryID else {
+                    throw DownloadError.blogNotFound
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:31]: Have you considered making this error more specific about the blog being a temporary ID?

**Review by mokagio — APPROVED** [review]
100% agree this fits nicely as a PR against the release branch! 👍

File: WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift (hunk 2 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:31]: I used a quite generic "blog not found" error, because I thought the caller won't care about this detail—whether it's caused by an invalid object id or the blog that associated with the object id is deleted. However, that's all hypothetical though, because no one handles this error. The error type is added just to make the compiler happy 🥲

Comment (mokagio) [reply WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift:31]: > The error type is added just to make the compiler happy 🥲

Excellent emoji choice.
