### PR TITLE
Hide Reader Details back button when it is the first view controller in the navigation stack

### LINKED ISSUE #22780: [iPad] Back Button Incorrectly Visible on Reader Details Screen When Accessed from Notifications
### Expected behavior

The back button shouldn't be visible for root view controllers in the navigation stack.

### Actual behavior

CleanShot 2024-03-06 at 16 36 31

### Steps to reproduce the behavior

Using an iPad device:

1. Navigate to Notifications screen
2. Locate a new post notification
3. Select the notification row
4. Expect the Reader Details screen to appear
5. Verify the Back Button is visible
6. Tapping the Back Button doesn't nothing

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #22780

## Description

This PR addresses a specific issue on the iPad, where the back button item incorrectly appeared on the Reader Details screen when navigating from the Notifications screen

| Before | After |
| ------ | ----- |
|  |  |

## Test Instructions

Using an iPad device:

#### Notifications

1. Navigate to Notifications tab
2. Tap a "New Post" notification
3. **Expect** the back button item not to be visible
4. Navigate to the Comments screen from the Reader Details screen
5. **Expect** the back button to be visible

#### Reader

1. Navigate to Reader
2. Tap any post
3. **Expect** the back button to be visible

## Regression Notes
1. Potential unintended areas of impact
This impacts the visibility of the Reader Details screen back button item. It should be smoke tested for iPhone devices too.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
N/A

## PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Testing checklist:
- [x] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] VoiceOver.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] iPhone and iPad. 
- [x] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift [hunk 1]
```diff
@@ -1031,27 +1032,35 @@ private extension ReaderDetailViewController {
...
-        navigationItem.largeTitleDisplayMode = .never
-        navigationItem.rightBarButtonItems = rightItems.compactMap({ $0 })
     }
 
     func backButtonItem() -> UIBarButtonItem {
-        let button = barButtonItem(with: .gridicon(.chevronLeft), action: #selector(didTapBackButton(_:)))
+        let config = UIImage.SymbolConfiguration(weight: .semibold)
+        let image = UIImage(systemName: "chevron.backward", withConfiguration: config) ?? .gridicon(.chevronLeft)
+        let button = barButtonItem(with: image, action: #selector(didTapBackButton(_:)))
         button.accessibilityLabel = Strings.backButtonAccessibilityLabel
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift:1063]: This change isn't part of the fix, but I've updated the custom back button item to closely match the system back button item.

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift [hunk 2]
```diff
@@ -1031,27 +1032,35 @@ private extension ReaderDetailViewController {
...
         }
-        navigationItem.largeTitleDisplayMode = .never
-        navigationItem.rightBarButtonItems = rightItems.compactMap({ $0 })
     }
 
     func backButtonItem() -> UIBarButtonItem {
-        let button = barButtonItem(with: .gridicon(.chevronLeft), action: #selector(didTapBackButton(_:)))
+        let config = UIImage.SymbolConfiguration(weight: .semibold)
+        let image = UIImage(systemName: "chevron.backward", withConfiguration: config) ?? .gridicon(.chevronLeft)
+        let button = barButtonItem(with: image, action: #selector(didTapBackButton(_:)))
```
Comment (salimbraksa) [inline WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift:1062]: This change isn't part of the fix, but I've updated the custom back button item to closely match the system back button item.

Comment (salimbraksa) [reply WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift:1062]: For context, the behavior of changing the back button's tint color while scrolling through a post with a featured image necessitated the use of a custom button instead of the standard system one.

https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/956261b2-7c5f-4870-b1ca-f46e7bb06513

I've tried removing this custom back button item and the system back button didn't work as expected. Its tint color remained black.

**Review by justtwago — APPROVED** [review]
Thanks for the fix, Salim! 🚀 
Tested it and it worked exactly as described.
