### PR TITLE
Fix scheduling issues

### LINKED ISSUE #13983: Prepublishing Nudges: customized date is ignored for previously saved drafts
Steps to reproduce:

1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap More > Save as Draft. 
1. Tap More > Publish Now. 
1. Change the date to something in the future.
1. Tap the "Schedule Now" button.
1. Notice the post is unexpectedly published with the current date and time. 

**Result:** customized date is ignored for previously saved drafts. ([1m15s](https://cloudup.com/cBnL0zq6OLZ))

Scheduled for May 9 on Apr 23 | Post was published immediately
--- | ---
scheduled-for-may-9|published-immediately
<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Note:** this happens when scheduling posts for the future or backdating posts to the past. It happens if you close and re-open a draft and then try to schedule it or if you use "Save as Draft" and then publish in the same session.

<p style="clear:both;"><sup>h/t @rachelmcr for reporting this in Slack. Thank you!</sup></p>

### PR DESCRIPTION
**Pull request by leandroalonso**
Fixes #13983 and #13985

#### Customized date is ignored for previously saved drafts (#13983)

1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap More > Save as Draft. 
1. Tap More > Publish. 
1. Change the date to something in the future.
1. Tap the "Schedule Now" button.
1. The post should be scheduled

#### Stuck in publish loop after changing publish date to immediately (#13985)

For this one, I fixed two issues: we do not display a date in the past. If it's in the past, we show "Immediately". Also, if you schedule a draft and then remove the scheduling, the draft will behave as a draft (instead of "Publish" as it was before, you'll see "Update").

1. Go to the My site tab > Blog posts > Drafts.
2. Select a draft to open it in the editor.
3. Optional: make some changes to the post content.
4. Open the ellipsis menu and tap "Publish"
5. Notice that the publish date is set to "Immediately". Tap Publish > select Publish immediately.
6. Dismiss the bottom sheet.
7. Tap "X" to close the editor.
8. Notice the "You have unsaved changes" prompt appears. Select "Update Draft" to save the changes to the draft.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift [hunk 1]
```diff
@@ -83,7 +83,11 @@ struct PublishSettingsViewModel {
             } else {
                 post.status = .publish
             }
-        } else {
+        } else if post.originalIsDraft() {
+            // If the original is a draft, keep the post as a draft
+            post.status = .draft
+            post.dateCreated = Date()
+        } else if post.hasFuturePublishDate() {
             post.publishImmediately()
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift:91]: Im a bit confused by this. Why would we publishImmediately if the post has future publish date?

**Comment by yaelirub** [comment]
@leandroalonso , thanks for fixing this!
It works as expected following the testing steps. 
I just have a small clarification question

File: WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift (hunk 1 above)
Comment (leandroalonso) [reply WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift:91]: In this case:

1. No date was given (aka the user tapped "Publish immediately"
2. The post is scheduled, which means we're changing it to be published immediately
3. The post is not a draft (it is an already scheduled published)

I'm open to suggestions because it's confusing. A comment might help?

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift:91]: A comment would be great!!
