### PR TITLE
Post: Use a post's titleForDisplay for notices.

### LINKED ISSUE #16776: Ampersand not properly shown in draft updated or post published notifications
If you have an ampersand on a post/page title, the notifications that pop up will show them as `&amp;` instead.

### Expected behavior
To see the `&`

### Actual behavior
You see the `&amp;` instead.

Screenshot: https://i.imgur.com/pxw82sz.png

### Steps to reproduce the behavior
1. Start a post or a page
2. In the title, make sure you have one ampersand. Example: _Testing & Testing_
3. Either save the draft or publish the post

##### Report on https://ios.forums.wordpress.org/topic/character-reference-appearing-in-post-title?replies=4

### PR DESCRIPTION
**Pull request by aerych**
Fixes #16776

This PR uses `.titleForDisplay()` for notices instead of `.postTitle`.  The `.titleForDisplay()` method handles decoding XML and other HTML entities. With this change post publish notices should no longer show `&amp;` where instead they should show `&`. 

Simulator Screen Shot - iPhone 11 - 2021-08-03 at 16 32 26
Simulator Screen Shot - iPhone 11 - 2021-08-03 at 16 33 16

To test:
Follow the steps to reproduce outlined in the issue.  Confirm that ampersands are correctly displayed.

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

3. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift [hunk 1]
```diff
@@ -125,7 +125,7 @@ struct PostNoticeViewModel {
     }
 
     private var message: String {
-        let title = post.postTitle ?? ""
+        let title = post.titleForDisplay() ?? ""
         if title.count > 0 {
```
Comment (ScoutHarris) [inline WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift]:
```suggestion
        if !title.isEmpty {
```

**Review by ScoutHarris — APPROVED** [review]
Hey @aerych .

This looks good. I just had one minor suggestion. `post.titleForDisplay()` could be cleaned up as well, but I won't be _too_ nitpicky. 😄

File: WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift (hunk 1 above)
Comment (aerych) [reply WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift]: Right you are.  Thanks for thinking about it beyond my little change :)

**Comment by aerych** [comment]
Thanks @ScoutHarris !
