### PR TITLE
Fix WPBlogSelectorButton image position

### LINKED ISSUE #8707: Editor title view arrow collides with blog name
A couple of times over the last day or so, I've seen the dropdown arrow in the editor title view colliding with the blog name:

img_1731

I'm not sure if this is related to the recent RTL changes? https://github.com/wordpress-mobile/WordPress-iOS/pull/8610

I _think_ it happens when the app launches directly to the editor (state restoration), but I've been unable to recreate it on demand so far.

cc @etoledom

### PR DESCRIPTION
**Pull request by etoledom**
This PR fixes the position of the blog selector button image when restoring the app state from the editor

Fixes #8707 

This could be a UIKit bug (not sure). 
Fixed by changing when the `semanticContentAttribute` is set to flip the layout (and move the button image to the right)

To test:

- Build and run the app in Xcode
- Open the editor
- Exit to the home screen
- Stop the app in Xcode
- Re-run the app
- Blog picker button arrow should be at the right side of the button.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m [hunk 1]
```diff
@@ -52,6 +45,25 @@ + (instancetype)buttonWithFrame:(CGRect)frame buttonStyle:(WPBlogSelectorButtonS
...
 
+- (void)didMoveToSuperview
+{
+    [super didMoveToSuperview];
+    [self invertLayout];
+}
+
+/// Inverts the layout to show the image at the right side
+///
+- (void)invertLayout
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m]: Nitpick, but could we rename this something like `invertLayoutIfNeeded` or `ifRequired`?

Comment (etoledom) [reply WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m]: Oh! But it always invert it 😆
The button will always be the inverted of the current user layout.

Maybe the comment is misleading?

Comment (frosty) [reply WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m]: No, I get it now – sorry, I misunderstood what was happening. Perhaps just update the comment to `Inverts the layout to show the image on the trailing side`, as it won't always be `right` if we're in RTL. Thanks! :shipit:!
