### PR TITLE
Fix an issue with search results disappearing after returning from site details

### LINKED ISSUE #24112: Reader: Search cancels after returning from one of the result details
**Description**

- Open Reader / Search
- Search for a blog
- Open one of the sites from the results
- Tap "Back"

**Observed Results**
- Search is cancelled

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/24112.

Before:

https://github.com/user-attachments/assets/b0f43140-fbf6-487e-835b-1caec1f0cca6

After:

https://github.com/user-attachments/assets/0a1eabec-5878-4224-b2a7-08ba2a3b6506

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/307">25.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift [hunk 1]
```diff
@@ -41,6 +41,7 @@ final class ReaderSearchViewController: UIViewController {
     private var currentChildVC: UIViewController?
     private var previousSearchTopic: ReaderAbstractTopic?
     private let contextManager = ContextManager.shared
+    private var isFirstAppearance = false
```
Comment (crazytonyli) [inline WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift]: Is this value supposed to be true?

File: WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift [hunk 2]
```diff
@@ -62,8 +63,11 @@ final class ReaderSearchViewController: UIViewController {
     override func viewDidAppear(_ animated: Bool) {
         super.viewDidAppear(animated)
 
-        DispatchQueue.main.async {
-            self.searchController.searchBar.becomeFirstResponder()
+        if isFirstAppearance {
```
Comment (crazytonyli) [inline WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift:66]: Is `isMovingToParent` applicable here?

File: WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift (hunk 1 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift]: Right. No idea how I tested it

File: WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift (hunk 2 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Reader/Controllers/ReaderSearchViewController.swift:66]: I don't know. I trust `viewDidAppear(_ animated: Bool)` and `isFirstAppearance` more.

**Review by crazytonyli — APPROVED** [review]
