### PR TITLE
Load plans icons from the API

### LINKED ISSUE #5099: Plans: load icons from the API
The current approach of hardcoding the images doesn't work anymore since the slugs don't match. Store the `icon` and `icon_active` attributes from the API and load the images remotely.

It'd be nice to still bundle the icons in the app but fall back to the remote.

### PR DESCRIPTION
**Pull request by koke**
Since this is blocking #5069, I think it's ready to merge, but I plan to refactor the image downloading code later to de-duplicate the several slightly different downloading methods. I already started with WPImageSource here https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/93

Fixes #5099 

Needs review: @frosty

### CODE REVIEW

File: WordPress/Classes/Extensions/UIImageView+Networking.swift [hunk 1]
```diff
@@ -22,9 +29,16 @@ extension UIImageView
             placeholderImage: placeholderImage,
             success: { [weak self]
                 (request: NSURLRequest, response: NSHTTPURLResponse?, image: UIImage) -> Void in
-                
-                self?.image = image
-                success?(image)
+
+                let processedImage: UIImage
```
Comment (frosty) [inline WordPress/Classes/Extensions/UIImageView+Networking.swift]: You could just do:

`let processedImage = processor?(image) ?? image`

here? Conciseness vs clarity, perhaps.

File: WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift [hunk 2]
```diff
@@ -335,9 +335,11 @@ enum PlanPostPurchasePageType: Int {
     case Themes
     
     static func pageTypesForPlan(plan: Plan) -> [PlanPostPurchasePageType] {
-        switch plan.slug {
-        case "premium": return [.PurchaseComplete, .Customize, .VideoPress]
-        case "business": return [.PurchaseComplete, .Customize, .VideoPress, .Themes]
+        switch plan.id {
+        // Premium
+        case 1003: return [.PurchaseComplete, .Customize, .VideoPress]
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift]: Should we create a small enum for these values, instead of comments?

File: WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift [hunk 3]
```diff
@@ -193,7 +193,7 @@ class PlanDetailViewController: UIViewController {
     
     private func populateHeader() {
         let plan = viewModel.plan
-        planImageView.image = plan.image
+        planImageView.setImageWithURL(plan.iconUrl)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift]: I think we should be using the active icon URL here if the plan is active. Also, should we resize the icon here to ensure it's the correct size?

**Comment by frosty** [comment]
A couple of minor code comments for you, @koke! Also, I'm still seeing a couple of empty icons in the asset catalog:

screen shot 2016-04-19 at 10 39 02

Thanks!

File: WordPress/Classes/Extensions/UIImageView+Networking.swift (hunk 1 above)
Comment (koke) [inline WordPress/Classes/Extensions/UIImageView+Networking.swift]: Yeah, I went for the longer version. I didn't wanted to introduce much change before the refactor but my initial plan was for the `processor` value to not be optional and have a default value of `identity`:

```swift
func identity<T>(x: T) -> T {
    return x
}
```

I still have to think more about if that's really better than the optional version.

File: WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift (hunk 2 above)
Comment (koke) [inline WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift]: Makes sense. Will the post purchase screens stay hardcoded, or we'll be fetching that info from the API as well?

**Comment by koke** [comment]
> I think we should be using the active icon URL here if the plan is active

I'm seeing the inactive icon on the mockups, perhaps you were thinking about the post-purchase screens?

plan_business

File: WordPress/Classes/Extensions/UIImageView+Networking.swift (hunk 1 above)
Comment (frosty) [inline WordPress/Classes/Extensions/UIImageView+Networking.swift]: Okay, happy to stick with the longer version :)

**Comment by frosty** [comment]
So in the latest mockups I have, the current plan should have the active icon:

screen shot 2016-04-19 at 11 21 09

This would make sense as it then matches the functionality of the plan list view.

**Comment by koke** [comment]
Oh, that definitely makes more sense, I'll change it.

File: WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift (hunk 2 above)
Comment (frosty) [inline WordPress/Classes/ViewRelated/Plans/PlanPostPurchaseViewController.swift]: I think we decided to leave them hardcoded for now... although thinking about it, we could quite easily make them dynamic without having to alter the API. We could simply select which screens to show based on the features that the purchased plan has.

**Comment by koke** [comment]
@frosty OK, just pushed a fix for the active icon, ready for a final check.

**Comment by frosty** [comment]
:shipit:!
