### PR TITLE
Fix crash when search token are duplicated

### LINKED ISSUE #22269: NSInternalInconsistencyException: Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
Sentry Issue: [JETPACK-IOS-172S](https://a8c.sentry.io/issues/4737699726/?referrer=github_integration)

```
NSInternalInconsistencyException: Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
    WordPress.PostSearchViewModel.ItemID.token(AnyHashable(WordPress.PostSearchTagToken(tag: "#TomorrowsPapersToday")))
)}
  File "PostSearchViewModel.swift", line 134, in PostSearchViewModel.makeSnapshot
  File "PostSearchViewModel.swift", line 83, in PostSearchViewModel.reload
  File "PostSearchViewModel.swift", line 246, in PostSearchViewModel.updateSuggestedTokens
  File "<compiler-generated>", in PostSearchViewModel.updateSuggestedTokens
  File "<compiler-generated>", in PostSearchViewModel.updateSuggestedTokens
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kean**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/22269.

Adds defensive code to make sure the search tokens never have duplicates. It should not be possible to add duplicate tags in the first place, but evidently, there are some sites that do have duplicates.

To test:

- (Regression testing) Verify that tags are displayed as suggested search token

## Regression Notes
1. Potential unintended areas of impact: Post Search
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/Search/PostSearchSuggestionsService.swift [hunk 1]
```diff
@@ -28,12 +28,16 @@ actor PostSearchSuggestionsService {
...
+        let output = Array(tokens
             .flatMap { $0 }
             .filter { !selectedTokenIDs.contains($0.token.id) }
             .sorted { ($0.score, $0.token.value) > ($1.score, $1.token.value) }
             .map { $0.token }
             .prefix(3))
+
+        // Remove duplicates
+        var encounteredIDs = Set<AnyHashable>()
+        return output.filter { encounteredIDs.insert($0.id).inserted }
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Post/Search/PostSearchSuggestionsService.swift:40]: FYI there's an Array extension method called `deduplicated()`!

**Review by momo-ozawa — APPROVED** [review]
LGTM w 1 comment

File: WordPress/Classes/ViewRelated/Post/Search/PostSearchSuggestionsService.swift (hunk 1 above)
Comment (kean) [reply WordPress/Classes/ViewRelated/Post/Search/PostSearchSuggestionsService.swift:40]: Unfortunately, I could use it as is. The issue is that the elements are not Hashable, and I have to extract the ID here: `insert($0.id)`. Maybe there was a better way to design the original protocols for filters, but I decided to keep it.
