### PR TITLE
Fix an issue with avatars not loading in suggestions

### LINKED ISSUE #21155: The avatars in users suggestions list not loading
### Expected behavior

- Avatars are loaded

### Actual behavior

- Avatars are not loaded

### Steps to reproduce the behavior

- Open one of the A8C posts
- Tap on a comment text field
- Start typing a username 

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

latest

## RCA

- Take the following URL: `https://0.gravatar.com/avatar/6e53a25107fdb57cb66d87fc0c88ff5ba3aa16909ad94e39a825fba47157d08d?s=96&d=identicon&r=G`
- `[WPAvatarSource parseURL:forAvatarHash:]` is called to determine the avatar size
- `if ([hash length] == 32) {` condition resolves to `false` because hash length is 64
- `SuggestionsTableView/fetchIcon` (line 192) doesn't start the download because the resolved image type is `.unknown`

Screenshot 2023-07-20 at 5 08 06 PM

### PR DESCRIPTION
**Pull request by kean**
Fixes #21155

The reason it's not working is the following change to the avatar hashes: pb6Nl-gyD-p2.

The proper fix will require a little more work. The app shouldn't make any assumptions about the contents of these identifiers. It should also not use `WPAvatarSource` because it's yet another non-centralized image loading system in the app with its own cache, which contributes to high memory usage issues, and it fails to reuse the caches and there work for fetching the same avatars in other places of the app.

To test:

- Open Reader
- Open one of the A8C posts
- Tap to reply and start typing a user name (staring with @ sign)
- Verify that the avatars are loaded

## Regression Notes
1. Potential unintended areas of impact: user suggestions list in reader replies
2. What I did to test those areas of impact (or what existing automated tests I relied on): manual testing
3. What automated tests I added (or what prevented me from doing so): n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/Utility/WPAvatarSource.m [hunk 1]
```diff
@@ -129,7 +129,7 @@ - (WPAvatarSourceType)parseURL:(NSURL *)url forAvatarHash:(NSString **)avatarHas
     if ([components count] > 2) {
         NSString *type = components[1];
         NSString *hash = components[2];
-        if ([hash length] == 32) {
+        if ([hash length] == 32 || [hash length] == 64) {
```
Comment (guarani) [inline WordPress/Classes/Utility/WPAvatarSource.m:132]: This makes sense given the hash is now 64 characters 👍 
nitpick: I don't know why this has to verify the hash's length, since it seems unlikely we'll get the wrong length and if we do, I don't think there's harm in it. What will happen AFAIK is that we'll just [request the avatar/blavatar](https://en.gravatar.com/site/implement/images/) and it'll fail.

**Review by guarani — APPROVED** [review]
Change looks good! Tested and verified avatars now work. I didn't test blavatars though, but it seems like they work very similarly.

**Comment by guarani** [comment]
> This is a hotfix. The reason it's not working is the following change to the avatar hashes: pb6Nl-gyD-p2.

If this targets `trunk`, it won't be a hotfix nor a betafix but just a regular fix, as defined here PbMoDN-uy-p2.
