### PR TITLE
Fix Notice and Empty View shown at the same time in Site → Pages/Posts

### LINKED ISSUE #11310: Snack bar is displayed on top of "unable to load this page" view
Steps:
- Be offline
- Go to site pages
We should show one or the other 
IMG_3597

### PR DESCRIPTION
**Pull request by shiki**
Fixes #11310.

This fixes a bug in Site → Pages and Site → Posts where when there is no content and no internet connection, both the Notice and Empty View are shown at the same time.

| Before | After |
|--------|-------|
|   |   |

## Testing

Before starting, make sure that you have not loaded anything in Site → Pages and Site → Posts. You can use an empty site or delete the app from the device.

1. Turn off the internet connection on the device.
2. Navigate to Site → Pages and Site → Posts.

You should not see the Notice anymore but see the empty view.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 1]
```diff
@@ -1149,6 +1145,10 @@ class AbstractPostListViewController: UIViewController,
     func noConnectionMessage() -> String {
         return ReachabilityUtils.noConnectionMessage()
     }
+
```
Comment (shiki) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: This is a reordering so the `NetworkAwareUI` methods are grouped together.

File: WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift [hunk 2]
```diff
@@ -1149,6 +1145,10 @@ class AbstractPostListViewController: UIViewController,
...
+    func shouldPresentAlert() -> Bool {
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: Why do we need this? Now there we're calling handleConnectionError it should call the shouldPresentAlert in NetworkAwareUI or is there a reason we need a specific implementation in AbstractPostListViewController?

Comment (shiki) [reply WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: I opted not to change this and just simply moved it to the same location as the other `NetworkAwareUI` methods. I thought that, since it overrides `NetworkAwareUI`'s `shouldPresentAlert()`, it's critical to leave it as is or I might cause a regression. 

Looking more closely, the difference is the additional `isViewOnScreen()` which is probably still important to be there for now. The `isViewOnScreen()` call will prevent us from showing a Notice in scenarios like:

1. On Site → Pages, the user refreshes the page
2. The user navigates away from the page
3. The refresh operation comes back and shows a Notice in the wrong context (!!) 

This is probably unlikely to happen though. Still, I believe we should keep this as is and look into improving `NetworkAwareUI` usage across the app later. WDYT @yaelirub?

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift]: I'm good with that. Thanks for the elaborate response.
