### PR TITLE
Fix my_site_tab_accessed tracking

### LINKED ISSUE #11395: Investigate possibility of inaccurate offline tracking
We found that there's a significant amount of Tracks events that have `device_info_is_online` set to `NO`. Comparing the WPAndroid's Tracks events, this seems inaccurate. 

These events warrant more investigation: 

- `my_site_tab_accessed`
- `stats_period_accessed`
- `stats_insights_accessed`
- `notifications_notification_details_opened`
- `login_accessed`
- `push_notification_alert_tapped`

## Guess

The current guess is `Reachability` is not reporting the correct value when the app is started. Also, consider that we might be incorrectly counting some of these events. For example, `notifications_notification_details_opened` is always triggered when you cold-start the app. 

## Related

- #11003 
- paCBwp-54-p2. 

## Tasks 

- [x] Fix inaccurate `device_info_is_online` values: automattic/Automattic-Tracks-iOS#100
- [ ] Investigate possible incorrect counting of`my_site_tab_accessed`. For example, I noticed that `my_site_tab_accessed` is logged even if the user is logged out. And it is logged twice when the app is placed in the foreground. Done in #11447. 

## Update 2019-04-10

For this ticket, we will be fixing the `device_info_is_online` and `my_site_tab_accessed`. Everything else is moved to #11395.

### PR DESCRIPTION
**Pull request by shiki**
Closes #11395 

## Findings

After some investigation, I found that the `my_site_tab_accessed` event is counted:

1. On app start (`WPTabBarController.init`)
2. On `WPTabBarController.decodeRestorableStateWithCoder`
3. When the user selects the _My Sites_ tab
4. On first launch of the app (user is not logged in)
5. After log out and moving the app to the background and then foreground again. 

The first and second causes the event to be counted *twice*.

Related: paCBwp-54-p2.

## Solution 

This adds a more elaborate mechanism for tracking the event. Most of them are encapsulated in the new file, `WPTabBarController+Swift.swift`. The event is now counted on these scenarios only:

- Logged in: The app has been placed in the foreground
- Logged in: The app was just launched and we restored the previously selected tab
- Logged in: The user selected a different tab
- Not logged in: After logging in (and this VC is shown)

## Testing

Please test that the event is only counted on the scenarios above. 

## Release Notes

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift [hunk 1]
```diff
@@ -0,0 +1,104 @@
+
+// MARK: - Tab Access Tracking
+
+extension WPTabBarController {
+    private static let tabIndexToStatMap: [WPTabType: WPAnalyticsStat] = [
+        .mySites: .mySitesTabAccessed,
+        .reader: .readerAccessed,
+        .me: .meTabAccessed
```
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift]: Do you know offhand why `notifications_accessed` isn't part of this?

**Comment by astralbodies** [comment]
I did notice something interesting with this approach:

```2019-04-11 08:43:34:234 WordPress[40745:1832604] 🔵 Tracked: me_tab_accessed
2019-04-11 08:43:34:797 WordPress[40745:1832604] 🔵 Tracked: application_opened```

The tab accessed is generally before application_opened. I think ultimately we'll be okay because the Tracks event timestamp would put these two at the same time.

File: WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift (hunk 1 above)
Comment (shiki) [reply WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift]: Not sure, it's in `viewWillAppear` of `NotificationsViewController`. I wonder we should do it this way instead of putting these in `WPTabBarController`.

Comment (astralbodies) [reply WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift]: I think the tab bar is the right solution .. we're firing off `notifications_accessed` every time the view is presented including after tapping a notification to see detail and then tapping back. I bet we're over-counting notifications because of this.

Comment (shiki) [reply WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift]: Ah, yeah, you're right. I added that in #11446.

**Comment by shiki** [comment]
@astralbodies This is ready for another round. The `application_opened` event should show up before `me_tab_accessed` now. Fixed that in 435bdbecf9282caf1de1db88ae09595d18acbcdb.
