### PR TITLE
Stats: Localize percentage strings

### LINKED ISSUE #18536: Stats: Percent sign should be localized in stats screen
### Expected behavior
Shortly, the percent sign should be localized according to the current language's rules.

The percentage symbol `%` should be at the start of the number (%100) in some languages (Turkish, Arabic), and the end of the number (100%) in some languages (English, French...). There are also rules for spacing between the sign and the number that can be checked over: https://en.wikipedia.org/wiki/Percent_sign#Form_and_spacing

WordPress.com stats screen in Turkish:
Screen Shot 2022-05-07 at 13 28 05

### Actual behavior
The percent sign is the end of the number in Turkish. I could find it only in days-weeks-months-years tabs of stats screens, but please check other screens where the sign could be used.

### Steps to reproduce the behavior
1. Change your device language to Turkish from OS settings > General > Language & Region > iPad Language > Türkçe(Turkish)
2. Open WordPress app.
3. Go to stats either using quick links or menu.
4. Switch to DAYS ("GÜNLER" in Turkish) tab.
5. Check the percent sign and notice it's the end of the number instead of the start.

##### Tested on iPad mini, iOS 15.4, WPiOS 19.6 (19.6.0.6)

### PR DESCRIPTION
**Pull request by staskus**
Fixes #18536

Percentage sign placement depends on a locale. At the moment, we include it localized string with an explanation but the string we provide for translators is hard to understand and work with and the placement of the percentage sign is not changed based on a locale.

### Solution

1. Remove percentage sign from localized strings
2. Use `NumberFormatter` with application's localization locale to build a number with percentage

- [x] Insights -> Most Popular Time card
- [x] Insights -> Views and Visitors card
- [x] Insights -> Total Likes card
- [x] Insights -> Total Comments card
- [x] Days/Weeks/Months/Years -> Overview Chart

### To test:

Note: At the moment new localized strings are not yet localized, so they will appear in English while percentage sign will be placed based on a current locale

1. Change your device language to Turkish from OS settings > General > Language & Region > iPad Language > Türkçe(Turkish)
3. Open Jetpack app.
4. Go to stats either using quick links or menu.
5. Switch to DAYS ("GÜNLER" in Turkish) tab.
6. Check the percent sign and notice it's the end of the number instead of the start.

## Regression Notes
1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

None

3. What automated tests I added (or what prevented me from doing so)
None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by irfano — CHANGES_REQUESTED** [review]
I tested the percentage symbol in various places in the stats. I'm sharing the screenshot of the only place where I found the symbol being used incorrectly. I couldn't review the code, perhaps @guarani can handle only code reviewing.

**Comment by staskus** [comment]
> I'm sharing the screenshot of the only place where I found the symbol being used incorrectly.

Thanks, @irfano! I missed this place. 🙇

**Comment by staskus** [comment]
✅ Added a missing localized percentage string

fix

**Review by irfano — APPROVED** [review]
Thanks for addressing my comment. LGTM! 👍🏻

File: WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift [hunk 1]
```diff
@@ -56,11 +56,16 @@ struct OverviewTabData: FilterTabBarItem, Hashable {
     }
 
     var differenceLabel: String {
-        let stringFormat = NSLocalizedString("%@%@ (%@%%)", comment: "Difference label for Period Overview stat, indicating change from previous period. Ex: +99.9K (5%)")
+        let stringFormat = NSLocalizedString(
+            "stats.overview.differenceLabelWithNumber",
+            value: "%1$@%2$@ (%3$@)",
+            comment: "Text for the Stats Traffic Overview stat difference label. Shows the change from the previous period, including the percentage value. E.g.: +12.3K (5%). %1$@ is the placeholder for the change sign ('-', '+', or none). %2$@ is the placeholder for the change numerical value. %3$@ is the placeholder for the change percentage value."
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift:62]: Thanks for updating the comment! 
I'm familiarizing myself with the localization process in https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/docs/localization.md#always-add-comments. TIL about the indexed format specifiers e.g. `%1$@` instead of `%@` and how it helps with localization 👍

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift [hunk 2]
```diff
@@ -143,6 +143,14 @@ extension Double {
...
     }
 
+    func abbreviatedPercentageString(forHeroNumber: Bool = false) -> String {
+        guard let numberWithPercentage = NumberFormatter.statsPercentage.string(from: .init(value: self)) else {
+            return abbreviatedString(forHeroNumber: forHeroNumber)
+        }
+
+        return numberWithPercentage.replacingOccurrences(of: "\(self)", with: self.abbreviatedString(forHeroNumber: forHeroNumber))
+    }
+
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift]: How should large percentages such as 10000% be formatted? This code formats them as "10,000%" which I think is correct (an alternative might be e.g. "10.0K%"). 

I think this code formats correctly, but there's some code that's never called.

From what I can tell, the call to `replacingOccurrences(of: with:)` will not have any effect.

Since `statsPercentage` applies formatting:
```
(lldb) po NumberFormatter.statsPercentage.string(from: .init(value: 10000))
▿ Optional<String>
  - some : "10,000%"
```

There are no occurrences of the original unformatted string in `numberWithPercentage`:
```
(lldb) po numberWithPercentage.replacingOccurrences(of: "\(self)", with: self.abbreviatedString(forHeroNumber: forHeroNumber))
"10,000%"
```

For smaller percentages like 1000 the same applies:
```
(lldb) po NumberFormatter.statsPercentage.string(from: .init(value: 1000))
▿ Optional<String>
  - some : "1,000%"
(lldb) po "1,000%".replacingOccurrences(of: "\(1000)", with: self.abbreviatedString(forHeroNumber: false))
"1,000%"
```

For even smaller numbers, the search-replace has no effect because it replaces with the same thing:
```
(lldb) po "100%".replacingOccurrences(of: "\(100)", with: 100.abbreviatedString(forHeroNumber: false))
"100%"
```

This means that there will be no abbreviation (even though it's in the function's name), and `forHeroNumber` will not be used. So I think it makes sense to simplify the function like this:

```
   func percentageString() -> String {
        guard let numberWithPercentage = NumberFormatter.statsPercentage.string(from: .init(value: self)) else {
            return "\(self)%"
        }

        return numberWithPercentage
    }
```


What do you think?

Also, it should be safe to force-unwrap the `string(from:)` since [there doesn't seem to be any chance of it returning nil for doubles](https://stackoverflow.com/questions/48504597/why-does-numberformatters-stringfrom-return-an-optional), but happy to go with what you think is best here.

**Review by guarani — APPROVED** [review]
Thanks @staskus! It's working well and I tested with Türkiye/Turkish language & region and with Paraguay/Spanish.

I left a code comment which I think should be addressed before merging but only relates to unused code, not any change in functionality, so I'll go ahead and approve.

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift (hunk 2 above)
Comment (staskus) [reply WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift]: What a great observation. Different locales have different grouping separators (and some don't), so this naive replacing strategy doesn't work in a lot of cases.

> an alternative might be e.g. "10.0K%

That was my intention, since previously `abbreviatedString()`% was used, so I wanted to keep the abbreviation logic and localize percentage placement. However, I don't think this abbreviation is necessary for percentages, they will rarely be that high.

> This means that there will be no abbreviation (even though it's in the function's name), and forHeroNumber will not be used. So I think it makes sense to simplify the function like this:

Yes, I agree. 

> Also, it should be safe to force-unwrap the string(from:) since [there doesn't seem to be any chance of it returning nil for doubles](https://stackoverflow.com/questions/48504597/why-does-numberformatters-stringfrom-return-an-optional), but happy to go with what you think is best here.

Yes, the arguments look convincing. The `nil` values look to be only possible if using some weird trickery.

File: WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift (hunk 1 above)
Comment (staskus) [reply WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift:62]: Thanks, I remember it well since I'm the one who updated this documentation https://github.com/wordpress-mobile/WordPress-iOS/pull/20111 😅

Comment (guarani) [reply WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift:62]: :D Cool!

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift [hunk 3]
```diff
@@ -157,16 +161,28 @@ extension NSNumber {
...
+        return self.doubleValue.percentageString()
+    }
 }
 
 extension Float {
     func abbreviatedString(forHeroNumber: Bool = false) -> String {
         return Double(self).abbreviatedString(forHeroNumber: forHeroNumber)
     }
+
+    func percentageString(forHeroNumber: Bool = false) -> String {
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift:175]: I just noticed that `forHeroNumber` could be removed here.

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift [hunk 4]
```diff
@@ -157,16 +161,28 @@ extension NSNumber {
...
+        return Double(self).percentageString()
+    }
 }
 
 extension Int {
     func abbreviatedString(forHeroNumber: Bool = false) -> String {
         return Double(self).abbreviatedString(forHeroNumber: forHeroNumber)
     }
+
+    func percentageString(forHeroNumber: Bool = false) -> String {
```
Comment (guarani) [inline WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift:185]: And it could also be removed here

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift (hunk 2 above)
Comment (guarani) [reply WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift]: > and some don't

I wasn't aware that some locales don't have thousand separators, this is good to know 👍 

> since previously abbreviatedString()% was used

I see, that's a good point.

File: WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift (hunk 3 above)
Comment (staskus) [reply WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift:175]: You're right https://github.com/wordpress-mobile/WordPress-iOS/pull/22957
