### PR TITLE
Stats Widget: Fix users without a site are incorrectly asked to login by the widget

### LINKED ISSUE #15857: Users without a site are incorrectly asked to login by the widget
### Expected behavior

Users without a site shouldn't be able to add any of the current widgets (Today stats or All Time stats).

### Actual behavior

Users who don't have a site yet (e.g. chose "Not now" option after sign up) are shown the "Log in to WordPress..." message in the widget.

### Steps to reproduce the behavior

1. Sign up for a new account
2. Skip the site creation process
3. Background the app and notice you can add the stats widgets
4. Notice that the widgets ask you to log in even though you're already logged in

##### Tested on iPhone 11, iOS 14.4, WPiOS 16.6

<sub>First reported [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/15838#pullrequestreview-586657850)</sub>

### PR DESCRIPTION
**Pull request by staskus**
This is a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/pull/18916 PR that was being merged from the fork and wasn't updated for a long time

## Issue

Closes #15857 

## Description

Users without a site are asked to login by the Stats Widget

### Rootcause

This case is not explicitly handled in the Stats Widget.

### Solution

1. Update `SiteListProvider` `getTimelines` method to reflect the logic:
- If user doesn't have default site and is logged in -> "Create or add a site to see today's/this week's/all time stats."
- If user doesn't have default site and is not logged in -> "Log in to WordPress to see today's stats"

2. Set `WPStatsHomeWidgetsUserDefaultsSiteIdKey` to `defaultSiteId` and `nil` in `StatsWidgetStore`. Since this key is only designed to be used by `StatsWidget` it makes sense to set it in `StatsWidgetStore` so full solution would be contained within this class and parts not scattered in `AccountService`.

3. Add `WPSiteDeleted` and `WPSiteCreated` notifications that are posted from services and listened in `StatsWidgetStore`. It is done for 2 main reasons:
- Avoid `Services` being aware and depend on `StatsWidgetStore`. They are lower level abstractions and should not care about the `Widgets`
- Increase understanding of `StatsWidgetStore` functionality. We can clearly see on which state changes the `StatsWidget` depends on and how we react.
 
### Another issue

While working on this issue found another issue with no sites case and widgets: [Stats Widget does not load when a new site appears after refreshing "My Site" tab](https://github.com/wordpress-mobile/WordPress-iOS/issues/18914) . It's more of a corner case and could potentially cause multiple changes in the codebase so decided not to tackle it in this PR.

#### 1st scenario - Add Widget -> Log in to an account without any site

1. Create WordPress account without any site
3. Make sure you are logged out of the app
4. Add WordPress "Stats Widget" (All Time / This Week / Today) on the home screen
5. Confirm that "Log in to WordPress..." message is shown on the widget
6. Log in into the app
7. Go back to the home screen
8. Confirm that "Create or add a site to see today's/this week's/all time stats."" message is shown on the widget

#### 2nd scenario -  Log in to an account without any site -> Add Widget
1. Make sure you are logged in into account without any site
2. Add WordPress "Stats Widget" (All Time / This Week / Today) on the home screen
3. Confirm that "Create or add a site to see today's/this week's/all time stats." message is shown on the widget

#### 3rd scenario - Log in to an account without any site -> Add Widget -> Create a new site
_As an external contributor I wasn't able to test this scenario due to Public-API limitations_

1. Make sure you are logged in into account without any site
2. Add WordPress "Stats Widget" (All Time / This Week / Today) on the home screen
3. Create a new site on the app
4. Go back to the home screen
5. Confirm that Stats are shown on the widget

#### 4th scenario - Log in to an account without any site -> Add Widget -> Log out:
1. Make sure you are logged in into account without any site
2. Add WordPress "Stats Widget" (All Time / This Week / Today) on the home screen
3. Confirm that "Create or add a site to see today's/this week's/all time stats." message is shown on the widget
4. Log out from the app
5. Confirm that "Log in to WordPress..." message is shown on the widget6. 

#### 5th scenario - Log in into account that has a site -> Remove site

1. Log in into an account that does have a site.
2. Add Stats widgets.
3. Delete the site (via My Site (menu tab selected) > Site Settings > Delete Site).
4. Confirm that "Create or add a site to see today's/this week's/all time stats." message is shown on the widget.

## Regression Notes

1. Potential unintended areas of impact

The other states of the widget

2. What I did to test those areas of impact (or what existing automated tests I relied on)

Retested scenarios in https://github.com/wordpress-mobile/WordPress-iOS/pull/18885

3. What automated tests I added (or what prevented me from doing so)

It may make sense to test `SiteListProviderTests` `getTimelines` as it has a complicated business logic. However, extension unit-testing has limitations and a recommended way would be to have a framework that is used by an extension and test that code instead. 

## Video & Photos

image

https://user-images.githubusercontent.com/4062343/213722741-428984ed-8f4a-448a-bfd1-b2c691cd6d16.mov

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by staskus** [comment]
@sla8c, @guarani this PR was reviewed in https://github.com/wordpress-mobile/WordPress-iOS/pull/18916, however 6 months have passed and there were lots of conflicts so I carefully cherry-picked commit by commit and retested.

There's no urgency to review this PR, nothing depends on it.

File: WordPress/Classes/Stores/StatsWidgetsStore.swift [hunk 1]
```diff
@@ -33,20 +34,22 @@ class StatsWidgetsStore {
...
 
-        if HomeWidgetThisWeekData.read() == nil {
+        if HomeWidgetThisWeekData.read() == nil || HomeWidgetThisWeekData.read()?.isEmpty == true {
             DDLogInfo("StatsWidgets: Writing initialization data into HomeWidgetThisWeekData.plist")
             HomeWidgetThisWeekData.write(items: initializeHomeWidgetData(type: HomeWidgetThisWeekData.self))
             WidgetCenter.shared.reloadTimelines(ofKind: AppConfiguration.Widget.Stats.thisWeekKind)
         }
 
-        if HomeWidgetAllTimeData.read() == nil {
+        if HomeWidgetAllTimeData.read() == nil || HomeWidgetAllTimeData.read()?.isEmpty == true {
```
Comment (sla8c) [inline WordPress/Classes/Stores/StatsWidgetsStore.swift]: @staskus this works but I wonder if it would be cleaner here to create a static wrapper function that returns a Bool?  For example `HomeWidgetTodayData.cacheDataExists()` which when done in HomeWidgetData would only have to be implemented once so that the same / similar logic check is not repeated?

**Comment by sla8c** [comment]
@staskus I've tested this + functionality works.  I've made one small comment about the possibility of making a small refactor to remove some code duplication / cleaner -- all in all looks pretty good.  Thanks!

File: WordPress/Classes/Stores/StatsWidgetsStore.swift (hunk 1 above)
Comment (staskus) [reply WordPress/Classes/Stores/StatsWidgetsStore.swift]: Thanks, that's a good idea!

**Review by sla8c — APPROVED** [review]
I've re-tested + all working and thanks for making that small enhancement!  🙇
