### PR TITLE
Reader: Update Reader fetch followed sites to fetch all sites

### LINKED ISSUE #15651: Reader: Following Sites list is incomplete
Not all the sites you follow in the WordPress.com Reader appear in the app. In fact, the number is way lower and I have the impression that the only sites I see on the Reader are WordPress sites with a connected Jetpack account.

### Expected behavior
To see all my followed sites on the Reader, no matter the platform.

### Actual behavior
* I see a smaller number on the app (76) in Reader > Filter > Following if compared to the WordPress.com Reader via browser (200+) [First image]
* I see a different list of sites on Reader > Manage > Followed Sites. The list has more than 76 sites but it's still incomplete.  [Second image]
* While the sites are not visible in the Following section, their posts are still being listed in the Reader

First Image | Second Image
------------ | -------------
Captura de Tela 2021-01-15 às 12 26 19 | Captura de Tela 2021-01-15 às 12 30 07
https://www.atlasobscura.com/ is not on the Following List as well as many other sites | Reader > Manage > Followed Sites. The site http://diariodorio.com/ is not present on Reader > Filter > Following

### Steps to reproduce the behavior
1. Log in to WordPress.com 
2. Go to the Reader
3. Make sure you follow a few non-JP, non-WP sites
4. Take note of the number of sites you follow
5. Go to the WP app and click on Reader
6. Tap the Filter and see the number of sites you're following
7. From the same page, click on Manage > Followed Sites
8. Count the number of sites you see

### Tasks

- [x] Get the same list of followed sites in Reader > Following > Filter as in web [#17173](https://github.com/wordpress-mobile/WordPress-iOS/pull/17173)
- [ ] Get the same list of followed sites in Reader > Settings > Followed Sites

### PR DESCRIPTION
**Pull request by wargcm**
Fixes #15651
WordPressKit PR: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/753

## Description

Previously, the API call was only returning the first page of a user's followed sites. This change adds support for a page parameter and uses that to fetch all the pages at the same time.

## Testing
I found the easiest way to test it is by reducing the page size and adding print statements to the new function when it fetches pages. You can copy this code block to make it easier:

<details><summary>Test code</summary>

```swift
    @objc func fetchAllFollowedSites(success: @escaping () -> Void, failure: @escaping (Error?) -> Void) {
        let service = ReaderTopicServiceRemote(wordPressComRestApi: apiRequest())
        let pageSize: UInt = 5

        service.fetchFollowedSites(forPage: 1, number: pageSize) { totalSites, sites in
            guard let totalSites, let sites else {
                failure(nil)
                return
            }
            let totalPages = Int(ceil(Double(totalSites.intValue) / Double(pageSize)))
            WPAnalytics.subscriptionCount = totalSites.intValue
            print("🟣 fetchAllFollowedSites - Total pages \(totalPages)")

            guard totalPages > 1 else {
                print("🟣 fetchAllFollowedSites - Merging \(sites.count) sites")
                self.mergeFollowedSites(sites, withSuccess: success)
                return
            }

            Task {
                print("🟣 fetchAllFollowedSites - Fetching additional pages")
                await withTaskGroup(of: Result<[RemoteReaderSiteInfo], Error>.self) { taskGroup in
                    for page in 2...totalPages {
                        taskGroup.addTask {
                            return await self.fetchFollowedSites(service: service, page: UInt(page), number: pageSize)
                        }
                    }
                    var allSites = sites
                    for await result in taskGroup {
                        if case .success(let sites) = result {
                            allSites.append(contentsOf: sites)
                        }
                    }
                    print("🟣 fetchAllFollowedSites - Merging \(sites.count) sites")
                    self.mergeFollowedSites(allSites, withSuccess: success)
                }
            }
        } failure: { error in
            failure(error)
        }
    }

    private func fetchFollowedSites(service: ReaderTopicServiceRemote, page: UInt, number: UInt) async -> Result<[RemoteReaderSiteInfo], Error> {
        return await withCheckedContinuation { continuation in
            service.fetchFollowedSites(forPage: page, number: number) { _, sites in
                print("🟣 fetchFollowedSites - finished fetching page \(page)")
                continuation.resume(returning: .success(sites ?? []))
            } failure: { error in
                DDLogError("Error fetching page \(page) for followed sites: \(String(describing: error))")
                continuation.resume(returning: .failure(error ?? FollowedSitesError.unknown))
            }
        }
    }
```

</details>

To test:
- Login to Jetpack
- Navigate to the dashboard or launch the app to it
- 🔎 **Verify** existing start up fetch site calls fetch all your sites
- Navigate to the `Subscriptions` feed in the Reader
- Tap on the `Blogs` chip
- Tap on `Edit`
- 🔎 **Verify** the fetch call fetches all of your sites

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by daniloercoli** [comment]
Hey @wargcm 👋 - I installed this PR by updating from an older one and then navigated to the Reader. As expected, the Subscriptions feed was already selected, since i was already in that feed in the old version of the app. However, despite waiting, the Site pill did not update. Attempting to pull to refresh did nothing. Even force closing the app and restarting it did not resolve the issue.
I had to return to the Discovery feed and then go back to Subscriptions to get the pill updated.

**Comment by daniloercoli** [comment]
On my test account (the one I've shared internally), a couple of sites are not properly displayed in the site selector (see the picture below). When I select one of those sites, I get the "No posts" screen.

Screenshot 2024-03-16 at 11 41 38

I believe the issue involves sites that have an empty title, but i'm not completely sure of that, since when i select them i get the No posts available.
Screenshot 2024-03-16 at 11 42 39

File: WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+                    for page in 2...totalPages {
+                        taskGroup.addTask {
+                            return await self.fetchFollowedSites(service: service, page: UInt(page), number: pageSize)
+                        }
+                    }
+                    var allSites = sites
+                    for await result in taskGroup {
+                        if case .success(let sites) = result {
+                            allSites.append(contentsOf: sites)
+                        }
```
Comment (dvdchr) [inline WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift]: Hmm, I'm wondering what we should do if errors occur within `2...totalPages`. Currently, the errors are ignored, and this may lead to missing sites from the followed blogs list despite the successful result. But I'm not sure myself how we should address this without making it overly complicated... 😅 

Some ideas: we could store the failed page numbers to retry. But in case of network errors, it could very well throw the user into a loop of multi-requests, especially considering that `fetchAllFollowedSites` are getting called multiple times after the app launches.

Anyways, it's still better than just fetching the first page! 😄

**Comment by dvdchr** [comment]
Thank you for the test code! I tested it several times and found it works quite reliably. 👏 

I modified the test prints a bit so that it prints out the amount of `allSites` at line 41:

```swift
print("🟣 fetchAllFollowedSites - Merging \(allSites.count) sites")
```

I saw 2 missing blogs; the UI shows 107 but the API returns 109. Perhaps they're P2s or private sites? 🤔 

Screenshot 2024-03-19 at 03 19 58

**Review by dvdchr — APPROVED** [review]

File: WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift (hunk 1 above)
Comment (daniloercoli) [reply WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift]: On Android, we're clearing the local sites list and replacing it with new sites fetched from the remote server. To keep the logic straightforward in this initial iteration, we've assumed that a network calls chain is successful only if all paged network calls are completed successfully. At the conclusion of the last call, we consider it a success, store the results locally, and emit an event to update the UI. If an issue arises in any of the calls, the entire chain is marked as a failure, and the local sites are NOT updated. 

I suggest keeping the logic as simple as possible. Imagine you have 100+ sites in the app. The Sites pill indicates 100+ sites, and at some point, you perform a pull to refresh, or the app updates the sites upon opening the Reader. If an error occurs during a middle call, you will see fewer sites than before without a clear explanation.

Comment (wargcm) [reply WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift]: I'll update it to fail if one of the pages doesn't succeed. It'll just use the first error we encounter. Updated in: https://github.com/wordpress-mobile/WordPress-iOS/pull/22842/commits/648e6cf256bfe98e0a3cd2c0786bc461a8af2717.

Which error does Android use if multiple of the calls fail? I could see the logic getting pretty complicated if we tried to take each into account.

**Comment by wargcm** [comment]
> I installed this PR by updating from an older one and then navigated to the Reader. As expected, the Subscriptions feed was already selected, since i was already in that feed in the old version of the app. However, despite waiting, the Site pill did not update. Attempting to pull to refresh did nothing. Even force closing the app and restarting it did not resolve the issue.
I had to return to the Discovery feed and then go back to Subscriptions to get the pill updated.

This is a separate issue with the chip not updating and is being addressed in: https://github.com/wordpress-mobile/WordPress-iOS/pull/22829.

> On my test account (the one I've shared internally), a couple of sites are not properly displayed in the site selector (see the picture below). When I select one of those sites, I get the "No posts" screen.

We've noticed this sometimes occurs too, but we aren't sure why either. It's an existing issue that should be unrelated to these changes. We could probably add some sort of filter to that list to remove the empty sites, but I'm not sure if we ever run into a scenario where one of those empty sites actually has content. If we did, then hiding them wouldn't be ideal because then the user wouldn't be able to individually view that site.

File: WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift (hunk 1 above)
Comment (daniloercoli) [reply WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift]: Similarly on Android, we log the first error encountered, even though we don't actually propagate the error to the UI.
```
            public void onErrorResponse(VolleyError volleyError) {
                AppLog.e(AppLog.T.READER, volleyError);
                serverBlogs.clear();
                taskCompleted(UpdateTask.FOLLOWED_BLOGS);
            }
```

**Comment by dvdchr** [comment]
Heads up: with https://github.com/wordpress-mobile/WordPress-iOS/pull/22842/commits/259c480a2284dcb86a8c8cfcc065aecceeea4890 I've updated the `WordPressKit` dependency to point to https://github.com/wordpress-mobile/WordPressKit-iOS/commit/c2a51c232a7c589d3bcf4ade75232d2338582e64 now that https://github.com/wordpress-mobile/WordPressKit-iOS/pull/753 is merged.

Since it's been pre-approved before, I'll set this PR on auto-merge on behalf of @wargcm.
