### PR TITLE
Change the background colors for badge notifications in dark mode.

### LINKED ISSUE #15323: Dark mode UI on "follow" notifications looks unpolished
### Expected behavior
I expected the one shade of gray/black for the full screen

### Actual behavior

Ea3KXDrWsAM8Pn2

### Steps to reproduce the behavior
Get a follow count notification on dark mode and tap through the notification

##### Tested on [device], iOS [version], WPiOS [version]
Not sure, I found this screenshot on Twitter https://twitter.com/Proudlyblog/status/1273896774185467904?s=20

### PR DESCRIPTION
**Pull request by emilylaguna**
Fixes #15323

I confirmed with @mbshakti that the light mode should display a white background still. 

### Screenshots

| Light Mode | Dark Mode |
|:---:|:---:|
|||

### To test:
1. Launch the app
2. Tap on the Notifications Tab
3. Locate a "badge" notification such as Jetpack Scan Threat, Anniversary Badge, Number of likes on a blog

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by leandroalonso — APPROVED** [review]
@emilylaguna @mbshakti the PR works as described, but I have to say that the light version seems a lot more "unpolished" to me than the dark version (which has a low contrast between the colors).

Can't we just remove the background from both versions? I guess this will also make the code simpler.

**Comment by emilylaguna** [comment]
@leandroalonso @mbshakti Based on the feedback I got from Shakti, I updated the view so the entire background is white. 

| iPhone | iPad |
|:---:|:---:|
||Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-12-16 at 09 53 01|

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift [hunk 1]
```diff
@@ -11,7 +11,11 @@ class NoteBlockTableViewCell: WPTableViewCell {
     ///
     /// - Note: After setting this property you should explicitly call `refreshSeparators` from within `UITableView.willDisplayCell`.
     ///
-    @objc var isBadge = false
+    @objc var isBadge = false {
+        didSet {
+            separatorsView.backgroundColor = WPStyleGuide.Notifications.blockBackgroundColorForRichText(isBadge)
```
Comment (leandroalonso) [inline WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift:16]: Why do we need that?

Comment (emilylaguna) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift:16]: The default background color for the table cell is `.listForeground` which results in the gray background colors in dark mode and the badge background color is clear. So this resets all the cells to have a clear background when they're badges.

Comment (emilylaguna) [reply WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTableViewCell.swift:16]: And since the `separatorsView` is set to the backgroundView for the cell we need to change its color instead of of the cells backgroundColor
