### PR TITLE
NoteTableViewCell: Fixing gravatar caching glitch

### LINKED ISSUE #4858: Gravatars caching oddly in Notifications
Scrolling around in the notifications screen in develop I'm noticing that the gravatars aren't being cached properly. Table view cell reuse seems to be not working right and gravatars from other rows end up showing on the wrong rows. Here's a video to demonstrate:

https://cloudup.com/cT53tcP9bTG
I keep scrolling back up to the top to show how where my face originally was there it gets swapped out with other gravatars depending on how far I scroll down.

cc: @jleandroperez

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #4858

To test:
1. Launch WPiOS and log into (YOUR `ardwptest1` Test Account, Aaron)
2. Open the Notifications Tab
3. Verify that the Gravatars don't get mixed

Needs review: @astralbodies 
Thanks in advance Aaron (+ thanks for lending me the buggy test account!!)

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift [hunk 1]
```diff
@@ -89,7 +89,14 @@ import WordPressShared
         
         // Handle non-gravatar images
         let placeholderImage = Style.blockGravatarPlaceholderImage(isApproved: !unapproved)
-        iconImageView.downloadImage(url, placeholderImage: placeholderImage)
+        iconImageView.downloadImage(url, placeholderImage: placeholderImage, success: nil, failure: { (error) in
+            // Note: Don't cache 404's. Otherwise Unapproved / Approved gravatars won't switch!
+            if self.gravatarURL?.isEqual(url) == true {
+                self.gravatarURL = nil
```
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift]: Is it possible that a race condition exists here? Doubtful things could happen that fast of course. :smile:

**Comment by astralbodies** [comment]
This seems to solve it! 

Any particular reason we're not resetting any of the properties (like `gravatarUrl`) in `prepareForReuse`?

File: WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift (hunk 1 above)
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Notifications/Views/NoteTableViewCell.swift]: No risk on this one, since the callback and `gravatarURL` assignment (few lines below) both happen on the Main Thread, always. Otherwise UIKit would get annoyed.

Thanks for checking!!

**Comment by jleandroperez** [comment]
Reason why `prepareForReuse` isn't wired on this one, is that all of the properties are really set for every new row (there's no conditional that prevents any set call).

Plus, several notifications might have the exact same gravatar. Avoiding `prepareForReuse` calls there improves performance slightly, since we're not clearing / re-loading the images over and over.

Thanks!!!

**Comment by astralbodies** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thank you Aaron!
