### PR TITLE
Fix field for category creation.

### LINKED ISSUE #8294: Unable to create new category while editing a post
### Expected behavior

When I tap to create a new category inside the category selection it should allow to create a new category

### Actual behavior

Even with the field filled correctly it show the following message:

img_0221

### Steps to reproduce the behavior

- Start the app
- Create a new post on a blog
- Tap on the ellipsis 
- Select post options
- Select Category
- Tap on the + to add a new category
- Give it a name
- Tap on save

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #8294 

To test:
 - Start the app
 - Create a new post
 - Tap on the ellipsis button
 - Tap on the Options option
 - Tap on Category
 - Tap on the + 
 - Give a name to the category
 - Tap on save
 - Check that it saves correctly.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m [hunk 1]
```diff
@@ -194,7 +193,7 @@ - (WPTextFieldTableViewCell *)createCategoryCell
     _createCategoryCell.textField.keyboardType = UIKeyboardTypeDefault;
     _createCategoryCell.textField.secureTextEntry = NO;
     _createCategoryCell.textField.autoresizingMask = UIViewAutoresizingFlexibleWidth;
-    _createCategoryCell.textField.delegate = self;
+    _createCategoryCell.textField.delegate = self;
```
Comment (jklausa) [inline WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m]: @SergioEstevao tiny nitpick: extra whitespace at the end of the line here
