### PR TITLE
Issues/6324 fix attribute parsing

### LINKED ISSUE #6324: Rich Text: Issue parsing tag attributes when not separated by a space
Props @tellyworth for the report. 
There is an issue parsing tag attributes when the attributes are not separated by a space causing some attributes to be ignored.  In the specific example it was an IMG tag where almost all the attributes were one big run-on string.  The result was the src attribute was overlooked.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #6324 
Its disappointing, but the attribute retrieval using NSScanner isn't going to be robust enough to handle different possible ways attributes can be written in a tag.  This PR switch to regex, using capture groups to retrieve attribute key/value pairs. Less code and less parsing FTW.

To test: 
Follow `flightpathblog.com` and view its stream in the reader.
Confirm the bug by viewing one of the affected photo posts, such as the one titled "Shoes".
Switch to this branch and confirm the fix. 

Needs review: @nheagy could I trouble you with this one?

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift [hunk 1]
```diff
@@ -354,6 +354,7 @@ class ListTagProcessor: HtmlTagProcessor
 class AttachmentTagProcessor: HtmlTagProcessor
 {
     let textAttachmentIdentifier = "WPTEXTATTACHMENTIDENTIFIER"
+    static let attributeRegex = try! NSRegularExpression(pattern: "([a-zA-Z-]+)=(?:\"|')([^\"']+)(?:\"|')", options: .CaseInsensitive)
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift]: Is there a reason to use both `[a-zA-Z]` and `.CaseInsensitive`?

File: WordPress/WordPressTest/WPRichTextFormatterTests.swift [hunk 2]
```diff
@@ -89,4 +89,18 @@ class WPRichTextFormatterTests: XCTestCase {
...
+
+        let str = "<img src=\"http://example.com\" class=\"classname\"alt='alttext'>"
+
+        let processor = AttachmentTagProcessor(tagName: "img", includesEndTag: false)
+
+        let attributes = processor.attributesFromTag(str)
+        XCTAssert(attributes.count == 3)
+        XCTAssert(attributes["src"] != nil)
+        XCTAssert(attributes["alt"] != nil)
+        XCTAssert(attributes["class"] != nil)
```
Comment (nheagy) [inline WordPress/WordPressTest/WPRichTextFormatterTests.swift]: I'd like to see the values tested as well, to ensure they're correct. Thoughts?

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift]: Not really. I included the cap range more out of habit than anything.  Removing :)

**Comment by aerych** [comment]
Thanks @nheagy!  The question about the regex pattern was a good one. The extra cap range wasn't really needed so its good to remove it.  I've updated the tests to check for the correct values, added some emoji for good measure, and added a new test to ensure the attribute key is always lower cased.  Ready for another look sir!

**Comment by nheagy** [comment]
This looks great! :shipit:

**Comment by aerych** [comment]
Thanks @nheagy !!!
