### PR TITLE
Post list preview: trim trailing newline in generated excerpt

### LINKED ISSUE #12673: Gutenberg paragraph shows up as an empty space in Post List
## Expected behavior

2 paragraphs should show up. (Maybe)

## Actual behavior

For Aztec edited posts with hardcoded HTML (below), the Post List shows both paragraphs. 

```html
<p>Paragraph 1</p>
<p>Paragraph 2</p>
```

For Gutenberg, with 2 paragraph blocks and same content, the Post List only shows the first paragraph and with a blank space below. 

### Steps to reproduce the behavior

1. Create a post in Gutenberg.
2. Add 2 paragraph blocks with one-line content.
3. Publish the post.

Tested on iPhone XS, iOS 12.4.1, WP 13.4.0.20191010

### PR DESCRIPTION
**Pull request by YuF-9468**
## Description
Fixes #12673.

This updates post preview generation to trim leading/trailing whitespace and newlines after extracting/collapsing preview text. It prevents preview labels from rendering a trailing blank line in the post list when content contains paragraph separators.

## Testing instructions
1. Create or edit a post with multiple paragraph blocks.
2. Return to the post list.
3. Verify the preview no longer shows an extra blank trailing line/empty space under the first visible line.

### Automated verification
- Added `testThatContentPreviewForDisplayTrimsLeadingAndTrailingNewlines` in `PostTests`.
- CI should run the updated test suite for this PR.

### CODE REVIEW

File: Tests/KeystoneTests/Tests/Models/PostTests.swift [hunk 1]
```diff
@@ -259,6 +259,15 @@ class PostTests: CoreDataTestCase {
         XCTAssertEqual(post.contentPreviewForDisplay(), "some contents\u{A0}go here")
     }
 
+    func testThatContentPreviewForDisplayTrimsLeadingAndTrailingNewlines() {
+        let post = newTestPost()
+
+        post.content = "<p>Paragraph 1</p><p>Paragraph 2</p>"
+        let preview = post.contentPreviewForDisplay()
+
+        XCTAssertEqual(preview, preview.trimmingCharacters(in: .whitespacesAndNewlines))
```
Comment (jkmassel) [inline Tests/KeystoneTests/Tests/Models/PostTests.swift]: This test just validates that the code under test uses the same implementation as the test.

Instead, could we do:


```suggestion
        XCTAssertEqual("expected value of the string", preview)
```

That would be a better test, because we're validating what we want the user to see rather than how the code should accomplish it.

**Review by jkmassel — CHANGES_REQUESTED** [review]
Thanks for taking a look at this! The implementation looks good, I just left a note about improving one test.

I appreciate the contribution, and I'm excited to get it merged!

**Comment by YuF-9468** [comment]
Great call — updated ✅

I changed the test to assert the explicit expected output instead of mirroring implementation details:

- `XCTAssertEqual("Paragraph 1\nParagraph 2", preview)`

Commit: `9f5831e`

**Review by jkmassel — APPROVED** [review]
Thanks for the contribution!
