### PR TITLE
Jetpack Focus: Fix UI issues by removing the `WPTabBarController` dependency

### LINKED ISSUE #19810: Jetpack Focus: Remove Jetpack features during phase 4 on launch
## Details
- [ ]  Remove tab bar
- [ ]  Remove segmented control in My Site
- [ ]  Remove JP features
- [ ]  Disable Quick Start
- [ ]  Remove irrelevant settings

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Closes #19810
Part of #19812

## Description
In the simplified UI, we no longer display a WPTabBarController. However, many areas of the app depend on `WPTabBarController.sharedInstance` to perform some actions. In this PR, we completely remove this dependency and instead depend on the newly added `RootViewCoordinator`. By doing so, all issues in the simplified UI that were present in #19816 should be fixed.

The PR touches many parts of the app, but most changes are systematic.

## ⚠️ Disclaimer ⚠️ 
Some Jetpack features are still accessible from external sources, like deep linking, widgets, and the 3D touch menu. This will be addressed in a following PR.
Also, blogging reminders and weekly roundups are still not disabled.

## Testing Instructions
This PR touches many areas of the app. Therefore there aren't specific testing instructions. Instead, please smoke test the following areas, both in the normal app state and in the simplified UI state (if applicable):
- Login flows
- Sign-in flows
- Site creation flow
- Interacting with push notifications
- Spotlight search (From outside the app)
  - Opening app settings
  - Opening a published post
  - Opening a draft post
  - Opening Reader/Notifications
- 3D touch menu
- Reader
- What's new announcement (Check #18231 for testing steps)
- Creating a post/page/story from the floating button
- Creating a post/page from the floating button in the posts/pages list view
- Blogging prompts

To get to the normal app state, open the debug menu and disable all the Jetpack Features Removal flags. Then kill and relaunch the app.
To get to the simplified UI state, open the debug menu and enable "Jetpack Features Removal Phase Four". Then kill and relaunch the app.

## Regression Notes
1. Potential unintended areas of impact
Mentioned above.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/System/RootViewPresenter+MeNavigation.swift [hunk 1]
```diff
@@ -1,32 +1,32 @@
-
 import UIKit
 
 /// Methods to access the Me Scene and sub levels
-extension WPTabBarController {
+extension RootViewPresenter {
```
Comment (staskus) [inline WordPress/Classes/System/RootViewPresenter+MeNavigation.swift:4]: Nice, refactored cleanly 👍

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift [hunk 2]
```diff
@@ -3,9 +3,9 @@ import Foundation
 /// `MySitesCoordinator` is used as the root presenter when Jetpack features are disabled
 /// and the app's UI is simplified.
 extension MySitesCoordinator: RootViewPresenter {
-
```
Comment (staskus) [inline WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift]: `rake git:install_hooks` as described in [README](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/README.md) should allow avoid this before the commit.

File: WordPress/Classes/Utility/Spotlight/SearchManager.swift [hunk 3]
```diff
@@ -431,30 +431,31 @@ fileprivate extension SearchManager {
...
+        RootViewControllerCoordinator.sharedPresenter.rootViewController.present(editor, animated: true)
     }
 
     func openEditor(for page: Page) {
         closePreviewIfNeeded(for: page)
         openListView(for: page)
 
         let editorViewController = EditPageViewController(page: page)
-        WPTabBarController.sharedInstance().present(editorViewController, animated: false)
+        RootViewControllerCoordinator.sharedPresenter.rootViewController.present(editorViewController, animated: false)
```
Comment (staskus) [inline WordPress/Classes/Utility/Spotlight/SearchManager.swift]: I'm thinking if we should really expose `rootViewController` from the `RootViewPresenter`.

Maybe we should hide it under the presenter interface `RootViewControllerCoordinator.sharedPresenter.present(...)`?

I understand it may be a bit problematic since I see that there're places where we access `rootViewController` directly, for example:

```swift
@objc func showAppUI(for blog: Blog? = nil, completion: Completion? = nil) {
    isShowingFullscreenSignIn = false
    show(RootViewCoordinator.sharedPresenter.rootViewController, completion: completion)
<...>
```

but since we're using a presenter here, maybe such places should be looking like this:

```swift
@objc func showAppUI(for blog: Blog? = nil, completion: Completion? = nil) {
    isShowingFullscreenSignIn = false
    RootViewCoordinator.sharedPresenter.showAppUI(on: self)
<...>
```

What are your thoughts? Did you encounter any problems by exposing `rootViewController`?

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift [hunk 4]
```diff
@@ -4,4 +4,116 @@ import Foundation
...
+        fallbackBehavior()
+    }
+
+    func showReaderTab(forPost: NSNumber!, onBlog: NSNumber!) {
+        fallbackBehavior()
+    }
+
+    // MARK: My Site
+
+    var mySitesCoordinator: MySitesCoordinator! {
```
Comment (staskus) [inline WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift]: As I understand it's only needed because `WBTabBarController` does not have `nullability` identifiers? If yes, then I agree that `WPTabBarController` improvements are outside the scope.

```suggestion
    var mySitesCoordinator: MySitesCoordinator {
```

File: WordPress/Classes/Utility/Universal Links/Routes+Reader.swift [hunk 5]
```diff
@@ -62,7 +62,8 @@ extension ReaderRoute: Route {
 
 extension ReaderRoute: NavigationAction {
     func perform(_ values: [String: String], source: UIViewController? = nil, router: LinkRouter) {
-        guard let coordinator = WPTabBarController.sharedInstance().readerCoordinator else {
+        guard let tabBarController = RootViewControllerCoordinator.sharedPresenter.rootViewController as? WPTabBarController,
+              let coordinator = tabBarController.readerCoordinator else {
```
Comment (staskus) [inline WordPress/Classes/Utility/Universal Links/Routes+Reader.swift]: Could `readerCoordinator` be part of `RootViewPresenter` protocol? We already have `Reader` section there. It could return `nil` same way as `readerTabViewController`.

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift [hunk 6]
```diff
@@ -297,7 +297,10 @@ class NotificationsViewController: UIViewController, UIViewControllerRestoration
 
     static func viewController(withRestorationIdentifierPath identifierComponents: [String],
                                coder: NSCoder) -> UIViewController? {
-        return WPTabBarController.sharedInstance().notificationsViewController
+        guard let tabBarController = RootViewControllerCoordinator.sharedPresenter.rootViewController as? WPTabBarController else {
+            return nil
+        }
+        return tabBarController.notificationsViewController
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Same suggestion as with `readerCoordinator`, for the sake of consistency I think it makes sense to move it to `RootViewPresenter` interface. 

We'll clearly see the differences between the 2 implementations, additionally, we could track when the app tries to access the variable unexpectedly, same way we track in the `fallback` methods.

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift [hunk 7]
```diff
@@ -144,7 +144,10 @@ class ReaderDetailViewController: UIViewController, ReaderDetailView {
     /// allowing Reader Detail to use a blue navbar.
     var useCompatibilityMode: Bool {
         // Use compatibility mode if not presented within the Reader
-        return WPTabBarController.sharedInstance().readerNavigationController.viewControllers.contains(self) == false
+        guard let tabBarController = RootViewControllerCoordinator.sharedPresenter.rootViewController as? WPTabBarController else {
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift]: Same comment as mentioned above with accessing `WPTabBarController?` directly

File: WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift [hunk 8]
```diff
@@ -519,7 +519,8 @@ extension SiteStatsInsightsTableViewController: SiteStatsInsightsDelegate {
 
             self.navigationController?.popToRootViewController(animated: false)
             RootViewControllerCoordinator.sharedPresenter.showReaderTab()
-            if let nc = WPTabBarController.sharedInstance().selectedViewController as? UINavigationController,
+            if let tabBarController = RootViewControllerCoordinator.sharedPresenter.rootViewController as? WPTabBarController,
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift]: Same comment as mentioned above with accessing `WPTabBarController?` directly

File: WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+OnboardingPrompt.swift [hunk 9]
```diff
@@ -21,9 +21,9 @@ extension MySiteViewController {
             }
         case .writing:
             // Open the editor
-            let controller = tabBarController as? WPTabBarController
-            controller?.showPostTab(completion: {
-                self.startAlertTimer()
+            let presenter = RootViewControllerCoordinator.sharedPresenter
+            presenter.showPostTab(completion: { [weak self] in
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+OnboardingPrompt.swift:25]: 👍 Good catch

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift [hunk 10]
```diff
@@ -111,9 +112,8 @@ extension MySitesCoordinator: RootViewPresenter {
     // MARK: Helpers
 
     /// Default implementation for functions that are not supported by the simplified UI.
-    private func fallbackBehavior() {
-        // TODO: Consider showing an overlay
-        // TODO: Print a log statement
-        // TODO: Consider tracking this
+    private func fallbackBehavior(callingFunction: String = #function) {
+        let properties = ["calling_function": callingFunction]
```
Comment (staskus) [inline WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift:132]: 👍

**Review by staskus — COMMENTED** [review]
👏 a clean refactoring, thanks! I appreciate splitting the PR into small and clear commits, much easier to review. 

For most part, it looks like 1 to 1 change from directly accessing VC to accessing VC through a `RootViewCoordinator` so it increases confidence in solution, even with so many changes. I haven't seen any major flaws looking from the code side. 

I left some comments and questions and moving on to a smoke testing.

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift (hunk 2 above)
Comment (hassaanelgarem) [reply WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift]: I actually have the hooks installed. What happened here was I ran the lint autocorrect command but forgot to stage its changes. That's why the commit went through. Thanks for pointing this out, though! ❤️

File: WordPress/Classes/Utility/Spotlight/SearchManager.swift (hunk 3 above)
Comment (hassaanelgarem) [reply WordPress/Classes/Utility/Spotlight/SearchManager.swift]: I agree that this would be better. However, it will be tricky to make it work in some places like `ReplyTextView.btnEnterFullscreenPressed`, for example.

I'll have a go at this later on and include it in another PR if I reach something 👍

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift (hunk 4 above)
Comment (hassaanelgarem) [reply WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift]: > As I understand it's only needed because WBTabBarController does not have nullability identifiers?

That's correct, yes. After some thought, though, I believe it's worth it to add nullability identifiers to `WBTabBarController`. Adding nullability identifiers also allows us to include variables like `readerCoordinator` in `RootViewPresenter`. (Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/19817#discussion_r1058950919) 

Updated in fb960a3a0d8fb5d5390ee2911d8eb9425d1c8a45, f03e6c240341e14b357c14414fb8de8cf0f6781a, and 9b95aa5bb01290a9ebe39532ed52bfc27962c3a0 👍

File: WordPress/Classes/Utility/Universal Links/Routes+Reader.swift (hunk 5 above)
Comment (hassaanelgarem) [reply WordPress/Classes/Utility/Universal Links/Routes+Reader.swift]: Done in 5a442959943a47db48d6f282f6c4a8a6937e6764 👍

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift (hunk 6 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift]: Done in f3f2794f217e75a2c479eb98b7e77ccca5276c60. And tracking is added in c17f29e324079c82b23da1b0f1fc28c100fd41fc 👍

File: WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift (hunk 7 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift]: Done in d8978105f0e302436aa4afe7ffea5f4123c76ebf 👍

File: WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift (hunk 8 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift]: Done in e619798f281ec0481b75fe5d1801c02d71f72018 👍

File: WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift (hunk 4 above)
Comment (staskus) [reply WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift]: Thanks for including the nullability identifiers, I'll check the changes!

File: WordPress/Classes/Utility/Spotlight/SearchManager.swift (hunk 3 above)
Comment (staskus) [reply WordPress/Classes/Utility/Spotlight/SearchManager.swift]: Okay, I see. There're many cases that complicate the removal of `rootViewController` from the interface.

I agree, let's leave it outside the scope of this PR 👍.

File: WordPress/Classes/ViewRelated/System/WPTabBarController.h [hunk 11]
```diff
@@ -21,27 +23,19 @@ extern NSNotificationName const WPTabBarHeightChangedNotification;
...
 @interface WPTabBarController : UITabBarController <UIViewControllerTransitioningDelegate>
 
-@property (nonatomic, strong, readonly) NotificationsViewController *notificationsViewController;
-@property (nonatomic, strong, readonly) UINavigationController *readerNavigationController;
-@property (nonatomic, strong, readonly) MySitesCoordinator *mySitesCoordinator;
-@property (nonatomic, strong, readonly) ReaderCoordinator *readerCoordinator;
-@property (nonatomic, strong, readonly) BloggingPromptCoordinator *bloggingPromptCoordinator;
+@property (nonatomic, strong, readonly, nullable) NotificationsViewController *notificationsViewController;
+@property (nonatomic, strong, readonly, nullable) UINavigationController *readerNavigationController;
+@property (nonatomic, strong, readonly, nullable) MySitesCoordinator *mySitesCoordinator;
```
Comment (staskus) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.h]: By looking at the implementation of `RootViewPresenter` in  `WPTabBarController.m` and `MySitesCoordinator` I think it could be `nonnull.` 

```suggestion
@property (nonatomic, strong, readonly, nonnull) MySitesCoordinator *mySitesCoordinator;
```

**Review by staskus — APPROVED** [review]
Looks good to me 🚀 👏

I smoke tested described scenarios on WP and JP apps with iPhone, iPad and with feature flags enabled and disabled. I also clicked around all the different menu items but I couldn't find a scenario where the views wouldn't open or open in an unexpected way.

I'm leaving one remaining comment about `nullable` vs `nonnull`. Other than that, I think it's worth waiting for at least a second review to have more confidence that I haven't missed any critical scenario.

File: WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift [hunk 12]
```diff
@@ -8,7 +8,7 @@ struct NotificationsRoute: Route {
 
 struct NotificationsNavigationAction: NavigationAction {
     func perform(_ values: [String: String], source: UIViewController? = nil, router: LinkRouter) {
-        WPTabBarController.sharedInstance().showNotificationsTab()
-        WPTabBarController.sharedInstance().popNotificationsTabToRoot()
+        RootViewCoordinator.sharedPresenter.showNotificationsTab()
+        RootViewCoordinator.sharedPresenter.popNotificationsTabToRoot()
```
Comment (dvdchr) [inline WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift:12]: Does phase four include disabling route handlers that lead to Jetpack-powered features? With the feature flag enabled, triggering a universal link for a Jetpack feature leads to `MySitesCoordinator.fallbackBehavior()`.

**Review by dvdchr — COMMENTED** [review]
The changes look good, and I haven't encountered any issues. But I did have some notes:

- When logged in to a WP.com account, there's still the Jetpack-powered banner in the Me screen. Is this intended?
- I also noticed that with phase four removal enabled, the WP app still "supports" universal link — it doesn't lead anywhere since the `MySitesCoordinator`one is used as the root presenter instance, but it'll trigger the `jetpackFeatureIncorrectlyAccessed` analytics. 

  I'm assuming that you're setting up the analytics as some alarm or detection mechanism in case there are unhandled entry points to Jetpack features. Still, since the issue is now identified, I wonder if we should handle it here 🤔 . Then again, I'm not sure if this is already planned for a separate PR, so just let me know if you've already planned for it! 🙂

**Comment by hassaanelgarem** [comment]
> When logged in to a WP.com account, there's still the Jetpack-powered banner in the Me screen. Is this intended?

@dvdchr We're still in discussion on whether to remove it or not. I'll remove it in a separate PR if we ultimately decide to remove it. (Ref: p1672272774859159-slack-C04564QS0V7)

> I also noticed that with phase four removal enabled, the WP app still "supports" universal link — it doesn't lead anywhere since the MySitesCoordinator one is used as the root presenter instance, but it'll trigger the jetpackFeatureIncorrectlyAccessed analytics.

I'm working on another PR related to this point. Right now, some Jetpack-powered deep links are still functional. For example, if you open a stats deep link, it will show the stats page. I'm working on a PR that'll disable those.

However, for all unsupported deep links, it will open the app and trigger the `jetpackFeatureIncorrectlyAccessed` event. To completely drop support of Jetpack deep links, we'll have to modify the [apple-app-site-association file](https://wordpress.com/.well-known/apple-app-site-association). But I believe this should be done after the Jetpack Focus project is complete.

File: WordPress/Classes/ViewRelated/System/WPTabBarController.h (hunk 11 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/System/WPTabBarController.h]: I agree. Updated in 1af613bc6594f9fd0b845188dd597a727ec6c73c 👍

**Comment by dvdchr** [comment]
Sounds good @hassaanelgarem. Thanks for elaborating! 👍🏼
