### PR TITLE
Issue/4098 app crashes when editing title after uploading video

### LINKED ISSUE #4098: App crashes when changing post title after uploading a video
Reported by a user. Title basically has it. Steps to repro:

1. type in title
2. upload video
3. try to change title
4. 4-6 keystrokes later, app freezes
5. close app, reopen
6. app crashes

User followed up with:
> I saved it to draft and then tried to edit the title, and the same stuff happens. :)

/cc @SergioEstevao

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #4098 

First it looked like the problem was in the webview handling of videos and the multiple refreshs around it. After some fixes on the javascript side the error was still happening but in a lesser degree. 
After some more digging I found out that our PrivateSiteURLProtocol, used to allows to view images/media on private sites, was the root cause of the problem because it was flooding the main queue with requests. 
This was more evident with video because when it was loaded on the web view a lot of requests where made in order to pre-cache the video, while with images only a single request goes out for each image.

There was also a related error on the media picker code , that could cause a crash when adding images from the media library making it even more fun to found the root cause of the error.

Needs Review: @bummytime

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m [hunk 1]
```diff
@@ -33,13 +36,19 @@ + (void)unregisterPrivateSiteURLProtocol
...
+        return NO;
     }
-    return NO;
+    if (![self requestGoesToWPComSite:request]){
+        return NO;
+    }
+    if (![self bearerToken]) {
+        return NO;
+    }
+    NSLog(@"I will load this using my token:%@", request.URL);
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m]: Probably should remove this.

**Comment by bummytime** [comment]
Nice work @SergioEstevao...Let's do this. :shipit:
