### PR TITLE
Fix Quick Start 'Follow other sites' tour

### LINKED ISSUE #13068: Quick Start: "Follow other sites" tour never completes
### Expected behavior

I expect that when I get to the Grow Your Audience > Follow other sites tour in Quick Start, it will walk me through how to find and follow sites.

### Actual behavior

The tour gets stuck on the "Tap < Reader to continue" step.

### Steps to reproduce the behavior

1. Create a new site in the app.
2. Accept the Quick Start help.
3. In the My Sites > Next Steps section, select "Grow Your Audience."
4. Select the "Follow other sites" tour.
5. When you see the step "Tap Reader to continue" tap the Reader icon in the bottom nav.
6. When you see the step "Tap < Reader to continue" tap `< Reader` in the top left (although notice that this isn't highlight with a blue dot like in other steps).
7. Notice that the "Tap < Reader to continue" hint never goes away, and there's no instructions about what to do next.
8. Go back to the My Sites tab and notice that the hint still doesn't go away.
9. Open "Grow Your Audience" again and notice that the "Follow other sites" tour is still incomplete.

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #13068 

In iOS13, `ManyDelegateNavigationController` no longer worked, causing `tourGuide.visited(.readerBack)` to not be called. Meaning the tour was never notified the readerBack step was completed.

To fix this:
- `ManyDelegateNavigationController` has been removed.
- `QuickStartNavigationWatcher` is now `QuickStartNavigationSettings`, and is no longer a `UINavigationControllerDelegate`.
- `QuickStartNavigationSettings` is updated in `WPSplitViewController`'s `navigationController:willShow`.

To test:
- Follow the repro steps noted on #13068 . (Thank you @rachelmcr for excellent repro steps.)
  - Hack: you can show the tour checklist by returning `true` in `QuickStartTourGuide:shouldShowChecklist`.
- Verify:
  - After tapping the Reader tab, the nav bar button `< Reader` is spotlighted.
    - In split view (like on an iPad) `< Reader` is not shown, so this step is skipped (this is existing functionality).
  - The `Tap < Reader to continue` hint is dismissed.
  - When you finish the tour (i.e. by tapping Reader > Search) the tour is marked as complete.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/WPSplitViewController.swift [hunk 1]
```diff
@@ -14,6 +14,8 @@ import WordPressShared
 
 class WPSplitViewController: UISplitViewController {
 
+    private let quickStartNavigationSettings = QuickStartNavigationSettings()
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/System/WPSplitViewController.swift]: In an ideal world, WPSplitViewController wouldn't need to know anything about quick start settings (hence the previous implementation), but as that's not working any more and there's a chance we may revisit WPSplitViewController in the not too distant future I think this is okay for now.
