### PR TITLE
Reader Improvements: Fix Discover indefinite ghost mode

### LINKED ISSUE #14660: Reader Cards: Discover gets stuck in ghost mode indefinitely
### Steps to reproduce the behavior
1. Load the new discover view
2. Scroll down to the next page
3. Tap on a topic
4. Tap back

### Expected behavior
The view should show the posts that were previously visible

### Actual behavior
The view gets stuck in the ghost mode until switching tabs

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Simulator 13.3

### PR DESCRIPTION
**Pull request by emilylaguna**
Fixes #14660

### To test:
1. Run the app with the Reader Improvements Phase 2 flag enabled
2. Tap on the Reader tab
3. Tap on the Discover tab
3. Scroll down a few posts
4. Tap on a topic at the top of a post
5. Wait for it to load
6. Tap back

**Expectation:** The app displays the posts that were there before

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift [hunk 1]
```diff
@@ -100,6 +103,10 @@ class ReaderCardsStreamViewController: ReaderStreamViewController {
         })
     }
 
+    override var topicPostsCount: Int {
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift:106]: After messing around with the ReaderStream and headers, tags, site topics, tag topics I realize even more the importance of simple naming so could this just be numberOfCards or cardsCount?

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift [hunk 2]
```diff
@@ -915,13 +915,23 @@ import WordPressFlux
...
+        if canSync() && (interval >= refreshInterval || topicPostsCount == 0) {
             syncHelper?.syncContentWithUserInteraction(false)
         } else {
             handleConnectionError()
         }
     }
 
+    /// Returns the number of posts for the current topic
+    /// This allows the count to be overriden by subclasses
+    var topicPostsCount: Int {
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift:928]: No need to change necessarily but could have also been a one liner :
`return readerTopic != nil ? readerTopic!.posts.count : 0`

**Comment by yaelirub** [comment]
@emilylaguna , good work here. 
Unrelated to this PR but needs to be discussed: is this really how the discover page going to look like before you scroll or is this just testing data:
Simulator Screen Shot - iPhone 11 Pro - 2020-08-17 at 18 38 05

We should limit the number of interests suggestions to a fixed number of rows so that the user will see the next card on the screen before scrolling.

**Comment by emilylaguna** [comment]
> Unrelated to this PR but needs to be discussed: is this really how the discover page going to look like before you scroll or is this just testing data:

This is coming directly from the server itself. The count changes sometimes, I think they're still working on the related interests code.

File: WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift (hunk 2 above)
Comment (emilylaguna) [reply WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift:928]: Makes sense, although I'm not a fan of the force unwrapping. I would change it to just:

`return readerTopic?.posts.count ?? 0`

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift:927]: lol great!
