### PR TITLE
ContextManager: wrap context mergeChanges with a fault protection method

### LINKED ISSUE #6748: CoreData Crash: crashing between writer context and mainContext
The top crash for WPiOS right now looks to involve an issues between our new `writerContext` and `mainContext` saving implementation introduced in: https://github.com/wordpress-mobile/WordPress-iOS/pull/6098

It's not entirely clear what's going on, and I've been trying to figure it out for a good bit. Leaving it alone for now, will loop back around with fresh(er) eyes.

cc @jleandroperez 

Example stack, although a bit different between crash logs:
```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1817aee38 __exceptionPreprocess
1  libobjc.A.dylib                0x180e13f80 objc_exception_throw
2  CoreData                       0x18361eab8 -[NSSQLCore _availableChannel]
3  CoreData                       0x18364ae6c -[NSSQLCore saveChanges:]
4  CoreData                       0x1836161b0 -[NSSQLCore executeRequest:withContext:error:]
5  CoreData                       0x1836ddd68 __65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke
6  CoreData                       0x1836e5d64 gutsOfBlockToNSPersistentStoreCoordinatorPerform
7  CoreData                       0x1836d85d4 _perform
8  CoreData                       0x183615d5c -[NSPersistentStoreCoordinator executeRequest:withContext:error:]
9  CoreData                       0x18363a510 -[NSManagedObjectContext save:]
10 WordPress                      0x1000baa34 -[ContextManager internalSaveContext:] (ContextManager.m:294)
11 WordPress                      0x1000ba8ac __37-[ContextManager mainContextDidSave:]_block_invoke (ContextManager.m:278)
12 CoreData                       0x1836ad08c developerSubmittedBlockToNSManagedObjectContextPerform
13 libdispatch.dylib              0x1811f947c _dispatch_client_callout
14 libdispatch.dylib              0x1812054c0 _dispatch_queue_drain
15 libdispatch.dylib              0x1811fcf80 _dispatch_queue_invoke
16 libdispatch.dylib              0x1811f947c _dispatch_client_callout
17 libdispatch.dylib              0x181207914 _dispatch_root_queue_drain
18 libdispatch.dylib              0x1812070b0 _dispatch_worker_thread3
19 libsystem_pthread.dylib        0x181411470 _pthread_wqthread
20 libsystem_pthread.dylib        0x181411020 start_wqthread
```

### PR DESCRIPTION
**Pull request by kurzee**
Fixes #6748 (I hope)

This is a calculated attempt of a fix for our top crash in Fabric consisting of internal inconsistency issues in CoreDate while trying to save our `writerContext`. Writing this up in detail for posterity.

```
ContextManager.m line 294
-[ContextManager internalSaveContext:]
```
The idea is that looking at the session logs of these crashes, almost every crash occurs after launching the app or returning from the background, such as shortly after `<WordPressAppDelegate:applicationDidBecomeActive:`.

Additionally, almost every stack trace has a Reader stack that follows a call to save the main context which generates subsequent notifications of `NSManagedObjectContextDidSaveNotification` landing on:

- https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift#L1370

And later we land on a different thread for the `writerContext`, which fires off it's own `internalSaveContext` and can crash along the way, generating the crash reports we're seeing:
- https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/ContextManager.m#L273

But why is this crashing? I was considering that maybe a faulting issue was occurring when the user is returning to the app and Reader object models are faulted, breaking things along the way. @aerych speculated something similar in https://github.com/wordpress-mobile/WordPress-iOS/issues/6757#issuecomment-282364294

Doing a little Googling: http://www.mlsite.net/blog/?p=518, there seems to be old cases in which merging objects after a context save notification can result in issues with object faults. Bingo.

That said, I propose we roll with a new wrapper method for merging objects in contexts, like we do here in Reader, to try and avoid this crash case. I'm not 100% confident this is the fix and there isn't a more sinister issue here, but it's a shot.

To test:
1. Open Reader, open Notifications that end in Reader streams.
2. Background, foreground, kill, restore.
3. Try and find generate a case of merging with faults, I had no luck.

Needs review: @aerych 

Also cc @astralbodies since you dug into this a bit before.

### CODE REVIEW

**Comment by astralbodies** [comment]
Also lets get @jleandroperez to take a look too.

**Comment by aerych** [comment]
Hiya @kurzee 
Code looks spot on and no problems testing.  I wasn't able to reproduce the original issue but its a tricky one so I'm not too surprised.  :shipit: pending @jleandroperez's review.

**Comment by astralbodies** [comment]
@aerych I won't have time to review this before cutting 7.1 this morning but I'm okay with us bringing it into the 7.1 branch within a day or so 😄.

Sorry for the delay!

File: WordPress/Classes/Utility/ContextManager.m [hunk 1]
```diff
@@ -188,6 +188,23 @@ - (BOOL)obtainPermanentIDForObject:(NSManagedObject *)managedObject
...
+- (void)mergeChanges:(NSManagedObjectContext *)context fromContextDidSaveNotification:(NSNotification *)notification
+{
+    [context performBlock:^{
+        // Fault-in updated objects before a merge to avoid any internal inconsistency errors later.
+        // Based on old solution referenced here: http://www.mlsite.net/blog/?p=518
+        NSSet* updates = [notification.userInfo objectForKey:NSUpdatedObjectsKey];
+        for (NSManagedObject *object in updates) {
+            if ([object isFault]) {
+                // Force a fault-in of the object's key-values
+                [[context objectWithID:[object objectID]] willAccessValueForKey:nil];
```
Comment (jleandroperez) [inline WordPress/Classes/Utility/ContextManager.m]: Since the **object** itself may belong to another NSManagedObjectContext, it might be a good idea to reload the entity in the **context** that's being merged. I'm not sure what would be the effect of `willAccessValueForKey`, when crossing threads.

Something like this perhaps?

```
       NSArray* updates = [notification.userInfo[NSUpdatedObjectsKey] allObjects];
        for (NSManagedObject* object in updates) {
            NSManagedObject* localMO = [context existingObjectWithID: object.objectID error:nil];
            if (localMO.isFault) {
                [localMO willAccessValueForKey:nil];
            }
        }
```

**Comment by kurzee** [comment]
>I've totally missed that snippet, during the Simperium phase out. Added a minor suggestion, regarding reloading the entity.

@jleandroperez good catch! I've added that check.

**Comment by kurzee** [comment]
Thanks @aerych, @jleandroperez, @astralbodies! Will cherrypick the commits and bring into 7.1.
