### PR TITLE
Fixing Restoration Crash

### LINKED ISSUE #5289: Crash: PeopleViewController State Restoration
### Expected behavior
No crash. Of course!

### Actual behavior
The app crashes.

### Steps to reproduce the behavior
1. Log into a WordPress.com account
2. Open My Sites > [Site]
3. Tap over the People row
4. Hit the Home button
5. Kill the app
6. Relaunch the app

As a result, `PeopleViewController` will crash, due to the missing State Restoration handling code. Not just that... but it'll enter into a loop crash, and the only way out is a reinstall.

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #5289

To test:
1. Log into a Dotcom account
2. Open `My Sites` > `Site` > People
3. Press the home button
4. Kill the app
5. Relaunch the app

As a result, the User's list should be onscreen. And of course, the app shouldn't crash.

Needs review: @frosty 
Thanks in advance James!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/People/PeopleViewController.swift [hunk 1]
```diff
@@ -93,4 +106,49 @@ public class PeopleViewController: UITableViewController, NSFetchedResultsContro
...
+        
+        guard let blogID = coder.decodeObjectForKey(RestorationKeys.blog) as? String,
+            let objectURL = NSURL(string: blogID),
+            let objectID = context.persistentStoreCoordinator?.managedObjectIDForURIRepresentation(objectURL),
+            let restoredBlog = try? context.existingObjectWithID(objectID) else
+        {
+            return nil
+        }
+        
+        guard let blog = restoredBlog as? Blog else {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/People/PeopleViewController.swift]: Is there a reason this is separate from the `guard` statements above? You could append it to the list of `let`s there, or even add the `as?` to the final statement:

`let blog = (try? context.existingObjectWithID(objectID)) as? Blog else {`

**Comment by jleandroperez** [comment]
@frosty ready for another look. Thank you!

**Comment by frosty** [comment]
:shipit:!

**Comment by jleandroperez** [comment]
Thanks for the review!!
