### PR TITLE
Only extract author info on a new Post / Page if the user can query for authors.

### LINKED ISSUE #16858: Cannot post to Atomic Site as an author
### Expected behavior

Creating or editing posts I own as an author will not fail to upload. 
### Actual behavior
Error message saying Post Failed to Upload

### Steps to reproduce the behavior
1. Be an author on an Atomic site
2. Create blog post on WP iOS client
3. Publish
4. Error message stating Post Failed to upload.

##### Slack ID 
p1626191963467800-slack-C03URUK5C

##### Zendesk
4136410-zen

IMG_BF1B46CF018F-1

### PR DESCRIPTION
**Pull request by twstokes**
Fixes #16858

This change addresses a bug where Atomic site users who had limited permissions (e.g. Authors, Contributors) couldn't create new Posts or Pages. This occurred because we were always passing the `blog.account.userID` to the API as the `author` value on [new Post and Page API requests](P2gHKz-g-p2.2/post/sites/%24site/posts/new/). We learned that for Atomic sites this ID - which is their wp.com user ID - is not accepted by the backend. We should have instead been sending their ID that is local to the Atomic site.

This fix drops sending the author's user ID unless the user has permissions to query for other authors on the site, and can populate `blog.authors`. In the `blog.authors` array, the user ID is always the correct ID for the site, e.g. the ID for a user on the Atomic site and not necessarily always their wp.com user ID.

## To test:

**Note:** If the app's logged in user's role is downgraded, leftover state (e.g. previously downloaded authors) may remain, resulting in failures of the tests below. It's recommended to test user role changes by going from lowest up, or by wiping the app state clean each time. This should be considered a bug and an issue will be created.

### Prerequisites for all test sites
- Add multiple authors: At least one Administrator role and one Author role

### Non-Jetpack self-hosted sites
There is a discrepancy for the Editor role. On web, an Editor can choose new authors. On WPiOS, the client cannot query for the list of users, and thus can't populate the authors, so the user will not have the Author option. In other words, for self-hosted sites the user role must be Administrator to use this feature.

#### Administrator role
- [ ] Creating a new Post.
- [ ] Creating a new Post and setting a different author.
- [ ] Creating a new Page.
- [ ] Creating a new Page and setting a different author.
- [ ] Updating an existing Post.
- [ ] Updating an existing Page.
- [ ] Updating an existing Post and changing the author.
- [ ] Updating an existing Page and changing the author.

#### Author role
- [ ] Creating a new Post.
- [ ] Updating an existing Post.

### Jetpack self-hosted sites
There is a discrepancy for the Editor role. On web, an Editor can choose new authors. On WPiOS, the client cannot query for the list of users, and thus can't populate the authors, so the user will not have the Author option. In other words, for self-hosted sites the user role must be Administrator to use this feature.

#### Administrator role
- [ ] Creating a new Post.
- [ ] Creating a new Post and setting a different author.
- [ ] Creating a new Page.
- [ ] Creating a new Page and setting a different author.
- [ ] Updating an existing Post.
- [ ] Updating an existing Page.
- [ ] Updating an existing Post and changing the author.
- [ ] Updating an existing Page and changing the author.

#### Author role
- [ ] Creating a new Post.
- [ ] Updating an existing Post.

#### Administrator role
- [ ] Creating a new Post.
- [ ] Creating a new Post and setting a different author.
- [ ] Creating a new Page.
- [ ] Creating a new Page and setting a different author.
- [ ] Updating an existing Post.
- [ ] Updating an existing Page.
- [ ] Updating an existing Post and changing the author.
- [ ] Updating an existing Page and changing the author.

#### Author role
- [ ] Creating a new Post.
- [ ] Updating an existing Post.

#### Administrator role
- [ ] Creating a new Post.
- [ ] Creating a new Post and setting a different author.
- [ ] Creating a new Page.
- [ ] Creating a new Page and setting a different author.
- [ ] Updating an existing Post.
- [ ] Updating an existing Page.
- [ ] Updating an existing Post and changing the author.
- [ ] Updating an existing Page and changing the author.

#### Author role
- [ ] Creating a new Post.
- [ ] Updating an existing Post.

---

**Creating with author change**

1. Create a new Post or Page on a site that has multiple users.
2. Access the Post or Page settings by tapping the horizontal ellipses (More Options) icon at the top right and choosing Settings.
3. Observe that "Author" appears as the top row under the "Publish" section.
4. Tap on the row and observe that authors are shown by their Display Name sorted alphabetically. 
5. Select a new author and publish or save the Post or Page.
6. Observe in the app and on the web that the new Post or Page has the chosen author.

**Updating with author change**

1. Select an existing Post or Page on a site that has multiple users.
2. Access the Post or Page settings by tapping the horizontal ellipses (More Options) icon at the top right and choosing Settings.
3. Observe that "Author" appears as the top row under the "Publish" section.
4. Tap on the row and observe that authors are shown by their Display Name sorted alphabetically.
5. Select a new author and update the Post or Page.
6. Observe in the app and on the web that the new Post or Page has the chosen author.

**Creating without author change**

1. Create a new Post or Page on a site that has multiple users.
2. Fill in test content
3. Publish the Post or Page
4. Observe in the app and on the web that the new Post or Page has the author that created it.

**Updating without author change**

1. Select an existing Post or Page by the author that is logged in.
2. Edit content on the Post or Page
3. Update the Post or Page
4. Observe in the app and on the web that the Post or Page reflects the updated content.

## Regression Notes
1. Potential unintended areas of impact
- Creating a new post
- Creating a new page
- Creating a new post with a different author
- Creating a new page with a different author
- Updating an existing post
- Updating an existing page
- Choosing a new author for an existing post
- Choosing a new author for an existing page

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Worked with @guarani to complete the test cases provided in this PR.

3. What automated tests I added (or what prevented me from doing so)
No new tests were added for this change.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/PostService.m [hunk 1]
```diff
@@ -54,8 +54,8 @@ - (Post *)createPostForBlog:(Blog *)blog {
     post.postType = Post.typeDefaultIdentifier;
 
     BlogAuthor *author = [blog getAuthorWithId:blog.userID];
-    post.authorID = author.userID ?: blog.account.userID;
-    post.author = author.displayName ?: blog.account.displayName;
+    post.authorID = author.userID;
```
Comment (twstokes) [inline WordPress/Classes/Services/PostService.m:57]: Originally we fell back on the `blog.account.userID` if we had no hit with `getAuthorWithId`, but I don't believe this was necessary. Tracking the author ID and display name is only needed to have for the UI to switch authors.

Therefore if we don't have authors to choose from, we won't be doing any switching. When `authorID` is `nil` here, it won't be passed to the API and the update will be done "as the current user".

**Comment by guarani** [comment]
Testing d2b017fbc631882f4e5181308c728c298ed08d9b:

### Non-Jetpack self-hosted sites

#### Administrator role
- [x] Creating a new Post.
- [x] Creating a new Post and setting a different author.
- [x] Creating a new Page.
- [x] Creating a new Page and setting a different author.
- [x] Updating an existing Post.
- [x] Updating an existing Page.
- [ ] Updating an existing Post and changing the author.
- [ ] Updating an existing Page and changing the author.

⚠️ Note: The last two points above couldn't be completed because I'm seeing a separate issue where tapping on the Author cell in Post Settings sometimes opens the Location picker instead. Will add a link to the issue here later.
**Update 27 Aug 2021: I couldn't reproduce this bug so I think it's a non-issue.**

#### Author role
- [x] Creating a new Post.
- [x] Updating an existing Post.

### Jetpack self-hosted sites

#### Administrator role

Admin user: `paulvonschrottky`

- [x] Creating a new Post.
- [x] Creating a new Post and setting a different author.
- [x] Creating a new Page.
- [x] Creating a new Page and setting a different author.
- [x] Updating an existing Post.
- [x] Updating an existing Page.
- [x] Updating an existing Post and changing the author.
- [x] Updating an existing Page and changing the author.

#### Author role

Author user: `p8ya8c`

- [x] Creating a new Post.
- [x] Updating an existing Post.

### WordPress.com Simple sites

Site: paulvonschrottky.wordpress.com

#### Administrator role

Admin user: `paulvonschrottky`

- [x] Creating a new Post.
- [x] Creating a new Post and setting a different author.
- [x] Creating a new Page.
- [x] Creating a new Page and setting a different author.
- [x] Updating an existing Post.
- [x] Updating an existing Page.
- [x] Updating an existing Post and changing the author.
- [x] Updating an existing Page and changing the author.

#### Author role

Author user: `p8ya8c`

- [x] Creating a new Post.
- [x] Updating an existing Post.

### WordPress.com Atomic sites

Site: pschrottkyunsupportedblockatomic.wpcomstaging.com

#### Administrator role

Admin user: `paulvonschrottky`

- [x] Creating a new Post.
- [x] Creating a new Post and setting a different author.
- [x] Creating a new Page.
- [x] Creating a new Page and setting a different author.
- [x] Updating an existing Post.
- [x] Updating an existing Page.
- [x] Updating an existing Post and changing the author.
- [x] Updating an existing Page and changing the author.

#### Author role

Author user: `p8ya8c`

- [x] Creating a new Post.
- [x] Updating an existing Post.

**Review by guarani — APPROVED** [review]
Tested thoroughly and looks good! Great to see a fix involving deleted code! ❤️ 
:shipit:

**Comment by twstokes** [comment]
Thank you @guarani!

**Comment by mokagio** [comment]
@twstokes  this has been bundled as part of [17.8 beta 2 (17.8.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/16878).

Thanks for your work 🙌
