### PR TITLE
Reset navigation on account change

### LINKED ISSUE #3130: Tabs should reset their nav hierarchy when accounts change.
To reproduce on the iPhone: 
- I signed out of my wpcom account.  This returned me to the sign in screen. 
- Created a new site via NUX. 
- When I was finished I was placed on Me tab. 
- I tapped on the My Sites tab and was taken to the comments screen. 

This was probably the last screen open on this tab before I signed out.  Tapping back showed a site belonging to the acct I signed out from. Tapping back again showed the list with just the newly created site.

I repeated the steps above, but this time I left the My Site tab on the post list. When I tapped to the My Sites tab after going through the NUX process the app crashed.

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #3130. Whenever the default account changes all navigation controllers in the tabbar are popped to their root. This resolves the issue in the cleanest way possible. It has a slight side effect of popping to the root when it's not necessary (such as if the user is in a self-hosted site's details page and logs out of WordPress.com account) however it's a lot easier to maintain than a lot of conditional checks for when to reset the navigation. It also adds a tracker for when the default account changes.

@aerych May I bother you with a review?

### CODE REVIEW

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m [hunk 1]
```diff
@@ -82,6 +82,11 @@ - (instancetype)init
                                                  selector:@selector(helpshiftUnreadCountUpdated:)
                                                      name:HelpshiftUnreadCountUpdatedNotification
                                                    object:nil];
+
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: When I was looking at WPTabBarController, I noticed we don't do anything to remove the observers that are added. I understand this is fine since we treat this class as a singleton. My paranoia is kicking in a bit and I'm wondering if at some future point we might change that.  Would it make sense to go ahead and add a `dealloc` method to `[[NSNotificationCenter defaultCenter] removeObserver:self]`?  Just a though, not a necessary change.

**Comment by aerych** [comment]
Hiya Oguz.  Changes look good but there's a merge conflict now. Feel free to :shipit: when resolved.

File: WordPress/Classes/ViewRelated/System/WPTabBarController.m (hunk 1 above)
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/System/WPTabBarController.m]: +1 It'd be a good idea to add those removeObserver lines, just for the paranoia. 

Nevertheless, somewhere around iOS 4 or 5, Apple added a removeObserver call. Undocumented behavior, but if you try to crash an app that way, it won't break!.

**Comment by oguzkocer** [comment]
@aerych & @jleandroperez - `[[NSNotificationCenter defaultCenter] removeObserver:self]` added and merge conflicts resolved.

**Comment by jleandroperez** [comment]
*Note:*
This PR also fixes issue #3205. Thanks @oguzkocer!
