### PR TITLE
Issue 7043 - 3D touch current site fix

### LINKED ISSUE #7043: 3D Touch doesn't accurately reflect current site
### Expected behavior
The 3d touch shortcuts should show the currently selected site

### Actual behavior
The 3d touch shortcuts always shows the first site alphabetically

### Steps to reproduce the behavior
Sign in with multiple sites, check the 3d touch shortcuts
Change your current site, check the 3d touch shortcuts

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #7043 

To test:
Sign in and verify the sites in the 3d touch shortcuts are correct
Change the site and verify the sites are correct again

@koke, any tips on how to unit test this?

### CODE REVIEW

File: WordPress/Classes/Services/RecentSitesService.swift [hunk 1]
```diff
@@ -79,5 +79,6 @@ class RecentSitesService: NSObject {
             return
         }
         touch(site: url)
+        WP3DTouchShortcutCreator().createShortcutsIf3DTouchAvailable(true)
```
Comment (koke) [inline WordPress/Classes/Services/RecentSitesService.swift]: Rather than call this directly here, I'd post a notification and handle it like the sign in one

File: WordPress/Classes/System/WordPressAppDelegate.m [hunk 2]
```diff
@@ -835,6 +835,11 @@ - (void)listenLocalNotifications
                            selector:@selector(handleLowMemoryWarningNote:)
                                name:UIApplicationDidReceiveMemoryWarningNotification
                              object:nil];
+    
+    [notificationCenter addObserver:self
+                           selector:@selector(handleSignInDidFinish:)
+                               name:SigninHelpers.WPSigninDidFinishNotification
```
Comment (koke) [inline WordPress/Classes/System/WordPressAppDelegate.m]: Why is `WPAccountDefaultWordPressComAccountChangedNotification` not enough?

Comment (kwonye) [inline WordPress/Classes/System/WordPressAppDelegate.m]: Because the account changing doesn't guarantee that the blogs are synced, which is when we get the default blog for the account (which was what was happening)

**Comment by kwonye** [comment]
@koke good call on the notification! Not only is it cleaner, it's easily testable. Ready for another pass.

Another test case I found was changing the blog name that's now handled by c87a395

File: WordPress/Classes/Services/RecentSitesService.swift [hunk 3]
```diff
@@ -10,6 +10,7 @@ class RecentSitesService: NSObject {
     private let database: KeyValueDatabase
     private let databaseKey = "RecentSites"
     private let legacyLastUsedBlogKey = "LastUsedBlogURLDefaultsKey"
+    @objc static let WPTouchedBlogNotification = "WPTouchedBlogNotification"
```
Comment (koke) [inline WordPress/Classes/Services/RecentSitesService.swift]: Since this is already namespaced by RecentSitesService, I'd drop the WP prefix. I was going to suggest replacing Blog with Site, but maybe just name it "Changed":

```
static let changedNotification = NSNotification.Name("RecentSitesChanged")
```

File: WordPress/Classes/System/WordPressAppDelegate.m [hunk 4]
```diff
@@ -860,6 +860,21 @@ - (void)listenLocalNotifications
...
+                             object:nil];
+    
+    [notificationCenter addObserver:self
+                           selector:@selector(create3DTouchShortcutItems)
+                               name:RecentSitesService.WPTouchedBlogNotification
+                             object:nil];
+    
+    [notificationCenter addObserver:self
+                           selector:@selector(create3DTouchShortcutItems)
+                               name:WPBlogUpdatedNotification
```
Comment (koke) [inline WordPress/Classes/System/WordPressAppDelegate.m]: Would this still work if you updated the site title from the app?

Comment (kwonye) [inline WordPress/Classes/System/WordPressAppDelegate.m]: Great call, verified it doesn't work. Tried something but it may be overkill. Will continue tomorrow.

**Comment by kwonye** [comment]
Thanks for the :shipit: @koke but I don't want to merge code in that isn't optimal. Per your suggestion, I've moved all the handling of 3D touch related notifications to the 3DShortcutCreator.

Still trying to figure out how to elegantly handle updating a blog without spamming a notification out. I'll ping you when I find something 👍

**Comment by astralbodies** [comment]
I'm targeting 7.7 with this PR - not enough time to test and 7.6 has been shipped off to Apple.

**Comment by elibud** [comment]
@kwonye this one has been moving from milestone to milestone for a while, I'm moving it to 7.9 now.

**Comment by kwonye** [comment]
@elibud thanks for the reminder. I'll resolve this this week.

**Comment by kwonye** [comment]
> Still trying to figure out how to elegantly handle updating a blog without spamming a notification out. I'll ping you when I find something 👍

After looking at this again, this doesn't send out a notification if there is no change to the blog (https://github.com/wordpress-mobile/WordPress-iOS/pull/7044/files#diff-5b1cb97c8a2d01d0f82bcf2fe1a7c4d2R944)

I think this is good to ship. I'm so sorry it took so long for me to get back to this.

**Comment by koke** [comment]
Buddybuild is currently failing with a build error

**Comment by koke** [comment]
BTW, :shipit: when green 😁
