### PR TITLE
Press stop on featured image uploading shows error

### LINKED ISSUE #3124: Editor: Error cancelling an uploading featured image.
Cancel uploading featured image shows an NSURLErrorDomain -999 error.   
Try to upload again causes a crash (sometimes you need to try a couple of times to trigger). 

img_0060

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix #3124 and https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/528

Pointing to 4.8

/cc @bummytime, can you please review.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 1]
```diff
@@ -1061,47 +1106,14 @@ - (void)handleDateChange:(id)value
 
 - (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info
 {
-    __weak PostSettingsViewController *weakSelf = self;
+    __weak __typeof(self) weakSelf = self;
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: :+1:

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 2]
```diff
@@ -1061,47 +1106,14 @@ - (void)handleDateChange:(id)value
...
-                DDLogError(@"Couldn't upload featured image %@: %@", assetURL, [error localizedDescription]);
-                [weakSelf.tableView reloadData];
-            }];
-            [progress setUserInfoObject:[UIImage imageWithData:media.thumbnail] forKey:WPProgressImageThumbnailKey];
-            progress.localizedDescription = NSLocalizedString(@"Uploading...",@"Label to show while uploading media to server");
-            weakSelf.featuredImageProgress = progress;
-            [weakSelf.tableView reloadData];
-        }];
-
+        [weakSelf uploadFeatureImage:asset];
```
Comment (bummytime) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: Much cleaner!

**Comment by bummytime** [comment]
:shipit:
