### PR TITLE
Use more detailed HTTP "User-Agent" header so web servers won't fallback to XHTML / WML

### LINKED ISSUE #4295: Facebook video doesn't render in "My Sites > View Site", but does in "Blog Posts > [post] > View"
Steps to reproduce:

1. create a new post with post content: ```https://www.facebook.com/zuck/videos/10102371249389011/```
2. publish post
3. select blog from "My Sites" in WP iOS app
4. select "View Site" and see blank space where video should be
5. close webkit window
6. select Blog Posts > [post] > View and see video rendered within post

### PR DESCRIPTION
**Pull request by pypt**
Some web servers (e.g. Facebook video) misinterpret the current `User-Agent` string as if the app was a feature phone and was only able to parse WML content, e.g.:

    wp-iphone/5.7 (iPhone OS 9.1, iPhone) Mobile

So, append "wp-iphone/<version>" to the UIWebView's default `User-Agent` string and use it instead:

    Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B137 wp-iphone/5.7

Fixes #4295.

### CODE REVIEW

**Comment by aerych** [comment]
Nice @pypt 

I can't think of any reason not to do this.  I took look at some the wpcom and wporg core UA detection libs (e.g. vars.php and the group of `is_mobile` checks) and it doesn't look like they'd be impacted at all.  Bonus, this likely would let us remove from the app code that switches between UAs (like post preview).   

Pinging @koke and @diegoreymendez for their history with the User Agent.
Pinging @astralbodies, @sendhil for any concerns from an analytics standpoint.

**Comment by sendhil** [comment]
No concerns from me from an analytics point of view.

**Comment by pypt** [comment]
I figured that Android app might want to use the same UA format too, so made a pull request to *WordPress-Android* too.

I should note that the Android app doesn't have the same problem as it uses the default UA to do most of the things (e.g. previewing the blog).

**Comment by koke** [comment]
I think this should be safe. IIRC @daniloercoli worked on a lot of that UA detection code, so pinging him as well :smile:

**Comment by daniloercoli** [comment]
It should be OK with Jetpack UA detection library as long as `Safari` is not in the new UA string.

**Comment by diegoreymendez** [comment]
No concerns regarding changing the UserAgent on my end.  However I do have some notes and questions regarding the code in the PR.  I'm adding them inline so you can review them.

File: WordPress/Classes/Utility/WPUserAgent.m [hunk 1]
```diff
@@ -35,17 +35,33 @@ - (void)setupUserAgent
...
+    [[NSUserDefaults standardUserDefaults] registerDefaults:tempRegisteredDefaults];
+    
+    NSString *userAgent = [[[UIWebView alloc] init] stringByEvaluatingJavaScriptFromString:@"navigator.userAgent"];
+    NSAssert(userAgent != nil, @"User agent shouldn't be nil");
+    NSAssert(! [userAgent isEmpty], @"User agent shouldn't be empty");
+    
+    [[NSUserDefaults standardUserDefaults] registerDefaults:originalRegisteredDefaults];
+    
+    return userAgent;
+}
```
Comment (diegoreymendez) [inline WordPress/Classes/Utility/WPUserAgent.m]: This method seems very thread unfriendly as it is right now.

If the method was called in two separate threads simultaneously it could change the final UserAgent (thread 1 records user Agent A, sets user agent B, thread 2 records user agent B sets user agent C, thread 1 restores A, thread 2 restores B).

If the user agent was requested by another thread while it's temporarily changed we would have a similar problem.  IMHO since the method is supposed to act as a getter, I'd try to solve this by caching the original user agent somewhere and avoid making any changes each time this method is called.

Comment (diegoreymendez) [inline WordPress/Classes/Utility/WPUserAgent.m]: Also, how does the addition of this method affect the following methods?  Are they still safe to use?

`- (void)useDefaultUserAgent`
`- (void)useWordPressUserAgent`
`- (void)setUserAgent:(NSString*)userAgent`

Comment (aerych) [inline WordPress/Classes/Utility/WPUserAgent.m]: Is there a specific scenario you have in mind where the UA could be changed in multiple threads?  I think currently its only ever modified in the main thread.

Comment (pypt) [inline WordPress/Classes/Utility/WPUserAgent.m]: > This method seems very thread unfriendly as it is right now.

It is, however I've assumed that `WPUserAgent` is only to be used with UIWebView which always runs on the main thread (as the rest of the UIKit's classes). Said class exposes `useDefaultUserAgent` and `useWordPressUserAgent` which only have effect on UIWebView and not on other means of using HTTP.

It's possible that someone in the future might want to make `defaultUserAgent` public and use it directly for whatever purposes (e.g. REST calls), in which case I can go about wrapping parts of the method with `@synchronized`, but I'm not sure if you need it right now.

> Also, how does the addition of this method affect the following methods? Are they still safe to use?

The new method temporarily resets the UA, reads it, and sets it back. This wasn't being done previously, so I'd argue that `useWordPressUserAgent` was less safe before as it could have led to custom UA duplicating itself:

1. Class 1 creates WPUserAgent object, WPUserAgent reads default user agent, stores it to NSUserDefaults.
2. Class 1 calls `useWordPressUserAgent`, WPUserAgent sets UA to the custom value
3. Class 1 "forgets" to reset the UA to the default value
4. Class 2 creates WPUserAgent object, WPUserAgent reads what it thinks is a default user agent value but is actually a leftover custom value from class 1
5. If class 2 calls `useDefaultUserAgent`, custom UA instead of the default one is set

This wasn't actually happening in the app because WPUserAgent's users were well behaved, but the unit test was actually testing this specific erroneous behavior by setting UA to the default one and then comparing it to a custom UA (fixed in 0a41c20).

Comment (pypt) [inline WordPress/Classes/Utility/WPUserAgent.m]: > It is, however I've assumed that WPUserAgent is only to be used with UIWebView which always runs on the main thread (as the rest of the UIKit's classes). Said class exposes useDefaultUserAgent and useWordPressUserAgent which only have effect on UIWebView and not on other means of using HTTP.

Some parts of the code use `currentUserAgent` though to get whatever's set in NSUserDefaults at the moment, but I don't think temporarily resetting NSUserDefaults could introduce new problems here.

Comment (diegoreymendez) [inline WordPress/Classes/Utility/WPUserAgent.m]: @pypt - Thanks for taking the time to reply.

Regarding multi-threading support: the fact that the method is private and only used during initialization makes it OK not to be thread safe IMO.  I'm just trying to rule out obscure issues this may bring in, but it seems we're safe on this front right now.

Part of what I don't like about the code we had / have (this was not introduced by you though, so ignore this please) is that I don't think we should be using `NSUserDefaults` for this, as this is not something that needs to be persisted across app launches.  But as I said above this is an unrelated note.

Your reply on this thread is good for me.

**Comment by diegoreymendez** [comment]
I'm good with this... :shipit: .

Can anyone provide a second confirmation?

**Comment by diegoreymendez** [comment]
Maybe @aerych?

**Comment by aerych** [comment]
Totes! :shipit:

**Comment by astralbodies** [comment]
Lets make sure this is also done on the Android side :smile:

**Comment by pypt** [comment]
@astralbodies, here's the same PR for Android: wordpress-mobile/WordPress-Android/pull/3410

**Comment by astralbodies** [comment]
Awesome @pypt - I should have checked that first :+1:
