### PR TITLE
Fix crash on Account Settings for self hosted

### LINKED ISSUE #4842: Crash on account settings for self hosted blogs
To reproduce:

- Fresh install
- Add a self-hosted site
- Navigate to Me > Account Settings
- Crash

I wrongly assumed `account` was a requirement of both My Profile and Account Settings (it was before we merged app settings and account settings). I think the best solution is to split the common code that lives in `SettingsController` and depends on `service`, and make `service` optional in `AccountSettingsController`. Then build a different table model depending on if there's an account or not.

This still leaves the question open about what happens if the default account changes.

### PR DESCRIPTION
**Pull request by koke**
I've removed most of the shared logic in SettingsCommon and only left the
ImmuTable action helpers there. My Profile doesn't make sense without a
service, while Account Settings still can display the app settings witout one.

The table view model and error logic is still similar for both, but not the
same, so each controller implements its own variant.

I also now pass the service to the action helpers explicitly to avoid having to
deal with optionals: the rows with actions that require a service won't be
displayed if there's no service.

Fixes #4842 
Cc: @astralbodies 
Needs Review: @jleandroperez

### CODE REVIEW

File: WordPress/Classes/ViewRelated/AccountSettingsViewController.swift [hunk 1]
```diff
@@ -3,12 +3,14 @@ import UIKit
 import RxSwift
 import WordPressComAnalytics
 
-func AccountSettingsViewController(account account: WPAccount) -> ImmuTableViewController {
-    let service = AccountSettingsService(userID: account.userID.integerValue, api: account.restApi)
+func AccountSettingsViewController(account account: WPAccount?) -> ImmuTableViewController {
+    let service = account.map({ account in
+        return AccountSettingsService(userID: account.userID.integerValue, api: account.restApi)
+    })
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: Just a thought on this one. Since `account` is an optional parameter, and not a collection, wouldn't be more appropriate to use... `if let` / `if guard` ?.

Plus ... if the account is *nil*, which shouldn't happen, but apparently, would... wouldn't the rest of the code break?

File: WordPress/Classes/ViewRelated/AccountSettingsViewController.swift [hunk 2]
```diff
@@ -27,66 +29,109 @@ private struct AccountSettingsController: SettingsController {
...
-            title: NSLocalizedString("Username", comment: "Account Settings Username label"),
-            value: settings?.username ?? "")
+    // MARK: - ImmuTableViewController
 
-        let email = TextRow(
-            title: NSLocalizedString("Email", comment: "Account Settings Email label"),
-            value: settings?.email ?? "")
+    func tableViewModelWithPresenter(presenter: ImmuTablePresenter) -> Observable<ImmuTable> {
+        if let service = self.service {
+            return service.settings.map({ settings in
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: Same as above, since `settings` is a single instance, are we sure we wanna use `map` instead of `if let` / `guard`?.

**Comment by jleandroperez** [comment]
Fix confirmed, not crashing anymore. Added two minor code comments / questions. Feel free to disregard.

Nice work @koke!!

:shipit:

File: WordPress/Classes/ViewRelated/AccountSettingsViewController.swift (hunk 1 above)
Comment (koke) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: If the account is nil, service will be nil, which is an acceptable scenario. In this case I like map more to handle the optionals, as it more concise. The alternative would be something like this

```swift
var service: AccountSettingsService? = nil
if let account = account {
  service = AccountSettingsService(...)
}
```

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: Just asking, because `Map`, although a valid statement here, is mostly used for collections. But i think it's just a matter of taste. 

P.s: You can drop the parenthesis, if you opt for the `map` style. 

```
let service = account.map { account in
   return AccountSettingsService(userID: account.userID.integerValue, api: account.restApi)
}
```

Comment (koke) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: > Map is mostly used for collections

You might be used to see it only on collections, but it's a concept that works for any kind of container (you can think of an optional as a collection limited to zero or one items). Collections are just the most obvious use case.

> You can drop the parenthesis

For this I like the style proposed [here](http://ericasadun.com/2015/11/17/a-handful-of-swift-style-rules-swiftlang/)

> The Rule of Kevin: “When a trailing closure argument is functional, use parentheses. When it is procedural, use braces.”

```swift
myCollection.map({blah}).filter({blah}).etc
myCollection.forEach {} // or 
dispatch_after(when, queue) {}
```

It makes sense because `map`/`filter`/`reduce` are things that you often chain together, and this doesn't look as good: 

```swift
foo.map {
  return $0 * 2
}.filter {
  return $0 < 10
}
```

Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/AccountSettingsViewController.swift]: I'd personally just drop the parenthesis because: although that's a functional call, it's not being chained to anything else.

Nevertheless, it's absolutely your call sir!
