### PR TITLE
Fix: Do not bounce to Safari when both apps are installed

### LINKED ISSUE #19755: Infinite redirect loop between WP and JP when accessing a private post from the app
Refs:
- p1670447671998299-slack-C014TPFLP4 
- p1670486250785319-slack-C011BKNU1V5
- p1669886587680679/1669871444.707189-slack-C046L7LPV0F

### Expected behavior
The infinite redirect shouldn't happen. From either app, when the app doesn't have access to the post, it should open in Safari instead.

### Actual behavior
Tapping a `*.wordpress.com` universal link that leads to a private post that the app cannot access leads to an infinite redirect between the WordPress and Jetpack app when both are installed.

See references for more details (including video recordings).

### Steps to reproduce the behavior

- Install both WordPress and Jetpack app.
- Tap any `*.wordpress.com` link that leads to a private site (e.g. P2) that you don't have access to.
- Observe that the app keeps redirecting between WordPress and Jetpack.

### Findings

- When encountering a private post that the app couldn't access, it tries to open the URL in the browser instead. This applies to both apps since they share the same codebase.
- Both WordPress and Jetpack apps handle the same Universal Link routes. This means when one app opens a post within the `*.wordpress.com` domain, the other catches the intent. Hence the infinite redirect.
- Note that the scope is limited to private posts where the app user doesn't have sufficient permission to read. My assumption is that this problem mostly applies to P2 posts.

##### Tested on iPhone 13 Pro, iOS 16.1, WPiOS 23.1.0.1

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #19755, p4a5px-2Rv-p2

### Context

When handling Universal Links, the app bounces the URL to Safari if it couldn't handle the link due to various reasons (unhandled routes, insufficient permission, etc). When both WordPress and Jetpack apps are installed, the URLs bounced by one app will be caught by the other, and since it couldn't handle it too, the other app will bounce the URL back again—leading to an infinite loop.

In #19775, this was handled by removing the bounce code in the Reader route since we're already displaying an error message with an option to display the URL in an in-app browser. However, p4a5px-2Rv-p2 shows that there are routes other than the Reader that can cause the infinite redirect.

### The fix

This PR adds a workaround for this issue by:
- Disabling the bounce to Safari when both apps are installed.
- For certain routes (e.g. `wordpress.com/post/(:siteURL|:siteID)/:postID`), the link will be converted to a wp-admin link (`https://<site-url>/wp-admin/post.php?post=...`), and will be opened in Safari.

### Environment 1: Both apps are installed

- Have both WordPress and Jetpack apps installed on the device or simulator.
- As there are test cases involving private sites, to make things easier, log in to your WordPress.com account and ensure that you use an account that has access to a private site.
- Tap the links as described by the table below, and verify the expectation column is correct:

No. | Link | Expectation
-|-|-
1 | A valid "edit post" link with site URL (`/post/:siteURL/:postID`) | Opens wp-admin link in Safari
2 | A valid "edit post" link with site ID (`/post/:siteID/:postID`) | Opens wp-admin link in Safari
3 | An **invalid** "edit post" link, e.g. with a wrong site ID. | Does nothing
4 | Any `*.wordpress.com` link that leads to a private site with insufficient access (e.g. a P2 post that you're not a member of) | Does nothing
5 | Any valid deeplink route, for example `https://wordpress.com/me` | Deeplinks into the feature

### Environment 2: Only one app installed

- Have only one app installed (either WordPress or Jetpack).
- Log in to your WordPress.com account.
- Tap the links as described by the table below, and verify the expectation column is correct:

No. | Link | Expectation
-|-|-
1 | A valid "edit post" link with site URL (`/post/:siteURL/:postID`) | Opens the link in Safari
2 | A valid "edit post" link with site ID (`/post/:siteID/:postID`) | Opens the link in Safari
3 | An **invalid** "edit post" link, e.g. with a wrong site ID. | Opens the link in Safari
4 | Any `*.wordpress.com` link that leads to a private site with insufficient access (e.g. a P2 post that you're not a member of) | Does nothing
5 | Any valid deeplink route, for example `https://wordpress.com/me` | Deeplinks into the feature

- Repeat the steps above, but now testing with the other app.

## Regression Notes
1. Potential unintended areas of impact
Some deeplink scenarios could be impacted or not correctly processed.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
I wasn't able to finish reviewing the PR (started looking at the code but haven't tested the changes yet). Will come back to this ASAP if no-one beats me to it.

File: WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+                guard let url = blogURLString(from: values),
+                      let postID = postID(from: values) else {
+                    return nil
+                }
+
+                var components = URLComponents(string: "https://\(url)/wp-admin/post.php")
+                components?.queryItems = [
+                    .init(name: "post", value: postID),
+                    .init(name: "action", value: "edit"),
+                    .init(name: "calypsoify", value: "1")
```
Comment (guarani) [inline WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:58]: nit: Can you share more about why `calypsoify` is here?

File: WordPress/Classes/Extensions/UIApplication+AppAvailability.swift [hunk 2]
```diff
@@ -3,6 +3,7 @@ import Foundation
 enum AppScheme: String {
     case wordpress = "wordpress://"
     case wordpressMigrationV1 = "wordpressmigration+v1://"
+    case jetpack = "jetpack://"
```
Comment (guarani) [inline WordPress/Classes/Extensions/UIApplication+AppAvailability.swift:6]: I'm using a debug build to test this PR and `isCounterpartAppInstalled` was always returning `false` when both apps were installed. Since debug builds use `jpdebug://` for JP and `wpdebug://` for WP, I updated these and the corresponding `Queried URL Schemes` so the apps can query these. Is that what you also did to test this?

**Review by guarani — COMMENTED** [review]
Hi @dvdchr! Thanks for the fix.

I'm sharing my partial review in case it helps.

### Environment 1: Both apps are installed

To test this I have:
- Testing links in a Note on my phone
- The links correspond to a private WP.com Simple site
- Both the JP and WP apps logged into a WP.com that **does not** have access to the site
- Mobile Safari is also logged into an account that **does not** have access to the site

At first, I tested the PR as-is and wasn't seeing the desired results. I then updated the URL schemes to the debug variety and the `Queried URL Schemes` as noted below but haven't finished retesting yet.

Is this how you also tested? Asking to make sure I'm on the right track.

File: WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift (hunk 1 above)
Comment (dvdchr) [reply WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:58]: Yep, sure! When I go to `wordpress.com/post/<site-url>/<post-id>`, it redirects to `<site-url>/wp-admin/post.php?post=<post-id>&action=edit&calypsoify=1` in the browser — both desktop and mobile.

I'm not sure what the `calypsoify` parameter is for, but my intent was to keep the behavior consistent. I'm open to suggestions if you think this parameter should not be applied. 🙂

File: WordPress/Classes/Extensions/UIApplication+AppAvailability.swift (hunk 2 above)
Comment (dvdchr) [reply WordPress/Classes/Extensions/UIApplication+AppAvailability.swift:6]: No, I didn't modify them. For **environment 1**, my setup was to have a debug build for Jetpack and a TestFlight version of WordPress (note that installing the App Store version also works). In the [apple app site association](https://wordpress.com/.well-known/apple-app-site-association), since the Jetpack app has a higher priority, it'll always be the first responder when handling external links. Plus, since TestFlight builds uses release flags, so the WordPress app will have the `wordpress://` scheme registered.

As for **environment 2**, I tested both of them in isolation (e.g. test JP with WP uninstalled, and vice versa) so I kinda ignored the value of `isCounterpartAppInstalled`.

Comment (dvdchr) [reply WordPress/Classes/Extensions/UIApplication+AppAvailability.swift:6]: If you're testing exclusively from the Simulator, I think making temporary modifications like you do should also work. For reference, you can refer to the `JetpackRedirector` class:

https://github.com/wordpress-mobile/WordPress-iOS/blob/4644af904081305ab869b9a230b72ab44186fb22/WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackRedirector.swift#L10-L22

File: WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift (hunk 1 above)
Comment (dvdchr) [reply WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:58]: Or did you mean adding some documentation in the code for the `calypsoify` parameter? 😅 Sorry if I misunderstood your question.

**Comment by staskus** [comment]
Thank you for the fixes!

I tested both environments. The results are almost as described. The only difference is that in **environment 2 step 4** I get the app open the Reader and show "error loading post" instead of opening Safari. In **environment 1** it behaves the same way.

- I installed `WordPress` through TestFlight and `Jetpack` through Xcode debug build
- Tested both environments after the changes and before the changes
- Tested environment 2 with both apps

Ideally, I would imagine both environments behaving the same way but again, having 2 apps installed is not a valid scenario and we're only looking to avoid loops temporarily.

**Comment by dvdchr** [comment]
@staskus, Thanks for jumping in to review! Appreciate it. 🙂 

> The only difference is that in environment 2 step 4, I get the app open the Reader and show "error loading post" instead of opening Safari

Great catch! This is... actually an error in the test expectation. 😅  The behavior you are seeing is already correct because the "bounce to Safari" in the Reader was removed in #19775, regardless of whether the counterpart app exists.

I've now updated Environment 2 step 4. Thanks again!

File: WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift [hunk 3]
```diff
@@ -0,0 +1,95 @@
+/// A router that handles routes that can be converted to /wp-admin links.
+///
+/// Note that this is a workaround for an infinite redirect issue between WordPress and Jetpack
+/// when both apps are installed.
+///
+/// This can be removed once we remove the Universal Link routes for the WordPress app.
+struct WPAdminConvertibleRouter: LinkRouter {
```
Comment (staskus) [inline WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:7]: To clarify, the idea of this workaround is:
- Where possible, construct wp-admin links which **do not redirect** to mobile apps
- If wp-admin links are not possible, do nothing in the app

And this solution wouldn't be viable if wp-admin pages would actually redirect to mobile apps?

Comment (dvdchr) [reply WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:7]: > this solution wouldn't be viable if wp-admin pages would actually redirect to mobile apps?

Yes, you're correct 💯.  I was taking advantage of the fact that we aren't handling any wp-admin routes in iOS.

My thinking was that the conversion to a wp-admin link, for some qualified links, allows some limited UX mitigation where users would still have their intent fulfilled in Safari; instead of being redirected into the app without navigating anywhere.

Comment (staskus) [reply WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:7]: Thanks for clarifying! 

Given that we recommend not using the apps together, I think this solution even exceeds expectations. Avoiding the loops might be even enough.

If we would actually want to have WordPress and Jetpack apps seamlessly work together, then we would need to look for approaches that support all the cases.

**Review by staskus — APPROVED** [review]
Tests cases passed ✅.

The main goal was to avoid loops which was accomplished by checking if counterpart app is installed when URLs are not handled. 

wp-admin solution works for post editing, since this web page does not have routing to mobile apps. If we wanted to seriously support WordPress and Jetpack apps working together, I would try to aim for a more bulletproof solution. Since this is a temporary solution for the scenario we're not really supporting, I think it's good to be accepted.

**Comment by dvdchr** [comment]
Thanks @staskus . Yeah, this likely won't be a bulletproof solution and will be removed later once we concluded all the migration steps. I'll go ahead and merge this for now. 🙂

File: WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift (hunk 1 above)
Comment (guarani) [reply WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift:58]: > Yep, sure! When I go to wordpress.com/post/<site-url>/<post-id>, it redirects to <site-url>/wp-admin/post.php?post=<post-id>&action=edit&calypsoify=1 in the browser — both desktop and mobile.

Thanks for explaining!

> I'm not sure what the calypsoify parameter is for, but my intent was to keep the behavior consistent. I'm open to suggestions if you think this parameter should not be applied. 🙂

Sounds fair. I'm not familiar with this parameter but I understand "calypsoify" to mean a version of WP Admin that feels a bit more like Calypso. I'm not sure in what cases it's used though. Setting it to true here seems like a reasonable safe choice 👍 

> Or did you mean adding some documentation in the code for the calypsoify parameter? 😅 Sorry if I misunderstood your question.

I didn't mean this, sorry for not being clear 🙇

File: WordPress/Classes/Extensions/UIApplication+AppAvailability.swift (hunk 2 above)
Comment (guarani) [reply WordPress/Classes/Extensions/UIApplication+AppAvailability.swift:6]: > No, I didn't modify them. For **environment 1**, my setup was to have a debug build for Jetpack and a TestFlight version of WordPress (note that installing the App Store version also works). In the [apple app site association](https://wordpress.com/.well-known/apple-app-site-association), since the Jetpack app has a higher priority, it'll always be the first responder when handling external links. Plus, since TestFlight builds uses release flags, so the WordPress app will have the `wordpress://` scheme registered.

Gotcha! I hadn't thought to test like this because I wanted to test the effects of the PR on both apps, but this probably wasn't necessary. 

While it would be nice to avoid hard-coding the URL schemes, I think it would be very difficult. I looked into it and it might involve moving the schemes from the target build settings up to the project build settings so that either app could access them for the current release type. From there I think either app's Info.plist could still read them via a build variable like `${WPCOM_SCHEME}`.

**Comment by guarani** [comment]
👋  @dvdchr, I came back to try this out on the latest 21.8 beta and had mixed results. Could you please let me know if this is the expected behavior?

> ### Environment 1: Both apps are installed

I have JPiOS 21.8.0.1 and WPiOS 21.8.0.3 installed and logged into one account (Account A). I have a couple of links to a test site owned by another account (Account B). Mobile Safari is logged into Account B.

| No. | Link | Expectation | Result |
| - | - | - | - |
| 1 | A valid "edit post" link with site URL (`/post/:siteURL/:postID`) e.g. https://wordpress.com/post/pschrottkytestbd.wordpress.com/9 | Opens wp-admin link in Safari | JPiOS opens, WPiOS opens, WPAdmin opens in Safari |

This flow works because I don't see the infinite switching. However, is it meant to open WPiOS before going to Safari?

---

| No. | Link | Expectation | Result |
| - | - | - | - |
| 2 | A valid "edit post" link with site ID (/post/:siteID/:postID) e.g. https://wordpress.com/post/207274994/9 | Opens wp-admin link in Safari | JPiOS opens, WPiOS opens |

I couldn't get it to open Safari here, it stayed on WPiOS. I'm not sure if it's something in my testing environment so wanted to reach out to you to get clarification.

**Comment by staskus** [comment]
> I have JPiOS 21.8.0.1 and WPiOS 21.8.0.3 installed and logged into one account (Account A). I have a couple of links to a test site owned by another account (Account B). Mobile Safari is logged into Account B.

@guarani I wasn't testing scenarios where we have different accounts on Safari and apps.

Are your links associated with Account A or Account B? My guess is that this is a separate scenario and hit different cases on the apps.

**Comment by dvdchr** [comment]
Thanks @guarani for raising this, and @staskus for helping out!

I tried to checkout and compile 21.8 locally but I've been stuck in the pod install step 😅 . I'm guessing something's up with my network routing to GitHub. I'll come back to this later and test once it's sorted out, but the expected workaround behavior is:

- Do nothing when the counterpart app is installed AND the app couldn't handle the link, or 
- Open in Safari when the link can be converted to wp-admin.

In some cases, `UniversalLinkRouter.canHandle(url:)` might return `true` despite not having proper access to the resource (e.g. a private blog post that the current user doesn't have access to), and in this case, the app should do nothing —provided that it detects that the counterpart app is installed. If this happens, the additional check in [`UniversalLinkRouter.handle(url:)`](https://github.com/wordpress-mobile/WordPress-iOS/blob/8eb7fcb308ba68f38840348ad5577503d59f12c3/WordPress/Classes/Utility/Universal%20Links/UniversalLinkRouter.swift#L152-L159) and [`Route.failAndBounce()`](https://github.com/wordpress-mobile/WordPress-iOS/blob/8eb7fcb308ba68f38840348ad5577503d59f12c3/WordPress/Classes/Utility/Universal%20Links/Route.swift#L41-L53) should've prevented the app from bouncing the link to Safari 🤔 

> I have JPiOS 21.8.0.1 and WPiOS 21.8.0.3 installed

To rule out the app scheme mismatch (as you've [mentioned](https://github.com/wordpress-mobile/WordPress-iOS/pull/20213#pullrequestreview-1314523982) during your testing), can you confirm if both apps were installed from TestFlight? The detection logic currently only checks for `wordpress://` and `jetpack://` schemes.

**Comment by guarani** [comment]
👋  Hi folks, thanks for taking a look!

> Are your links associated with Account A or Account B? My guess is that this is a separate scenario and hit different cases on the apps.

The links are owned by Site B.

> To rule out the app scheme mismatch (as you've [mentioned](https://github.com/wordpress-mobile/WordPress-iOS/pull/20213#pullrequestreview-1314523982) during your testing), can you confirm if both apps were installed from TestFlight? The detection logic currently only checks for `wordpress://` and `jetpack://` schemes.

Yes, I installed both from TestFlight. 

---

Just to clarify the overall problem we're trying to solve: The user has both JP & WP installed and logged in to an account. Then, the user encounters a link (e.g. in Slack) to a site that the account doesn't have access to on either app. We want to avoid the infinite loop that currently happens when tapping on the link.

Is this correct?

**Comment by dvdchr** [comment]
@guarani 👋🏼, I just tested this on the latest Jetpack + WordPress beta 21.9 via TestFlight.

- A valid "edit post" link with site URL (`/post/:siteURL/:postID`)
- A valid "edit post" link with site ID (`/post/:siteID/:postID`)

For me, in both cases this opens JP, then goes straight to wp-admin in Safari. Without transiting in WP. 🤔 I'm now curious if you've stumbled upon an edge case. 😨

**Comment by guarani** [comment]
Thanks for testing @dvdchr! I'm replying late because I was offline since late last week.

> For me, in both cases this opens JP, then goes straight to wp-admin in Safari. Without transiting in WP. 🤔 I'm now curious if you've stumbled upon an edge case. 😨

It seems to be working for me too on the 21.9 betas. I re-tried the 21.8 betas using the exact versions mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/20213#issuecomment-1456141183 and I **can** reproduce the issue there, so the issue appears to be fixed. Here's a comparison of what I see:

| 21.8 ❌ | 21.9 ✅ |
| - | - |
| <video src="https://user-images.githubusercontent.com/1898325/225744178-fde4f62c-e45c-4f73-84b4-6e374a4f96cf.MP4"></video> | <video src="https://user-images.githubusercontent.com/1898325/225744082-d7696448-55b7-4059-b6d6-f0b59419749c.MP4"></video> |
