### PR TITLE
Fixing Today widget configuration on account/site changes

### LINKED ISSUE #2598: Remove Today Widget upon db migration failure/forced logout
If the app is forced to log a user out make sure the Today Widget configuration is removed and the widget force-hidden.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #2598, #2746, and #4687 

To test:

1. Log out of your WordPress.com account and verify that the widget is not configured to a site anymore.
2. Delete the site that the Today widget is configured to. If there are no sites, the widget is unconfigured.
3. Delete the site that the Today widget is configured to. If there is another site, the widget is configured to one of the other sites.
4. Open the widget when there is no internet connection and verify that it stays configured.
5. Open the widget when there is an invalid oauth token (you can set it manually in `TodayViewController.swift` line 165)

Change 
`let statsService: WPStatsService = WPStatsService(siteId: siteID, siteTimeZone: timeZone, oauth2Token: oauthToken, andCacheExpirationInterval:0)` 

to 

`let statsService: WPStatsService = WPStatsService(siteId: siteID, siteTimeZone: timeZone, oauth2Token: "fds", andCacheExpirationInterval:0)`

and verify that the today widget becomes unconfigured.

Needs review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
Awesome work - will try and get this reviewed soon!

File: WordPress/Classes/Services/AccountService.m [hunk 1]
```diff
@@ -335,13 +330,6 @@ - (void)setupAppExtensionsWithDefaultAccount
                                      andOAuth2Token:oauth2Token];
         });
     }
-    
-    // Share Extension Configuration
-    dispatch_async(dispatch_get_main_queue(), ^{
```
Comment (astralbodies) [inline WordPress/Classes/Services/AccountService.m]: Was the share extension configuration moved elsewhere?

Comment (kwonye) [inline WordPress/Classes/Services/AccountService.m]: Derp, that was a total mental error on my part. I read that as `configureTodayExtension` so I removed it because it wasn't doing anything related to the today widget. Reverting the deletion of this. Great catch, thanks!

**Comment by astralbodies** [comment]
@kwonye :shipit: 

I really apologize for this long delay.

**Comment by kwonye** [comment]
@astralbodies no problem! Thanks for fixing the whitespace + review! Appreciate it 👍
