### PR TITLE
Fix an issue with WordPressComRestApi instance not being cached by WPAccount

### LINKED ISSUE #24320: Crash on Logout: Fatal Error in `WPAccount+RestApi.swift` due to Nil optional
After:

1. Switching websites
2. Navigating to the "Me" menu
3. Pressing logout

I encountered the following crash.

```WordPress/WPAccount+RestApi.swift:15: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value```

Image

### PR DESCRIPTION
**Pull request by kean**
The previous implementation was retaining it:

```
_wordPressComRestApi = [WordPressComRestAp...
```

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/24320

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/308">25.9</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/Models/WPAccount+RestApi.swift [hunk 1]
```diff
@@ -11,49 +11,54 @@ extension WPAccount {
...
+            self.wordPressComRestApi = api
             return api
         }
         set(api) {
             objc_setAssociatedObject(self, &apiAssociatedKey, api, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
         }
     }
 
+    private func makeWordPressComRestApi() -> WordPressComRestApi {
+        let api = WordPressComRestApi.defaultApi(
```
Comment (kean) [inline WordPress/Classes/Models/WPAccount+RestApi.swift:28]: To test: 

- Set a breakpoint and verify that this gets called ~one time on app launch
- Verify that it gets nilled out on logout

Comment (kean) [reply WordPress/Classes/Models/WPAccount+RestApi.swift:28]: The setter does seem to be called constantly on `didDidTurnInfoFault` – odd. 
Update: it's mostly the entities on the background thread.

File: WordPress/Classes/Models/WPAccount.h [hunk 2]
```diff
@@ -39,7 +39,7 @@
 /// Important: Do not set this directly!
 ///
 /// It's reserved for Objective-C to Swift interoperability in the context of separating this model from the app target and will be removed at some point.
-@property (nonatomic, strong) WordPressComRestApi *wordPressComRestApi;
+@property (nonatomic, strong) WordPressComRestApi *_wordPressComRestApi;
```
Comment (kean) [inline WordPress/Classes/Models/WPAccount.h:42]: I wasn't sure we can rely on overriding a property in an extension.

File: WordPress/Classes/Models/WPAccount+RestApi.swift [hunk 3]
```diff
@@ -10,48 +10,48 @@ extension WPAccount {
     /// This used to be defined in the Objective-C layer, but we moved it here in a Swift extension in an attempt to decouple the model code from it.
     /// This was done in the context of https://github.com/wordpress-mobile/WordPress-iOS/pull/24165 .
     @objc var wordPressComRestApi: WordPressComRestApi? {
```
Comment (kean) [inline WordPress/Classes/Models/WPAccount+RestApi.swift:12]: I wasn't sure we can rely on overriding a property in an extension, so I'm now relying on a stored property in `WPAccount`.

File: WordPress/WordPressTest/ThemeServiceTests.m [hunk 4]
```diff
@@ -165,7 +165,7 @@ - (void)testThatActivateThemeThrowsExceptionWithoutTheme
     ThemeService *service = nil;
 
     blog.dotComID = blogId;
-    blog.account.wordPressComRestApi = api;
+    blog.account._private_wordPressComRestApi = api;
```
Comment (crazytonyli) [inline WordPress/WordPressTest/ThemeServiceTests.m:168]: What do you think about adding the `wordPressComRestApi` setter back to support these statements?

**Review by crazytonyli — APPROVED** [review]

File: WordPress/WordPressTest/ThemeServiceTests.m (hunk 4 above)
Comment (kean) [reply WordPress/WordPressTest/ThemeServiceTests.m:168]: It's used only in tests as a way to mock the dependencies, so I think it's OK. It might be worth adding a method like `setTestingWordPressAPI` or something like this. Wdyt? I think this is also acceptable though.

Comment (crazytonyli) [reply WordPress/WordPressTest/ThemeServiceTests.m:168]: Yep. I'm okay with this. The app code should never use the setter after all.
