### PR TITLE
Fix offline text

### LINKED ISSUE #5758: Plans: Improve the error message if the user is offline
### Expected behavior

If the app can't load the Plans screen because the device is offline, I expect an error message that clearly explains that.

For example, this is the on-screen error on the Stats screen if the device is offline:

> No Connection
> An active internet connection is required to view stats
### Actual behavior

If I'm offline, I get a generic "oops" error message:

> Oops
> There was an error loading plans
> Contact support
### Steps to reproduce the behavior
1. Disable the device's internet connection (e.g. enable airplane mode)
2. Go to My Site > Plans
#### Screenshots

Error message on the Plans screen:

Error message on the Stats screen:

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #5758 

To test:

Turn on Airplane mode and verify it shows the new error message

@frosty I am fully aware this may not be the best way to fix this issue. If so, please let me know what the better way is 👍

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift [hunk 1]
```diff
@@ -16,11 +16,19 @@ enum PlanListViewModel {
...
+            if appDelegate.connectionAvailable {
+                return WPNoResultsView.Model(
+                    title: NSLocalizedString("Oops", comment: ""),
+                    message: NSLocalizedString("There was an error loading plans", comment: ""),
+                    buttonTitle: NSLocalizedString("Contact support", comment: "")
+                )
+            } else {
+                return WPNoResultsView.Model(
+                    title: NSLocalizedString("No connection", comment: ""),
+                  message: NSLocalizedString("An active internet connection is required to view stats", comment: "")
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift]: "stats", huh? 😉

**Comment by frosty** [comment]
I'm happy with this approach – it's the same way stats does it.

Just one code comment, and then :shipit: :)

**Comment by kwonye** [comment]
Haha, oh copy-paste.... thanks for the review @frosty!
