### PR TITLE
Issues/4526: Fix BlogDetailsViewController site name position in multitasking

### LINKED ISSUE #4526: Multitasking: Site name halfway off screen
On iOS 9.1, iPad Air 2, the site name is obscured off the left hand side of the pane:

image

### PR DESCRIPTION
**Pull request by frosty**
Fixes #4526 – Constraints on the site name header in BlogDetailsViewController are now updated whenever the trait collection changes, so that it's displayed correctly when multitasking (previously it only checked whether the device was an iPad or not).

To test: Please verify this in all multitasking configurations on iPad, and on iPhone when not multitasking to ensure nothing's broken – particularly the 6(s) Plus, as it uses regular size class in landscape.

Needs review: @jleandroperez

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m [hunk 1]
```diff
@@ -173,35 +196,39 @@ - (void)configureBlogDetailHeader
                                                                  multiplier:1.0
                                                                    constant:headerWidth]];
         // Center the headerView inside the wrapper
-        [headerWrapper addConstraint:[NSLayoutConstraint constraintWithItem:self.headerView
+        [constraints addObject:[NSLayoutConstraint constraintWithItem:self.headerView
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m]: (Absolutely no need to change anything!!). Just wanted to say... i recently discovered the `topAnchor` / `bottomAnchor` iOS 9 properties. Might become handy anytime else (you need way less code!)

Comment (frosty) [inline WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m]: Of course! Somehow anchors completely slipped my mind – I've updated this to use them.

**Comment by jleandroperez** [comment]
Looking great @frosty!

:shipit:
