### PR TITLE
Existing the editor to posts list / pages list will remain in the same tab.

### LINKED ISSUE #12284: [Auto-upload Published] Incorrect Post List tab is shown after exiting the editor
Part of #12240.

Based on the design described in #12240, PR #12252 changed the placement of locally published posts so that they will be initially placed in the Drafts list. After uploading, they will be moved to the Published list. 

However, there is a pre-existing feature where when exiting the editor after publishing, online or offline, the Post List automatically **shows the Published list**. 

## Steps

Please take a look at [this video](https://drive.google.com/file/d/1SZhc3DlWZFLOhBo4aNkMQZDGDZWEoGcc/view?usp=sharing). 

1. `0:00` Navigate to _Scheduled_. This is just to illustrate the tab switching.
2. `0:02` Create a post and while online and publish it.
3. `0:17` Notice that the current tab was automatically switched to the Published tab. ❓ 
4. `0:19` Navigate to Drafts list. The post is there. It will be moved to the Published list after uploading is done. 
5. `0:31` Go offline. Navigate to the Scheduled list again. Create a post and publish it. 
6. `0:45` Notice that after exiting the editor, the Published tab is selected again. ❓ 
7. `0:48` Navigate to Drafts list. The post is there as expected. Go online and it will be moved to the Published post once uploading is done. 

This can be reproduced by using the `issue/12240-master-branch` master branch commit 9813fd087550e804862d9105ef3c890b902c2849. 

## Questions 

- [x] @osullivanchris What do you think should be done for this? @malinajirka, did you handle this differently in WPAndroid? 

## Decision 2019-Aug-12

- [ ] As agreed in https://github.com/wordpress-mobile/WordPress-iOS/issues/12284#issuecomment-520402865, we will remove the auto-switching of tabs when exiting the editor. 

## Notes 

🌲Fixes should be targeting the master branch, `issue/12240-master-branch`.

### PR DESCRIPTION
**Pull request by yaelirub**
Fixes #12284 

To test:
1. Be on drafts / scheduled tab
2. Create a post / page
3. publish the post / page
4. The editor is removed from view
* Notice that the post lists / pages list remains on the same tab you started in.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/PostListViewController.swift [hunk 1]
```diff
@@ -485,14 +485,8 @@ class PostListViewController: AbstractPostListViewController, UIViewControllerRe
...
-        editor.onClose = { [weak self] changesSaved in
-            if changesSaved {
-                if let postStatus = editor.post?.status {
-                    self?.updateFilterWithPostStatus(postStatus)
-                }
-            } else {
-                self?.updateFilter(index: filterIndex)
-            }
+        editor.onClose = { [weak self] _ in
+             self?.updateFilter(index: filterIndex)
```
Comment (shiki) [inline WordPress/Classes/ViewRelated/Post/PostListViewController.swift]:
```suggestion

```

It looks like we do not need to keep this at all if we also remove the `updateFilterWithPostStatus` call on line 493 which moves the tab to Draft right away. 

https://github.com/wordpress-mobile/WordPress-iOS/blob/67cc42ce581751fb52f16f710a59e41e00aa31aa/WordPress/Classes/ViewRelated/Post/PostListViewController.swift#L493

File: WordPress/Classes/ViewRelated/Pages/PageListViewController.swift [hunk 2]
```diff
@@ -466,15 +466,8 @@ class PageListViewController: AbstractPostListViewController, UIViewControllerRe
...
-            if changesSaved {
-                if let postStatus = editorViewController?.post.status {
-                    self?.updateFilterWithPostStatus(postStatus)
-                }
-            } else {
-                self?.updateFilter(index: filterIndex)
-            }
-
+        editorViewController.onClose = { [weak self, weak editorViewController] _, _ in
+            self?.updateFilter(index: filterIndex)
```
Comment (shiki) [inline WordPress/Classes/ViewRelated/Pages/PageListViewController.swift]:
```suggestion

```

It looks like we do not need to keep this at all if we also remove the `updateFilterWithPostStatus` call on line 480 which moves the tab to Draft right away. 

https://github.com/wordpress-mobile/WordPress-iOS/blob/67cc42ce581751fb52f16f710a59e41e00aa31aa/WordPress/Classes/ViewRelated/Pages/PageListViewController.swift#L480

**Comment by yaelirub** [comment]
Hey @shiki , thanks for the review. I updated according to your suggestions and it's ready for another look
