### PR TITLE
[JP Plugin] Add cancellation and misc. fixes

### LINKED ISSUE #20018: Configure the existing Jetpack Remote Install flow
Depends on #20017 

Reuse the existing Jetpack Remote Install flow to use the new plugin installation endpoint, skip the Jetpack Connection step, and update some copy for the UI.

Installation | Error
-|-
jetpack_install_flow | error

## Tasks

- [x] #20066 
- [x] #20108
- [x] #20130 
- [x] #20131
- [ ] #20143

## Todo
- [x] Install screen
  - [x] Performs request with the new endpoint when "Continue" is tapped (in #20130)
- [x] Loading screen
  - [x] Cancel the API request when the "Cancel" button is tapped (in #20143)
- [x] Complete screen
  - [x] Remove the Cancel button (in #20131)
  - [x] Update the subtitle text (in #20130)
  - [x] Update the primary button text to "Done" (in #20130)
- [x] Error screen
  - [x] Performs request to the new endpoint when "Retry" is tapped (in #20130)
  - [x] Contact Support button tags `origin:jp-install-full-plugin-error` as metadata (in #20143)
- [x] Adjust Tracks (in #20131)

### Others

- [x] Rename `ViewData` to `ViewModel` based on [this review comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/20066#discussion_r1104889541). (in #20143)

### PR DESCRIPTION
**Pull request by dvdchr**
Refs #20018

---

⚠️ **Note: Auto-merge is enabled!** ⚠️ 

---

Several minor changes in this PR:

- Request cancellation — The `Progress` object returned from the service is now retained in the view model, and `cancel()` is called whenever the user taps the Cancel button.
- Added a support origin tag when the user taps "Contact Support" from the error state.
- Renamed `ViewData` -> `ViewModel`, as per [this review comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/20066#discussion_r1104889541).

## To test

For convenience, add this temporary code on the FAB again:

```swift
// MySiteViewController+FAB.swift: line 8
        let newPage = {
            // FIXME: Remove changes after testing.
            let presenter = RootViewCoordinator.sharedPresenter
            let blog = presenter.currentOrLastBlog()
//            presenter.showPageEditor(forBlog: blog)

            let viewModel = WPComJetpackRemoteInstallViewModel()
            let controller = JetpackRemoteInstallViewController(blog: blog!, delegate: nil, viewModel: viewModel)
            let navController = UINavigationController(rootViewController: controller)
            navController.modalPresentationStyle = .fullScreen
            presenter.rootViewController.dismiss(animated: true) { [weak presenter] in
                presenter?.rootViewController.present(navController, animated: true)
            }
        }
```

- Run the Jetpack app, and log in to your WordPress.com account.
- Switch to the self-hosted site.
- Turn on airplane mode / disable your connection to easily reach the error page.
- Tap on the FAB > Site Page.
- Tap Continue, and the error screen should be shown shortly.
- Tap Contact Support > Ticket List.
- Verify that this event fired: `🔵 Tracked: support_ticket_list_viewed <source: origin:jp-install-full-plugin-error>` (notice the origin part)

> **Note**: The cancellation part is not manually testable right now, because part of the cancellation flow involves dismissing the modal, which will be implemented by the `JetpackRemoteInstallDelegate` later on in the wiring part.

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/WPComJetpackRemoteInstallViewModel.swift [hunk 1]
```diff
@@ -84,6 +89,16 @@ extension WPComJetpackRemoteInstallViewModel: JetpackRemoteInstallViewModel {
             break
         }
     }
+
+    /// NOTE: There's no guarantee that the plugin installation will be properly cancelled.
+    /// We *might* be able to cancel if the request hasn't been fired; but if it has, it'll probably succeed.
+    ///
+    /// An alternative would be to have a listener that checks if installation completes after cancellation,
+    /// and fires background request to uninstall the plugin. But this will not be implemented now.
```
Comment (wargcm) [inline WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/WPComJetpackRemoteInstallViewModel.swift:97]: I'm inclined to say that we just disable the ability to cancel when the request is already in progress. It'd make things easier from a code perspective and it'd be more clear for a user. We don't have to make that change now but just something to think about.

**Review by wargcm — APPROVED** [review]
✅ Observed the track with the correct source.

I'm also approving knowing that the auto-merge is on since my comment doesn't block anything. LGTM 👍
