### PR TITLE
Fix help button crash

### LINKED ISSUE #8199: Crash: tapping nav bar Help button in LoginSocialErrorViewController
### Expected behavior
Should display Support view.

### Actual behavior
Crashes with error handleHelpButtonTapped: unrecognized selector sent to instance

### Steps to reproduce the behavior
Get to social login error page. Tap help button in nav bar.

To note, it also affects #8172 .

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #8199

To test:
- ensure the help button works on the Google login error screen
- also the new site creation screen

Needs review: @ScoutHarris

### CODE REVIEW

File: WordPress/Classes/ViewRelated/NUX/SiteTypeTableViewController.swift [hunk 1]
```diff
@@ -87,6 +87,15 @@ class SiteTypeTableViewController: UITableViewController, LoginWithLogoAndHelpVi
...
 
+    // MARK: - LoginWithLogoAndHelpViewController methods
+
+    func handleHelpButtonTapped(_ sender: AnyObject) {
+        displaySupportViewController(sourceTag: .wpComLogin)
+    }
+    
+    // this VC isn't setup to handle the badge count. Should be fixed when NUXAbstractViewController and LoginViewController are refactored
+    func handleHelpshiftUnreadCountUpdated(_ notification: Foundation.Notification) { }
+
```
Comment (ScoutHarris) [inline WordPress/Classes/ViewRelated/NUX/SiteTypeTableViewController.swift]: Hey @nheagy - just wondering why this is. Seems the same as `LoginSocialErrorViewController` - catch the results from `addHelpButtonToNavController` and update an needed. I'm not seeing the difference. Can you elaborate?

Comment (nheagy) [reply WordPress/Classes/ViewRelated/NUX/SiteTypeTableViewController.swift]: I had to cut & paste code from `NUXAbstractViewController` into `LoginSocialErrorViewController` to get it to work. I decided not to paste it here because this view isn't yet in production, and I plan to refactor `NUXAbstractViewController` and `LoginWithLogoAndHelpViewController` before this is released.

Sound ok?

Comment (ScoutHarris) [reply WordPress/Classes/ViewRelated/NUX/SiteTypeTableViewController.swift]: I see. Yep, that sounds fine. Thanks!

**Comment by ScoutHarris** [comment]
Looks ok to me. :shipit: !

**Comment by nheagy** [comment]
This needed some Swift 4 fixes. Can you take a look @jleandroperez?

File: WordPress/Classes/ViewRelated/NUX/LoginViewController.swift [hunk 2]
```diff
@@ -12,19 +15,27 @@ extension LoginWithLogoAndHelpViewController where Self: UIViewController {
...
         navigationItem.titleView = imageView
     }
+
     func addHelpButtonToNavController() -> (UIButton, WPNUXHelpBadgeLabel) {
         let helpButtonMarginSpacerWidth = CGFloat(-8)
         let helpBadgeSize = CGSize(width: 12, height: 10)
         let helpButtonContainerFrame = CGRect(x: 0, y: 0, width: 44, height: 44)
 
-        NotificationCenter.default.addObserver(self, selector: #selector(NUXAbstractViewController.handleHelpshiftUnreadCountUpdated(_:)), name: NSNotification.Name.HelpshiftUnreadCountUpdated, object: nil)
+        NotificationCenter.default.addObserver(forName: NSNotification.Name.HelpshiftUnreadCountUpdated, object: nil, queue: nil) { [weak self](notification) in
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/NUX/LoginViewController.swift]: You can drop `NSNotification.Name`, since its inferred in the context (just `.HelpshiftUnreadCountUpdated` should work).

Ain't that *AWESOME*? (it's called 'extensible enums', we've recently stumbled upon that). Works as follows:

```
extension String {
    static let someConstant = "Something"
}

func someDummyMethod(string: String) { }
```

Whenever you call `someDummyMethod`, you can just use `.someConstant` as a parameter (Since the type is inferred). `NSNotification.Name` works exactly the same way,

File: WordPress/Classes/ViewRelated/NUX/LoginViewController.swift [hunk 3]
```diff
@@ -12,19 +15,27 @@ extension LoginWithLogoAndHelpViewController where Self: UIViewController {
...
+            self?.handleHelpshiftUnreadCountUpdated(notification)
+        }
 
         let customView = UIView(frame: helpButtonContainerFrame)
 
         let helpButton = UIButton(type: .custom)
         helpButton.setTitle(NSLocalizedString("Help", comment: "Help button"), for: .normal)
         helpButton.setTitleColor(UIColor(white: 1.0, alpha: 0.4), for: .highlighted)
-        helpButton.addTarget(self, action: #selector(NUXAbstractViewController.handleHelpButtonTapped(_:)), for: .touchUpInside)
+        helpButton.on(.touchUpInside) { [weak self](control: UIControl) in
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/NUX/LoginViewController.swift]: If you replace `(control: UIControl)` with just `control in`, the UIButton type gets auto-inferred, and you can drop the guard below.

Comment (nheagy) [reply WordPress/Classes/ViewRelated/NUX/LoginViewController.swift]: Good catch! Thanks

**Comment by nheagy** [comment]
Thanks @ScoutHarris and @jleandroperez!
