### PR TITLE
Fix a layout issue when we don’t have image size

### LINKED ISSUE #10834: Reader: Empty space at top of some post detail views
### Expected behavior

I expect that when I view the post detail in the Reader, the post content will begin directly below the title and author/timestamp for the post.

### Actual behavior

Some posts show a large gap of empty space at the top of the post detail view.

This consistently happens with certain posts that begin with an image: posts created in the Calypso classic editor with the Calypso Reader's Share button (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-do-a-little-test/)) and posts created in the iOS block editor (Gutenberg) starting with an image block (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-ios-block-editor/)).

It _doesn't_ consistently happen with posts created in Aztec (e.g. [this one](https://rachel-test-domain.com/2019/01/16/photo-post-2/)) or the Calypso block editor (e.g. [this one](https://rachel-test-domain.com/2019/01/02/photos-calypso-block-editor/)).

The empty space goes away after swiping up (a fast scroll down the post).

Example of the empty space in a post created in iOS Gutenberg:

### Steps to reproduce the behavior

1. Enable Gutenberg in the app (internal only).
2. Add an image block at the top of the post. (Other post content can be optionally included.)
3. Publish the post.
4. View the post detail in the Reader.

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes #10834

To test: Try with gifs, comments, and non-animated, fixed-size images. Also, watch the CPU usage – it should peak quickly when loading in a new image or when loading the initial post. This is important because the original PR addressed a crash caused by excessive CPU usage.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift [hunk 1]
```diff
@@ -298,9 +298,16 @@ extension WPRichContentView: WPTextAttachmentManagerDelegate {
         let finalSize = efficientImageSize(with: url, proposedSize: proposedSize)
         let image = richTextImage(with: finalSize, url, attachment)
 
-        // show that something is loading.
-        attachment.maxSize = CGSize(width: proposedSize.width, height: proposedSize.height)
+        let needsLayoutRefreshWhenLoaded = finalSize.height == 0
 
+        // show that something is loading.
+        if finalSize.height == 0 {
```
Comment (yaelirub) [inline WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Could this be `if needsLayoutRefreshWhenLoaded ` ?

Comment (jkmassel) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Good call! I don't love the variable name for that though, because the name is tightly associated with the `layoutAttachmentViews` call.

What about renaming `needsLayoutRefreshWhenLoaded ` to `isUsingTemporaryLayoutDimensions`? Then we can use it in both places and it should be logical?

Comment (yaelirub) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: sounds good to me!

Comment (jkmassel) [reply WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift]: Sweet – done!
