### PR TITLE
Stats: PeriodStore + improve CoreData Persistence + Caching

### LINKED ISSUE #19430: [iOS] Stats: Views and Visitors card always show outdated cached totals first
Once `Views and Visitors` caches total numbers, it doesn't update the cache, always showing the same numbers before loading most recent numbers.

https://user-images.githubusercontent.com/4062343/195125867-ded61ece-4592-4e2e-bd88-7db899aa5348.mov

## Expected behavior

Once the totals are updated, they should be cached and shown immediately after coming back to stats.

### Steps to reproduce the behavior

1. Enable state revamp feature flag
2. Open Stats
3. Add Views & Visitors card
4. Come back to menu and return to Stats
5. Notice total numbers changing every time

### PR DESCRIPTION
**Pull request by sla8c**
This PR adds functionality to fix a caching issue in the PeriodStore

The StatsPeriodStore has a [note](https://github.com/wordpress-mobile/WordPress-iOS/blob/246e149ece9c94c3a773739302ba4d7e452df389/WordPress/Classes/Stores/StatsPeriodStore.swift#L580) on how the persist to CoreData has an unintuitive call.  And after diving deeply + trying to diagnose I can see that at the tail end of fetchAsyncData no further saves to CoreData are called

### Attempted solution 1

~~I've tried to fix this by adding a barrierblock as the last operation to fetchAsyncData but at this time that is still not working so I've left this in draft status~~

~~Note that all the other fetch calls in StatsPeriodStore also save to core data ie: fetchAllVideos, fetchAllSearchTerms etc so I'm not sure why fetchAsyncData did not have this as well and cannot see why it shouldn't have (this call)~~

### Attempted solution 2

The barrierblock solution was discarded in favor of using dispatch groups to save to core data once multiple fetches have completed.

Fixes #19430

These should be the steps for a successful test (same as in the issue)
1. Enable new stats feature flags
2. Go to Stats screen and add Views & Visitors card
3. Tap back and return to main stats screen
4. The total numbers on Views & Visitors should hold their cached value

## Regression Notes
1. Potential unintended areas of impact
Stats

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by staskus** [comment]
@sla8c , I looked at this change and I agree with you that it makes perfect sense.

I also tried to understand why it might not be working. I found that `PeriodOperation` (`StatsPeriodAsyncOperation`) is not marked as `finished`, therefore the `queue` never triggers barrierBlock. I'm not sure why we're not marking the operation as `finished` after we receive the data.

This is a quick change that I made to `StatsPeriodAsyncOperation`:

```
    override func main() {
        service?.getData(for: period, endingOn: date, limit: limit) { [unowned self] (type: TimeStatsType?, error: Error?) in
            if self.isCancelled {
                self.state = .isFinished
                return
            }

            self.completion(type, error)
            self. State = .isFinished // <- code of line that was added
        }
    }
```

After this change, the block is triggered:

image

**Comment by sla8c** [comment]
@staskus as discussed I've pushed a change for this using DispatchGroups and its ready for review.  Thanks! 🙇

File: WordPress/Classes/Stores/StatsPeriodStore.swift [hunk 1]
```diff
@@ -493,6 +530,10 @@ private extension StatsPeriodStore {
 
         // 'limit' in this context is used for the 'num' parameter for the 'file-downloads' endpoint.
         // 'num' relates to the "number of periods to include in the query".
+        if FeatureFlag.statsNewAppearance.enabled {
+            group.enter()
+            DDLogInfo("Stats Period: Enter group fetching file downloads.")
```
Comment (staskus) [inline WordPress/Classes/Stores/StatsPeriodStore.swift:572]: This is more of a nitpick:
  
Since we have all the `.enter` calls inside a `fetchAsyncData(..)` I would have all the `.leave` calls inside this method as well. Otherwise, `.leave` calls get scattered across all the `receive...()` methods which can be called from other contexts. While looking at those `receive..()` methods in isolation, it's unclear what is the use of the `DispatchGroup` and if it's supposed to be notified in those other contexts as well.

[Here is the example](https://github.com/wordpress-mobile/WordPress-iOS/compare/issue/stats-period-core-data-persist...issue/stats-period-core-data-persist-imprv?expand=1)

**Review by staskus — COMMENTED** [review]
@guarani let me know if you'd like to review as well.

I'll wait for your take. We can make any improvements if needed ourselves.

**Comment by guarani** [comment]
> @guarani let me know if you'd like to review as well.

👋 @staskus, sure – I'd like to review this now.

> I'll wait for your take. We can make any improvements if needed ourselves.

Ok, sounds like a plan 👍

File: WordPress/Classes/Stores/StatsPeriodStore.swift (hunk 1 above)
Comment (guarani) [reply WordPress/Classes/Stores/StatsPeriodStore.swift:572]: 👋 I agree so I went ahead and put the `.leave()` calls within the context of the `.enter()` calls. I don't think this changes the functionality in any way.

Comment (staskus) [reply WordPress/Classes/Stores/StatsPeriodStore.swift:572]: Thanks. I'll check and approve if the rest is good 👍

**Review by guarani — COMMENTED** [review]
This fix works great! I found I verified that after the app gets new Stats data for Views, it uses that on subsequent loads of the Stats page.

I'm not sure about a couple of things:
- Is saving to core data only needed when the feature flag is on (and not when it's off)?
- Is saving to core data even when there's an error fetching the data the right choice?
I'll come back to this to finish digging into these questions.

**Comment by staskus** [comment]
> * Is saving to core data only needed when the feature flag is on (and not when it's off)?

If we don't add Feature Flags, we would make this functionality available for the non-revamped version of Stats as well. I tested and I don't see a problem with that, outside the fact that this improvement then could get shipped before the actual revamped stats. 

> * Is saving to core data even when there's an error fetching the data the right choice?

No issues happen because of that but there's a bit of inefficiency.

If an error happens for all the calls, then there's no change in data in the `state`, and the same information gets persisted again.

If an error happens for one or two of the calls and the others succeed then we're correct to persist data.

**Review by staskus — APPROVED** [review]
I'm approving this PR since the functionality works for me and the usage of `DispatchGroup` in this scenario is understandable.

As I explained in the previous comment: usage of `FeatureFlag` could potentially be optional and I don't see any issues that could come with persisting data if some of the calls fail.

**Comment by staskus** [comment]
Merging with one approval. Since the functionality is left under the feature flag it's safe to merge.
