### PR TITLE
Reader Detail: Dispatch header layoutIfNeeded on main queue

### LINKED ISSUE #21797: Bug: Reader detail header overlaps with the content sometimes
### Expected behavior
The Reader detail header section shouldn't overlap with the content.

### Actual behavior
The header section overlaps with the content. See pcdRpT-45K-p2#comment-6761.

### Steps to reproduce the behavior

- Navigate to the Notifications tab.
- Select any post-type notifications.
- Observe that the header overlaps into the content area about 10-25% of the time.

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #21797 

This (hopefully) fixes an intermittent issue where the header can appear to overlap with the contents sometimes. See #21797 for more details. I'm guessing that some sort of race might be happening here. Even though the GeometryReader has triggered its `onChange` closure, the view might not be done updating its content size yet, and the host view calls `layoutIfNeeded` before the changes are fully applied.

Screenshot 2023-10-17 at 18 07 00

The view highlighted in blue is the swiftUI's host view. As you can see, the SwiftUI view (right in front of the highlighted view) already has its content size updated, but the host view is still using the "old" size somehow.

To fix this, I simply dispatched the `layoutIfNeeded` call to the main queue. I no longer see this issue after retrying it 10-20 times.

## Regression Notes
1. Potential unintended areas of impact
Should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Review by wargcm — APPROVED** [review]
I opened multiple posts on both a simulator and a real device and didn't see it overlapping. That being said, if it is a race condition, we should probably double-check the beta builds after this is merged. It's possible there's a timing difference between the debug and release builds.

LGTM! 🛳️

File: WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNewHeaderView.swift [hunk 1]
```diff
@@ -60,8 +60,11 @@ class ReaderDetailNewHeaderViewHost: UIView {
         guard let swiftUIView = subviews.first else {
             return
         }
-        swiftUIView.invalidateIntrinsicContentSize()
-        layoutIfNeeded()
+
+        DispatchQueue.main.async {
+            swiftUIView.invalidateIntrinsicContentSize()
+            self.layoutIfNeeded()
+        }
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNewHeaderView.swift:67]: Did you consider annotating the method with `@MainActor`?

Comment (dvdchr) [reply WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNewHeaderView.swift:67]: Sorry for missing your comment, and thanks for the suggestion @mokagio! Annotating this method with `MainActor` is a great idea since I need this method to always run on the main thread. 

Turns out #21797 resurfaced, so I'll need to investigate this again. When the fix is up, I'll make sure to include your suggestion in there. 🙂
