### PR TITLE
Blaze: Update blaze instance from the correct thread

### LINKED ISSUE #20397: NSInvalidArgumentException: -[WPAccount isTemporaryID]: unrecognized selector sent to instance 0x28312c9b0
Sentry Issue: [JETPACK-IOS-Z5](https://a8c.sentry.io/issues/4019993079/?referrer=github_integration)

```
NSInvalidArgumentException: -[WPAccount isTemporaryID]: unrecognized selector sent to instance 0x28312c9b0
  File "BlazeService.swift", line 59, in BlazeService.updateBlog
  File "<compiler-generated>", in thunk for closure
  File "ContextManager.swift", line 91, in ContextManager.performAndSave
  File "<compiler-generated>", in ContextManager.performAndSave
  File "<compiler-generated>", in thunk for closure
...
(22 additional frame(s) were not displayed)
```

#### Similar Issues
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20388
- https://github.com/wordpress-mobile/WordPress-iOS/issues/17765

### PR DESCRIPTION
**Pull request by momo-ozawa**
Fixes #20397 

## Description
Fixes an issue where Blog managed object was being updated from the wrong thread.

Queries the Blog managed object using the context provided by the `performAndSave` closure to ensure the managed object is updated correctly.

Ref: pbArwn-602-p2

## How to test
0. Switch to trunk
1. Add `-com.apple.CoreData.ConcurrencyDebug 1` to your launch arguments
2. Build and run the Jetpack app
3. The app crashes
Screenshot 2023-03-27 at 11 52 23

4. Switch to this branch
5. Build and run the Jetpack app
6. The app doesn't crash 

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
n/a

7. What automated tests I added (or what prevented me from doing so)
n/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/BlazeService.swift [hunk 1]
```diff
@@ -33,31 +33,41 @@ import WordPressKit
...
 
-    private func updateBlog(_ blog: Blog, isBlazeApproved: Bool, completion: (() -> Void)? = nil) {
+    private func updateBlogWithID(_ objectID: NSManagedObjectID,
+                                  isBlazeApproved: Bool,
+                                  completion: (() -> Void)? = nil) {
         contextManager.performAndSave({ context in
+
+            guard let blog = context.object(with: objectID) as? Blog else {
+                DDLogError("Unable to update isBlazeApproved value for blog")
+                completion?()
```
Comment (crazytonyli) [inline WordPress/Classes/Services/BlazeService.swift]: The completion block can't be called here, otherwise it'll cause the same issue in https://github.com/wordpress-mobile/WordPress-iOS/pull/20196.

File: WordPress/Classes/Services/BlazeService.swift [hunk 2]
```diff
@@ -33,31 +33,41 @@ import WordPressKit
...
+                return
+            }
+
             blog.isBlazeApproved = isBlazeApproved
             DDLogInfo("Successfully updated isBlazeApproved value for blog: \(isBlazeApproved)")
+
         }, completion: {
             completion?()
```
Comment (crazytonyli) [inline WordPress/Classes/Services/BlazeService.swift]: This `completion` block will be called regardless if the Core Data operation in the closure above success or not.

**Review by crazytonyli — CHANGES_REQUESTED** [review]

File: WordPress/Classes/Services/BlazeService.swift (hunk 1 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/BlazeService.swift]: An alternative would be declaring contextManager as `CoreDataStackSwift`, so that you can catch the error thrown by the Core Data operation closure:

```swift
contextManager.performAndSave({ context in
    let blog = try context.existingObject(with: objectID) as! Blog
    blog.isBlazeApproved = isBlazeApproved
}, completion: { (result: Result<Void, Error>) in
    completion?()
}, on: .main)
```

File: WordPress/Classes/Services/BlazeService.swift (hunk 2 above)
Comment (momo-ozawa) [reply WordPress/Classes/Services/BlazeService.swift]: That's the desired behavior - I've amended the documentation to clarify this 🙇‍♀️

File: WordPress/Classes/Services/BlazeService.swift (hunk 1 above)
Comment (momo-ozawa) [reply WordPress/Classes/Services/BlazeService.swift]: > The completion block can't be called here

Fixed! [20eddd8](https://github.com/wordpress-mobile/WordPress-iOS/pull/20413/commits/20eddd86c7fc3d3856e0dde3b199b055fe2057b5)

We're only logging the error, so I decided to use `guard let blog = try? ...`

**Review by hassaanelgarem — APPROVED** [review]
The changes look good to me, and it works as described 🚀

**Review by crazytonyli — APPROVED** [review]

**Comment by mokagio** [comment]
Taking over merge to ship a new beta

**Comment by hypest** [comment]
Thank you for the fix @momo-ozawa !

Can you add a link to a convo with context about going with a beta fix instead, for example, of a hotfix? Thanks!

**Comment by momo-ozawa** [comment]
@hypest 👋 

We didn't have a conversation about whether to do a betafix vs hotfix for this crash. Sorry - I should have checked in with the release rotation team! Since this crash affected ~0.05% of users (low impact), and this isn't a critical flow (medium severity), I figured this would be a betafix instead of a hotfix.

Sentry Issue: [JETPACK-IOS-Z5](https://a8c.sentry.io/issues/4019993079/?referrer=github_integration)

**Comment by hypest** [comment]
Thanks for elaborating @momo-ozawa !

> Since this crash affected ~0.05% of users (low impact), and this isn't a critical flow (medium severity), I figured this would be a betafix instead of a hotfix.

Makes sense.

To try to understand the impact, I wonder, are the users affected all on the Blaze flow, or some may be on an irrelevant flow? If all on the Blaze flow, would all Blaze flow users encounter the issue? I would elevate the impact assessment depending on those questions.

For the severity assessment part, I wonder if the issue has been a blocker for the Blaze users for, say, reaching the check-out stage. If yes, I'd elevate the severity here as well.

I understand that the fix will be out with the 22.0 release scheduled for today so, no further action needed, but I think we probably want to update the crash priority matrix, to include the new revenue flows, the least.

**Comment by momo-ozawa** [comment]
@hypest Those are good points, thanks for sharing.

> To try to understand the impact, I wonder, are the users affected all on the Blaze flow, or some may be on an irrelevant flow?
>
> If all on the Blaze flow, would all Blaze flow users encounter the issue?
>
> For the severity assessment part, I wonder if the issue has been a blocker for the Blaze users for, say, reaching the check-out stage

This crash can happen when assessing whether users are eligible for Blaze. So this is before users begin the blaze purchase flow. Also, it doesn't happen all the time.

> I think we probably want to update the crash priority matrix, to include the new revenue flows, the least.

Agreed! I've updated the crash priority matrix to include this info. pbArwn-1gZ-p2
