### PR TITLE
Fix a crash due to Core Data Concurrency Violation in the Weekly Roundup Background Task

### LINKED ISSUE #20957: Weekly Roundup background task causes Core Data multithreading violation
### Expected behavior
No multithreading violation to occur.

### Actual behavior
Running the Weekly Roundup background task can cause the app to halt on a Core Data multithreading violation (`_PFAssertSafeMultiThreadedAccess_impl ()`) when ran in debug mode.

### Steps to reproduce the behavior

Running a local build attached to Xcode's debugger:

1. On My Site tap the avatar at the top right
2. App Settings
3. Debug
4. Weekly Roundup
5. Tap Schedule immediately
6. Observe Xcode

### Notes:
- In production this may cause `-[__NSCFSet addObject:]: attempt to insert nil` to be thrown
- It may be a variation of https://github.com/wordpress-mobile/WordPress-iOS/issues/20843

### PR DESCRIPTION
**Pull request by salimbraksa**
Fixes #20957

## Description

This PR rectifies a crash that occurs during the Weekly Roundup Background Task, resulting from a Core Data Concurrency Violation.

### Root of the Problem

The principal cause of this crash stems from the Weekly Roundup task's method of fetching a list of blogs. It uses the main context, however, this is done from a background thread, resulting in a direct Core Data Concurrency Violation. A screenshot illustrating the issue is included below.

Issue Screenshot

### Proposed Solution

- Modify the code segment that generates the list of blogs so that it conducts the fetch on a derived context's queue.
- Ensure that users of the blogs list access the blogs from the context's queue.
- For those users who no longer have access to the context that initiated the blogs, they will be passed the blogs `NSManagedObjectID`, which will facilitate the creation of new blog instances.

## Test Instructions

<details>
  <summary>How to trigger Weekly Roundup Task</summary>

1. Head to Me > App Settings > Debug > Weekly Roundup then tap Schedule Immediately
2. If the above doesn't work for you, and it didn't work for me even on `trunk`, you can run this code on `AppDelegate`.

```swift
let task = WeeklyRoundupBackgroundTask()
task.run { error in
    DDLogError(error)
} completion: { completed in
    DDLogInfo("Weekly Roundup Background Task Completed: \(completed)")
}
```
</details>

I recommend to perform the following tests on `trunk` to verify the before and after behavior. 

#### Testing whether the crash is resolved

1. Make sure `-com.apple.CoreData.ConcurrencyDebug` is enabled.
2. Build and run Jetpack app.
3. Trigger the the Weekly Round up Task. See **How to trigger Weekly Roundup Task** above.
4. The app shouldn't crash.

#### Testing whether the push notifications appear

1. Make sure you have access to Weekly Roundup enabled sites. 
2. Trigger the the Weekly Round up Task.
3. Wait for a few seconds.
4. **Expect** to receive up to 5 push notifications
5. Tap one of the push notifications.
6. **Expect** to be redirected to Stats screen.

## Regression Notes
1. Potential unintended areas of impact
The Weekly Roundup feature should be re-tested.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Existing Weekly Roundup unit tests and manual testing.

3. What automated tests I added (or what prevented me from doing so)
None. 

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Services/NotificationSettingsService.swift [hunk 1]
```diff
@@ -15,15 +15,15 @@ class NotificationSettingsService {
...
+                  defaultAccount.authToken != nil,
+                  let restApi = defaultAccount.wordPressComRestApi,
+                  restApi.hasCredentials() else {
+                return nil
+            }
+            return restApi
         }
-
         self.init(coreDataStack: coreDataStack, wordPressComRestApi: remoteApi)
     }
```
Comment (salimbraksa) [inline WordPress/Classes/Services/NotificationSettingsService.swift:28]: This initializer was called from a background thread in `WeeklyRoundupBackgroundTask`. This initializer fetches the default account using the main context, which is a Concurrency violation if executed on a background thread.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 2]
```diff
@@ -158,33 +224,40 @@ private class WeeklyRoundupDataProvider {
...
         }
     }
 
-    private func getAllSites() -> Result<[Blog], Error> {
+    static private func weeklyRoundupEnabledSites(
+        settings: [NotificationSettings],
+        sites: [Blog],
+        in context: NSManagedObjectContext) -> [Blog] {
+        return sites.filter { site in
+            guard let siteSettings = settings.first(where: { $0.blogManagedObjectID == site.objectID }),
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: The previous code was:

```swift
guard let siteSettings = settings.first(where: { $0.blog == site })
```

The `settings` is an array of `NotificationSettings` instances. And the type has a `blog` property. Those instances are created in `NotificationSettingsService.getAllSettings` method.

So the problem here is that the comparison `$0.blog == site` is performed on a queue different than `$0.blog` context's queue.

The fix was to compare the object ids `$0.blogManagedObjectID == site.objectID`, which is thread-safe.

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift [hunk 3]
```diff
@@ -15,10 +15,20 @@ open class NotificationSettings {
...
+    /// with `context.existingObject(with: blogManagedObjectID)` to retrieve the corresponding managed object in a thread-safe manner.
     ///
     public let blog: Blog?
 
+    /// The managed object identifier for the associated blog. This property serves as a thread-safe version of the `blog` property.
+    ///
+    /// Rather than directly accessing the `blog` property from a different thread than the one it was created on, use this identifier with
+    /// `context.existingObject(with: blogManagedObjectID)` to retrieve the corresponding managed object in a thread-safe manner.
+    ///
+    public let blogManagedObjectID: NSManagedObjectID?
```
Comment (salimbraksa) [inline WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: More [details](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076/files?diff=unified&w=1#r1263660084) here on why this property was added and how it is used.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 4]
```diff
@@ -7,7 +7,8 @@ private class WeeklyRoundupDataProvider {
 
     // MARK: - Definitions
 
-    typealias SiteStats = [Blog: StatsSummaryData]
+    typealias BlogManagedObjectID = NSManagedObjectID
+    typealias SiteStats = [BlogManagedObjectID: StatsSummaryData]
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:11]: An instance of `SiteStats` type was used in a queue different than the Blog's context queue. I replaced the key type `Blog` with `NSManagedObjectID` for better thread-safety. And users of this instance can fetch the blog instance like this:

```swift
let blog = try? context.existingObject(id) as? Blog
```

[See this example.](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076/files?diff=unified&w=1#diff-613b9e0de8670cd7d053d38d4bbd118d4472713971701edf415c9e493114c468R508)

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 5]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
     func getTopSiteStats(completion: @escaping (Result<SiteStats?, Error>) -> Void) {
-        getSites() { [weak self] sitesResult in
+        self.coreDataStack.performAndSave { [weak self] context in
+            guard let self else {
+                completion(.success(nil))
+                return
+            }
+            self.getTopSiteStats(in: context, completion: completion)
+        }
+    }
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: @crazytonyli This method fetches a list of blogs on a background thread without saving anything. I'm wondering if there is an alternative to `ContextManager.performAndSave` but without the saving part.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 6]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
 
+    /// Returns the end date for the period (the start of the current week).
+    /// This function creates a calendar with a GMT timezone and specifies that it needs a date representing the start of the current week.
+    /// If it can't find a valid date, it returns nil.
+    private func getPeriodEndDate() -> Date? {
+        var gmtCalendar = Calendar(identifier: .gregorian)
+        gmtCalendar.timeZone = TimeZone(secondsFromGMT: 0)!
+        var endDateComponents = DateComponents()
+        endDateComponents.weekday = 1
+        return gmtCalendar.nextDate(after: Date(), matching: endDateComponents, matchingPolicy: .nextTime, direction: .backward)
```
Comment (salimbraksa) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: This is an existing logic and I didn't change anything here. I just extracted this logic from `getTopSiteStats` into its own method.

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift [hunk 7]
```diff
@@ -15,10 +15,20 @@ open class NotificationSettings {
     ///
     public let streams: [Stream]
 
-    /// Maps to the associated blog, if any.
+    /// The associated blog. This property is not thread-safe.
+    ///
+    /// If you need to access this property from a thread different from the one it was created on, don't access it directly. Instead, use the `blogManagedObjectID`
+    /// with `context.existingObject(with: blogManagedObjectID)` to retrieve the corresponding managed object in a thread-safe manner.
     ///
     public let blog: Blog?
```
Comment (crazytonyli) [inline WordPress/Classes/Models/Notifications/NotificationSettings.swift:23]: Can we get rid of this property? Maybe replace it with a `func blog(in context: NSManagedObjectContext)`, which would help us finding out whether the call sites access the `blog` instance safely?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 8]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
+        authToken: String,
+        in context: NSManagedObjectContext,
+        completion: @escaping (Result< StatsSummaryData?, Error>) -> Void
+    ) {
+        guard let dotComID = site.dotComID?.intValue else {
+            completion(.failure(DataRequestError.dotComSiteWithoutDotComID(site)))
+            return
+        }
+        let wpApi = WordPressComRestApi.defaultApi(oAuthToken: authToken, userAgent: WPUserAgent.wordPress())
+        let statsServiceRemote = StatsServiceRemoteV2(wordPressComRestApi: wpApi, siteID: dotComID, siteTimezone: site.timeZone)
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I'm aware that it's a common pattern in the app to create a "Remote" instance and dispose it after use, but IMO it would still be beneficial to reuse it if we can? What do you think if we create one "Remote" instance in the `getTopSiteStats` function and pass it to the `fetchStats` calls, so that we can re-use the `URLSession` instance underneath?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 5 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: We can potentially add an argument to the performQuery function, i.e. `performQuery(fromBackground: Bool = false, ...)`. But I'm not sure how many places would actually need to execute a query from a background thread. Blog reminder probably is a outlier where it needs to execute intense queries.

BTW, the saving part of `performAndSave` would not run, if there is no thing to be saved.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 9]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
+    /// If it encounters any error during fetching, it calls the completion handler with an appropriate error object.
+    /// The completion handler is executed in the same queue as the provided `NSManagedObjectContext`.
+    ///
+    /// **Note:** The completion handler is executed on the context's queue.
+    private func fetchStats(
+        for site: Blog,
+        endingOn periodEndDate: Date,
+        authToken: String,
+        in context: NSManagedObjectContext,
+        completion: @escaping (Result< StatsSummaryData?, Error>) -> Void
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: There is an extra space after `Result< `.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 10]
```diff
@@ -136,19 +202,19 @@ private class WeeklyRoundupDataProvider {
...
-    private func getSites(result: @escaping (Result<[Blog], Error>) -> Void) {
+    private func getSites(in context: NSManagedObjectContext, result: @escaping (Result<[Blog], Error>) -> Void) {
 
-        switch getAllSites() {
+        switch getAllSites(in: context) {
         case .success(let sites):
-            filterCandidateSites(sites, result: result)
+            filterCandidateSites(sites, in: context, result: result)
         case .failure(let error):
             result(.failure(error))
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: The `result` closure in the `success` case is called from the `context` queue, I think we should do the same in the `failure` case here, to keep the behaviour consistent:
```suggestion
            context.perform {
                result(.failure(error))
            }
```

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 11]
```diff
@@ -158,33 +224,40 @@ private class WeeklyRoundupDataProvider {
             return
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:182]: The `result` closure before the return statement should be called from the `context` queue too?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 12]
```diff
@@ -158,33 +224,40 @@ private class WeeklyRoundupDataProvider {
...
-                return sitePreferences["weekly_roundup"] ?? true
+            context.perform {
+                let weeklyRoundupEnabledSites = Self.weeklyRoundupEnabledSites(settings: settings, sites: sites, in: context)
+                result(.success(weeklyRoundupEnabledSites))
             }
-
-            result(.success(weeklyRoundupEnabledSites))
         } failure: { (error: NSError?) in
             let error = DataRequestError.filterWeeklyRoundupEnabledSitesError(error)
             result(.failure(error))
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:197]: The `result` closure here should be called from the `context` queue too?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 13]
```diff
@@ -468,6 +537,27 @@ class WeeklyRoundupBackgroundTask: BackgroundTask {
         operationQueue.addOperation(completionOperation)
     }
 
+    // MARK: - Helpers
+
+    private func scheduleDynamicNotification(site: Blog, stats: StatsSummaryData, completion: @escaping (Result<Void, Error>) -> Void) {
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: What do you think we pass the blog instance's `NSManagedObjectID` as argument and let the function query the blog instance itself? That'll prevent this function from being called from a queue that's not bound to the Blog argument.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 14]
```diff
@@ -468,6 +537,27 @@ class WeeklyRoundupBackgroundTask: BackgroundTask {
...
+        let dotComID = site.dotComID?.intValue
+        self.notificationScheduler.scheduleDynamicNotification(
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I think we can take a small step further to replace this function's `Blog` argument with site title and dotCom id. IMO, it's generally a good idea to _not_ pass `NSManagedObject` around.

**Review by crazytonyli — CHANGES_REQUESTED** [review]
Thanks for making the changes! The convention of executing callback from given context queue has made the code much easier to navigate 👍. It's just unfortunate that we have to be mindful to ensure the convention is implemented in all cases.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 9 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolved in fac2f074ab1fb0a9832ef449b0fe2ee37df8d99c

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 13 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolved in 44b82c7378b8c3bba2f167cd1dfeabd4ddff4ed1

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 14 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolved in 44b82c7378b8c3bba2f167cd1dfeabd4ddff4ed1

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 8 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: > so that we can re-use the URLSession instance underneath?

I'm not sure I understand this part, but here is a commit ae7a3ef7d9db5439aeea449d07afd808eb976554 passing the service instance to `fetchStats` method. Let me know if I understood your suggestion correctly.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 10 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Good catch, I focused on the `success` case and forgot about the `failure` case.

I resolved the issue in 0659e51f8f9af011561d808846b7fd4b229fd7b9 but I took a different approach. Instead of wrapping each individual `result(...)` call in `context.perform`, I passed in a context-aware, thread-safe `result` callback. Like this:

```swift
let result = { ... }

self.getSites(in: context) { sitesResult in
   context.perform {
       result(sitesResult)
    }
}
```

This ensures the `result` callback is always called on the context's queue.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 11 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:182]: See https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1267095822

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 12 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:197]: See https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1267095822

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 10 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I think this problem can be generalized like this:

Let's say we have an async function `foo`.

```swift
func foo(in context: NSManagedObjectContext, completion: () -> Void)
```

**The question is, who should be responsible for calling the `completion` on the context queue?**

And in my opinion, the answer depends on how many times `foo` function is called:

1. If `foo` is frequently called, it makes sense to incorporate `context.perform` directly within the `foo` function. This way, anyone using `foo` doesn't have to repeatedly call `context.perform` each time they use it.
2. But, if `foo` is a single-use function, like `getSites`, the responsibility of invoking `context.perform` can fall on the caller.

What do you think?

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 7 above)
Comment (salimbraksa) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:23]: Making this change would impact some code in `NotificationSettingDetailsViewController`, which is outside the scope of this PR. But I totally agree with you on removing the `blog` property, I'll open a new PR addressing this feedback.

Just to make sure I understand your suggestion, the implementation of `blog(in:)` should look like this?

```swift
func blog(in context: NSManagedObjectContext) -> Blog? {
      return context.existingObject(self.blogManagedObjectID) as? Blog
}
```

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 10 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I think the difficult part is not defining or implementing these conventions, rather it's the fact that we need to _remember_ these conventions. And, it's easy to miss code path where accidentally breaks these conventions.

Maybe we can take advantage of Swift's language feature to enforce these rules. Something like this:

```swift
protocol CallbackExecutor {
    func invokeCallback(_ closure: @escaping () -> Void)
}

extension DispatchQueue: CallbackExecutor {
    func invokeCallback(_ closure: @escaping () -> Void) {
        async {
            closure()
        }
    }
}

extension NSManagedObjectContext: CallbackExecutor {
    func invokeCallback(_ closure: @escaping () -> Void) {
        perform(closure)
    }
}

struct AsyncCallback<Arguments> {
    var executor: CallbackExecutor
    var closure: (Arguments) -> Void

    func invoke(with args: Arguments) {
        executor.invokeCallback {
            closure(args)
        }
    }

    static func queue<Arguments>(_ queue: DispatchQueue = .global(), closure: @escaping (Arguments) -> Void) -> AsyncCallback<Arguments> {
        .init(executor: queue, closure: closure)
    }

    static func context<Arguments>(_ context: NSManagedObjectContext, closure: @escaping (Arguments) -> Void) -> AsyncCallback<Arguments> {
        .init(executor: context, closure: closure)
    }
}

// Example:
func getSite(completion: AsyncCallback<Int>) {
    // ...
}

getSite(completion: .context(context, closure: { value in print(value) }))
```

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 7 above)
Comment (crazytonyli) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:23]: Yep. Hope that function should work and should be safer than storing a `Blog` instance.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 8 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: What I wanted to suggest is using one `StatsServiceRemoteV2` instance to make HTTP API calls, instead of creating many instance in the for loop. `StatsServiceRemoteV2` uses `URLSession` underneath. In theory, reusing one `URLSession` instance to make HTTP request to one endpoint is more performant than using multiple instances.

However, I just noticed that `StatsServiceRemoteV2` requires a site id to initialize. We kind of have to create multiple instances per site due to this constraint, unfortunately. Feel free to ignore my previous comment.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 15]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
-
-                        completion(.success(bestBlogStats))
+                    group.leave()
+                }
+                guard let self else {
+                    return
+                }
+                switch result {
+                case .failure(let error):
+                    self.onError(error)
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:101]: I'm a little bit confused by this function. When an error occurs, should `onError` be called, or should `completion` block be called, or maybe both? Also, ifHTTP API calls fail for all sites (or more than one site), this `onError` closure will be called multiple times. Is that expected?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 16]
```diff
@@ -34,89 +35,154 @@ private class WeeklyRoundupDataProvider {
...
+    ///
+    /// **Note:** The completion handler is executed on a background queue.
     func getTopSiteStats(completion: @escaping (Result<SiteStats?, Error>) -> Void) {
-        getSites() { [weak self] sitesResult in
+        self.coreDataStack.performAndSave { [weak self] context in
+            guard let self else {
+                completion(.success(nil))
+                return
+            }
+            self.getTopSiteStats(in: context, completion: completion)
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: This context intance is passed on to many functions, most of which runs asynchronously. There are two issues I can see here:

First, it's best that we don't let the context object created by `performAndSave` to live outside of the `performAndSave` scope: When `performAndSave` exits, we should stop using the context object. Otherwise, we can't ensure changes made to the context object is saved by `performAndSave`.

Second, I don't think we _need_ to use one single context object across that many functions. For example, `fetchStats(for:endingOn:in:with:completion:)` doesn't need a `context` argument. It can accept a site id argument instead of a `Blog` instance. `filterWeeklyRoundupEnabledSites(_:in:result:)` also doesn't need a `context` argument. It can accept a list of `NSManagedObjectID` and returns a list of `NSManagedObjectID` to the result closure. The same changes can probably be made to most of the other functions that takes a `context` argument.

**Review by crazytonyli — CHANGES_REQUESTED** [review]

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 7 above)
Comment (salimbraksa) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:23]: Sounds good, I'll open a new PR addressing this change.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 17]
```diff
@@ -34,85 +36,142 @@ private class WeeklyRoundupDataProvider {
...
+    ///
+    /// **Note:** The completion handler is executed on the context's queue.
+    private func getTopSiteStats(
+        from sites: [Blog],
+        in context: NSManagedObjectContext,
+        completion: @escaping (Result<SiteStats?, Error>) -> Void
+    ) {
+        guard let periodEndDate = Self.makePeriodEndDate() else {
+            DDLogError("Something's wrong with the period end date selection.")
             return
```
Comment (hassaanelgarem) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:74]: ❓ Do we need to call the completion handler here?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 18]
```diff
@@ -34,85 +36,142 @@ private class WeeklyRoundupDataProvider {
...
 
+    // MARK: API
+
+    /// Fetches the top site statistics from all available sites in the provided context.
+    ///
+    /// This method retrieves all sites in the given context, then fetches the weekly stats
+    /// for each site. The result, which includes the top 5 sites based on the received stats,
+    /// is returned through the provided completion handler.
+    ///
+    /// **Note:** The completion handler is executed on a background queue.
```
Comment (hassaanelgarem) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: 💡 I know this can be bigger than the scope of this PR, but I think we should avoid leaking background threads outside of their corresponding classes. Adding a note in the documentation is nice for sure, but since we're not passing back managed objects, then it would be better to default to communicating on the main thread.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 17 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:74]: @hassaanelgarem Good catch, It wasn't in the previous implementation but I agree we should call the completion handler there.

Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:74]: Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/21076/commits/eebf90cd1ab03d1a2f9f4b38427bdb7a18e03a96

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 15 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:101]: This `onError` closure is inherited from the previous implementation. And honestly I find having both `onError` and a `completionHandler` a bit confusing.

This `onError` closure comes from the block we pass to `WeeklyRoundupBackgroundTask.run` method. See the following screenshot.



The difference between `onError` and `completionHandler` is that `onError` is called when the task fails to fetch the stats of a site. Instead of interrupting the whole task because of a single site failure, the error is reported through that `onError` and the task continues.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 16 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: > First, it's best that we don't let the context object created by performAndSave to live outside of the performAndSave scope: When performAndSave exits, we should stop using the context object. Otherwise, we can't ensure changes made to the context object is saved by performAndSave.

Good point 👍 

> Second, I don't think we _need_ to use one single context object across that many functions. For example, `fetchStats(for:endingOn:in:with:completion:)` doesn't need a `context` argument. It can accept a site id argument instead of a `Blog` instance. `filterWeeklyRoundupEnabledSites(_:in:result:)` also doesn't need a `context` argument. It can accept a list of `NSManagedObjectID` and returns a list of `NSManagedObjectID` to the result closure. The same changes can probably be made to most of the other functions that takes a `context` argument.

I attempted to implement this suggestion but encountered more obstacles that necessitated further refactoring. Here's a brief recap of what I initially set out to do and what I ended up doing:

Initially, I substituted `NSManagedObject` with `NSManagedObjectID` in the `filterWeeklyRoundupEnabledSites` method as you suggested. You were correct, the filtering logic doesn't necessitate the entire `Blog` instance.

However, this method has to return a list of `Blog` through its `result` completion handler.

```swift
result(.success(weeklyRoundupEnabledSites))
```

Thus, I replaced `NSManagedObject` with `NSManagedObjectID` throughout the entire call-stack. In essence, this change propagated to all other methods.

The issue arose when the following two methods needed some `Blog` properties to function:

1. `static private func makeRemoteStatsService(for site: Site)`

This requires `site.account.authToken` and `site.timeZone`.

2. `fetchStats(for:endingOn:with)`

This requires `site.dotComID` because it is passed through an error.

Admittedly, it would be possible to use `coreDataStack.performAndSave` to retrieve a `Blog` instance, but this doesn't seem efficient as it would send N queries to Core Data (where N represents the number of blogs). In contrast, the previous approach only required one query to fetch the entire list of blogs.

Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Now, as for what I ended up implementing, when fetching the list of `Blogs`, I mapped the result to a plain, context-free `Site` struct. Like this:

```swift
private struct Site {
    let managedObjectID: NSManagedObjectID
    let authToken: String?
    let dotComID: Int?
    let timeZone: TimeZone
    let isAdmin: Bool
    let isAutomatticP2: Bool

    init(blog: Blog) {
        self.managedObjectID = blog.objectID
        self.authToken = blog.account?.authToken
        self.dotComID = blog.dotComID?.intValue
        self.timeZone = blog.timeZone
        self.isAdmin = blog.isAdmin
        self.isAutomatticP2 = blog.isAutomatticP2
    }
}

private func getAllSites(in context: NSManagedObjectContext) -> Result<[Site], Error> {
    // ...
    let result = try context.fetch(request)
    let sites = result.map { Site(blog: $0) }
    // ...
}
```

Since `Site` is a just a plain struct and the list is immutable , then we can pass it around threads without issues. Now the `context` is removed from all methods except the one responsible for fetching the sites.

Here is the commit 5d2364ab12443a0541a4386ce5837db1fff9e584 that implements the changes

Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I realize this solution isn't very elegant, but if there aren't any major issues, I propose we proceed with this Pull Request. We can refine and improve it in future Pull Requests. 🙏

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 18 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/21076/commits/8d98c2b2a3f1d31f37df81179d2c1c65bc786109

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 3 above)
Comment (kean) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: Sorry, I'm a bit late with this comment, but I just noticed it in my notifications.

The documentation comment about the `blog` property applies to any managed object properties, so it feels a bit redundant. What you would normally want to do if you need to access the `blog` property from a different thread is re-fetch the `notifications` object itself first:

```swift
let settingsID = settings.objectID
context.perform {
    let settings = try? context.existingObject(with: settingsID)
    let blog = settings.blog // Now you can access the associated blog safely
}
```

The main advantage is that this way, there is no need to duplicate data (`blogManagedObjectID`).

P.S. I saw the other comments, and it's clear that there are some challenges with reworking this, so feel free to disregard this. A nice workaround will do if it fixes the issue. But ideally, I would confine the entire `WeeklyRoundupDataProvider` to either the main thread or the background context.

Comment (salimbraksa) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: You're right, @kean. If `NotificationSettings` was a managed object, any of its properties, including `blogManagedObjectID`, wouldn't be safe to access from a different thread. But in this situation, `NotificationSettings` isn't a managed object, so it's safe to access its properties except the `blog` property.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 16 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: That looks awesome. The functions look super clean. Thanks for making the changes!

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 19]
```diff
@@ -135,20 +155,24 @@ private class WeeklyRoundupDataProvider {
...
+            guard let self else {
+                result(.success([]))
+                return
+            }
+            switch getAllSites(in: context) {
+            case .success(let sites):
+                filterCandidateSites(sites, result: result)
+            case .failure(let error):
+                result(.failure(error))
+            }
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:169]: What do you think we call the `filterCandidateSites(sites, result: result)` outside of the `performAndSave` function, considering it runs asynchronously and doesn't need a context object? We can simply move the switch case out:

```swift
let allSites = coreDataStack.performQuery { self.getAllSites(in: $0) }
switch allSite {
// ...
}
```

BTW, I think it's okay to use performQuery in this case? The query traverses `Blog` models, which should finish pretty quickly considering there shouldn't be many `Blog` in the database?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 20]
```diff
@@ -427,25 +511,15 @@ class WeeklyRoundupBackgroundTask: BackgroundTask {
...
-                    periodEndDate: self.currentRunPeriodEndDate()
-                ) { result in
-
-                    switch result {
-                    case .success:
-                        self.eventTracker.notificationScheduled(type: .weeklyRoundup, siteId: site.dotComID?.intValue)
-                    case .failure(let error):
-                        onError(error)
+                self.coreDataStack.performAndSave { context in
+                    self.scheduleDynamicNotification(siteID: siteID, stats: stats, in: context) { result in
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: We can remove the context argument from the `scheduleDynamicNotification` function, and let the function itself uses `coreDataStack.performQuery` to find the `Blog` instance using the `siteID` argument.

**Review by crazytonyli — CHANGES_REQUESTED** [review]
Thanks for exploring my suggestions! I think `WeeklyRoundupBackgroundTask` is in a really good place now, in terms of dealing with Core Data. 👍

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 19 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:169]: @crazytonyli Yes that should work, but I thought since this is a "background task", it would be great to execute all operations on the background. 

Also, I don't know how many blogs users have but, I know A11ns have lots of blogs ( including Matt ). Though, even if a user has a 100 blogs, I don't think that would significantly impact the performance. But I thought it wouldn't hurt to fetch those blogs from the background.

I'm not sure if you've come across this post ( [Core Data Performance: 6 tips you should know](https://www.avanderlee.com/swift/core-data-performance/) ) before, but the author ( a known developer in the iOS Community ) recommends to use background contexts as much as possible. 

That being said, is there a particular reason on why fetching those blogs on the main thread is better than fetching them from the background thread?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 20 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: @crazytonyli Same question as the one from this [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1268800180). Is there a particular reason why fetching the blog from the main thread is a better approach? Even though this is a "background task".

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 19 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:169]: > Yes that should work, but I thought since this is a "background task", it would be great to execute all operations on the background.

If I understand correctly, ["background task"](https://developer.apple.com/documentation/backgroundtasks) in here means a task that runs during the app is the background, not a task that executing in non-main threads?

But I agree. We don't necessary need to use the main context to query. That makes me think we should have an option to run `performQuery` in a background context, or outright changing it to use a background context. Anyway, that's probably a bigger and unrelated change.

> That being said, is there a particular reason on why fetching those blogs on the main thread is better than fetching them from the background thread?

Mainly because what we do in this class here are querying, and I think `performQuery` has the right semantic for it.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 20 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: I have answered the question of `performAndSave` or `performQuery` in https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1268829526. What do you think removing the context argument from `scheduleDynamicNotification`?

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 3 above)
Comment (kean) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: Oh, you are right. I knew I had misunderstood something. I assumed that was also a managed object. 

Is there a way to remove the `blog` property entirely and keep only the new `blogManagedObjectID` property?

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 19 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:169]: I agree`performQuery` has the right semantic, that's what I asked you in this [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1265634985) if there is a read-only equivalent of `performAndSave`. That's because I was looking for an API that queries data on the **background thread** and the closest thing is `performAndSave`. 

> That makes me think we should have an option to run performQuery in a background context, or outright changing it to use a background context. 

That would be great. I think we should even make it standard querying data from the background thread whenever possible. Performing core data fetches on the main thread might be contributing to those "App Hangs" errors.

That being said, are you okey if I keep `performAndSave` in this PR for now? I can refactor it later once we add an async version of `performQuery`.

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 20 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: > What do you think removing the context argument from scheduleDynamicNotification?

Sounds good, I'll make the change tomorrow.

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 3 above)
Comment (salimbraksa) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: > Is there a way to remove the blog property entirely and keep only the new blogManagedObjectID property?

Yes, that's the plan. See this [discussion](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1266013556).

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 12 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:197]: Resolving this conversation as this change is no longer needed. See this [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1267526635).

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 11 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:182]: Resolving this conversation as this change is no longer needed. See this [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1267526635).

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 10 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolving this conversation as this change is no longer needed. See this [comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/21076#discussion_r1267526635).

File: WordPress/Classes/Models/Notifications/NotificationSettings.swift (hunk 3 above)
Comment (kean) [reply WordPress/Classes/Models/Notifications/NotificationSettings.swift:30]: Good stuff!

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 20 above)
Comment (salimbraksa) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift]: Resolved in f2858c9088c6109b4ec266208c650891298e7a36

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 21]
```diff
@@ -34,86 +37,103 @@ private class WeeklyRoundupDataProvider {
...
+        service.getData(for: .week, endingOn: periodEndDate, limit: 1) { (timeStats: StatsSummaryTimeIntervalData?, error) in
+            guard let timeStats = timeStats else {
+                if let error = error {
+                    completion(.failure(DataRequestError.errorRetrievingStats(site.dotComID, error: error)))
+                } else {
+                    completion(.failure(DataRequestError.unknownErrorRetrievingStats(site.managedObjectID)))
+                }
+                return
             }
+            completion(.success(timeStats.summaryData.first))
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:136]: Nitpick: It's probably just me, but I find nested guard and if is hard to follow. On top of that, we need to make sure the `completion` must be called once and once only. What do you think we refactor it a little bit into something like this?

```swift
let result: Result<StatsSummaryData?, Error>
if let error {
  result = .failure(.errorRetrieving..)
} else if let timeStats {
  result = .success(...)
} else {
  result = .failure(unknownError...)
}
completion(result)
```

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift (hunk 19 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:169]: Sounds good.

For your consideration, here is an alternative way to implement this function, where the Core Data query and using the query result are separated:

```swift
// pseudo and poorly-formatted code :-)
coreDataStack.performAndSave({ self.getAllSites(in: $0)}, completion: { allSites in
  switch allSites {
    case .success(): filterCandidateSites(...)
    case .failure(error): result(.failure(error))
  }
}, queue: .global())
```

File: WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift [hunk 22]
```diff
@@ -468,6 +540,43 @@ class WeeklyRoundupBackgroundTask: BackgroundTask {
...
+            ) { result in
+                switch result {
+                case .success:
+                    self.eventTracker.notificationScheduled(type: .weeklyRoundup, siteId: dotComID)
+                    completion(.success(()))
+                case .failure(let error):
+                    completion(.failure(error))
+                }
+            }
+        }
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift:577]: Similar suggestion as above:

```swift
coreDataStack.performAndSave({
  let site = try $0.existingObject(...)
  guard let dotComID = ... {
     throw ...
  }
  return (site.title,dotComID)
}, completion: { result in
  switch result {
  case let .success(title, dotComID):
    self.notificationScheduler.schedule(....)
  case let .failure(error):
    completion(.failure(error))
  }
}, on: .global())
```

**Review by crazytonyli — APPROVED** [review]
Thanks for taking my suggestions! I have added a couple more nitpicks 😸
