### PR TITLE
Quick Start for Existing Users: Add media upload tour

### LINKED ISSUE #386: Empty view incorrect placement
## Description
The empty view doesn't fill the whole screen and is not centered.

## Steps to reproduce
1. Run WPiOS
2. Switch to a site that has no media uploaded
3. Open Media
4. Observe that the custom empty view is misplaced
5. Upload an image
6. Type in anything in the search bar till no results match
7. Observe that the no results label is misplaced.

## Expected behavior
Empty view to be correctly placed and centered within the picker view.

## Screenshots
No Media | No Search Results
-|-
EmptyMediaIssue|Simulator Screen Shot - iPhone 13 Pro - 2022-04-28 at 06 49 59

**Tested on**
 - Device: iPhone 13 Pro / Simulators
 - OS: iOS 15.4

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Part of #18388

## Description
- Added new Media upload tour
    - First step depends on where the tour is triggered from
        - Site menu: Point to media menu item, and vertically scroll to it
        - Dashboard: Point to media quick action button, and horizontally scroll to it 
    - Second step points to add media button
- Now we always show the media button, even if there's media available (Ref: p1651124342417449-slack-C027K4MNPGQ)
- This PR uses a beta version of `MediaPicker-iOS` that fixes https://github.com/wordpress-mobile/MediaPicker-iOS/issues/386

 Step 1 Menu | Step 1 Home | Step 2 with media | Step 2 no media
-- | -- | -- | --
Step1-menu|Step1-home|Step2-withmedia|Step2-nomedia

### Initial screen: Site Menu (With media)

1. Make sure the initial screen is site menu
2. Switch to a site that has media already uploaded
3. Enable quick start for existing site from debug menu
4. Start media upload task
5. Make sure notice gets dispalyed with correct copy
6. Make sure spotlight appears over media item and that the screen autoscrolls to it
7. Tap on media item
8. Make sure the second notice gets dispalyed with correct copy
9. Make sure spotlight is added to the add button
10. Tap on the add button
11. Make sure the notice is dismissed
12. Navigate back to site menu
13. Make sure media task is marked as completed

### Initial screen: Home (With media)

1. Make sure the initial screen is Home
2. Switch to a site that has media already uploaded
3. Enable quick start for existing site from debug menu
4. Start media upload task
5. Make sure notice gets dispalyed with correct copy
6. Make sure spotlight appears over media quick action button and that the screen autoscrolls to it
7. Tap on media button
8. Make sure the second notice gets dispalyed with correct copy
9. Make sure spotlight is added to the add button
10. Tap on the add button
11. Make sure the notice is dismissed
12. Navigate back to site menu
13. Make sure media task is marked as completed14. 

### No Media

1. Switch to a site that has no media uploaded
2. Enable quick start for existing site from debug menu
3. Start media upload task
4. Navigate to media
5. Make sure the second notice gets dispalyed with correct copy
6. Make sure the add button is visibile and a spotlight is added to it
7. Tap on the add button OR the "Upload Media" button
8. Make sure the notice is dismissed in both cases
9. Navigate back to site menu
10. Make sure media task is marked as completed

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h [hunk 1]
```diff
@@ -74,6 +74,8 @@ typedef NS_ENUM(NSInteger, QuickStartTourElement) {
     QuickStartTourElementNotifications = 23,
     QuickStartTourElementSetupQuickStart = 24,
     QuickStartTourElementRemoveQuickStart = 25,
+    QuickStartTourElementMediaScreen = 26,
+    QuickStartTourElementMediaAdd = 27,
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h]: MediaUpload might be a better name, wdyt?
```suggestion
    QuickStartTourElementMediaUpload = 27,
```

File: WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift [hunk 2]
```diff
@@ -386,6 +386,32 @@ struct QuickStartNotificationsTour: QuickStartTour {
...
+    let suggestionNoText = Strings.notNow
+    let suggestionYesText = Strings.yesShowMe
+    let possibleEntryPoints: Set<QuickStartTourEntryPoint> = [.blogDetails, .blogDashboard]
+
+    var waypoints: [WayPoint] = {
+        let step1DescriptionBase = NSLocalizedString("Select %@ to see your current library.", comment: "A step in a guided tour for quick start. %@ will be the name of the item to select.")
+        let step1DescriptionTarget = NSLocalizedString("Media", comment: "The menu item to select during a guided tour.")
+        let step1: WayPoint = (element: .mediaScreen, description: step1DescriptionBase.highlighting(phrase: step1DescriptionTarget, icon: .gridicon(.image)))
+
+        let step2DescriptionBase = NSLocalizedString("Select %@to upload media. You can add it to your posts / pages from any device.", comment: "A step in a guided tour for quick start. %@ will be a plus icon.")
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift:390]: [Q] Is it intentional that there no space between the "%@" and the "to"?

File: WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift [hunk 3]
```diff
@@ -142,12 +154,18 @@ class MediaLibraryViewController: WPMediaPickerViewController {
 
             var barButtonItems = [UIBarButtonItem]()
 
-            if blog.userCanUploadMedia && assetCount > 0 {
-                let addButton = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(addTapped))
+            if blog.userCanUploadMedia {
+                addButton.spotlightOffset = Constants.addButtonSpotlightOffset
+                let config = UIImage.SymbolConfiguration(textStyle: .body, scale: .large)
+                let image = UIImage(systemName: "plus", withConfiguration: config) ?? .gridicon(.plus)
```
Comment (momo-ozawa) [inline WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift:160]: [Q] Any particular reason we're using the system image over the gridicon?

**Review by momo-ozawa — COMMENTED** [review]
Works as described! 

- Looks like you need to fix `QuickStartFactoryTests`
- Once you release the new `WPMediaPicker` you can point to the released version before merging this PR

File: WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift (hunk 2 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift:390]: It is yes.
`String.highlighting` adds a space between the title and the icon passed. Given that the title is empty in this case, this means `String.highlighting` will add an extra space either way.

Removing the space from the base sting was to mitigate this issue. This was simpler than modifying `String.highlighting` to handle this specific case.

File: WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift (hunk 3 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift:160]: We were using the system's default button. Since I had to manually create the button to add the spotlight view, I tried (to the best of my ability) to maintain the same look as before. I found that the plus grid icon was a bit thicker than the system icon.

Grid Icon | System
-|-
GridIcon|System

File: WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h]: Done! 724a60ded182b0b18ee6a76b41d839b6ae7a77b2

**Comment by hassaanelgarem** [comment]
@momo-ozawa 
> Looks like you need to fix QuickStartFactoryTests

Fixed in 913e67bf821e7a060da1662222d823d53bbd3e5f

> Once you release the new WPMediaPicker you can point to the released version before merging this PR

Done in a91b3b59b2708c93274135773c019254fd2d9dc2

**Review by momo-ozawa — APPROVED** [review]
Looking great! Can you also update the release notes? Otherwise, LGTM!
