### PR TITLE
Stop using attachments to post has possible featured images.

### LINKED ISSUE #3612: Attached image not in a gallery is used as a featured image
When you have an attached image which is not inserted a post, it shows up as a featured image on the iOS app. This seems to happen only when other images are added to the post as a gallery.

Steps to reproduce:
1. Upload 3 images.
2. Create a gallery with 2 of the images, leaving the last uploaded image.
3. Publish the post.
4. View the post on your Reader feed. The last image which in not included in the post will show up as a featured image.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #3612

Sometimes images are attached and then removed from the content, so they should'n be used as possible feature images.

To test:
 - Launch the app
 - Create a new post
 - Tap on add media and select one new image
 - After the image is uploaded remove it from the post content
 - Save or Publish the post
 - Check that in the post list the image don't shows up

Needs review: @aerych

### CODE REVIEW

**Comment by aerych** [comment]
Hiya @SergioEstevao 

There are situations where we want/need to check the attachments dictionary for an image to display. 

One example: 
- In wp-admin create a new post.
- Add a title and text. 
- Tap to add media, select the option to add a gallery and now upload several images to use in the gallery. These images will be attachments to the post. 
- Publish the post. 

When we fetch this post (because we're fetching with an edit context) the only way to get an image to show is from the list of attachments. 

Another example:
- Create a new post and upload several individual images (not a gallery) insert these images as thumbnails. Make sure your thumbnail width is less than 150px. 

Check the post in the reader.  The reader won't consider any of these images as displayable because of the width specified in the image tag, however, the attachment dictionary reports the actual size and the image can still be featured. 


Rather than removing the attachment checks completely, I think we need to make the check a little smarter so it ignores attachments not contained in post content, either by checking attachment ID or url.

**Comment by SergioEstevao** [comment]
@aerych can we add a check for gallery short codes on content, get the media ids on the content, and match to attachment ids?

**Comment by aerych** [comment]
We could do that if it doesn't add any significant overhead.  Its kind of a minor issue so we could also close it as won't fix and ask users to just detach orphaned images.

**Comment by SergioEstevao** [comment]
>
>  detach orphaned images.


At the moment they cannot do this in the app. Even in Calypso they cannot
do this!

**Comment by aerych** [comment]
> At the moment they cannot do this in the app. Even in Calypso they cannot do this!

Right. Afaik the only (easy) way to do this is via the Media menu in wp-admin, by choosing a list view and clicking the "detach" link.   Not very intuitive at all, to be sure.

**Comment by SergioEstevao** [comment]
@aerych ready for another look, I restored the use of attachments on the Reader posts.
 I also added an extra check for galleries ids on the post list.

File: WordPress/Classes/Utility/DisplayableImageHelper.m [hunk 1]
```diff
@@ -109,6 +109,34 @@ + (NSString *)searchPostContentForImageToDisplay:(NSString *)content
     return imageSrc;
 }
 
++ (NSSet *)searchPostContentForAttachmentIdsInGalleries:(NSString *)content
+{
+    NSMutableSet *resultSet = [NSMutableSet set];
+    // If there is no image tag in the content, just bail.
```
Comment (aerych) [inline WordPress/Classes/Utility/DisplayableImageHelper.m]: `image tag` => `gallery shortcode` ?

File: WordPress/Classes/Utility/DisplayableImageHelper.m [hunk 2]
```diff
@@ -109,6 +109,34 @@ + (NSString *)searchPostContentForImageToDisplay:(NSString *)content
...
+    if (!content || [content rangeOfString:@"[gallery "].location == NSNotFound) {
+        return resultSet;
+    }
+
+    // Get all the things
+    static NSRegularExpression *regexGallery;
+    static dispatch_once_t onceTokenRegexGallery;
+    dispatch_once(&onceTokenRegexGallery, ^{
+        NSError *error;
+        NSString *galleryPattern = @"(\\[gallery [^]]*\\])";
```
Comment (aerych) [inline WordPress/Classes/Utility/DisplayableImageHelper.m]: Maybe tweak the regex pattern so the capture group is on the IDs.  That would save a bit of work in `idsFromGallery`.  I'm not sure of the exact regex pattern off hand but I *think* it would be something like: 
```
@"\\[gallery[\s\S]+ids=\\"([0-9,]*)\\"[^]]*\\]"
```

File: WordPress/Classes/Services/PostService.m [hunk 3]
```diff
@@ -525,6 +526,16 @@ - (void)updatePost:(AbstractPost *)post withRemotePost:(RemotePost *)remotePost
     post.password = remotePost.password;
     post.post_thumbnail = remotePost.postThumbnailID;
     post.pathForDisplayImage = remotePost.pathForDisplayImage;
+    if (post.pathForDisplayImage.length == 0) {
+        // Let's see if some galleries are available
+        NSSet *mediaIDs = [DisplayableImageHelper searchPostContentForAttachmentIdsInGalleries:post.content];
+        for (Media *media in post.blog.media) {
+            NSNumber *mediaID = media.mediaID;
+            if (mediaID && [mediaIDs containsObject:mediaID]){
```
Comment (aerych) [inline WordPress/Classes/Services/PostService.m]: *super* nitpicky, but maybe a space before the `{`

**Comment by aerych** [comment]
Heya @SergioEstevao  Took the branch for a test drive and it works great.  Very cool. 
I had one suggestion for an optimization and a couple of nitpicks. Up to you if you think its worth the change. :)

**Comment by SergioEstevao** [comment]
@aerych ready for another round of review.

File: WordPress/Classes/Utility/DisplayableImageHelper.m [hunk 4]
```diff
@@ -109,6 +109,34 @@ + (NSString *)searchPostContentForImageToDisplay:(NSString *)content
...
+        NSError *error;
+        NSString *galleryPattern = @"\\[gallery[^]]+ids=\"([0-9,]*)\"[^]]*\\]";
+        regexGallery = [NSRegularExpression regularExpressionWithPattern:galleryPattern options:NSRegularExpressionCaseInsensitive error:&error];
+    });
+
+    // Find all the gallery shortcodes in the content passed.
+    NSArray *matches = [regexGallery matchesInString:content options:0 range:NSMakeRange(0, [content length])];
+
+    for (NSTextCheckingResult *match in matches) {
+        NSString *tag = [content substringWithRange:match.range];
```
Comment (aerych) [inline WordPress/Classes/Utility/DisplayableImageHelper.m]: Cool. So with that updated regex, the NSTextCheckingResult will now return multiple ranges.  The first range, the one referenced by the `match.range` property is for the entire match.  However, we now have a match on just the gallery IDs via `match.rangeAtIndex(1)`.  So we can use that to avoid a lot of the string parsing and other work in `idsFromGallery`.   A very rough example would be: 
```
        NSRange rng = [match rangeAtIndex:1];
        NSString *tag = [content substringWithRange:rng];
        NSArray *arr = [tag componentsSeparatedByString:@","];
        NSMutableArray *idsArr = [NSMutableArray array];
        for (NSString *item in arr) {
            [idsArr addObject:[item numericValue]];
        }
        NSSet *tagIds = [NSSet setWithArray:idsArr];
```

**Comment by SergioEstevao** [comment]
@aerych follow your suggestion above, can you please have another look.

**Comment by aerych** [comment]
Looks good to me! 
:shipit: sir :)
