### PR TITLE
fix: Preview adjusts for device orientation change

### LINKED ISSUE #18483: Post Preview: Rotating during preview load with display zoom can cut off preview
Expected:
For a user who is using display zoom, the preview of a post should not get cut off if the user rotates the device (changing from landscape to portrait) while the preview is loading.

Actual:
In this scenario, the post does get cut off.

https://user-images.githubusercontent.com/103850310/166083152-78faed41-1491-471b-bb61-8155d9da4613.MP4

Setup:
Settings > Display & Brightness > View > Select “Zoomed”

Steps to reproduce:
1. Open post (draft or published, it doesn’t seem to matter)
2. If not already, rotate device into landscape mode
3. Preview
4. While loading, rotate to portrait mode
5. Note that the post gets cut off on the left. Zooming out via gesture does not remedy it, you have to close and re-open preview for it to be properly set in the screen.

Tested on iPhone XS, iOS 15.4.1, WPiOS 19.7.0.2

### PR DESCRIPTION
**Pull request by dcalhoun**
Fixes #18483. After orientation changes, the device width may be too narrow for the existing preview, which causes it to overflow the view. This overflow is more prominent when Display Zoom is enabled, but is present regardless. By resetting the preview width after orientation change, we ensure the preview fits the view. 

<details><summary>Before</summary>

https://user-images.githubusercontent.com/438664/175136889-8e4b3c83-d266-4d49-b15b-9ec5c25353f1.mov

</details>

<details><summary>After</summary>

https://user-images.githubusercontent.com/438664/175137277-42547889-c3a7-4872-83ba-5f55c1d83832.mov

</details>

To test:

> **Note**: It is important to test on both an iPhone and iPad, as the reporting of view dimensions seems to vary between the device types. 

<details><summary>While previewing, rotate from portrait to landscape orientation</summary>

1. Open a published or drafted post.   
1. Position your device in _portrait_ orientation. 
1. Tap the three-dot menu in the top-right of the editor, select _Preview_.
1. Tap the device icon in the bottom-right and select a preview device size.
1. Rotate your device to _landscape_ orientation. 
1. Verify the preview does not overflow the width of the device; the entirety of the preview is visible on the screen.<sup>1</sup> 
1. Rotate your device to _portrait_ orientation. 
1. Verify the preview does not overflow the width of the device; the entirety of the preview is visible on the screen.<sup>1</sup> 
1. Repeat steps 4-8 with each of the preview device sizes available. 

<sup>1</sup> One way to verify the correct display is to again toggle the device away and back to your current preview device, e.g. "mobile" → "desktop" → "mobile" without rotating the device. This will re-render the preview and provide a clear picture as to what the preview should look like. 

</details>

<details><summary>While previewing, rotate from landscape to portrait orientation</summary>

1. Open a published or drafted post.   
1. Position your device in _landscape_ orientation. 
1. Tap the three-dot menu in the top-right of the editor, select _Preview_.
1. Tap the device icon in the bottom-right and select a preview device size.
1. Rotate your device to _portrait_ orientation. 
1. Verify the preview does not overflow the width of the device; the entirety of the preview is visible on the screen.<sup>1</sup> 
1. Rotate your device to _landscape_ orientation. 
1. Verify the preview does not overflow the width of the device; the entirety of the preview is visible on the screen.<sup>1</sup> 
1. Repeat steps 4-8 with each of the preview device sizes available. 

<sup>1</sup> One way to verify the correct display is to again toggle the device away and back to your current preview device, e.g. "mobile" → "desktop" → "mobile" without rotating the device. This will re-render the preview and provide a clear picture as to what the preview should look like. 

</details>

## Regression Notes
1. Potential unintended areas of impact
  The preview web view could experience bugs during rotation or memory leaks from the changes.
2. What I did to test those areas of impact (or what existing automated tests I relied on)
  Manually tested various devices, zoom settings, and multiple rotation events.
3. What automated tests I added (or what prevented me from doing so)
  None, I am interested in recommendations/guidance on if/what automated testing should be added.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift [hunk 1]
```diff
@@ -104,6 +104,17 @@ class PreviewWebKitViewController: WebKitViewController {
             showNoResults(withTitle: Constants.noPreviewTitle)
         }
         setupDeviceLabel()
+
+        NotificationCenter.default.addObserver(self, selector: #selector(orientatedChanged), name: UIDevice.orientationDidChangeNotification, object: nil)
+    }
+
+    deinit {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift]: I _think_ this [isn't required](https://developer.apple.com/documentation/foundation/notificationcenter/1415360-addobserver) but it's one less thing for the system to clean up if we're explicit. 👍 

> If your app targets iOS 9.0 and later or macOS 10.11 and later, you do not need to unregister an observer that you created with this function. If you forget or are unable to remove an observer, the system cleans up the next time it would have posted to it.

**Review by twstokes — APPROVED** [review]
LGTM @dcalhoun, great work! 🚀 

Both tests succeeded for me on an iPhone 12:
- ✅ Change preview device while in landscape orientation
- ✅ Rotate device to landscape orientation with Display Zoom enabled

**Comment by dcalhoun** [comment]
@twstokes after further testing, I identified a scenario where overflowing content still occurred. Namely, when using an iPad Pro 11 inch in landscape orientation, selecting "Desktop" as the preview device, and rotating to portrait orientation. 

Further debugging and research led me to believe the original issue is solely related to orientation changes and unrelated to Display Zoom. I have updated the implementation to use [`viewWillTransition`](https://developer.apple.com/documentation/uikit/uicontentcontainer/1621466-viewwilltransition), which I believe is the most appropriate method. I have also removed previous code attempting to detect the Display Zoom scale. 

I'd appreciate your review again. I updated the PR description and testing instructions to be more robust and provided before/after videos as well.  Thank you for the help and your patience with a bit of back-and-forth. 🙇🏻

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 2]
```diff
@@ -359,9 +359,18 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
 
     /// Sets the width of the web preview
     /// - Parameter width: The width value to set the webView to
-    func setWidth(_ width: CGFloat?) {
+    func setWidth(_ width: CGFloat?, viewSize: CGSize? = nil) {
         if let width = width {
-            widthConstraint?.constant = min(width, view.superview?.frame.width ?? width)
+            var horizontalViewBound: CGFloat
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift]: Nit: This could be a constant.

```suggestion
            let horizontalViewBound: CGFloat
```

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 3]
```diff
@@ -359,9 +359,18 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
 
     /// Sets the width of the web preview
     /// - Parameter width: The width value to set the webView to
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift:361]: Could we add a parameter comment for `viewSize` here? 🙇

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 4]
```diff
@@ -359,9 +359,18 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
...
-    func setWidth(_ width: CGFloat?) {
+    func setWidth(_ width: CGFloat?, viewSize: CGSize? = nil) {
         if let width = width {
-            widthConstraint?.constant = min(width, view.superview?.frame.width ?? width)
+            var horizontalViewBound: CGFloat
+            if let viewWidth = viewSize?.width {
+                horizontalViewBound = viewWidth
+            } else if let superViewWidth = view.superview?.frame.width {
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift:368]: I realized that `view.superview?.frame.width` won't have the "going to" value from `viewWillTransition`, otherwise we could simplify things some. This makes sense. 👍

File: WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift [hunk 5]
```diff
@@ -106,6 +106,11 @@ class PreviewWebKitViewController: WebKitViewController {
         setupDeviceLabel()
     }
 
+    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
```
Comment (twstokes) [inline WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift:109]: Good call going to this class method over the notification. It's a good fit for this case. 👍

File: WordPress/Classes/Utility/WebKitViewController.swift [hunk 6]
```diff
@@ -359,9 +359,18 @@ class WebKitViewController: UIViewController, WebKitAuthenticatable {
 
     /// Sets the width of the web preview
     /// - Parameter width: The width value to set the webView to
-    func setWidth(_ width: CGFloat?) {
+    func setWidth(_ width: CGFloat?, viewSize: CGSize? = nil) {
```
Comment (twstokes) [inline WordPress/Classes/Utility/WebKitViewController.swift]: Nit: If we only need the width from `viewSize`, maybe we should just pass that in?

**Review by twstokes — COMMENTED** [review]
👋 @dcalhoun! Thanks for all your work on this. I've made some comments on the PR and will do device testing now. 🙇

File: WordPress/Classes/Utility/WebKitViewController.swift (hunk 4 above)
Comment (dcalhoun) [reply WordPress/Classes/Utility/WebKitViewController.swift:368]: I interpret your comment to mean no changes are needed here. Please correct me if I am mistaken, however.

Comment (twstokes) [reply WordPress/Classes/Utility/WebKitViewController.swift:368]: Yep! All good. 👍

**Comment by twstokes** [comment]
I tested on an iPhone 12 with and without Display Zoom enabled, as well as an iPad Pro in Simulator and did not spot any issues. 🚀 

✅ While previewing, rotate from portrait to landscape orientation
✅ While previewing, rotate from landscape to portrait orientation

**Review by twstokes — APPROVED** [review]
