### PR TITLE
Fix issues with user profile pictures in Reader

### LINKED ISSUE #23546: The avatar blinks when liking a post in the Reader
### Expected behavior
Avatars should not blink

### Actual behavior
Avatars sometimes blink

There's something wrong with avatars, it's not only that they blink but they're also sometimes missing or incorrect. I've seen all kinds of faces instead of mine. However, this a report for the blinking behavior.

### Steps to reproduce the behavior
1. Use Dark Moder
2. Follow 20-30 sites and start liking their posts
3. You'll notice that most of the times avatars blink when you like but not always

https://martechp2.wordpress.com/wp-content/uploads/2024/09/rpreplay_final1725389293.mp4

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

Jetpack iOS, iPhone 15 Pro

### LINKED ISSUE #23548: When posting a comment, my avatar sometimes turn to other things
### Expected behavior
I should always see my own avatar

### Actual behavior
I sometimes see the default gravatar or the avatar of the previous person who posted a comment

### Steps to reproduce the behavior
Post comments until you see it. It doesn't happen very often so the issue might not be the easiest to reproduce.

Both Veselins are me with another avatar
IMG_9036
IMG_9035

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Jetpack iOS, iPhone 15 Pro

### PR DESCRIPTION
**Pull request by kean**
I identified a few concurrency issues in the Gravatar framework that's currently being used in Reader in a couple of other places. I reported them together with the suggested improvements, but to address the immediate issues, it would be best to switch to the main `ImageDownloader` used by the app.

- Fix https://github.com/wordpress-mobile/WordPress-iOS/issues/23548 (**RCA**: to concurrency and cancellation issues)
- Fix https://github.com/wordpress-mobile/WordPress-iOS/issues/23546 (**RCA**: issue due to the async cache)
- Use our custom `URLCache` for caching avatars (Gravatar no longer pollutes default `URLCache`)
- Add coalescing, background image decompression, proper image view reuse and task cancellation, and a couple of other features added by `ImageDownloader`
- Disable animations when showing avatars (these are only distracting and are no a good fit for scrollable content)
- Improve scrolling performance and image loading performance due to the reduces size on 3x devices

## To test:

- Go to Reader / Comments and check that the avatars are loading

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-iOS/milestone/296">25.4</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/Classes/ViewRelated/Gravatar/UIImageView+Gravatar.swift [hunk 1]
```diff
@@ -52,33 +55,17 @@ extension UIImageView {
         // Calling `layoutIfNeeded()` forces UIKit to calculate the actual size.
         layoutIfNeeded()
 
-        let size = Int(ceil(frame.width * UIScreen.main.scale))
+        let size = Int(ceil(frame.width * min(2, UIScreen.main.scale)))
```
Comment (kean) [inline WordPress/Classes/ViewRelated/Gravatar/UIImageView+Gravatar.swift:58]: 3x is too much for web images.

File: WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import UIKit
+import Gifu
+
+extension UIImageView {
+    @MainActor
+    var wp: ImageViewExtensions { ImageViewExtensions(imageView: self) }
+}
+
+@MainActor
+struct ImageViewExtensions {
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift:11]: I think you can take this a step further to support `ImageView` too. Something like this

```swift
protocol AsyncImageView {
  func controller(_: ImageViewController, state: State)
}

struct ImageViewExtensions<View: AsyncImageView> {
  let view: View
  ...
}

extension ImageView: AsyncImageView { ... }
extension UIImageView: AsyncImageView { ... }
```

File: WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+                gifView.configure(image: image)
+            } else {
+                imageView.image = image
+            }
+        case .failure:
+            break
+        }
+    }
+
+    private static let controllerKey = malloc(1)!
```
Comment (crazytonyli) [inline WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift:56]: This is the first time I see this pattern. The pattern used in most of the code is using the address of a static variable. Like this code:

```swift
private var observerKey = 0

extension StatsForegroundObservable where Self: UIViewController {
    private var enterForegroundObserver: NSObjectProtocol? {
        get {
            objc_getAssociatedObject(self, &controllerKey) as? NSObjectProtocol
        }
        set {
            objc_setAssociatedObject(self, &observerKey, newValue, .OBJC_ASSOCIATION_RETAIN)
        }
    }
}
```

Comment (kean) [reply WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift:56]: It's one of the modern, if that's that the right word, ways to do it. I originally learned about it from Eskimo's [message [here](https://forums.swift.org/t/objc-setassociatedobject-vs-swift/45188/3), and since then shipped it [here](https://github.com/kean/Nuke/blob/0e953da39106db3f989364ba443a8ca12e558668/Sources/NukeExtensions/ImageViewExtensions.swift#L221), so it's been battle tested.

This will produce a warning.

```swift
objc_getAssociatedObject(self, &controllerKey)
```

File: WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift (hunk 2 above)
Comment (kean) [reply WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift:11]: I wanted to avoid introducing a protocol to avoid coupling `ImageViewController` with the UI. It can now be used in SwiftUI and it can be used in other `UIImageView` extensions if needed. I'd keep it as is for now because there is only one method so there is no significant difference whether it's a protocol or a closure.

**Comment by kean** [comment]
I fixed the tests in https://github.com/wordpress-mobile/WordPress-iOS/pull/23597/commits/f13046811834d99f9ab51a1ec721c8d97d7c11e0 by removing the memory cache from the login flow. At this point, you are unlikely to have the image in cache, and these flows are being replaced soon anyway.

I think what we should ultimately do is move `ImageDownloader` and its extensions to a package so that it could be used from anywhere.

File: WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift (hunk 3 above)
Comment (crazytonyli) [reply WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift:56]: I don't think it makes much sense to use `&controllerKey`, given `controllerKey` is already a pointer.

To be honest, both approaches seem a bit strange to me, even though they all make perfect sense.

**Review by crazytonyli — APPROVED** [review]
