### PR TITLE
Fix bottom padding in login on iPhone X

### LINKED ISSUE #8335: NUX: Bottom button and text has too much padding on iPhone X
On the iPhone X, there is too much space above the keyboard when visible:

img_09825dcc0924-1

`SigninKeyboardResponder` probably needs to take the new Safe area layout guides into account.

### PR DESCRIPTION
**Pull request by nheagy**
Fixes #8335

Login buttons now have appropriate padding on iPhone X:

8335 iphone x padding fix

To test:
- Ensure that the login button is in the right place on iOS 11 and 10 devices, on iPhone X, regular iPhone, and iPad

Needs review: @aerych 
Got time for one more before you go?

### CODE REVIEW

File: WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift [hunk 1]
```diff
@@ -148,7 +148,17 @@ extension SigninKeyboardResponder where Self: NUXAbstractViewController {
...
             return view.frame.height - keyboardFrame.minY
         }
-        return keyboardFrame.height
+        var bottomAdjust: CGFloat = 0
+        var heightDelta = keyboardFrame.height
+        if #available(iOS 11, *) {
+            bottomAdjust = view.safeAreaInsets.bottom
+        }
+
+        if keyboardFrame.height > bottomAdjust {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift]: Is there ever a situation where `keyboardFrame.height` is not greater than `bottomAdjust`?  I couldn't seem to find that condition while testing.  Maybe there isn't and we can do away with the conditional?

Comment (aerych) [reply WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift]: Actually, if we can do away with the conditional maybe this could be simplified to 
```
var bottomAdjust: CGFloat = 0
if #available(iOS 11, *) {
    bottomAdjust = view.safeAreaInsets.bottom
}
return keyboardFrame.height - bottomAdjust
```
and save a couple of lines?  It seemed like the value of `bottomAdjust` is either `34` on the X or `0` on everything else.   Just a thought.

Comment (nheagy) [reply WordPress/Classes/ViewRelated/NUX/SigninKeyboardResponder.swift]: Yeah, that definitely works. Missed that last potential refactor 😉

Thanks Eric—wherever you are 😜
