### PR TITLE
Fixes an issue with the tour guide not initializing some values in time.

### LINKED ISSUE #11687: Site Creation: "Upload a site icon" tutorial step not clear.
## Description:

The step that explains to the user how to "Upload a site icon" is not explaining clearly to the user what needs to be tapped.

## Images:

This is how it looks in iOS:

IMG_9C9240FED0E9-1

This is how it looks in Android (notice the blue dot showing where to tap):

Screenshot_20190513-213714

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #11687 

This PR also fixes two issues that could cause the spotlight effect to never go away:

1. If we run the "Upload an Icon" tutorial multiple times in a row without ever tapping the icon.
2. If we run the "Upload an Icon" tutorial and then a different one without ever tapping on the icon.

## Testing:

1. Create a WP.com site.
2. When offered to, request assistance to set the site up.
3. Make sure the spotlight dot effect is visible when the "Upload an Icon" tutorial is running.
4. Try multiple combinations of running "Upload an Icon" tutorial multiple times in a row with and without tapping on the icon.  Make sure it behaves well.
5. Try multiple combinations of running "Upload an Icon" tutorial and other tutorials multiple times in a row with and without tapping on the icon.  Make sure it behaves well.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift [hunk 1]
```diff
@@ -116,7 +116,16 @@ open class QuickStartTourGuide: NSObject {
...
+    /// Starts the specified tour.
+    ///
+    /// - Parameters:
+    ///     - tour: the tour to start.
+    ///     - blog: the blog in which the tour will take place.
+    ///     - immeditately: whether the tour must start immediately or not.  If this is `false`
+    ///         the tour will be initialized but the first step won't be executed.  The caller of
+    ///         this method must also call `run()` to effectively start the tour.
+    ///
+    func start(tour: QuickStartTour, for blog: Blog, immediately: Bool = false) {
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Why add a parameter that is never used? Unless I'm mistaken, after this PR `immediately` is always false.

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift [hunk 2]
```diff
@@ -126,10 +135,26 @@ open class QuickStartTourGuide: NSObject {
...
+            if immediately {
+                showCurrentStep()
+            }
         }
     }
 
+    /// Runs the current tour.  Only works after calling `startTour` with parameter `immediately` set to
+    /// `false`, and if the tour is in the first step.  Otherwise this method will do nothing.
+    ///
+    func run() {
```
Comment (nheagy) [inline WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: `run` is a pretty ambiguous name, and doesn't fit the verbs used elsewhere in this class.

What about putting this guard at the start of `showCurrentStep` instead?

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 1 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Actually this was a mistake in my PR, as the default value was meant to be `true`.  I've just fixed it.

There are two calls to this method.  The one that delays running the tutorial:

https://github.com/wordpress-mobile/WordPress-iOS/blob/e3ee8cd321feb74e37f69d012346aff898a64484/WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift#L102-L107

And the one that I didn't want to modify, which was previously and still is immediate:

https://github.com/wordpress-mobile/WordPress-iOS/blob/e3ee8cd321feb74e37f69d012346aff898a64484/WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift#L104-L107

I could make the immediate one still make both calls if we prefer, but I wanted to bring up both scenarios are currently used.  Thoughts?

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 2 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: I considered using `initialize()` and `start()`, thus removing the `immediate` param and forcing both to always be called (immediately or not, it'd be up to the caller).  Maybe that's a better option?  Any suggestion to make the method names clearer is of course welcome!

As to moving the guard in this method into `showCurrentStep()`, I'm not sure I understand: these methods have different purposes (`showCurrentStep()` should be called for all steps, whereas `run()` should only be called to run the tutorial from the first step forward.  But maybe this point would become less important if we go for something like `initialize` / `start`.

Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Maybe `prepare` and `start`?

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 1 above)
Comment (nheagy) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: I'd prefer that both use the same process to start a tour, as it keeps the API simpler. I'd like to break up `start(tour:blog:)` into two methods. The immediate start version can call both methods in sequence.

I propose:
`start(tour:blog:)` become `prepare(tour:blog:)`
`run()` become `begin()`

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 2 above)
Comment (nheagy) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Yeah, I liked those names. I prefer `begin` to `start` but it's a minor difference—start sounds immediate to me.

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 1 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Changed the process so that it's now the same for both cases.

File: WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift (hunk 2 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift]: Changed to `prepare()` and `begin()`.

**Comment by diegoreymendez** [comment]
@nheagy - Ready for another look.

**Comment by diegoreymendez** [comment]
Oh nm, I missed the approval.  Thanks for the review!
