### PR TITLE
Geolocation post settings ui refresh

### LINKED ISSUE #4597: Geolocation details has wrong bottom bar style
Title has it.  Another one we need to update.

simulator screen shot dec 18 2015 11 13 20 am

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #4597 

Refresh the UI for setting the geo location. See the discussion on the ticket for the changes made.
I also took the opportunity to update some of the code in the LocationServices.

Needs Review: @aerych

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.m [hunk 1]
```diff
@@ -56,6 +62,8 @@ - (void)layoutSubviews
 
     self.mapView.frame = CGRectMake(0.0, 0.0, width, mapHeight);
     self.addressLabel.frame = CGRectMake(labelX, mapHeight, labelWidth, addressLabelHeight);
+    CGSize chevronSize = self.chevron.frame.size;
+    self.chevron.frame = CGRectMake(labelWidth-chevronSize.width, mapHeight+((addressLabelHeight-chevronSize.height)/2), chevronSize.width, chevronSize.height);
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.m]: For improved readability, maybe compose the x and y values in variables, add spaces around the operators and, (I know this is super nitpicky) make the denominator a double instead of an int for type matching?  Something like:
```
CGFloat x = labelWidth - chevronSize.width;
CGFloat y = mapHeight + ((addressLabelHeight - chevronSize.height) / 2.0);
self.chevron.frame = CGRectMake(x, y, chevronSize.width, chevronSize.height);
```

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 2]
```diff
@@ -73,26 +54,31 @@ - (void)viewWillAppear:(BOOL)animated
...
-- (void)setupToolbar
-{
-    UIToolbar *toolbar = self.navigationController.toolbar;
-    toolbar.barTintColor = [WPStyleGuide littleEddieGrey];
-    toolbar.translucent = NO;
-    toolbar.barStyle = UIBarStyleDefault;
-
-    if ([self.toolbarItems count] > 0) {
-        return;
+- (UIBarButtonItem *)refreshButton {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: Nitpicky code style, maybe move the `{` to its own line

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 3]
```diff
@@ -73,26 +54,31 @@ - (void)viewWillAppear:(BOOL)animated
...
     }
+    return _refreshButton;
+}
 
-    self.deleteButton = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"gridicons-trash"] style:UIBarButtonItemStylePlain target:self action:@selector(removeGeolocation)];
-    self.refreshButton = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"gridicons-sync"] style:UIBarButtonItemStylePlain target:self action:@selector(updateLocation)];
-
-    self.deleteButton.tintColor = [WPStyleGuide readGrey];
-    self.refreshButton.tintColor = [WPStyleGuide readGrey];
+- (UIBarButtonItem *)activityItem {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: And here.

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 4]
```diff
@@ -73,26 +54,31 @@ - (void)viewWillAppear:(BOOL)animated
...
+        _activityIndicator = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
+        _activityItem = [[UIBarButtonItem alloc] initWithCustomView:_activityIndicator];
+    }
+    return _activityItem;
+}
 
-    UIActivityIndicatorView *activityView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhite];
-    [activityView startAnimating];
-    self.activityItem = [[UIBarButtonItem alloc] initWithCustomView:activityView];
+- (PostGeolocationView *)geoView {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: Here too

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 5]
```diff
@@ -135,37 +119,66 @@ - (void)updateLocation
     [self refreshView];
 }
 
+- (void)showLocationPermissionDisabled {
+    [self showLocationError:[NSError errorWithDomain:kCLErrorDomain code:kCLErrorDenied userInfo:nil]];
+}
+
+- (void)showLocationError:(NSError *)error {
+    NSString *title = NSLocalizedString(@"Location", @"Title for alert when a generic error happened when trying to find the location of the device");
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: Looks like `PostSettingsViewController` does pretty much the same thing.  Maybe this could be factored out into a helper method (maybe on `LocationService`)?

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 6]
```diff
@@ -135,37 +119,66 @@ - (void)updateLocation
...
+    [alertController addAction:okAction];
+    
+    if (otherButtonTitle) {
+        UIAlertAction *otherAction = [UIAlertAction actionWithTitle:otherButtonTitle style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) {
+            NSURL *settingsURL = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
+            [[UIApplication sharedApplication] openURL:settingsURL];
+        }];
+        [alertController addAction:otherAction];
+    }
+    [self presentViewController:alertController animated:YES completion:nil];
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: To help make this a more generic method you might call `[alertController presentFromRootViewController]` instead.

File: WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m [hunk 7]
```diff
@@ -135,37 +119,66 @@ - (void)updateLocation
...
 
-- (void)refreshToolbar
+- (void)refreshNavigationBar
 {
     UIBarButtonItem *leftFixedSpacer = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:nil];
     UIBarButtonItem *rightFixedSpacer = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:nil];
-    UIBarButtonItem *centerFlexSpacer = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:nil action:nil];
 
     leftFixedSpacer.width = -2.0f;
     rightFixedSpacer.width = -5.0f;
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m]: One of these days.... I swear... I'm going to find all the remaining `f` modifiers and purge them.  Nothing to change here... just ... ranting.

File: WordPress/Classes/Utility/LocationService.m [hunk 8]
```diff
@@ -196,18 +173,8 @@ - (void)locationManager:(CLLocationManager *)manager didFailWithError:(NSError *
...
     [self getAddressForLocation:location];
-#else
-    if (location.horizontalAccuracy > 0 && location.horizontalAccuracy < LocationHorizontalAccuracyThreshold) {
-        [self stopUpdatingLocation];
-        [self getAddressForLocation:location];
-    } else {
-        self.lastUpdatedLocation = location;
-    }
-#endif
 }
```
Comment (aerych) [inline WordPress/Classes/Utility/LocationService.m]: Super cool cleanup of `LocationService` :clap:

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 9]
```diff
@@ -606,48 +618,123 @@ - (UITableViewCell *)configureFeaturedImageCellForIndexPath:(NSIndexPath *)index
...
+    [self presentViewController:alertController animated:YES completion:nil];
+}
+
+- (void)updatePostLocationState:(BOOL)geoLocationOn {
+    if (geoLocationOn && self.locationService.locationServicesDisabled) {
+        [self showLocationError:[NSError errorWithDomain:kCLErrorDomain code:kCLErrorDenied userInfo:nil]];
+    } else if (geoLocationOn && !self.locationService.locationServicesDisabled) {
+        __weak __typeof__(self) weakSelf = self;
+        [self.locationService getCurrentLocationAndAddress:^(CLLocation *location, NSString *address, NSError *error) {
+            __typeof__(self) strongSelf = weakSelf;
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: `__typeof__(self) ` here captures a strong reference to `self`, defeating the purpose of declaring `weakSelf` earlier. Should probably be changed to 
`__typeof__(weakSelf) strongSelf = weakSelf;`

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 10]
```diff
@@ -606,48 +618,123 @@ - (UITableViewCell *)configureFeaturedImageCellForIndexPath:(NSIndexPath *)index
...
+            if (!strongSelf) {
+                return;
+            }
+            if ( error) {
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: Super nitpicky... but... extra space.

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 11]
```diff
@@ -606,48 +618,123 @@ - (UITableViewCell *)configureFeaturedImageCellForIndexPath:(NSIndexPath *)index
...
+
+- (WPTableViewCell *)geoLocationActivityCell {
+    if (!_geoLocationActivityCell) {
+        _geoLocationActivityCell = [[WPTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil];
+        _geoLocationActivityCell.accessoryType = UITableViewCellAccessoryNone;
+        [WPStyleGuide configureTableViewCell:_geoLocationActivityCell];
+        UIActivityIndicatorView *spinner = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
+        _geoLocationActivityCell.accessoryView = spinner;
+        [spinner startAnimating];
+        _geoLocationActivityCell.textLabel.text = NSLocalizedString(@"Finding your location...", @"Geo-tagging posts, status message when geolocation is found.");
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: Would it make sense to call a method to return the localized string rather than duplicate it here?

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 12]
```diff
@@ -606,48 +618,123 @@ - (UITableViewCell *)configureFeaturedImageCellForIndexPath:(NSIndexPath *)index
...
+}
 
+- (UITableViewCell *)configureGeolocationCellForIndexPath:(NSIndexPath *)indexPath
+{
+    WPTableViewCell *cell;
+    switch (indexPath.row) {
+        case (0): {
+            return self.geoLocationSwitchCell;
+        }
+        break;
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: For both case statements,
No need for the `(` `)`s on the case statement.
Not sure if this is in the style guide or not, but the `{` `}` are unnecessary unless there are variables to define in block scope.  
Also, since the case is returning, the `break;` is unneeded.

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m [hunk 13]
```diff
@@ -606,48 +618,123 @@ - (UITableViewCell *)configureFeaturedImageCellForIndexPath:(NSIndexPath *)index
...
-
+- (void)showLocationError:(NSError *)error {
+    NSString *title = NSLocalizedString(@"Location", @"Title for alert when a generic error happened when trying to find the location of the device");
+    NSString *message = NSLocalizedString(@"There was a problem when trying to access your location. Please try again later.",  @"Explaining to the user there was an error trying to obtain the current location of the user.");
+    NSString *cancelText = NSLocalizedString(@"OK", "");
+    NSString *otherButtonTitle = nil;
+    if (error.domain == kCLErrorDomain && error.code == kCLErrorDenied) {
+        otherButtonTitle = NSLocalizedString(@"Open Settings", @"Go to the settings app");
+        title = NSLocalizedString(@"Location", @"Title for alert when access to the media library is not granted by the user");
+        message = NSLocalizedString(@"WordPress needs permission to access your device location in order to geotag your post. Please change the privacy settings if you wish to allow this.",  @"Explaining to the user why the app needs access to the device location.");
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: I think we're not saying "geotag" anywhere else, so it felt a bit weird to see here.  Maybe we could wordsmith this message some?  Another take on it might be `WordPress needs permission to add your location to the post. Please update your privacy settings.` but that feels a bit terse. Maybe we can get some editorial input?

**Comment by aerych** [comment]
HIya @SergioEstevao !
Nice change and clean up. :)  I tested on both an iPad and iPhone and had no problems. I also tried with location services disabled, and with the permissions reset in the simulator.  I noticed in the iPhone simulator when I needed to grant permissions, the first attempt to get a location was an error and I was prompted to try again, but it worked on the second attempt.  This didn't always happen and might just be a bit of weirdness in the simulator.  

I had some (very) nitpicky code style comments and left one or two other suggestions.

File: WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m (hunk 9 above)
Comment (SergioEstevao) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: @aerych The idea of this code is that if you get to this point I don't want the block to be released to avoid some operations be done and others not.

Comment (aerych) [inline WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m]: Sure.  My concern is how its constructed.  
First, a weak connection to self is defined `__weak __typeof__(self) weakSelf = self;` which will be used inside the block. No problem.  Second, the weak reference to self, `weakSelf`, is assigned to a new variable to get a strong reference: `__typeof__(self) strongSelf = weakSelf;`.  Also, no problem in principle but notice how its currently declared. Since `__typeof__(self)` is inside the block, a reference to `self` is being captured inside the block and will be retained. This defeats the purpose of the `weakSelf` reference.  If the goal is to have the weakSelf / strongSelf pattern, then strong self should be defined as `__typeof__(weakSelf) strongSelf = weakSelf;` rather than `__typeof__(self) strongSelf = weakSelf;`.

**Comment by SergioEstevao** [comment]
@aerych ready for another round of review.

**Comment by aerych** [comment]
Code changes look good. I took things for one more round of testing and noticed something I missed before.  Earlier, I tried disabling location services just for WordPress, but not turned off for everything.  This time I tried disabling location services altogether and got an odd behavior.  First I saw one alert prompting to enable location services, then I saw another.  The second one goes by quickly as the app goes into the background and the settings app comes into the foreground, but its there waiting when the app resumes. 

simulator screen shot feb 15 2016 5 14 53 pm

simulator screen shot feb 15 2016 5 20 35 pm

**Comment by SergioEstevao** [comment]
@aerych I'm unable to reproduce it can you tell me the exact steps you did?

**Comment by aerych** [comment]
These are the steps I'm taking in the simulator:
1. In the Settings app: General > Reset > Reset Location & Privacy
2. In the Settings app: Privacy > Location Services > Toggle Location Services off. 
3. Back in WordPress, edit a post.
4. Open post settings and toggle on Location.

Here's a short video: https://cloudup.com/cyiuFjK5OLp
Cloudup's playback is being cranky so you might need to download the original to view it.

**Comment by SergioEstevao** [comment]
@aerych Thanks for the details I was able to reproduce it now. I pushed a commit to fix this so it's now ready for the final review! (I hope)

**Comment by aerych** [comment]
HI Sergio.  Getting close!  I tried to reproduce the issue and there is no longer a double alert prompt, however, this is what I'm seeing when location services are disabled, and I tap the button to open settings:
simulator screen shot feb 16 2016 9 31 37 am

Since location services are still disabled, the option to choose the setting for WordPress is also disabled, leaving the user to wonder what steps they need to take.  

Maybe it would make sense to check specifically for location services being disabled, and allow the native iOS prompt in that situation. This way the user would be taken directly to the correct place in the settings app to update location privacy settings.  Maybe something like: 
### LocationService
```
- (BOOL)locationServiceDenied
{
    CLAuthorizationStatus status = [CLLocationManager authorizationStatus];
    return status == kCLAuthorizationStatusDenied;
}
```

### PostSettingsViewController
```
- (void)updatePostLocationState:(BOOL)geoLocationOn 
{
    if (geoLocationOn) {
        if ([self.locationService locationServiceDenied]) {
            [self.locationService getCurrentLocationAndAddress:nil];
            self.geoLocationSwitchCell.on = NO;
            return;
        }
[...]
}
```

The down side is the user would have to make two attempts to set the location, but I'm not seeing a way around it if location services are disabled. 

One other small thing, in the prompt: `WordPress needs permission to access your device's location in order to add it to your post. Please change the privacy settings if you wish to allow this.` The second sentence doesn't sound natural.  Maybe it could just say something like `Please update your privacy settings.` instead?

Thoughts?

**Comment by SergioEstevao** [comment]
@aerych ready for another go. It was impossible to detect when the system message was going to show up so I decide to reword the alert if the location services are disabled.

File: WordPress/Classes/Utility/LocationService.m [hunk 14]
```diff
@@ -196,18 +177,54 @@ - (void)locationManager:(CLLocationManager *)manager didFailWithError:(NSError *
...
+#pragma mark - Show alert for location errors
+
+- (void)showAlertForLocationServicesDisabled
+{
+    [self showAlertForLocationError:[NSError errorWithDomain:kCLErrorDomain code:kCLErrorDenied userInfo:nil]];
+}
+
+- (void)showAlertForLocationError:(NSError *)error
+{
+    NSString *title = NSLocalizedString(@"Location", @"Title for alert when a generic error happened when trying to find the location of the device");
```
Comment (aerych) [inline WordPress/Classes/Utility/LocationService.m]: Since the title is always `Location`, maybe just define it once here and not redefine it in the if/else block below?

**Comment by aerych** [comment]
Hi @SergioEstevao.  I'm seeing a double prompt when Location is enabled, but the user opts out of the first prompt.  Here's a quick video. 
https://cloudup.com/c_gOiNWlqeu
Cloudup is still having problems. It might say upload failed when you view it but the download link should still work.

**Comment by SergioEstevao** [comment]
@aerych one more time please?

**Comment by aerych** [comment]
That got it :)  Thanks Sergio!  :shipit:
