### PR TITLE
Jetpack Extensions: Use different keys to avoid conflicts between WP and JP extensions

### LINKED ISSUE #19591: Jetpack Share Extension: Site list not accurate if WordPress and Jetpack are both installed
### Expected behavior
Jetpack extensions to be fully separated from the account signed into the WordPress app. The site list displayed should always be from the account signed into the Jetpack app. 

### Actual behavior
The site list displayed is from the app that was most recently launched.

### Steps to reproduce the behavior
Install & run Jetpack
Sign in using account A
Install & run WordPress
Sign in using account B
Go to photos
Select a photo
Tap on the share button
Select Jetpack
Observe that the site list displayed is the one from account B not account A.

### PR DESCRIPTION
**Pull request by hassaanelgarem**
Fixes #19591

## Description
This PR fixes an issue where jetpack extensions were conflicting with WP extensions. This is done by using different keys for the WP and JP extensions.

P.S: This change means we will have to migrate the extensions' data since they are no longer shared between WP and JP. This will be done in a coming PR and will follow the same pattern as the one in #19663, that's why this PR depends on #19663's branch.

## Testing Instructions

1. Install & run Jetpack
2. Sign in using account A
3. Install & run WordPress
4. Sign in using account B
5. Go to photos
6. Select a photo
7. Tap on the share button
8. Select Jetpack
9. Make sure that the site list displayed is the one from account A, not account B.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift [hunk 1]
```diff
@@ -0,0 +1,31 @@
+// WordPress Extension configuration
+
+import Foundation
+
+@objc extension AppConfiguration {
```
Comment (dvdchr) [inline WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift:8]: As we will be having a couple of "similar-but-different" configuration files, (e.g., `WidgetConfiguration`, `AppConfiguration`, `AppConstants`), I think it would help to add some documentation/warning here (and in the counterpart file) stating that the **keys must be in-sync with the counterpart file**. 

While this doesn't entirely prevent mistakes, I feel it still helps to deter human errors. More detail on this: https://github.com/wordpress-mobile/WordPress-iOS/pull/19479#discussion_r1002819063

**Review by dvdchr — COMMENTED** [review]
Hi @hassaanelgarem 👋🏼 . Thank you for working on this! I left one non-blocking suggestion, and the changes are looking good to me.

> This change means we will have to migrate the extensions' data since they are no longer shared between WP and JP. This will be done in a coming PR [...]

Please note that this PR and the changes you've planned in the next PR need to be all-or-nothing; If we merge this, we **must** also merge the addition to the migration process.

My recommendation is to either put everything in this PR or don't merge this PR until both the PRs are green. I can't help but think about the risks due to the very tight time constraints 😅 

What do you think?

File: WordPress/Jetpack/ExtensionConfiguration.swift [hunk 2]
```diff
@@ -0,0 +1,31 @@
+// Jetpack Extension configuration
+
+import Foundation
+
+@objc extension AppConfiguration {
```
Comment (dvdchr) [inline WordPress/Jetpack/ExtensionConfiguration.swift:8]: (see the comment above)

**Review by momo-ozawa — APPROVED** [review]
Works as described. Will we be able to target 21.3, given the code freeze is coming up very soon?

File: WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift (hunk 1 above)
Comment (staskus) [reply WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift:8]: Thanks for linking this comment thread 👍.

Yes, we went for this solution without too many discussions, simply following the pattern that was already established with `AppConfiguration` files. However, it does have drawbacks with discoverability and the necessity to build both targets to ensure there're no errors.

File: WordPress/Classes/Services/NotificationFilteringService.swift [hunk 3]
```diff
@@ -14,16 +14,16 @@ final class NotificationFilteringService {
     var wordPressNotificationsEnabled: Bool {
         get {
             guard let userDefaults = userDefaults,
-                  userDefaults.value(forKey: WPNotificationsEnabledKey) != nil else {
```
Comment (staskus) [inline WordPress/Classes/Services/NotificationFilteringService.swift]: There'll be conflicts with these after my latest merge.

WPNotificationsEnabledKey and subsequently AppConfiguration.Extension.NotificationsService.enabledKey are no longer needed and could be deleted.

**Review by staskus — APPROVED** [review]

**Review by dvdchr — APPROVED** [review]

File: WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift (hunk 1 above)
Comment (hassaanelgarem) [reply WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift:8]: Good point @dvdchr!
I've added documentation here and in the other configuration files c9a58f22befd1902e4c78b19e8947def4e53f160 👍

File: WordPress/Classes/Services/NotificationFilteringService.swift (hunk 3 above)
Comment (hassaanelgarem) [reply WordPress/Classes/Services/NotificationFilteringService.swift]: Thanks for the heads up @staskus 🙇

**Comment by hassaanelgarem** [comment]
> Please note that this PR and the changes you've planned in the next PR need to be all-or-nothing; If we merge this, we must also merge the addition to the migration process.

@dvdchr Agreed. I've added a "Do not merge" label, and I'll remove it once #19666 is ready.

@mokagio FYI. ~~Also, given the time, I don't think #19666 will be ready and approved before the code freeze. Do you think we can include these two PRs in a beta release?~~
Edit: #19666 is merged into this PR, and I've enabled auto-merge on this PR, so it will be merged once the CI passes 👍

File: WordPress/Jetpack/ExtensionConfiguration.swift [hunk 4]
```diff
@@ -0,0 +1,33 @@
+// Jetpack Extension configuration
+
+import Foundation
+
+/// - Warning:
+/// This configuartion extension has a **WordPress** counterpart in the WordPress bundle.
```
Comment (dvdchr) [inline WordPress/Jetpack/ExtensionConfiguration.swift]:
```suggestion
/// This configuration extension has a **WordPress** counterpart in the WordPress bundle.
```

File: WordPress/Jetpack/AppStyleGuide.swift [hunk 5]
```diff
@@ -2,6 +2,9 @@ import Foundation
 import WordPressShared
 import Gridicons
 
+/// - Warning:
+/// This configuartion struct has a **WordPress** counterpart in the WordPress bundle.
```
Comment (dvdchr) [inline WordPress/Jetpack/AppStyleGuide.swift]:
```suggestion
/// This configuration struct has a **WordPress** counterpart in the WordPress bundle.
```

File: WordPress/Jetpack/AppDependency.swift [hunk 6]
```diff
@@ -1,5 +1,8 @@
 import Foundation
 
+/// - Warning:
+/// This configuartion class has a **WordPress** counterpart in the WordPress bundle.
```
Comment (dvdchr) [inline WordPress/Jetpack/AppDependency.swift]:
```suggestion
/// This configuration class has a **WordPress** counterpart in the WordPress bundle.
```

File: WordPress/Jetpack/AppConstants.swift [hunk 7]
```diff
@@ -1,6 +1,9 @@
 import Foundation
 import WordPressKit
 
+/// - Warning:
+/// This configuartion class has a **WordPress** counterpart in the WordPress bundle.
```
Comment (dvdchr) [inline WordPress/Jetpack/AppConstants.swift]:
```suggestion
/// This configuration class has a **WordPress** counterpart in the WordPress bundle.
```

File: WordPress/Jetpack/AppConfiguration.swift [hunk 8]
```diff
@@ -2,6 +2,9 @@ import Foundation
 
 /**
  * Jetpack Configuration
+ * - Warning:
+ * This configuartion class has a **WordPress** counterpart in the WordPress bundle.
```
Comment (dvdchr) [inline WordPress/Jetpack/AppConfiguration.swift]:
```suggestion
 * This configuration class has a **WordPress** counterpart in the WordPress bundle.
```

File: WordPress/Classes/Utility/App Configuration/WidgetConfiguration.swift [hunk 9]
```diff
@@ -2,6 +2,9 @@
 
 import Foundation
 
+/// - Warning:
+/// This configuartion extension has a **Jetpack** counterpart in the Jetpack bundle.
```
Comment (dvdchr) [inline WordPress/Classes/Utility/App Configuration/WidgetConfiguration.swift]:
```suggestion
/// This configuration extension has a **Jetpack** counterpart in the Jetpack bundle.
```

**Review by dvdchr — APPROVED** [review]
Just noticed a typo 😅 But it's looking good overall. :shipit:
