### PR TITLE
Passes UserDefaults.standard instead of creating new instances of UserDefaults

### LINKED ISSUE #20654: Delay before interactivity after bringing app to foreground
### Expected behavior
App to be immediately interactive and respond to user input.

### Actual behavior
- Sometimes there's a delay before the app is interactive
- This doesn't happen when Airplane Mode is enabled

| Airplane Mode off | Airplane Mode on |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/3d6cb28b-9a95-45e6-b07c-919b19fdfb95" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/3488d4b7-a92e-4831-a5fb-5c0c9d2408a7" /> |

### Steps to reproduce the behavior
1. Send the app to the background
2. Bring the app to the foreground
3. Immediately try to scroll or switch views using the tab bar

### PR DESCRIPTION
**Pull request by aerych**
Fixes #20654

This PR attempts to resolve a severe hang that occurs when foregrounding the app in certain circumstances.  
User's with many blogs will be more affected than users with very few blogs.  What appears to happen is: 
1. The app is foregrounded.
2. The app delegate calls `GutenbergSettings().performGutenbergPhase2MigrationIfNeeded`
3. GutenbergRollout.atLeastOneSiteHasAztecEnabled is called which loops over every blog stored in the app.
4. The check for the editor current creates a new instance of GutenbergSettings for _each_ blog being checked, and each instance of GutenbergSettings creates a new instance of UserDefaults, which is automatically populated with the current values for the app and user.  (See [this comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/20654#issuecomment-1631603338) in the related issue for more details.)

This PR attempts to resolve the hang by passing the singleton instance of UserDefaults.standard to GutenbergSettings, avoiding all the extra work being done to populate each new instance of UserDefaults.

NOTE: It's not clear to me if there is a reason GutenbergSettings needs a fresh instance of UserDefaults. There doesn't seem to be but I'm unfamiliar with the related code. Reviewers please take an extra look at this to make sure I haven't overlooked anything! 

To test:
Confirm the issue by follwing these steps: 

- Start fresh by force closing the app. Open and then background the app. Then open it again and confirm that the app is immediately responsive.
- Switch to the reader tab.
- Tap on a post with many comments and view the detail.
- Tap on the option to view the comments.
- Background and reopen the app. Confirm the app is not immediately responsive.
- Back out of the comments to the post stream. (The stream shouldn't matter.)
- Background and reopen the app. Confirm the app is still unresponsive.
- Switch tabs to either sites or notifications. Background and reopen the app. Confirm the app is still unresponsive.

Then switch to this branch and repeat the steps above and confirm that the app is NOT unresponsive. 

## Regression Notes
1. Potential unintended areas of impact
Potential unintended changes to UserDefaults.standard that were avoided by using an separate instance. I'm not seeing where this would be an issue but paranoia ftw! 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
No tests that I'm aware of. 

3. What automated tests I added (or what prevented me from doing so)
We could add a test to check that the same instance of UserDefaults is being used for each created copy of GutenbergSettings, but I'm not sure this is reasonable. It would seem to make more sense to to alter the default initializer so database: has a default value of UserDefaults.standard rather than add a test.  Or there may be other, better approaches.  Thoughts? 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

File: WordPress/Classes/Models/Blog+Editor.swift [hunk 1]
```diff
@@ -39,7 +39,7 @@ extension Blog {
     /// The editor to use when creating a new post
     ///
     var editor: MobileEditor {
-        return mobileEditor ?? GutenbergSettings().getDefaultEditor(for: self)
+        return mobileEditor ?? GutenbergSettings(database: UserDefaults.standard).getDefaultEditor(for: self)
```
Comment (twstokes) [inline WordPress/Classes/Models/Blog+Editor.swift]: 👋 @aerych - I wonder if we should update the [convenience init](https://github.com/wordpress-mobile/WordPress-iOS/blob/ef1794962ba5bdcc1becfa251941ef115043cd43/WordPress/Classes/Utility/Editor/GutenbergSettings.swift#L46) to use the singleton so that all callers can benefit.

I'm drawing a blank on why a fresh `UserDefaults()` would be needed?

**Review by twstokes — APPROVED** [review]
I can consistently reproduce the hang before these changes, and cannot reproduce after. Great work @aerych! 🙇 

I left one comment, but it shouldn't hold up this PR. In a future PR we should reassess why we're trying to migrate to Gutenberg every time the app is active ([which was questioned at origin](https://github.com/wordpress-mobile/WordPress-iOS/pull/13189/files#r363766624)) and if we still need to migrate users. I'll be glad to drive those efforts.

Thank you!

**Comment by twstokes** [comment]
I do want to add that this area [seems well tested](https://github.com/wordpress-mobile/WordPress-iOS/blob/issue/20654-fix-for-severe-hang/WordPress/WordPressTest/GutenbergSettingsTests.swift), and if avoiding using the `UserDefaults()` singleton was intentional, perhaps it would've been covered. 🤔 I still can't think of what or how that would benefit anything.

File: WordPress/Classes/Models/Blog+Editor.swift (hunk 1 above)
Comment (aerych) [reply WordPress/Classes/Models/Blog+Editor.swift]: I'm glad to hear the way UserDefaults() is called is a mystery to more than just me.  I made the change here for the lighter touch but I think it's probably safe (and more helpful) to make move the assignment into GutenbergSettings.  To be slightly cleaner, I think we can get rid of the convenience initializer and make UserDefaults.standard a default parameter value in the  `init(database:)`.

**Comment by aerych** [comment]
Thanks @twstokes !  I made a change to the initializer.  Game for another quick peek for paranoia sake?

**Comment by twstokes** [comment]
Will do @aerych! Would you mind adding a release note for 22.9? I failed to catch that in my first round.

**Review by twstokes — APPROVED** [review]
LGTM @aerych!

As an extra test I loaded a self-hosted site with Jetpack enabled, and disabled the Block Editor from the app. I moved the app to the background, and then foreground, and was "migrated" to the Block Editor - new posts used the Block Editor. I then disabled the Block Editor again from the app and repeated the process. The second time it stayed disabled, which tells me it was successfully committed to UserDefaults.

File: WordPress/Classes/Models/Blog+Editor.swift (hunk 1 above)
Comment (twstokes) [reply WordPress/Classes/Models/Blog+Editor.swift]: Good call on the default param. 👍

**Comment by aerych** [comment]
> As an extra test [..]

Excellent!  Thanks for going the extra mile to be sure. 
Release notes updated!  I'll merge as soon as CI is happy. :)
