### PR TITLE
Jetpack Social: Exclude unshared private connections from other users

### LINKED ISSUE #20744: Jetpack Social: unshared connections are visible to other admins
Refs pcdRpT-2Ey-p2#comment-4800

### Expected behavior
Unshared connections should not be visible to other users.

### Actual behavior
Unshared connections are visible to other users.

### Steps to reproduce the behavior

- From account A, create a Jetpack Social connection.
- Ensure that sharing is toggled OFF for that connection.
- Log in to a different account that also has administrator access to the same site.
- Observe that the connection from account A is visible in the Site menu > Social.

##### Tested on iPhone 14 Pro, iOS 16.1, Jetpack iOS 22.4 (beta)

### LINKED ISSUE #21201: Jetpack Social connections screen shows visual bug after disconnecting
### Expected behavior
The social connection screen should display the empty state after removing all the connected accounts for the service.

### Actual behavior
The screen looked like it tried to display both states. Refer to the screenshot below:

### Steps to reproduce the behavior

1. Launch the Jetpack app. 
2. Switch to a blog with existing Jetpack Social connections.
3. Go to the Social screen from My Site > Menu tab > Social.
4. Tap one of the connected services.
5. Tap the account, and disconnect.
6. Tap back.
7. 🔎 Observe that the screen is in a bugged state.

### PR DESCRIPTION
**Pull request by dvdchr**
Fixes #20744 

Since the endpoint returns all connections for the site, this PR filters any connections from other users that are not shared by checking the `shared` value and comparing the `userID` field to the current user's ID.

## To test

- Add your secondary WP.com account as an administrator in your test site.
- From your secondary account, create a new Social connection. This can be done either from the app or the web.
- Make sure that the sharing option is unchecked for this connection.
- Launch the Jetpack app.
- Log in with your primary WP.com account.
- Switch to the test site that has been prepared.
- Go to My Site > Social.
- 🔎 Verify that the private connection from your secondary account is not visible.

## Regression Notes
1. Potential unintended areas of impact
Some connections might not be shown correctly, or the user might be in a state where they don't have a proper account ID yet.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested the changes, and added new tests.

3. What automated tests I added (or what prevented me from doing so)
Unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
N/A. This PR doesn't introduce any visual changes.

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

### CODE REVIEW

**Comment by mokagio** [comment]
I'm going to bump this to the next release because we'll be code freezing [23.1](https://github.com/wordpress-mobile/WordPress-iOS/milestone/255) today and this hasn't been approved yet.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

File: WordPress/Classes/Services/SharingSyncService.swift [hunk 1]
```diff
@@ -28,18 +28,27 @@ import WordPressKit
...
+            let currentUserID: NSNumber = self.coreDataStack.performQuery { context in
+                guard let blog = try? context.existingObject(with: blogObjectID) as? Blog,
+                      let accountID = blog.account?.userID else {
+                    return NSNumber(value: 0)
+                }
+                return accountID
+            }
+
+            // Ensure that we're only processing shared or owned connections
+            let authorizedConnections = remoteConnections.filter { $0.shared || $0.userID.isEqual(to: currentUserID) }
```
Comment (wargcm) [inline WordPress/Classes/Services/SharingSyncService.swift:47]: No issue with the code, just a comment. It's strange to me that we're having the client filter out this info instead of doing it on the backend.

**Review by wargcm — APPROVED** [review]
LGTM! :shipit:

File: WordPress/Classes/Services/SharingSyncService.swift (hunk 1 above)
Comment (dvdchr) [reply WordPress/Classes/Services/SharingSyncService.swift:47]: Yeah, that is true. There could be a special purpose behind why it's done this way, or if it's indeed a mistake, I'll look into opening a ticket for the backend side.
