### PR TITLE
Issue/7878 fix editor bars with long titles 8.5.2

### LINKED ISSUE #7878: Long site/url interfering with action buttons in Editor
### Expected behavior
If I had a long site title or URL (in the case of an empty site title), I would expect to still see the publish button in portrait mode in the Editor.

### Actual behavior
The Publish button is either not available or overrun with text.

### Steps to reproduce the behavior
1. Set a long site title (I used "This is a long site title I mean who would write something...")
2. Open the editor

Neither the "X" to exit the editor or the Publish action are available:

screen shot 2017-09-29 at 10 30 54

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #7878 

This PR fixes the issues with long names of blogs by setting the `ContentHuggingPriority` on components of the navigation bar on iOS11. This keeps the structure and layout of the navigation bar the same has before and avoid the use of the title view.

screen shot 2017-10-12 at 12 38 47
screen shot 2017-10-12 at 12 38 43

To test:  
 - Open the editor on a blog with a long name
 - Check that the navigation bar shows correctly and the blog name it's cropped correctly if needed.
 - Test on different devices (iPhone SE, iPhone 8+, iPad) and multitasking modes.
 - Test on iOS10 and iOS11

Thanks to @frosty for the nudge to the right direction.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 1]
```diff
@@ -202,20 +201,40 @@ class AztecPostViewController: UIViewController, PostEditor {
...
         return button
     }()
 
 
+    fileprivate lazy var moreButton: UIButton = {
+        let image = Gridicon.iconOfType(.ellipsis)
+        let moreItem = UIButton(type: .system)
+        moreItem.setImage(image, for: .normal)
+        var frame = CGRect(origin: .zero, size: image.size)
+        moreItem.frame = frame
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Can we just assign the `CGRect` directly here? We don't need the extra variable.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 2]
```diff
@@ -202,20 +201,40 @@ class AztecPostViewController: UIViewController, PostEditor {
...
+        moreItem.setContentHuggingPriority(UILayoutPriorityRequired, for: .horizontal)
+        return moreItem
+    }()
     /// NavigationBar's More Button
     ///
     fileprivate lazy var moreBarButtonItem: UIBarButtonItem = {
-        let image = Gridicon.iconOfType(.ellipsis)
-        let moreItem = UIBarButtonItem(image: image, style: .plain, target: self, action: #selector(moreWasPressed))
-        moreItem.accessibilityLabel = NSLocalizedString("More", comment: "Action button to display more available options")
+        let moreItem = UIBarButtonItem(customView: self.moreButton)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Should we still set the `accessibilityLabel` on `moreItem` here? We could just pass it through from the button:

`moreItem.accessibilityLabel = self.moreButton.accessibilityLabel`

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 3]
```diff
@@ -202,20 +201,40 @@ class AztecPostViewController: UIViewController, PostEditor {
...
     /// Publish Button
-    fileprivate(set) lazy var publishButton: UIBarButtonItem = {
-        let button = UIBarButtonItem(title: self.postEditorStateContext.publishButtonText, style: WPStyleGuide.barButtonStyleForDone(), target: self, action: #selector(publishButtonTapped(sender:)))
+    fileprivate(set) lazy var publishButton: UIButton = {
+        let button = UIButton(type: .system)
+        button.addTarget(self, action: #selector(publishButtonTapped(sender:)), for: .touchUpInside)
+        button.setTitle(self.postEditorStateContext.publishButtonText, for: .normal)
+        button.sizeToFit()
         button.isEnabled = self.postEditorStateContext.isPublishButtonEnabled
+        button.setContentHuggingPriority(UILayoutPriorityRequired, for: .horizontal)
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: I think to be safe we should also set `compressionResistance` to required for the publish and X buttons, and low for the blog selector button.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 4]
```diff
@@ -775,19 +802,21 @@ class AztecPostViewController: UIViewController, PostEditor {
...
-        blogPickerButton.sizeToFit()
-
-        // Cap the size, according to the current traits
-        var blogPickerSize = hasHorizontallyCompactView() ? Constants.blogPickerCompactSize : Constants.blogPickerRegularSize
-        blogPickerSize.width = min(blogPickerSize.width, blogPickerButton.frame.width)
-
-        blogPickerButton.frame.size = blogPickerSize
+        if #available(iOS 11, *) {
+            return
+        } else {
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: This doesn't really need to be in an `else`, as the return will exit from the `if` anyway.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 5]
```diff
@@ -170,7 +170,6 @@ class AztecPostViewController: UIViewController, PostEditor {
     ///
     fileprivate lazy var separatorButtonItem: UIBarButtonItem = {
         let separator = UIBarButtonItem(barButtonSystemItem: .fixedSpace, target: nil, action: nil)
-        separator.width = Constants.separatorButtonWidth
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: How come we don't need to set a separator width any more?

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift (hunk 3 above)
Comment (frosty) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Or at the very least, I'm surprised we don't have to. It may be good to be explicit about it.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift (hunk 4 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Could be replaced by a guard, which ensures the `return` is not removed.

**Comment by frosty** [comment]
Tested with the hybrid editor on same devices on iOS 11 too. Everything's looking good. One small issue is that the weight of the publish button changes a lot when touching down on it:

publish-button

I think we probably just need to set a style for the different states. Finally, if I'm being super nitpicky, the gap between the selector and the Publish button could be slightly wider, and the gap between the Publish button and the `...` could be slightly narrower. Again, not a big issue though, and shouldn't block this.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift (hunk 5 above)
Comment (SergioEstevao) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: There is a default value, before we where hacking with a negative value to get some magic margins. That is not even officially allowed and I don't think we need to do it anymore

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift (hunk 2 above)
Comment (diegoreymendez) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Not sure about this one because there's a chance this may confuse users, if it's mentioned twice by VoiceOver.

As I understand it the item you interact with it really the button, so that's where I think the accessibility label should go.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 6]
```diff
@@ -245,6 +268,10 @@ class AztecPostViewController: UIViewController, PostEditor {
         let button = WPUploadStatusButton(frame: CGRect(origin: .zero, size: Constants.uploadingButtonSize))
         button.setTitle(NSLocalizedString("Media Uploading", comment: "Message to indicate progress of uploading media to server"), for: .normal)
         button.addTarget(self, action: #selector(displayCancelMediaUploads), for: .touchUpInside)
+        if #available(iOS 11, *) {
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: Do we need this guard?  It feels like even if the code inside is not necessary before iOS 11, it won't break anything.

The thing I have against guards is once you add them it's really hard to remove them, if they're not extensively documented.

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift [hunk 7]
```diff
@@ -775,19 +802,21 @@ class AztecPostViewController: UIViewController, PostEditor {
...
     func resizeBlogPickerButton() {
         // Ensure the BlogPicker gets it's maximum possible size
-        blogPickerButton.sizeToFit()
-
-        // Cap the size, according to the current traits
-        var blogPickerSize = hasHorizontallyCompactView() ? Constants.blogPickerCompactSize : Constants.blogPickerRegularSize
-        blogPickerSize.width = min(blogPickerSize.width, blogPickerButton.frame.width)
-
-        blogPickerButton.frame.size = blogPickerSize
+        if #available(iOS 11, *) {
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: This is similar to the case of other guards... it's easy to understand that for iOS 11 this method becomes a no-op, but it's hard to understand why.

My suggestion would be to try and remove the guard entirely (if that's ever possible), or to try and document it in a way that anyone can understand why it's here.

File: WordPress/Classes/ViewRelated/Post/WPPostViewController.m [hunk 8]
```diff
@@ -1279,6 +1286,10 @@ - (UIBarButtonItem *)uploadStatusButton
         [button setTitle:NSLocalizedString(@"Media Uploading", @"Message to indicate progress of uploading media to server") forState: UIControlStateNormal];
         [button addTarget:self action:@selector(showCancelMediaUploadPrompt) forControlEvents:UIControlEventTouchUpInside];
         _uploadStatusButton = [[UIBarButtonItem alloc] initWithCustomView:button];
+        if (@available(iOS 11, *)) {
```
Comment (diegoreymendez) [inline WordPress/Classes/ViewRelated/Post/WPPostViewController.m]: Same as above... any chance we can remove this one?

**Comment by SergioEstevao** [comment]
I addressed some of the comments please have a look.

**Comment by diegoreymendez** [comment]
iOS 10 looks like this on an iPhone 7.

It's not great, but:

- It's exactly the same as what we had before, and
- It's not a blocking issue.

For those reasons, I don't think trying to fix that in this PR would be a good idea.

screen shot 2017-10-12 at 11 32 29 am

**Comment by bummytime** [comment]
So, @frosty's[ layout issues](https://github.com/wordpress-mobile/WordPress-iOS/pull/7954#pullrequestreview-68914149) aside (and I agree) this PR fixes the core issue in #7878 in that the action buttons are now usable. I looked at both the Aztec and Hybrid editors.

Tested on iOS 10.3 Devices:
✅ iPad Pro 12"
✅ iPhone 6+
✅ iPhone 5
✅ iPhone SE

Tested on iOS 11 Devices:
✅ iPad Pro 10.5"
✅ iPhone SE
✅ iPhone 7+

@SergioEstevao any thoughts on the accessibility comments [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/7954/files#r144281294)?

File: WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift (hunk 2 above)
Comment (SergioEstevao) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: it's set on the button so it should be fine no?

Comment (frosty) [reply WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift]: I just tested this and it looks like the accessibility label does get passed through 👍
