### PR TITLE
Notification Details: Fix potential crash on viewWillDisappear

### LINKED ISSUE #6948: Notifications Detail: Crash accessing keyboardManager in viewWillDisappear
We have a crash in `viewWillDisappear` of `NotificationsDetailViewController`. Looks like it's happening when we're launching from a notification's action. Seems as though there may be a case where the 'default' detail view gets swapped out before its view has loaded.

```
#0. Crashed: com.apple.main-thread
0  WordPress                      0x10028cd50 @objc NotificationDetailsViewController.viewWillDisappear(Bool) -> () (NotificationDetailsViewController.swift:152)
1  UIKit                          0x1919f7894 -[UIViewController _setViewAppearState:isAnimating:] + 944
2  UIKit                          0x191a6b50c -[UIViewController __viewWillDisappear:] + 100
3  UIKit                          0x191ab513c -[UINavigationController viewWillDisappear:] + 124
4  UIKit                          0x1919f7894 -[UIViewController _setViewAppearState:isAnimating:] + 944
5  UIKit                          0x191a6b50c -[UIViewController __viewWillDisappear:] + 100
6  UIKit                          0x192056aac -[UISplitViewControllerClassicImpl setViewControllers:] + 1216
7  WordPress                      0x1004637d0 specialized WPSplitViewController.viewControllers.setter (WPSplitViewController.swift)
8  WordPress                      0x10045f854 @objc WPSplitViewController.viewControllers.setter (WPSplitViewController.swift)
9  UIKit                          0x192057bb0 -[UISplitViewControllerClassicImpl showDetailViewController:sender:] + 940
10 UIKit                          0x191ff0434 -[UISplitViewController showDetailViewController:sender:] + 68
11 WordPress                      0x100464098 specialized WPSplitViewController.showDetailViewController(UIViewController, sender : Any?) -> () (WPSplitViewController.swift)
12 WordPress                      0x1004603f4 @objc WPSplitViewController.showDetailViewController(UIViewController, sender : Any?) -> () (WPSplitViewController.swift)
13 UIKit                          0x191d52054 -[UIViewController _showViewController:withAction:sender:] + 128
14 UIKit                          0x19208e808 __66-[UIStoryboardShowSegueTemplate newDefaultPerformHandlerForSegue:]_block_invoke + 148
15 UIKit                          0x19219c854 -[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] + 452
16 UIKit                          0x19219c65c -[UIStoryboardSegueTemplate _perform:] + 92
17 UIKit                          0x191d429b8 -[UIViewController performSegueWithIdentifier:sender:] + 108
18 WordPress                      0x100435788 specialized NotificationsViewController.showDetailsForNotification(Notification) -> () (NotificationsViewController.swift)
19 WordPress                      0x10042be44 @objc NotificationsViewController.encodeRestorableState(with : NSCoder) -> () + 4299292228
20 WordPress                      0x100429fb0 @objc NotificationsViewController.showDetailsForNotificationWithID(String) -> () (NotificationsViewController.swift)
21 WordPress                      0x100117b2c -[WPTabBarController showNotificationsTabForNoteWithID:] (WPTabBarController.m:646)
22 WordPress                      0x10044f50c specialized InteractiveNotificationsManager.handleAction(with : String, userInfo : NSDictionary, responseText : String?) -> Bool (InteractiveNotificationsManager.swift)
23 WordPress                      0x100450018 specialized specialized InteractiveNotificationsManager.userNotificationCenter(UNUserNotificationCenter, didReceive : UNNotificationResponse, withCompletionHandler : () -> ()) -> () (InteractiveNotificationsManager.swift)
24 WordPress                      0x10044d160 @objc InteractiveNotificationsManager.userNotificationCenter(UNUserNotificationCenter, didReceive : UNNotificationResponse, withCompletionHandler : () -> ()) -> () (InteractiveNotificationsManager.swift)
25 UIKit                          0x191c772c8 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] + 4216
26 UIKit                          0x191c7be60 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 2412
27 UIKit                          0x191c7b280 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 452
28 UIKit                          0x191c66820 __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 152
29 UIKit                          0x191c664a4 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 888
30 UIKit                          0x191f9253c -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 464
31 FrontBoardServices             0x18d6d9dd4 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376 + 208
32 FrontBoardServices             0x18d70792c __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
33 FrontBoardServices             0x18d707798 -[FBSSerialQueue _performNext] + 176
34 FrontBoardServices             0x18d707b40 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
35 CoreFoundation                 0x18badeb5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
36 CoreFoundation                 0x18bade4a4 __CFRunLoopDoSources0 + 524
37 CoreFoundation                 0x18badc0a4 __CFRunLoopRun + 804
38 CoreFoundation                 0x18ba0a2b8 CFRunLoopRunSpecific + 444
39 GraphicsServices               0x18d4be198 GSEventRunModal + 180
40 UIKit                          0x191a4a7fc -[UIApplication _run] + 684
41 UIKit                          0x191a45534 UIApplicationMain + 208
42 WordPress                      0x10001666c main (main.m:5)
43 libdispatch.dylib              0x18a9ed5b8 (Missing)
```

### PR DESCRIPTION
**Pull request by frosty**
Fixes #6948. 

One of our current top crashes for 7.2 is happening on `keyboardManager.stopListeningToKeyboardNotifications()` in `viewWillDisappear` of `NotificationDetailsViewController`. `keyboardManager` was an implicitly-unwrapped optional, so there is a possibility it could be nil (which I'm presuming is the cause of the crash).

I've switched `keyboardManager` to a real optional, and we'll fail silently if it doesn't exist at that point. There _might_ be a deeper issue going on here, but at least this should stop us crashing.

To test:

* Ensure the keyboard handling still works as expected.
* You could try nilling out the `keyboardManager` and ensure we don't crash.

Needs review: @jleandroperez

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift [hunk 1]
```diff
@@ -62,7 +62,7 @@ class NotificationDetailsViewController: UIViewController {
 
     /// Keyboard Manager: Aids in the Interactive Dismiss Gesture
     ///
-    fileprivate var keyboardManager: KeyboardDismissHelper!
+    fileprivate var keyboardManager: KeyboardDismissHelper? = nil
```
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift]: By default optionals are =`nil`. Can we remove that?

Comment (frosty) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift]: Hah, not sure what I was thinking there 😅 Fixed!
