### PR TITLE
Uploading media via the Share extension silently fails for Contributors

### LINKED ISSUE #8621: App Extensions: Contributor role appears to successfully upload media
Title has it. When a user (who's role is set to `Contributor` on a site) shares media via either app extension, the background upload silently fails and the post sans media is uploaded anyway.

We should check for the contributor role prior before allowing the user to tap "Publish" or "Save" in situations like this.

Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/8619#pullrequestreview-96492215

### PR DESCRIPTION
**Pull request by mindgraffiti**
#Fixes #8621. Is dependent upon [WordPressKit-iOS PR #13](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/13)

cc: @ctarda in case you're interested :)

# Description
When a user (whose role is set to `Contributor` on a site) shares media via either share extension (main share activity extension or `Save as Draft`), the background upload silently fails and the post sans media is uploaded anyway. Instead, when a `Contributor` attempts to share some media by using the extension, there should be an alert that appears to tell the user they can't take that action.

## Testing Setup
1. Ensure you have the WordPress Share activity and the `Save as Draft` options turned on. If you're not sure if you have it, check out **How to turn on `Save as Draft`** at the bottom.
2. On your test website that you'll be sharing to, ensure that your user is set to the `Contributor` role

### Testing publishing a post 
1. Go to the Photos app and select some photo(s)
2. Press the Share icon button
3. Choose WordPress (the full-color app icon with the word "WordPress" below it)
4. Tap **Next**
5. In the **Publish post on:** section, choose your test site 
6. Tap **Publish**

**Expected Result**
An alert appears with the title **Sharing Error**. Message: This role is unable to upload media. Please contact your Site Administrator. Button title: Nevermind (dismisses alert and the modal view)
img_1883

### Testing `Save as Draft` 
1. Go to the Photos app and select some photo(s)
2. Press the Share icon button
3. Choose `Save as Draft` (the black and white app icon with the words "Save as Draft" below it)
4. Tap **Save**

The same alert listed in the first test should appear.

#### How to turn on "Save as Draft"
1. Trigger the share extension by attempting to share a piece of content. (For example, Safari > Share button).
2. Choose the "More" button
3. Find the "Save as Draft" activity, turn it on, and hit "Done".
4. The WordPress "Save as Draft" option should appear in the bottom row.

### CODE REVIEW

**Comment by michelleweber** [comment]
Let's get a little more specific!

Sharing Error

Your account does not have permission to upload media to this site. The Site Administrator can change these permissions. 

Button: Dismiss OR Return to post

File: WordPress/WordPressShareExtension/AppExtensionsService.swift [hunk 1]
```diff
@@ -102,6 +102,17 @@ extension AppExtensionsService {
         })
     }
 
+    func isAuthorizedToUploadMedia(in sites: [RemoteBlog], for selectedSiteID: Int) -> Bool {
+        let siteID = NSNumber(value: selectedSiteID)
+        var isAuthorizedToUploadFiles = false
+        for site in sites {
```
Comment (ctarda) [inline WordPress/WordPressShareExtension/AppExtensionsService.swift]: I am not sure if this would make sense, but I think this loop could be avoided by doing something similar to this:

``
isAuthorizedToUploadFIles = sites.filter({$0.blogId == siteID}).isUserCapableOf(.uploadFiles)
``

That way, we could not only avoid the loop, but declare isAuthorizedToUploadFiles as a `let` instead of a `var`

File: WordPress/WordPressShareExtension/ShareModularViewController.swift [hunk 2]
```diff
@@ -808,8 +814,33 @@ fileprivate extension ShareModularViewController {
 
         // Then proceed uploading the actual post
         let networkService = AppExtensionsService()
+        let isAuthorizedToUploadFiles = networkService.isAuthorizedToUploadMedia(in: siteList, for: siteID)
         let localImageURLs = [URL](shareData.sharedImageDict.keys)
-        if !localImageURLs.isEmpty {
+
+        if localImageURLs.isEmpty {
```
Comment (ctarda) [inline WordPress/WordPressShareExtension/ShareModularViewController.swift]: Would it make sense to encapsulate each branch of the `if else` in a separate method? It might make this method a bit more readable, what do you think?

File: WordPress/WordPressShareExtension/AppExtensionsService.swift [hunk 3]
```diff
@@ -102,6 +102,17 @@ extension AppExtensionsService {
         })
     }
 
+    func isAuthorizedToUploadMedia(in sites: [RemoteBlog], for selectedSiteID: Int) -> Bool {
```
Comment (bummytime) [inline WordPress/WordPressShareExtension/AppExtensionsService.swift]: Could we add some doc comments here?

File: WordPress/WordPressShareExtension/ShareModularViewController.swift (hunk 2 above)
Comment (bummytime) [reply WordPress/WordPressShareExtension/ShareModularViewController.swift]: +1 to @ctarda's comment ☝️ . Then the `isAuthorizedToUploadMedia` check could be at the top of the new "uploadPostWithMedia" func...perhaps as `guard` statement e.g.:

```
let isAuthorizedToUploadFiles = networkService.isAuthorizedToUploadMedia(in: siteList, for: siteID)
 guard isAuthorizedToUploadFiles else {
            // Error: this role is unable to upload media.
            let error = self.createErrorWithDescription("This role is unable to upload media.")
            self.tracks.trackExtensionError(error)
            let title = NSLocalizedString("Sharing Error", comment: "Share extension error dialog title.")
            let message = NSLocalizedString("This role is unable to upload media. Please contact your Site Administrator.", comment: "Share extension error dialog text.")
            self.showAlert(title: title, message: message, retry: false)
            return
        }
```

File: WordPress/WordPressShareExtension/ShareModularViewController.swift [hunk 4]
```diff
@@ -826,35 +857,21 @@ fileprivate extension ShareModularViewController {
...
-            })
         }
     }
 
-    func showAlert() {
-        let title = NSLocalizedString("Sharing Error", comment: "Share extension error dialog title.")
-        let message = NSLocalizedString("Whoops, something went wrong while sharing. You can try again, maybe it was a glitch.", comment: "Share extension error dialog text.")
+    func showAlert(title: String = NSLocalizedString("Sharing Error", comment: "Share extension error dialog title."),
+                   message: String = NSLocalizedString("Whoops, something went wrong while sharing. You can try again, maybe it was a glitch.", comment: "Share extension error dialog text."),
+                   retry: Bool = true) {
```
Comment (bummytime) [inline WordPress/WordPressShareExtension/ShareModularViewController.swift]: Instead of passing a retry `Bool`, maybe we could simply pass in a completion handler that will get executed after the alert is dismissed. This will avoid baking-in any specific logic within this function.
