### PR TITLE
Aztec: Context now tracks Content Changes

### LINKED ISSUE #6766: Prompt to discard unsaved changes appears even if no changes were made
First reported by @designsimply [here](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/272).

Steps to reproduce:

1. Open any published post using WPiOS 6.8+ (Aztec should be enabled by default on 6.8+ alpha).
1. Tap the "Edit" link.
1. Do not make any changes.
1. Tap the arrow at the top left to stop editing.

<strong>Result:</strong> I get asked whether I want to discard unsaved changes even though I haven't made any changes.

img_0377
<sup>Tested with WPiOS 6.8.1, Safari iOS 10.2.1, iPhone 6S.</sup>

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #6766

### To test:
1. Enable Aztec!
2. Open any published post using
3. Tap the "Edit" link.
4. Verify that the top right button (**"Update"**) is disabled
5. Type any character int he post's title
6. Verify that the **Update** button gets enabled
7. Undo the edit performed in (4)
8. Verify that the **Update** button gets disabled
9. Edit the Post's Contents
10. Verify that the **Update** button gets enabled
11. Undo the edition, and verify that the **Update** button gets disabled again

Needs review: @astralbodies 
May i bug you with yet anoooother review?

Thanks!!!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift [hunk 1]
```diff
@@ -807,38 +806,39 @@ private extension AztecPostViewController {
 //
 extension AztecPostViewController: PostEditorStateContextDelegate {
     override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
-        if keyPath == BasePost.statusKeyPath {
+        guard let keyPath = keyPath else {
+            return
+        }
+
+        switch keyPath {
```
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift]: Totally forgot you could `switch` on strings in Swift ❤️

File: WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift [hunk 2]
```diff
@@ -807,38 +806,39 @@ private extension AztecPostViewController {
...
+        case #keyPath(AbstractPost.dateCreated):
             let dateCreated = post.dateCreated ?? Date()
             postEditorStateContext.updated(publishDate: dateCreated)
-            return
-        } else if keyPath == #keyPath(AbstractPost.content) {
-            postEditorStateContext.updated(hasContent: editorHasContent)
-            return
+        case #keyPath(AbstractPost.content):
+            editorContentWasUpdated()
+        default:
```
Comment (astralbodies) [inline WordPress/Classes/ViewRelated/Post/AztecPostViewController.swift]: Oops. Didn't realize I forgot to call super!

**Comment by jleandroperez** [comment]
Thank **you** for the review sir!
