### PR TITLE
Plugin Directory — small fixes.

### LINKED ISSUE #8789: Plugin errors should be logged
Right now, there are no errors logged when there's a failure in the plugin remotes, which would make debugging and support difficult.

### PR DESCRIPTION
**Pull request by jklausa**
This is a collection of small fixes and touchups for PD, I felt all of them were small enough to warrant rolling them up in a collective PR, instead of 3 tiny ones.

The biggest change should be fairly invisible, except in bad scenarios — sometimes on slower devices (or simulator when your Mac is under a lot of load) the initial screen of Plugin Directory would freeze for a second or two. This was caused because every `PluginDirectoryEntry` that would get downloaded would trigger a full reload — and on a reasonable internet connection, it would mean we'd call `tableView.reloadData` like 20+ times right after each other. We're now throttling those calls, to avoid the freeze.

There should also no longer be a weird gray gap at the bottom of the Plugin Directory. 

Also — fixes #8789, adding error logging to plugin remotes.

### CODE REVIEW

File: WordPress/Classes/Utility/Throttle.swift [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+/// This class provides an easy way to ensure that an operation won't be repeated more often than `seconds` amount of time.
+/// Common use cases include online search — avoiding hitting the backend with a request for every character
+/// the user types.
+
+/// - Note:
+/// Any new block passed to `throttle(:_)` cancels the previous one. If you need to throttle multiple things
+/// (i.e. online search and unrelated background refresh), you'll need to have a separate `Throttle` for each of them.
+public class Throttle {
+    private let queue: DispatchQueue = DispatchQueue.global(qos: .default)
+
```
Comment (elibud) [inline WordPress/Classes/Utility/Throttle.swift]: Can we get rid of this empty line here?
