### PR TITLE
Use PostRepository to fetch pages in the Menu screen

### LINKED ISSUE #21947: Menus screen enters an infinite loop of loading site's pages
### Expected behavior & Actual behavior

When a site does not have any menu, the Menus screen fetches all pages in the site and creates menu items for each top level page. The API requests to load all pages should stop once all pages are loaded. But it doesn't stop. The API request continues to fire.

The infinity loading causes the "default menu" section the Menu screen staying at "loading menus" state.

### Steps to reproduce the behavior

To reproduce this bug, prepare a site that doesn't have any menu, like a brand new WP.com site. Add a couple of pages to the site.

1. Adds a log at [this line in `PostService`](https://github.com/wordpress-mobile/WordPress-iOS/blob/c2493d92aef172fd89573eafac778b5d771e397a/WordPress/Classes/Services/PostService.m#L122)
2. Launch the app from Xcode and go to the prepared site from the app.
3. Go to the Menu screen (My Site -> More -> Menu)
4. Check out Xcode's console output. The log added at step 1 will keep printing in the console.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
c2493d92aef172fd89573eafac778b5d771e397a

### PR DESCRIPTION
**Pull request by crazytonyli**
Fixes #21947

There are a few issues in the "sync posts" function in `PostServices`, which I have described in https://github.com/wordpress-mobile/WordPress-iOS/pull/21814. In this PR, I have replace one usage of the "sync posts" function with the new implementation in `PostRepository`.

To test: verify #21947 is fixed.

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Verify #21947

3. What automated tests I added (or what prevented me from doing so)
Unit tests for successful API responses and cancellation.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist: N/A

### CODE REVIEW

File: WordPress/Classes/Services/MenusService.h [hunk 1]
```diff
@@ -72,16 +72,12 @@ typedef void(^MenusServiceFailureBlock)(NSError *error);
            failure:(nullable MenusServiceFailureBlock)failure;
 
 /**
- *  @brief      Generate a list MenuItems from the blog's top-level pages.
+ *  @brief      Create a list MenuItems from the given page.
  *
- *  @param      blog      The blog to use for pages.  Cannot be nil.
- *  @param      success   The success handler.  Can be nil.
- *  @param      failure   The failure handler.  Can be nil.
+ *  @return     A MenuItem instance for the page if it's a top-level page. Otherwise, nil.
```
Comment (mokagio) [inline WordPress/Classes/Services/MenusService.h:77]: Nitpick. There docs in the previous method has `@param`s. The new one doesn't. One could see this as a regression.

At the same time, I personally prefer this style of documentation, which I interpret as "only document was is not obvious."

What do you think? Is it worth using this as an example to start a team-wide conversation to define a standard?

File: WordPress/Classes/Services/MenusService.m [hunk 2]
```diff
@@ -9,8 +9,6 @@
 #import "WordPress-Swift.h"
 @import WordPressKit;
 
-NS_ASSUME_NONNULL_BEGIN
```
Comment (mokagio) [inline WordPress/Classes/Services/MenusService.m:12]: Why was this removed? I'm guessing because it's not necessary in `.m` files?

File: WordPress/Classes/Services/MenusService.m [hunk 3]
```diff
@@ -161,47 +159,21 @@ - (void)deleteMenu:(Menu *)menu
...
-                                 [[ContextManager sharedInstance] saveContext:self.managedObjectContext withCompletionBlock:^{
-                                     if (success) {
-                                         success(items);
-                                     }
-                                 } onQueue:dispatch_get_main_queue()];
-                             }];
-                         }
-                         failure:failure];
+- (MenuItem *)createItemWithPageID:(NSManagedObjectID *)pageObjectID inContext:(NSManagedObjectContext *)context {
+    Page *page = [context existingObjectWithID:pageObjectID error:nil];
```
Comment (mokagio) [inline WordPress/Classes/Services/MenusService.m:163]: Have you considered passing an error object?

File: WordPress/Classes/ViewRelated/Menus/MenusViewController.m [hunk 4]
```diff
@@ -176,6 +173,15 @@ - (void)viewWillDisappear:(BOOL)animated
     [[NSNotificationCenter defaultCenter] removeObserver:self];
 }
 
+- (void)viewDidDisappear:(BOOL)animated
+{
+    [super viewDidDisappear:animated];
+
+    if (self.navigationController == nil && self.fetchAllPagesCancellationHandler != nil) {
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Menus/MenusViewController.m:180]: Why does the code check for the `navigationController` value?

File: WordPress/Classes/ViewRelated/Menus/MenusViewController.swift [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+        Task { [weak self] in
+            let allPages: [TaggedManagedObjectID<Page>]
+            do {
+                allPages = try await fetchAllPagesTask.value
+            } catch {
+                failure(error)
+                return
+            }
+
+            guard let menusService = self?.menusService else { return }
```
Comment (mokagio) [inline WordPress/Classes/ViewRelated/Menus/MenusViewController.swift:23]: I was going to suggest moving the check at the start of the `Task` to exit early. But maybe it's best to check if `self` is still available after the `fetchAllPagesTask` completed, in case the ViewController (`self`) was deallocated in the meantime. Is this the reason for the check being at this point?

File: WordPress/WordPressTest/PostRepositoryTests.swift [hunk 6]
```diff
@@ -241,6 +241,65 @@ class PostRepositoryTests: CoreDataTestCase {
...
+            task.cancel()
+        }
+
+        do {
+            let _ = try await task.value
+        } catch is CancellationError {
+            cancelled.fulfill()
+        }
+
+        await fulfillment(of: [cancelled], timeout: 0.3)
```
Comment (mokagio) [inline WordPress/WordPressTest/PostRepositoryTests.swift:312]: This is a neat test 🤩

File: WordPress/WordPressTest/PostRepositoryTests.swift [hunk 7]
```diff
@@ -241,6 +241,65 @@ class PostRepositoryTests: CoreDataTestCase {
...
+            try (1...10).map {
+                let post = try XCTUnwrap(RemotePost(siteID: NSNumber(value: $0), status: "publish", title: "Post: Test", content: "This is a test post"))
+                post.type = "page"
+                return post
+            },
+        ]
+
+        let pages = try await repository.fetchAllPages(statuses: [.publish], in: blogID).value
+        XCTAssertEqual(pages.count, 110)
+    }
```
Comment (mokagio) [inline WordPress/WordPressTest/PostRepositoryTests.swift:288]: Have you considered a test to explicitly check that no more requests are made after an empty or < page size response has been received?

🤔 I guess the fact that `await` triggers sort of guarantees this, but I don't know... I feel like it would be "nice" to test it explicitly. 

_Not a must_. If I had some time, I'd see if I could change the source code to make these tests pass with more requests, but I don't think I'll get to it any time soon.

**Review by mokagio — APPROVED** [review]
I'm approving to unblock but I haven't had the time to manually test. 

To be clear, that's on me. I'll try to come back to this, but wanted to unblock just in case.

File: WordPress/Classes/Services/MenusService.h (hunk 1 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/MenusService.h:77]: > "only document was is not obvious."

This is exactly what I was thinking. I don't think those param docs in the original function is really useful.

File: WordPress/Classes/Services/MenusService.m (hunk 2 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/MenusService.m:12]: Indeed.  No benefit whatsoever in using it in .m files.

File: WordPress/Classes/Services/MenusService.m (hunk 3 above)
Comment (crazytonyli) [reply WordPress/Classes/Services/MenusService.m:163]: That didn't cross my mind. That's a good idea though: turning this Objective-C function to a throwing Swift function.

But unfortunately, after giving it go, I noticed Swift turns the function to `createItem() throws -> MenuItem`, but I want an optional return value: `createItem() throws -> MenuItem?`. I think I'll keep it as it is, because returning an non optional MenuItem is a lie.

File: WordPress/Classes/ViewRelated/Menus/MenusViewController.m (hunk 4 above)
Comment (crazytonyli) [reply WordPress/Classes/ViewRelated/Menus/MenusViewController.m:180]: To make sure we only cancel the fetching when user taps the Back button. `viewDidDisappear` is also called when a new view controller is pushed into the stack. In which case, we'd like the pages fetching to continue.

File: WordPress/WordPressTest/PostRepositoryTests.swift (hunk 7 above)
Comment (crazytonyli) [reply WordPress/WordPressTest/PostRepositoryTests.swift:288]: > explicitly check that no more requests are made after an empty or < page size response has been received?

I think that's already covered here. If there are more requests fired, then the fake `PostServiceRemote` API response would make sure either

- an extra 100 or 10 page instances are returned to the `PostRepository` fucntion. Or,
- a failure is returned.

That means the final total pages should be more than 110 and breaks the assertion or throw an error. Given the test passes, we should(?) be fairly certain that there no unnecessary requests are fired.

I guess that's not entirely true. Because if the `fetchAllPages` is implemented in a way that removes duplication or swallows error, then the test would still pass when there _are_ unnecessary requests.

I guess we could to add a `XCTFail` to the error case to be really really sure.

https://github.com/wordpress-mobile/WordPress-iOS/blob/5339b86f6ae66cc608ff3a466c8a6b53a0dbd487/WordPress/WordPressTest/PostRepositoryTests.swift#L350-L354

Comment (crazytonyli) [reply WordPress/WordPressTest/PostRepositoryTests.swift:288]: I have added another test in https://github.com/wordpress-mobile/WordPress-iOS/pull/21949/commits/ed781a5a1bb52c36bf0eeeceb040a719c05b2ae1 to ensure when there is an HTTP API error, the fetchAllPages should throw, which means the error is not swallowed and at the same time ensure no extra requests are fired after an empty or < page size response.
