### PR TITLE
Issues/4200 fix site topics

### LINKED ISSUE #4200: Reader: Browse Sites can show an empty list when there are results
Title has it.  I noticed this while testing #4194.  

I can reproduce when browsing the "Posts I Like" list, but likely can be reproduced with any list or topic. 
Tap the avatar in a post card to browse the related site. The site details screen appears and begins syncing. Syncing ends showing no results. However, if you pull to refresh again the sites posts will be shown when the second sync ends.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #4200 
A site topics constructed from a post was not being saved when it was created. This made it possible for the topic to be discarded when a derived context was reset when merging posts.
There was also a race condition with saving the main context and displaying the no results view.  This patch addresses both issues.

To tests:

Scenario 1:
- Open the reader to any tag or list.
- Tap an avatar to preview the site.
- Ensure the site details screen displays the posts it syncs.

Scenario 2: 
- Open notifications
- Tap to preview a site from any follow notification (or notification that supports previewing a site). 
- Ensure the site details screen displays the posts it syncs. 

@jleandroperez may I trouble you for a quick review?

Needs Review : @jleandroperez

### CODE REVIEW

File: WordPress/Classes/Services/ReaderTopicService.m [hunk 1]
```diff
@@ -363,6 +363,10 @@ - (ReaderTopic *)siteTopicForPost:(ReaderPost *)post
     topic.topicDescription = post.blogDescription;
     topic.path = path;
 
+    [self.managedObjectContext performBlockAndWait:^{
```
Comment (jleandroperez) [inline WordPress/Classes/Services/ReaderTopicService.m]: Since few lines above this snippet, we're actually running a fetch request (and inserting an object into the context), i think we either need to wrap up the snippet that calls this method, (or) wrap all of its contents within a performBlockAndWait.

OR we could just get rid of the `performBlockAndWait`, and add an... `NSAssert([NSThread isMainThread], @"")`, and pray for @astralbodies not to notice it!

Comment (jleandroperez) [inline WordPress/Classes/Services/ReaderTopicService.m]: Huh. I shouldn't have used his handle. Thank you, mention notifications, i really appreciate that!

**Comment by jleandroperez** [comment]
@aerych one minor comment added, which doesn't really affect the (current) behavior.

Looking great on my side! Feel free to :shipit:!

File: WordPress/Classes/Services/ReaderTopicService.m (hunk 1 above)
Comment (aerych) [inline WordPress/Classes/Services/ReaderTopicService.m]: I'm wrestling a bit with this. I think wrapping the insides of the method in a performBlockAndWait would be weird since we're returning a value. It also seems bad to make the caller responsible for only ever calling the method with a perform block.
I think what we need to do is refactor to use performBlockAndWait internally, and instead of returning a topic, use a completion handler on the main queue.  But maybe for the purpose of this patch we use the NSAssert? 
Reader topics are being violently refactored very soon so I'm not too keen on doing too much more here. 
Thoughts?

**Comment by aerych** [comment]
Thanks @jleandroperez!
