### PR TITLE
Extensions: fixed site list ordering

### LINKED ISSUE #8645: Extensions: Change the order of the sites
In the share draft extension, the site list is ordered with the primary site at top, then alphabetically (A-Z):

screen shot 2018-02-19 at 8 07 52 am

Change this order to:

1. primary site at top (pre-selected)
2. order of recency
3. alphabetically (A-Z)

In short, mimic the site list ordering in WPiOS.

### PR DESCRIPTION
**Pull request by bummytime**
Fixes #8645 

This PR fixes the site list order in the draft/share extension based on recently used sites in WPiOS. The order of the list should be as follows:

1. Primary site (always displayed even if hidden in WPiOS)
2. Last 3 recently used sites (Can be 0-3 sites)
3. Remaining visible sites in alpha order (excluding sites from 1 and 2 ☝️ )

## Testing

While testing this, you will probably want to log into WPiOS using a few test accounts (e.g. account with many sites, a single site, a few sites, etc). Basic procedure:

1. With a fresh install of WPiOS, log into the main app.
2. Open Safari and share a page using the app extension
3. On the site list screen, verify the primary site is at the top (pre-selected) and the remaining sites are below it in alphabetical order.
4. Cancel out of the share ext
5. Go back to WPiOS and open the site info page for 1 to 3 different sites
6. Re-open Safari and share a page using the app extension
7. On the site list screen, verify:
  * the primary site is at the top (pre-selected), 
  * the 1 to 3 recently used sites from step 5 are displayed
  * the remaining sites are below the recent sites in alphabetical order

Test this out in both the draft and share extensions. You may also want to verify the proper categories appear for the selected site and that you can save/publish the post with the selected site.

@ctarda would you mind taking a peek at this? Thanks! 😄

### CODE REVIEW

**Comment by ctarda** [comment]
It definitely works as advertised on the share extension:

simulator screen shot - iphone 8 - 2018-06-04 at 17 31 23

In the screenshot, the selected blog is my primary site, blogs two and three are the two last blogs that I selected in the main app's list of sites.

However, and I don't know if this is the expected behaviour, the list of blogs on the main app is not sorted anymore alphabetically:
simulator screen shot - iphone 8 - 2018-06-04 at 17 28 53

And the primary blog is not the first one on the list anymore. That seems a bit odd to me, but I don't know if that's the expected behaviour.

File: WordPress/WordPressShareExtension/AppExtensionsService.swift [hunk 1]
```diff
@@ -91,9 +91,24 @@ extension AppExtensionsService {
...
+            let recentSites = recentSiteURLs.compactMap({ url in
+                return visibleSitesSansPrimary.first(where: { $0.url == url })
+            })
+
+            // Everything else
+            let remainingSites = visibleSitesSansPrimary.filter({ site in
+                !recentSites.contains(site)
+            })
+
+            let combinedSiteList = primarySites + recentSites + remainingSites
```
Comment (ctarda) [inline WordPress/WordPressShareExtension/AppExtensionsService.swift]: Would it make sense to encapsulate any of those three blocks in a separate method, so that this line would read similar to:

``
let primarySites = visiblePrimarySites()
let combinedSiteList = primarySites + recentSites(primarySites) + remainingSites(primarySites)
``

Would that make this method easier to understand that way?. If we needed to dig into the details of how primarySites (or recent sites, or remaining sites) are obtained we can dig into the specific method.

**Comment by ctarda** [comment]
Aaaand I just noticed that's precisely the way it works. 😊

File: WordPress/WordPressShareExtension/AppExtensionsService.swift (hunk 1 above)
Comment (bummytime) [reply WordPress/WordPressShareExtension/AppExtensionsService.swift]: Makes sense to me @ctarda! I will do that.
