### PR TITLE
Fixes Notification Filters Logic

### LINKED ISSUE #4986: Notifications: after clicking Unread tab in notifications view, can't access any other notifications
### Expected behavior
I'd expect to be able to switch back to All, Comments, Likes, etc — via the tabs at the top of notifications view.

### Actual behavior
After clicking the Unread tab once, I lose the tabs and can't see anything besides "No unread notifications" warning.
img_4501

### Steps to reproduce the behavior
Update to 6.1 beta, and click post a new comment on a test blog with a different user. Open iOS app, and click the notifications icon in bottom right (should show an orange dot).

Then, click the Unread tab in notifications view.

##### Tested on [device], iOS [version]
iPhone 6+, iOS 9.2.1

WordPress app version 6.1.0.20160318

##### Misc

Note: I also sent in a lookback with a video.

### PR DESCRIPTION
**Pull request by jleandroperez**
Fixes #4986

#### Scenario: WordPress.com Account
1. Log into a WordPress.com account with few notifications (i can hand over a test account via DM!)
2. Tap over the Notifications tab
3. Ensure that at least one of the filters produces zero results, and tap on it

As a result, the Notification Filters should remain visible.

Needs review: @frosty 
Thanks in advance James!

Props to @lancewillett for spotting this one + reporting it!

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m [hunk 1]
```diff
@@ -944,20 +951,20 @@ - (NSString *)noResultsTitleText
 - (NSString *)noResultsMessageText
 {
     NSString *jetapackMessage   = NSLocalizedString(@"Jetpack supercharges your self-hosted WordPress site.", @"Notifications message displayed when a self-hosted user is not connected to Jetpack");
```
Comment (frosty) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m]: I know you didn't change this as part of this PR, but small typo here - should be `jetpackMessage` :)

**Comment by frosty** [comment]
Other than the small note above, this works for me – fixes the problem on my test account.

:shipit:!

File: WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m (hunk 1 above)
Comment (jleandroperez) [inline WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.m]: Thanks for spotting that one!

**Comment by jleandroperez** [comment]
Thank you @frosty !!
