### PR TITLE
Likes lists: show specific error messages when fetching fails

### LINKED ISSUE #17009: Notification > Likes list: improve error messaging
### Expected behavior
When fetching Likes fails, the displayed error gives some indication why.

### Actual behavior
When fetching Likes fails, the displayed error message is generic:

Screen Shot 2021-08-11 at 12 56 41 PM

### Steps to reproduce the behavior
- Go to Notifications > Likes.
- Select a notification that will fail to fetch Likes.
  - The scenario that discovered this:
    -  Comment on a P2 post where you are not a member of the P2 (i.e. you haven't tapped `Join this space`)
    - Get likes on that comment.
    - In the app, select the Like Notification for that comment.
    - The Likes fetching fails and the error view is displayed.

### Additional Information

Per the API documentation, possible Comment Likes errors are:

comment_likes

The Likes list is also shown from Reader post details. We should implement the same error handling for Post Likes as well. Post errors are the same with one extra:

post_likes

### PR DESCRIPTION
**Pull request by ScoutHarris**
Fixes #17009

This changes the Likes lists to show the API response error message when fetching likes fails so it's clear(er) to the user why it failed. 
- The error title is now `Error loading likes` (instead of `Oops`).
- The error subtitle is the API response error message.
- The error strings are now provided by `LikesListController`, instead of duplicated in `NotificationDetailsViewController` and `ReaderDetailLikesListController`.

To test:

Refer to https://github.com/wordpress-mobile/WordPress-iOS/issues/17009 for the specific error messages available for Comments and Posts likes. Since they're all displayed the same way in app, I don't think it's necessary to test _every_ case. Below are steps for two:
- `User cannot access this private blog`
- `Unknown comment`/`Unknown post`
---

`User cannot access this private blog`:

Notifications:
- In the app, find a Like notification (either Post or Comment) and verify you can view the likes list.
- Remove yourself as a member of that P2 with the Automattic Blogs tool.
- In the app, try to view the Likes list again. 
- Verify the error message is displayed.

Reader Post:
- In the app, find a Reader post with likes and verify you can view the likes list.
- Remove yourself as a member of that P2 with the Automattic Blogs tool.
- In the app, try to view the Likes list again. 
- Verify the error message is displayed.

| Notification | Reader Post |
|--------|-------|
| notif_likes | reader_likes |

---

`Unknown comment`/`Unknown post`:
- In the [`fetchLikes`](https://github.com/wordpress-mobile/WordPress-iOS/blob/2ee057815aa56eac808e6f318aa65f6bf8443b78/WordPress/Classes/ViewRelated/Likes/LikesListController.swift#L254) method, change `postID` and `commentID` to a bogus number.
```
postService.getLikesFor(postID: 999,
...
commentService.getLikesFor(commentID: 999,
```

- Attempt to view the Likes list for:
  - Comment like notification.
  - Post like notification.
  - Reader post.
- Verify the error message is displayed.

| Comment like | Post like | Reader Post likes |
|--------|-------|-------|
| notif_invalid_comment_id | notif_invalid_post_id | reader_invalid_post_id |
---

## Regression Notes
1. Potential unintended areas of impact
Shouldn't be any.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested Likes lists in notifications and reader posts to ensure errors are displayed as expected.

3. What automated tests I added (or what prevented me from doing so)
N/A. 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/Classes/ViewRelated/Likes/LikesListController.swift [hunk 1]
```diff
@@ -190,9 +193,23 @@ class LikesListController: NSObject {
...
+
+            let errorMessage: String? = {
+                // Get error message from API response if provided.
+                if let error = error,
+                   let message = (error as NSError).userInfo[WordPressComRestApi.ErrorKeyErrorMessage] as? String,
+                   !message.isEmpty {
+                    return message
+                }
+                return nil
+            }()
```
Comment (aerych) [inline WordPress/Classes/ViewRelated/Likes/LikesListController.swift:209]: Nice.

**Review by aerych — APPROVED** [review]
Howdy @ScoutHarris 👋 
Changes look good to me!  Tested as described and confirmed the updated error messages. 
:shipit: from me. :)

**Comment by ScoutHarris** [comment]
Thanks @aerych !
